### ISSUE TITLE
Run demo cluster with docker-compose failed

### ISSUE THREAD

**Issue by cd1989** [zalando/patroni#1001]
With the master branch, I failed to run the provided demo example, with following error logs:

```
2019-03-11 06:19:50,784 INFO: Failed to import patroni.dcs.consul
2019-03-11 06:19:50,856 INFO: Selected new etcd server http://etcd3:2379
2019-03-11 06:19:50,867 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a7ba43cc0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /v2/machines
2019-03-11 06:19:50,871 ERROR: Failed to get list of machines from http://etcd3:2379/v2: MaxRetryError("HTTPConnectionPool(host='etcd3', port=2379): Max retries exceeded with url: /v2/machines (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a7ba436d8>: Failed to establish a new connection: [Errno 111] Connection refused',))",)
2019-03-11 06:19:50,871 INFO: Retrying on http://etcd1:2379
2019-03-11 06:19:50,878 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a7b4fb4e0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /v2/machines
2019-03-11 06:19:50,881 ERROR: Failed to get list of machines from http://etcd1:2379/v2: MaxRetryError("HTTPConnectionPool(host='etcd1', port=2379): Max retries exceeded with url: /v2/machines (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a7b4fb5c0>: Failed to establish a new connection: [Errno 111] Connection refused',))",)
2019-03-11 06:19:50,882 INFO: Retrying on http://etcd2:2379
2019-03-11 06:19:52,237 ERROR: Failed to get list of machines from http://etcd2:2379/v2: EtcdException(None,)
2019-03-11 06:19:52,237 INFO: waiting on etcd
2019-03-11 06:19:57,243 INFO: Selected new etcd server http://etcd3:2379
2019-03-11 06:19:57,265 INFO: Lock owner: None; I am patroni2
2019-03-11 06:19:57,287 INFO: trying to bootstrap a new cluster
2019-03-11 06:19:57,293 ERROR: Exception during execution of long running task bootstrap
Traceback (most recent call last):
  File "/patroni/async_executor.py", line 97, in run
    wakeup = func(*args) if args else func()
  File "/patroni/postgresql.py", line 1680, in bootstrap
    return do_initialize(config) and self.write_pg_hba(pg_hba) and self.save_configuration_files() \
  File "/patroni/postgresql.py", line 558, in _initdb
    ret = self.pg_ctl('initdb', *options)
  File "/patroni/postgresql.py", line 277, in pg_ctl
    return subprocess.call(pg_ctl + ['-D', self._data_dir] + list(args), **kwargs) == 0
  File "/usr/lib/python3.5/subprocess.py", line 247, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'pg_ctl'
2019-03-11 06:19:57,302 INFO: removing initialize key after failed attempt to bootstrap the cluster
2019-03-11 06:19:57,759 INFO: Lock owner: None; I am patroni2
Traceback (most recent call last):
  File "/patroni.py", line 6, in <module>
    main()
  File "/patroni/__init__.py", line 182, in main
    return patroni_main()
  File "/patroni/__init__.py", line 148, in patroni_main
    patroni.run()
  File "/patroni/__init__.py", line 119, in run
    logger.info(self.ha.run_cycle())
  File "/patroni/ha.py", line 1305, in run_cycle
    info = self._run_cycle()
  File "/patroni/ha.py", line 1213, in _run_cycle
    return self.post_bootstrap()
  File "/patroni/ha.py", line 1109, in post_bootstrap
    self.cancel_initialization()
  File "/patroni/ha.py", line 1104, in cancel_initialization
    raise PatroniException('Failed to bootstrap cluster')
patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'
```

State of all containers:

```
$ docker ps -a
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                     PORTS                              NAMES
9a8a09533519        zer0one/patroni:v1.5.6   "/bin/sh /entrypoint…"   2 minutes ago       Exited (0) 3 minutes ago                                      demo-patroni1
24368088fbe3        zer0one/patroni:v1.5.6   "/bin/sh /entrypoint…"   2 minutes ago       Exited (0) 3 minutes ago                                      demo-patroni2
8cc4e1b3e49c        zer0one/patroni:v1.5.6   "/bin/sh /entrypoint…"   2 minutes ago       Up 3 minutes                                                  demo-etcd1
9286714f1e02        zer0one/patroni:v1.5.6   "/bin/sh /entrypoint…"   2 minutes ago       Up 3 minutes                                                  demo-etcd3
2c55b9bc1f94        zer0one/patroni:v1.5.6   "/bin/sh /entrypoint…"   2 minutes ago       Up 3 minutes                                                  demo-etcd2
b8dcd3768026        zer0one/patroni:v1.5.6   "/bin/sh /entrypoint…"   2 minutes ago       Exited (0) 3 minutes ago                                      demo-patroni3
638db75cdf17        zer0one/patroni:v1.5.6   "/bin/sh /entrypoint…"   2 minutes ago       Up 3 minutes               0.0.0.0:5000-5001->5000-5001/tcp   demo-haproxy
```

My env is Mac OS.

**Comment by CyberDem0n** [comment]
Have you build the new image?

The provided example is 100% working on Linux and Mac.

**Comment by cd1989** [comment]
Yes, I have built the image.
