### ISSUE TITLE
Patroni shutdown database when old consul leader is unavailable 

### ISSUE THREAD

**Issue by ev1k** [zalando/patroni#1003]
Hi! 
The problem I see when  we change consul cluster leader and stop it.

Is it  possible that we are doing something wrong in the configuration or is it a bug?

patroni: 1.5.5
postgresql: 11.2
dcs: consul

Steps to reproduce: 
- change leader in Consul cluster (consul leave)

Patroni logs:
```Mar 16 08:45:44 postgresql patroni[2828]: 2019-03-16 08:45:44,685 ERROR: get_cluster
Mar 16 08:45:44 postgresql patroni[2828]: 2019-03-16 08:45:44,685 ERROR: get_cluster
Mar 16 08:45:44 postgresql patroni[2828]: Traceback (most recent call last):
Mar 16 08:45:44 postgresql patroni[2828]:   File "/usr/local/lib/python2.7/dist-packages/patroni/dcs/consul.py", line 294, in _load_cluster
Mar 16 08:45:44 postgresql patroni[2828]:     _, results = self.retry(self._client.kv.get, path, recurse=True)
Mar 16 08:45:44 postgresql patroni[2828]:   File "/usr/local/lib/python2.7/dist-packages/patroni/dcs/consul.py", line 225, in retry
Mar 16 08:45:44 postgresql patroni[2828]:     return self._retry.copy()(*args, **kwargs)
Mar 16 08:45:44 postgresql patroni[2828]:   File "/usr/local/lib/python2.7/dist-packages/patroni/utils.py", line 263, in __call__
Mar 16 08:45:44 postgresql patroni[2828]:     raise RetryFailedError("Exceeded retry deadline")
Mar 16 08:45:44 postgresql patroni[2828]: RetryFailedError: 'Exceeded retry deadline'
Mar 16 08:45:44 postgresql patroni[2828]: 2019-03-16 08:45:44,688 ERROR: Error communicating with DCS

Mar 16 08:46:03 postgresql patroni[2828]: 2019-03-16 08:46:03.820 UTC [2856] LOG:  database system is shut down
Mar 16 08:46:03 postgresql patroni[2828]: 2019-03-16 08:46:03,865 INFO: closed patroni connection to the postgresql cluster
Mar 16 08:46:03 postgresql patroni[2828]: 2019-03-16 08:46:03,899 INFO: postmaster pid=8836
Mar 16 08:46:03 postgresql patroni[2828]: localhost:5432 - no response
Mar 16 08:46:03 postgresql patroni[2828]: 2019-03-16 08:46:03.933 UTC [8836] LOG:  listening on IPv4 address "0.0.0.0", port 5432
Mar 16 08:46:03 postgresql patroni[2828]: 2019-03-16 08:46:03.934 UTC [8836] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
Mar 16 08:46:04 postgresql patroni[2828]: 2019-03-16 08:46:04.060 UTC [8838] LOG:  database system was shut down at 2019-03-16 08:46:03 UTC
Mar 16 08:46:04 postgresql patroni[2828]: 2019-03-16 08:46:04.061 UTC [8838] WARNING:  recovery command file "recovery.conf" specified neither primary_conninfo nor restore_command
Mar 16 08:46:04 postgresql patroni[2828]: 2019-03-16 08:46:04.061 UTC [8838] HINT:  The database server will regularly poll the pg_wal subdirectory to check for files placed there.
Mar 16 08:46:04 postgresql patroni[2828]: 2019-03-16 08:46:04.061 UTC [8838] LOG:  entering standby mode
Mar 16 08:46:04 postgresql patroni[2828]: 2019-03-16 08:46:04.070 UTC [8838] LOG:  consistent recovery state reached at 842/C4000098
Mar 16 08:46:04 postgresql patroni[2828]: 2019-03-16 08:46:04.070 UTC [8838] LOG:  invalid record length at 842/C4000098: wanted 24, got 0
Mar 16 08:46:04 postgresql patroni[2828]: 2019-03-16 08:46:04.071 UTC [8836] LOG:  database system is ready to accept read only connections
Mar 16 08:46:04 postgresql patroni[2828]: localhost:5432 - accepting connections
Mar 16 08:46:04 postgresql patroni[2828]: localhost:5432 - accepting connections
Mar 16 08:46:04 postgresql patroni[2828]: 2019-03-16 08:46:04,934 INFO: demoted self because DCS is not accessible and i was a leader
Mar 16 08:46:04 postgresql patroni[2828]: 2019-03-16 08:46:04,936 WARNING: Loop time exceeded, rescheduling immediately.
Mar 16 08:46:04 postgresql patroni[2828]: 2019-03-16 08:46:04,957 INFO: Lock owner: postgresql; I am postgresql
Mar 16 08:46:04 postgresql patroni[2828]: 2019-03-16 08:46:04,958 INFO: establishing a new patroni connection to the postgres cluster
Mar 16 08:46:05 postgresql patroni[2828]: 2019-03-16 08:46:05,017 INFO: promoted self to leader because i had the session lock
Mar 16 08:46:05 postgresql patroni[2828]: server promoting
Mar 16 08:46:05 postgresql patroni[2828]: 2019-03-16 08:46:05.021 UTC [8838] LOG:  received promote request
Mar 16 08:46:05 postgresql patroni[2828]: 2019-03-16 08:46:05.021 UTC [8838] LOG:  redo is not required
Mar 16 08:46:05 postgresql patroni[2828]: 2019-03-16 08:46:05,021 INFO: cleared rewind state after becoming the leader
Mar 16 08:46:05 postgresql patroni[2828]: 2019-03-16 08:46:05.025 UTC [8838] LOG:  selected new timeline ID: 3
Mar 16 08:46:05 postgresql patroni[2828]: 2019-03-16 08:46:05.061 UTC [8838] LOG:  archive recovery complete
Mar 16 08:46:05 postgresql patroni[2828]: 2019-03-16 08:46:05.126 UTC [8839] LOG:  checkpoint starting: force
Mar 16 08:46:05 postgresql patroni[2828]: 2019-03-16 08:46:05.129 UTC [8836] LOG:  database system is ready to accept connections
Mar 16 08:46:05 postgresql patroni[2828]: 2019-03-16 08:46:05.153 UTC [8839] LOG:  checkpoint complete: wrote 0 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.021 s, sync=0.000 s, total=0.027 s; sync files=0, longest=0.000 s, average=0.000 s; distance=0 kB, estimate=0 kB
Mar 16 08:46:06 postgresql patroni[2828]: 2019-03-16 08:46:06,938 INFO: Lock owner: postgresql; I am postgresql

**Comment by CyberDem0n** [comment]
Could you share patroni config? Especially the `consul` section.

**Comment by ev1k** [comment]
Yes. 
I looked at the code and I think when the consul cluster changes the leader, it has a lock for 1-2 seconds. My cluster patroni send state to the consul every 2 seconds. 


My config template
```name: {{ servername }}
scope: {{ cluster_name }}

consul:
  host: {{ consul_host }}
  scheme: https
  verify: true
  cacert: {{ consul_cacert }}
  cert: {{ consul_cert }}
  key: {{ consul_key }}

restapi:
  listen: 0.0.0.0:8008
  connect_address: {{ ansible_default_ipv4.address }}:8008
  authentication:
    username: admin
    password: {{ patroni_password }}

bootstrap:
  dcs:
    ttl: 20
    loop_wait: 2
    retry_timeout: 2
    maximum_lag_on_failover: 1048576 # 1 megabyte in bytes
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        archive_mode: "on"
        wal_level: replica
        archive_command: cd .
        max_wal_senders: 10
        wal_keep_segments: 128
        archive_timeout: 1800s
        max_replication_slots: 5
        hot_standby: "on"
        wal_log_hints: "on"

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - local all postgres peer
  - local all all peer
  - host  all all 127.0.0.1/32 md5
  - host  all all 172.17.0.0/16 md5
  - host  replication rep 127.0.0.1/32 md5
  - host replication {{ repluser }} {{ networkaddress }} md5
  - host all all {{ networkaddress }} md5

postgresql:
  listen: 0.0.0.0:5432
  connect_address: {{ ansible_default_ipv4.address }}:5432
  data_dir: /var/lib/postgresql/{{ pgversion }}/main
  bin_dir: /usr/lib/postgresql/{{ pgversion }}/bin/
  config_dir: /etc/postgresql/{{ pgversion }}/main
  pg_rewind:
    username: postgres
    password: {{ postgres_password }}
  pg_hba:
  - local all postgres peer
  - local all all peer
  - host  all all 127.0.0.1/32 md5
  - host  all all 172.17.0.0/16 md5
  - host  replication rep 127.0.0.1/32 md5
  - host replication {{ repluser }} {{ networkaddress }} md5
  - host all all {{ networkaddress }} md5
  replication:
    username: {{ repluser }}
    password: {{ replpass }}
    network:  {{ networkaddress }}
  superuser:
    username: postgres
    password: {{ postgres_password }}

watchdog:
  mode: automatic # Allowed values: off, automatic, required
  device: /dev/watchdog
  safety_margin: -1

**Comment by CyberDem0n** [comment]
Hi @ev1k,

I would really recommend you to put `consul.checks: []` into your config, otherwise consul expires all sessions associated with the agent which is disconnected from the server for 1-2 seconds. 

Another problem is, you set `retry_timeout` value to 2 seconds, which is way too small. Basically Patroni will demote the current master and start it read-only if it wasn't able to update the leader key during 2 seconds.

The appropriate value of `retry_timeout` for you would be 8 or 9, it will make Patroni more resilient to short network problems.

**Comment by CyberDem0n** [comment]
You should read "network problems" as some troubles with communication with consul. Reasons could be absolutely different. Internal leader elections in the consul cluster is one of such reasons. Since consul implements raft protocol I would expect that such leader elections taking about 2 seconds.

**Comment by ev1k** [comment]
Hi @CyberDem0n,

Thank you for the response and recommendations to improve our configs. I've finished testing new configs and look the new issue. 

Steps to reproduce:

- consul cluster has 3 nodes
- leave  anyone node from the cluster
- stop consul process
- start consul process
- add this node to the cluster back
-  repeat steps 2-5 for every node in the cluster

When you stop the last node ( 2 pervious nodes in the claster again) patroni shutdown database
```Apr 10 07:54:44 postgresql01 patroni[30263]: 2019-04-10 07:54:44,701 INFO: Lock owner: postgresql01; I am postgresql01
Apr 10 07:54:44 postgresql01 patroni[30263]: 2019-04-10 07:54:44,703 INFO: no action.  i am the leader with the lock
Apr 10 07:54:56 postgresql01 patroni[30263]: 2019-04-10 07:54:56,713 ERROR: refresh_session
Apr 10 07:54:56 postgresql01 patroni[30263]: Traceback (most recent call last):
Apr 10 07:54:56 postgresql01 patroni[30263]:   File "/usr/local/lib/python2.7/dist-packages/patroni/dcs/consul.py", line 279, in refresh_session
Apr 10 07:54:56 postgresql01 patroni[30263]:     return self.retry(self._do_refresh_session)
Apr 10 07:54:56 postgresql01 patroni[30263]:   File "/usr/local/lib/python2.7/dist-packages/patroni/dcs/consul.py", line 225, in retry
Apr 10 07:54:56 postgresql01 patroni[30263]:     return self._retry.copy()(*args, **kwargs)
Apr 10 07:54:56 postgresql01 patroni[30263]:   File "/usr/local/lib/python2.7/dist-packages/patroni/utils.py", line 263, in __call__
Apr 10 07:54:56 postgresql01 patroni[30263]:     raise RetryFailedError("Exceeded retry deadline")
Apr 10 07:54:56 postgresql01 patroni[30263]: RetryFailedError: 'Exceeded retry deadline'
Apr 10 07:54:56 postgresql01 patroni[30263]: 2019-04-10 07:54:56,714 ERROR: Error communicating with DCS
Apr 10 07:54:56 postgresql01 patroni[30263]: 2019-04-10 07:54:56.723 UTC [30294] LOG:  received fast shutdown request
Apr 10 07:54:56 postgresql01 patroni[30263]: 2019-04-10 07:54:56.723 UTC [30294] LOG:  aborting any active transactions
Apr 10 07:54:56 postgresql01 patroni[30263]: 2019-04-10 07:54:56.724 UTC [30319] user@postgresql01 FATAL:  terminating connection due to administrator command
Apr 10 07:54:56 postgresql01 patroni[30263]: 2019-04-10 07:54:56.724 UTC [30316] postgres@postgres FATAL:  terminating connection due to administrator command
Apr 10 07:54:56 postgresql01 patroni[30263]: 2019-04-10 07:54:56.726 UTC [30345] LOG:  autovacuum launcher shutting down
Apr 10 07:54:56 postgresql01 patroni[30263]: 2019-04-10 07:54:56.730 UTC [30306] LOG:  shutting down
Apr 10 07:54:56 postgresql01 patroni[30263]: 2019-04-10 07:54:56.957 UTC [30294] LOG:  database system is shut down
Apr 10 07:54:56 postgresql01 patroni[30263]: 2019-04-10 07:54:56,981 INFO: closed patroni connection to the postgresql cluster
Apr 10 07:54:57 postgresql01 patroni[30263]: 2019-04-10 07:54:57,001 INFO: postmaster pid=30524
Apr 10 07:54:57 postgresql01 patroni[30263]: localhost:5432 - no response
Apr 10 07:54:57 postgresql01 patroni[30263]: 2019-04-10 07:54:57.084 UTC [30526] LOG:  database system was shut down at 2019-04-10 07:54:56 UTC
Apr 10 07:54:57 postgresql01 patroni[30263]: 2019-04-10 07:54:57.084 UTC [30526] WARNING:  recovery command file "recovery.conf" specified neither primary_conninfo nor restore_command
Apr 10 07:54:57 postgresql01 patroni[30263]: 2019-04-10 07:54:57.084 UTC [30526] HINT:  The database server will regularly poll the pg_xlog subdirectory to check for files placed there.
Apr 10 07:54:57 postgresql01 patroni[30263]: 2019-04-10 07:54:57.084 UTC [30526] LOG:  entering standby mode
Apr 10 07:54:57 postgresql01 patroni[30263]: 2019-04-10 07:54:57.090 UTC [30526] LOG:  consistent recovery state reached at E/7E000098
Apr 10 07:54:57 postgresql01 patroni[30263]: 2019-04-10 07:54:57.090 UTC [30526] LOG:  invalid record length at E/7E000098: wanted 24, got 0
Apr 10 07:54:57 postgresql01 patroni[30263]: 2019-04-10 07:54:57.091 UTC [30524] LOG:  database system is ready to accept read only connections
Apr 10 07:54:58 postgresql01 patroni[30263]: localhost:5432 - accepting connections
Apr 10 07:54:58 postgresql01 patroni[30263]: localhost:5432 - accepting connections
Apr 10 07:54:58 postgresql01 patroni[30263]: 2019-04-10 07:54:58,037 INFO: demoted self because DCS is not accessible and i was a leader
```

Do you have any ideas?

**Comment by CyberDem0n** [comment]
Well, it failed to renew the sessions during `retry_timeout` seconds and therefore restarted postgres in read-only because it can't determine its state.

What are the values of ttl, loop_wait, and retry_timeout?
You posted to a few log lines, so I can't even guess.
If you changed the `bootstrap` section after the cluster was initialized - that won't work.
The real values are stored in consul and you have to use `patronictl show-config/edit-config` to view/change them.

**Comment by ev1k** [comment]
@CyberDem0n, thank you for the response!

Yes, we use `patronictl edit-config`
```
loop_wait: 2
retry_timeout: 8
```

**Comment by CyberDem0n** [comment]
From the Patroni perspective consul doesn't accept writes.
I could only recommend to look on consul logs in order to figure out why.
