### ISSUE TITLE
Shutting down PostgreSQL may wait indefinitely

### ISSUE THREAD

**Issue by feikesteenbergen** [zalando/patroni#101]
It has happened that PostgreSQL does not shut down when signaled. Patroni then waits indefinitely for postgres to shut down.

It may be a ok idea to do a `shutdown -m immediate` after n minutes if postgres doesn't shutdown.

**Comment by feikesteenbergen** [comment]
3-node cluster, current status:
```
+------------+-------------------------+----------------+--------+------------------------------+-----------+
| Cluster    | Member                  | Host           | Leader |            State             | Lag in MB |
+------------+-------------------------+----------------+--------+------------------------------+-----------+
| feiketest4 | postgresql_032d74312dfa | 172.31.146.188 |        | restart failed (stop failed) |           |
| feiketest4 | postgresql_29959ec893cd | 172.31.129.244 |        | restart failed (stop failed) |           |
| feiketest4 | postgresql_3c990c12f0d5 | 172.31.170.137 |   *    |           running            |     0     |
+------------+-------------------------+----------------+--------+------------------------------+-----------+
```

```
postgres@29959ec893cd:~$ ps auxwww
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
postgres     1  1.4  2.3 704572 23476 ?        Ssl  Nov18  14:19 python /home/postgres/patroni/patroni.py /home/postgres/postgres.yml
postgres    18  0.0  0.1  20000  1260 ?        S    Nov18   0:41 /bin/bash /postgres_ha.sh
postgres  2444  3.0  0.1  19752  1952 ?        Ss   08:07   0:00 bash
postgres  2464  0.0  0.0   5912   612 ?        S    08:07   0:00 sleep 30
postgres  2475  0.0  0.0   5912   616 ?        S    08:07   0:00 sleep 5
postgres  2477  0.0  0.1  17164  1292 ?        R+   08:07   0:00 ps auxwww
postgres  9180  0.0  0.1  19664  1632 ?        S    Nov18   0:02 /bin/bash ./test.sh
postgres 26319  0.7  1.6 249380 16812 ?        S    04:37   1:38 /usr/lib/postgresql/9.4/bin/postgres -D /home/postgres/pgdata/data --listen_addresses=0.0.0.0 --port=5432 --hot_standby=on --ssl=on --wal_keep_segments=8 --wal_level=hot_standby --archive_command=envdir /home/postgres/etc/wal-e.d/env wal-e --aws-instance-profile wal-push "%p" -p 1 --wal_log_hints=on --max_wal_senders=5 --archive_timeout=1800s --archive_mode=on --ssl_cert_file=/home/postgres/dummy.crt --max_replication_slots=5 --ssl_key_file=/home/postgres/dummy.key
postgres 26485  0.0  0.1 249380  1892 ?        Ss   04:37   0:00 postgres: checkpointer process
postgres 26487  0.0  0.1 104492  1704 ?        Ss   04:37   0:00 postgres: stats collector process
postgres 26542 64.0  0.4 261248  5016 ?        Rs   04:37 134:18 postgres: wal receiver process   streaming 1/95000000
```

```
postgres@032d74312dfa:~$ ps auxwww
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
postgres     1  0.7  2.2 704812 22700 ?        Ssl  Nov18   6:44 python /home/postgres/patroni/patroni.py /home/postgres/postgres.yml
postgres    17  0.0  0.1  20000  1252 ?        S    Nov18   0:23 /bin/bash /postgres_ha.sh
postgres  3338  0.1  0.2  19744  2064 ?        Ss   07:58   0:00 bash
postgres  3394  0.0  0.0   5912   612 ?        S    07:58   0:00 sleep 5
postgres  3401  0.0  0.1  17164  1288 ?        R+   07:58   0:00 ps auxwww
postgres  3913  0.0  1.6 249384 16776 ?        S    Nov18   0:17 /usr/lib/postgresql/9.4/bin/postgres -D /home/postgres/pgdata/data --listen_addresses=0.0.0.0 --port=5432 --hot_standby=on --ssl=on --wal_keep_segments=8 --wal_level=hot_standby --archive_command=envdir /home/postgres/etc/wal-e.d/env wal-e --aws-instance-profile wal-push "%p" -p 1 --wal_log_hints=on --max_wal_senders=5 --archive_timeout=1800s --archive_mode=on --ssl_cert_file=/home/postgres/dummy.crt --max_replication_slots=5 --ssl_key_file=/home/postgres/dummy.key
postgres 27452  9.0  0.4 250240  4248 ?        Ss   04:37  18:06 postgres: wal sender process standby 172.31.129.244(44593) streaming 1/95000090
```

Part of the logs, `032d74312dfa` was a master and was triggered with a manual failover

```
Nov 19 04:37:55 ip-172-31-146-188 docker/032d74312dfa[839]: 2015-11-19 04:37:55,216 INFO: no action.  i am the leader with the lock
Nov 19 04:37:55 ip-172-31-146-188 docker/032d74312dfa[839]: 172.31.12.3 - - [19/Nov/2015 04:37:55] "GET /master HTTP/1.1" 200 -
Nov 19 04:37:54 ip-172-31-146-188 docker/032d74312dfa[839]: 172.31.4.166 - - [19/Nov/2015 04:37:54] "GET /master HTTP/1.1" 200 -
Nov 19 04:37:55 ip-172-31-146-188 docker/032d74312dfa[839]: 172.31.14.197 - - [19/Nov/2015 04:37:55] "GET /slave HTTP/1.1" 503 -
Nov 19 04:37:55 ip-172-31-146-188 docker/032d74312dfa[839]: 2015-11-19 04:37:55,206 INFO: Lock owner: postgresql_032d74312dfa; I am postgresql_032d74312dfa
Nov 19 04:37:55 ip-172-31-146-188 docker/032d74312dfa[839]: 2015-11-19 04:37:55,216 INFO: no action.  i am the leader with the lock
Nov 19 04:37:55 ip-172-31-146-188 docker/032d74312dfa[839]: 172.31.12.3 - - [19/Nov/2015 04:37:55] "GET /master HTTP/1.1" 200 -
Nov 19 04:37:56 ip-172-31-146-188 docker/032d74312dfa[839]: 2015-11-19 04:37:56,398 INFO: Got response from postgresql_29959ec893cd http://172.31.129.244:8008/patroni: {"state": "running", "role": "replica", "xlog": {"received_location": 6777999160, "paused": false, "replayed_location": 6777999160}, "postmaster_start_time": "2015-11-19 04:37:08.820 UTC", "tags": {}}
Nov 19 04:37:56 ip-172-31-146-188 docker/032d74312dfa[839]: 2015-11-19 04:37:56,417 INFO: Got response from postgresql_3c990c12f0d5 http://172.31.170.137:8008/patroni: {"state": "running", "role": "replica", "xlog": {"received_location": null, "paused": false, "replayed_location": 6559891456}, "postmaster_start_time": "2015-11-19 04:36:56.249 UTC", "tags": {}}
Nov 19 04:37:56 ip-172-31-146-188 docker/032d74312dfa[839]: 2015-11-19 04:37:56,500 INFO: Lock owner: postgresql_032d74312dfa; I am postgresql_032d74312dfa
Nov 19 04:37:56 ip-172-31-146-188 docker/032d74312dfa[839]: 2015-11-19 04:37:56,551 INFO: Got response from postgresql_3c990c12f0d5 http://172.31.170.137:8008/patroni: {"state": "running", "role": "replica", "xlog": {"received_location": null, "paused": false, "replayed_location": 6559891456}, "postmaster_start_time": "2015-11-19 04:36:56.249 UTC", "tags": {}}
Nov 19 04:37:56 ip-172-31-146-188 docker/032d74312dfa[839]: 2015-11-19 04:37:56,564 INFO: Got response from postgresql_29959ec893cd http://172.31.129.244:8008/patroni: {"state": "running", "role": "replica", "xlog": {"received_location": 6777999160, "paused": false, "replayed_location": 6777999160}, "postmaster_start_time": "2015-11-19 04:37:08.820 UTC", "tags": {}}
Nov 19 04:37:56 ip-172-31-146-188 docker/032d74312dfa[839]: 2015-11-19 04:37:56,602 INFO: manual failover: demoting myself
Nov 19 04:37:56 ip-172-31-146-188 docker/032d74312dfa[839]: 2015-11-19 04:37:56,603 INFO: closed patroni connection to the postgresql cluster
Nov 19 04:37:56 ip-172-31-146-188 docker/032d74312dfa[839]: LOG:  received fast shutdown request
Nov 19 04:37:56 ip-172-31-146-188 docker/032d74312dfa[839]: LOG:  aborting any active transactions
Nov 19 04:37:56 ip-172-31-146-188 docker/032d74312dfa[839]: FATAL:  terminating connection due to administrator command
Nov 19 04:37:56 ip-172-31-146-188 docker/032d74312dfa[839]: LOG:  autovacuum launcher shutting down
Nov 19 04:37:56 ip-172-31-146-188 docker/032d74312dfa[839]: LOG:  shutting down
Nov 19 04:37:56 ip-172-31-146-188 docker/032d74312dfa[839]: waiting for server to shut down....LOG:  database system is shut down
Nov 19 04:37:56 ip-172-31-146-188 docker/032d74312dfa[839]: wal_e.main   INFO     MSG: starting WAL-E
Nov 19 04:37:56 ip-172-31-146-188 docker/032d74312dfa[839]:         DETAIL: The subcommand is "wal-push".
Nov 19 04:37:56 ip-172-31-146-188 docker/032d74312dfa[839]:         STRUCTURED: time=2015-11-19T04:37:56.759371-00 pid=27535
Nov 19 04:37:56 ip-172-31-146-188 docker/032d74312dfa[839]: wal_e.worker.upload INFO     MSG: begin archiving a file
Nov 19 04:37:56 ip-172-31-146-188 docker/032d74312dfa[839]:         DETAIL: Uploading "pg_xlog/0000013D0000000100000094" to "s3://zalando-acid-eu-west-1-spilo-app/spilo/feiketest4/wal/wal_005/0000013D0000000100000094.lzo".
Nov 19 04:37:56 ip-172-31-146-188 docker/032d74312dfa[839]:         STRUCTURED: time=2015-11-19T04:37:56.789886-00 pid=27535 action=push-wal key=s3://zalando-acid-eu-west-1-spilo-app/spilo/feiketest4/wal/wal_005/0000013D0000000100000094.lzo prefix=spilo/feiketest4/wal/ seg=0000013D0000000100000094 state=begin
Nov 19 04:37:57 ip-172-31-146-188 docker/032d74312dfa[839]: wal_e.worker.upload INFO     MSG: completed archiving to a file
Nov 19 04:37:57 ip-172-31-146-188 docker/032d74312dfa[839]:         DETAIL: Archiving to "s3://zalando-acid-eu-west-1-spilo-app/spilo/feiketest4/wal/wal_005/0000013D0000000100000094.lzo" complete at 1277.47KiB/s.
Nov 19 04:37:57 ip-172-31-146-188 docker/032d74312dfa[839]:         STRUCTURED: time=2015-11-19T04:37:57.139769-00 pid=27535 action=push-wal key=s3://zalando-acid-eu-west-1-spilo-app/spilo/feiketest4/wal/wal_005/0000013D0000000100000094.lzo prefix=spilo/feiketest4/wal/ rate=1277.47 seg=0000013D0000000100000094 state=complete
Nov 19 04:37:58 ip-172-31-146-188 docker/032d74312dfa[839]: 2015-11-19 04:37:58,608 ERROR: get_postgresql_status
Nov 19 04:37:58 ip-172-31-146-188 docker/032d74312dfa[839]: Traceback (most recent call last):
Nov 19 04:37:58 ip-172-31-146-188 docker/032d74312dfa[839]:   File "/home/postgres/patroni/patroni/api.py", line 231, in get_postgresql_status
Nov 19 04:37:58 ip-172-31-146-188 docker/032d74312dfa[839]:     pg_is_in_recovery() AND pg_is_xlog_replay_paused()""", retry=retry)[0]
Nov 19 04:37:58 ip-172-31-146-188 docker/032d74312dfa[839]:   File "/home/postgres/patroni/patroni/api.py", line 217, in query
Nov 19 04:37:58 ip-172-31-146-188 docker/032d74312dfa[839]:     return self.server.query(sql, *params)
Nov 19 04:37:58 ip-172-31-146-188 docker/032d74312dfa[839]:   File "/home/postgres/patroni/patroni/api.py", line 287, in query
Nov 19 04:37:58 ip-172-31-146-188 docker/032d74312dfa[839]:     raise PostgresConnectionException('connection problems')
Nov 19 04:37:58 ip-172-31-146-188 docker/032d74312dfa[839]: PostgresConnectionException: 'connection problems'
Nov 19 04:37:58 ip-172-31-146-188 docker/032d74312dfa[839]: 172.31.6.141 - - [19/Nov/2015 04:37:58] "GET /slave HTTP/1.1" 503 -
Nov 19 04:37:58 ip-172-31-146-188 docker/032d74312dfa[839]: ..FATAL:  the database system is shutting down
Nov 19 04:37:58 ip-172-31-146-188 docker/032d74312dfa[839]: FATAL:  the database system is shutting down
Nov 19 04:37:58 ip-172-31-146-188 docker/032d74312dfa[839]: 2015-11-19 04:37:58,933 ERROR: get_postgresql_status
Nov 19 04:37:58 ip-172-31-146-188 docker/032d74312dfa[839]: Traceback (most recent call last):
Nov 19 04:37:58 ip-172-31-146-188 docker/032d74312dfa[839]:   File "/home/postgres/patroni/patroni/api.py", line 231, in get_postgresql_status
Nov 19 04:37:58 ip-172-31-146-188 docker/032d74312dfa[839]:     pg_is_in_recovery() AND pg_is_xlog_replay_paused()""", retry=retry)[0]
Nov 19 04:37:58 ip-172-31-146-188 docker/032d74312dfa[839]:   File "/home/postgres/patroni/patroni/api.py", line 217, in query
Nov 19 04:37:58 ip-172-31-146-188 docker/032d74312dfa[839]:     return self.server.query(sql, *params)
Nov 19 04:37:58 ip-172-31-146-188 docker/032d74312dfa[839]:   File "/home/postgres/patroni/patroni/api.py", line 287, in query
Nov 19 04:37:58 ip-172-31-146-188 docker/032d74312dfa[839]:     raise PostgresConnectionException('connection problems')
Nov 19 04:37:58 ip-172-31-146-188 docker/032d74312dfa[839]: PostgresConnectionException: 'connection problems'
Nov 19 04:37:58 ip-172-31-146-188 docker/032d74312dfa[839]: 172.31.22.160 - - [19/Nov/2015 04:37:58] "GET /slave HTTP/1.1" 503 -
Nov 19 04:37:59 ip-172-31-146-188 docker/032d74312dfa[839]: FATAL:  the database system is shutting down
Nov 19 04:37:59 ip-172-31-146-188 docker/032d74312dfa[839]: FATAL:  the database system is shutting down
Nov 19 04:37:59 ip-172-31-146-188 docker/032d74312dfa[839]: 2015-11-19 04:37:59,540 ERROR: get_postgresql_status
Nov 19 04:37:59 ip-172-31-146-188 docker/032d74312dfa[839]: Traceback (most recent call last):
Nov 19 04:37:59 ip-172-31-146-188 docker/032d74312dfa[839]:   File "/home/postgres/patroni/patroni/api.py", line 231, in get_postgresql_status
Nov 19 04:37:59 ip-172-31-146-188 docker/032d74312dfa[839]:     pg_is_in_recovery() AND pg_is_xlog_replay_paused()""", retry=retry)[0]
Nov 19 04:37:59 ip-172-31-146-188 docker/032d74312dfa[839]:   File "/home/postgres/patroni/patroni/api.py", line 217, in query
Nov 19 04:37:59 ip-172-31-146-188 docker/032d74312dfa[839]:     return self.server.query(sql, *params)
Nov 19 04:37:59 ip-172-31-146-188 docker/032d74312dfa[839]:   File "/home/postgres/patroni/patroni/api.py", line 287, in query
Nov 19 04:37:59 ip-172-31-146-188 docker/032d74312dfa[839]:     raise PostgresConnectionException('connection problems')
Nov 19 04:37:59 ip-172-31-146-188 docker/032d74312dfa[839]: PostgresConnectionException: 'connection problems'
Nov 19 04:37:59 ip-172-31-146-188 docker/032d74312dfa[839]: 172.31.21.255 - - [19/Nov/2015 04:37:59] "GET /master HTTP/1.1" 200 -
Nov 19 04:37:59 ip-172-31-146-188 docker/032d74312dfa[839]: .FATAL:  the database system is shutting down
Nov 19 04:37:59 ip-172-31-146-188 docker/032d74312dfa[839]: FATAL:  the database system is shutting down
```

**Comment by feikesteenbergen** [comment]
I've also seen it happen during startup: Recovery is stuck, therefore no good connection can be made by Patroni.

**Comment by LappleApple** [comment]
@feikesteenbergen @alexeyklyukin @CyberDem0n  Does this bug still exist? If so, can we add the "Help Wanted" tag/label?

**Comment by alexeyklyukin** [comment]
We don't know, and yes, we can use some help investigating this.

**Comment by LappleApple** [comment]
Thanks, @alexeyklyukin. Added the HW label as suggested. Possibly we can get some investigative help internally? LMK and I'll put out the pitch.

**Comment by alexeyklyukin** [comment]
Making immediate shutdown in either the restart or the switchover case is dangerous. We cannot influence PostgreSQL to shut down faster than it is, so if PG doesn't shut down - it should be the operator responsibility to investigate (for instance, if the is a logical decoding client active).
