### ISSUE TITLE
Secondary failed to be promoted during primary/etcd maintenance

### ISSUE THREAD

**Issue by anthonyalberto** [zalando/patroni#1022]
Hello, opening this issue to report a problem we've been observing a few times across different clusters with the same topology. 

The problem seems to happens when we bring down a host for maintenance that has pg primary + etcd leader. The secondary cannot seem to talk to the other 2 etcd members and desperately keeps trying to talk to the leader node that's not accessible anymore.

Going to describe one instance of that incident here.

### Cluster description

Running postgresql 9.6.10 alongside patroni 1.4.5. 2 PG members, 3 etcd members.

The topology of that cluster is the following:

```
host0: one etcd member (10.229.0.5)
host1: one etcd member (10.229.0.6), one pg member (10.229.0.3)
host2: one etcd member (10.229.0.4), one pg member (10.229.0.2)
```

At the time of the incident, host1 was hosting both the etcd leader and the pg primary.
Secondary was on host2.
We performed maintenance on host1 for roughly an hour. Secondary never promoted itself.

### Relevant Patroni configuration of the secondary

```yml
scope: postgresql
namespace: /patroni/
name: postgresql9_2

restapi:
  listen: 10.229.0.2:8008
  connect_address: 10.229.0.2:8008

etcd:
  hosts: 10.229.0.4:4001,10.229.0.5:4001,10.229.0.6:4001

bootstrap:
  method: initdb_or_restore
  initdb_or_restore:
    keep_existing_recovery_conf: False
    command: /app/scripts/custom_bootstrap
  post_bootstrap: /app/scripts/post_bootstrap
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
```

### Secondary logs

When primary + etcd leader went down:

```
2019-04-04 14:22:03,531 INFO: no action.  i am a secondary and i am following a leader
2019-04-04 14:22:12 UTC [3209]: [2-1] user=,db=,client= FATAL:  could not receive data from WAL stream: SSL SYSCALL error:EOF detected
2019-04-04 14:22:12 UTC [246443]: [1-1] user=,db=,client= FATAL:  could not connect to the primary server: could not connect to server: Connection refused
        Is the server running on host "10.229.0.3" and accepting
        TCP/IP connections on port 5432?
2019-04-04 14:22:14,038 INFO: Selected new etcd server http://10.229.0.4:4001
2019-04-04 14:22:14,040 INFO: Lock owner: postgresql8_3; I am postgresql9_2
2019-04-04 14:22:14,041 INFO: does not have lock
2019-04-04 14:22:14,045 INFO: no action.  i am a secondary and i am following a leader
2019-04-04 14:22:24,034 INFO: Selected new etcd server http://10.229.0.6:4001
2019-04-04 14:22:27,372 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=0, status=None)) after connecti
on broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f76ea89f8d0>, u'Connection to 10.229.0.6 timed out. (connect timeout=3.33333333333)')': /v2/keys/patroni/postgresql/?rec
ursive=true
2019-04-04 14:22:30,709 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connecti
on broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f76ea89f950>, u'Connection to 10.229.0.6 timed out. (connect timeout=3.33333333333)')': /v2/keys/patroni/postgresql/?rec
ursive=true
2019-04-04 14:22:34,046 ERROR: Request to server http://10.229.0.6:4001 failed: MaxRetryError(u"HTTPConnectionPool(host=u'1
0.229.0.6', port=4001): Max retries exceeded with url: /v2/keys/patroni/postgresql/?recursive=true (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f76ea966050>, u'Connecti
on to 10.229.0.6 timed out. (connect timeout=3.33333333333)'))",)
2019-04-04 14:22:34,047 INFO: Reconnection allowed, looking for another server.
2019-04-04 14:22:34,047 ERROR: Machines cache is empty, no machines to try.
2019-04-04 14:22:34,047 ERROR: get_cluster
Traceback (most recent call last):
 File "/app/patroni-1.4.5/patroni/dcs/etcd.py", line 450, in _load_cluster
   result = self.retry(self._client.read, self.client_path(''), recursive=True)
 File "/app/patroni-1.4.5/patroni/dcs/etcd.py", line 325, in retry
   return self._retry.copy()(*args, **kwargs)
 File "/app/patroni-1.4.5/patroni/utils.py", line 254, in __call__
   return func(*args, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/etcd/client.py", line 597, in read
   timeout=timeout)
 File "/app/patroni-1.4.5/patroni/dcs/etcd.py", line 205, in api_execute
   response = self._do_http_request(request_executor, method, self._base_uri + path, **kwargs)
 File "/app/patroni-1.4.5/patroni/dcs/etcd.py", line 168, in _do_http_request
   self._base_uri = self._next_server(cause=e)
 File "/usr/local/lib/python2.7/dist-packages/etcd/client.py", line 832, in _next_server
   cause=cause)
EtcdConnectionFailed: No more machines in the cluster
2019-04-04 14:22:34,051 ERROR: Error communicating with DCS
```

From there, it enters a loop where it keeps trying the same former etcd leader:

```
2019-04-04 14:22:34,056 WARNING: Loop time exceeded, rescheduling immediately.
2019-04-04 14:22:34,056 INFO: Selected new etcd server http://10.229.0.6:4001
2019-04-04 14:22:36,710 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f76ea219150>: Failed to establish a new connection: [Errno 113] No route to host',)': /v2/machines
2019-04-04 14:22:39,710 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f76e9f91890>: Failed to establish a new connection: [Errno 113] No route to host',)': /v2/machines
2019-04-04 14:22:42,710 ERROR: Failed to get list of machines from http://10.229.0.6:4001/v2: MaxRetryError("HTTPConnectionPool(host=u'10.229.0.6', port=4001): Max retries exceeded with url: /v2/machines (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f76ea2191d0>: Failed to establish a new connection: [Errno 113] No route to host',))",)
2019-04-04 14:22:42,710 ERROR: Could not get the list of servers, maybe you provided the wrong host(s) to connect to?
2019-04-04 14:22:42,710 ERROR: Error communicating with DCS
2019-04-04 14:22:42,712 INFO: DCS is not accessible
2019-04-04 14:22:42,712 INFO: Selected new etcd server http://10.229.0.6:4001
2019-04-04 14:22:45,710 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f76ea89fb90>: Failed to establish a new connection: [Errno 113] No route to host',)': /v2/machines
2019-04-04 14:22:48,710 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f76ea89f690>: Failed to establish a new connection: [Errno 113] No route to host',)': /v2/machines
2019-04-04 14:22:51,710 ERROR: Failed to get list of machines from http://10.229.0.6:4001/v2: MaxRetryError("HTTPConnectionPool(host=u'10.229.0.6', port=4001): Max retries exceeded with url: /v2/machines (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f76ea966890>: Failed to establish a new connection: [Errno 113] No route to host',))",)
2019-04-04 14:22:51,710 ERROR: Could not get the list of servers, maybe you provided the wrong host(s) to connect to?
2019-04-04 14:22:52,711 INFO: Selected new etcd server http://10.229.0.6:4001
2019-04-04 14:22:54,710 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f76ea89fa10>: Failed to establish a new connection: [Errno 113] No route to host',)': /v2/machines
2019-04-04 14:22:57,710 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f76ea9661d0>: Failed to establish a new connection: [Errno 113] No route to host',)': /v2/machines
2019-04-04 14:23:00,710 ERROR: Failed to get list of machines from http://10.229.0.6:4001/v2: MaxRetryError("HTTPConnectionPool(host=u'10.229.0.6', port=4001): Max retries exceeded with url: /v2/machines (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f76ea219450>: Failed to establish a new co
nnection: [Errno 113] No route to host',))",)
2019-04-04 14:23:00,710 ERROR: Could not get the list of servers, maybe you provided the wrong host(s) to connect to?
2019-04-04 14:23:00,710 ERROR: Error communicating with DCS
2019-04-04 14:23:00 UTC [246481]: [1-1] user=[unknown],db=[unknown],client=127.0.0.1 LOG:  connection received: host=127.0.
0.1 port=45033
2019-04-04 14:23:00 UTC [246482]: [1-1] user=[unknown],db=[unknown],client=127.0.0.1 LOG:  connection received: host=127.0.
0.1 port=45034
2019-04-04 14:23:00,712 INFO: DCS is not accessible
2019-04-04 14:23:00,713 WARNING: Loop time exceeded, rescheduling immediately.
2019-04-04 14:23:00,713 INFO: Selected new etcd server http://10.229.0.6:4001
...
```

Finally, it's able to connect when maintenance is over. As soon as it's able to talk to `10.229.0.6` (the former leader), it switches to `10.229.0.5`

```
2019-04-04 15:32:35,210 INFO: Selected new etcd server http://10.229.0.6:4001
2019-04-04 15:32:37,352 INFO: Selected new etcd server http://10.229.0.5:4001
2019-04-04 15:32:38 UTC [251082]: [1-1] user=,db=,client= FATAL:  could not connect to the primary server: could not connect to server: No route to host
         Is the server running on host "10.229.0.3" and accepting
         TCP/IP connections on port 5432?

2019-04-04 15:32:38,342 WARNING: request failed: GET http://10.229.0.3:8008/patroni (HTTPConnectionPool(host='10.229.0.3', port=8008): Max retries exceeded with url: /patroni (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f76ea204f10>: Failed to establish a new connection: [Errno 113] No route to host',)))
2019-04-04 15:32:38,379 INFO: promoted self to leader by acquiring session lock
2019-04-04 15:32:38,384 INFO: cleared rewind state after becoming the leader
```

### Additional info

- I've looked at the etcd logs. As soon as the etcd leader went down, they elected a new leader without a problem.

Thanks for your help!

**Comment by CyberDem0n** [comment]
I would suggest you first to upgrade Patroni to the latest version, there were definitely some changes in this area.

**Comment by anthonyalberto** [comment]
Alright for the time being we'll bump patroni to 1.5.5 before attempting maintenance, see if it makes a difference

Closing this for now!

**Comment by CyberDem0n** [comment]
The latest version is 1.5.6
