### ISSUE TITLE
Consul support multiple datacenter cluster

### ISSUE THREAD

**Issue by ihard** [zalando/patroni#1026]
Hi, I'm trying to create a cluster in multiple datacenters with Consul.
Consul is configured in two data centers dc1 and dc2.
```
consul version
Consul v1.4.4
```

```
patronictl version
patronictl version 1.5.6
```

config patroni for all nodes cluster
```
consul:
  host: 127.0.0.1:8500
  url: http://127.0.0.1:8500
  token: secret
  dc: dc1
  register_service: True
```

In the dc1, there are no problems, the cluster has assembled.
In dc2 patronictl sees nodes in dc1, but not register from dc2

patroni.log
```
2019-04-09 19:08:27,369 ERROR: refresh_session
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/utils.py", line 254, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/consul.py", line 272, in _do_refresh_session
    lock_delay=0.001, behavior='delete')
  File "/usr/local/lib/python3.6/dist-packages/consul/base.py", line 1764, in create
    data=data)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/consul.py", line 116, in wrapper
    return callback(self.response(self.http.request(method.upper(), self.uri(path, params), **kwargs)))
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/consul.py", line 82, in response
    raise ConsulInternalError(msg)
patroni.dcs.consul.ConsulInternalError: 500 rpc error making call: rpc error making call: rpc error making call: Missing node registration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/consul.py", line 283, in refresh_session
    return self.retry(self._do_refresh_session)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/consul.py", line 225, in retry
    return self._retry.copy()(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/utils.py", line 263, in __call__
    raise RetryFailedError("Exceeded retry deadline")
patroni.utils.RetryFailedError: 'Exceeded retry deadline'
2019-04-09 19:08:27,370 INFO: waiting on consul
```

consul.log from agent
```
2019/04/09 19:10:00 [ERR] consul: "Session.Apply" RPC failed to server 10.201.34.228:8300: rpc error making call: rpc error making call: rpc error making call: Missing node
2019/04/09 19:10:00 [ERR] http: Request PUT /v1/session/create?dc=dc1, error: rpc error making call: rpc error making call: rpc error making call: Missing node registration from=127.0.0.1:37872
```

consul.log from server
```
2019/04/09 19:16:02 [ERR] consul: RPC failed to server 10.200.74.225:8300 in DC "dc1": rpc error making call: rpc error making call: Missing node registration
```

consul members
```
Node                     Address             Status  Type    Build  Protocol  DC   Segment
dc2-consul1              10.201.34.228:8301  alive   server  1.4.4  2         dc2  <all>
dc2-consul2              10.201.34.229:8301  alive   server  1.4.4  2         dc2  <all>
dc2-consul3              10.201.34.230:8301  alive   server  1.4.4  2         dc2  <all>
dc2-db-postgres-common1  10.201.34.238:8301  alive   client  1.4.4  2         dc2  <default>
dc2-db-postgres-common2  10.201.34.239:8301  alive   client  1.4.4  2         dc2  <default>
dc2-db-postgres-common3  10.201.34.240:8301  alive   client  1.4.4  2         dc2  <default>
```

consul members -wan
```
Node             Address             Status  Type    Build  Protocol  DC   Segment
dc2-consul1.dc2  10.201.34.228:8302  alive   server  1.4.4  2         dc2  <all>
dc2-consul2.dc2  10.201.34.229:8302  alive   server  1.4.4  2         dc2  <all>
dc2-consul3.dc2  10.201.34.230:8302  alive   server  1.4.4  2         dc2  <all>
dc1-consul1.dc1  10.200.74.225:8302  alive   server  1.4.4  2         dc1  <all>
dc1-consul2.dc1  10.200.74.226:8302  alive   server  1.4.4  2         dc1  <all>
dc1-consul3.dc1  10.200.74.227:8302  alive   server  1.4.4  2         dc1  <all>
```

**Comment by CyberDem0n** [comment]
It fails to create a session in `dc1` because node (local consul agent) is not registered there: https://www.consul.io/api/session.html

There is not much value in such setup. If dc1 goes down Patroni in dc2 won't be able to do anything.
I would better recommend you to run the [standby cluster](https://github.com/zalando/patroni/blob/master/docs/replica_bootstrap.rst) in dc2.

P.S. and I would really insist on adding `checks: []` to the Patroni consul config.

**Comment by ihard** [comment]
Thank! It all worked.

**Comment by gsl23** [comment]
> Thank! It all worked.

ihard, how u did this ? With two undependent consuls in two dc OR with one multi dc consul cluster ?

**Comment by ihard** [comment]
@gsl23,
One multi dc cunsul cluster,
in master dc
```
consul:
  host: 127.0.0.1:8500
  url: http://127.0.0.1:8500
  dc: dc1
  checks: []
  register_service: True
bootstrap:
  dcs:
    slots:
      standby_cluster:
        type: physical
```
in slave dc
```
consul:
  host: 127.0.0.1:8500
  url: http://127.0.0.1:8500
  dc: dc2
  checks: []
  register_service: True
bootstrap:
  dcs:
    standby_cluster:
      host: master.db-main.service.dc1.consul
      port: 5432
      primary_slot_name: standby_cluster
      create_replica_methods:
        - basebackup
```

**Comment by lifedanceman** [comment]
@ihard Hi, tell me please, in your environment if all members in dc1 is down or network connectivity between data centers is broken,  is standby leader promoted automatically?
