### ISSUE TITLE
Consul token not re-read on SIGHUP

### ISSUE THREAD

**Issue by ccakes** [zalando/patroni#1028]
I'm running Patroni using Nomad + Consul and ACLs enabled. Currently running Patroni 1.5.5

The Nomad job gets a Consul token from Vault for Patroni to use which is cycled every 24 hours. It dutifully updates the patroni.yml config file with the new token and sends a SIGHUP to the process but it doesn't seem to recognise the new token, once the previous one expires the logs fill up with

<details>
<summary>Logs</summary>

```
2019-04-10 14:57:17,443 ERROR: get_cluster
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/patroni/dcs/consul.py", line 294, in _load_cluster
_, results = self.retry(self._client.kv.get, path, recurse=True)
File "/usr/lib/python3.6/site-packages/patroni/dcs/consul.py", line 225, in retry
return self._retry.copy()(*args, **kwargs)
File "/usr/lib/python3.6/site-packages/patroni/utils.py", line 254, in __call__
return func(*args, **kwargs)
File "/usr/lib/python3.6/site-packages/consul/base.py", line 554, in get
params=params)
File "/usr/lib/python3.6/site-packages/patroni/dcs/consul.py", line 116, in wrapper
return callback(self.response(self.http.request(method.upper(), self.uri(path, params), **kwargs)))
File "/usr/lib/python3.6/site-packages/consul/base.py", line 223, in cb
CB._status(response, allow_404=allow_404)
File "/usr/lib/python3.6/site-packages/consul/base.py", line 181, in _status
raise ACLPermissionDenied(response.body)
consul.base.ACLPermissionDenied: rpc error making call: ACL not found
2019-04-10 14:57:17,445 ERROR: Error communicating with DCS
2019-04-10 14:57:17,551 INFO: closed patroni connection to the postgresql cluster
2019-04-10 14:57:17,604 INFO: postmaster pid=26676
/tmp:27740 - no response
/tmp:27740 - accepting connections
/tmp:27740 - accepting connections
2019-04-10 14:57:18,623 INFO: demoted self because DCS is not accessible and i was a leader
2019-04-10 14:57:27,443 ERROR: get_cluster
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/patroni/dcs/consul.py", line 294, in _load_cluster
_, results = self.retry(self._client.kv.get, path, recurse=True)
File "/usr/lib/python3.6/site-packages/patroni/dcs/consul.py", line 225, in retry
return self._retry.copy()(*args, **kwargs)
File "/usr/lib/python3.6/site-packages/patroni/utils.py", line 254, in __call__
return func(*args, **kwargs)
File "/usr/lib/python3.6/site-packages/consul/base.py", line 554, in get
params=params)
File "/usr/lib/python3.6/site-packages/patroni/dcs/consul.py", line 116, in wrapper
return callback(self.response(self.http.request(method.upper(), self.uri(path, params), **kwargs)))
File "/usr/lib/python3.6/site-packages/consul/base.py", line 223, in cb
CB._status(response, allow_404=allow_404)
```
</details>

Seems like a bug? Or should I be preferring environment variables for this config? Manually sending SIGHUP didn't seem to have any effect, not `POST /reload` however restarting the daemon (with the same token in the config file) worked fine

Suggestions appreciated if there's a way I should be handling this better. Obviously I could remove the token requirement or give Patroni a permanent token rather than using Vault, but it feels like the current config _should_ work

**Comment by BillSchumacher** [comment]
I'm fairly certain the user is only updated on the first run from .yml.

**Comment by BillSchumacher** [comment]
Looks like you lost connectivity to consul reading you log. Not sure how the token plays a role in all this, in my consul configuration in the .yml it's just:

consul:
  host: 127.0.0.1:8500

**Comment by BillSchumacher** [comment]
If you're using the token to have consul connect to consul servers you're probably wanting to modify the local consul agent's configuration and not patroni unless you were referring to the DB users.

**Comment by ccakes** [comment]
For clarification - the token I'm referring to is the **token** value in [this section](https://patroni.readthedocs.io/en/latest/SETTINGS.html#consul). It's to authenticate Patroni with Consul so it can use the KV store.

The logs are pretty clear that it's an ACL issue, not a connectivity issue, in these lines:
```
raise ACLPermissionDenied(response.body)
consul.base.ACLPermissionDenied: rpc error making call: ACL not found
```

**Comment by ccakes** [comment]
I'm guessing that since the Consul subclass doesn't implement `reload_config()` that'd be why this doesn't work

Question for the devs: is there a particular reason why or would you be open to a PR for this?

**Comment by CyberDem0n** [comment]
Well, I just never thought about such use-case. It is not very hard to fix it, contributions are always welcome.

**Comment by ccakes** [comment]
I've just submitted a draft PR (#1030) - let me know what I've missed and I'll fix it up
