### ISSUE TITLE
how to make patroni-postgresql database, data persistent in docker

### ISSUE THREAD

**Issue by sysadmin-imran** [zalando/patroni#1046]
I Have used this link https://github.com/seocahill/ha-postgres-docker-stack.git for achieving postgresql HA in docker, though high availability was achieved but data of database is not remaining persistent once all containers removed/exited launched in two vms ( i wanted shutdown one vm to test whether HA is achieved or not. HA was achieved but data  persistent of database was not achieved).

To make data-persistent i tried docker volume persistence trick, below one in conjunction with  
 environment:
      - PATRONI_POSTGRESQL_DATA_DIR=/data/dbnode1 
 volumes:
      - pgdata:/data/dbnode1  

i am getting following error

initdb: could not change permissions of directory "/data/dbnode1": Operation not permitted
pg_ctl: database system initialization failed
2019-04-22 12:18:11,109 INFO: removing initialize key after failed attempt to bootstrap the cluster
2019-04-22 12:18:11,110 INFO: renaming data directory to /data/dbnode1_2019-04-22-12-18-11
2019-04-22 12:18:11,111 ERROR: Could not rename data directory /data/dbnode1
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/patroni/postgresql.py", line 1730, in move_data_directory
    os.rename(self._data_dir, new_name)
OSError: [Errno 16] Device or resource busy: '/data/dbnode1' -> '/data/dbnode1_2019-04-22-12-18-11'
2019-04-22 12:18:11,577 INFO: Lock owner: None; I am dbnode1
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/patroni/__init__.py", line 159, in patroni_main
    patroni.run()
  File "/usr/local/lib/python3.5/dist-packages/patroni/__init__.py", line 125, in run
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python3.5/dist-packages/patroni/ha.py", line 1323, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.5/dist-packages/patroni/ha.py", line 1232, in _run_cycle
    return self.post_bootstrap()
  File "/usr/local/lib/python3.5/dist-packages/patroni/ha.py", line 1128, in post_bootstrap
    self.cancel_initialization()
  File "/usr/local/lib/python3.5/dist-packages/patroni/ha.py", line 1123, in cancel_initialization
    raise PatroniException('Failed to bootstrap cluster')
patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'
fixing permissions on existing directory /data/dbnode1 

How to get data persistence using your git repo  "https://github.com/seocahill/ha-postgres-docker-stack.git"

**Comment by CyberDem0n** [comment]
The user which is used to run Patroni and postgres should have enough permissions to read and write files in the PGDATA. It is the responsibility of the operator to give such permissions (on the filesystem)

Or in other words, Patroni is environment agnostic and knows nothing about filesystem permissions, volumes, dockers and so on.

You should better report your problem to the author of `ha-postgres-docker-stack` or try to figure out what is wrong on your own.

**Comment by alexeyklyukin** [comment]
Typically, you don't treat the root of the mounted volume as your data directory, as filesystems tend to put some unrelated cruft like lost+found there. Instead, you create a subdirectory in your mount and give it correct permissions for postgres (normally, postgres user should be the owner and no other user or group should have access there).

**Comment by cobolbaby** [comment]
The core of the problem is the directory permissions. You can follow the instructions:

```
sudo chown -R 999:999 <HostPath> 
sudo chmod -R 700 <HostPath>
```
and <HostPath> should be mapped to `/home/postgres/data`

**Comment by sysadmin-imran** [comment]
yeah these two below commands on the host VM did the trick and it was definitely user ownership and files/folders permission issue, Thanks cobolbaby.

sudo chown -R 999:999 /test/postgres/data 
sudo chmod -R 700 /test/postgres/data/ 

and then i mapped it this way in docker-compose.yml file

environment:
   - PATRONI_POSTGRESQL_DATA_DIR=/data/dbnode1
volumes:
    - /test/postgres/data/dbnode1:/data/dbnode1


 off-course it also worked  this way

environment:
    - PATRONI_POSTGRESQL_DATA_DIR=/home/postgres/data 
volumes:
    - /test/postgres/data/dbnode1:/home/postgres/data/dbnode1
