### ISSUE TITLE
patroni enter chaos status after kubernetes error recover

### ISSUE THREAD

**Issue by zhangmingld** [zalando/patroni#1070]
We use helm to install our patroni in  kubenretes cluster, and delete the rbac rule carelessly,  a second later,  we recreate the rbac rule 
Then we check the patroni log , it enters a chaos status 

Here is the log 
after kubernetes cluster recovers, patroni start as replica first , then on_role_change to replica 
then on_role_change to master ......
`2019-05-16T03:24:48.908589367Z 2019-05-16 05:24:48,907 INFO: no action.  i am the leader with the lock
2019-05-16T03:24:58.895291111Z 2019-05-16 05:24:58,895 INFO: Lock owner: test-db-pg-0; I am test-db-pg-0
2019-05-16T03:24:58.904595811Z 2019-05-16 05:24:58,898 ERROR: Permission denied
2019-05-16T03:24:58.904610265Z Traceback (most recent call last):
2019-05-16T03:24:58.90461344Z   File "/var/lib/postgresql/patroni/dcs/kubernetes.py", line 61, in wrapper
2019-05-16T03:24:58.904616598Z     return func(*args, **kwargs)
2019-05-16T03:24:58.904619289Z   File "/var/lib/postgresql/patroni/dcs/kubernetes.py", line 275, in patch_or_create
2019-05-16T03:24:58.904622077Z     return self.retry(func, self._namespace, body) if retry else func(self._namespace, body)
2019-05-16T03:24:58.90462466Z   File "/var/lib/postgresql/patroni/dcs/kubernetes.py", line 112, in retry
2019-05-16T03:24:58.904627662Z     return self._retry.copy()(*args, **kwargs)
2019-05-16T03:24:58.904630153Z   File "/var/lib/postgresql/patroni/utils.py", line 254, in __call__
2019-05-16T03:24:58.90463283Z     return func(*args, **kwargs)
2019-05-16T03:24:58.904635339Z   File "/var/lib/postgresql/patroni/dcs/kubernetes.py", line 50, in wrapper
2019-05-16T03:24:58.904637877Z     return getattr(self._api, func)(*args, **kwargs)
2019-05-16T03:24:58.90464053Z   File "/usr/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 14905, in patch_namespaced_config_map
2019-05-16T03:24:58.90464334Z     (data) = self.patch_namespaced_config_map_with_http_info(name, namespace, body, **kwargs)
2019-05-16T03:24:58.904646048Z   File "/usr/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 14999, in patch_namespaced_config_map_with_http_info
2019-05-16T03:24:58.904648765Z     collection_formats=collection_formats)
2019-05-16T03:24:58.90465136Z   File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
2019-05-16T03:24:58.90465396Z     _return_http_data_only, collection_formats, _preload_content, _request_timeout)
2019-05-16T03:24:58.904656553Z   File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
2019-05-16T03:24:58.904659181Z     _request_timeout=_request_timeout)
2019-05-16T03:24:58.904661622Z   File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 380, in request
2019-05-16T03:24:58.904664231Z     body=body)
2019-05-16T03:24:58.904674952Z   File "/usr/lib/python2.7/site-packages/kubernetes/client/rest.py", line 286, in PATCH
2019-05-16T03:24:58.904677839Z     body=body)
2019-05-16T03:24:58.90468025Z   File "/usr/lib/python2.7/site-packages/kubernetes/client/rest.py", line 222, in request
2019-05-16T03:24:58.904682931Z     raise ApiException(http_resp=r)
2019-05-16T03:24:58.904685383Z ApiException: (403)
2019-05-16T03:24:58.90468779Z Reason: Forbidden
2019-05-16T03:24:58.904690661Z HTTP response headers: HTTPHeaderDict({'Date': 'Thu, 16 May 2019 03:24:58 GMT', 'Audit-Id': '0babf543-fbd5-463c-97b8-82c252187821', 'Content-Length': '410', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff'})
2019-05-16T03:24:58.904693533Z HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps \"test-db-pg-leader\" is forbidden: User \"system:serviceaccount:clean-install:test-db-pg\" cannot patch resource \"configmaps\" in API group \"\" in the namespace \"clean-install\"","reason":"Forbidden","details":{"name":"test-db-pg-leader","kind":"configmaps"},"code":403}
2019-05-16T03:24:58.904699292Z 
2019-05-16T03:24:58.904701734Z 
2019-05-16T03:24:58.904704231Z 2019-05-16 05:24:58,903 ERROR: failed to update leader lock
2019-05-16T03:24:58.904707182Z 2019-05-16 05:24:58,903 INFO: pg_rewind args: ['pg_rewind', '--help']
2019-05-16T03:24:58.925782406Z 2019-05-16 05:24:58,925 INFO: pg_controldata env: {'LANG': 'C', 'LC_ALL': 'C', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/python'}
2019-05-16T03:24:58.945302669Z 2019-05-16 05:24:58,945 INFO: Postgres stop: success: True, signaled: True, block_callbacks: False
2019-05-16T03:24:58.945362853Z 2019-05-16 05:24:58,945 INFO: Postgres call_nowait: bootstrapping: False, callback: {'on_stop': '/var/lib/postgresql/scripts/patroni_callback.py', 'on_start': '/var/lib/postgresql/scripts/patroni_callback.py', 'on_role_change': '/var/lib/postgresql/scripts/patroni_callback.py'}, cb_name: on_stop
2019-05-16T03:24:58.945390468Z 2019-05-16 05:24:58,945 INFO: Postgres call callback: on_stop, role: master, scope: test-db-pg
2019-05-16T03:24:58.945555402Z 2019-05-16 05:24:58,945 INFO: Postgres call callback: on_stop, cmd: ['/var/lib/postgresql/scripts/patroni_callback.py', 'on_stop', 'master', 'test-db-pg']
2019-05-16T03:24:59.283020069Z 2019-05-16 05:24:59,282 INFO: callback: cluster: test-db-pg, namespace: clean-install, role: master, action: on_stop
2019-05-16T03:24:59.283038789Z 2019-05-16 05:24:59,282 INFO: del_endpoint: endpoint_name: test-db-pg-replica, namespace: clean-install
2019-05-16T03:24:59.299706679Z 2019-05-16 05:24:59,299 INFO: del_subset subsets before: [{'addresses': [{'hostname': None,
2019-05-16T03:24:59.299728508Z                 'ip': '192.168.239.176',
2019-05-16T03:24:59.299733515Z                 'node_name': None,
2019-05-16T03:24:59.299737764Z                 'target_ref': None}],
2019-05-16T03:24:59.299741934Z  'not_ready_addresses': None,
2019-05-16T03:24:59.29975642Z  'ports': [{'name': 'metrics', 'port': 9187, 'protocol': 'TCP'},
2019-05-16T03:24:59.299760455Z            {'name': 'postgresql', 'port': 5432, 'protocol': 'TCP'}]}], ip: 192.168.9.148
2019-05-16T03:24:59.300123155Z 2019-05-16 05:24:59,300 INFO: del_subset subsets final: [{'addresses': [{'hostname': None,
2019-05-16T03:24:59.300130267Z                 'ip': '192.168.239.176',
2019-05-16T03:24:59.300134244Z                 'node_name': None,
2019-05-16T03:24:59.300138209Z                 'target_ref': None}],
2019-05-16T03:24:59.300142227Z  'not_ready_addresses': None,
2019-05-16T03:24:59.300146309Z  'ports': [{'name': 'metrics', 'port': 9187, 'protocol': 'TCP'},
2019-05-16T03:24:59.300150425Z            {'name': 'postgresql', 'port': 5432, 'protocol': 'TCP'}]}]
2019-05-16T03:24:59.41654998Z 2019-05-16 05:24:59,415 INFO: Postgres call callback: on_stop, res: 0
2019-05-16T03:24:59.45568124Z 2019-05-16 05:24:59,455 INFO: demoted self because failed to update leader lock in DCS
2019-05-16T03:24:59.456315884Z 2019-05-16 05:24:59,456 INFO: closed patroni connection to the postgresql cluster
2019-05-16T03:24:59.456531967Z 2019-05-16 05:24:59,456 INFO: pg_controldata env: {'LANG': 'C', 'LC_ALL': 'C', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/python'}
2019-05-16T03:24:59.465391873Z 2019-05-16 05:24:59,465 INFO: Start postgres with options: ['--listen_addresses=0.0.0.0,*', '--max_worker_processes=8', '--max_locks_per_transaction=64', '--wal_level=replica', '--track_commit_timestamp=off', '--max_prepared_transactions=0', '--port=5432', '--max_replication_slots=10', '--max_connections=100', '--hot_standby=on', '--cluster_name=test-db-pg', '--wal_log_hints=on', '--max_wal_senders=10']
2019-05-16T03:24:59.466446496Z 2019-05-16 05:24:59,465 INFO: Starting postgres: postgres -D /var/lib/postgresql/data/pgdata --config-file=/var/lib/postgresql/data/pgdata/postgresql.conf --listen_addresses=0.0.0.0,* --max_worker_processes=8 --max_locks_per_transaction=64 --wal_level=replica --track_commit_timestamp=off --max_prepared_transactions=0 --port=5432 --max_replication_slots=10 --max_connections=100 --hot_standby=on --cluster_name=test-db-pg --wal_log_hints=on --max_wal_senders=10
2019-05-16T03:25:00.122039161Z 2019-05-16 05:25:00,121 INFO: postmaster pid=1526
2019-05-16T03:25:00.122505769Z 2019-05-16 05:25:00,122 INFO: pg_isready args: ['pg_isready', '-p', '5432', '-d', 'postgres', '-h', 'localhost', '-U', 'postgres']
2019-05-16T03:25:00.169375604Z localhost:5432 - rejecting connections
2019-05-16T03:25:00.169975531Z 2019-05-16 05:25:00,169 INFO: pg_isready args: ['pg_isready', '-p', '5432', '-d', 'postgres', '-h', 'localhost', '-U', 'postgres']
2019-05-16T03:25:00.205445929Z localhost:5432 - rejecting connections
2019-05-16T03:25:01.207595199Z 2019-05-16 05:25:01,206 INFO: pg_isready args: ['pg_isready', '-p', '5432', '-d', 'postgres', '-h', 'localhost', '-U', 'postgres']
2019-05-16T03:25:01.235032968Z localhost:5432 - accepting connections
2019-05-16T03:25:01.236552995Z 2019-05-16 05:25:01,236 INFO: Postgres call_nowait: bootstrapping: False, callback: {'on_stop': '/var/lib/postgresql/scripts/patroni_callback.py', 'on_start': '/var/lib/postgresql/scripts/patroni_callback.py', 'on_role_change': '/var/lib/postgresql/scripts/patroni_callback.py'}, cb_name: on_start
2019-05-16T03:25:01.236624047Z 2019-05-16 05:25:01,236 INFO: Postgres call callback: on_start, role: replica, scope: test-db-pg
2019-05-16T03:25:01.23679015Z 2019-05-16 05:25:01,236 INFO: Postgres call callback: on_start, cmd: ['/var/lib/postgresql/scripts/patroni_callback.py', 'on_start', 'replica', 'test-db-pg']
2019-05-16T03:25:01.236981417Z 2019-05-16 05:25:01,236 INFO: Postgres call_nowait: bootstrapping: False, callback: {'on_stop': '/var/lib/postgresql/scripts/patroni_callback.py', 'on_start': '/var/lib/postgresql/scripts/patroni_callback.py', 'on_role_change': '/var/lib/postgresql/scripts/patroni_callback.py'}, cb_name: on_role_change
2019-05-16T03:25:01.237220709Z 2019-05-16 05:25:01,237 INFO: Postgres call callback: on_role_change, role: replica, scope: test-db-pg
2019-05-16T03:25:01.240681184Z 2019-05-16 05:25:01,240 INFO: Postgres call callback: on_role_change, cmd: ['/var/lib/postgresql/scripts/patroni_callback.py', 'on_role_change', 'replica', 'test-db-pg']
2019-05-16T03:25:01.863600205Z 2019-05-16 05:25:01,863 WARNING: Killed the old callback process because it was still running: ['/var/lib/postgresql/scripts/patroni_callback.py', 'on_start', 'replica', 'test-db-pg']
2019-05-16T03:25:01.938143639Z 2019-05-16 05:25:01,937 INFO: Lock owner: test-db-pg-0; I am test-db-pg-0
2019-05-16T03:25:01.938190806Z 2019-05-16 05:25:01,938 INFO: establishing a new patroni connection to the postgres cluster
2019-05-16T03:25:02.007552374Z 2019-05-16 05:25:02,007 INFO: pg_ctl args: (), {}
2019-05-16T03:25:02.015469001Z server signaled
2019-05-16T03:25:02.018771416Z 2019-05-16 05:25:02,016 INFO: Postgres call_nowait: bootstrapping: False, callback: {'on_stop': '/var/lib/postgresql/scripts/patroni_callback.py', 'on_start': '/var/lib/postgresql/scripts/patroni_callback.py', 'on_role_change': '/var/lib/postgresql/scripts/patroni_callback.py'}, cb_name: on_reload
2019-05-16T03:25:02.087219324Z 2019-05-16 05:25:02,086 INFO: promoted self to leader because i had the session lock
2019-05-16T03:25:02.087677565Z 2019-05-16 05:25:02,087 INFO: pg_ctl args: ('-W',), {}
2019-05-16T03:25:02.094933258Z server promoting
2019-05-16T03:25:02.095817391Z 2019-05-16 05:25:02,094 INFO: cleared rewind state after becoming the leader
2019-05-16T03:25:02.095839177Z 2019-05-16 05:25:02,095 INFO: Postgres call_nowait: bootstrapping: False, callback: {'on_stop': '/var/lib/postgresql/scripts/patroni_callback.py', 'on_start': '/var/lib/postgresql/scripts/patroni_callback.py', 'on_role_change': '/var/lib/postgresql/scripts/patroni_callback.py'}, cb_name: on_role_change
2019-05-16T03:25:02.095844Z 2019-05-16 05:25:02,095 INFO: Postgres call callback: on_role_change, role: master, scope: test-db-pg
2019-05-16T03:25:02.095847722Z 2019-05-16 05:25:02,095 INFO: Postgres call callback: on_role_change, cmd: ['/var/lib/postgresql/scripts/patroni_callback.py', 'on_role_change', 'master', 'test-db-pg']
2019-05-16T03:25:02.567656727Z 2019-05-16 05:25:02,567 WARNING: Killed the old callback process because it was still running: ['/var/lib/postgresql/scripts/patroni_callback.py', 'on_role_change', 'replica', 'test-db-pg']
2019-05-16T03:25:02.570579489Z 2019-05-16 05:25:02,570 INFO: pg_controldata env: {'LANG': 'C', 'LC_ALL': 'C', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/python'}
2019-05-16T03:25:02.634846425Z 2019-05-16 05:25:02,634 INFO: Lock owner: test-db-pg-1; I am test-db-pg-0
2019-05-16T03:25:02.635327639Z 2019-05-16 05:25:02,635 INFO: Lock owner: test-db-pg-1; I am test-db-pg-0
2019-05-16T03:25:02.635374472Z 2019-05-16 05:25:02,635 INFO: does not have lock
2019-05-16T03:25:02.636781599Z 2019-05-16 05:25:02,636 INFO: pg_rewind args: ['pg_rewind', '--help']
2019-05-16T03:25:02.691575879Z 2019-05-16 05:25:02,691 INFO: pg_controldata env: {'LANG': 'C', 'LC_ALL': 'C', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/python'}
2019-05-16T03:25:02.712369141Z 2019-05-16 05:25:02,712 INFO: Postgres stop: success: True, signaled: True, block_callbacks: False
2019-05-16T03:25:02.714002058Z 2019-05-16 05:25:02,712 INFO: Postgres call_nowait: bootstrapping: False, callback: {'on_stop': '/var/lib/postgresql/scripts/patroni_callback.py', 'on_start': '/var/lib/postgresql/scripts/patroni_callback.py', 'on_role_change': '/var/lib/postgresql/scripts/patroni_callback.py'}, cb_name: on_stop
2019-05-16T03:25:02.714015586Z 2019-05-16 05:25:02,712 INFO: Postgres call callback: on_stop, role: master, scope: test-db-pg
2019-05-16T03:25:02.714018912Z 2019-05-16 05:25:02,712 INFO: Postgres call callback: on_stop, cmd: ['/var/lib/postgresql/scripts/patroni_callback.py', 'on_stop', 'master', 'test-db-pg']
2019-05-16T03:25:03.414641823Z 2019-05-16 05:25:03,414 INFO: callback: cluster: test-db-pg, namespace: clean-install, role: master, action: on_stop
2019-05-16T03:25:03.414698869Z 2019-05-16 05:25:03,414 INFO: del_endpoint: endpoint_name: test-db-pg-replica, namespace: clean-install
2019-05-16T03:25:03.429026887Z 2019-05-16 05:25:03,428 INFO: del_subset subsets before: None, ip: 192.168.9.148
2019-05-16T03:25:03.545601724Z 2019-05-16 05:25:03,545 INFO: Postgres call callback: on_stop, res: 0
2019-05-16T03:25:03.617251712Z 2019-05-16 05:25:03,617 INFO: demoting self because i do not have the lock and i was a leader
2019-05-16T03:25:03.618170345Z 2019-05-16 05:25:03,618 INFO: closed patroni connection to the postgresql cluster
2019-05-16T03:25:03.618408463Z 2019-05-16 05:25:03,618 INFO: pg_controldata env: {'LANG': 'C', 'LC_ALL': 'C', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/python'}
2019-05-16T03:25:03.626028263Z 2019-05-16 05:25:03,625 INFO: Start postgres with options: ['--listen_addresses=0.0.0.0,*', '--max_worker_processes=8', '--max_locks_per_transaction=64', '--wal_level=replica', '--track_commit_timestamp=off', '--max_prepared_transactions=0', '--port=5432', '--max_replication_slots=10', '--max_connections=100', '--hot_standby=on', '--cluster_name=test-db-pg', '--wal_log_hints=on', '--max_wal_senders=10']
2019-05-16T03:25:03.626172443Z 2019-05-16 05:25:03,626 INFO: Starting postgres: postgres -D /var/lib/postgresql/data/pgdata --config-file=/var/lib/postgresql/data/pgdata/postgresql.conf --listen_addresses=0.0.0.0,* --max_worker_processes=8 --max_locks_per_transaction=64 --wal_level=replica --track_commit_timestamp=off --max_prepared_transactions=0 --port=5432 --max_replication_slots=10 --max_connections=100 --hot_standby=on --cluster_name=test-db-pg --wal_log_hints=on --max_wal_senders=10
2019-05-16T03:25:04.399293803Z 2019-05-16 05:25:04,399 INFO: callback: cluster: test-db-pg, namespace: clean-install, role: master, action: on_role_change
2019-05-16T03:25:04.413468794Z 2019-05-16 05:25:04,413 INFO: del_endpoint: endpoint_name: test-db-pg-replica, namespace: clean-install
2019-05-16T03:25:04.419368469Z 2019-05-16 05:25:04,419 INFO: del_subset subsets before: None, ip: 192.168.9.148
2019-05-16T03:25:04.727741798Z 2019-05-16 05:25:04,727 INFO: postmaster pid=1615
2019-05-16T03:25:04.728205824Z 2019-05-16 05:25:04,728 INFO: pg_isready args: ['pg_isready', '-p', '5432', '-d', 'postgres', '-h', 'localhost', '-U', 'postgres']
2019-05-16T03:25:04.794339081Z localhost:5432 - rejecting connections
2019-05-16T03:25:04.795324787Z 2019-05-16 05:25:04,794 INFO: pg_isready args: ['pg_isready', '-p', '5432', '-d', 'postgres', '-h', 'localhost', '-U', 'postgres']
2019-05-16T03:25:04.818815527Z localhost:5432 - rejecting connections
2019-05-16T03:25:05.820710408Z 2019-05-16 05:25:05,820 INFO: pg_isready args: ['pg_isready', '-p', '5432', '-d', 'postgres', '-h', 'localhost', '-U', 'postgres']
2019-05-16T03:25:05.845177959Z localhost:5432 - accepting connections
2019-05-16T03:25:05.846796803Z 2019-05-16 05:25:05,846 INFO: Postgres call_nowait: bootstrapping: False, callback: {'on_stop': '/var/lib/postgresql/scripts/patroni_callback.py', 'on_start': '/var/lib/postgresql/scripts/patroni_callback.py', 'on_role_change': '/var/lib/postgresql/scripts/patroni_callback.py'}, cb_name: on_start
2019-05-16T03:25:05.846881977Z 2019-05-16 05:25:05,846 INFO: Postgres call callback: on_start, role: replica, scope: test-db-pg
2019-05-16T03:25:05.84701597Z 2019-05-16 05:25:05,846 INFO: Postgres call callback: on_start, cmd: ['/var/lib/postgresql/scripts/patroni_callback.py', 'on_start', 'replica', 'test-db-pg']
2019-05-16T03:25:05.847160807Z 2019-05-16 05:25:05,847 INFO: Postgres call_nowait: bootstrapping: False, callback: {'on_stop': '/var/lib/postgresql/scripts/patroni_callback.py', 'on_start': '/var/lib/postgresql/scripts/patroni_callback.py', 'on_role_change': '/var/lib/postgresql/scripts/patroni_callback.py'}, cb_name: on_role_change
2019-05-16T03:25:05.8473782Z 2019-05-16 05:25:05,847 INFO: Postgres call callback: on_role_change, role: replica, scope: test-db-pg
2019-05-16T03:25:05.85026448Z 2019-05-16 05:25:05,849 INFO: Postgres call callback: on_role_change, cmd: ['/var/lib/postgresql/scripts/patroni_callback.py', 'on_role_change', 'replica', 'test-db-pg']
2019-05-16T03:25:06.461133147Z 2019-05-16 05:25:06,460 WARNING: Killed the old callback process because it was still running: ['/var/lib/postgresql/scripts/patroni_callback.py', 'on_start', 'replica', 'test-db-pg']
2019-05-16T03:25:06.531545185Z 2019-05-16 05:25:06,531 INFO: Lock owner: test-db-pg-1; I am test-db-pg-0
2019-05-16T03:25:06.53207006Z 2019-05-16 05:25:06,531 INFO: does not have lock
2019-05-16T03:25:06.532091478Z 2019-05-16 05:25:06,531 INFO: establishing a new patroni connection to the postgres cluster
2019-05-16T03:25:06.542053911Z 2019-05-16 05:25:06,541 INFO: Local timeline=2 lsn=0/3037F78
2019-05-16T03:25:06.550319649Z 2019-05-16 05:25:06,550 INFO: master_timeline=2
2019-05-16T03:25:06.551032731Z 2019-05-16 05:25:06,550 INFO: master: history=1	0/3032098	no recovery target specified
2019-05-16T03:25:06.551049279Z 
2019-05-16T03:25:06.604161699Z 2019-05-16 05:25:06,603 INFO: no action.  i am a secondary and i am following a leader
2019-05-16T03:25:07.452981227Z 2019-05-16 05:25:07,452 INFO: callback: cluster: test-db-pg, namespace: clean-install, role: replica, action: on_role_change
2019-05-16T03:25:07.453004803Z 2019-05-16 05:25:07,452 INFO: add_endpoint: endpoint_name: test-db-pg-replica, namespace: clean-install
2019-05-16T03:25:07.467548287Z 2019-05-16 05:25:07,466 INFO: add_subset subsets before: None, ip: 192.168.9.148
2019-05-16T03:25:07.467564662Z 2019-05-16 05:25:07,467 INFO: add_subset subsets final: [{'addresses': [{'hostname': None,
2019-05-16T03:25:07.467567899Z                 'ip': '192.168.9.148',
2019-05-16T03:25:07.467570739Z                 'node_name': None,
2019-05-16T03:25:07.467573308Z                 'target_ref': None}],
2019-05-16T03:25:07.467576082Z  'not_ready_addresses': None,
2019-05-16T03:25:07.467578667Z  'ports': [{'name': 'postgresql', 'port': 5432, 'protocol': None},
2019-05-16T03:25:07.467586575Z            {'name': 'metrics', 'port': 9187, 'protocol': None}]}]
2019-05-16T03:25:13.555914624Z 2019-05-16 05:25:13,555 INFO: Lock owner: test-db-pg-1; I am test-db-pg-0
2019-05-16T03:25:13.555938522Z 2019-05-16 05:25:13,555 INFO: does not have lock
2019-05-16T03:25:13.556743045Z 2019-05-16 05:25:13,556 INFO: no action.  i am a secondary and i am following a leader
2019-05-16T03:25:23.518980667Z 2019-05-16 05:25:23,517 INFO: Lock owner: test-db-pg-1; I am test-db-pg-0
2019-05-16T03:25:23.519001519Z 2019-05-16 05:25:23,517 INFO: does not have lock
2019-05-16T03:25:23.519005116Z 2019-05-16 05:25:23,517 INFO: no action.  i am a secondary and i am following a leader
2019-05-16T03:25:33.573893607Z 2019-05-16 05:25:33,573 INFO: Lock owner: test-db-pg-1; I am test-db-pg-0`

**Comment by CyberDem0n** [comment]
> We use helm to install our patroni in kubenretes cluster, and delete the rbac rule carelessly, a second later, we recreate the rbac rule
Then we check the patroni log , it enters a chaos status

If you shoot your own leg it hurts.

When Patroni can't access K8s API it demotes postgres.

**Comment by zhangmingld** [comment]
@CyberDem0n 
It is not only demoted，as the log says, first it stops itsself then started as a replica
That is normal 
but later,
a role_change to replica happens
`2019-05-16T03:25:01.240681184Z 2019-05-16 05:25:01,240 INFO: Postgres call callback: on_role_change, cmd: ['/var/lib/postgresql/scripts/patroni_callback.py', 'on_role_change', 'replica', 'test-db-pg']`

then, a moment later
a master stop happens
`05-16T03:25:02.714018912Z 2019-05-16 05:25:02,712 INFO: Postgres call callback: on_stop, cmd: ['/var/lib/postgresql/scripts/patroni_callback.py', 'on_stop', 'master', 'test-db-pg'] `

later, an start as replica happens 
`2019-05-16T03:25:05.84701597Z 2019-05-16 05:25:05,846 INFO: Postgres call callback: on_start, cmd: ['/var/lib/postgresql/scripts/patroni_callback.py', 'on_start', 'replica', 'test-db-pg'] `

then it says it has a on_role_change to replica
`2019-05-16T03:25:05.85026448Z 2019-05-16 05:25:05,849 INFO: Postgres call callback: on_role_change, cmd: ['/var/lib/postgresql/scripts/patroni_callback.py', 'on_role_change', 'replica', 'test-db-pg'] `

finally it starts as a replica
`2019-05-16T03:25:06.461133147Z 2019-05-16 05:25:06,460 WARNING: Killed the old callback process because it was still running: ['/var/lib/postgresql/scripts/patroni_callback.py', 'on_start', 'replica', 'test-db-pg']`

So, here is the problem , a k8s error can lead so many role change ?

The patroni should just change to replica or start as a replica rather than so many changes (start as -->replica--> on_role_chage to replica --> on_stop master --> start as replica --> on_role_change to replica --> start as replica )

**Comment by zhangmingld** [comment]
Can anyone help to look at this ?

**Comment by CyberDem0n** [comment]
What Patroni version do you run?

**Comment by zhangmingld** [comment]
@CyberDem0n  
document-database-pg-0:/ # patronictl version
patronictl version 1.5.1

**Comment by CyberDem0n** [comment]
That's quite an outdated version.
In 1.5.6 there were some changes in this area.
