### ISSUE TITLE
Pod repeately generate core-file

### ISSUE THREAD

**Issue by henrywangx** [zalando/patroni#1093]
Hi, 
Have you ever faced the pod repeately generate core-files? After running serval days, one of my testbed has faced this issue. I use the example of k8s to deploy(with a PV). And I also faced it before, but it was killed by SIGBUS, I guess it's caused by hugepage. This testbed, I don't know why it's killed by SIGABRT.
log of one pod:

```
2019-06-17 10:07:28.100 GMT [443] FATAL:  the database system is starting up
localhost:5432 - rejecting connections
2019-06-17 10:07:28.107 GMT [439] LOG:  entering standby mode
2019-06-17 10:07:28.107 GMT [439] LOG:  could not read from log segment 0000005D0000000000000026, offset 0: No such file or directory
2019-06-17 10:07:28.107 GMT [439] LOG:  invalid primary checkpoint record
2019-06-17 10:07:28.107 GMT [439] LOG:  invalid secondary checkpoint record
2019-06-17 10:07:28.107 GMT [439] PANIC:  could not locate a valid checkpoint record
2019-06-17 10:07:28.800 GMT [436] LOG:  startup process (PID 439) was terminated by signal 6: Aborted
2019-06-17 10:07:28.800 GMT [436] LOG:  aborting startup due to startup process failure
2019-06-17 10:07:28.824 GMT [436] LOG:  database system is shut down
localhost:5432 - no response
2019-06-17 10:07:29,162 WARNING: Postgresql is not running.
2019-06-17 10:07:29,163 INFO: Lock owner: timescaledb-1; I am timescaledb-2
2019-06-17 10:07:29,170 INFO: Reaped pid=445, exit status=0
2019-06-17 10:07:29,171 INFO: pg_controldata:
  WAL block size: 8192
  Latest checkpoint's oldestMultiXid: 1
  Mock authentication nonce: 422c67104fab59de588bd4da35b91c2ba9a08e36af8394840856b3754cd5a4a5
  Latest checkpoint's REDO WAL file: 0000005D0000000000000026
  Latest checkpoint's full_page_writes: on
  Date/time type storage: 64-bit integers
  Time of latest checkpoint: Fri Jun 14 11:37:11 2019
  Data page checksum version: 1
  Latest checkpoint's NextMultiOffset: 0
  Latest checkpoint location: 0/26BB1F58
  Latest checkpoint's oldestActiveXID: 1349298
  Database cluster state: in production
  Maximum size of a TOAST chunk: 1996
  Fake LSN counter for unlogged rels: 0/1
  Database block size: 8192
  max_prepared_xacts setting: 0
  Database system identifier: 6701709978291933247
  Minimum recovery ending location: 0/0
  Maximum length of identifiers: 64
  Min recovery ending loc's timeline: 0
  max_worker_processes setting: 8
  Backup start location: 0/0
  Prior checkpoint location: 0/26B171F8
  pg_control last modified: Fri Jun 14 11:37:29 2019
  Latest checkpoint's newestCommitTsXid: 0
  Latest checkpoint's PrevTimeLineID: 93
  Bytes per WAL segment: 16777216
  track_commit_timestamp setting: off
  wal_log_hints setting: on
  Latest checkpoint's NextXID: 0:1349298
  Backup end location: 0/0
  Float4 argument passing: by value
  Latest checkpoint's REDO location: 0/26B97278
  Float8 argument passing: by value
  Latest checkpoint's NextOID: 448989
  Catalog version number: 201707211
  Latest checkpoint's oldestCommitTsXid: 0
  max_locks_per_xact setting: 64
  End-of-backup record required: no
  Latest checkpoint's oldestXID's DB: 1
  max_connections setting: 300
  Latest checkpoint's oldestMulti's DB: 1
  Blocks per segment of large relation: 131072
  Maximum data alignment: 8
  Maximum columns in an index: 32
  wal_level setting: replica
  Latest checkpoint's NextMultiXactId: 1
  pg_control version number: 1002
  Latest checkpoint's TimeLineID: 93
  Latest checkpoint's oldestXID: 549
  Size of a large-object chunk: 2048

2019-06-17 10:07:29,196 INFO: Lock owner: timescaledb-1; I am timescaledb-2
2019-06-17 10:07:29,210 INFO: Reaped pid=447, exit status=0
2019-06-17 10:07:29,218 INFO: Reaped pid=448, exit status=0
```
And I tried gdb for debugging it:

```
postgres@timescaledb-0:~$ gdb /usr/lib/postgresql/10/bin/postgres /home/postgres/pgdata/pgroot/data/core.10023
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/lib/postgresql/10/bin/postgres...Reading symbols from /usr/lib/debug/.build-id/df/f232473b3978e93a857ed976b76be894fd3676.debug...done.
done.
[New LWP 1343]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `postgres: timescaledb: startup process   recovering 0000005D0000000000000026  '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f1e5ecfafff in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007f1e5ecfafff in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f1e5ecfc42a in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x000055d3e4dfbaad in errfinish (dummy=<optimized out>) at ./build/../src/backend/utils/error/elog.c:555
#3  0x000055d3e4aa7137 in StartupXLOG () at ./build/../src/backend/access/transam/xlog.c:6283
#4  0x000055d3e4c79f13 in StartupProcessMain () at ./build/../src/backend/postmaster/startup.c:211
#5  0x000055d3e4ab4758 in AuxiliaryProcessMain (argc=argc@entry=2, argv=argv@entry=0x7ffcdb77beb0) at ./build/../src/backend/bootstrap/bootstrap.c:426
#6  0x000055d3e4c76d9b in StartChildProcess (type=StartupProcess) at ./build/../src/backend/postmaster/postmaster.c:5361
#7  0x000055d3e4c798c6 in PostmasterMain (argc=17, argv=0x55d3e6ce4d90) at ./build/../src/backend/postmaster/postmaster.c:1355
#8  0x000055d3e4a21124 in main (argc=17, argv=0x55d3e6ce4d90) at ./build/../src/backend/main/main.c:228

```

**Comment by CyberDem0n** [comment]
This is not really a Patroni problem.
