### ISSUE TITLE
haproxy check master or replica error

### ISSUE THREAD

**Issue by Liuzhj** [zalando/patroni#1098]
patroni: 1.5.6
haproxy: 1.5.18

haproxy.cfg
```
listen pg_master
    bind *:5432
    mode tcp
    option httplog
    option http-server-close
    option httpchk OPTIONS /master
    http-check expect status 200
    default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions
    server postgresql_xx_5432 xx:5432  maxconn 100 check port 8008
    server postgresql_xx_5432 xx:5432  maxconn 100 check port 8008
    server postgresql_xx_5432 xx:5432  maxconn 100 check port 8008
```

patroni_error.log
```
Jun 27 21:48:48 centos7 patroni: 2019-06-27 21:48:48,568 WARNING: Exception happened during processing of request from 192.168.10.69:37822
Jun 27 21:48:48 centos7 patroni: 2019-06-27 21:48:48,568 WARNING: Traceback (most recent call last):
Jun 27 21:48:48 centos7 patroni: File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
Jun 27 21:48:48 centos7 patroni: self.finish_request(request, client_address)
Jun 27 21:48:48 centos7 patroni: File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
Jun 27 21:48:48 centos7 patroni: self.RequestHandlerClass(request, client_address, self)
Jun 27 21:48:48 centos7 patroni: File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
Jun 27 21:48:48 centos7 patroni: self.finish()
Jun 27 21:48:48 centos7 patroni: File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
Jun 27 21:48:48 centos7 patroni: self.wfile.close()
Jun 27 21:48:48 centos7 patroni: File "/usr/lib64/python2.7/socket.py", line 279, in close
Jun 27 21:48:48 centos7 patroni: self.flush()
Jun 27 21:48:48 centos7 patroni: File "/usr/lib64/python2.7/socket.py", line 303, in flush
Jun 27 21:48:48 centos7 patroni: self._sock.sendall(view[write_offset:write_offset+buffer_size])
Jun 27 21:48:48 centos7 patroni: error: [Errno 32] Broken pipe
```

- symptom
haproxy check master `option httpchk OPTIONS /master` is correctly。
but check other replica nodes is error. 

how to solved it ? 
looks like it is bug ?

**Comment by CyberDem0n** [comment]
Such error logs are the indicator that HAProxy is closing the connection too early.
They are annoying but harmless.
Could you please to try to remove `option http-server-close`?
