### ISSUE TITLE
Patronictl Error

### ISSUE THREAD

**Issue by anikin-aa** [zalando/patroni#1100]
Hi, we have faced next error during patronictl call
```
Traceback (most recent call last):
  File "/patroni/patronictl.py", line 5, in <module>
    ctl(None)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/patroni/patroni/ctl.py", line 814, in members
    output_members(cluster, cluster_name, extended, fmt)
  File "/patroni/patroni/ctl.py", line 723, in output_members
    append_port = any(str(m.conn_kwargs()['port']) != '5432' for m in cluster.members) or\
  File "/patroni/patroni/ctl.py", line 723, in <genexpr>
    append_port = any(str(m.conn_kwargs()['port']) != '5432' for m in cluster.members) or\
  File "/patroni/patroni/dcs/__init__.py", line 155, in conn_kwargs
    r = urlparse(self.conn_url)
  File "/usr/lib64/python2.7/urlparse.py", line 142, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib64/python2.7/urlparse.py", line 196, in urlsplit
    i = url.find(':')
AttributeError: 'NoneType' object has no attribute 'find'
```

Could you please help with this ?
From trace I can see, that patroni is trying to parse conn_url from cluster member. 
What is the potential problem can be ?
All of the pods got parsable conn_url in annontation.

We are running patroni in OpenShift, using ConfigMaps as a DCS.
Patroni ver 1.5.6

Thanks.

**Comment by CyberDem0n** [comment]
Could you please change the `log.level` to `DEBUG` and post here the logs?

**Comment by anikin-aa** [comment]
Right now problem is not reproducible, patronictl works fine.
We've got some kind of cron job that from time to time check patroni status via patronictl and in some cases patronictl fails.
So I think right now `DEBUG` logs will not help.
