### ISSUE TITLE
Patroni requires services create permission in Kubernetes

### ISSUE THREAD

**Issue by jorsol** [zalando/patroni#1132]
I'm using patroni in Kubernetes, create a ServiceAccount and a Role without the "create" permision for "Services" since I create the service manually (the headless service to avoid deletion of example-config endpoint) but starting patroni gives me this error:

```
2019-08-02 14:48:15,882 ERROR: create_config_service failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/patroni/dcs/kubernetes.py", line 298, in _create_config_service
    if not self._api.create_namespaced_service(self._namespace, body):
  File "/usr/lib/python2.7/site-packages/patroni/dcs/kubernetes.py", line 50, in wrapper
    return getattr(self._api, func)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 6820, in create_namespaced_service
    (data) = self.create_namespaced_service_with_http_info(namespace, body, **kwargs)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 6905, in create_namespaced_service_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 364, in request
    body=body)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/rest.py", line 266, in POST
    body=body)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Date': 'Fri, 02 Aug 2019 14:48:15 GMT', 'Content-Length': '314', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services is forbidden: User \"system:serviceaccount:default:example-patroni\" cannot create resource \"services\" in API group \"\" in the namespace \"default\"","reason":"Forbidden","details":{"kind":"services"},"code":403}
```

Acording to the kubernetes example it should not be required: https://github.com/zalando/patroni/blob/0b1b1e3b542714b47634391f7dbb00016d885bff/kubernetes/patroni_k8s.yaml#L190-L199

**Comment by CyberDem0n** [comment]
Interesting, it fails with `403 Forbidden`, not with 409...
It shouldn't be so hard to fix it by doing an explicit check that service already exists.

**Comment by phin1x** [comment]
Are there any updates on this issue? we faced the same problems with the version 2.1.0.

**Comment by nhudson** [comment]
Just created a PR to hopefully address this in #2390, though it seems weird to just be adding another `or` statement to just work around the issue.
