### ISSUE TITLE
Problem starting sample configuration with "./patroni.py postgres0.yml"

### ISSUE THREAD

**Issue by Sasquash23** [zalando/patroni#1143]
In installed all the prerequisites and started etcd.

When I run the command ./patroni /etc/patroni.yml as root, I get:
2019-08-07 18:18:41,025 INFO: Failed to import patroni.dcs.consul
2019-08-07 18:18:41,042 INFO: Selected new etcd server http://10.111.110.112:2379
2019-08-07 18:18:41,058 INFO: No PostgreSQL configuration items changed, nothing to reload.
2019-08-07 18:18:41,068 INFO: Lock owner: None; I am postgresql0
2019-08-07 18:18:41,072 INFO: trying to bootstrap a new cluster
pg_ctl: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that will
own the server process.
2019-08-07 18:18:41,081 INFO: removing initialize key after failed attempt to bootstrap the cluster
2019-08-07 18:18:41,564 INFO: Lock owner: None; I am postgresql0
Traceback (most recent call last):
  File "./patroni", line 10, in <module>
    sys.exit(main())
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/patroni/__init__.py", line 196, in main
    return patroni_main()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/patroni/__init__.py", line 160, in patroni_main
    patroni.run()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/patroni/__init__.py", line 125, in run
    logger.info(self.ha.run_cycle())
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/patroni/ha.py", line 1344, in run_cycle
    info = self._run_cycle()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/patroni/ha.py", line 1253, in _run_cycle
    return self.post_bootstrap()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/patroni/ha.py", line 1149, in post_bootstrap
    self.cancel_initialization()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/patroni/ha.py", line 1144, in cancel_initialization
    raise PatroniException('Failed to bootstrap cluster')
patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'

AS root I cannot start postgres instance.
But when I try to start it as postgres:
Traceback (most recent call last):
  File "./patroni", line 6, in <module>
    from patroni import main
ImportError: cannot import name 'main'

**Comment by Sasquash23** [comment]
versions
patroni v1.6.0
python 3.6.3
Red Hat Enterprise Linux Server release 7.6 (Maipo).

The library patroni.dcs.consul has been installed.

**Comment by anikin-aa** [comment]
@Sasquash23 hi there, this is a limitation of PostgreSQL, you should run patronictl from not root user, but from `postgres`, f.e.

**Comment by cleitondomazak** [comment]
If you run this with the `root` some conf files will be changed for the `root` and the permissions will be set applied for him and the PostgreSQL will break. 

Is possible to add a check and do not start the process without `postgres` user?

**Comment by janezpenkosajn** [comment]
I have a similar problem, I try to run sample config under "postgres" user. I get the folowing error:

2019-09-16 09:25:09,449 INFO: Failed to import patroni.dcs.consul
2019-09-16 09:25:09,462 INFO: Selected new etcd server http://127.0.0.1:2379
2019-09-16 09:25:09,475 INFO: No PostgreSQL configuration items changed, nothing to reload.
2019-09-16 09:25:09,479 INFO: Lock owner: None; I am postgresql0
2019-09-16 09:25:09,483 INFO: trying to bootstrap a new cluster
2019-09-16 09:25:09,489 ERROR: Exception during execution of long running task bootstrap
Traceback (most recent call last):
  File "/home/janez/repos/patroni/patroni/async_executor.py", line 97, in run
    wakeup = func(*args) if args else func()
  File "/home/janez/repos/patroni/patroni/postgresql/bootstrap.py", line 305, in bootstrap
    return do_initialize(config.get(method)) and self._postgresql.config.append_pg_hba(pg_hba) \
  File "/home/janez/repos/patroni/patroni/postgresql/bootstrap.py", line 80, in _initdb
    ret = self._postgresql.pg_ctl('initdb', *options)
  File "/home/janez/repos/patroni/patroni/postgresql/__init__.py", line 166, in pg_ctl
    return subprocess.call(pg_ctl + ['-D', self._data_dir] + list(args), **kwargs) == 0
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
2019-09-16 09:25:09,495 INFO: removing initialize key after failed attempt to bootstrap the cluster
2019-09-16 09:25:09,978 INFO: Lock owner: None; I am postgresql0
Traceback (most recent call last):
  File "./patroni.py", line 6, in <module>
    main()
  File "/home/janez/repos/patroni/patroni/__init__.py", line 196, in main
    return patroni_main()
  File "/home/janez/repos/patroni/patroni/__init__.py", line 160, in patroni_main
    patroni.run()
  File "/home/janez/repos/patroni/patroni/__init__.py", line 125, in run
    logger.info(self.ha.run_cycle())
  File "/home/janez/repos/patroni/patroni/ha.py", line 1344, in run_cycle
    info = self._run_cycle()
  File "/home/janez/repos/patroni/patroni/ha.py", line 1253, in _run_cycle
    return self.post_bootstrap()
  File "/home/janez/repos/patroni/patroni/ha.py", line 1149, in post_bootstrap
    self.cancel_initialization()
  File "/home/janez/repos/patroni/patroni/ha.py", line 1144, in cancel_initialization
    raise PatroniException('Failed to bootstrap cluster')
patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'

The "etcd" is running, all the prerequisit python modules are installed.

**Comment by CyberDem0n** [comment]
It can't find postgres binaries.
Please either set `postgresql.bin_dir` or make postgres binaries available in the `PATH`.

**Comment by Sasquash23** [comment]
Hi,
Problem has been solved.
Some files in python directories had too low permission, that is why postgres has no access.
Thank you for help.

**Comment by amadhaka** [comment]
Hi Sasquash :- where did you find the above logs , location plz i am trying to install and start patroni and getting very similar issues on RHEL.
Thanks,
Aman

**Comment by Sasquash23** [comment]
Hi,
You can list python by command:
ls /usr/bin/python*
