### ISSUE TITLE
[etcd] EtcdKeyNotFound - failed to update leader lock - PG restart

### ISSUE THREAD

**Issue by Soulou** [zalando/patroni#1181]
Setup:

* 3 ETCD dedicated nodes, working for months, with fast disk
* Patroni 1.6.0
* PG 11.2

Today, out of the blue, my database leader just restarted being demoted, after failing to update its etcd key (it seems)

What could lead suddenly to such an error: EtcdKeyNotFound ?

The ETCD cluster was fine and running, nothing weird in the logs:

Here are patroni/pg logs: 

```
2019-09-17 16:24:57.330335749 +0200 CEST [postgresql-1] 2019-09-17 14:24:57,200 ERROR:
2019-09-17 16:24:57.330339517 +0200 CEST [postgresql-1] Traceback (most recent call last):
2019-09-17 16:24:57.330340498 +0200 CEST [postgresql-1] File "/usr/local/lib/python2.7/dist-packages/patroni/dcs/etcd.py", line 339, in wrapper
2019-09-17 16:24:57.330417685 +0200 CEST [postgresql-1] retval = func(self, *args, **kwargs) is not None
2019-09-17 16:24:57.330421479 +0200 CEST [postgresql-1] File "/usr/local/lib/python2.7/dist-packages/patroni/dcs/etcd.py", line 538, in _update_leader
2019-09-17 16:24:57.330422507 +0200 CEST [postgresql-1] return self.retry(self._client.test_and_set, self.leader_path, self._name, self._name, self._ttl)
2019-09-17 16:24:57.330714975 +0200 CEST [postgresql-1] File "/usr/local/lib/python2.7/dist-packages/patroni/dcs/etcd.py", line 323, in retry
2019-09-17 16:24:57.330798212 +0200 CEST [postgresql-1] return self._retry.copy()(*args, **kwargs)
2019-09-17 16:24:57.330799501 +0200 CEST [postgresql-1] File "/usr/local/lib/python2.7/dist-packages/patroni/utils.py", line 313, in __call__
2019-09-17 16:24:57.330800258 +0200 CEST [postgresql-1] return func(*args, **kwargs)
2019-09-17 16:24:57.330800887 +0200 CEST [postgresql-1] File "/usr/local/lib/python2.7/dist-packages/etcd/client.py", line 703, in test_and_set
2019-09-17 16:24:57.330801519 +0200 CEST [postgresql-1] return self.write(key, value, prevValue=prev_value, ttl=ttl)
2019-09-17 16:24:57.330802394 +0200 CEST [postgresql-1] File "/usr/local/lib/python2.7/dist-packages/etcd/client.py", line 500, in write
2019-09-17 16:24:57.330865473 +0200 CEST [postgresql-1] response = self.api_execute(path, method, params=params)
2019-09-17 16:24:57.330885498 +0200 CEST [postgresql-1] File "/usr/local/lib/python2.7/dist-packages/patroni/dcs/etcd.py", line 218, in api_execute
2019-09-17 16:24:57.330940371 +0200 CEST [postgresql-1] return self._handle_server_response(response)
2019-09-17 16:24:57.330942924 +0200 CEST [postgresql-1] File "/usr/local/lib/python2.7/dist-packages/etcd/client.py", line 987, in _handle_server_response
2019-09-17 16:24:57.330944876 +0200 CEST [postgresql-1] etcd.EtcdError.handle(r)
2019-09-17 16:24:57.330947113 +0200 CEST [postgresql-1] File "/usr/local/lib/python2.7/dist-packages/etcd/__init__.py", line 306, in handle
2019-09-17 16:24:57.330971771 +0200 CEST [postgresql-1] raise exc(msg, payload)
2019-09-17 16:24:57.330976927 +0200 CEST [postgresql-1] EtcdKeyNotFound: Key not found : /postgresql_clusters/<cluster name>/leader
2019-09-17 16:24:58.153470514 +0200 CEST [postgresql-1] 2019-09-17 14:24:57,330 ERROR: failed to update leader lock
2019-09-17 16:25:00.055973491 +0200 CEST [postgresql-1] 2019-09-17 14:25:00 UTC LOG:  received immediate shutdown request
```

If you could give me any way to look it would be great. Thanks a lot.

-- Léo

**Comment by Soulou** [comment]
Configuration of DCS:

```
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
```

and via ENV:

```
# env | grep PATRONI
PATRONI_ETCD_CERT=/path
PATRONI_ETCD_CACERT=/path
PATRONI_ETCD_PASSWORD=<password>
PATRONI_ETCD_HOSTS='10.0.0.1:2381','10.0.0.#2:2381','10.0.0.#3:2381'
PATRONI_ETCD_USERNAME=<username>
PATRONI_ETCD_KEY=/path
PATRONI_ETCD_PROTOCOL=https
```

**Comment by CyberDem0n** [comment]
It works exactly as designed. If update of leader key failed, postgres should not be running as master and restarted in read-only.
When was the last time leader key updated? You should analyse more patroni logs, I am pretty sure there's some answer.

**Comment by Soulou** [comment]
Thanks @CyberDem0n I've more details about the behavior here.

This happen during a `pg_restore`, especially during the creation of indexes taking most of the resources of the server. So I assume patroni is slowed down, and fails to refresh leader etcd key on time. Does this sound possible to you? 

What do you think is the best way to handle this situation?

**Comment by CyberDem0n** [comment]
Yes, it is totally possible.
You can mitigate the problem by increasing the `ttl`, and `retry_timeout`.

**Comment by Soulou** [comment]
Ok we're giving it a try now, thanks.

**Comment by Soulou** [comment]
Ok since I've increased those values, I haven't been able to reproduce the problem here, so I'm closing this for now, thanks for your help
