### ISSUE TITLE
Patroni starts master demotion before retry_timeout exceeded

### ISSUE THREAD

**Issue by psuderevsky** [zalando/patroni#1195]
Patroni version: 1.6.0
PostgreSQL version: 11.5
Configuration
```
ttl=30
retry_timeout=10
loop_wait=10
```

**Test 1 - etcd cluster is unhealthy**
**Action:** `for i in {1..100000}; do date; pkill -KILL etcd ; sleep 0.5; done` 
**Nodes:** all
**Condition:** Leader TTL=23, etcd systemd service restart option set to "on-failure"
**Result:** master started demotion in 2-2 seconds, etcd service stopped trying restarting in 3 seconds
**Service interruption:** until manual etcd start 

**Test 2 - etcd cluster is unhealthy**
**Action:** `pkill -KILL etcd ; sleep 7; systemctl start etcd`
**Nodes:** all
**Condition:** Leader TTL=22, etcd systemd service restart option set to "no"
**Result:** master started demotion in 1-2 seconds, was demoted in 4 seconds, promoted back to master in 11 seconds(4 seconds after etcd start) 
**Service interruption:** 11 seconds

**Test 3 - network interface is down**
**Action:** `ifdown int_name && sleep 8 && ifup int_name`
**Nodes:** all
**Condition:** Leader TTL=22
**Result:** etcd leader has been re-elected after 10 seconds, master started shutting down after 3 seconds (duration = 9 seconds),promoted to master after 12 seconds
**Service interruption:** 12 seconds

**Documentations says:** _retry_timeout: timeout for DCS and PostgreSQL operation retries. DCS or network issues shorter than this will not cause Patroni to demote the leader. Default value: 10_
Actual demotion time with the default settings should be between 10 and 20 seconds.

**In fact:** Demotion performed right after _loop_wait_ exceeded, i.e. when ttl = (ttl - loop_wait).

Test 2 patroni log for example:
```
Sep 27 07:14:47 dbserver3 patroni[308623]: 2019-09-27 07:14:47,558 INFO: Lock owner: pg3; I am pg3
Sep 27 07:14:47 dbserver3 patroni[308623]: 2019-09-27 07:14:47,562 INFO: no action.  i am the leader with the lock
Sep 27 07:14:57 dbserver3 patroni[308623]: 2019-09-27 07:14:57,559 INFO: Lock owner: pg3; I am pg3
Sep 27 07:14:57 dbserver3 patroni[308623]: 2019-09-27 07:14:57,564 INFO: no action.  i am the leader with the lock
Sep 27 07:15:07 dbserver3 patroni[308623]: 2019-09-27 07:15:07,557 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewCon
Sep 27 07:15:07 dbserver3 patroni[308623]: 2019-09-27 07:15:07,558 ERROR: Request to server https://8.8.85.2:2379 failed: MaxRetryError("HTTPSConnectionPool(host='8.8.85.2', port=2
Sep 27 07:15:07 dbserver3 patroni[308623]: 2019-09-27 07:15:07,558 INFO: Reconnection allowed, looking for another server.
Sep 27 07:15:07 dbserver3 patroni[308623]: 2019-09-27 07:15:07,558 INFO: Selected new etcd server https://8.8.84.2:2379
Sep 27 07:15:07 dbserver3 patroni[308623]: 2019-09-27 07:15:07,559 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewCon
Sep 27 07:15:07 dbserver3 patroni[308623]: 2019-09-27 07:15:07,560 ERROR: Request to server https://8.8.84.2:2379 failed: MaxRetryError(u"HTTPSConnectionPool(host=u'8.8.84.2', port
Sep 27 07:15:07 dbserver3 patroni[308623]: 2019-09-27 07:15:07,560 INFO: Reconnection allowed, looking for another server.
Sep 27 07:15:07 dbserver3 patroni[308623]: 2019-09-27 07:15:07,560 INFO: Selected new etcd server https://8.8.81.2:2379
Sep 27 07:15:07 dbserver3 patroni[308623]: 2019-09-27 07:15:07,561 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewCon
Sep 27 07:15:07 dbserver3 patroni[308623]: 2019-09-27 07:15:07,562 ERROR: Request to server https://8.8.81.2:2379 failed: MaxRetryError(u"HTTPSConnectionPool(host=u'8.8.81.2', port
Sep 27 07:15:07 dbserver3 patroni[308623]: 2019-09-27 07:15:07,562 INFO: Reconnection allowed, looking for another server.
Sep 27 07:15:07 dbserver3 patroni[308623]: 2019-09-27 07:15:07,562 ERROR: Machines cache is empty, no machines to try.
Sep 27 07:15:07 dbserver3 patroni[308623]: 2019-09-27 07:15:07,562 ERROR: get_cluster
Sep 27 07:15:07 dbserver3 patroni[308623]: Traceback (most recent call last):
Sep 27 07:15:07 dbserver3 patroni[308623]: File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 455, in _load_cluster
Sep 27 07:15:07 dbserver3 patroni[308623]: result = self.retry(self._client.read, self.client_path(''), recursive=True)
Sep 27 07:15:07 dbserver3 patroni[308623]: File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 323, in retry
Sep 27 07:15:07 dbserver3 patroni[308623]: return self._retry.copy()(*args, **kwargs)
Sep 27 07:15:07 dbserver3 patroni[308623]: File "/usr/lib/python2.7/site-packages/patroni/utils.py", line 313, in __call__
Sep 27 07:15:07 dbserver3 patroni[308623]: return func(*args, **kwargs)
Sep 27 07:15:07 dbserver3 patroni[308623]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 597, in read
Sep 27 07:15:07 dbserver3 patroni[308623]: timeout=timeout)
Sep 27 07:15:07 dbserver3 patroni[308623]: File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 205, in api_execute
Sep 27 07:15:07 dbserver3 patroni[308623]: response = self._do_http_request(request_executor, method, self._base_uri + path, **kwargs)
Sep 27 07:15:07 dbserver3 patroni[308623]: File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 170, in _do_http_request
Sep 27 07:15:07 dbserver3 patroni[308623]: self._base_uri = self._next_server(cause=e)
Sep 27 07:15:07 dbserver3 patroni[308623]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 832, in _next_server
Sep 27 07:15:07 dbserver3 patroni[308623]: cause=cause)
Sep 27 07:15:07 dbserver3 patroni[308623]: EtcdConnectionFailed: No more machines in the cluster
Sep 27 07:15:07 dbserver3 patroni[308623]: 2019-09-27 07:15:07,563 ERROR: Error communicating with DCS
Sep 27 07:15:08 dbserver3 patroni[308623]: 2019-09-27 07:15:08,569 INFO: closed patroni connection to the postgresql cluster
Sep 27 07:15:08 dbserver3 patroni[308623]: 2019-09-27 07:15:08,581 INFO: postmaster pid=311544
Sep 27 07:15:08 dbserver3 patroni[308623]: 2019-09-27 12:15:08 UTC  LOG:  Auto detecting pg_stat_kcache.linux_hz parameter...
Sep 27 07:15:08 dbserver3 patroni[308623]: 2019-09-27 12:15:08 UTC  LOG:  pg_stat_kcache.linux_hz is set to 1000000
Sep 27 07:15:08 dbserver3 patroni[308623]: /var/run/postgresql:5432 - no response
Sep 27 07:15:08 dbserver3 patroni[308623]: 2019-09-27 12:15:08 UTC  LOG:  listening on IPv4 address "0.0.0.0", port 5432
Sep 27 07:15:08 dbserver3 patroni[308623]: 2019-09-27 12:15:08 UTC  LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
Sep 27 07:15:08 dbserver3 patroni[308623]: 2019-09-27 12:15:08 UTC  LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
Sep 27 07:15:10 dbserver3 patroni[308623]: 2019-09-27 12:15:10 UTC  LOG:  redirecting log output to logging collector process
Sep 27 07:15:10 dbserver3 patroni[308623]: 2019-09-27 12:15:10 UTC  HINT:  Future log output will appear in directory ".".
Sep 27 07:15:10 dbserver3 patroni[308623]: /var/run/postgresql:5432 - rejecting connections
Sep 27 07:15:10 dbserver3 patroni[308623]: /var/run/postgresql:5432 - accepting connections
Sep 27 07:15:10 dbserver3 patroni[308623]: 2019-09-27 07:15:10,961 INFO: demoted self because DCS is not accessible and i was a leader
Sep 27 07:15:17 dbserver3 patroni[308623]: 2019-09-27 07:15:17,556 INFO: Selected new etcd server https://8.8.85.2:2379
Sep 27 07:15:17 dbserver3 patroni[308623]: 2019-09-27 07:15:17,576 INFO: Lock owner: pg3; I am pg3
Sep 27 07:15:17 dbserver3 patroni[308623]: 2019-09-27 07:15:17,576 INFO: establishing a new patroni connection to the postgres cluster
Sep 27 07:15:17 dbserver3 patroni[308623]: 2019-09-27 07:15:17,581 INFO: wdat_wdt activated with 25 second timeout, timing slack 15 seconds
Sep 27 07:15:17 dbserver3 patroni[308623]: server signaled
Sep 27 07:15:17 dbserver3 patroni[308623]: 2019-09-27 07:15:17,591 INFO: promoted self to leader because i had the session lock
Sep 27 07:15:17 dbserver3 patroni[308623]: server promoting
Sep 27 07:15:17 dbserver3 patroni[308623]: 2019-09-27 07:15:17,595 INFO: cleared rewind state after becoming the leader
Sep 27 07:15:18 dbserver3 patroni[308623]: 2019-09-27 07:15:18,612 INFO: Lock owner: pg3; I am pg3
Sep 27 07:15:18 dbserver3 patroni[308623]: 2019-09-27 07:15:18,621 INFO: Assigning synchronous standby status to pg2
Sep 27 07:15:18 dbserver3 patroni[308623]: server signaled
Sep 27 07:15:18 dbserver3 patroni[308623]: 2019-09-27 07:15:18,629 INFO: Synchronous standby status assigned to pg2
Sep 27 07:15:18 dbserver3 patroni[308623]: 2019-09-27 07:15:18,635 INFO: no action.  i am the leader with the lock
Sep 27 07:15:28 dbserver3 patroni[308623]: 2019-09-27 07:15:28,613 INFO: Lock owner: pg3; I am pg3
```

**Comment by CyberDem0n** [comment]
@psuderevsky it looks like you are doing a very extensive testing :+1:

Here is a possible fix https://github.com/zalando/patroni/compare/bugfix/etcd-retry, please try it.
If everything is fine I'll open a PR.

**Comment by psuderevsky** [comment]
@CyberDem0n Unfortunately, behaviour is totally the same with a provided fix (I've just replaced etcd.py for tests).
```
Sep 30 10:36:45 dbserver1 patroni[29630]: 2019-09-30 10:36:45,185 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='8.8.85.2', port=2379): Read timed out. (read timeout=1.66666666667)",)': /v2/keys/service/platform/?recursive=true
Sep 30 10:36:45 dbserver1 patroni[29630]: 2019-09-30 10:36:45,186 ERROR: Request to server https://8.8.85.2:2379 failed: MaxRetryError("HTTPSConnectionPool(host='8.8.85.2', port=23
79): Max retries exceeded with url: /v2/keys/service/platform/?recursive=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f09381dc050>: Failedb to establish a new connection: [Errno 101] Network is unreachable',))",)
Sep 30 10:36:45 dbserver1 patroni[29630]: 2019-09-30 10:36:45,186 INFO: Reconnection allowed, looking for another server.
Sep 30 10:36:45 dbserver1 patroni[29630]: 2019-09-30 10:36:45,186 INFO: Selected new etcd server https://8.8.81.2:2379
Sep 30 10:36:45 dbserver1 patroni[29630]: 2019-09-30 10:36:45,187 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0939046410>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /v2/keys/service/platform/?recursive=true
Sep 30 10:36:45 dbserver1 patroni[29630]: 2019-09-30 10:36:45,187 ERROR: Request to server https://8.8.81.2:2379 failed: MaxRetryError(u"HTTPSConnectionPool(host=u'8.8.81.2', port=
2379): Max retries exceeded with url: /v2/keys/service/platform/?recursive=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f09381b9a10>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",)
Sep 30 10:36:45 dbserver1 patroni[29630]: 2019-09-30 10:36:45,187 INFO: Reconnection allowed, looking for another server.
Sep 30 10:36:45 dbserver1 patroni[29630]: 2019-09-30 10:36:45,187 INFO: Selected new etcd server https://8.8.84.2:2379
Sep 30 10:36:45 dbserver1 patroni[29630]: 2019-09-30 10:36:45,188 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f09381b9a10>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /v2/keys/service/platform/?recursive=true
Sep 30 10:36:45 dbserver1 patroni[29630]: 2019-09-30 10:36:45,188 ERROR: Request to server https://8.8.84.2:2379 failed: MaxRetryError(u"HTTPSConnectionPool(host=u'8.8.84.2', port=
2379): Max retries exceeded with url: /v2/keys/service/platform/?recursive=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0939046a10>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",)
Sep 30 10:36:45 dbserver1 patroni[29630]: 2019-09-30 10:36:45,188 INFO: Reconnection allowed, looking for another server.
Sep 30 10:36:45 dbserver1 patroni[29630]: 2019-09-30 10:36:45,188 ERROR: Machines cache is empty, no machines to try.
Sep 30 10:36:45 dbserver1 patroni[29630]: 2019-09-30 10:36:45,188 ERROR: get_cluster
Sep 30 10:36:45 dbserver1 patroni[29630]: Traceback (most recent call last):
Sep 30 10:36:45 dbserver1 patroni[29630]: File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 455, in _load_cluster
Sep 30 10:36:45 dbserver1 patroni[29630]: File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 323, in retry
Sep 30 10:36:45 dbserver1 patroni[29630]: File "/usr/lib/python2.7/site-packages/patroni/utils.py", line 313, in __call__
Sep 30 10:36:45 dbserver1 patroni[29630]: return func(*args, **kwargs)
Sep 30 10:36:45 dbserver1 patroni[29630]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 597, in read
Sep 30 10:36:45 dbserver1 patroni[29630]: timeout=timeout)
Sep 30 10:36:45 dbserver1 patroni[29630]: File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 205, in api_execute
Sep 30 10:36:45 dbserver1 patroni[29630]: kwargs['encode_multipart'] = False
Sep 30 10:36:45 dbserver1 patroni[29630]: File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 170, in _do_http_request
Sep 30 10:36:45 dbserver1 patroni[29630]: raise etcd.EtcdException("Could not get the list of servers, "
Sep 30 10:36:45 dbserver1 patroni[29630]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 832, in _next_server
Sep 30 10:36:45 dbserver1 patroni[29630]: cause=cause)
Sep 30 10:36:45 dbserver1 patroni[29630]: EtcdConnectionFailed: No more machines in the cluster
Sep 30 10:36:45 dbserver1 patroni[29630]: 2019-09-30 10:36:45,188 ERROR: Error communicating with DCS
```
As far as I remember Patroni should perform `number of etcd hosts` retries every `retry_timeout / number of etcd hosts` seconds, but I'am not sure whether it must happen under all the possible conditions/exceptions.

**Comment by CyberDem0n** [comment]
Something is fishy. The following line can't appear in the stack trace:
 File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 205, in api_execute
Sep 30 10:36:45 dbserver1 patroni[29630]: kwargs['encode_multipart'] = False

**Comment by psuderevsky** [comment]
Ohh sorry. Now I've tested it again like a good guy and I do confirm that your fix works. Thank you!

The only confusing thing now is very uninformative logging. System log with the latest test results attached.
[patroni.1195.1.txt](https://github.com/zalando/patroni/files/3672337/patroni.1195.1.txt)

**Comment by CyberDem0n** [comment]
Yep, we need to have a back-off here.
