### ISSUE TITLE
Should the timeout of zookeeper could be configurable

### ISSUE THREAD

**Issue by henrywangx** [zalando/patroni#1250]
Hi guys,
Sometimes, I faced the patroni restart my database. I checked the log 

```bash
2019-10-24T09:40:42.790379000Z Traceback (most recent call last):
2019-10-24T09:40:42.790436000Z   File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/zookeeper.py", line 302, in touch_member
2019-10-24T09:40:42.790480000Z     self._client.set_async(self.member_path, encoded_data).get(timeout=1)
2019-10-24T09:40:42.790520000Z   File "/usr/local/lib/python3.5/dist-packages/kazoo/handlers/utils.py", line 78, in get
2019-10-24T09:40:42.790584000Z     raise self._timeout_factory()
2019-10-24T09:40:42.790628000Z kazoo.handlers.threading.KazooTimeoutError
```
Yes, this is highly possible caused by the busy io or busy zookeeper. But I'm wondering could `timeout=1` be dynamically according to retry-timeout. 1s may be too sensitive. whether we could enlarge this parameter to redunce those restart?

**Comment by CyberDem0n** [comment]
This exception is absolutely harmless.
Hardcoded timeout=1 is used only in places where it is 100% safe.
In this specific case it the update of member key didn't finish in 1 second, but this is fine, because on the next HA loop Patroni will still do it. Moreover, member and leader keys expiration is bound to the session. As long as Patroni is connected to one of zookeeper nodes keys will be there.

**Comment by henrywangx** [comment]
But it only retry 3 times. Since every time the timeout is 1s. So it's also high possible to failover since heartbeat can't reach. Right?

**Comment by CyberDem0n** [comment]
The `python-kazoo` is doing its own heartbeats (Pings) to zookeeper, and they are not controlled by Patroni. Zookeeper will invalidate the session when it didn't receive Pings during session_timeout.
There is absolutely no relation between `touch_member()` and Pings sent to zookeeper.
So you are wrong, it will not cause a failover.

**Comment by henrywangx** [comment]
ok, I got it. Thanks very much.
