### ISSUE TITLE
Can't start patroni service

### ISSUE THREAD

**Issue by tmpm697** [zalando/patroni#1271]
sudo vi /etc/patroni/config.yml
```
zookeeper:
  hosts: [zk1:2181, zk2:2181, zk3:2181] #this is line 8 in below
```

start service failed:
```
● patroni.service - Runners to orchestrate a high-availability PostgreSQL
   Loaded: loaded (/lib/systemd/system/patroni.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-11-11 05:25:22 UTC; 843ms ago
  Process: 6474 ExecStart=/usr/bin/patroni /etc/patroni/config.yml (code=exited, status=1/FAILURE)
 Main PID: 6474 (code=exited, status=1/FAILURE)

Nov 11 05:25:22 pt1 patroni[6474]:     self.tokens.append(self.scan_plain())
Nov 11 05:25:22 pt1 patroni[6474]:   File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 1299, in scan_plain
Nov 11 05:25:22 pt1 patroni[6474]:     "Please check http://pyyaml.org/wiki/YAMLColonInFlowContext for details.")
Nov 11 05:25:22 pt1 patroni[6474]: yaml.scanner.ScannerError: while scanning a plain scalar
Nov 11 05:25:22 pt1 patroni[6474]:   in "/etc/patroni/config.yml", line 8, column 11
Nov 11 05:25:22 pt1 patroni[6474]: found unexpected ':'
Nov 11 05:25:22 pt1 patroni[6474]:   in "/etc/patroni/config.yml", line 8, column 14
Nov 11 05:25:22 pt1 patroni[6474]: Please check http://pyyaml.org/wiki/YAMLColonInFlowContext for details.
Nov 11 05:25:22 pt1 systemd[1]: patroni.service: Main process exited, code=exited, status=1/FAILURE
Nov 11 05:25:22 pt1 systemd[1]: patroni.service: Failed with result 'exit-code'.
```

I don't have any clue why patroni can't start, it indicate that some wrong with zookeeper connection string, but from patroni nodes (pt1, pt2) I can totally connect to zk nodes:

```
echo "ruok" | nc zk1 2181; echo
imok
```

**Comment by CyberDem0n** [comment]
You have to quote host:port pairs.
Please look to the [documentation](https://github.com/zalando/patroni/blob/master/docs/SETTINGS.rst#zookeeper).

**Comment by tmpm697** [comment]
> You have to quote host:port pairs.
> Please look to the [documentation](https://github.com/zalando/patroni/blob/master/docs/SETTINGS.rst#zookeeper).

I installed `python-zookeeper` and quote host:port and still can't start patroni:
```
● patroni.service - Runners to orchestrate a high-availability PostgreSQL
   Loaded: loaded (/lib/systemd/system/patroni.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-11-11 08:11:42 UTC; 11s ago
  Process: 17972 ExecStart=/usr/bin/patroni /etc/patroni/config.yml (code=exited, status=1/FAILURE)
 Main PID: 17972 (code=exited, status=1/FAILURE)

Nov 11 08:11:42 pt1 patroni[17972]:     return patroni_main()
Nov 11 08:11:42 pt1 patroni[17972]:   File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 141, in patroni_main
Nov 11 08:11:42 pt1 patroni[17972]:     patroni = Patroni()
Nov 11 08:11:42 pt1 patroni[17972]:   File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 25, in __init__
Nov 11 08:11:42 pt1 patroni[17972]:     self.dcs = get_dcs(self.config)
Nov 11 08:11:42 pt1 patroni[17972]:   File "/usr/lib/python3/dist-packages/patroni/dcs/__init__.py", line 74, in get_dcs
Nov 11 08:11:42 pt1 patroni[17972]:     Available implementations: """ + ', '.join(available_implementations))
Nov 11 08:11:42 pt1 patroni[17972]: patroni.exceptions.PatroniException: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: etcd'
Nov 11 08:11:42 pt1 systemd[1]: patroni.service: Main process exited, code=exited, status=1/FAILURE
Nov 11 08:11:42 pt1 systemd[1]: patroni.service: Failed with result 'exit-code'.
```

**Comment by CyberDem0n** [comment]
That's because you have to install `python3-kazoo`

**Comment by tmpm697** [comment]
Another log:
```
patroni /etc/patroni/config.yml
2019-11-11 08:28:12,604 INFO: Failed to import patroni.dcs.consul
2019-11-11 08:28:12,639 INFO: Failed to import patroni.dcs.exhibitor
2019-11-11 08:28:12,640 INFO: Failed to import patroni.dcs.kubernetes
2019-11-11 08:28:12,646 INFO: Failed to import patroni.dcs.zookeeper
Traceback (most recent call last):
  File "/usr/bin/patroni", line 11, in <module>
    load_entry_point('patroni==1.6.0', 'console_scripts', 'patroni')()
  File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 196, in main
    return patroni_main()
  File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 158, in patroni_main
    patroni = Patroni()
  File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 28, in __init__
    self.dcs = get_dcs(self.config)
  File "/usr/lib/python3/dist-packages/patroni/dcs/__init__.py", line 95, in get_dcs
    Available implementations: """ + ', '.join(available_implementations))
patroni.exceptions.PatroniException: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: etcd'
```

**Comment by tmpm697** [comment]
> That's because you have to install `python3-kazoo`

my godness, is there instruction about install this package to make zookeeper work with patroni in readme.md?

**Comment by CyberDem0n** [comment]
Well, the [README.rst](https://github.com/zalando/patroni/blob/master/README.rst#technical-requirementsinstallation) tells that you have to use `pip install patroni[zookeeper]`. It will install all necesary dependancies.

**Comment by tmpm697** [comment]
> Well, the [README.rst](https://github.com/zalando/patroni/blob/master/README.rst#technical-requirementsinstallation) tells that you have to use `pip install patroni[zookeeper]`. It will install all necesary dependancies.

I install patroni via `apt install patroni`, beside that under ubuntu 18.04 issue command `pip install patroni[zookeeper]` give instruction about check `pip install help`

**Comment by CyberDem0n** [comment]
There is a way to figure out dependencies:
```
$ apt-cache show patroni
Package: patroni
Version: 1.6.0-4.pgdg18.04+1
Architecture: all
Maintainer: Debian PostgreSQL Maintainers <team+postgresql@tracker.debian.org>
Installed-Size: 564
Depends: python3-cdiff, python3-click (>= 4.1), python3-dateutil,
 python3-prettytable (>= 0.7), python3-psutil, python3-requests,
 python3-six (>= 1.7), python3-tzlocal, python3-urllib3, python3-yaml,
 python3:any (>= 3.5~), lsb-base (>= 3.0-6), python3-psycopg2,
 python3-etcd (>= 0.4.3) | python3-consul (>= 0.7.0) | python3-kazoo | python3-kubernetes
```
 **python3-etcd (>= 0.4.3) | python3-consul (>= 0.7.0) | python3-kazoo | python3-kubernetes**

If you want to improve the documentation - feel free top open a PR.

**Comment by tmpm697** [comment]
Thanks.
