### ISSUE TITLE
pg_ctl: database system initialization failed

### ISSUE THREAD

**Issue by qianyuyu** [zalando/patroni#1275]
I have installed Postgresql-9.5 and  used the command 
`/usr/pgsql-9.5/bin/postgresql95-setup initdb`
There are some files existed in the folder /var/lib/pgsql/9.5/data

Then I stop the postgre service and `mkdir /data/patroni`  according to the https://www.linode.com/docs/databases/postgresql/create-a-highly-available-postgresql-cluster-using-patroni-and-haproxy/

When I  START the Patroni the log is

```
Nov 13 02:11:48 localhost.localdomain polkitd[5599]: Unregistered Authentication Agent for unix-process:24395:40505442 (system bus name :1.483, object path /org/freedesktop/
Nov 13 02:11:48 localhost.localdomain patroni[24402]: 2019-11-13 02:11:48,593 INFO: Failed to import patroni.dcs.consul
Nov 13 02:11:48 localhost.localdomain patroni[24402]: 2019-11-13 02:11:48,604 INFO: Selected new etcd server http://10.95.183.160:2379
Nov 13 02:11:48 localhost.localdomain patroni[24402]: 2019-11-13 02:11:48,612 INFO: No PostgreSQL configuration items changed, nothing to reload.
Nov 13 02:11:48 localhost.localdomain patroni[24402]: 2019-11-13 02:11:48,618 INFO: Lock owner: None; I am postgresql_a1
Nov 13 02:11:48 localhost.localdomain patroni[24402]: 2019-11-13 02:11:48,621 INFO: trying to bootstrap a new cluster
Nov 13 02:11:48 localhost.localdomain patroni[24402]: The files belonging to this database system will be owned by user "postgres".
Nov 13 02:11:48 localhost.localdomain patroni[24402]: This user must also own the server process.
Nov 13 02:11:48 localhost.localdomain patroni[24402]: The database cluster will be initialized with locale "en_US.UTF-8".
Nov 13 02:11:48 localhost.localdomain patroni[24402]: The default text search configuration will be set to "english".
Nov 13 02:11:48 localhost.localdomain patroni[24402]: Data page checksums are enabled.
Nov 13 02:11:48 localhost.localdomain patroni[24402]: fixing permissions on existing directory /data/patroni ... ok
Nov 13 02:11:48 localhost.localdomain patroni[24402]: creating subdirectories ... ok
Nov 13 02:11:48 localhost.localdomain patroni[24402]: selecting default max_connections ... 100
Nov 13 02:11:48 localhost.localdomain patroni[24402]: selecting default shared_buffers ... 128MB
Nov 13 02:11:48 localhost.localdomain patroni[24402]: selecting default timezone ... Asia/Shanghai
Nov 13 02:11:48 localhost.localdomain patroni[24402]: selecting dynamic shared memory implementation ... posix
Nov 13 02:11:48 localhost.localdomain patroni[24402]: creating configuration files ... ok
Nov 13 02:11:49 localhost.localdomain patroni[24402]: creating template1 database in /data/patroni/base/1 ... ok
Nov 13 02:11:49 localhost.localdomain patroni[24402]: initializing pg_authid ... ok
Nov 13 02:11:49 localhost.localdomain patroni[24402]: initdb: password file "/tmp/tmptT5VC7" is empty
Nov 13 02:11:49 localhost.localdomain patroni[24402]: initdb: removing contents of data directory "/data/patroni"
Nov 13 02:11:49 localhost.localdomain patroni[24402]: pg_ctl: database system initialization failed
Nov 13 02:11:49 localhost.localdomain patroni[24402]: 2019-11-13 02:11:49,289 INFO: removing initialize key after failed attempt to bootstrap the cluster
Nov 13 02:11:49 localhost.localdomain patroni[24402]: 2019-11-13 02:11:49,291 INFO: renaming data directory to /data/patroni_2019-11-13-02-11-49
Nov 13 02:11:49 localhost.localdomain patroni[24402]: 2019-11-13 02:11:49,616 INFO: Lock owner: None; I am postgresql_a1
Nov 13 02:11:49 localhost.localdomain patroni[24402]: Traceback (most recent call last):
Nov 13 02:11:49 localhost.localdomain patroni[24402]: File "/usr/bin/patroni", line 11, in <module>
Nov 13 02:11:49 localhost.localdomain patroni[24402]: load_entry_point('patroni==1.6.0', 'console_scripts', 'patroni')()
Nov 13 02:11:49 localhost.localdomain patroni[24402]: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 196, in main
Nov 13 02:11:49 localhost.localdomain patroni[24402]: return patroni_main()
Nov 13 02:11:49 localhost.localdomain patroni[24402]: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 160, in patroni_main
Nov 13 02:11:49 localhost.localdomain patroni[24402]: patroni.run()
Nov 13 02:11:49 localhost.localdomain patroni[24402]: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 125, in run
Nov 13 02:11:49 localhost.localdomain patroni[24402]: logger.info(self.ha.run_cycle())
Nov 13 02:11:49 localhost.localdomain patroni[24402]: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 1344, in run_cycle
Nov 13 02:11:49 localhost.localdomain patroni[24402]: info = self._run_cycle()
Nov 13 02:11:49 localhost.localdomain patroni[24402]: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 1253, in _run_cycle
Nov 13 02:11:49 localhost.localdomain patroni[24402]: return self.post_bootstrap()
Nov 13 02:11:49 localhost.localdomain patroni[24402]: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 1149, in post_bootstrap
Nov 13 02:11:49 localhost.localdomain patroni[24402]: self.cancel_initialization()
Nov 13 02:11:49 localhost.localdomain patroni[24402]: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 1144, in cancel_initialization
Nov 13 02:11:49 localhost.localdomain patroni[24402]: raise PatroniException('Failed to bootstrap cluster')
Nov 13 02:11:49 localhost.localdomain patroni[24402]: patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'
Nov 13 02:11:49 localhost.localdomain systemd[1]: patroni.service: main process exited, code=exited, status=1/FAILURE
Nov 13 02:11:49 localhost.localdomain systemd[1]: Unit patroni.service entered failed state.
Nov 13 02:11:49 localhost.localdomain systemd[1]: patroni.service failed.
```

I dont know what happend. There is my patroni.yml
```
scope: postgres
name: postgresql0

restapi:
    listen: ip:8008
    connect_address: ip:8008

etcd:
    host: ip:2379

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        master_start_timeout: 5
        synchronous_commit: 'on'
        synchronous_standby_names: '*'
        synchronous_mode: true
        synchronous_mode_strict: true
        postgresql:
            use_pg_rewind: true
            use_slots: true
            parameters:   
                wal_level: hot_standby
                hot_standby: 'on'
                wal_keep_segments: 8
                max_wal_senders: 20
                max_worker_processes: 10
                track_commit_timestamp: on
                max_replication_slots: 20
                wal_log_hints: 'on'
                checkpoint_timeout: 30
                logging_collector: 'on'
                log_rotation_age: '200000'
                log_line_prefix: '%m - %l - %p - %h - %u@%d - &x'
                log_directory: 'pg_log'
                log_min_messages: 'WARNING'
                log_min_error_statement: 'NOTICE'
                log_checkpoints: 'on'
                log_timezone: 'America/Mexico_city'
                log_connections: 'on'
                log_disconnections: 'on'
                log_duration: 'on'
                client_min_messages: 'WARNING'

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host all all 0.0.0.0/0 trust
    - host all postgres 127.0.0.1/32 trust
    - host all postgres 0.0.0.0/0 trust
    - host all all 0.0.0.0/0 trust

    users:
        admin:
            password: admin
            options:
                - createrole
                - createdb

postgresql:
    listen: ip:5432
    connect_address: ip:5432
    data_dir: /data/patroni
    config_dir: /data/patroni
    bin_dir: /usr/pgsql-9.5/bin/
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: ''
        superuser:
            username: postgres
            password: ''
    parameters:
        unix_socket_directories: '.'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

**Comment by CyberDem0n** [comment]
Why do you want to use the empty string as a password?

**Comment by qianyuyu** [comment]
> Why do you want to use the empty string as a password?

HAHA, I get it.But the default password is not empty?

**Comment by CyberDem0n** [comment]
> HAHA

I wouldn't laugh when trust access is open to the entire world...
