### ISSUE TITLE
cannot start patroni

### ISSUE THREAD

**Issue by sandeepkalra** [zalando/patroni#1343]
Hi, I have a simple single node w/ zookeeper, and I am trying to start Patroni.

My YML file is :

scope: chetak
namespace: /p1/
name: pg_0

restapi:
  listen: 127.0.0.1:8008
  connect_address: 127.0.0.1:8008

zookeeper:
  hosts: zookeeper:2181

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      parameters:
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - host replication replicator 127.0.0.1/32 md5
  - host all all 0.0.0.0/0 md5
  users:
    admin: admin
    password: adminpw
    options:
      - createrole
      - createdb

postgresql:
  listen: 127.0.0.1:5432
  connect_address: 127.0.0.1:5432
  data_dir: /bp2/data/psql
  bin_dir: /usr/lib/postgresql/12/bin/
  pgpass: /bp2/log/pgpass
  authentication:
    replication:
      username: admin
      password: adminpw
    superuser:
      username: admin
      password: adminpw
    rewind:  # Has no effect on postgres 10 and lower
      username: admin
      password: adminpw
  parameters:
    unix_socket_directories: '.'
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: fals
 ==== yml ends ===

On starting Patroni, I get the following:
 
2019-12-21 06:25:19,133 INFO: Connecting to 172.16.0.30:2181, use_ssl: False
2019-12-21 06:25:19,138 INFO: Zookeeper connection established, state: CONNECTED
2019-12-21 06:25:19,142 INFO: No PostgreSQL configuration items changed, nothing to reload.
2019-12-21 06:25:19,157 INFO: Lock owner: None; I am pg_0
2019-12-21 06:25:19,166 INFO: trying to bootstrap a new cluster
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default text search configuration will be set to "english".

Data page checksums are enabled.

creating directory /bp2/data/psql ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    /usr/lib/postgresql/12/bin/pg_ctl -D /bp2/data/psql -l logfile start

2019-12-21 06:25:20,179 INFO: postmaster pid=596
localhost:5432 - no response
2019-12-21 06:25:20.219 UTC [596] LOG:  starting PostgreSQL 12.1 (Ubuntu 12.1-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit
2019-12-21 06:25:20.219 UTC [596] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2019-12-21 06:25:20.254 UTC [596] LOG:  listening on Unix socket "./.s.PGSQL.5432"
2019-12-21 06:25:20.318 UTC [598] LOG:  database system was shut down at 2019-12-21 06:25:19 UTC
2019-12-21 06:25:20.355 UTC [596] LOG:  database system is ready to accept connections
localhost:5432 - accepting connections
localhost:5432 - accepting connections
2019-12-21 06:25:21,226 INFO: establishing a new patroni connection to the postgres cluster
2019-12-21 06:25:21,234 INFO: running post_bootstrap
2019-12-21 06:25:21,241 ERROR: post_bootstrap
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/patroni/postgresql/bootstrap.py", line 341, in post_bootstrap
    self.create_or_update_role(name, value.get('password'), value.get('options', []))
AttributeError: 'str' object has no attribute 'get'
2019-12-21 06:25:21,243 INFO: removing initialize key after failed attempt to bootstrap the cluster
2019-12-21 06:25:21.247 UTC [596] LOG:  received immediate shutdown request
2019-12-21 06:25:21.251 UTC [609] WARNING:  terminating connection because of crash of another server process
2019-12-21 06:25:21.251 UTC [609] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2019-12-21 06:25:21.251 UTC [609] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2019-12-21 06:25:21.251 UTC [602] WARNING:  terminating connection because of crash of another server process
2019-12-21 06:25:21.251 UTC [602] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2019-12-21 06:25:21.251 UTC [602] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2019-12-21 06:25:21.254 UTC [596] LOG:  database system is shut down
2019-12-21 06:25:21,260 INFO: renaming data directory to /bp2/data/psql_2019-12-21-06-25-21
2019-12-21 06:25:21,645 INFO: Lock owner: None; I am pg_0
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/patroni/__init__.py", line 221, in main
    return patroni_main()
  File "/usr/local/lib/python3.7/dist-packages/patroni/__init__.py", line 185, in patroni_main
    patroni.run()
  File "/usr/local/lib/python3.7/dist-packages/patroni/__init__.py", line 134, in run
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python3.7/dist-packages/patroni/ha.py", line 1336, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.7/dist-packages/patroni/ha.py", line 1244, in _run_cycle
    return self.post_bootstrap()
  File "/usr/local/lib/python3.7/dist-packages/patroni/ha.py", line 1141, in post_bootstrap
    self.cancel_initialization()
  File "/usr/local/lib/python3.7/dist-packages/patroni/ha.py", line 1136, in cancel_initialization
    raise PatroniException('Failed to bootstrap cluster')
patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'
postgres@4a18e50d741f:/bp2/src$ vim /usr/local/lib/python3.7/dist-packages/patroni/postgresql/bootstrap.py +341

Also, I am puzzled on the command response. Most of the response on patronictl are cryptic. I ave one here. 

postgres@4a18e50d741f:/bp2/src$ patronictl remove /p1
Error: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: exhibitor, zookeeper'

Can someone help?

**Comment by kostiantyn-nemchenko** [comment]
Hi @sandeepkalra ,

`bootstrap.dcs.users` section is wrong. Should be like this
```
  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb
```

**Comment by sandeepkalra** [comment]
Thanks a lot. It solved the issue.
