### ISSUE TITLE
Patroni hangs after communication loss with DCS (Consul)

### ISSUE THREAD

**Issue by TestDrivenDevil** [zalando/patroni#1344]
Hi,

I'm doing network loss tests on a patroni cluster (1 master, 2 replicas)  and I see following behavior:  Each time patroni loses communication towards DCS, once communication is up again, the REST API of patroni is not responding anymore (it blocks on calling it). It's like patroni process is hanging. When I stop the service, it takes some time to stop and I see following lines in /var/log/messages, telling me the process is hanging.

```
systemd: patroni.service stop-sigterm timed out. Killing.
systemd: patroni.service: main process exited, code=killed, status=9/KILL
systemd: Unit patroni.service entered failed state.
systemd: patroni.service failed.
```

Looking for patroni logging I see following lines in /var/log/messages:

```
patroni: 2019-12-23 11:32:25,907 WARNING: Retry got exception: HTTPConnectionPool(host='192.168.1.10', port=8500): Max retries exceeded with url: /v1/session/renew/72d086a6-2fd5-ede2-fa31-529ea97bf1bc (Caused by ReadTimeoutError("HTTPConnectionPool(host='10.50.202.85', port=8500): Read timed out. (read timeout=3.33333333333)",))
patroni: 2019-12-23 11:32:25,907 ERROR: refresh_session
patroni: Traceback (most recent call last):
patroni: File "/usr/lib/python2.7/site-packages/patroni/dcs/consul.py", line 294, in refresh_session
patroni: return self.retry(self._do_refresh_session)
patroni: File "/usr/lib/python2.7/site-packages/patroni/dcs/consul.py", line 232, in retry
patroni: return self._retry.copy()(*args, **kwargs)
patroni: File "/usr/lib/python2.7/site-packages/patroni/utils.py", line 339, in __call__
patroni: raise RetryFailedError("Exceeded retry deadline")
patroni: RetryFailedError: 'Exceeded retry deadline'
python: detected unhandled Python exception in '/usr/bin/patroni'
patroni: Traceback (most recent call last):
patroni: File "/usr/bin/patroni", line 11, in <module>
patroni: load_entry_point('patroni==1.6.3', 'console_scripts', 'patroni')()
patroni: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 221, in main
patroni: return patroni_main()
patroni: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 189, in patroni_main
patroni: patroni.shutdown()
patroni: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 162, in shutdown
patroni: self.ha.shutdown()
patroni: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 1349, in shutdown
patroni: self.while_not_sync_standby(lambda: self.state_handler.stop(checkpoint=False, on_safepoint=disable_wd))
patroni: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 473, in while_not_sync_standby
patroni: if self.touch_member():
patroni: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 210, in touch_member
patroni: return self.dcs.touch_member(data)
patroni: File "/usr/lib/python2.7/site-packages/patroni/dcs/consul.py", line 149, in wrapper
patroni: return func(*args, **kwargs)
patroni: File "/usr/lib/python2.7/site-packages/patroni/dcs/consul.py", line 371, in touch_member
patroni: create_member = not permanent and self.refresh_session()
patroni: File "/usr/lib/python2.7/site-packages/patroni/dcs/consul.py", line 297, in refresh_session
patroni: raise ConsulError('Failed to renew/create session')
patroni: patroni.dcs.consul.ConsulError: 'Failed to renew/create session'
```

**Comment by CyberDem0n** [comment]
What exactly is your problem?
If Patroni can't access Consul it will restart postgres read-only, anything else not promissed.

**Comment by TestDrivenDevil** [comment]
Thanks for the quick response.

Well, the problem is not when Patroni cannot access Consul but after communication to Consul is re-established: Patroni is not responding anymore to any REST API call (for example http://127.0.0.1:8008/health). `patronictl list` won't list this member either and when stopping patroni service via `systemctl stop`  systemd will need to kill the process because it's not responding to proper shutdown anymore.
I see this behaviour consistently on any of the nodes, it does not matter if Patroni is the leader or a standby.

**Comment by CyberDem0n** [comment]
> patroni: 2019-12-23 11:32:25,907 WARNING: Retry got exception: 
HTTPConnectionPool(host='**192.168.1.10**', port=8500): Max retries exceeded with url: /v1/session/renew/72d086a6-2fd5-ede2-fa31-529ea97bf1bc 
(Caused by ReadTimeoutError("HTTPConnectionPool(host='**10.50.202.85**', port=8500): Read timed out. (read timeout=3.33333333333)",))

Something is fishy! Patroni supposed to connect to the local consul agent.

**Comment by TestDrivenDevil** [comment]
Oops, that was not correct, I fixed that but both IP addresses are in fact of the node where patroni is running. 
I redid the test now connecting to 127.0.0.1 but I still see the same behaviour: 

```
Dec 23 17:00:26 HACluster4Node2 patroni: 2019-12-23 17:00:26,260 WARNING: Retry got exception: HTTPConnectionPool(host='127.0.0.1', port=8500): Max retries exceeded with url: /v1/session/renew/682dbc58-ae77-d4b7-e057-2f459d99e787 (Caused by ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=8500): Read timed out. (read timeout=3.33333333333)",))
Dec 23 17:00:26 HACluster4Node2 patroni: 2019-12-23 17:00:26,261 ERROR: refresh_session
Dec 23 17:00:26 HACluster4Node2 patroni: Traceback (most recent call last):
Dec 23 17:00:26 HACluster4Node2 patroni: File "/usr/lib/python2.7/site-packages/patroni/dcs/consul.py", line 294, in refresh_session
Dec 23 17:00:26 HACluster4Node2 patroni: return self.retry(self._do_refresh_session)
Dec 23 17:00:26 HACluster4Node2 patroni: File "/usr/lib/python2.7/site-packages/patroni/dcs/consul.py", line 232, in retry
Dec 23 17:00:26 HACluster4Node2 patroni: return self._retry.copy()(*args, **kwargs)
Dec 23 17:00:26 HACluster4Node2 patroni: File "/usr/lib/python2.7/site-packages/patroni/utils.py", line 339, in __call__
Dec 23 17:00:26 HACluster4Node2 patroni: raise RetryFailedError("Exceeded retry deadline")
Dec 23 17:00:26 HACluster4Node2 patroni: RetryFailedError: 'Exceeded retry deadline'
Dec 23 17:00:37 HACluster4Node2 patroni: 2019-12-23 17:00:37,771 WARNING: Retry got exception: HTTPConnectionPool(host='127.0.0.1', port=8500): Max retries exceeded with url: /v1/session/renew/682dbc58-ae77-d4b7-e057-2f459d99e787 (Caused by ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=8500): Read timed out. (read timeout=3.33333333333)",))
Dec 23 17:00:37 HACluster4Node2 patroni: 2019-12-23 17:00:37,771 ERROR: refresh_session
Dec 23 17:00:37 HACluster4Node2 patroni: Traceback (most recent call last):
Dec 23 17:00:37 HACluster4Node2 patroni: File "/usr/lib/python2.7/site-packages/patroni/dcs/consul.py", line 294, in refresh_session
Dec 23 17:00:37 HACluster4Node2 patroni: return self.retry(self._do_refresh_session)
Dec 23 17:00:37 HACluster4Node2 patroni: File "/usr/lib/python2.7/site-packages/patroni/dcs/consul.py", line 232, in retry
Dec 23 17:00:37 HACluster4Node2 patroni: return self._retry.copy()(*args, **kwargs)
Dec 23 17:00:37 HACluster4Node2 patroni: File "/usr/lib/python2.7/site-packages/patroni/utils.py", line 339, in __call__
Dec 23 17:00:37 HACluster4Node2 patroni: raise RetryFailedError("Exceeded retry deadline")
Dec 23 17:00:37 HACluster4Node2 patroni: RetryFailedError: 'Exceeded retry deadline'
Dec 23 17:00:37 HACluster4Node2 python: detected unhandled Python exception in '/usr/bin/patroni'
Dec 23 17:00:37 HACluster4Node2 patroni: Traceback (most recent call last):
Dec 23 17:00:37 HACluster4Node2 patroni: File "/usr/bin/patroni", line 11, in <module>
Dec 23 17:00:37 HACluster4Node2 patroni: load_entry_point('patroni==1.6.3', 'console_scripts', 'patroni')()
Dec 23 17:00:37 HACluster4Node2 patroni: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 221, in main
Dec 23 17:00:37 HACluster4Node2 patroni: return patroni_main()
Dec 23 17:00:37 HACluster4Node2 patroni: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 189, in patroni_main
Dec 23 17:00:37 HACluster4Node2 patroni: patroni.shutdown()
Dec 23 17:00:37 HACluster4Node2 patroni: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 162, in shutdown
Dec 23 17:00:37 HACluster4Node2 patroni: self.ha.shutdown()
Dec 23 17:00:37 HACluster4Node2 patroni: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 1349, in shutdown
Dec 23 17:00:37 HACluster4Node2 patroni: self.while_not_sync_standby(lambda: self.state_handler.stop(checkpoint=False, on_safepoint=disable_wd))
Dec 23 17:00:37 HACluster4Node2 patroni: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 473, in while_not_sync_standby
Dec 23 17:00:37 HACluster4Node2 patroni: if self.touch_member():
Dec 23 17:00:37 HACluster4Node2 patroni: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 210, in touch_member
Dec 23 17:00:37 HACluster4Node2 patroni: return self.dcs.touch_member(data)
Dec 23 17:00:37 HACluster4Node2 patroni: File "/usr/lib/python2.7/site-packages/patroni/dcs/consul.py", line 149, in wrapper
Dec 23 17:00:37 HACluster4Node2 patroni: return func(*args, **kwargs)
Dec 23 17:00:37 HACluster4Node2 patroni: File "/usr/lib/python2.7/site-packages/patroni/dcs/consul.py", line 371, in touch_member
Dec 23 17:00:37 HACluster4Node2 patroni: create_member = not permanent and self.refresh_session()
Dec 23 17:00:37 HACluster4Node2 patroni: File "/usr/lib/python2.7/site-packages/patroni/dcs/consul.py", line 297, in refresh_session
Dec 23 17:00:37 HACluster4Node2 patroni: raise ConsulError('Failed to renew/create session')
Dec 23 17:00:37 HACluster4Node2 patroni: patroni.dcs.consul.ConsulError: 'Failed to renew/create session'
```
Would it be related to `Dec 23 17:00:37 HACluster4Node2 python: detected unhandled Python exception in '/usr/bin/patroni'` in the log lines?

**Comment by CyberDem0n** [comment]
On shutdown we are not trying to handle all exceptions, it simply doesn't make sense.

From logs I can only tell that consul agent isn't responding within 3.33 seconds, what is pretty big timeout. Are you sure that agent is in a healthy state after it is back?

**Comment by TestDrivenDevil** [comment]
Hi,

Sorry for my late reply, I was on holiday. 
I did some more testing and the above stack trace where Patroni is stuck during shutdown is not happening when communication to Consul is back but when communication to Consul is lost. I'm ok that not all exceptions are handled during shutdown but I do not expect that the process is hanging because of that.

**Comment by CyberDem0n** [comment]
The process is not hanging. It just does a few attempts to update information in consul.

**Comment by TestDrivenDevil** [comment]
Looking at the stack trace: ```Dec 23 17:00:37 HACluster4Node2 patroni: patroni.shutdown()```. Isn't patroni shutting down? If yes, I would expect that when listing the active processes I would not see patroni running but it's still there and when execute systemctl stop I see following lines in /var/log/messages: 
```
systemd: patroni.service stop-sigterm timed out. Killing.
systemd: patroni.service: main process exited, code=killed, status=9/KILL
systemd: Unit patroni.service entered failed state.
systemd: patroni.service failed.
 ```

This looks like it's hanging, right?

**Comment by CyberDem0n** [comment]
I see, it hangs in the logger thread.
Will prepare a fix.

**Comment by TestDrivenDevil** [comment]
Thanks!
