### ISSUE TITLE
can not change temp_file_limit config

### ISSUE THREAD

**Issue by lrc0** [zalando/patroni#1345]
I use the patroni rest api: 
```
curl -s -XPATCH -d '{"loop_wait":5,"ttl":20,"postgresql":{"parameters":{"temp_file_limit":"10GB"}}}' http://10.244.2.181:8008/config | jq . 
```
return:
```
{
  "loop_wait": 5,
  "maximum_lag_on_failover": 33554432,
  "postgresql": {
    "parameters": {
      "archive_command": "/etc/timescaledb/scripts/pgbackrest_archive.sh %p",
      "archive_mode": "on",
      "archive_timeout": "1800s",
      "autovacuum_analyze_scale_factor": 0.02,
      "autovacuum_max_workers": 10,
      "autovacuum_vacuum_scale_factor": 0.05,
      "checkpoint_completion_target": 0.99,
      "hot_standby": "on",
      "listen_addresses": "*",
      "log_autovacuum_min_duration": 0,
      "log_checkpoints": "on",
      "log_connections": "on",
      "log_disconnections": "on",
      "log_line_prefix": "%t [%p]: [%c-%l] %u@%d,app=%a [%e] ",
      "log_lock_waits": "on",
      "log_min_duration_statement": "1s",
      "log_statement": "ddl",
      "max_connections": 200000,
      "max_prepared_transactions": 200001,
      "max_wal_senders": 2000,
      "max_wal_size": "750MB",
      "min_wal_size": "250MB",
      "shared_buffers": "300MB",
      "shared_preload_libraries": "timescaledb,pg_stat_statements",
      "ssl": "on",
      "ssl_cert_file": "/etc/certificate/tls.crt",
      "ssl_key_file": "/etc/certificate/tls.key",
      "superuser_reserved_connections": 1000,
      "tcp_keepalives_idle": 900,
      "tcp_keepalives_interval": 100,
      "temp_file_limit": "10GB",
      "timescaledb.passfile": "../.pgpass",
      "unix_socket_directories": "/var/run/postgresql",
      "unix_socket_permissions": "0750",
      "wal_level": "hot_standby",
      "wal_log_hints": "on",
      "work_mem": "16MB"
    },
    "use_pg_rewind": true,
    "use_slots": true
  },
  "retry_timeout": 10,
  "ttl": 20
}
```
i find the pg_file_setting is applied

```
postgres=# postgres=# select * from pg_file_settings where name='temp_file_limit';
                sourcefile                | sourceline | seqno |      name       | setting | applied | error
------------------------------------------+------------+-------+-----------------+---------+---------+-------
 /var/lib/postgresql/data/postgresql.conf |         40 |    51 | temp_file_limit | 10GB    | t       |
(1 row)
```
also i executed:
```
curl -XPOST http://10.244.2.181:8008/restart
```
 and:
```
pg_ctl reload 
```

 that can not change the temp_file_limit in pg_setting 
```
postgres=# select name,setting,boot_val,reset_val from pg_settings where name='temp_file_limit';
      name       |  setting  | boot_val | reset_val
-----------------+-----------+----------+-----------
 temp_file_limit | 131072000 | -1       | 131072000
(1 row)
```

but when i change the max_connections using the same api , it works.

**Comment by CyberDem0n** [comment]
Magic doesn't exist, either `temp_file_limit` is also defined in the patroni.yaml or it was changed with ALTER SYSTEM.
Both places take precedence over values from DCS.

**Comment by lrc0** [comment]
> Magic doesn't exist, either `temp_file_limit` is also defined in the patroni.yaml or it was changed with ALTER SYSTEM.
> Both places take precedence over values from DCS.

First of all thank you for responding so quickly ！

I exec:
```
postgres=# ALTER SYSTEM SET temp_file_limit="10GB";
ALTER SYSTEM
postgres=# select name,setting,boot_val,reset_val from pg_settings where name='temp_file_limit';
      name       |  setting  | boot_val | reset_val
-----------------+-----------+----------+-----------
 temp_file_limit | 131072000 | -1       | 131072000
(1 row)
```
it does not work either, and my patroni.yml is:
```
$ cat patroni.yaml
bootstrap:
  dcs:
    loop_wait: 10
    maximum_lag_on_failover: 33554432
    postgresql:
      parameters:
        archive_command: /etc/timescaledb/scripts/pgbackrest_archive.sh %p
        archive_mode: "on"
        archive_timeout: 1800s
        autovacuum_analyze_scale_factor: 0.02
        autovacuum_max_workers: 10
        autovacuum_vacuum_scale_factor: 0.05
        checkpoint_completion_target: 0.99
        hot_standby: "on"
        listen_addresses: '*'
        log_autovacuum_min_duration: 0
        log_checkpoints: "on"
        log_connections: "on"
        log_disconnections: "on"
        log_line_prefix: '%t [%p]: [%c-%l] %u@%d,app=%a [%e] '
        log_lock_waits: "on"
        log_min_duration_statement: 1s
        log_statement: ddl
        max_connections: 200000
        max_prepared_transactions: 200001
        max_wal_senders: 2000
        max_wal_size: 750MB
        min_wal_size: 250MB
        shared_buffers: 300MB
        shared_preload_libraries: timescaledb,pg_stat_statements
        ssl: "on"
        ssl_cert_file: /etc/certificate/tls.crt
        ssl_key_file: /etc/certificate/tls.key
        superuser_reserved_connections: 1000
        tcp_keepalives_idle: 900
        tcp_keepalives_interval: 100
        temp_file_limit: -1
        timescaledb.passfile: ../.pgpass
        unix_socket_directories: /var/run/postgresql
        unix_socket_permissions: "0750"
        wal_level: hot_standby
        wal_log_hints: "on"
        work_mem: 16MB
        ... ...
```
the temp_file_limit is -1 , not 125GB. 
i think if it takes effect , the temp_file_limit must be -1 , can not be 131072000

**Comment by lrc0** [comment]
by the way i am using the helm chart deploying the postgresql in kubernetes,

**Comment by CyberDem0n** [comment]
1. You didn't show the actual config, because the following section does nothing as log as cluster bootstrapped.
```yaml
bootstrap:
  dcs:
```

2. `select name,setting,boot_val,reset_val from pg_settings` -- there are also very usefull fields `sourcefile` and `sourceline` in the pg_settings view...

**Comment by lrc0** [comment]
the sourcefile and sourceline is empty
```
postgres=# select name,setting,boot_val,reset_val,sourcefile,sourceline from pg_settings where name='temp_file_limit';
      name       |  setting  | boot_val | reset_val | sourcefile | sourceline
-----------------+-----------+----------+-----------+------------+------------
 temp_file_limit | 131072000 | -1       | 131072000 |            |
(1 row)
```

**Comment by CyberDem0n** [comment]
> the sourcefile and sourceline is empty

Then there are two options, 1 - it was set in the command line (highly unlikely), 2 - it was set in your session (for example from ~/.psqlrc)

**Comment by lrc0** [comment]
i am deploying postgresql in kubernetes cluster, i cannot find .psqlrc in the pod. is there any other way to change the temp_file_limit config dynamic

**Comment by CyberDem0n** [comment]
There is nothing in Patroni what prevents from changing it:
```bash
postgres@a0cf40a5dd85:~$ patronictl edit-config -p temp_file_limit=10GB
--- 
+++ 
@@ -23,6 +23,7 @@
     max_wal_senders: 10
     tcp_keepalives_idle: 900
     tcp_keepalives_interval: 100
+    temp_file_limit: 10GB
     track_functions: all
     wal_keep_segments: 8
     wal_level: hot_standby

Apply these changes? [y/N]: y
Configuration changed
```

```bash
2019-12-23 14:39:28,782 INFO: no action.  i am the leader with the lock
2019-12-23 14:39:28,786 INFO: Changed tcp_keepalives_idle from 0 to 900
2019-12-23 14:39:28,786 INFO: Changed tcp_keepalives_interval from 0 to 100
2019-12-23 14:39:28,786 INFO: Changed temp_file_limit from -1 to 10GB
2019-12-23 14:39:28,788 INFO: Reloading PostgreSQL configuration.
server signaled
2019-12-23 14:39:38,772 INFO: Lock owner: a0cf40a5dd85; I am a0cf40a5dd85
2019-12-23 14:39:38,781 INFO: no action.  i am the leader with the lock
```

```bash
postgres@a0cf40a5dd85:~$ psql
psql (12.1 (Ubuntu 12.1-1.pgdg18.04+1))
Type "help" for help.

postgres=# show temp_file_limit ;
 temp_file_limit 
-----------------
 10GB
(1 row)

```

**Comment by lrc0** [comment]
Sorry for replying so late ...

Maybe there is something wrong with my image，I exec:
```
$ patronictl edit-config -p temp_file_limit=10GB
```
but it report a err:
```
Traceback (most recent call last):
  File "/usr/bin/patronictl", line 11, in <module>
    load_entry_point('patroni==1.6.0', 'console_scripts', 'patronictl')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/patroni/ctl.py", line 1198, in edit_config
    show_diff(before_editing, after_editing)
  File "/usr/lib/python3/dist-packages/patroni/ctl.py", line 1033, in show_diff
    cdiff.markup_to_pager(cdiff.PatchStream(buf), opts)
  File "/usr/lib/python3/dist-packages/cdiff.py", line 640, in markup_to_pager
    pager_cmd, stdin=subprocess.PIPE, stdout=sys.stdout)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'less': 'less'
```

my image is: 
```
timescaledev/timescaledb-ha:pg11-ts1.5
```

**Comment by CyberDem0n** [comment]
I have no idea about how timescaledb images are built.
Maybe @feikesteenbergen could help?
In any case there is nothing wrong in Patroni.
Highly likely the value is coming from patroni.yml backed into the docker image.
