### ISSUE TITLE
Network interruption with consul servers behaves different if you are leader or replica

### ISSUE THREAD

**Issue by gerardo-herzig** [zalando/patroni#1363]
Hi all. Im trying to simulate how patroni acts when network breaks between patroni nodes and consul servers. For that, im using something like
`iptables -I INPUT -s <consul.servers.network> -j REJECT`
`iptables -I OUTPUT -d <consul.servers.network> -j REJECT`

Now, if i apply a 10 seconds `iptables` in a non-leader node, this happen:
```
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]: 2020-01-10 18:23:43,783 ERROR: watch
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]: Traceback (most recent call last):
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:   File "/opt/patroni/lib/python3.5/site-packages/urllib3/connectionpool.py", line 384, in _make_request
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:     six.raise_from(e, None)
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:   File "<string>", line 2, in raise_from
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:   File "/opt/patroni/lib/python3.5/site-packages/urllib3/connectionpool.py", line 380, in _make_request
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:     httplib_response = conn.getresponse()
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:   File "/usr/lib/python3.5/http/client.py", line 1213, in getresponse
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:     response.begin()
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:   File "/usr/lib/python3.5/http/client.py", line 307, in begin
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:     version, status, reason = self._read_status()
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:   File "/usr/lib/python3.5/http/client.py", line 268, in _read_status
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:   File "/usr/lib/python3.5/socket.py", line 575, in readinto
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:     return self._sock.recv_into(b)
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]: socket.timeout: timed out
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]: During handling of the above exception, another exception occurred:
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]: Traceback (most recent call last):
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:   File "/opt/patroni/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:     chunked=chunked)
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:   File "/opt/patroni/lib/python3.5/site-packages/urllib3/connectionpool.py", line 386, in _make_request
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:   File "/opt/patroni/lib/python3.5/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:     raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]: urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=8500): Read timed out. (read timeout=10.57853
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]: During handling of the above exception, another exception occurred:
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]: Traceback (most recent call last):
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:   File "/opt/patroni/lib/python3.5/site-packages/patroni/dcs/consul.py", line 528, in watch
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:     idx, _ = self._client.kv.get(self.leader_path, index=leader_index, wait=str(timeout) + 's')
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:   File "/opt/patroni/lib/python3.5/site-packages/consul/base.py", line 554, in get
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:     params=params)
Jan 10 18:23:43 patroni-01-db-gstg audit[26320]: SYSCALL arch=c000003e syscall=42 success=no exit=-115 a0=3 a1=7fffb3ed0660 a2=10 a3=3421 items=0 ppid=1 pid=26320 auid=4294967
Jan 10 18:23:43 patroni-01-db-gstg audit: SOCKADDR saddr=020021347F0000010000000000000000
Jan 10 18:23:43 patroni-01-db-gstg audit: PROCTITLE proctitle="(patroni)"
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:   File "/opt/patroni/lib/python3.5/site-packages/patroni/dcs/consul.py", line 116, in wrapper
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:     return callback(self.response(self.http.request(method.upper(), self.uri(path, params), **kwargs)))
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:   File "/opt/patroni/lib/python3.5/site-packages/urllib3/request.py", line 68, in request
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:     **urlopen_kw)
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:   File "/opt/patroni/lib/python3.5/site-packages/urllib3/request.py", line 89, in request_encode_url
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:     return self.urlopen(method, url, **extra_kw)
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:   File "/opt/patroni/lib/python3.5/site-packages/urllib3/poolmanager.py", line 323, in urlopen
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:     response = conn.urlopen(method, u.request_uri, **kw)
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:   File "/opt/patroni/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:     _stacktrace=sys.exc_info()[2])
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:   File "/opt/patroni/lib/python3.5/site-packages/urllib3/util/retry.py", line 398, in increment
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]:     raise MaxRetryError(_pool, url, error or ResponseError(cause))
Jan 10 18:23:43 patroni-01-db-gstg patroni[26320]: urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8500): Max retries exceeded with url: /v1/kv/ser
```

But, when i try this on the leader, not a single error appears in the logs. Only after `60` seconds of network interruption, this appears in the patroni logs:
```
Jan 13 16:47:43 patroni-04-db-gstg consul[30575]: consul: "KVS.List" RPC failed to server 10.224.4.5:8300: rpc error making call: EOF

Jan 13 16:47:47 patroni-04-db-gstg patroni[11982]: 2020-01-13 16:47:47,398 ERROR: get_cluster
Jan 13 16:47:47 patroni-04-db-gstg patroni[11982]: Traceback (most recent call last):
Jan 13 16:47:47 patroni-04-db-gstg patroni[11982]:   File "/opt/patroni/lib/python3.5/site-packages/patroni/utils.py", line 313, in __call__
Jan 13 16:47:47 patroni-04-db-gstg patroni[11982]:     return func(*args, **kwargs)
Jan 13 16:47:47 patroni-04-db-gstg patroni[11982]:   File "/opt/patroni/lib/python3.5/site-packages/consul/base.py", line 554, in get
Jan 13 16:47:47 patroni-04-db-gstg patroni[11982]:     params=params)
Jan 13 16:47:47 patroni-04-db-gstg patroni[11982]:   File "/opt/patroni/lib/python3.5/site-packages/patroni/dcs/consul.py", line 116, in wrapper
Jan 13 16:47:47 patroni-04-db-gstg patroni[11982]:     return callback(self.response(self.http.request(method.upper(), self.uri(path, params), **kwargs)))
Jan 13 16:47:47 patroni-04-db-gstg patroni[11982]:   File "/opt/patroni/lib/python3.5/site-packages/patroni/dcs/consul.py", line 82, in response
Jan 13 16:47:47 patroni-04-db-gstg patroni[11982]:     raise ConsulInternalError(msg)
Jan 13 16:47:47 patroni-04-db-gstg patroni[11982]: patroni.dcs.consul.ConsulInternalError: 500 rpc error getting client: failed to get conn: dial tcp 10.224.29.104:0->10.224.4.3:8300: connect: connection refused

an 13 16:47:51 patroni-04-db-gstg consul[30575]:     2020/01/13 16:47:51 [WARN] agent: Check "service:patroni-master" is now critical
Jan 13 16:47:51 patroni-04-db-gstg consul[30575]: agent: Check "service:patroni-master" is now critical

Jan 13 16:48:16 patroni-04-db-gstg patroni[11982]: 2020-01-13 16:48:16,026 INFO: promoted self to leader because i had the session lock

```
Patroni 1.6.0
Related settings:
```
consul:
  host: 127.0.0.1:8500 ## Consul `client`
bootstrap:
  dcs:
    ttl: 90
    loop_wait: 10
    retry_timeout: 30
    maximum_lag_on_failover: 1048576


```
So, its that OK? Why it behaves that way?

Any ideas?

Gerardo

**Comment by CyberDem0n** [comment]
> Only after 60 seconds of network interruption, this appears in the patroni logs:

Why don't you post all logs (before and after)?

> Related settings:

Please also add `consul.checks: []` to the config. You can find about it in the [documentation](https://patroni.readthedocs.io/en/latest/SETTINGS.html#consul) or among other "issues" here.

**Comment by kostiantyn-nemchenko** [comment]
@CyberDem0n does it make sense setting `consul.checks` to `[]` by default? You have to repeat the same configuration details for every new user that prefers consul as DCS.

**Comment by CyberDem0n** [comment]
I think so, just somehow always forgetting to do so...

**Comment by gerardo-herzig** [comment]
> > Only after 60 seconds of network interruption, this appears in the patroni logs:
> 
> Why don't you post all logs (before and after)?

Sure, here. Note that at 16:47:15 communication between patroni and consul server has been interrupted

```
2020-01-13_16:47:08 patroni-04-db-gstg patroni[11982]:  2020-01-13 16:47:08,596 INFO: Lock owner: patroni-04-db-gstg.c.gitlab-staging-1.internal; I am patroni-04-db-gstg.c.gitlab-staging-1.internal
2020-01-13_16:47:08 patroni-04-db-gstg patroni[11982]:  2020-01-13 16:47:08,614 INFO: no action.  i am the leader with the lock
2020-01-13_16:47:47 patroni-04-db-gstg patroni[11982]:  2020-01-13 16:47:47,397 WARNING: Retry got exception: 500 rpc error getting client: failed to get conn: dial tcp 10.224.29.104:0->10.224.4.3:8300: connect: connection refused
2020-01-13_16:47:47 patroni-04-db-gstg patroni[11982]:  2020-01-13 16:47:47,398 ERROR: get_cluster
2020-01-13_16:47:47 patroni-04-db-gstg patroni[11982]:  Traceback (most recent call last):
2020-01-13_16:47:47 patroni-04-db-gstg patroni[11982]:    File "/opt/patroni/lib/python3.5/site-packages/patroni/utils.py", line 313, in __call__
2020-01-13_16:47:47 patroni-04-db-gstg patroni[11982]:      return func(*args, **kwargs)
2020-01-13_16:47:47 patroni-04-db-gstg patroni[11982]:    File "/opt/patroni/lib/python3.5/site-packages/consul/base.py", line 554, in get
2020-01-13_16:47:47 patroni-04-db-gstg patroni[11982]:      params=params)
2020-01-13_16:47:47 patroni-04-db-gstg patroni[11982]:    File "/opt/patroni/lib/python3.5/site-packages/patroni/dcs/consul.py", line 116, in wrapper
2020-01-13_16:47:47 patroni-04-db-gstg patroni[11982]:      return callback(self.response(self.http.request(method.upper(), self.uri(path, params), **kwargs)))
2020-01-13_16:47:47 patroni-04-db-gstg patroni[11982]:    File "/opt/patroni/lib/python3.5/site-packages/patroni/dcs/consul.py", line 82, in response
2020-01-13_16:47:47 patroni-04-db-gstg patroni[11982]:      raise ConsulInternalError(msg)
2020-01-13_16:47:47 patroni-04-db-gstg patroni[11982]:  patroni.dcs.consul.ConsulInternalError: 500 rpc error getting client: failed to get conn: dial tcp 10.224.29.104:0->10.224.4.3:8300: connect: connection refused
2020-01-13_16:47:47 patroni-04-db-gstg patroni[11982]:  During handling of the above exception, another exception occurred:
2020-01-13_16:47:47 patroni-04-db-gstg patroni[11982]:  Traceback (most recent call last):
2020-01-13_16:47:47 patroni-04-db-gstg patroni[11982]:    File "/opt/patroni/lib/python3.5/site-packages/patroni/dcs/consul.py", line 307, in _load_cluster
2020-01-13_16:47:47 patroni-04-db-gstg patroni[11982]:      _, results = self.retry(self._client.kv.get, path, recurse=True)
2020-01-13_16:47:47 patroni-04-db-gstg patroni[11982]:    File "/opt/patroni/lib/python3.5/site-packages/patroni/dcs/consul.py", line 230, in retry
2020-01-13_16:47:47 patroni-04-db-gstg patroni[11982]:      return self._retry.copy()(*args, **kwargs)
2020-01-13_16:47:47 patroni-04-db-gstg patroni[11982]:    File "/opt/patroni/lib/python3.5/site-packages/patroni/utils.py", line 324, in __call__
2020-01-13_16:47:47 patroni-04-db-gstg patroni[11982]:      raise RetryFailedError("Exceeded retry deadline")
2020-01-13_16:47:47 patroni-04-db-gstg patroni[11982]:  patroni.utils.RetryFailedError: 'Exceeded retry deadline'
2020-01-13_16:47:47 patroni-04-db-gstg patroni[11982]:  2020-01-13 16:47:47,398 ERROR: Error communicating with DCS
2020-01-13_16:47:49 patroni-04-db-gstg patroni[11982]:  2020-01-13 16:47:49,383 INFO: closed patroni connection to the postgresql cluster
2020-01-13_16:47:49 patroni-04-db-gstg patroni[11982]:  2020-01-13 16:47:49,434 INFO: postmaster pid=13482
2020-01-13_16:47:49 patroni-04-db-gstg patroni[11982]:  localhost:5432 - no response
2020-01-13_16:47:49 patroni-04-db-gstg patroni[11982]:  2020-01-13 16:47:49.897 GMT [13482, 0]: [1-1] user=,db=,app=,client= LOG:  redirecting log output to logging collector process
2020-01-13_16:47:49 patroni-04-db-gstg patroni[11982]:  2020-01-13 16:47:49.897 GMT [13482, 0]: [2-1] user=,db=,app=,client= HINT:  Future log output will appear in directory "/var/log/gitlab/postgresql".
2020-01-13_16:47:50 patroni-04-db-gstg patroni[11982]:  localhost:5432 - rejecting connections
2020-01-13_16:47:50 patroni-04-db-gstg patroni[11982]:  localhost:5432 - rejecting connections
2020-01-13_16:47:51 patroni-04-db-gstg patroni[11982]:  localhost:5432 - rejecting connections
2020-01-13_16:47:52 patroni-04-db-gstg patroni[11982]:  localhost:5432 - accepting connections
2020-01-13_16:47:52 patroni-04-db-gstg patroni[11982]:  2020-01-13 16:47:52,751 INFO: demoted self because DCS is not accessible and i was a leader
2020-01-13_16:47:52 patroni-04-db-gstg patroni[11982]:  2020-01-13 16:47:52,776 WARNING: Loop time exceeded, rescheduling immediately.
2020-01-13_16:47:52 patroni-04-db-gstg patroni[11982]:  + [[ replica == \m\a\s\t\e\r ]]
2020-01-13_16:47:52 patroni-04-db-gstg patroni[11982]:  + exit
2020-01-13_16:48:16 patroni-04-db-gstg patroni[11982]:  2020-01-13 16:48:16,000 INFO: Lock owner: patroni-04-db-gstg.c.gitlab-staging-1.internal; I am patroni-04-db-gstg.c.gitlab-staging-1.internal
2020-01-13_16:48:16 patroni-04-db-gstg patroni[11982]:  2020-01-13 16:48:16,000 INFO: establishing a new patroni connection to the postgres cluster
2020-01-13_16:48:16 patroni-04-db-gstg patroni[11982]:  2020-01-13 16:48:16,026 INFO: promoted self to leader because i had the session lock
2020-01-13_16:48:16 patroni-04-db-gstg patroni[11982]:  2020-01-13 16:48:16,028 WARNING: Loop time exceeded, rescheduling immediately.
2020-01-13_16:48:16 patroni-04-db-gstg patroni[11982]:  2020-01-13 16:48:16,036 INFO: Lock owner: patroni-04-db-gstg.c.gitlab-staging-1.internal; I am patroni-04-db-gstg.c.gitlab-staging-1.internal
2020-01-13_16:48:16 patroni-04-db-gstg patroni[11982]:  2020-01-13 16:48:16,039 INFO: updated leader lock during promote
2020-01-13_16:48:16 patroni-04-db-gstg patroni[11982]:  server promoting
2020-01-13_16:48:16 patroni-04-db-gstg patroni[11982]:  2020-01-13 16:48:16,054 INFO: cleared rewind state after becoming the leader
2020-01-13_16:48:16 patroni-04-db-gstg patroni[11982]:  + [[ master == \m\a\s\t\e\r ]]
2020-01-13_16:48:16 patroni-04-db-gstg patroni[11982]:  ++ seq 1 5
2020-01-13_16:48:16 patroni-04-db-gstg patroni[11982]:  + for i in '$(seq 1 5)'
2020-01-13_16:48:16 patroni-04-db-gstg patroni[11982]:  + gitlab-psql -tc 'SELECT pg_is_in_recovery()'
2020-01-13_16:48:16 patroni-04-db-gstg patroni[11982]:  + grep f
2020-01-13_16:48:16 patroni-04-db-gstg patroni[11982]:  + sleep 60
2020-01-13_16:48:20 patroni-04-db-gstg patroni[11982]:  2020-01-13 16:48:20,128 INFO: Lock owner: patroni-04-db-gstg.c.gitlab-staging-1.internal; I am patroni-04-db-gstg.c.gitlab-staging-1.internal
2020-01-13_16:48:20 patroni-04-db-gstg patroni[11982]:  2020-01-13 16:48:20,175 INFO: no action.  i am the leader with the lock
```

**Comment by CyberDem0n** [comment]
> 2020-01-13 16:47:08,614 INFO: no action.  i am the leader with the lock
2020-01-13 16:47:47,397 WARNING: Retry got exception: 500 rpc error getting client: failed to get conn: dial tcp 10.224.29.104:0->10.224.4.3:8300: connect: connection refused


16:47:08 -- last successfull communication with the cluster.

After that it sleeps for 10 seconds (loop_wait) and starts the next HA loop.
Since retry_timeout is set to 30 seconds, the request times out at 16:47:47.

The math is about right, 30+10 = 40.

**Comment by gerardo-herzig** [comment]
> > 2020-01-13 16:47:08,614 INFO: no action.  i am the leader with the lock
> > 2020-01-13 16:47:47,397 WARNING: Retry got exception: 500 rpc error getting client: failed to get conn: dial tcp 10.224.29.104:0->10.224.4.3:8300: connect: connection refused
> 
> 16:47:08 -- last successfull communication with the cluster.
> 
> After that it sleeps for 10 seconds (loop_wait) and starts the next HA loop.
> Since retry_timeout is set to 30 seconds, the request times out at 16:47:47.
> 
> The math is about right, 30+10 = 40.

Thank you so much for your answer. But im more puzzled with the `10 second` restart induced to non-leader nodes. That is OK to you?

**Comment by CyberDem0n** [comment]
> im more puzzled with the 10 second restart induced to non-leader nodes

Please re-read [this](https://github.com/zalando/patroni/issues/1363#issuecomment-574232198) and apply suggested change to the configuration. 
The issue https://github.com/zalando/patroni/issues/522 has a detailed explanation of what and why is happening.
