### ISSUE TITLE
Patroni on k8s: deleted master endpoint not recreated

### ISSUE THREAD

**Issue by riddhi89** [zalando/patroni#1387]
```
Patroni version: 1.6.3
PostgreSQL server version: 12.1
K8s server version: v1.15.6
```
We use `PATRONI_KUBERNETES_USE_ENDPOINTS: true` setting and rely on Patroni to create and manage the K8s Endpoint which stores the leader information in the annotations. 

However, recently we observed a scenario where the endpoint resource gets deleted and Patroni was unable to recreate this endpoint after K8s network glitches (could be due to a restart of k8s master node services), which caused the below error and the master pod/node to be demoted to a replica.

```
2020-02-10 06:25:26,224 INFO: no action.  i am the leader with the lock
2020-02-10 06:25:36,210 INFO: Lock owner: pgsql-a49a54b9-e0f2-4d63-9042-a2d0384df879-0; I am pgsql-a49a54b9-e0f2-4d63-9042-a2d0384df879-0

2020-02-10 06:25:37,212 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1187687048>, 'Connection to 172.17.0.1 timed out. (connect timeout=1)')': /api/v1/namespaces/a49a54b9-e0f2-4d63-9042-a2d0384df879/endpoints/pgsql-a49a54b9-e0f2-4d63-9042-a2d0384df879

2020-02-10 06:25:37,212 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1187687048>, 'Connection to 172.17.0.1 timed out. (connect timeout=1)')': /api/v1/namespaces/a49a54b9-e0f2-4d63-9042-a2d0384df879/endpoints/pgsql-a49a54b9-e0f2-4d63-9042-a2d0384df879

2020-02-10 06:25:46,210 INFO: Lock owner: pgsql-a49a54b9-e0f2-4d63-9042-a2d0384df879-0; I am pgsql-a49a54b9-e0f2-4d63-9042-a2d0384df879-0
2020-02-10 06:25:46,223 INFO: no action.  i am the leader with the lock
2020-02-10 06:25:56,210 INFO: Lock owner: pgsql-a49a54b9-e0f2-4d63-9042-a2d0384df879-0; I am pgsql-a49a54b9-e0f2-4d63-9042-a2d0384df879-0
2020-02-10 06:25:56,223 INFO: no action.  i am the leader with the lock
2020-02-10 06:26:06,210 INFO: Lock owner: pgsql-a49a54b9-e0f2-4d63-9042-a2d0384df879-0; I am pgsql-a49a54b9-e0f2-4d63-9042-a2d0384df879-0
2020-02-10 06:26:06,218 ERROR: failed to update leader lock
Traceback (most recent call last):
  File "/src/patroni/patroni/dcs/kubernetes.py", line 66, in wrapper
    return func(*args, **kwargs)
  File "/src/patroni/patroni/dcs/kubernetes.py", line 409, in patch_or_create
    ret = self.retry(func, self._namespace, body) if retry else func(self._namespace, body)
  File "/src/patroni/patroni/dcs/kubernetes.py", line 233, in retry
    return self._retry.copy()(*args, **kwargs)
  File "/src/patroni/patroni/utils.py", line 328, in __call__
    return func(*args, **kwargs)
  File "/src/patroni/patroni/dcs/kubernetes.py", line 55, in wrapper
    return getattr(self._api, func)(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/kubernetes/client/apis/core_v1_api.py", line 14840, in patch_namespaced_endpoints
    (data) = self.patch_namespaced_endpoints_with_http_info(name, namespace, body, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/kubernetes/client/apis/core_v1_api.py", line 14940, in patch_namespaced_endpoints_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/dist-packages/kubernetes/client/api_client.py", line 334, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.7/dist-packages/kubernetes/client/api_client.py", line 168, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.7/dist-packages/kubernetes/client/api_client.py", line 393, in request
    body=body)
  File "/usr/local/lib/python3.7/dist-packages/kubernetes/client/rest.py", line 286, in PATCH
    body=body)
  File "/usr/local/lib/python3.7/dist-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
2020-02-10 06:26:06,214 ERROR: Unexpected error from Kubernetes API
Reason: Not Found
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"endpoints \"pgsql-a49a54b9-e0f2-4d63-9042-a2d0384df879\" not found","reason":"NotFound","details":{"name":"pgsql-a49a54b9-e0f2-4d63-9042-a2d0384df879","kind":"endpoints"},"code":404}
HTTP response headers: HTTPHeaderDict({'Audit-Id': '69a537c6-9c3c-4583-8424-fec879483d2c', 'Content-Type': 'application/json', 'Date': 'Mon, 10 Feb 2020 06:26:06 GMT', 'Content-Length': '262'})
2020-02-10 06:26:06,229 INFO: Reaped pid=23944, exit status=0
2020-02-10 06:26:06,256 INFO: demoted self because failed to update leader lock in DCS
2020-02-10 06:26:06,257 INFO: closed patroni connection to the postgresql cluster
2020-02-10 06:26:06,462 INFO: postmaster pid=23950
22:26:06.500 localhost:5432 - rejecting connections
22:26:06.591 localhost:5432 - accepting connections
2020-02-10 06:26:06,593 INFO: establishing a new patroni connection to the postgres cluster
2020-02-10 06:26:06,593 INFO: Lock owner: pgsql-a49a54b9-e0f2-4d63-9042-a2d0384df879-0; I am pgsql-a49a54b9-e0f2-4d63-9042-a2d0384df879-0
2020-02-10 06:26:06,606 ERROR: failed to update leader lock

<error repeats>
```

Any pointers as to why Patroni is unable to recreate the endpoint (not recognize it was deleted) instead of trying to patch it? 
FWIW, just for testing, in a healthy cluster, when we tried manually deleting the endpoint , Patroni seems to be quickly recreating it.

**Comment by CyberDem0n** [comment]
Due to the network glitch long poll connections seem to hang and therefore internal object cache is not updated anymore. Patroni assumes that the leader endpoint still exists and trying to patch it.

The https://github.com/zalando/patroni/pull/1366 should solve the problem. Basically you need to upgrade to 1.6.4, it should help.

**Comment by riddhi89** [comment]
Great! Thank you for the quick feedback @CyberDem0n. We will try upgrading patroni to 1.6.4 and report back if we still see this issue. Closing this issue for now / will re-open if we still notice it.
