### ISSUE TITLE
Convert a Standalone to a Patroni Cluster issue

### ISSUE THREAD

**Issue by alexeyshishkin01** [zalando/patroni#1398]
Hello, all!
I'm following the link https://patroni.readthedocs.io/en/latest/existing_data.html
Steps 1 and 2 are done.
Step 3 throws the error:

2020-02-18 23:01:38,461 INFO: No PostgreSQL configuration items changed, nothing to reload.
2020-02-18 23:01:38,465 INFO: establishing a new patroni connection to the postgres cluster
2020-02-18 23:01:39,318 INFO: establishing a new patroni connection to the postgres cluster
2020-02-18 23:01:39,330 WARNING: Retry got exception: 'connection problems'
localhost:5433 - accepting connections
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 224, in main
    return patroni_main()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 186, in patroni_main
    patroni = Patroni(conf)
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 35, in __init__
    self.postgresql = Postgresql(self.config['postgresql'])
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 98, in __init__
    self.set_role('master' if self.is_leader() else 'replica')
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 306, in is_leader
    return bool(self._cluster_info_state_get('timeline'))
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 301, in _cluster_info_state_get
    raise PostgresConnectionException(self._cluster_info_state['error'])
patroni.exceptions.PostgresConnectionException: "'Too many retry attempts'"

Postgres log file shows:

2020-02-18 23:01:38 UTC [4829]: [1-1] db=[unknown],user=[unknown],app=[unknown],client=::1 LOG:  connection received: host=::1 port=35580
2020-02-18 23:01:38 UTC [4829]: [2-1] db=postgres,user=patroni_superuser,app=[unknown],client=::1 FATAL:  no pg_hba.conf entry for host "::1", user "patroni_superuser", database "postgres", SSL on
2020-02-18 23:01:38 UTC [4830]: [1-1] db=[unknown],user=[unknown],app=[unknown],client=::1 LOG:  connection received: host=::1 port=35582
2020-02-18 23:01:38 UTC [4830]: [2-1] db=postgres,user=patroni_superuser,app=[unknown],client=::1 FATAL:  no pg_hba.conf entry for host "::1", user "patroni_superuser", database "postgres", SSL off

I wonder why Patroni uses "::1" to connect to Postgres?

What is the way to change it? (say use IPv4 addressing instead of IPv6)

**Comment by CyberDem0n** [comment]
Hi @alexeyshishkin01,

my guess would be that it is trying to connect to [localhost](https://github.com/zalando/patroni/blob/master/patroni/postgresql/config.py#L827) which is getting resolved into `::1` and `127.0.0.1`.

**Comment by alexeyshishkin01** [comment]
ok, thanks!
