### ISSUE TITLE
Kazoo 2.7.0 Compatibility

### ISSUE THREAD

**Issue by danyalprout** [zalando/patroni#1448]
Hi,

The latest version of Kazoo (2.7.0) has changed the [arguments to the connection method](https://github.com/python-zk/kazoo/blob/2.7.0/kazoo/protocol/connection.py#L622) method to include hostIP.

In the Patroni code we only [expect host/post](https://github.com/danyalprout/patroni/blob/master/patroni/dcs/zookeeper.py#L75-L79). This results in the following error when attempting to start Patroni using Zookeeper as a DCS.

```
2020-03-17 18:15:37,068 INFO: Zookeeper session closed, state: CLOSED
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kazoo/protocol/connection.py", line 497, in zk_loop
    if retry(self._connect_loop, retry) is STOP_CONNECTING:
  File "/usr/local/lib/python3.6/dist-packages/kazoo/retry.py", line 126, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kazoo/protocol/connection.py", line 537, in _connect_loop
    status = self._connect_attempt(host, hostip, port, retry)
  File "/usr/local/lib/python3.6/dist-packages/kazoo/protocol/connection.py", line 565, in _connect_attempt
    read_timeout, connect_timeout = self._connect(host, hostip, port)
TypeError: _kazoo_connect() takes 3 positional arguments but 4 were given
```

 I'm happy to submit a PR enabling `_kazoo_connect` to function in both scenarios. I just wanted to check in and make sure I've got the required context. 

Thanks

**Comment by CyberDem0n** [comment]
Yes please, I think it would be enough to replace arguments with `*args`.

**Comment by nealeu** [comment]
@CyberDem0n If you could bump a release out with this, it would help us, and probably plenty others.

I suspect someone with a bit of knowledge or time could configure Renovate to trigger a CI build with updated deps when a dependency is updated.

**Comment by Rajendra08** [comment]
@danyalprout 
Thanks for the fix.
When we can get release for this issue? 
In requirements.txt file given as  "kazoo>=1.3.1", so it is always picking 2.7.0 and we are not able to connect with zookeeper.

This needs to be released to unblock us.
