### ISSUE TITLE
Patroni doesnt realize cluster is unhealthy

### ISSUE THREAD

**Issue by threenotrump** [zalando/patroni#1450]
[patroni2.yml.txt](https://github.com/zalando/patroni/files/4347629/patroni2.yml.txt)
[patroni1.yml.txt](https://github.com/zalando/patroni/files/4347630/patroni1.yml.txt)
[patroni3.yml.txt](https://github.com/zalando/patroni/files/4347631/patroni3.yml.txt)

Hello 

I am new to patroni and tried to search my issue, checked my configuration  and couldnt find any solution.

If I missed anything I apologize in advance.

I have 3 node patroni etcd cluster.

When I shutdown one node patroni shows the remaining two nodes.

But when I shutdown the other node patroni doesnt realize the remaining node is down and cluster has failed.

OS: Centos 8 

Patroni version : patroni 1.6.4

Etcd version :  3.3.13

All three nodes running

[root@pg5 12]# etcdctl cluster-health
member 3a3178cfbb0eb9e is healthy: got healthy result from http://192.168.150.130:2379
member 427523d98696ed3b is healthy: got healthy result from http://192.168.150.129:2379
member ee7b613c5ce61d6b is healthy: got healthy result from http://192.168.150.131:2379
cluster is healthy
[root@pg5 12]# patronictl -c /etc/patroni.yml list
+----------+--------+-----------------+--------+---------+----+-----------+
| Cluster  | Member |       Host      |  Role  |  State  | TL | Lag in MB |
+----------+--------+-----------------+--------+---------+----+-----------+
| postgres | node1  | 192.168.150.129 | Leader | running |  3 |           |
| postgres | node2  | 192.168.150.130 |        | running |  3 |         0 |
| postgres | node3  | 192.168.150.131 |        | running |  3 |         0 |
+----------+--------+-----------------+--------+---------+----+-----------+

First node closed.

[root@pg5 12]# etcdctl cluster-health
member 3a3178cfbb0eb9e is healthy: got healthy result from http://192.168.150.130:2379
member 427523d98696ed3b is healthy: got healthy result from http://192.168.150.129:2379
failed to check the health of member ee7b613c5ce61d6b on http://192.168.150.131:2379: Get http://192.168.150.131:2379/health: dial tcp 192.168.150.131:2379: i/o timeout
member ee7b613c5ce61d6b is unreachable: [http://192.168.150.131:2379] are all unreachable
cluster is degraded
[root@pg5 12]# patronictl -c /etc/patroni.yml list
2020-03-18 10:53:33,163 - ERROR - Failed to get list of machines from http://192.168.150.131:2379/v2: MaxRetryError("HTTPConnectionPool(host='192.168.150.131', port=2379): Max retries exceeded with url: /v2/machines (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f708a0536d8>, 'Connection to 192.168.150.131 timed out. (connect timeout=3.3333333333333335)'))",)
+----------+--------+-----------------+--------+---------+----+-----------+
| Cluster  | Member |       Host      |  Role  |  State  | TL | Lag in MB |
+----------+--------+-----------------+--------+---------+----+-----------+
| postgres | node1  | 192.168.150.129 | Leader | running |  3 |           |
| postgres | node2  | 192.168.150.130 |        | running |  3 |         0 |
+----------+--------+-----------------+--------+---------+----+-----------+

Last node closed

[root@pg5 12]# etcdctl cluster-health
failed to check the health of member 3a3178cfbb0eb9e on http://192.168.150.130:2379: Get http://192.168.150.130:2379/health: dial tcp 192.168.150.130:2379: connect: no route to host
member 3a3178cfbb0eb9e is unreachable: [http://192.168.150.130:2379] are all unreachable
member 427523d98696ed3b is unhealthy: got unhealthy result from http://192.168.150.129:2379
failed to check the health of member ee7b613c5ce61d6b on http://192.168.150.131:2379: Get http://192.168.150.131:2379/health: dial tcp 192.168.150.131:2379: connect: no route to host
member ee7b613c5ce61d6b is unreachable: [http://192.168.150.131:2379] are all unreachable
cluster is unavailable
[root@pg5 12]# patronictl -c /etc/patroni.yml list
2020-03-18 10:57:14,669 - ERROR - Failed to get list of machines from http://192.168.150.131:2379/v2: MaxRetryError("HTTPConnectionPool(host='192.168.150.131', port=2379): Max retries exceeded with url: /v2/machines (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6e406216d8>: Failed to establish a new connection: [Errno 113] No route to host',))",)
+----------+--------+-----------------+--------+---------+----+-----------+
| Cluster  | Member |       Host      |  Role  |  State  | TL | Lag in MB |
+----------+--------+-----------------+--------+---------+----+-----------+
| postgres | node1  | 192.168.150.129 | Leader | running |  3 |           |
| postgres | node2  | 192.168.150.130 |        | running |  3 |         0 |
+----------+--------+-----------------+--------+---------+----+-----------+

Even though cluster is unavailable first node is still up and accepting connections.

Patroni shows 2 nodes remaining.

What am I missing here?

Shoudnt patroni realize cluster is gone and shutdown postgres?

Thanks very much for the help.

**Comment by CyberDem0n** [comment]
> But when I shutdown the other node patroni doesnt realize the remaining node is down and cluster has failed.

That's not correct, Patroni restarts primary in read-only mode, please examine Patroni logs on node1.
For more details you can read https://github.com/zalando/patroni/issues/1199

**Comment by threenotrump** [comment]
Thank you very much for the fast reply.

What you said is true postgres is started read only.

patroni log shows demoting of the last node.

When I checked patroni logs it printed the exceptions below.

If it is normal you close the issue.

Thanks again for the help.

2020-03-18 11:59:59,829 ERROR:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 469, in create_connection_patched
    raise err
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 459, in create_connection_patched
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f937874e828>: Failed to establish a new connection: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 193, in _do_http_request
    response = request_executor(method, url, fields=fields, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.150.131', port=2379): Max retries exceeded with url: /v2/keys/pg_cluster/postgres/leader (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f937874e828>: Failed to establish a new connection: [Errno 113] No route to host',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/etcd/client.py", line 828, in _next_server
    mach = self._machines_cache.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 391, in wrapper
    retval = func(self, *args, **kwargs) is not None
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 590, in _update_leader
    return self.retry(self._client.write, self.leader_path, self._name, prevValue=self._name, ttl=self._ttl)
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 375, in retry
    return retry(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/patroni/utils.py", line 330, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/etcd/client.py", line 500, in write
    response = self.api_execute(path, method, params=params)
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 243, in api_execute
    response = self._do_http_request(request_executor, method, self._base_uri + path, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 207, in _do_http_request
    self._base_uri = self._next_server(cause=e)
  File "/usr/local/lib/python3.6/site-packages/etcd/client.py", line 832, in _next_server
    cause=cause)
etcd.EtcdConnectionFailed: No more machines in the cluster
2020-03-18 11:59:59,830 ERROR: failed to update leader lock
2020-03-18 11:59:59,832 INFO: Selected new etcd server http://192.168.150.131:2379
