### ISSUE TITLE
Create Replica Fails after a few minutes

### ISSUE THREAD

**Issue by tyamell** [zalando/patroni#1460]
I'm trying to create a replica using wal-g from a large database. If I run a backup-fetch outside of patroni, the backup is pulled down correctly. 

However, it only runs for roughly 5 minutes inside of patroni and then is stopped. I enabled DEBUG logging I the only thing I see is a new consul session is created, instead of refreshing the existing one. I'm assuming this cancels out the create replica command? Any idea what is going on.

```2020-03-25 00:07:35,861 DEBUG: API thread: 10.178.12.54 - - [25/Mar/2020 00:07:35] OPTIONS /replica 503 latency: 0.102996826171875 ms
2020-03-25 00:07:35,936 DEBUG: API thread: 10.178.5.229 - - [25/Mar/2020 00:07:35] OPTIONS /replica 503 latency: 0.07510185241699219 ms
2020-03-25 00:07:36,188 DEBUG: API thread: 10.178.15.133 - - [25/Mar/2020 00:07:36] OPTIONS /replica 503 latency: 0.07200241088867188 ms
2020-03-25 00:07:36,689 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-03-25 00:07:36,690 DEBUG: https://127.0.0.1:8501 "PUT /v1/session/renew/97c406c3-0a05-4938-2b32-250fe8354ce4 HTTP/1.1" 200 276
2020-03-25 00:07:36,691 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-03-25 00:07:36,695 DEBUG: https://127.0.0.1:8501 "PUT /v1/kv/metricstore/main/members/ip-10-178-12-54.us-west-2.compute.internal?acquire=97c406c3-0a05-4938-2b32-250fe8354ce4 HTTP/1.1" 200 4
2020-03-25 00:07:36,696 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-03-25 00:07:36,697 DEBUG: https://127.0.0.1:8501 "GET /v1/kv/metricstore/main/?recurse=1 HTTP/1.1" 200 None
2020-03-25 00:07:36,698 INFO: Lock owner: ip-10-178-5-229.us-west-2.compute.internal; I am ip-10-178-12-54.us-west-2.compute.internal
2020-03-25 00:07:36,699 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-03-25 00:07:36,702 DEBUG: https://127.0.0.1:8501 "PUT /v1/kv/metricstore/main/members/ip-10-178-12-54.us-west-2.compute.internal?acquire=97c406c3-0a05-4938-2b32-250fe8354ce4 HTTP/1.1" 200 4
2020-03-25 00:07:58,973 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-03-25 00:07:58,973 DEBUG: Starting new HTTPS connection (1): 127.0.0.1:8501
2020-03-25 00:07:58,980 DEBUG: https://127.0.0.1:8501 "PUT /v1/session/create HTTP/1.1" 200 45
2020-03-25 00:07:58,987 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-03-25 00:07:58,989 DEBUG: https://127.0.0.1:8501 "GET /v1/kv/metricstore/main/?recurse=1 HTTP/1.1" 200 None
2020-03-25 00:07:58,991 INFO: No PostgreSQL configuration items changed, nothing to reload.
2020-03-25 00:07:59,007 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-03-25 00:07:59,008 DEBUG: https://127.0.0.1:8501 "GET /v1/kv/metricstore/main/?recurse=1 HTTP/1.1" 200 None
pg_controldata: could not open file "/mnt/data/main/global/pg_control" for reading: No such file or directory
2020-03-25 00:07:59,011 ERROR: Error when calling pg_controldata
Traceback (most recent call last):
  File "patroni/postgresql/__init__.py", line 636, in controldata
  File "subprocess.py", line 356, in check_output
  File "subprocess.py", line 438, in run
```

**Comment by CyberDem0n** [comment]
You didn't show the Patroni config and version, so it is hard to guess.
Assuming that you are using the default loop_wait and logs are interrupted for 22 seconds I can imagine that Patroni was killed and restarted, maybe due to the OOM.
