### ISSUE TITLE
patronictl list not work after recovery from "no space left"

### ISSUE THREAD

**Issue by qingguee** [zalando/patroni#1463]
Hello,
We meet "no space left" issue in our WAL file folder, after some clean up, we have enough space.
But "patronictl list" not work.

```
db-pg-0:/ # patronictl list
Traceback (most recent call last):
  File "/usr/local/bin/patronictl", line 11, in <module>
    load_entry_point('patroni==1.6.3', 'console_scripts', 'patronictl')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/patroni/ctl.py", line 781, in members
    output_members(cluster, cluster_name, extended, fmt)
  File "/usr/local/lib/python2.7/site-packages/patroni/ctl.py", line 707, in output_members
    cluster = cluster_as_json(cluster)
  File "/usr/local/lib/python2.7/site-packages/patroni/utils.py", line 391, in cluster_as_json
    conn_kwargs = m.conn_kwargs()
  File "/usr/local/lib/python2.7/site-packages/patroni/dcs/__init__.py", line 160, in conn_kwargs
    r = urlparse(self.conn_url)
  File "/usr/lib64/python2.7/urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib64/python2.7/urlparse.py", line 201, in urlsplit
    i = url.find(':')
AttributeError: 'NoneType' object has no attribute 'find'
```
- Patroni config
```
bootstrap:
  dcs:
    synchronous_mode: true
    postgresql:
      use_pg_rewind: true
  initdb:
  - auth-host: md5
  - auth-local: trust
  - encoding: UTF8
  - locale: en_US.UTF-8
  - data-checksums

  pg_hba:
  - host all all samehost md5
  - host all all ::0/0    md5
  - host all all all md5
  - host replication replica all md5
  post_init: /var/lib/postgresql/scripts/pg_init.sh
postgresql:
  callbacks:
    on_start: /var/lib/postgresql/scripts/patroni_callback.py
    on_stop: /var/lib/postgresql/scripts/patroni_callback.py
    on_role_change: /var/lib/postgresql/scripts/patroni_callback.py
  parameters:
    logging_collector: "off"
  pg_hba:
    - local all all trust
    - host all all 127.0.0.1/32 md5
    - host all all ::1/128 md5
    - local replication all trust
    - host replication all 127.0.0.1/32 md5
    - host replication all ::1/128 md5
    - host all all samehost md5
    - host all all ::0/0    md5
    - host all all all md5
    - host replication replica all md5
watchdog:
  mode: off

```

- But from log, the cluster is working
```
2020-03-26 05:47:36,847 INFO: does not have lock
2020-03-26 05:47:36,849 INFO: no action.  i am a secondary and i am following a leader
2020-03-26 05:47:46,847 INFO: Lock owner: db-pg-2; I am db-pg-0
2020-03-26 05:47:46,847 INFO: does not have lock
2020-03-26 05:47:46,849 INFO: no action.  i am a secondary and i am following a leader

```
```
db-pg-0                                              2/2     Running            0          165m
db-pg-1                                              1/2     CrashLoopBackOff   92         7h30m
db-pg-2                                              2/2     Running            0          3d12h
```

- I was deleted the POD, let it recreate. But still have this problem. 
- The traffic is like CREATE, then keep sending UPDATE every 2 seconds. So not heavy

**How can I recovery from this kind of problem? For example, is there any reset?** 

BRs,
Fan

**Comment by CyberDem0n** [comment]
Yeah, the issue is with `db-pg-1`, the pod is there, but not running, it confuses `patronictl`

**Comment by qingguee** [comment]
So, will there be some fix to handling this error? I mean it block other actions(e.g. patronictl reinit)

The expected behavior is that Patroni handle this error, it should not block any function.

BRs,
Fan
