### ISSUE TITLE
Cant install on CentOS 8.1.1911 with Python 2.7.16 and setuptools 39.0.1

### ISSUE THREAD

**Issue by izharsky** [zalando/patroni#1464]
[root@centos81-01 ~]# pip2 install patroni[zookeeper]
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip2 install --user` instead.
Collecting patroni[zookeeper]
  Using cached https://files.pythonhosted.org/packages/13/fd/5096b2ba31ce61f97999be3475d1f4c2c21756bd65940fa3d8374340f9de/patroni-1.6.4.tar.gz
    Complete output from command python setup.py egg_info:
    /usr/lib/python2.7/site-packages/setuptools/dist.py:397: UserWarning: Normalizing '3.2.3-2' to '3.2.3.post2'
      normalized_version,
    warning: no files found matching '*.txt'
    no previously-included directories found matching 'build'
    no previously-included directories found matching 'dist'
    no previously-included directories found matching '.git*'
    zip_safe flag not set; analyzing archive contents...

    Installed /tmp/pip-build-dc0XWh/patroni/.eggs/functools32-3.2.3.post2-py2.7.egg
    Searching for enum34
    Reading https://pypi.python.org/simple/enum34/
    Downloading https://files.pythonhosted.org/packages/6f/2c/a9386903ece2ea85e9807e0e062174dc26fdce8b05f216d00491be29fad5/enum34-1.1.10-py2-none-any.whl#sha256=a98a201d6de3f2ab3db284e70a33b0f896fbf35f8086594e8c9e74b909058d53
    Best match: enum34 1.1.10
    Processing enum34-1.1.10-py2-none-any.whl
    Installing enum34-1.1.10-py2-none-any.whl to /tmp/pip-build-dc0XWh/patroni/.eggs

    Installed /tmp/pip-build-dc0XWh/patroni/.eggs/enum34-1.1.10-py2.7.egg
    Searching for entrypoints<0.4.0,>=0.3.0
    Reading https://pypi.python.org/simple/entrypoints/
    Downloading https://files.pythonhosted.org/packages/ac/c6/44694103f8c221443ee6b0041f69e2740d89a25641e62fb4f2ee568f2f9c/entrypoints-0.3-py2.py3-none-any.whl#sha256=589f874b313739ad35be6e0cd7efde2a4e9b6fea91edcc34e58ecbb8dbe56d19
    Best match: entrypoints 0.3
    Processing entrypoints-0.3-py2.py3-none-any.whl
    Installing entrypoints-0.3-py2.py3-none-any.whl to /tmp/pip-build-dc0XWh/patroni/.eggs
    writing requirements to /tmp/pip-build-dc0XWh/patroni/.eggs/entrypoints-0.3-py2.7.egg/EGG-INFO/requires.txt

    Installed /tmp/pip-build-dc0XWh/patroni/.eggs/entrypoints-0.3-py2.7.egg
    Searching for configparser
    Reading https://pypi.python.org/simple/configparser/
    Downloading https://files.pythonhosted.org/packages/e5/7c/d4ccbcde76b4eea8cbd73b67b88c72578e8b4944d1270021596e80b13deb/configparser-5.0.0.tar.gz#sha256=2ca44140ee259b5e3d8aaf47c79c36a7ab0d5e94d70bd4105c03ede7a20ea5a1
    Best match: configparser 5.0.0
    Processing configparser-5.0.0.tar.gz
    Writing /tmp/easy_install-ndBRby/configparser-5.0.0/setup.cfg
    Running configparser-5.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ndBRby/configparser-5.0.0/egg-dist-tmp-NJPZhS
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-dc0XWh/patroni/setup.py", line 166, in <module>
        setup_package(__version__)
      File "/tmp/pip-build-dc0XWh/patroni/setup.py", line 150, in setup_package
        entry_points={'console_scripts': CONSOLE_SCRIPTS},
      File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 513, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1057, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1069, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 580, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 672, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 698, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 883, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1151, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1139, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: 'egg_base' must be a directory name (got `src`)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dc0XWh/patroni/

**Comment by CyberDem0n** [comment]
Python 2.7 in EOL since 1st of January 2020

**Comment by izharsky** [comment]
Workarounded by installing
`python2-devel gcc platform-python-devel`
and installing via pip3
