### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'pg_controldata': 'pg_controldata'

### ISSUE THREAD

**Issue by aogb** [zalando/patroni#1468]
After setting up master/slave replication and with integration of Patroni, i receive the error message when starting patroni.

My postgres is installed with docker.

FileNotFoundError: [Errno 2] No such file or directory: 'pg_controldata': 'pg_controldata'

**Comment by CyberDem0n** [comment]
Please use [search](https://github.com/zalando/patroni/issues?q=is%3Aissue+No+such+file+or+directory%3A+pg_controldata+is%3Aclosed).

**Comment by aogb** [comment]
Hello, But i did. I didn't anything related please

**Comment by Kar1na90** [comment]
I'm getting the same error while trying to upgrade from 12 to 13 (using docker with patroni):

│ timescaledb Process Process-1:                                                                                                                                                                                                                             │
Traceback (most recent call last):                                                                                                                                                                                                             File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap                                                                                                                                                                self.run()                                                                                                                                                                                                                                  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run                                                                                                                                                                        self._target(*self._args, **self._kwargs)                                                                                                                                                                                                  File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 138, in patroni_main                                                                                                                                                         abstract_main(Patroni, schema)                                                                                                                                                                                                             File "/usr/lib/python3/dist-packages/patroni/daemon.py", line 98, in abstract_main                                                                                                                                                           controller = cls(config)                                                                                                                                                                                                                   File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 33, in __init__                                                                                                                                                              self.postgresql = Postgresql(self.config['postgresql'])                                                                                                                                                                                    File "/usr/lib/python3/dist-packages/patroni/postgresql/__init__.py", line 100, in __init__                                                                                                                                                  self.set_role(self.get_postgres_role_from_data_directory())                                                                                                                                                                                File "/usr/lib/python3/dist-packages/patroni/postgresql/__init__.py", line 232, in get_postgres_role_from_data_directory                                                                                                                     if self.data_directory_empty() or not self.controldata():                                                                                                                                                                                  File "/usr/lib/python3/dist-packages/patroni/postgresql/__init__.py", line 718, in controldata                                                                                                                                               data = subprocess.check_output([self.pgcommand('pg_controldata'), self._data_dir], env=env)                                                                                                                                                File "/usr/lib/python3.7/subprocess.py", line 395, in check_output                                                                                                                                                                           **kwargs).stdout                                                                                                                                                                                                                           File "/usr/lib/python3.7/subprocess.py", line 472, in run                                                                                                                                                                                    with Popen(*popenargs, **kwargs) as process:                                                                                                                                                                                               File "/usr/lib/python3.7/subprocess.py", line 775, in __init__                                                                                                                                                                               restore_signals, start_new_session)                                                                                                                                                                                                        File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child                                                                                                                                                                        raise child_exception_type(errno_num, err_msg, err_filename)                                                                                                                                                                               FileNotFoundError: [Errno 2] No such file or directory: 'pg_controldata': 'pg_controldata'

**Comment by krun2010qq** [comment]
I have similar error when try to setup the patroni with systemd.. I can set it up correctly with postgres user tho..

**Comment by krun2010qq** [comment]
ok, I fixed the issue by adding the below line of my patroni.service file for systemd

`Environment=PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/vmware/postgres/12/bin/`

So, basically it is PATH issue.
