### ISSUE TITLE
Replication connection error: could not connect to server: FATAL:  password authentication failed for user "replicator"

### ISSUE THREAD

**Issue by pySilver** [zalando/patroni#1489]
First make sure correct pg_hba.conf is in use:

```
postgres@18aa43abe82c:/$ psql
psql (12.2 (Debian 12.2-2.pgdg100+1))
Type "help" for help.

postgres=# select current_setting('hba_file');
                 current_setting
-------------------------------------------------
 /var/lib/postgresql/data/postgres-3/pg_hba.conf
(1 row)

postgres=# \q
postgres@18aa43abe82c:/$ cat /var/lib/postgresql/data/postgres-3/pg_hba.conf
# Do not edit this file manually!
# It will be overwritten by Patroni!
host replication replicator 127.0.0.1/32 md5
host replication replicator 10.0.0.0/24 md5
host all all 0.0.0.0/0 md5
```

Then lets try to connect to current leader manually with login and password from 10.0.0.5 to 10.0.0.7:

```
# Running on 10.0.0.5
postgres@93873aaf2ab3:/$ psql -h 10.0.0.7 postgres -U replicator -W
Password:
psql (12.2 (Debian 12.2-2.pgdg100+1))
Type "help" for help.

postgres=>
```

Looks correct. However patroni fails to connect. Current leader logs are full of:

```
2020-04-13 14:01:27,905 INFO: Lock owner: node-postgres-3; I am node-postgres-3
2020-04-13 14:01:27,917 INFO: no action.  i am the leader with the lock
2020-04-13 14:01:30 UTC [691]: [1-1] 5e9470ba.2b3 0 [unknown] [unknown] [unknown] 10.0.0.7 LOG:  connection received: host=10.0.0.7 port=34718
2020-04-13 14:01:31 UTC [692]: [1-1] 5e9470bb.2b4 0 [unknown] [unknown] [unknown] 10.0.0.5 LOG:  connection received: host=10.0.0.5 port=48302
2020-04-13 14:01:31 UTC [692]: [2-1] 5e9470bb.2b4 0 [unknown] replicator [unknown] 10.0.0.5 FATAL:  password authentication failed for user "replicator"
2020-04-13 14:01:31 UTC [692]: [3-1] 5e9470bb.2b4 0 [unknown] replicator [unknown] 10.0.0.5 DETAIL:  Password does not match for user "replicator".
 Connection matched pg_hba.conf line 5: "host  replication replicator 10.0.0.0/24    md5”
```

Looks like a bug? 

patroni.yml config:

```
---
scope: postgres
name: node-postgres-3
namespace: /patroni

consul:
  host: 10.0.0.7
  port: 8500
  token: <my-token-here>
  register_service: true

restapi:
  listen: ':8008'
  connect_address: 10.0.0.7:8008

bootstrap:
  method: initdb
  intidb:
    - data-checksums
    - encoding: UTF8
    - locale: en_US.UTF-8
  walg:
    command: wal-g backup-fetch /var/lib/postgresql/data/postgres-3 LATEST
    keep_existing_recovery_conf: false
    recovery_conf:
      recovery_target_action: promote
      recovery_target_timeline: latest
      recovery_target_inclusive: true
      restore_command: wal-g wal-fetch "%f" "%p"
  pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 10.0.0.0/24 md5
    - host all all 0.0.0.0/0 md5
  dcs:
    loop_wait: 10
    ttl: 30
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    synchronous_mode_strict: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        archive_mode: "on"
        archive_timeout: 300s
        archive_command: wal-g wal-push "%p"
        wal_level: replica
        wal_keep_segments: 8
        wal_log_hints: "on"
        max_wal_senders: 10
        max_replication_slots: 10
        hot_standby: "on"

postgresql:
  authentication:
    superuser:
      username: postgres
      password: mypassword
    replication:
      username: replicator
      password: mypassword
    rewind:
      username: rewind
      password: mypassword
  listen: '*:5432'
  connect_address: 10.0.0.7:5432
  data_dir: /var/lib/postgresql/data/postgres-3
  pgpass: /var/run/postgresql/.pgpass
  #recovery_conf:
  #  restore_command: wal-g wal-fetch "%f" "%p"
  #  recovery_target_timeline: latest
  #  recovery_target_action: promote
  #  recovery_target_inclusive: true
  pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 10.0.0.0/24 md5
    - host all all 0.0.0.0/0 md5
  parameters:
    shared_preload_libraries: 'pg_stat_statements'
    tcp_keepalives_idle: 900
    tcp_keepalives_interval: 100
    log_destination: "stderr"
    log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
    log_checkpoints: 'on'
    log_lock_waits: 'on'
    log_min_duration_statement: 500
    log_autovacuum_min_duration: 0
    log_connections: 'on'
    log_disconnections: 'on'
    log_statement: 'ddl'
    log_temp_files: 0
    track_functions: all
  create_replica_methods:
    #- wal_g
    - basebackup
  wal_g:
    command: wal-g backup-fetch /var/lib/postgresql/data/postgres-3 LATEST
    no_master: 1
    no_params: true
  basebackup:
    max-rate: "100M"
    checkpoint: fast

watchdog:
  mode: off

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
```

Patroni: `patronictl version 1.6.4`
PostgreSQL: `postgres (PostgreSQL) 12.2 (Debian 12.2-2.pgdg100+1)`

Similar issue: #951

**Comment by pySilver** [comment]
It works fine only when I use `host replication replicator 10.0.0.0/24 trust` instead of md5, but that does not look right to me..

**Comment by CyberDem0n** [comment]
Postgres refusing connections has nothing to do with Patroni.

When testing with psql you are not using the replication protocol. You have to use pg_basebackup or pg_recievewal.

**Comment by pySilver** [comment]
Can I somehow see the password that has been used in request then? Does it
has anything to do with .pgpass presence?

Thats really hard to find the root of a problem :/

W dniu pon., 13.04.2020 o 18:38 Alexander Kukushkin <
notifications@github.com> napisał(a):

**Comment by pySilver** [comment]
@CyberDem0n well I've just tested and it still not working:


Content of `.pgpass` file:
```
postgres@9b9bacdfac0c:/$ cat /var/lib/postgresql/.pgpass
10.0.0.7:5432:*:replicator:EwMLrnDCqPz6utpostgres@9b9bacdfac0c:/$
```
so it's `10.0.0.7:5432:*:replicator:EwMLrnDCqPz6ut` (no newline, so shell output joined lines)

Trying to connect without password (FAIL):
```
postgres@9b9bacdfac0c:/$ pg_basebackup -P -R -X stream -c fast -h 10.0.0.7 -U replicator -D /var/lib/postgresql/data/test
pg_basebackup: error: could not connect to server: FATAL:  password authentication failed for user "replicator"
```

Trying to connect with password promt (SUCCESS):
postgres@9b9bacdfac0c:/$ pg_basebackup -P -R -X stream -c fast -h 10.0.0.7 -U replicator -D /var/lib/postgresql/data/test -W
Password:
24595/24595 kB (100%), 1/1 tablespace
postgres@9b9bacdfac0c:/$
```

**Comment by pySilver** [comment]
Logs on follower:

```
2020-04-13 17:23:56,331 INFO: Lock owner: node-postgres-3; I am node-postgres-1
2020-04-13 17:23:56,332 INFO: does not have lock
2020-04-13 17:23:56 UTC [2921]: [1-1] 5e94a02c.b69 0 [unknown] [unknown] [unknown] 127.0.0.1 LOG:  connection received: host=127.0.0.1 port=51820
2020-04-13 17:23:56 UTC [2921]: [2-1] 5e94a02c.b69 0 [unknown] replicator [unknown] 127.0.0.1 LOG:  replication connection authorized: user=replicator
2020-04-13 17:23:56 UTC [2921]: [3-1] 5e94a02c.b69 0 [unknown] replicator [unknown] 127.0.0.1 LOG:  disconnection: session time: 0:00:00.006 user=replicator database= host=127.0.0.1 port=51820
2020-04-13 17:23:56,347 INFO: no action.  i am a secondary and i am following a leader
ERROR: 2020/04/13 17:23:56.374233 Archive '00000005000000000000000F' does not exist.
2020-04-13 17:23:56 UTC [2922]: [1-1] 5e94a02c.b6a 0     FATAL:  could not connect to the primary server: FATAL:  password authentication failed for user "replicator"
ERROR: 2020/04/13 17:23:56.613840 Archive '00000006.history' does not exist.
2020-04-13 17:23:57 UTC [2931]: [1-1] 5e94a02d.b73 0 [unknown] [unknown] [unknown] 10.0.0.6 LOG:  connection received: host=10.0.0.6 port=39298
ERROR: 2020/04/13 17:24:01.351949 Archive '00000005000000000000000F' does not exist.
2020-04-13 17:24:01 UTC [2941]: [1-1] 5e94a031.b7d 0     FATAL:  could not connect to the primary server: FATAL:  password authentication failed for user "replicator"
ERROR: 2020/04/13 17:24:01.561265 Archive '00000006.history' does not exist.
2020-04-13 17:24:06,344 INFO: Lock owner: node-postgres-3; I am node-postgres-1
2020-04-13 17:24:06,344 INFO: does not have lock
2020-04-13 17:24:06 UTC [2959]: [1-1] 5e94a036.b8f 0 [unknown] [unknown] [unknown] 127.0.0.1 LOG:  connection received: host=127.0.0.1 port=51842
2020-04-13 17:24:06 UTC [2959]: [2-1] 5e94a036.b8f 0 [unknown] replicator [unknown] 127.0.0.1 LOG:  replication connection authorized: user=replicator
2020-04-13 17:24:06 UTC [2959]: [3-1] 5e94a036.b8f 0 [unknown] replicator [unknown] 127.0.0.1 LOG:  disconnection: session time: 0:00:00.007 user=replicator database= host=127.0.0.1 port=51842
2020-04-13 17:24:06,364 INFO: no action.  i am a secondary and i am following a leader
2020-04-13 17:24:06 UTC [192]: [11-1] 5e949de5.c0 0     LOG:  restored log file "00000005000000000000000F" from archive
ERROR: 2020/04/13 17:24:06.776398 Archive '000000050000000000000010' does not exist.
2020-04-13 17:24:06 UTC [2973]: [1-1] 5e94a036.b9d 0     FATAL:  could not connect to the primary server: FATAL:  password authentication failed for user "replicator"
ERROR: 2020/04/13 17:24:06.974582 Archive '00000006.history' does not exist.
2020-04-13 17:24:07 UTC [2981]: [1-1] 5e94a037.ba5 0 [unknown] [unknown] [unknown] 10.0.0.6 LOG:  connection received: host=10.0.0.6 port=39374
ERROR: 2020/04/13 17:24:11.383264 Archive '000000050000000000000010' does not exist.
2020-04-13 17:24:11 UTC [2991]: [1-1] 5e94a03b.baf 0     FATAL:  could not connect to the primary server: FATAL:  password authentication failed for user "replicator"
ERROR: 2020/04/13 17:24:11.586716 Archive '00000006.history' does not exist.
2020-04-13 17:24:15 UTC [251]: [4-1] 5e949de7.fb 0     LOG:  restartpoint starting: time
2020-04-13 17:24:15 UTC [251]: [5-1] 5e949de7.fb 0     LOG:  restartpoint complete: wrote 0 buffers (0.0%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.001 s, sync=0.000 s, total=0.009 s; sync files=0, longest=0.000 s, average=0.000 s; distance=16384 kB, estimate=31129 kB
2020-04-13 17:24:15 UTC [251]: [6-1] 5e949de7.fb 0     LOG:  recovery restart point at 0/F000060
2020-04-13 17:24:16,238 INFO: Lock owner: node-postgres-3; I am node-postgres-1
2020-04-13 17:24:16,240 INFO: does not have lock
2020-04-13 17:24:16 UTC [3008]: [1-1] 5e94a040.bc0 0 [unknown] [unknown] [unknown] 127.0.0.1 LOG:  connection received: host=127.0.0.1 port=51918
2020-04-13 17:24:16 UTC [3008]: [2-1] 5e94a040.bc0 0 [unknown] replicator [unknown] 127.0.0.1 LOG:  replication connection authorized: user=replicator
2020-04-13 17:24:16 UTC [3008]: [3-1] 5e94a040.bc0 0 [unknown] replicator [unknown] 127.0.0.1 LOG:  disconnection: session time: 0:00:00.010 user=replicator database= host=127.0.0.1 port=51918
2020-04-13 17:24:16,271 INFO: no action.  i am a secondary and i am following a leader
ERROR: 2020/04/13 17:24:16.393219 Archive '000000050000000000000010' does not exist.
2020-04-13 17:24:16 UTC [3009]: [1-1] 5e94a040.bc1 0     FATAL:  could not connect to the primary server: FATAL:  password authentication failed for user "replicator"
ERROR: 2020/04/13 17:24:16.600547 Archive '00000006.history' does not exist.
2020-04-13 17:24:17 UTC [3017]: [1-1] 5e94a041.bc9 0 [unknown] [unknown] [unknown] 10.0.0.6 LOG:  connection received: host=10.0.0.6 port=39396
ERROR: 2020/04/13 17:24:21.399686 Archive '000000050000000000000010' does not exist.
2020-04-13 17:24:21 UTC [3027]: [1-1] 5e94a045.bd3 0     FATAL:  could not connect to the primary server: FATAL:  password authentication failed for user "replicator"
ERROR: 2020/04/13 17:24:21.612379 Archive '00000006.history' does not exist.
```

Logs on current leader:

```
2020-04-13 17:25:34,718 INFO: Lock owner: node-postgres-3; I am node-postgres-3
2020-04-13 17:25:34,724 INFO: no action.  i am the leader with the lock
2020-04-13 17:25:36 UTC [744]: [1-1] 5e94a090.2e8 0 [unknown] [unknown] [unknown] 10.0.0.7 LOG:  connection received: host=10.0.0.7 port=45488
2020-04-13 17:25:36 UTC [745]: [1-1] 5e94a090.2e9 0 [unknown] [unknown] [unknown] 10.0.0.6 LOG:  connection received: host=10.0.0.6 port=39898
2020-04-13 17:25:36 UTC [745]: [2-1] 5e94a090.2e9 0 [unknown] replicator [unknown] 10.0.0.6 FATAL:  password authentication failed for user "replicator"
2020-04-13 17:25:36 UTC [745]: [3-1] 5e94a090.2e9 0 [unknown] replicator [unknown] 10.0.0.6 DETAIL:  Password does not match for user "replicator".
	Connection matched pg_hba.conf line 4: "host replication replicator 10.0.0.0/24 md5"
2020-04-13 17:25:38 UTC [746]: [1-1] 5e94a092.2ea 0 [unknown] [unknown] [unknown] 10.0.0.5 LOG:  connection received: host=10.0.0.5 port=36328
2020-04-13 17:25:38 UTC [746]: [2-1] 5e94a092.2ea 0 [unknown] replicator [unknown] 10.0.0.5 FATAL:  password authentication failed for user "replicator"
2020-04-13 17:25:38 UTC [746]: [3-1] 5e94a092.2ea 0 [unknown] replicator [unknown] 10.0.0.5 DETAIL:  Password does not match for user "replicator".
	Connection matched pg_hba.conf line 4: "host replication replicator 10.0.0.0/24 md5"
2020-04-13 17:25:41 UTC [748]: [1-1] 5e94a095.2ec 0 [unknown] [unknown] [unknown] 10.0.0.6 LOG:  connection received: host=10.0.0.6 port=39912
2020-04-13 17:25:41 UTC [748]: [2-1] 5e94a095.2ec 0 [unknown] replicator [unknown] 10.0.0.6 FATAL:  password authentication failed for user "replicator"
2020-04-13 17:25:41 UTC [748]: [3-1] 5e94a095.2ec 0 [unknown] replicator [unknown] 10.0.0.6 DETAIL:  Password does not match for user "replicator".
	Connection matched pg_hba.conf line 4: "host replication replicator 10.0.0.0/24 md5"
```

**Comment by CyberDem0n** [comment]
Something is fishy here. Patroni for sure supports pg12 without any issues.
Where is the postgres home directory? Is there .pgpass file? Can it be that there's a mesh of postgres libraries (libpq)?
Try it on the freshly setup host and I am 100% sure it'll work.

**Comment by pySilver** [comment]
@CyberDem0n thats 3xVM with plain docker container based on https://hub.docker.com/_/postgres (postgres:12) with only addition - patroni installation. So we can call it "fresh".  I'm going to reset it all once again with the following config and report back here.

```
postgres@9b9bacdfac0c:/$ cat /secrets/patroni.yml
---
scope: postgres
name: node-postgres-1
namespace: /patroni

consul:
  host: 10.0.0.6
  port: 8500
  token: <hidden>
  register_service: true

restapi:
  listen: ':8008'
  connect_address: 10.0.0.6:8008

bootstrap:
  method: initdb
  intidb:
    - data-checksums
    - encoding: UTF8
    - locale: en_US.UTF-8
  walg:
    command: wal-g backup-fetch /var/lib/postgresql/data/postgres-1 LATEST
    keep_existing_recovery_conf: false
    recovery_conf:
      recovery_target_action: promote
      recovery_target_timeline: latest
      recovery_target_inclusive: true
      restore_command: wal-g wal-fetch "%f" "%p"
  dcs:
    loop_wait: 10
    ttl: 30
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    synchronous_mode_strict: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        archive_mode: "on"
        archive_timeout: 300s
        archive_command: wal-g wal-push "%p"
        wal_level: replica
        wal_keep_segments: 8
        wal_log_hints: "on"
        max_wal_senders: 10
        max_replication_slots: 10
        hot_standby: "on"

postgresql:
  authentication:
    superuser:
      username: postgres
      password: testpassword
    replication:
      username: replicator
      password: testpassword
    rewind:
      username: rewind
      password: testpassword
  listen: '*:5432'
  connect_address: 10.0.0.6:5432
  data_dir: /var/lib/postgresql/data/postgres-1
  pgpass: /var/lib/postgresql/.pgpass
  recovery_conf:
    restore_command: wal-g wal-fetch "%f" "%p"
    recovery_target_timeline: latest
    recovery_target_action: promote
    recovery_target_inclusive: true
  pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 10.0.0.0/24 md5
    - host all all 0.0.0.0/0 md5
  parameters:
    shared_preload_libraries: 'pg_stat_statements'
    tcp_keepalives_idle: 900
    tcp_keepalives_interval: 100
    log_destination: "stderr"
    log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
    log_checkpoints: 'on'
    log_lock_waits: 'on'
    log_min_duration_statement: 500
    log_autovacuum_min_duration: 0
    log_connections: 'on'
    log_disconnections: 'on'
    log_statement: 'ddl'
    log_temp_files: 0
    track_functions: all
  create_replica_methods:
    - basebackup
  wal_g:
    command: wal-g backup-fetch /var/lib/postgresql/data/postgres-1 LATEST
    no_master: 1
    no_params: true
  basebackup:
    max-rate: "100M"
    checkpoint: fast

watchdog:
  mode: off

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
```

**Comment by pySilver** [comment]
@CyberDem0n Nah, same problem. 3 nodes. 1 elected to be master and 2 cannot authenticate to replicate.

.pgpass is here:
# root @ postgres-1 in ~ [18:07:38]
$ docker exec -it f4130028428e bash
postgres@f4130028428e:/$ ls -la /var/lib/postgresql/
total 20
drwxr-xr-x 1 postgres postgres 4096 Apr 13 18:04 .
drwxr-xr-x 1 root     root     4096 Apr 13 10:28 ..
drwx------ 2 postgres postgres 4096 Apr 13 17:56 data
-rw------- 1 postgres postgres   41 Apr 13 18:07 .pgpass
postgres@f4130028428e:/$ cat /var/lib/postgresql/.pgpass
10.0.0.7:5432:*:replicator: testpasswordpostgres@f4130028428e:/$
```

**Comment by pySilver** [comment]
Nope, having the same data_dir does not help.

```2020-04-13 18:16:01,035 INFO: trying to bootstrap a new cluster
initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
2020-04-13 18:16:02 UTC [34]: [1-1] 5e94ac62.22 0     LOG:  starting PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2020-04-13 18:16:02 UTC [34]: [2-1] 5e94ac62.22 0     LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-04-13 18:16:02 UTC [34]: [3-1] 5e94ac62.22 0     LOG:  listening on IPv6 address "::", port 5432
2020-04-13 18:16:02 UTC [34]: [4-1] 5e94ac62.22 0     LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-04-13 18:16:02,200 INFO: postmaster pid=34
2020-04-13 18:16:02 UTC [36]: [1-1] 5e94ac62.24 0     LOG:  database system was shut down at 2020-04-13 18:16:01 UTC
2020-04-13 18:16:02 UTC [34]: [5-1] 5e94ac62.22 0     LOG:  database system is ready to accept connections
2020-04-13 18:16:02 UTC [44]: [1-1] 5e94ac62.2c 0 [unknown] [unknown] [unknown] 127.0.0.1 LOG:  connection received: host=127.0.0.1 port=50850
2020-04-13 18:16:02 UTC [44]: [2-1] 5e94ac62.2c 0 postgres postgres [unknown] 127.0.0.1 LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2020-04-13 18:16:02 UTC [44]: [3-1] 5e94ac62.2c 0 postgres postgres pg_isready 127.0.0.1 LOG:  disconnection: session time: 0:00:00.012 user=postgres database=postgres host=127.0.0.1 port=50850
2020-04-13 18:16:02 UTC [46]: [1-1] 5e94ac62.2e 0 [unknown] [unknown] [unknown] 127.0.0.1 LOG:  connection received: host=127.0.0.1 port=50852
2020-04-13 18:16:02 UTC [46]: [2-1] 5e94ac62.2e 0 postgres postgres [unknown] 127.0.0.1 LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2020-04-13 18:16:02 UTC [46]: [3-1] 5e94ac62.2e 0 postgres postgres pg_isready 127.0.0.1 LOG:  disconnection: session time: 0:00:00.009 user=postgres database=postgres host=127.0.0.1 port=50852
2020-04-13 18:16:02,333 INFO: establishing a new patroni connection to the postgres cluster
2020-04-13 18:16:02 UTC [47]: [1-1] 5e94ac62.2f 0 [unknown] [unknown] [unknown] 127.0.0.1 LOG:  connection received: host=127.0.0.1 port=50854
2020-04-13 18:16:02 UTC [47]: [2-1] 5e94ac62.2f 0 postgres postgres [unknown] 127.0.0.1 LOG:  connection authorized: user=postgres database=postgres application_name=Patroni
2020-04-13 18:16:02,361 WARNING: Could not register service: unknown role type promoted
2020-04-13 18:16:02,361 INFO: running post_bootstrap
2020-04-13 18:16:02,455 INFO: Register service postgres, params {'service_id': 'postgres/node-postgres-3', 'address': '10.0.0.7', 'port': 5432, 'check': {'http': 'http://10.0.0.7:8008/master', 'interval': '5s', 'DeregisterCriticalServiceAfter': '150.0s'}, 'tags': ['master']}
2020-04-13 18:16:02,477 INFO: initialized a new cluster
2020-04-13 18:16:09 UTC [51]: [1-1] 5e94ac69.33 0 [unknown] [unknown] [unknown] 10.0.0.7 LOG:  connection received: host=10.0.0.7 port=49160
2020-04-13 18:16:11 UTC [53]: [1-1] 5e94ac6b.35 0 [unknown] [unknown] [unknown] 10.0.0.6 LOG:  connection received: host=10.0.0.6 port=42842
2020-04-13 18:16:11 UTC [53]: [2-1] 5e94ac6b.35 0 [unknown] replicator [unknown] 10.0.0.6 FATAL:  password authentication failed for user "replicator"
2020-04-13 18:16:11 UTC [53]: [3-1] 5e94ac6b.35 0 [unknown] replicator [unknown] 10.0.0.6 DETAIL:  Password does not match for user "replicator".
	Connection matched pg_hba.conf line 4: "host replication replicator 10.0.0.0/24 md5"
2020-04-13 18:16:11 UTC [54]: [1-1] 5e94ac6b.36 0 [unknown] [unknown] [unknown] 10.0.0.5 LOG:  connection received: host=10.0.0.5 port=41434
2020-04-13 18:16:11 UTC [54]: [2-1] 5e94ac6b.36 0 [unknown] replicator [unknown] 10.0.0.5 FATAL:  password authentication failed for user "replicator"
2020-04-13 18:16:11 UTC [54]: [3-1] 5e94ac6b.36 0 [unknown] replicator [unknown] 10.0.0.5 DETAIL:  Password does not match for user "replicator".
	Connection matched pg_hba.conf line 4: "host replication replicator 10.0.0.0/24 md5"
2020-04-13 18:16:12,388 INFO: Lock owner: node-postgres-3; I am node-postgres-3
2020-04-13 18:16:12,401 INFO: Lock owner: node-postgres-3; I am node-postgres-3
2020-04-13 18:16:12,454 INFO: no action.  i am the leader with the lock
2020-04-13 18:16:16 UTC [57]: [1-1] 5e94ac70.39 0 [unknown] [unknown] [unknown] 10.0.0.6 LOG:  connection received: host=10.0.0.6 port=42844
2020-04-13 18:16:16 UTC [57]: [2-1] 5e94ac70.39 0 [unknown] replicator [unknown] 10.0.0.6 FATAL:  password authentication failed for user "replicator"
2020-04-13 18:16:16 UTC [57]: [3-1] 5e94ac70.39 0 [unknown] replicator [unknown] 10.0.0.6 DETAIL:  Password does not match for user "replicator".
	Connection matched pg_hba.conf line 4: "host replication replicator 10.0.0.0/24 md5"
2020-04-13 18:16:16 UTC [58]: [1-1] 5e94ac70.3a 0 [unknown] [unknown] [unknown] 10.0.0.5 LOG:  connection received: host=10.0.0.5 port=41438
2020-04-13 18:16:16 UTC [58]: [2-1] 5e94ac70.3a 0 [unknown] replicator [unknown] 10.0.0.5 FATAL:  password authentication failed for user "replicator"
2020-04-13 18:16:16 UTC [58]: [3-1] 5e94ac70.3a 0 [unknown] replicator [unknown] 10.0.0.5 DETAIL:  Password does not match for user "replicator".
	Connection matched pg_hba.conf line 4: "host replication replicator 10.0.0.0/24 md5"
2020-04-13 18:16:19 UTC [59]: [1-1] 5e94ac73.3b 0 [unknown] [unknown] [unknown] 10.0.0.7 LOG:  connection received: host=10.0.0.7 port=49170
2020-04-13 18:16:21 UTC [61]: [1-1] 5e94ac75.3d 0 [unknown] [unknown] [unknown] 10.0.0.6 LOG:  connection received: host=10.0.0.6 port=42850
2020-04-13 18:16:21 UTC [61]: [2-1] 5e94ac75.3d 0 [unknown] replicator [unknown] 10.0.0.6 FATAL:  password authentication failed for user "replicator"
2020-04-13 18:16:21 UTC [61]: [3-1] 5e94ac75.3d 0 [unknown] replicator [unknown] 10.0.0.6 DETAIL:  Password does not match for user "replicator".```

and the passive node:

```pg_basebackup: error: could not connect to server: FATAL:  password authentication failed for user "replicator"
2020-04-13 18:19:36,375 ERROR: Error when fetching backup: pg_basebackup exited with code=1
2020-04-13 18:19:36,376 ERROR: failed to bootstrap from leader 'node-postgres-3'
2020-04-13 18:19:36,376 INFO: Removing data directory: /var/lib/postgresql/data/pgdata
2020-04-13 18:19:41,228 INFO: Lock owner: node-postgres-3; I am node-postgres-2
2020-04-13 18:19:41,240 INFO: trying to bootstrap from leader 'node-postgres-3'
pg_basebackup: error: could not connect to server: FATAL:  password authentication failed for user "replicator"
2020-04-13 18:19:41,305 ERROR: Error when fetching backup: pg_basebackup exited with code=1
2020-04-13 18:19:41,306 WARNING: Trying again in 5  seconds```

I think I need to go with "trust" connection for my internal network, I'm literally out of ideas what can cause all this troubles.  :(

**Comment by CyberDem0n** [comment]
```
    replication:
      username: replicator
      password: testpassword
```

I hope it is set to the same value on **_all_** nodes.

**Comment by CyberDem0n** [comment]
One can build docker image based on postgres:12 and run it locally with docker-compose:
```bash
docker build --build-arg PG_MAJOR=12 -t patroni .
docker-compose up -d
```

It starts 3 node etcd cluster + 3 patroni nodes + haproxy.
No issues whatsoever.

**Comment by pySilver** [comment]
> I hope it is set to the same value on all nodes.
If you mean patroni.yml then its all almost-identical on every node. The only difference is `name`:

name: node-postgres-1
name: node-postgres-2
name: node-postgres-3

**Comment by pySilver** [comment]
One thing to note: Data directory on this failing nodes is empty, so database is not initialized. I guess it should be this way right?

**Comment by CyberDem0n** [comment]
It is empty because pg_basebackup fails.
pg_basebackup is executed as:
```
export PGPASSFILE= /var/lib/postgresql/.pgpass
pg_basebackup --pgdata=postgresql.data_dir -X stream --dbname="host=master.ip port=5432 user=replicator"
```

Since it fails, either password in the /var/lib/postgresql/.pgpass is wrong or there is something is wrong with libpq.

**Comment by pySilver** [comment]
@CyberDem0n I think I nailed it. WAL-G was introduced and configured with environment variables such as PGHOST PGPORT PGUSER and PGPASSWORD and looks like it overrides pg_basebackup source of connection settings.

**Comment by pySilver** [comment]
It is definitely it. To anyone find this - check your environment variables of you are facing similar issue.

@CyberDem0n thank you for your code and support!

**Comment by Tekchanddagar** [comment]
@pySilver, We are also facing similar issue and we also have wal-g setup at our end. Below are the error logs on my replica node and master is working fine.

```
Jan 16 10:46:36 apple-db-01 patroni[1737999]: pg_basebackup: error: FATAL:  password authentication failed for user "repuser"
Jan 16 10:46:36 apple-db-01 patroni[1737999]: password retrieved from file "/tmp/pgpass"
PermissionError: [Errno 13] Permission denied: '/mnt/volume_ams3_21/psql'
2021-01-16 10:46:41,081 INFO: renaming data directory to /mnt/volume_ams3_21/psql_2021-01-16-10-46-41
2021-01-16 10:46:41,081 ERROR: Could not rename data directory /mnt/volume_ams3_21/psql
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/patroni/postgresql/__init__.py", line 957, in remove_data_directory
    shutil.rmtree(self._data_dir)
  File "/usr/lib/python3.8/shutil.py", line 719, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python3.8/shutil.py", line 717, in rmtree
    os.rmdir(path)
PermissionError: [Errno 13] Permission denied: '/mnt/volume_ams3_21/psql'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/patroni/postgresql/__init__.py", line 930, in move_data_directory
    os.rename(self._data_dir, new_name)
PermissionError: [Errno 13] Permission denied: '/mnt/volume_ams3_21/psql' -> '/mnt/volume_ams3_21/psql_2021-01-16-10-46-41'

```

Earlier this node was master and working fine. But now master is changed and its showing this error.

Please help us.

Thank You
