### ISSUE TITLE
Issue with switchover via patronictl

### ISSUE THREAD

**Issue by lochanm2** [zalando/patroni#1496]
Hi,
We have installed patroni ( 3 nodes cluster ) and everything seems working fine but when I try to do a manual failover, it throws below error...

```
root@op-dflux-cip-stage-pgsql-ha-01:~# patronictl -d etcd://10.16.4.166:2379 failover patroniha
Candidate ['op_dflux_cip_stage_pgsql_ha_01', 'op_dflux_cip_stage_pgsql_ha_03'] []: op_dflux_cip_stage_pgsql_ha_03
Current cluster topology
+-----------+--------------------------------+------------------+--------+---------+----+-----------+
|  Cluster  |             Member             |       Host       |  Role  |  State  | TL | Lag in MB |
+-----------+--------------------------------+------------------+--------+---------+----+-----------+
| patroniha | op_dflux_cip_stage_pgsql_ha_01 | 10.16.4.166:5433 |        | running |  2 |         0 |
| patroniha | op_dflux_cip_stage_pgsql_ha_02 | 10.16.4.50:5433  | Leader | running |  2 |           |
| patroniha | op_dflux_cip_stage_pgsql_ha_03 | 10.16.4.142:5433 |        | running |  2 |         0 |
+-----------+--------------------------------+------------------+--------+---------+----+-----------+
Are you sure you want to failover cluster patroniha, demoting current master op_dflux_cip_stage_pgsql_ha_02? [y/N]: y
2020-04-15 13:02:09,008 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd6d03ace48>: Failed to establish a new connection: [Errno 111] Connection refused',)': /failover
2020-04-15 13:02:09,009 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd6d03acda0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /failover
2020-04-15 13:02:09,010 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd6d03acef0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /failover
2020-04-15 13:02:09,010 - ERROR - None
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/etcd.py", line 469, in create_connection_patched
    raise err
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/etcd.py", line 459, in create_connection_patched
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd6d03acc88>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/ctl.py", line 677, in _do_failover_or_switchover
    r = request_patroni(member, 'post', action, failover_value)
  File "/usr/local/lib/python3.6/dist-packages/patroni/ctl.py", line 133, in request_patroni
    return request_executor(member, method, endpoint, data)
  File "/usr/local/lib/python3.6/dist-packages/patroni/request.py", line 53, in __call__
    return self.request(method, url, data, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/request.py", line 46, in request
    return self._pool.request(method.upper(), url, body=body, **kwargs)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 70, in request
    **urlopen_kw)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 321, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8008): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd6d03acc88>: Failed to establish a new connection: [Errno 111] Connection refused',))
2020-04-15 13:02:09,014 - WARNING - Failing over to DCS
2020-04-15 13:02:09.01507 Could not failover using Patroni api, falling back to DCS
+-----------+--------------------------------+------------------+--------+---------+----+-----------+
|  Cluster  |             Member             |       Host       |  Role  |  State  | TL | Lag in MB |
+-----------+--------------------------------+------------------+--------+---------+----+-----------+
| patroniha | op_dflux_cip_stage_pgsql_ha_01 | 10.16.4.166:5433 |        | running |  2 |         0 |
| patroniha | op_dflux_cip_stage_pgsql_ha_02 | 10.16.4.50:5433  | Leader | running |  2 |           |
| patroniha | op_dflux_cip_stage_pgsql_ha_03 | 10.16.4.142:5433 |        | running |  2 |         0 |
+-----------+--------------------------------+------------------+--------+---------+----+-----------+
```
The patroni yml file is 

```
root@op-dflux-cip-stage-pgsql-ha-02:~# cat /etc/patroni/pg_patroni.yml
# "Note: This file is managed by DE Ansible in the 'patroni' role. Local changes will be overwritten."

scope: patroniha
#namespace: /service/
name:                  op_dflux_cip_stage_pgsql_ha_02
patroni_log_dir:       "/var/log/postgresql/"
patroni_log_file_size: 100MB

restapi:
  listen: 10.16.4.50:8008
  connect_address: 127.0.0.1:8008

etcd:
  host: 127.0.0.1:2379

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
#    master_start_timeout: 300
#    synchronous_mode: false
    #standby_cluster:
      #host: 127.0.0.1
      #port: 1111
      #primary_slot_name: patroni
    postgresql:
      use_pg_rewind: true
#     use_slots: true
      parameters:
        max_connections:          500
        shared_buffers:           1994MB
        effective_cache_size:     3988MB
        wal_level:                hot_standby
        hot_standby:              "on"
        wal_keep_segments:        8
        max_wal_senders:          10
        max_replication_slots:    10
        wal_log_hints:            "on"
        archive_mode:             "on"
        archive_timeout:          1800s
        archive_command:          /bin/cp %p /data/postgresql/archive/%f
        shared_preload_libraries: 'pg_stat_statements'
#      recovery_conf:
#        restore_command: cp ../wal_archive/%f %p

  # some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  # TYPE  DATABASE        USER            ADDRESS                 METHOD

  # "local" is for Unix domain socket connections only
  - local   all             all                                                         trust
  - host    all             all             127.0.0.1/32                                trust
  - host    all             all             ::1/128                                     trust
  - local   replication     all                                                         trust
  - host    replication     all             ::1/128                                     trust
  - host    all         replicator          0.0.0.0/0                                   md5
  - host    replication replicator          127.0.0.1/32                                md5
  - host    replication replicator          10.16.4.166/32         md5
  - host    replication replicator          10.16.4.50/32         md5
  - host    replication replicator          10.16.4.142/32         md5
  - host    all             all             0.0.0.0/0                                   md5

  # Additional script to be launched after initial cluster creation (will be passed the connection URL as parameter)
# post_init: /usr/local/bin/setup_cluster.sh

  # Some additional users users which needs to be created after initializing new cluster
  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb

postgresql:
  listen: 10.16.4.50,localhost, 127.0.0.1:5433
  connect_address: 10.16.4.50:5433
  data_dir: /data/postgresql/db
  bin_dir: /usr/lib/postgresql/12/bin
#  config_dir:
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: rep-pass
    superuser:
      username: postgres
      password: zalando
    rewind:  # Has no effect on postgres 10 and lower
      username: rewind_user
      password: rewind_password
  # Server side kerberos spn
#  krbsrvname: postgres
  parameters:
    # Fully qualified kerberos ticket file for the running user
    # same as KRB5CCNAME used by the GSS
#   krb_server_keyfile: /var/spool/keytabs/postgres
    unix_socket_directories: '/var/run/postgresql/'

#watchdog:
#  mode: automatic # Allowed values: off, automatic, required
#  device: /dev/watchdog
#  safety_margin: 5

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
root@op-dflux-cip-stage-pgsql-ha-02:~#
```

**Comment by CyberDem0n** [comment]
> restapi:
  listen: 10.16.4.50:8008
  **connect_address: 127.0.0.1:8008**

Why there is a localhost in the connect_address?
Have you read the [documentation](https://patroni.readthedocs.io/en/latest/SETTINGS.html#rest-api)?

**Comment by lochanm2** [comment]
Hi @CyberDem0n , please consider my ignorance, so if I understand correctly, this connect_address should contain all ips of the cluster with the port?

**Comment by lochanm2** [comment]
I am able to add connect_address to ip and issue is fixed now. Thanks.

**Comment by Liuzhj** [comment]
hi @lochanm2 
can you share you ansible playbook for me ? i want to be study and reference, thank you very much .
