### ISSUE TITLE
One node of cluster entered single user mode and failed to restart

### ISSUE THREAD

**Issue by lily2110** [zalando/patroni#1506]
OS: Ubuntu 18.04
Patroni: 1.4.2

There are 3 members in my cluster called A, B and C here. A was primary at first. After A was stopped, C became primary. And then A was restart. But A restart failed. From log, seems A entered "crashing recovery in single user mode". This is the log.
```
Apr 2 23:51:16   INFO Failed to import patroni.dcs.consul
Apr 2 23:51:16   INFO Selected new etcd server https://172.18.131.3:2379
Apr 2 23:51:16   INFO Lock owner: fa5ff081-2b01-4200-acbb-8c4e4fc62280_g3vjqGGH; I am fa5ff081-2b01-4200-acbb-8c4e4fc62280_UCDA3Ebu
Apr 2 23:51:16   WARNING Postgresql is not running.
Apr 2 23:51:16   INFO doing crash recovery in a single user mode
Apr 2 23:51:16   UTC [121-1] LOG:  database system was interrupted; last known up at 2020-02-24 11:48:06 UTC
Apr 2 23:51:17   UTC [121-2] LOG:  database system was not properly shut down; automatic recovery in progress
Apr 2 23:51:17   UTC [121-3] LOG:  redo starts at 43/62003530
Apr 2 23:51:17   UTC [121-4] LOG:  invalid record length at 43/62003610: wanted 24, got 0
Apr 2 23:51:17   UTC [121-5] LOG:  redo done at 43/620035D8
Apr 2 23:51:17   PostgreSQL stand-alone backend 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1)
Apr 2 23:51:26   INFO backend> 2020-04-02 23:51:26,189 patroni INFO: Lock owner: fa5ff081-2b01-4200-acbb-8c4e4fc62280_g3vjqGGH; I am fa5ff081-2b01-4200-acbb-8c4e4fc62280_UCDA3Ebu
Apr 2 23:51:26   INFO Demoting master during doing crash recovery in a single user mode
Apr 2 23:51:26   WARNING Cannot stop server; single-user server is running (PID: 121)
Apr 2 23:51:26   WARNING pg_ctl stop failed
Apr 2 23:51:26   INFO lost leader lock during doing crash recovery in a single user mode
Apr 2 23:51:26   ERROR Exception during CHECKPOINT
Apr 2 23:51:26   Traceback (most recent call last):
Apr 2 23:51:26       with self._get_connection_cursor(**connect_kwargs) as cur:
Apr 2 23:51:26     File "/usr/lib/python3/dist-packages/patroni/postgresql.py", line 895, in checkpoint
Apr 2 23:51:26       return next(self.gen)
Apr 2 23:51:26     File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 130, in connect
Apr 2 23:51:26     File "/usr/lib/python3/dist-packages/patroni/postgresql.py", line 1184, in _get_connection_cursor
Apr 2 23:51:26   	Is the server running on host "localhost" (::1) and accepting
Apr 2 23:51:26       with psycopg2.connect(**kwargs) as conn:
Apr 2 23:51:26       conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Apr 2 23:51:26   	TCP/IP connections on port 5432?
Apr 2 23:51:26   could not connect to server: Cannot assign requested address
Apr 2 23:51:26   	TCP/IP connections on port 5432?
Apr 2 23:51:26   INFO does not have lock
Apr 2 23:51:26   WARNING Cannot stop server; single-user server is running (PID: 121)
Apr 2 23:51:26   INFO Lock owner: fa5ff081-2b01-4200-acbb-8c4e4fc62280_g3vjqGGH; I am fa5ff081-2b01-4200-acbb-8c4e4fc62280_UCDA3Ebu
Apr 2 23:51:26   WARNING pg_ctl stop failed
Apr 2 23:51:26  
Apr 2 23:51:26   INFO establishing a new patroni connection to the postgres cluster
Apr 2 23:51:26   	Is the server running on host "localhost" (127.0.0.1) and accepting
Apr 2 23:51:26     File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
Apr 2 23:51:26   psycopg2.OperationalError: could not connect to server: Connection refused
Apr 2 23:51:27   INFO establishing a new patroni connection to the postgres cluster
Apr 2 23:51:27   could not connect to server: Cannot assign requested address
Apr 2 23:51:27       'no action.  i am a secondary and i am following a leader', refresh=False)
Apr 2 23:51:27   localhost:5432 - no response
Apr 2 23:51:27       self._connection = psycopg2.connect(**self._local_connect_kwargs)
Apr 2 23:51:27       self._cursor_holder = self.connection().cursor()
Apr 2 23:51:27   	TCP/IP connections on port 5432?
Apr 2 23:51:27     File "/usr/lib/python3/dist-packages/patroni/ha.py", line 262, in follow
Apr 2 23:51:27       cursor = self._cursor()
Apr 2 23:51:27   	Is the server running on host "localhost" (127.0.0.1) and accepting
Apr 2 23:51:27     File "/usr/lib/python3/dist-packages/patroni/postgresql.py", line 726, in _cluster_info_state_get
Apr 2 23:51:27   	TCP/IP connections on port 5432?
Apr 2 23:51:27   INFO Error communicating with PostgreSQL. Will try again later
Apr 2 23:51:27     File "/usr/lib/python3/dist-packages/patroni/postgresql.py", line 461, in _cursor
Apr 2 23:51:27   psycopg2.OperationalError: could not connect to server: Connection refused
Apr 2 23:51:27   patroni.exceptions.PostgresConnectionException: "'Too many retry attempts'"
Apr 2 23:51:27     File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 130, in connect
Apr 2 23:51:27       conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Apr 2 23:51:27       raise PostgresConnectionException(self._cluster_info_state['error'])
Apr 2 23:51:27     File "/usr/lib/python3/dist-packages/patroni/postgresql.py", line 453, in connection
Apr 2 23:51:27   	Is the server running on host "localhost" (::1) and accepting
Apr 2 23:51:27  
Apr 2 23:51:27   Traceback (most recent call last):
Apr 2 23:51:27   During handling of the above exception, another exception occurred:
Apr 2 23:51:27       self.load_replication_slots()
Apr 2 23:51:27       raise PostgresConnectionException('connection problems')
Apr 2 23:51:27   ERROR Exception when changing replication slots 
Apr 2 23:51:27       msg = self.process_healthy_cluster()
Apr 2 23:51:27  
Apr 2 23:51:27       cursor = self._query("SELECT slot_name FROM pg_replication_slots WHERE slot_type='physical'")
Apr 2 23:51:27     File "/usr/lib/python3/dist-packages/patroni/postgresql.py", line 1464, in load_replication_slots
Apr 2 23:51:27   patroni.exceptions.PostgresConnectionException: 'connection problems'
Apr 2 23:51:27     File "/usr/lib/python3/dist-packages/patroni/ha.py", line 770, in process_healthy_cluster
Apr 2 23:51:27   Traceback (most recent call last):
Apr 2 23:51:27     File "/usr/lib/python3/dist-packages/patroni/postgresql.py", line 1478, in sync_replication_slots
Apr 2 23:51:27     File "/usr/lib/python3/dist-packages/patroni/postgresql.py", line 491, in _query
Apr 2 23:51:27       is_leader = self.state_handler.is_leader()
Apr 2 23:51:27     File "/usr/lib/python3/dist-packages/patroni/postgresql.py", line 731, in is_leader
Apr 2 23:51:27  
Apr 2 23:51:27       return bool(self._cluster_info_state_get('timeline'))
Apr 2 23:51:27  
Apr 2 23:51:27     File "/usr/lib/python3/dist-packages/patroni/postgresql.py", line 476, in _query
Apr 2 23:51:27   During handling of the above exception, another exception occurred:
Apr 2 23:51:27   Traceback (most recent call last):
Apr 2 23:51:27     File "/usr/lib/python3/dist-packages/patroni/ha.py", line 1107, in _run_cycle
Apr 2 23:51:27   INFO establishing a new patroni connection to the postgres cluster
Apr 2 23:51:28   INFO Lock owner: fa5ff081-2b01-4200-acbb-8c4e4fc62280_g3vjqGGH; I am fa5ff081-2b01-4200-acbb-8c4e4fc62280_UCDA3Ebu
Apr 2 23:51:28   INFO establishing a new patroni connection to the postgres cluster
Apr 2 23:51:28   INFO does not have lock
Apr 2 23:51:29   INFO establishing a new patroni connection to the postgres cluster
Apr 2 23:51:29     File "/usr/lib/python3/dist-packages/patroni/ha.py", line 770, in process_healthy_cluster
Apr 2 23:51:29     File "/usr/lib/python3/dist-packages/patroni/ha.py", line 1107, in _run_cycle
Apr 2 23:51:29       msg = self.process_healthy_cluster()
Apr 2 23:51:29       'no action.  i am a secondary and i am following a leader', refresh=False)
Apr 2 23:51:29   localhost:5432 - no response 
```
I want to make clear the root cause of this problem. 
After entering single user mode, what is the next logic of patroni to process this member? When will patroni let postgresql exit single user mode and start postgresql again?
How can I make this member back to normal?
Appreciate to your help!

**Comment by CyberDem0n** [comment]
Patroni: 1.4.2 was released more than two years ago.
Since then there were a lot of bugs fixed.
I can't reproduce this issue on the latest version.
