### ISSUE TITLE
IPv6 listen address not handled properly

### ISSUE THREAD

**Issue by mkowalski** [zalando/patroni#1532]
The following stack trace appears, when trying to use IPv6-only environment, i.e. configuring `listen: '[2a0f:a580:0:420::2]:5432'`

```
patroni              | Traceback (most recent call last):                      
patroni              |   File "patroni.py", line 6, in <module>                                                             
patroni              |     main()                                                     
patroni              |   File "/patroni/__init__.py", line 224, in main                           
patroni              |     return patroni_main()                            
patroni              |   File "/patroni/__init__.py", line 186, in patroni_main
patroni              |     patroni = Patroni(conf)    
patroni              |   File "/patroni/__init__.py", line 36, in __init__
patroni              |     self.api = RestApiServer(self, self.config['restapi'])
patroni              |   File "/patroni/api.py", line 492, in __init__
patroni              |     self.reload_config(config)                                      
patroni              |   File "/patroni/api.py", line 612, in reload_config
patroni              |     self.__initialize(config['listen'], ssl_options)
patroni              |   File "/patroni/api.py", line 580, in __initialize
patroni              |     self.__httpserver_init(host, port)
patroni              |   File "/patroni/api.py", line 554, in __httpserver_init
patroni              |     info = socket.getaddrinfo(host, port, socket.AF_UNSPEC, socket.SOCK_STREAM, 0, socket.AI_PASSIVE)
patroni              |   File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
patroni              |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
patroni              | socket.gaierror: [Errno -2] Name or service not known
```

After quick debugging it seems that the function initializing the server has a flaw... In https://github.com/zalando/patroni/blob/master/patroni/api.py#L580 we are passing a result of `split_host_port(listen, None)` however

```
>>> split_host_port('[2a0f:a580:0:420::2]:5432',5432)
('[2a0f:a580:0:420::2]', 5432)
```
(note the brackets)

If we try to call
```
socket.getaddrinfo(host, port, socket.AF_UNSPEC, socket.SOCK_STREAM, 0, socket.AI_PASSIVE)
```
with `host` containing the brackets, the call will fail.

A solution could be to add an additional logic to the `split_host_port` function so that returned tuple always contains host in correct format, i.e. with no brackets. Given this could have a potential impact on other parts of the codebase, at the moment I'm not 100% sure how safe that is.

**Comment by CyberDem0n** [comment]
I the configuration you can specify it without square brackets and it will work.

**Comment by mkowalski** [comment]
Sorry but no, `2a0f:a580:0:420::2:5432` is not a legal syntax for IPv6 with port.

**Comment by CyberDem0n** [comment]
It might be not a legal syntax, but it will make it work without code changes.

P.S.I don't have any objections on your suggested improvements.
