### ISSUE TITLE
If patronictl edit-config -p support pgkvpairs, what's the input format.

### ISSUE THREAD

**Issue by luyisa** [zalando/patroni#1566]
Hi, I want to use edit-config -p to modify multiple parameters in one time, I checked resource code, seems pgkvpairs support multiple parameters in one time, but I have tried, it won't work. 

`patronictl edit-config -p 'max_connections=300', 'max_locks_per_transaction=64'

throws 

> 2020-05-31 01:30:49,321 patroni ERROR: Exception when setting dynamic_configuration
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/config.py", line 139, in set_dynamic_configuration
    self._local_configuration)
  File "/usr/lib/python3/dist-packages/patroni/config.py", line 279, in _build_effective_configuration
    config = self._safe_copy_dynamic_configuration(dynamic_configuration)
  File "/usr/lib/python3/dist-packages/patroni/config.py", line 184, in _safe_copy_dynamic_configuration
    config[name] = int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'

**Comment by luyisa** [comment]
Fix the way, I am wrong, I should use -p to point more times. Close this one.
