### ISSUE TITLE
Failover doesn't occur when consul is down on the leader node

### ISSUE THREAD

**Issue by krazy350** [zalando/patroni#1581]
Hi all,
i am kind of following [https://github.com/zalando/patroni/issues/1054](url).

I have 4 patroni nodes, with psql asynchronous replication.

```
root@patroni-test-d(stable):~# patronictl list 11-patroni
+ Cluster: 11-patroni (6836218402094631224) +---------+----+-----------+
|     Member     |       Host      |  Role  |  State  | TL | Lag in MB |
+----------------+-----------------+--------+---------+----+-----------+
| patroni-test-a | 10.7.54.91:5434 |        | running |  1 |         0 |
| patroni-test-b | 10.7.54.78:5434 |        | running |  1 |         0 |
| patroni-test-c | 10.7.54.87:5434 |        | running |  1 |         0 |
| patroni-test-d | 10.7.54.88:5434 | Leader | running |  1 |           |
+----------------+-----------------+--------+---------+----+-----------+
```
I stop the consul on leader node (patroni-node-d)
```
root@patroni-test-d(stable):~# systemctl stop consul
```

In leader log i see that dcs is not accessible, so far good

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/dcs/consul.py", line 308, in _load_cluster
    _, results = self.retry(self._client.kv.get, path, recurse=True)
  File "/usr/lib/python3/dist-packages/patroni/dcs/consul.py", line 231, in retry
    return self._retry.copy()(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/patroni/utils.py", line 341, in __call__
    raise RetryFailedError("Exceeded retry deadline")
patroni.utils.RetryFailedError: 'Exceeded retry deadline'
2020-06-09 06:20:23,713 ERROR: Error communicating with DCS
2020-06-09 06:20:23,714 INFO: DCS is not accessible
```

On standby node i see

```
root@patroni-test-c(stable):~# patronictl list 11-patroni
+ Cluster: 11-patroni (6836218402094631224) --------+----+-----------+
|     Member     |       Host      | Role |  State  | TL | Lag in MB |
+----------------+-----------------+------+---------+----+-----------+
| patroni-test-a | 10.7.54.91:5434 |      | running |  1 |         0 |
| patroni-test-b | 10.7.54.78:5434 |      | running |  1 |         0 |
| patroni-test-c | 10.7.54.87:5434 |      | running |  1 |         0 |
+----------------+-----------------+------+---------+----+-----------+
```
and in logs

```
2020-06-09 06:21:49,766 INFO: Wal position of patroni-test-d is ahead of my wal position
2020-06-09 06:21:49,787 INFO: following a different leader because i am not the healthiest node
2020-06-09 06:21:59,682 INFO: Got response from patroni-test-b http://10.7.54.78:8012/patroni: {"state": "running", "postmaster_start_time": "2020-06-09 08:18:03.405 CEST", "role": "replica", "server_version": 110008, "cluster_unlocked": true, "xlog": {"received_location": 369377232, "replayed_location": 369377232, "replayed_timestamp": "2020-06-09 08:18:02.414 CEST", "paused": false}, "timeline": 1, "database_system_identifier": "6836218402094631224", "patroni": {"version": "1.6.5", "scope": "11-patroni"}}
2020-06-09 06:21:59,684 INFO: Got response from patroni-test-d http://10.7.54.88:8012/patroni: {"state": "running", "postmaster_start_time": "2020-06-09 08:18:14.000 CEST", "role": "replica", "server_version": 110008, "cluster_unlocked": true, "xlog": {"received_location": 374109392, "replayed_location": 374109392, "replayed_timestamp": null, "paused": false}, "timeline": 1, "database_system_identifier": "6836218402094631224", "patroni": {"version": "1.6.5", "scope": "11-patroni"}}
2020-06-09 06:21:59,689 INFO: Got response from patroni-test-a http://10.7.54.91:8012/patroni: {"state": "running", "postmaster_start_time": "2020-06-09 08:18:03.351 CEST", "role": "replica", "server_version": 110008, "cluster_unlocked": true, "xlog": {"received_location": 369377232, "replayed_location": 369377232, "replayed_timestamp": "2020-06-09 08:18:02.414 CEST", "paused": false}, "timeline": 1, "database_system_identifier": "6836218402094631224", "patroni": {"version": "1.6.5", "scope": "11-patroni"}}
2020-06-09 06:21:59,766 INFO: Wal position of patroni-test-d is ahead of my wal position
2020-06-09 06:21:59,790 INFO: following a different leader because i am not the healthiest node
```

And no failover occurs. In mentioned issue  "CyberDem0n commented on May 13, 2019" that it needs some refactoring in async mode. Is this still true?  Is there any change how to solve this failover problem.

Thank yoy very much

Zdenek

**Comment by krazy350** [comment]
```
ii  patroni                              1.6.5-2.pgdg100+1            all          PostgreSQL High Availability with ZooKeeper, etcd, Consul, or Kubernetes
```

**Comment by CyberDem0n** [comment]
`patroni-test-d` is the ahead of any other node, doing a failover in such a situation would mean that we will lose some transactions.

**Comment by krazy350** [comment]
Yes, because it was leader. When consul was stopped, patroni-test-d went read only.

**Comment by CyberDem0n** [comment]
We don't want to lose transactions, do we?

**Comment by krazy350** [comment]
So you want to say, that in case consul is down on leader node, psql went to read-only. Cluster has now no leader and manual intervention is needed to promote some replicas to master?

**Comment by CyberDem0n** [comment]
Nodes `a`, `b`, and `c` know for sure that the former primary `d` is ahead of them. If one of them promote that could result in data loss. Therefore they don't.

**Comment by krazy350** [comment]
From my point of view when you compare outage when there is no leader and manual intervention is needed and loss of some transactions, the second approach wins. Maybe there could be some configuration parameters to allow this kind of scenario. What do you think?

**Comment by CyberDem0n** [comment]
I am against implementing a foot gun.
You just shoot yourself by stopping the consul agent and the typical recommendation to solve this problem is employing auto-restart for consul agent rather than fixing it on the wrong side.

**Comment by krazy350** [comment]
Ok, thank you.
