### ISSUE TITLE
Patronictl unknown CA error 

### ISSUE THREAD

**Issue by jooof** [zalando/patroni#1597]
Hi all.
I'm trying to set certification for rest api but the patronictl switchover (and all the other PUT requests) is not working and is giving me the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/patroni/ctl.py", line 703, in _do_failover_or_switchover
    r = request_patroni(member, 'post', action, failover_value)
  File "/usr/local/lib/python3.5/dist-packages/patroni/ctl.py", line 165, in request_patroni
    return request_executor(member, method, endpoint, data)
  File "/usr/local/lib/python3.5/dist-packages/patroni/request.py", line 53, in __call__
    return self.request(method, url, data, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/patroni/request.py", line 46, in request
    return self._pool.request(method.upper(), url, body=body, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/request.py", line 80, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/usr/local/lib/python3.5/dist-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/poolmanager.py", line 336, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 765, in urlopen
    **response_kw
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 765, in urlopen
    **response_kw
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 765, in urlopen
    **response_kw
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='194.5.195.218', port=8008): Max retries exceeded with url: /switchover (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:645)'),))
2020-06-21 18:12:54,928 - WARNING - Failing over to DCS
2020-06-21 18:12:54.92859 Could not switchover using Patroni api, falling back to DCS
```

Patroni itself works just fine. here's the yaml file:

```
scope: postgres
namespace: /patroni1/
name: consul-2

restapi:
  listen: 0.0.0.0:8008
  connect_address: 194.5.195.218:8008
  authentication:
      username: patroni_rest_api_user
      password: ****
  certfile: /etc/patroni/ssl/server-cert.pem
  keyfile: /etc/patroni/ssl/server-key.pem
  cafile: /etc/patroni/ssl/CA-cert.pem
  verify_client: optional 

ctl:
        insecure: true
        cacert: /etc/patroni/ssl/CA-cert.pem

consul:
        host: localhost:8500
        token: "****"

bootstrap:
    dcs:
        ttl: 100
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true
            use_slots: true
            parameters:
                    wal_level: replica
                    hot_standby: "on"
                    wal_keep_segments: 8
                    max_wal_senders: 5
                    max_replication_slots: 5
                    checkpoint_timeout: 30
    initdb:
        - encoding: UTF8
        - data-checksums
    pg_hba:
        - local all all  127.0.0.1/32 trust
        - host all all 0.0.0.0/0 reject
        - host replication replicator 194.5.175.150/32 md5
        - host replication replicator 194.5.195.218/32 md5
        - host replication replicator 194.5.205.150/32 md5
    users:
        patroni:
            password: ****
            options:
                - superuser
                - createrole
                - createdb
        replicator:
            password: ****
            options:
                - replication

postgresql:
    listen: 0.0.0.0
    connect_address: 194.5.195.218
    data_dir: /var/lib/postgresql/12/main
    config_dir: /var/lib/postgresql/12/main
    bin_dir: /usr/lib/postgresql/12/bin
    pgpass: /tmp/pgpass
    authentication:
        superuser:
            username: patroni
            password: ****
        replication:
            username: replicator
            password: ****
        rewind:
            username: rewind_user
            password: ****
    parameters:
        unix_socket_directories: '/tmp'
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
log:
   dir: /var/log/postgresql
   level: DEBUG
```

shouldn't ctl just take all the variables it needs from the restapi?

**Comment by CyberDem0n** [comment]
You specified `restapi.verify_client: optional` and at the same time `ctl.insecure: true`. Not sure how urllib3 handles it.

If there is no corresponding value in the ctl section it takes it from restapi.

There is also no value in setting ttl to 100 it if retry_timeout is 10.

**Comment by jooof** [comment]
at first it was set to required and there was no ctl section and it still had the same error. I changed like this so it might work and it didn't.

**Comment by CyberDem0n** [comment]
If certificates and keys are correctly set up, everything should work.
I can only recommend to debug the issue with curl.

**Comment by jooof** [comment]
It works perfectly when using curl. Also on the patroni itself. That's the problem

**Comment by CyberDem0n** [comment]
Have you tried doing requests _different_ from GET?
For example `POST /restart`.

**Comment by jooof** [comment]
No I haven't. I'll try it to see what happens. Thanks

**Comment by jooof** [comment]
I checked it out and the problem was from the Certificate itself. Thank you so much
