### ISSUE TITLE
postgresql.config miss

### ISSUE THREAD

**Issue by StephenLiuYa** [zalando/patroni#1607]
I run the complete demo but got error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/async_executor.py", line 97, in run
    wakeup = func(*args) if args else func()
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 645, in restart
    ret = self.stop(block_callbacks=True) and self.start(timeout, task, True, role)
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 423, in start
    self.config.write_postgresql_conf(configuration)
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/config.py", line 416, in write_postgresql_conf
    os.rename(self._postgresql_conf, self._postgresql_base_conf)
FileNotFoundError: [Errno 2] No such file or directory: '/home/postgres/pgdata/pgroot/data/postgresql.conf' -> '/home/postgres/pgdata/pgroot/data/postgresql.base.conf'
/var/run/postgresql:5432 - no response
```

How can I got the config file

**Comment by jawabuu** [comment]
@StephenLiuYa How did you resolve this?

**Comment by yxxhero** [comment]
any updates?
