### ISSUE TITLE
Cannot start patroni

### ISSUE THREAD

**Issue by shaikmuzakkir** [zalando/patroni#1672]
patroni config file:
`scope: postgres
namespace: /db/
name: node1

restapi:
    listen: 10.74.24.125:8008
    connect_address: 10.74.24.125:8008

etcd:
    host: 10.74.24.124:2379

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 10.74.24.15/0 md5
    - host replication replicator 10.74.24.13/0 md5
    - host replication replicator 10.74.24.22/0 md5
    - host all all 0.0.0.0/0 md5

    users:
        admin:
            password: admin
            options:
                - createrole
                - createdb

postgresql:
    listen: 10.74.24.125:5432
    connect_address: 10.74.24.125:5432
    data_dir: /data/patroni
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: rep-pass
        superuser:
            username: postgres
            password: secretpassword
    parameters:
        unix_socket_directories: '.'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false`

Error:

`2020-08-30 06:03:15,726 INFO: Failed to import patroni.dcs.etcd
2020-08-30 06:03:15,743 INFO: Failed to import patroni.dcs.kubernetes
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/patroni/__init__.py", line 235, in main
    return patroni_main()
  File "/usr/local/lib/python2.7/dist-packages/patroni/__init__.py", line 197, in patroni_main
    patroni = Patroni(conf)
  File "/usr/local/lib/python2.7/dist-packages/patroni/__init__.py", line 32, in __init__
    self.dcs = get_dcs(self.config)
  File "/usr/local/lib/python2.7/dist-packages/patroni/dcs/__init__.py", line 106, in get_dcs
    Available implementations: """ + ', '.join(sorted(set(available_implementations))))
patroni.exceptions.PatroniException: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: consul, exhibitor, zookeeper'`

pip freeze:
`boto==2.49.0
cdiff==1.0
certifi==2020.6.20
cffi==1.14.2
chardet==3.0.4
click==7.1.2
contextlib2==0.6.0.post1
cryptography==3.1
dnspython==2.0.0
enum34==1.1.10
flake8==3.8.3
functools32==3.2.3.post2
idna==2.10
importlib-metadata==1.7.0
ipaddress==1.0.23
kazoo==2.8.0
mccabe==0.6.1
pathlib2==2.3.5
patroni==1.6.5
prettytable==0.7.2
psutil==5.7.2
psycopg2==2.6.1
pycodestyle==2.6.0
pycparser==2.20
pycrypto==2.6.1
pyflakes==2.2.0
pyOpenSSL==19.1.0
pysyncobj==0.3.5
python-apt==1.1.0b1+ubuntu0.16.4.9
python-consul==1.1.0
python-dateutil==2.8.1
python-etcd==0.4.5
pytz==2013.8
PyYAML==5.3.1
requests==2.1.0
scandir==1.10.0
six==1.15.0
typing==3.7.4.3
tzlocal==2.1
UNKNOWN==0.0.0
urllib3==1.25.10`

patroni.service file:
`[Unit]
Description=High availability PostgreSQL Cluster
After=syslog.target network.target

[Service]
Type=simple
User=postgres
Group=postgres
ExecStart=/usr/local/bin/patroni /etc/patroni/patroni.yml
KillMode=process
TimeoutSec=30
Restart=no

[Install]
WantedBy=multi-user.targ`

OS: Ubuntu 16.04
Postgresql Version: 9.5

Could you please let me know what might be the issue?

**Comment by shaikmuzakkir** [comment]
I get this error when I try to import etcd and hence may be the error:

```
root@hazr024dc539b1:~/etcd# pip freeze | grep etcd
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
python-etcd==0.4.5
root@hazr024dc539b1:~/etcd# python
Python 2.7.12 (default, Jul 21 2020, 15:19:50)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import etcd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/etcd/__init__.py", line 2, in <module>
    from .client import Client
  File "/usr/local/lib/python2.7/dist-packages/etcd/client.py", line 22, in <module>
    import dns.resolver
  File "/usr/local/lib/python2.7/dist-packages/dns/resolver.py", line 19, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse
>>>
```

**Comment by shaikmuzakkir** [comment]
Installed a virtualenvironment and install python-etcd there and the `import etcd` works in python terminal. But when I start the patroni serice it still complains:
```
2020-08-30 06:57:57,316 INFO: Failed to import patroni.dcs.etcd
2020-08-30 06:57:57,431 INFO: Failed to import patroni.dcs.kubernetes
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/patroni/__init__.py", line 235, in main
    return patroni_main()
  File "/usr/local/lib/python2.7/dist-packages/patroni/__init__.py", line 197, in patroni_main
    patroni = Patroni(conf)
  File "/usr/local/lib/python2.7/dist-packages/patroni/__init__.py", line 32, in __init__
    self.dcs = get_dcs(self.config)
  File "/usr/local/lib/python2.7/dist-packages/patroni/dcs/__init__.py", line 106, in get_dcs
    Available implementations: """ + ', '.join(sorted(set(available_implementations))))
patroni.exceptions.PatroniException: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: consul, exhibitor, zookeeper'
```

**Comment by CyberDem0n** [comment]
> Installed a virtualenvironment and install python-etcd there and the import etcd works in python terminal. But when I start the patroni serice it still complains:

Because the service is not using virtualenv.

Also, please keep in mind that python 2.7 is EOL since 2020-01-01.

**Comment by shaikmuzakkir** [comment]
I tried to clear all packages and re-installed patroni and etcd which is now starting the patroni service via systemctl outside the virtualenv. But patronictl still shows the error:
```
$ patronictl list postgres
Error: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: etcd'
```

**Comment by CyberDem0n** [comment]
patronictl -c /etc/patroni/patroni.yml list

**Comment by shaikmuzakkir** [comment]
Thanks that worked. I see that when I manually stop the postgresql service, patronictl still say the state to be running. Does it only display the state of patroni(which is running) and not postgresql whose state is important to be monitored? Is there a patronictl way to check the state of postgresql service rather than patroni?

```
root@node1# systemctl status postgresql
* postgresql.service - PostgreSQL RDBMS
   Loaded: loaded (/lib/systemd/system/postgresql.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Sun 2020-08-30 11:04:31 UTC; 1 day 1h ago
  Process: 12164 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
 Main PID: 12164 (code=exited, status=0/SUCCESS)

Aug 30 08:27:49 node1 systemd[1]: Starting PostgreSQL RDBMS...
Aug 30 08:27:49 node1 systemd[1]: Started PostgreSQL RDBMS.
Aug 30 11:04:31 node1 systemd[1]: Stopped PostgreSQL RDBMS.
Aug 31 13:04:01 node1 systemd[1]: Stopped PostgreSQL RDBMS.
root@node1:/home# patronictl -c /etc/patroni.yml list
+ Cluster: postgres (6866691596792643549) --+----+-----------+
| Member |      Host     |  Role  |  State  | TL | Lag in MB |
+--------+---------------+--------+---------+----+-----------+
| node1  | 10.74.24.25 |        | running |  2 |      47.0 |
| node2  | 10.74.24.23 |        | running |  3 |       0.0 |
| node3  | 10.74.24.22 | Leader | running |  3 |           |
+--------+---------------+--------+---------+----+-----------+

```

**Comment by CyberDem0n** [comment]
> when I manually stop the postgresql service, patronictl still say the state to be running.

I am not sure what you are doing, but something is fishy.
With Patroni you should not have any postgresql services! It is a task of Patroni to start/stop postgres!

Also, patronictl shows information that is not up-to-date, and delayed up to loop_wait seconds.

**Comment by shaikmuzakkir** [comment]
> > when I manually stop the postgresql service, patronictl still say the state to be running.
> 
> I am not sure what you are doing, but something is fishy.
> With Patroni you should not have any postgresql services! It is a task of Patroni to start/stop postgres!
> 
> Also, patronictl shows information that is not up-to-date, and delayed up to loop_wait seconds.

I had setup cluster based on this guide - https://www.techsupportpk.com/2020/02/how-to-set-up-highly-available-postgresql-cluster-ubuntu-19-20.html.  I agree it is the task of patroni to start or stop postgres. When I start patroni it starts the postgresql service by itself and ptroni is stopped, the postgresql service is stopped. But what if postgresql service is stopped manually or if the postgresql service crashes for some reason? The state of patroni still shows "running" in the patronictl list output posted previously. Is that expected? I agree Patroni is running but when postgresql is not running is there a way to find out by any patronictl commands? Or setup patroni to automatically start postgres when postgres stop for some reason?

**Comment by CyberDem0n** [comment]
> When I start patroni it starts the postgresql service by itself and ptroni is stopped, the postgresql service is stopped.

Patroni never ever interacts with services in your OS! It starts/stops/promotes postgres directly.

> But what if postgresql service is stopped manually or if the postgresql service crashes for some reason?

Again. You should not use postgres service. If postgres crashed Patroni will notice that try to start it up.

>The state of patroni still shows "running" in the patronictl list output posted previously. 

Maybe because the postgres is really running? Have you double-checked the process list?
