### ISSUE TITLE
Patroni outage for mysterious reason

### ISSUE THREAD

**Issue by caseyallenshobe** [zalando/patroni#1675]
When this happened, all the replica nodes in the cluster went from "running" into "starting" status for a while, although the leader did not change.  We are not clear on what could cause this from the logs, pasted below.  Disk I/O was showing 100% utilization when I looked at the server right after this which is presumably a factor, but things appeared to be responsive.  I would appreciate any insights or advice!

```
2020-09-01 00:35:19,973 INFO: no action.  i am the leader with the lock
2020-09-01 00:35:22,963 INFO: Lock owner: p-dc10-dbpgdvr1-1; I am p-dc10-dbpgdvr1-1
2020-09-01 00:35:55,735 ERROR: get_postgresql_status
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/api.py", line 443, in get_postgresql_status
    self.server.patroni.postgresql.lsn_name), retry=retry)[0]
  File "/usr/lib/python3/dist-packages/patroni/api.py", line 416, in query
    return self.server.query(sql, *params)
  File "/usr/lib/python3/dist-packages/patroni/api.py", line 503, in query
    raise e
  File "/usr/lib/python3/dist-packages/patroni/api.py", line 499, in query
    cursor.execute(sql, params)
psycopg2.errors.QueryCanceled: canceling statement due to statement timeout

2020-09-01 00:35:55,771 ERROR: failed to update leader lock
2020-09-01 00:36:07,483 INFO: Deregister service postgresql-dvr1-12-main/p-dc10-dbpgdvr1-1
2020-09-01 00:36:07,500 INFO: demoted self because failed to update leader lock in DCS
2020-09-01 00:36:07,510 WARNING: Loop time exceeded, rescheduling immediately.
2020-09-01 00:36:07,528 INFO: Lock owner: None; I am p-dc10-dbpgdvr1-1
2020-09-01 00:36:07,528 INFO: not healthy enough for leader race
2020-09-01 00:36:07,528 INFO: starting after demotion in progress
2020-09-01 00:36:07,529 INFO: closed patroni connection to the postgresql cluster
2020-09-01 00:36:08,144 INFO: postmaster pid=549
2020-09-01 00:36:10,507 INFO: Lock owner: None; I am p-dc10-dbpgdvr1-1
2020-09-01 00:36:10,507 INFO: not healthy enough for leader race
```
...
```
2020-09-01 00:37:08,223 INFO: Lock owner: None; I am p-dc10-dbpgdvr1-1
2020-09-01 00:37:08,223 INFO: Still starting up as a standby.
2020-09-01 00:37:08,229 INFO: establishing a new patroni connection to the postgres cluster
2020-09-01 00:37:09,026 INFO: establishing a new patroni connection to the postgres cluster
2020-09-01 00:37:09,029 WARNING: Retry got exception: 'connection problems'
2020-09-01 00:37:09,032 INFO: Error communicating with PostgreSQL. Will try again later
```
...
```
2020-09-01 00:37:32,247 INFO: establishing a new patroni connection to the postgres cluster
2020-09-01 00:37:33,573 INFO: Got response from p-dc10-dbpgdvr1-3 http://10.127.38.114:8008/patroni: {"state": "starting", "role": "replica", "database_system_identifier": "6781543497195005939", "patroni": {"version": "1.6.5", "scope": "postgresql-dvr1-12-main"}}
2020-09-01 00:37:33,575 WARNING: Request failed to p-dc10-dbpgdvr1-3: GET http://10.127.38.114:8008/patroni ('xlog')
2020-09-01 00:37:33,855 INFO: Got response from p-dc10-dbpgdvr1-5 http://10.127.38.84:8008/patroni: {"state": "starting", "role": "replica", "database_system_identifier": "6781543497195005939", "patroni": {"version": "1.6.5", "scope": "postgresql-dvr1-12-main"}}
2020-09-01 00:37:33,856 WARNING: Request failed to p-dc10-dbpgdvr1-5: GET http://10.127.38.84:8008/patroni ('xlog')
2020-09-01 00:37:34,024 INFO: Got response from p-dc10-dbpgdvr1-2 http://10.127.38.113:8008/patroni: {"state": "starting", "role": "replica", "database_system_identifier": "6781543497195005939", "patroni": {"version": "1.6.5", "scope": "postgresql-dvr1-12-main"}}
2020-09-01 00:37:34,024 WARNING: Request failed to p-dc10-dbpgdvr1-2: GET http://10.127.38.113:8008/patroni ('xlog')
2020-09-01 00:37:34,049 INFO: Got response from p-dc10-dbpgdvr1-4 http://10.127.38.83:8008/patroni: {"state": "starting", "role": "replica", "database_system_identifier": "6781543497195005939", "patroni": {"version": "1.6.5", "scope": "postgresql-dvr1-12-main"}}
2020-09-01 00:37:34,049 WARNING: Request failed to p-dc10-dbpgdvr1-4: GET http://10.127.38.83:8008/patroni ('xlog')
2020-09-01 00:37:34,143 INFO: Register service postgresql-dvr1-12-main, params {'service_id': 'postgresql-dvr1-12-main/p-dc10-dbpgdvr1-1', 'address': '10.127.38.112', 'port': 5432, 'check': {'http': 'http://10.127.38.112:8008/replica', 'interval': '5s', 'DeregisterCriticalServiceAfter': '150.0s'}, 'tags': ['replica']}
2020-09-01 00:37:34,227 INFO: promoted self to leader by acquiring session lock
2020-09-01 00:37:34,240 INFO: cleared rewind state after becoming the leader
2020-09-01 00:37:35,211 INFO: Lock owner: p-dc10-dbpgdvr1-1; I am p-dc10-dbpgdvr1-1
2020-09-01 00:37:35,221 INFO: Register service postgresql-dvr1-12-main, params {'service_id': 'postgresql-dvr1-12-main/p-dc10-dbpgdvr1-1', 'address': '10.127.38.112', 'port': 5432, 'check': {'http': 'http://10.127.38.112:8008/master', 'interval': '5s', 'DeregisterCriticalServiceAfter': '150.0s'}, 'tags': ['master']}
2020-09-01 00:37:35,239 INFO: updated leader lock during promote
2020-09-01 00:37:38,211 INFO: Lock owner: p-dc10-dbpgdvr1-1; I am p-dc10-dbpgdvr1-1
2020-09-01 00:37:38,255 INFO: no action.  i am the leader with the lock
```

**Comment by CyberDem0n** [comment]
> 2020-09-01 00:35:19,973 INFO: no action.  i am the leader with the lock
2020-09-01 00:35:22,963 INFO: Lock owner: p-dc10-dbpgdvr1-1; I am p-dc10-dbpgdvr1-1
2020-09-01 00:35:55,735 ERROR: get_postgresql_status

The first line was from the previous HA loop.
Since the next loop started at `00:35:22` it gives us only 3 seconds. I assume that the loop_wait parameter is default, 10s, therefore the previous HA loop took about 7 seconds to complete. This is already an indicator that something is terribly wrong. Usually it should not take more than a few ms.

Now let's look at the second and third lines. Between them nearly 33 seconds, what is above ttl=30, therefore the session expired and also the leader key. After that Patroni **failed to update the leader lock** and **demoted** postgres.

The exception, (2020-09-01 00:35:55,735 ERROR: get_postgresql_status ... psycopg2.errors.QueryCanceled: canceling statement due to statement timeout) happened in the REST API thread. It didn't directly cause the demotion, but might have influenced it a bit. The query was canceled after 2s timeout. This is way too much for a query that is only calling a few functions from pg_catalog (pg_current_wal_lsn(), pg_last_wal_replay_lsn(), pg_stat_get_wal_senders() and so on).

I can only think that the system was terribly slow or may be under memory pressure. We observed similar issues a lot when running postgres+patroni in containers with limited memory. Sudden spikes of write activity were generating a lot of dirty pages and kernel was paging out Patroni causing such freezes (30+ seconds of no activity in logs). After we set on all nodes vm.dirty_background_bytes = 67108864 and vm.dirty_bytes = 134217728 problem mostly gone.

**Comment by caseyallenshobe** [comment]
I have loop_wait set to 3 seconds, not the default of 10.  TTL is 30.

As for the sysctl settings you mentioned, this is what we have them set to:
vm.dirty_background_bytes = 1073741824
vm.dirty_bytes = 2147483648

The nodes have 64MB of RAM, and the usage generally doesn't look very high.  From the same node right now:
```
              total        used        free      shared  buff/cache   available
Mem:       65966696     5681868      493468    16874712    59791360    42804272
```

If there's any relevant settings from Postgres or Patroni that I can provide, let me know and I will.

**Comment by CyberDem0n** [comment]
Have you checked postgres logs? There might be something interesting. 
There are not so many places where patroni could spend so much time. Either connection to postgres was busy or the patroni process was paged out.
The first one it should be possible to check in Postgres logs (if logging of slow queries is enabled).

**Comment by caseyallenshobe** [comment]
I should also mention, these nodes are VM's, hosted on VMWare ESXi.  The backend storage are SSD arrays, which should be quite fast.  The memory graph for the VM, from VMWare's vSphere interface, for the last 24 hours, doesn't show any unusually high memory usage - does "memory pressure" mean something other than just the amount used?

![image](https://user-images.githubusercontent.com/45512157/91886414-8adfa580-ec46-11ea-9266-9193468ca449.png)

**Comment by caseyallenshobe** [comment]
Unfortunately, I no longer have logs available, as we rotate them hourly and clean them up after processing with pgBadger to save space.  I didn't think to capture logs last night, but will keep that in mind should anything like this occur again.

**Comment by CyberDem0n** [comment]
Yes, memory pressure is more or less high memory usage. You can probably exclude it.

What is really strange, that the monitoring query which usually runs faster than a millisecond timed out after 2s.

**Comment by caseyallenshobe** [comment]
I've been digging into this, and it appears that I/O latency increased to 60+ms during this time.  I've been told that usually you want to stay sub-10ms for IO response times; 20+ms is usually very noticeable/painful.  So it seems pretty likely that this was the cause of that usually-fast query taking too long.  The VM layer is reporting only a 13ms latency when the 60+ latency from the OS is observed.  We're not sure where/why yet, as the backend storage is definitely not looking like the bottleneck (sub-1ms latency), but will keep digging into this to see if we can pinpoint the bottleneck.  Thank you for your feedback!
