### ISSUE TITLE
DB Server Crashing Frequently

### ISSUE THREAD

**Issue by Argha-2890** [zalando/patroni#1677]
Hi Team,

```
Patroni Version : 1.6.5
PostgreSQL Version : 11
```

I am getting the below error frequently which is causing the DB to go down and eventually failing over to the slave.

```
2020-08-31 17:50:38,425 ERROR:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/etcd.py", line 422, in wrapper
    retval = func(self, *args, **kwargs) is not None
  File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/etcd.py", line 621, in _update_leader
    return self.retry(self._client.write, self.leader_path, self._name, prevValue=self._name, ttl=self._ttl)
  File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/etcd.py", line 406, in retry
    return retry(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/patroni/utils.py", line 330, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/etcd/client.py", line 500, in write
    response = self.api_execute(path, method, params=params)
  File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/etcd.py", line 249, in api_execute
    return self._handle_server_response(response)
  File "/usr/local/lib/python3.5/dist-packages/etcd/client.py", line 987, in _handle_server_response
    etcd.EtcdError.handle(r)
  File "/usr/local/lib/python3.5/dist-packages/etcd/__init__.py", line 306, in handle
    raise exc(msg, payload)
etcd.EtcdKeyNotFound: Key not found : /rbdb/reviewboard/leader
2020-08-31 17:50:38,445 WARNING: Exception happened during processing of request from 10.47.226.209:58636
2020-08-31 17:50:38,535 WARNING: Exception happened during processing of request from 10.47.226.209:58592
2020-08-31 17:50:38,617 WARNING: Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/usr/local/lib/python3.5/dist-packages/patroni/api.py", line 130, in do_OPTIONS
    self.do_GET(write_status_code_only=True)
  File "/usr/local/lib/python3.5/dist-packages/patroni/api.py", line 121, in do_GET
    self.wfile.write('{0} {1} {2}\r\n'.format(self.protocol_version, status_code, message).encode('utf-8'))
  File "/usr/lib/python3.5/socket.py", line 593, in write
    return self._sock.send(b)
ConnectionResetError: [Errno 104] Connection reset by peer

2020-08-31 17:50:38,765 ERROR: failed to update leader lock
2020-08-31 17:50:38,766 WARNING: Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/usr/local/lib/python3.5/dist-packages/patroni/api.py", line 130, in do_OPTIONS
    self.do_GET(write_status_code_only=True)
  File "/usr/local/lib/python3.5/dist-packages/patroni/api.py", line 121, in do_GET
    self.wfile.write('{0} {1} {2}\r\n'.format(self.protocol_version, status_code, message).encode('utf-8'))
  File "/usr/lib/python3.5/socket.py", line 593, in write
    return self._sock.send(b)
ConnectionResetError: [Errno 104] Connection reset by peer

2020-09-01 03:40:41,428 ERROR: get_postgresql_status
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/patroni/api.py", line 443, in get_postgresql_status
    self.server.patroni.postgresql.lsn_name), retry=retry)[0]
  File "/usr/local/lib/python3.5/dist-packages/patroni/api.py", line 416, in query
    return self.server.query(sql, *params)
  File "/usr/local/lib/python3.5/dist-packages/patroni/api.py", line 503, in query
    raise e
  File "/usr/local/lib/python3.5/dist-packages/patroni/api.py", line 499, in query
    cursor.execute(sql, params)
psycopg2.errors.QueryCanceled: canceling statement due to statement timeout

2020-09-01 03:40:44,419 WARNING: Exception happened during processing of request from 10.47.226.209:60134
2020-09-01 03:40:44,489 WARNING: Exception happened during processing of request from 10.47.226.209:60102

```

We have configured HAProxy as our Load Balancer between the app and DB instances. I suspect that the issue lies with HAProxy as the exceptions are coming from the IP : 10.47.226.209 which is where HAProxy is setup.

HAProxy Config : 

```
global
    maxconn 500

defaults
    log global
    mode tcp
    retries 2
    timeout client 10800s
    timeout connect 4s
    timeout server 10800s
    timeout check 5s

listen stats
    mode http
    bind *:7000
    stats enable
    stats uri /haproxy?stats
   

listen RB_RW
    bind *:5432
    option httpchk OPTIONS /master
    default-server inter 3s fall 3 rise 2 downinter 5s
    server pg1 xxxx:5432 maxconn 250 check port 8008
    server pg2 xxxx:5432 maxconn 250 check port 8008
    server pg3 xxxxx:5432 maxconn 250 check port 8008
```

**Comment by CyberDem0n** [comment]
```
psycopg2.errors.QueryCanceled: canceling statement due to statement timeout
```

Patroni is using the statement_timeout=2s and running only very light queries.
If these queries get canceled something is terribly wrong with your server.

**Comment by Argha-2890** [comment]
@CyberDem0n - We are still getting this error and leader is constantly changing as a result of it. Could you please guide me on how to fix this issue.  I have tried to debug the cause but unable to reproduce the same.

**Comment by CyberDem0n** [comment]
> Could you please guide me on how to fix this issue.

Check postgres logs, check system logs, check the load on the system, look at your monitoring system, check config files, and so on.
I bet you only looked at Patroni logs... You didn't even share your configs (haproxy doesn't count).

**Comment by Argha-2890** [comment]
@CyberDem0n - Apologies for the late response. I was monitoring to see whether the issue reoccurs and unfortunately it has.

Patroni Config File : 

```
scope: deepthought
namespace: /dtdb/
name: pg1

restapi:
  listen: xxxxxx:8008
  connect_address: xxxxxx:8008


etcd:
  hosts: xxxxxx:2379,xxxxxx:2379,xxxxxx:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true


  initdb:  # Note: It needs to be a list (some options need values, others are switches)
    - encoding: UTF8
    - locale: en_US.UTF-8
    - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator xxxxx/32 md5
    - host replication replicator xxxx/32 md5
    - host replication replicator xxxx/32 md5
    - host all all 0.0.0.0/0 md5

  users:
    admin:
      password: admin123$
      options:
        - createrole
        - createdb

postgresql:
  listen: xxxxxx:5432
  connect_address: xxxxxx:5432
  data_dir: /pgdt/deepthought
  bin_dir: /usr/lib/postgresql/11/bin
  pgpass: /tmp/pgpass1
  authentication:
    replication:
      username: replicator
      password: xxxxxxx
    superuser:
      username: postgres
      password: xxxxxxx
  parameters:
    unix_socket_directories: '/tmp/, /var/run/postgresql/'
    archive_mode: "on"
    #    archive_command: "/usr/bin/pgbackrest --stanza:mdb archive-push %p"
    wal_log_hints: "on"
    logging_collector: "on"
    log_directory: "/var/log/postgresql"
    log_filename: "postgresql-%Y-%m-%d_%H%M%S.log"
    wal_level: "replica"
    wal_log_hints: "on"
    shared_buffers: "32GB"
    effective_cache_size: "96GB"
    maintenance_work_mem: "2GB"
    checkpoint_completion_target: 0.7
    wal_buffers: "16MB"
    default_statistics_target: 100
    random_page_cost: 1.1
    effective_io_concurrency: 200
    work_mem: "41943kB"
    min_wal_size: "1GB"
    max_wal_size: "4GB"
    archive_timeout: "1800s"
    listen_addresses: "*"


tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

log:
    dir: /var/log/postgresql
    level: INFO
```

PostgreSQL Logs : 

```
2020-09-12 03:57:39.382 PDT [109870] LOG:  received immediate shutdown request
2020-09-12 03:57:40.207 PDT [117335] WARNING:  terminating connection because of crash of another server process
2020-09-12 03:57:40.207 PDT [117335] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2020-09-12 03:57:40.207 PDT [117335] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2020-09-12 03:57:40.292 PDT [117315] WARNING:  terminating connection because of crash of another server process
2020-09-12 03:57:40.292 PDT [117315] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.

```

PostgreSQL Logs:

```
2020-09-12 01:09:35.900 PDT [9105] ERROR:  -1894967296 is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)
2020-09-12 01:09:35.900 PDT [9105] STATEMENT:  SET statement_timeout = -1894967296
2
```

1. I have checked the PostgreSQL logs and it didn't help me identify the exact cause for this issue. Could it be an issue with etcd and DB servers? I pinged and couldn't find any packet loss between the DB and etcd servers. 
2. Resources shouldn't be a concern as the servers have pretty high specs. 128 GB RAM and 32 CPU(s). The DB is also less compared to the specs.

**Comment by CyberDem0n** [comment]
Having a lot of RAM and CPU resources doesn't mean that IO can't be slow.
Looking randomly at logs also is not how it supposed to work.

You have to analyze a few minutes of Patroni and Postgres logs before the immediate shutdown and failover.
Every 10s Patroni should report its status. Does it always happen regularly? Are there any inconsistencies, i.e. suddenly it takes not 10s, but 15s-20s-30s+? What is in postgres logs around that time?

**Comment by Argha-2890** [comment]
It's happening every week and is a recent issue. 

> You have to analyze a few minutes of Patroni and Postgres logs before the immediate shutdown and failover.

PG Logs : 

```
2020-09-11 12:47:38.479 PDT [48714] LOG:  received immediate shutdown request
2020-09-11 12:47:38.483 PDT [28442] WARNING:  terminating connection because of crash of another server process
2020-09-11 12:47:38.483 PDT [28442] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2020-09-11 12:47:38.483 PDT [28442] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2020-09-11 12:47:38.499 PDT [48736] WARNING:  terminating connection because of crash of another server process
2020-09-11 12:47:38.499 PDT [48736] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2020-09-11 12:47:38.499 PDT [48736] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2020-09-11 12:47:43.054 PDT [28368] FATAL:  the database system is shutting down
2020-09-11 12:47:45.146 PDT [48714] LOG:  database system is shut down
```

Patroni Logs : 

```
2020-09-11 12:46:45,089 INFO: no action.  i am the leader with the lock
2020-09-11 12:46:55,075 INFO: Lock owner: pg1; I am pg1
2020-09-11 12:46:55,089 INFO: no action.  i am the leader with the lock
2020-09-11 12:47:32,934 ERROR: Request to server http://10.47.226.209:2379 failed: MaxRetryError('HTTPConnectionPool(host=\'10.47.226.209\', port=2379): Max retries exceeded with url: /v2/keys/rbdb
/reviewboard/?recursive=true (Caused by ReadTimeoutError("HTTPConnectionPool(host=\'10.47.226.209\', port=2379): Read timed out. (read timeout=0)",))',)
2020-09-11 12:47:35,945 INFO: Reconnection allowed, looking for another server.
2020-09-11 12:47:35,946 INFO: Retrying on http://10.47.226.104:2379
2020-09-11 12:47:36,346 INFO: Selected new etcd server http://10.47.226.104:2379
2020-09-11 12:47:37,679 WARNING: Exception happened during processing of request from 10.47.226.208:41500
2020-09-11 12:47:37,682 WARNING: Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/usr/local/lib/python3.5/dist-packages/patroni/api.py", line 134, in do_GET_patroni
    self._write_status_response(200, response)
  File "/usr/local/lib/python3.5/dist-packages/patroni/api.py", line 78, in _write_status_response
    self._write_json_response(status_code, response)
  File "/usr/local/lib/python3.5/dist-packages/patroni/api.py", line 37, in _write_json_response
    self._write_response(status_code, json.dumps(response), content_type='application/json')
  File "/usr/local/lib/python3.5/dist-packages/patroni/api.py", line 34, in _write_response
    self.wfile.write(body.encode('utf-8'))
  File "/usr/lib/python3.5/socket.py", line 593, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Broken pipe
```



> Every 10s Patroni should report its status. Does it always happen regularly? Are there any inconsistencies, i.e. suddenly it takes not 10s, but 15s-20s-30s+? What is in postgres logs around that time?

I am suspecting this to be the issue wherein it is taking more than 10 seconds sometime for Patroni status checks. Should I increase this value to say 30 or 60 seconds? Any drawbacks to in case I do make the changes.

**Comment by CyberDem0n** [comment]
>2020-09-11 12:46:55,089 INFO: no action.  i am the leader with the lock
2020-09-11 12:47:32,934 ERROR:

Now you have to figure out what was going on with you server between `12:46:55` and `12:47:32`, that's BTW 37 seconds, which is enough for the leader key to expire.

**Comment by Argha-2890** [comment]
I will do that. But in case I increase the value for ttl to 60 seconds. Will that have any drawbacks?

**Comment by CyberDem0n** [comment]
1. you have to use `patronictl edit-config` to change `ttl`
2. higher ttl value makes the failure detection slower but reducing chances of false positives
3. if you increase the ttl, it also makes sense to increase the `retry_timeout`, but mind the formula: `loop_wait + 2 * retry_timeout <= ttl`

**Comment by Argha-2890** [comment]
Ok..Thanks @CyberDem0n .

Will monitor and do the changes if required.

**Comment by tbozzio** [comment]
Hi @CyberDem0n ,

I've found your posts really really helpful when it has come to troubleshooting customer Patroni issues.

Should the formula for the interplay of `ttl`, `loop_wait` and `retry_timeout` be `2 * retry_timeout + loop_wait <= ttl` or `loop_wait + 2 * retry_timeout <= ttl`?

I ask, as I wanted to definitively know before making a recommendation to a customer.

Thanks in advance.

**Comment by CyberDem0n** [comment]
@tbozzio, I am sorry, but I fail to see a difference between two formulas. Multiply operation has a higher priority than sum, and the sum operation is commutative.

**Comment by tbozzio** [comment]
Thanks for making that clear - I now see where I failed to interpret the formulae correctly.
