### ISSUE TITLE
Patroni shutting down after DCS timeout

### ISSUE THREAD

**Issue by caseyallenshobe** [zalando/patroni#1686]
Using Patroni 1.6.5, I have now found this problem on two different clusters, after finding the database completely shut down:

```
2020-09-03 06:25:06,992 INFO: Lock owner: d-gp2-dbpgmgotanetworker1-1; I am d-gp2-dbpgmgotanetworker1-1
2020-09-03 06:25:10,570 INFO: no action.  i am the leader with the lock
2020-09-03 06:25:10,572 WARNING: Loop time exceeded, rescheduling immediately.
2020-09-03 06:25:10,575 INFO: Lock owner: d-gp2-dbpgmgotanetworker1-1; I am d-gp2-dbpgmgotanetworker1-1
2020-09-03 06:25:32,568 WARNING: Retry got exception: HTTPConnectionPool(host='127.0.0.1', port=8500): Max retries exceeded with url: /v1/session/renew/9d917d3c-e58b-c70b-df71-18267a973682 (Caused by ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=8500): Read timed out. (read timeout=3.3333333333333335)",))
2020-09-03 06:25:34,356 ERROR: refresh_session
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1356, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=8500): Read timed out. (read timeout=3.3333333333333335)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/utils.py", line 330, in __call__
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/patroni/dcs/consul.py", line 274, in _do_refresh_session
    self._client.session.renew(self._session)
  File "/usr/lib/python3/dist-packages/consul/base.py", line 1817, in renew
    params=params)
  File "/usr/lib/python3/dist-packages/patroni/dcs/consul.py", line 117, in wrapper
    return callback(self.response(self.http.request(method.upper(), self.uri(path, params), **kwargs)))
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 70, in request
    **urlopen_kw)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 322, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8500): Max retries exceeded with url: /v1/session/renew/9d917d3c-e58b-c70b-df71-18267a973682 (Caused by ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=8500): Read timed out. (read timeout=3.3333333333333335)",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/dcs/consul.py", line 293, in refresh_session
    return self.retry(self._do_refresh_session)
  File "/usr/lib/python3/dist-packages/patroni/dcs/consul.py", line 231, in retry
    return self._retry.copy()(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/patroni/utils.py", line 341, in __call__
    raise RetryFailedError("Exceeded retry deadline")
patroni.utils.RetryFailedError: 'Exceeded retry deadline'
2020-09-03 06:25:55,770 INFO: Lock owner: d-gp2-dbpgmgotanetworker1-1; I am d-gp2-dbpgmgotanetworker1-1
2020-09-03 06:25:55,817 INFO: Deregister service postgresql-mgotanetworker1-12-main/d-gp2-dbpgmgotanetworker1-1
```

systemctl status shows the following:
```
● patroni@12-main.service - Patroni instance 12-main
   Loaded: loaded (/lib/systemd/system/patroni@.service; indirect; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-09-03 06:25:59 UTC; 6 days ago
 Main PID: 8639 (code=exited, status=1/FAILURE)

Sep 03 06:25:57 d-gp2-dbpgmgotanetworker1-1 patroni@12-main[8639]:     return self.dcs.touch_member(data)
Sep 03 06:25:57 d-gp2-dbpgmgotanetworker1-1 patroni@12-main[8639]:   File "/usr/lib/python3/dist-packages/patroni/dcs/consul.py", line 148, in wrapper
Sep 03 06:25:57 d-gp2-dbpgmgotanetworker1-1 patroni@12-main[8639]:     return func(*args, **kwargs)
Sep 03 06:25:57 d-gp2-dbpgmgotanetworker1-1 patroni@12-main[8639]:   File "/usr/lib/python3/dist-packages/patroni/dcs/consul.py", line 370, in touch_member
Sep 03 06:25:57 d-gp2-dbpgmgotanetworker1-1 patroni@12-main[8639]:     create_member = not permanent and self.refresh_session()
Sep 03 06:25:57 d-gp2-dbpgmgotanetworker1-1 patroni@12-main[8639]:   File "/usr/lib/python3/dist-packages/patroni/dcs/consul.py", line 296, in refresh_sessi
Sep 03 06:25:57 d-gp2-dbpgmgotanetworker1-1 patroni@12-main[8639]:     raise ConsulError('Failed to renew/create session')
Sep 03 06:25:57 d-gp2-dbpgmgotanetworker1-1 patroni@12-main[8639]: patroni.dcs.consul.ConsulError: 'Failed to renew/create session'
Sep 03 06:25:59 d-gp2-dbpgmgotanetworker1-1 systemd[1]: patroni@12-main.service: Main process exited, code=exited, status=1/FAILURE
Sep 03 06:25:59 d-gp2-dbpgmgotanetworker1-1 systemd[1]: patroni@12-main.service: Failed with result 'exit-code'.
```

In the Consul agent log, I see the following:
```
2020/09/03 06:25:48 [WARN] agent: Check "service:postgresql-mgotanetworker1-12-main/d-gp2-dbpgmgotanetworker1-1" HTTP request failed: Get http://10.124.193.243:8008/master: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2020/09/03 06:25:48 [INFO] agent: Synced check "service:postgresql-mgotanetworker1-12-main/d-gp2-dbpgmgotanetworker1-1"
2020/09/03 06:25:55 [ERR] http: Request GET /v1/agent/service/deregister/postgresql-mgotanetworker1-12-main/d-gp2-dbpgmgotanetworker1-1, error: method GET not allowed from=127.0.0.1:36598
2020/09/03 06:25:58 [WARN] agent: Check "service:postgresql-mgotanetworker1-12-main/d-gp2-dbpgmgotanetworker1-1" HTTP request failed: Get http://10.124.193.243:8008/master: read tcp 10.124.193.243:41968->10.124.193.243:8008: read: connection reset by peer
2020/09/03 06:26:03 [WARN] agent: Check "service:postgresql-mgotanetworker1-12-main/d-gp2-dbpgmgotanetworker1-1" HTTP request failed: Get http://10.124.193.243:8008/master: dial tcp 10.124.193.243:8008: connect: connection refused
...(last line repeats for a while)...
2020/09/03 06:28:44 [INFO] agent: Deregistered service "postgresql-mgotanetworker1-12-main/d-gp2-dbpgmgotanetworker1-1"
2020/09/03 06:28:44 [INFO] agent: Deregistered check "service:postgresql-mgotanetworker1-12-main/d-gp2-dbpgmgotanetworker1-1"
2020/09/03 06:28:44 [INFO] agent: Check "service:postgresql-mgotanetworker1-12-main/d-gp2-dbpgmgotanetworker1-1" for service "postgresql-mgotanetworker1-12-main/d-gp2-dbpgmgotanetworker1-1" has been critical for too long; deregistered service
```

I'm not sure what might have caused this, but it appears that the local Consul agent lost connection with the Consul servers for a few minutes.  I would expect that the database should go read-only during this, and recover afterwards, rather than resulting in a dead Patroni service.

**Comment by caseyallenshobe** [comment]
FWIW, it's possible that the above clusters were actually running 1.6.1 or 1.6.2, although the package installed had been upgraded to 1.6.5.  Not sure if there's any way to confirm/deny that now.  I can say with certainty though that the above logs were from Patroni 1.6.1, 1.6.2, or 1.6.5.

**Comment by CyberDem0n** [comment]
It was fixed in the https://github.com/zalando/patroni/commit/c6207933, so yes, 1.6.5 is affected.

**Comment by caseyallenshobe** [comment]
Okay, so we'll want to upgrade to 2.0.0 once it's packaged.  Is it possible to upgrade Patroni without incurring a PostgreSQL outage?

**Comment by CyberDem0n** [comment]
> Is it possible to upgrade Patroni without incurring a PostgreSQL outage?

patronictl pause --wait
restart patroni
patronictl resume
