### ISSUE TITLE
Patroni immediately demotes on a temporary blip (seconds) of a k8s master

### ISSUE THREAD

**Issue by feikesteenbergen** [zalando/patroni#1729]
**Describe the bug**
A temporary `401: Unauthorized` returned by Kubernetes results in immediate demotion of the primary to a replica.
The k8s master was unable to authorize many requests (also non-patroni) for roughly 10 seconds.

After a couple of seconds, the update can continue and the (now restarted) postgresql instance is promoted to be a master.

**To Reproduce**
Use Kubernetes endpoints for Patroni on a cluster that receives all kinds of infrastructure level updates.

**Expected behavior**
That the obtaining of a leader lock will be retried until the leader lock expires.

**Environment**
- Patroni version: 1.6.5
- PostgreSQL version: 1.7.3
- DCS (and its version): Kubernetes v1.17.9

**Patroni configuration file**

```yaml
bootstrap:
  dcs:
    postgresql:
      authentication: {}
      parameters: {} # redacted
      pgbackrest:
        command: ""
        keep_data: false
        no_master: false
        no_params: false
      recovery_conf:
        recovery_target_timeline: latest
        restore_command: envdir /etc/postgresql/environment pgbackrest archive-get %f "%p"
        standby_mode: "on"
      use_pg_rewind: true
      use_slots: true
  initdb:
  - auth-host: md5
  - auth-local: trust
  method: restore_or_initdb
  post_init: /etc/postgresql/scripts/post_init.sh
  restore_or_initdb:
    command: envdir /etc/postgresql/environment /etc/postgresql/scripts/restore_or_initdb.sh
kubernetes:
  labels:
    application: spilo
    cluster-name: namespace-instance
    node-name: instance-an
  namespace: namespace
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
  role_label: spilo-role
  scope_label: node-name
  use_endpoints: true
log:
  level: WARNING
namespace: namespace
postgresql:
  authentication:
    replication:
      username: standby
    superuser:
      username: postgres
  bin_dir: /usr/lib/postgresql/12/bin
  callbacks:
    on_role_change: /scripts/on_role_change.sh zalandos true
  create_replica_methods:
  - pgbackrest
  - basebackup
  data_dir: /home/postgres/pgdata/data
  listen: 0.0.0.0:5432
  pg_hba:
  - hostssl   all,replication all         10.0.0.0/8     md5
  - hostssl   all,replication all         172.0.0.0/8    md5
  - hostssl   all,replication all         100.0.0.0/8    md5
  - local     all,replication postgres                   peer
  pgbackrest:
    command: envdir /etc/postgresql/environment /usr/bin/pgbackrest --stanza=poddb
      --delta restore --log-level-stderr=info
    keep_data: true
    no_master: true
    no_params: true
  use_unix_socket: true
restapi:
  listen: 0.0.0.0:8008
scope: instance-an
```

**patronictl show-config**

```
postgresql:
  authentication: {}
  parameters: {} # redacted
  pgbackrest:
    command: ''
    keep_data: false
    no_master: false
    no_params: false
  recovery_conf:
    recovery_target_timeline: latest
    restore_command: envdir /etc/postgresql/environment pgbackrest archive-get %f "%p"
    standby_mode: 'on'
  use_pg_rewind: true
  use_slots: true
```

**Have you checked Patroni logs?**
```console
2020-10-07 06:01:53,121 ERROR: ObjectCache.run ProtocolError('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
2020-10-07 06:01:56,230 ERROR: Unexpected error from Kubernetes API
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 436, in patch_or_create
    ret = self.retry(func, self._namespace, body) if retry else func(self._namespace, body)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 257, in retry
    return self._retry.copy()(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/patroni/utils.py", line 330, in __call__
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 76, in wrapper
    return getattr(self._api, func)(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/kubernetes/client/apis/core_v1_api.py", line 14806, in patch_namespaced_endpoints
    (data) = self.patch_namespaced_endpoints_with_http_info(name, namespace, body, **kwargs)
  File "/usr/lib/python3/dist-packages/kubernetes/client/apis/core_v1_api.py", line 14897, in patch_namespaced_endpoints_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python3/dist-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/lib/python3/dist-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python3/dist-packages/kubernetes/client/api_client.py", line 380, in request
    body=body)
  File "/usr/lib/python3/dist-packages/kubernetes/client/rest.py", line 286, in PATCH
    body=body)
  File "/usr/lib/python3/dist-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Www-Authenticate': 'Basic realm="kubernetes-master"', 'Date': 'Wed, 07 Oct 2020 06:01:56 GMT', 'Content-Length': '129'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
2020-10-07 06:01:56,234 ERROR: failed to update leader lock
```

**Have you checked PostgreSQL logs?**
```
2020-10-07 06:01:56 UTC [335]: [5f7ade94.14f-7] @,app= [00000] LOG:  received immediate shutdown request
2020-10-07 06:01:57 UTC [28691]: [5f7d59d4.7013-5] @,app= [00000] LOG:  database system is ready to accept read only connections
2020-10-07 06:02:13 UTC [28693]: [5f7d59d4.7015-8] @,app= [00000] LOG:  received promote request
```

**Have you tried to use GitHub issue search?**
Yes

**Additional context**
We do see other parts of the k8s environment receive `Unauthorized` on their API calls, so this problem is not strictly with Patroni,
but (one of the) k8s masters responding in error for a short period of time.

We could do something here with unexpected errors, as in, also retry unexpected errors?

https://github.com/zalando/patroni/blob/master/patroni/dcs/kubernetes.py#L896-L905

**Comment by CyberDem0n** [comment]
@feikesteenbergen right now we are retrying on 500, 503, and 504: https://github.com/zalando/patroni/blob/master/patroni/dcs/kubernetes.py#L468
Any other response code is non-retriable (according to K8s docs).

`ERROR: ObjectCache.run ProtocolError('Connection broken: IncompleteRead(0 bytes read)` -- this line means the WATCH connection to the API was broken, probably because the K8s master node is going off. Therefore the PATCH endpoint was either sent to the old master node or to the new one.
It looks like a concurrency issue with K8s API. Old master node should be removed from the service before the shutdown and the new node should not be added before it becomes 100% ready.

Adding 401 to the list shouldn't be hard and most likely it will mitigate the problem.

**Comment by feikesteenbergen** [comment]
This is probably the culprit:

https://github.com/kubernetes/kubernetes/issues/65785#issuecomment-576963962

Arguably, a `401` does not need a retry.

**Comment by CyberDem0n** [comment]
Looks like it is. IMO it is better to follow specs rather than implement workarounds which like:
1. might break in the future
2. produce unnecessary load on the api server.

**Comment by feikesteenbergen** [comment]
I'll close this for now in the hopes that we can fix/workaround this issue with k8s itself. I agree with the specs thing.
