### ISSUE TITLE
Comma separated list in PARAMETERS env variable

### ISSUE THREAD

**Issue by krezovic** [zalando/patroni#1743]
**Describe the bug**
I'm using patroni in Kubernetes, and trying to set the parameters using PARAMETERS env variable.

```
            - name: PARAMETERS
              value: >-
                {"max_wal_senders":10,"shared_preload_libraries":"pg_stat_statements","work_mem":"64MB"}
```

If I add more comma separated values to shared_preload_libraries, i.e.

```
            - name: PARAMETERS
              value: >-
                {"max_wal_senders":10,"shared_preload_libraries":"auth_delay, auto_explain, pg_stat_statements","work_mem":"64MB"}
```

The environment variable in the statefulset definition seems to be fine, but when I log into POD, I get the following ENV value, and an error:

```
$ env | grep PARAMETERS
PARAMETERS={"max_wal_senders":"10","shared_preload_libraries":"auth_delay"," auto_explain"," pg_stat_statements","work_mem":"64MB","shared_buffers":"2048MB","max_connections":"100","wal_level":"replica","logging_collector":"on","log_destination":"stderr","log_directory":"/srv/postgresql/volume/var","log_filename":"pg_logfile-%u","log_rotation_size":"0","log_rotation_age":"1d","log_truncate_on_rotation":"on","synchronous_commit":"on","synchronous_standby_names":""}
```

There are more values than I requested, and the comma separated list above is not correctly specified, resulting in a runtime error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 158, in _read_json_content
    request = json.loads(self.rfile.read(content_length).decode('utf-8'))
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 108 (char 107)

100   968  100   460  100   508   224k   248k --:--:-- --:--:-- --:--:--  945k
parse error: Invalid numeric literal at line 1, column 10
```

**To Reproduce**

Set PARAMETERS to "{"shared_preload_libraries":"auth_delay, auto_explain, pg_stat_statements"}"

**Environment**
- Patroni version: 1.6.4
- PostgreSQL version: 11.9

**Comment by CyberDem0n** [comment]
Hi @krezovic, I have no clue what you are talking about.
You probably should address this question to whoever maintains the docker image.

**Comment by krezovic** [comment]
so PARAMETERS is not something supported by patroni?

**Comment by krezovic** [comment]
Thank you for the hint, the PARAMETERS is a feature implemented by docker image provider. Sorry for the noise.
