### ISSUE TITLE
Not able to Start/bootstrap standby_cluster in another DC

### ISSUE THREAD

**Issue by suhasadhav** [zalando/patroni#1754]
**Describe the bug**
I have setup a 3 node Patroni cluster in DC1 and now setting up standby cluster for DR in DC2. WHenever I start patroni it gives me "INFO: waiting for standby_leader to bootstrap".

But when I run pg_basebackup command manually it starts working correctly after that but getting below issue while doing any operation using patronictl:

```
Traceback (most recent call last):
  File "/bin/patronictl", line 11, in <module>
    load_entry_point('patroni==1.6.5', 'console_scripts', 'patronictl')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/patroni/ctl.py", line 1166, in edit_config
    before_editing = format_config_for_editing(cluster.config.data)
AttributeError: 'NoneType' object has no attribute 'data'
```

**To Reproduce**

**Expected behavior**
I used below conf file in standby cluster:

```
bootstrap:
  dcs:
    standby_cluster:
      host: 10.26.5.44
      port: 5432
    postgresql:
      use_pg_rewind: true
      use_slots: false
      parameters:
        archive_mode: 'on'
        hot_standby: 'on'
        listen_addresses: '*'
        max_connections: '1000'
        max_locks_per_transaction: '64'
        max_prepared_transactions: '0'
        max_replication_slots: '10'
        max_wal_senders: '10'
        max_worker_processes: '8'
        pg_stat_statements.track: all
        port: '5432'
        shared_buffers: 10GB
        shared_preload_libraries: pg_stat_statements
        synchronous_commit: 'on'
        synchronous_standby_names: '*'
        wal_keep_segments: 50
        wal_level: replica
  initdb:
  - encoding: UTF8
  - data-checksums

  pg_hba:
  - host replication replicator 10.26.5.44/32 md5
  - host all all 0.0.0.0/0 md5

```

Below is the DEBUG:
```
2020-11-11 21:10:42,121 DEBUG: New etcd client created for http://127.0.0.1:4001
2020-11-11 21:10:42,121 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-11-11 21:10:42,121 DEBUG: Starting new HTTP connection (1): cbtcnbpgdb7:2379
2020-11-11 21:10:42,123 DEBUG: http://cbtcnbpgdb7:2379 "GET /v2/machines HTTP/1.1" 200 70
2020-11-11 21:10:42,124 DEBUG: Retrieved list of machines: [u'http://10.28.5.52:2379', u'http://10.28.5.53:2379', u'http://10.28.5.54:2379']
2020-11-11 21:10:42,124 INFO: Selected new etcd server http://10.28.5.52:2379
2020-11-11 21:10:42,125 DEBUG: Issuing read for key /pgbpmdr/pgbpmdr/ with args {'retry': <patroni.utils.Retry object at 0x7f4ee832dad0>, 'recursive': True}
2020-11-11 21:10:42,126 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-11-11 21:10:42,126 DEBUG: Starting new HTTP connection (1): 10.28.5.52:2379
2020-11-11 21:10:42,127 DEBUG: http://10.28.5.52:2379 "GET /v2/keys/pgbpmdr/pgbpmdr/?recursive=true HTTP/1.1" 404 85
2020-11-11 21:10:42,131 INFO: No PostgreSQL configuration items changed, nothing to reload.
2020-11-11 21:10:42,135 DEBUG: Issuing read for key /pgbpmdr/pgbpmdr/ with args {'retry': <patroni.utils.Retry object at 0x7f4ee8ef8710>, 'recursive': True}
2020-11-11 21:10:42,136 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-11-11 21:10:42,137 DEBUG: http://10.28.5.52:2379 "GET /v2/keys/pgbpmdr/pgbpmdr/?recursive=true HTTP/1.1" 404 85
2020-11-11 21:10:42,138 DEBUG: Writing {"conn_url":"postgres://cbtcnbpgdb2:5432/postgres","api_url":"http://cbtcnbpgdb2:8008/patroni","tags":{"nofailover":true,"noloadbalance":true,"nosync":true},"state":"stopped","version":"1.6.5","role":"uninitialized"} to key /pgbpmdr/pgbpmdr/members/cbtcnbpgdb2 ttl=30 dir=False append=False
2020-11-11 21:10:42,139 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-11-11 21:10:42,143 DEBUG: http://10.28.5.52:2379 "PUT /v2/keys/pgbpmdr/pgbpmdr/members/cbtcnbpgdb2 HTTP/1.1" 201 424
2020-11-11 21:10:42,144 INFO: Lock owner: None; I am cbtcnbpgdb2
2020-11-11 21:10:42,145 DEBUG: Writing {"conn_url":"postgres://cbtcnbpgdb2:5432/postgres","api_url":"http://cbtcnbpgdb2:8008/patroni","tags":{"nofailover":true,"noloadbalance":true,"nosync":true},"state":"stopped","version":"1.6.5","role":"uninitialized"} to key /pgbpmdr/pgbpmdr/members/cbtcnbpgdb2 ttl=30 dir=False append=False
2020-11-11 21:10:42,145 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-11-11 21:10:42,148 DEBUG: http://10.28.5.52:2379 "PUT /v2/keys/pgbpmdr/pgbpmdr/members/cbtcnbpgdb2 HTTP/1.1" 200 835
2020-11-11 21:10:42,148 INFO: waiting for standby_leader to bootstrap
2020-11-11 21:10:52,136 DEBUG: Issuing read for key /pgbpmdr/pgbpmdr/ with args {'retry': <patroni.utils.Retry object at 0x7f4eefe505d0>, 'recursive': True}
2020-11-11 21:10:52,137 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-11-11 21:10:52,139 DEBUG: http://10.28.5.52:2379 "GET /v2/keys/pgbpmdr/pgbpmdr/?recursive=true HTTP/1.1" 200 614
2020-11-11 21:10:52,141 INFO: Lock owner: None; I am cbtcnbpgdb2
2020-11-11 21:10:52,142 DEBUG: Writing {"conn_url":"postgres://cbtcnbpgdb2:5432/postgres","api_url":"http://cbtcnbpgdb2:8008/patroni","tags":{"nofailover":true,"noloadbalance":true,"nosync":true},"state":"stopped","version":"1.6.5","role":"uninitialized"} to key /pgbpmdr/pgbpmdr/members/cbtcnbpgdb2 ttl=30 dir=False append=False
2020-11-11 21:10:52,143 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-11-11 21:10:52,147 DEBUG: http://10.28.5.52:2379 "PUT /v2/keys/pgbpmdr/pgbpmdr/members/cbtcnbpgdb2 HTTP/1.1" 200 835
2020-11-11 21:10:52,148 INFO: waiting for standby_leader to bootstrap
~
```

**Screenshots**

**Environment**
- Patroni version: 1.6.5
- PostgreSQL version: 11.6
- DCS (and its version):ETCD

**Patroni configuration file**
```
Please copy&paste your Patroni configuration file here
```

**patronictl show-config**
```
Please copy&paste the output of "patronictl show-config" command here
```

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.

**Additional context**

**Comment by CyberDem0n** [comment]
1. python2.7 -- is EOL for about 1 year
2. Patroni version: 1.6.5 -- is outdated, you have to use the latest version
3. `waiting for standby_leader to bootstrap` -- most likely there is already initialize key for the standby cluster. You can verify it by running `patronictl list`.

**Comment by suhasadhav** [comment]
We are in production environment now so upgrading Patroni and python would be difficult. I tried again by removing the key in DCS but having same issue:

```
#patronictl -c /etc/patroni/conf.yml list
+ Cluster: pgbpmdr (uninitialized) -+-----------+
| Member | Host | Role | State | TL | Lag in MB |
+--------+------+------+-------+----+-----------+
+--------+------+------+-------+----+-----------+
```

**Comment by CyberDem0n** [comment]
> We are in production environment now so upgrading Patroni and python would be difficult.

Come on, we are talking about the standby cluster, which doesn't even running!

> I tried again by removing the key in DCS but having same issue:

Well, you didn't even show the full Patroni config file. Now you don't show logs...

**Comment by suhasadhav** [comment]
Ohh. I thought you are talking about upgrade in production, if upgrade in DR site is the option we can try that but can we try some alternative here because I wanted to have same version in both PROD and DR site.

Below is the full config file:
```
name: mcokapgdb2
namespace: /pgbpmdr/
scope: pgbpmdr

log:
  level: DEBUG
  traceback_level: DEBUG
  dir: '/etc/patroni/logs'
  file_num: 5

restapi:
  listen: mcokapgdb2:8008
  connect_address: mcokapgdb2:8008

etcd:
  hosts:
  - mcokapgdb7:2379
  - mcokapgdb8:2379
  - mcokapgdb9:2379


bootstrap:
  dcs:
    standby_cluster:
      host: 10.26.5.44
      port: 5432
    postgresql:
      use_pg_rewind: true
      use_slots: false
      parameters:
        archive_mode: 'on'
        hot_standby: 'on'
        listen_addresses: '*'
        max_connections: '1000'
        max_locks_per_transaction: '64'
        max_prepared_transactions: '0'
        max_replication_slots: '10'
        max_wal_senders: '10'
        max_worker_processes: '8'
        pg_stat_statements.track: all
        port: '5432'
        shared_buffers: 10GB
        shared_preload_libraries: pg_stat_statements
        synchronous_commit: 'on'
        synchronous_standby_names: '*'
        wal_keep_segments: 50
        wal_level: replica
  initdb:
  - encoding: UTF8
  - data-checksums

  pg_hba:
  - host replication replicator 10.26.5.44/32 md5
  - host all all 0.0.0.0/0 md5

  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb

postgresql:
  listen: '*'
  connect_address: mcokapgdb2:5432
  bin_dir: /usr/pgsql-11/bin
  data_dir: /pgcluster/pgdata
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: replicator
    superuser:
      username: postgres
      password: postgres
    rewind:
      username: rewind_user
      password: rewind_password
  parameters:
    unix_socket_directories: '.'


tags:
    nofailover: true
    noloadbalance: true
    clonefrom: false
    nosync: true

```

```
2020-11-12 00:02:35,223 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-11-12 00:02:35,227 DEBUG: http://10.28.5.54:2379 "PUT /v2/keys/pgbpmdr/pgbpmdr/members/mcokapgdb2 HTTP/1.1" 200 835
2020-11-12 00:02:35,228 INFO: waiting for standby_leader to bootstrap
2020-11-12 00:02:45,216 DEBUG: Issuing read for key /pgbpmdr/pgbpmdr/ with args {'retry': <patroni.utils.Retry object at 0x7f75a09e7790>, 'recursive': True}
2020-11-12 00:02:45,217 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-11-12 00:02:45,219 DEBUG: http://10.28.5.54:2379 "GET /v2/keys/pgbpmdr/pgbpmdr/?recursive=true HTTP/1.1" 200 614
2020-11-12 00:02:45,221 INFO: Lock owner: None; I am mcokapgdb2
2020-11-12 00:02:45,222 DEBUG: Writing {"conn_url":"postgres://mcokapgdb2:5432/postgres","api_url":"http://mcokapgdb2:8008/patroni","tags":{"nofailover":true,"noloadbalance":true,"nosync":true},"state":"stopped","version":"1.6.5","role":"uninitialized"} to key /pgbpmdr/pgbpmdr/members/mcokapgdb2 ttl=30 dir=False append=False
2020-11-12 00:02:45,223 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-11-12 00:02:45,227 DEBUG: http://10.28.5.54:2379 "PUT /v2/keys/pgbpmdr/pgbpmdr/members/mcokapgdb2 HTTP/1.1" 200 834
2020-11-12 00:02:45,228 INFO: waiting for standby_leader to bootstrap
2020-11-12 00:02:55,216 DEBUG: Issuing read for key /pgbpmdr/pgbpmdr/ with args {'retry': <patroni.utils.Retry object at 0x7f7599a7a750>, 'recursive': True}
2020-11-12 00:02:55,217 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-11-12 00:02:55,219 DEBUG: http://10.28.5.54:2379 "GET /v2/keys/pgbpmdr/pgbpmdr/?recursive=true HTTP/1.1" 200 613
2020-11-12 00:02:55,221 INFO: Lock owner: None; I am mcokapgdb2
2020-11-12 00:02:55,223 DEBUG: Writing {"conn_url":"postgres://mcokapgdb2:5432/postgres","api_url":"http://mcokapgdb2:8008/patroni","tags":{"nofailover":true,"noloadbalance":true,"nosync":true},"state":"stopped","version":"1.6.5","role":"uninitialized"} to key /pgbpmdr/pgbpmdr/members/mcokapgdb2 ttl=30 dir=False append=False
2020-11-12 00:02:55,224 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-11-12 00:02:55,228 DEBUG: http://10.28.5.54:2379 "PUT /v2/keys/pgbpmdr/pgbpmdr/members/mcokapgdb2 HTTP/1.1" 200 834
2020-11-12 00:02:55,229 INFO: waiting for standby_leader to bootstrap
2020-11-12 00:03:05,216 DEBUG: Issuing read for key /pgbpmdr/pgbpmdr/ with args {'retry': <patroni.utils.Retry object at 0x7f7599a7a790>, 'recursive': True}
2020-11-12 00:03:05,217 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-11-12 00:03:05,219 DEBUG: http://10.28.5.54:2379 "GET /v2/keys/pgbpmdr/pgbpmdr/?recursive=true HTTP/1.1" 200 614
2020-11-12 00:03:05,222 INFO: Lock owner: None; I am mcokapgdb2
2020-11-12 00:03:05,223 DEBUG: Writing {"conn_url":"postgres://mcokapgdb2:5432/postgres","api_url":"http://mcokapgdb2:8008/patroni","tags":{"nofailover":true,"noloadbalance":true,"nosync":true},"state":"stopped","version":"1.6.5","role":"uninitialized"} to key /pgbpmdr/pgbpmdr/members/mcokapgdb2 ttl=30 dir=False append=False
2020-11-12 00:03:05,224 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-11-12 00:03:05,229 DEBUG: http://10.28.5.54:2379 "PUT /v2/keys/pgbpmdr/pgbpmdr/members/mcokapgdb2 HTTP/1.1" 200 835
2020-11-12 00:03:05,230 INFO: waiting for standby_leader to bootstrap
2020-11-12 00:03:15,216 DEBUG: Issuing read for key /pgbpmdr/pgbpmdr/ with args {'retry': <patroni.utils.Retry object at 0x7f7599a7a750>, 'recursive': True}
2020-11-12 00:03:15,217 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-11-12 00:03:15,219 DEBUG: http://10.28.5.54:2379 "GET /v2/keys/pgbpmdr/pgbpmdr/?recursive=true HTTP/1.1" 200 614
2020-11-12 00:03:15,221 INFO: Lock owner: None; I am mcokapgdb2
2020-11-12 00:03:15,223 DEBUG: Writing {"conn_url":"postgres://mcokapgdb2:5432/postgres","api_url":"http://mcokapgdb2:8008/patroni","tags":{"nofailover":true,"noloadbalance":true,"nosync":true},"state":"stopped","version":"1.6.5","role":"uninitialized"} to key /pgbpmdr/pgbpmdr/members/mcokapgdb2 ttl=30 dir=False append=False
2020-11-12 00:03:15,224 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-11-12 00:03:15,228 DEBUG: http://10.28.5.54:2379 "PUT /v2/keys/pgbpmdr/pgbpmdr/members/mcokapgdb2 HTTP/1.1" 200 835
2020-11-12 00:03:15,228 INFO: waiting for standby_leader to bootstrap
2020-11-12 00:03:25,216 DEBUG: Issuing read for key /pgbpmdr/pgbpmdr/ with args {'retry': <patroni.utils.Retry object at 0x7f7599a7a790>, 'recursive': True}
2020-11-12 00:03:25,217 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-11-12 00:03:25,219 DEBUG: http://10.28.5.54:2379 "GET /v2/keys/pgbpmdr/pgbpmdr/?recursive=true HTTP/1.1" 200 614
2020-11-12 00:03:25,221 INFO: Lock owner: None; I am mcokapgdb2
2020-11-12 00:03:25,222 DEBUG: Writing {"conn_url":"postgres://mcokapgdb2:5432/postgres","api_url":"http://mcokapgdb2:8008/patroni","tags":{"nofailover":true,"noloadbalance":true,"nosync":true},"state":"stopped","version":"1.6.5","role":"uninitialized"} to key /pgbpmdr/pgbpmdr/members/mcokapgdb2 ttl=30 dir=False append=False
2020-11-12 00:03:25,223 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-11-12 00:03:25,227 DEBUG: http://10.28.5.54:2379 "PUT /v2/keys/pgbpmdr/pgbpmdr/members/mcokapgdb2 HTTP/1.1" 200 835
2020-11-12 00:03:25,228 INFO: waiting for standby_leader to bootstrap
2020-11-12 00:03:35,216 DEBUG: Issuing read for key /pgbpmdr/pgbpmdr/ with args {'retry': <patroni.utils.Retry object at 0x7f7599a7a750>, 'recursive': True}
2020-11-12 00:03:35,217 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-11-12 00:03:35,219 DEBUG: http://10.28.5.54:2379 "GET /v2/keys/pgbpmdr/pgbpmdr/?recursive=true HTTP/1.1" 200 614
2020-11-12 00:03:35,221 INFO: Lock owner: None; I am mcokapgdb2
2020-11-12 00:03:35,223 DEBUG: Writing {"conn_url":"postgres://mcokapgdb2:5432/postgres","api_url":"http://mcokapgdb2:8008/patroni","tags":{"nofailover":true,"noloadbalance":true,"nosync":true},"state":"stopped","version":"1.6.5","role":"uninitialized"} to key /pgbpmdr/pgbpmdr/members/mcokapgdb2 ttl=30 dir=False append=False
2020-11-12 00:03:35,224 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-11-12 00:03:35,228 DEBUG: http://10.28.5.54:2379 "PUT /v2/keys/pgbpmdr/pgbpmdr/members/mcokapgdb2 HTTP/1.1" 200 835
2020-11-12 00:03:35,228 INFO: waiting for standby_leader to bootstrap
2020-11-12 00:03:45,216 DEBUG: Issuing read for key /pgbpmdr/pgbpmdr/ with args {'retry': <patroni.utils.Retry object at 0x7f7599a7a790>, 'recursive': True}
2020-11-12 00:03:45,217 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-11-12 00:03:45,219 DEBUG: http://10.28.5.54:2379 "GET /v2/keys/pgbpmdr/pgbpmdr/?recursive=true HTTP/1.1" 200 614
2020-11-12 00:03:45,221 INFO: Lock owner: None; I am mcokapgdb2
2020-11-12 00:03:45,222 DEBUG: Writing {"conn_url":"postgres://mcokapgdb2:5432/postgres","api_url":"http://mcokapgdb2:8008/patroni","tags":{"nofailover":true,"noloadbalance":true,"nosync":true},"state":"stopped","version":"1.6.5","role":"uninitialized"} to key /pgbpmdr/pgbpmdr/members/mcokapgdb2 ttl=30 dir=False append=False
2020-11-12 00:03:45,223 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-11-12 00:03:45,228 DEBUG: http://10.28.5.54:2379 "PUT /v2/keys/pgbpmdr/pgbpmdr/members/mcokapgdb2 HTTP/1.1" 200 835
2020-11-12 00:03:45,229 INFO: waiting for standby_leader to bootstrap
2020-11-12 00:03:55,216 DEBUG: Issuing read for key /pgbpmdr/pgbpmdr/ with args {'retry': <patroni.utils.Retry object at 0x7f75a09e7c50>, 'recursive': True}
2020-11-12 00:03:55,217 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-11-12 00:03:55,219 DEBUG: http://10.28.5.54:2379 "GET /v2/keys/pgbpmdr/pgbpmdr/?recursive=true HTTP/1.1" 200 614
2020-11-12 00:03:55,221 INFO: Lock owner: None; I am mcokapgdb2
2020-11-12 00:03:55,222 DEBUG: Writing {"conn_url":"postgres://mcokapgdb2:5432/postgres","api_url":"http://mcokapgdb2:8008/patroni","tags":{"nofailover":true,"noloadbalance":true,"nosync":true},"state":"stopped","version":"1.6.5","role":"uninitialized"} to key /pgbpmdr/pgbpmdr/members/mcokapgdb2 ttl=30 dir=False append=False
2020-11-12 00:03:55,223 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-11-12 00:03:55,228 DEBUG: http://10.28.5.54:2379 "PUT /v2/keys/pgbpmdr/pgbpmdr/members/mcokapgdb2 HTTP/1.1" 200 835
2020-11-12 00:03:55,229 INFO: waiting for standby_leader to bootstrap
2020-11-12 00:04:05,216 DEBUG: Issuing read for key /pgbpmdr/pgbpmdr/ with args {'retry': <patroni.utils.Retry object at 0x7f7599a7a790>, 'recursive': True}
2020-11-12 00:04:05,217 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-11-12 00:04:05,219 DEBUG: http://10.28.5.54:2379 "GET /v2/keys/pgbpmdr/pgbpmdr/?recursive=true HTTP/1.1" 200 614
2020-11-12 00:04:05,221 INFO: Lock owner: None; I am mcokapgdb2
```

**Comment by CyberDem0n** [comment]
You have a tag nofailover: true, that's the problem
Since this node isn't allowed to become a leader it won't take a basebackup (initialize standby cluster).

**Comment by suhasadhav** [comment]
You are a genius!!
I was tagging this to have no failover on this node but forgot to think logically that both clusters are having separate DCS so it wont be failed over to standby cluster.

Thank you Man!

**Comment by suhasadhav** [comment]
One more doubt, I am setting this Cluster for Disaster recovery situation, when actual Disaster happens on primary site how can I make standalone cluster in read-write mode and detach from primary cluster.

**Comment by kostiantyn-nemchenko** [comment]
@suhasadhav just remove the `standby_cluster` section via `patronictl edit-config`

**Comment by suhasadhav** [comment]
Thank you, Closing the issue.
