### ISSUE TITLE
Patroni wrong cert error

### ISSUE THREAD

**Issue by andrei-matei** [zalando/patroni#1758]
Hello all,

I am opening this here because I am not sure if it's a bug or if I am doing something wrong.

I am using Patroni (in Crunchy postgres-operator) and at the time it start, I get a weird error regarding SSL failing when trying to connect to Kubernetes API. Is there a place where I need to setup a CA so that communication works?

Here is the error:
`2020-11-14 09:59:41,806 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)'),)': /api/v1/namespaces/pgo/pods?labelSelector=vendor%3Dcrunchydata%2Ccrunchy-pgha-scope%3Dhippo1
**2020-11-14 09:59:41,811 ERROR: Request to server https://10.32.0.1:443 failed: MaxRetryError("HTTPSConnectionPool(host='10.32.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/pgo/configmaps?labelSelector=vendor%3Dcrunchydata%2Ccrunchy-pgha-scope%3Dhippo1 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)'),))",)
2020-11-14 09:59:41,812 ERROR: Request to server https://10.32.0.1:443 failed: MaxRetryError("HTTPSConnectionPool(host='10.32.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/pgo/pods?labelSelector=vendor%3Dcrunchydata%2Ccrunchy-pgha-scope%3Dhippo1 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)'),))",)**
2020-11-14 09:59:42,734 ERROR: get_cluster
**Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/kubernetes.py", line 700, in _load_cluster
    self._wait_caches(stop_time)
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/kubernetes.py", line 692, in _wait_caches
    raise RetryFailedError('Exceeded retry deadline')
patroni.utils.RetryFailedError: 'Exceeded retry deadline'**
2020-11-14 09:59:42,734 WARNING: Can not get cluster from dcs
2020-11-14 09:59:42,812 ERROR: ObjectCache.run TypeError("unsupported operand type(s) for -: 'NoneType' and 'float'",)
2020-11-14 09:59:42,813 ERROR: ObjectCache.run TypeError("unsupported operand type(s) for -: 'NoneType' and 'float'",)
2020-11-14 09:59:42,819 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)'),)': /api/v1/namespaces/pgo/configmaps?labelSelector=vendor%3Dcrunchydata%2Ccrunchy-pgha-scope%3Dhippo1
2020-11-14 09:59:42,821 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)'),)': /api/v1/namespaces/pgo/pods?labelSelector=vendor%3Dcrunchydata%2Ccrunchy-pgha-scope%3Dhippo1`

On Kubernetes API Server I can see this error:
log.go:172] http: TLS handshake error from 10.10.81.113:37460: remote error: tls: unknown certificate authority

I am running in Kubernetes 18.10, installed with Kubeadm, running on local Centos 7 20.03 machines, with 3 masters connected to HAProxy and external etcd. Does anyone have any idea why the error? I am banging my head against the table for 3 days :)

Thanks in advance,
Andrei

**Comment by CyberDem0n** [comment]
Patroni is using serviceaccount token and ca.crt from /var/run/secrets/kubernetes.io/serviceaccount/: https://github.com/zalando/patroni/blob/e8e87bf0a14b5a85e3ea0b405d2f77003e22f7ad/patroni/dcs/kubernetes.py#L29

I can only advise to check with curl that they are valid.

**Comment by parmpreetSingh** [comment]
Hi CyberDemOn

We are also facing the same issue :-
2020-12-23 13:49:30,942 ERROR: Request to server https://10.200.32.1:443 failed: MaxRetryError("HTTPSConnectionPool(host='10.200.32.1', port=443): Max retries exceeded with url: /api/v1/namespaces/pgo/pods?labelSelector=vendor%3Dcrunchydata%2Ccrunchy-pgha-scope%3Dhippo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)'),))",)

If i will try the same request using curl with Token properly set and passing the cacerts. It is going though fine.

Only difference is we are not having "TLS handshake error" in the logs as pointed by Andrei.

**Comment by jeffmhastings** [comment]
Are you using an intermediate CA to sign certificates for the Kubernetes API server? I've seen reports of similar errors caused by the service account token's ca.crt not including the root CA certificate. There's a similar issue reported with another project that's using the python Kuebrnetes client https://github.com/jupyterhub/kubespawner/issues/492

**Comment by knackaron** [comment]
I've submitted a pull request to resolve this issue.  Current behavior is not modified, but flexibility is given to cluster operators who need to override the CA bundle using the pretty much globally-accepted method of setting the `SSL_CERT_FILE` environment variable.

@jeffmhastings  Setting `--root-ca-file` for `kube-controller-manager` is not something that should done, as it can affect every other k8s client in the cluster, whereas it's only the Python clients that seem to have this problem with only providing the intermediate CA certificate.  Altering that option also lends itself to issues upon cluster upgrades using `kubeadm` or whatever other tooling might manage your cluster upgrades.  There was also some strong words against providing the full chain in the `ServiceAccount` secrets here: https://bugzilla.redhat.com/show_bug.cgi?id=1654558#c4

As cluster operators, there are a lot of components that require additional CA certificates to be provided, more than just k8s clients.  We've found that supplying the CA certificates in one location (e.g., a `Secret` per namespace) and mounting them into Pods that require them is the most portable solution.  Not all applications (and by that I really mean Helm charts) have first-class support for overriding the CA bundle, but nearly all do have support for environment variables, volumes, and volume mounts, so we've adopted that methodology to keep things as consistent as possible when integrating the many open source components that go into a production grade k8s cluster.

**Comment by SaiSankethG** [comment]
File "/usr/local/lib/python3.10/dist-packages/patroni/dcs/kubernetes.py", line 980, in __load_cluster                 │
│     self._wait_caches(stop_time)                                                                                        │
│   File "/usr/local/lib/python3.10/dist-packages/patroni/dcs/kubernetes.py", line 860, in _wait_caches                   │
│     raise RetryFailedError('Exceeded retry deadline')   

the pods shows running but when i checked the logs for the postgres pod, shows the apiExpection() connection refused.  
is the issue with the deployment or the pods ?
