### ISSUE TITLE
[patronictl][prettytable] SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by lokanadham100** [zalando/patroni#1763]
patronictl command is throwing following error
```
/home# patronictl
Traceback (most recent call last):
  File "/usr/bin/patronictl", line 7, in <module>
    from patroni.ctl import ctl
  File "/opt/patroni/venv/lib/python3.5/site-packages/patroni/ctl.py", line 34, in <module>
    from prettytable import PrettyTable
  File "/opt/patroni/venv/lib/python3.5/site-packages/prettytable/__init__.py", line 3, in <module>
    from .prettytable import (
  File "/opt/patroni/venv/lib/python3.5/site-packages/prettytable/prettytable.py", line 250
    raise Exception(f"Index {index} is invalid, must be an integer or slice")
                                                                           ^
SyntaxError: invalid syntax
```
**To Reproduce**
Just create new patroni cluster, it will fetch latest dependencies and the above error will come while using patronictl command line tool.

**pip list with the issue**
```
/home# /opt/patroni/venv/bin/pip list
cdiff (1.0)
certifi (2020.11.8)
chardet (3.0.4)
click (7.1.2)
idna (2.10)
patroni (1.6.4)
pip (8.1.1)
pkg-resources (0.0.0)
prettytable (2.0.0)
psutil (5.7.3)
psycopg2-binary (2.8.4)
python-consul (1.1.0)
python-dateutil (2.8.1)
pytz (2020.4)
PyYAML (5.3.1)
requests (2.25.0)
setuptools (20.7.0)
six (1.15.0)
tzlocal (2.1)
urllib3 (1.26.2)
wcwidth (0.2.5)
You are using pip version 8.1.1, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Temporary Fix**
From the pip list from the old cluster and above error message, found out that issue is because of `prettytable` package. It got updated to major version 2.
We degraded `prettytable` back to 1.0.1 using pip uninstall/install commands as follows. 
```
/home# /opt/patroni/venv/bin/pip uninstall prettytable
Uninstalling prettytable-2.0.0:
  /opt/patroni/venv/lib/python3.5/site-packages/prettytable-2.0.0.dist-info/COPYING
  /opt/patroni/venv/lib/python3.5/site-packages/prettytable-2.0.0.dist-info/INSTALLER
  /opt/patroni/venv/lib/python3.5/site-packages/prettytable-2.0.0.dist-info/METADATA
  /opt/patroni/venv/lib/python3.5/site-packages/prettytable-2.0.0.dist-info/RECORD
  /opt/patroni/venv/lib/python3.5/site-packages/prettytable-2.0.0.dist-info/WHEEL
  /opt/patroni/venv/lib/python3.5/site-packages/prettytable-2.0.0.dist-info/top_level.txt
  /opt/patroni/venv/lib/python3.5/site-packages/prettytable/__init__.py
  /opt/patroni/venv/lib/python3.5/site-packages/prettytable/__pycache__/__init__.cpython-35.pyc
  /opt/patroni/venv/lib/python3.5/site-packages/prettytable/prettytable.py
Proceed (y/n)? y
  Successfully uninstalled prettytable-2.0.0
You are using pip version 8.1.1, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


/home# /opt/patroni/venv/bin/pip list
cdiff (1.0)
certifi (2020.11.8)
chardet (3.0.4)
click (7.1.2)
idna (2.10)
patroni (1.6.4)
pip (8.1.1)
pkg-resources (0.0.0)
psutil (5.7.3)
psycopg2-binary (2.8.4)
python-consul (1.1.0)
python-dateutil (2.8.1)
pytz (2020.4)
PyYAML (5.3.1)
requests (2.25.0)
setuptools (20.7.0)
six (1.15.0)
tzlocal (2.1)
urllib3 (1.26.2)
wcwidth (0.2.5)
You are using pip version 8.1.1, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


/home# /opt/patroni/venv/bin/pip install prettytable==1.0.1
Collecting prettytable==1.0.1
  Downloading https://files.pythonhosted.org/packages/39/da/8336296a830caa495a25304e12ffb32a8c3a9d2d08ba995f066fe16152e1/prettytable-1.0.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in /opt/patroni/venv/lib/python3.5/site-packages (from prettytable==1.0.1)
Requirement already satisfied (use --upgrade to upgrade): wcwidth in /opt/patroni/venv/lib/python3.5/site-packages (from prettytable==1.0.1)
Installing collected packages: prettytable
Successfully installed prettytable-1.0.1
You are using pip version 8.1.1, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


/home# /opt/patroni/venv/bin/pip list
cdiff (1.0)
certifi (2020.11.8)
chardet (3.0.4)
click (7.1.2)
idna (2.10)
patroni (1.6.4)
pip (8.1.1)
pkg-resources (0.0.0)
prettytable (1.0.1)
psutil (5.7.3)
psycopg2-binary (2.8.4)
python-consul (1.1.0)
python-dateutil (2.8.1)
pytz (2020.4)
PyYAML (5.3.1)
requests (2.25.0)
setuptools (20.7.0)
six (1.15.0)
tzlocal (2.1)
urllib3 (1.26.2)
wcwidth (0.2.5)
You are using pip version 8.1.1, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

After this `patronictl` working fine.

**Root Cause**
Issue happend because of upgrade of `prettytable` package to latest major version, which patroni dont have support.
We see that `requirements.txt` dont have major version level lock for most of the packages, so this kind of issues might happen in future as well.

**Solution**
We need to lock `requirements.txt` to current available major versions.

**Extra Note**
We are using `patroni-1.6.4`. But issue will happen in master as well.

**Comment by CyberDem0n** [comment]
Patroni perfectly supports the latest version of prettytable.

That's prettytable doesn't support python 3.5, which by the way EOL since September 13th, 2020.

The question is how did you managed to install 2.0.0 with python 3.5, because it doesn't even exists:
```bash
(venv3.5) ~/patroni$ pip install prettytable==2.0.0
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
ERROR: Could not find a version that satisfies the requirement prettytable==2.0.0 (from versions: 0.3, 0.4, 0.5, 0.6, 0.6.1, 0.7.1, 0.7.2, 1.0.0, 1.0.1)
ERROR: No matching distribution found for prettytable==2.0.0
```
