### ISSUE TITLE
Cannot start a standby cluster (Patroni incorrectly promotes itself as master and stops replicating)

### ISSUE THREAD

**Issue by adacaccia** [zalando/patroni#1773]
**Describe the bug**
Wanted a "standby cluster", so configured Patroni accordingly via postgres-operator, but right after the initial "pg_basebackup", Patroni incorrectly promotes itself as master and thus stops replicating, while creating new object on the database thus making the whole datadir unsuitable for another attempt.

**To Reproduce**
a) As per [official documentation](https://github.com/zalando/postgres-operator/blob/master/docs/reference/operator_parameters.md), install postgres-operator:
1. kubectl create -f manifests/operatorconfiguration.crd.yaml
2. kubectl create -f manifests/postgresql-operator-default-configuration.yaml
3. kubectl create -f manifests/operator-service-account-rbac.yaml
4. kubectl create -f manifests/postgres-operator.yaml
b) Create a standby cluster:
kubectl create -f manifests/standby-cluster.yaml

**Expected behavior**
The cluster should start, then create an initial backup from the old cluster (pg_basebackup: OK), then it should start actually following the old cluster via replication.

**Screenshots**
N/A

**Environment**
- Patroni version: registry.opensource.zalan.do/acid/spilo-12:1.6-p5
- PostgreSQL version: 12.4
- DCS (and its version): Kubernetes 1.17.12

**Patroni configuration file**
```

```

**patronictl show-config**
```
Please copy&paste the output of "patronictl show-config" command here
```

**Have you checked Patroni logs?**

```
FATAL: no pg_hba.conf entry for replication connection from host "127.0.0.1", user "standby", SSL off
2020-11-17 11:53:36,681 ERROR: Can not fetch local timeline and lsn from replication connection
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/init.py", line 735, in get_replica_timeline
with self.get_replication_connection_cursor(**self.config.local_replication_address) as cur:
File "/usr/lib/python3.6/contextlib.py", line 81, in enter
return next(self.gen)
File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/init.py", line 730, in get_replication_connection_cursor
with get_connection_cursor(**conn_kwargs) as cur:
File "/usr/lib/python3.6/contextlib.py", line 81, in enter
return next(self.gen)
File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/connection.py", line 43, in get_connection_cursor
with psycopg2.connect(**kwargs) as conn:
File "/usr/lib/python3/dist-packages/psycopg2/init.py", line 127, in connect
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL: password authentication failed for user "standby"
FATAL: no pg_hba.conf entry for replication connection from host "127.0.0.1", user "standby", SSL off
2020-11-17 11:53:36,733 INFO: promoted self to leader by acquiring session lock
2020-11-17 11:53:36,733 INFO: promoted self to leader by acquiring session lock
2020-11-17 11:53:36,734 INFO: Lock owner: exacto-timescaledb-0; I am exacto-timescaledb-0
server promoting
2020-11-17 11:53:36,734 INFO: Lock owner: exacto-timescaledb-0; I am exacto-timescaledb-0
server promoting
2020-11-17 11:53:36,738 INFO: cleared rewind state after becoming the leader
2020-11-17 11:53:36,738 INFO: cleared rewind state after becoming the leader
/scripts/on_role_change.sh: line 6: on_role_change: command not found
/scripts/on_role_change.sh: line 6: on_role_change: command not found
2020-11-17 11:53:36,746 INFO: Lock owner: exacto-timescaledb-0; I am exacto-timescaledb-0
2020-11-17 11:53:36,746 INFO: Lock owner: exacto-timescaledb-0; I am exacto-timescaledb-0
```

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.

**Additional context**
More details in the [issue](https://github.com/zalando/postgres-operator/issues/1220) I've initially opened on postgres-operator, but as it seems more closely related to Patroni, I'm duplicating it here.

**Comment by CyberDem0n** [comment]
The standby cluster feature in Patroni works correctly. The only reason why Patroni could decide to promote Postgres - when there is no stanby_cluster section in the DCS configuration, but you didn't show `patronictl show-config` output.
