### ISSUE TITLE
Usage of python-consul

### ISSUE THREAD

**Issue by wilfriedroset** [zalando/patroni#1810]
**Describe the bug**
When it comes to consul dcs, patroni leverage `python-consul`, as per [requirements.txt](https://github.com/zalando/patroni/blob/master/requirements.txt#L8). This library is inactive for [more than 2 years now](https://github.com/cablehead/python-consul/commits/master).

For several other usecases related to consul we have been using happily [python-consul2](https://github.com/poppyred/python-consul2) is actively maintained. Users starts moving away from `python-consul` and there is a PR to warn about it: https://github.com/hashicorp/consul/pull/9079

While working on the setup of patroni on consul with `python-consul2`, we have stumble upon the traceback below.
Everything works has expected with `python-consul`.

Before diving in the code I would like to have your thoughts about that. Do you have plan to move away from `python-consul`?

I can see several solutions:
* leave it as it is and warn about it in the documentation
* completely move away the unsupported version
* support both `python-consul` and `python-consul2` (for how long?)
* work with @poppyred to be able to use `python-consul2` as a drop-in replacement which works with patroni

**To Reproduce**
use patroni with python-consul2 instead of python-consul

**Expected behavior**
A working patroni just like with python-consul

**Environment**
- os: debian 9
- patroni version: 2.0.1 from pgdg
- postgresql version: 9.6.20 from pgdg
- python-consul: 0.7.1
- python-consul2: 0.1.1
- consul: 1.8.5

**Patroni configuration file**
```yml
consul:
  host: http://localhost:8500
  consistency: consistent
```

**Have you checked Patroni logs?**
```
Jan 07 15:58:52 redacted-hostname systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL.
Jan 07 15:58:52 redacted-hostname patroni[19400]: Traceback (most recent call last):
Jan 07 15:58:52 redacted-hostname patroni[19400]:   File "/usr/bin/patroni", line 11, in <module>
Jan 07 15:58:52 redacted-hostname patroni[19400]:     load_entry_point('patroni==2.0.1', 'console_scripts', 'patroni')()
Jan 07 15:58:52 redacted-hostname patroni[19400]:   File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 170, in main
Jan 07 15:58:52 redacted-hostname patroni[19400]:     return patroni_main()
Jan 07 15:58:52 redacted-hostname patroni[19400]:   File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 138, in patroni_main
Jan 07 15:58:52 redacted-hostname patroni[19400]:     abstract_main(Patroni, schema)
Jan 07 15:58:52 redacted-hostname patroni[19400]:   File "/usr/lib/python3/dist-packages/patroni/daemon.py", line 98, in abstract_main
Jan 07 15:58:52 redacted-hostname patroni[19400]:     controller = cls(config)
Jan 07 15:58:52 redacted-hostname patroni[19400]:   File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 29, in __init__
Jan 07 15:58:52 redacted-hostname patroni[19400]:     self.dcs = get_dcs(self.config)
Jan 07 15:58:52 redacted-hostname patroni[19400]:   File "/usr/lib/python3/dist-packages/patroni/dcs/__init__.py", line 92, in get_dcs
Jan 07 15:58:52 redacted-hostname patroni[19400]:     return item(config[name])
Jan 07 15:58:52 redacted-hostname patroni[19400]:   File "/usr/lib/python3/dist-packages/patroni/dcs/consul.py", line 215, in __init__
Jan 07 15:58:52 redacted-hostname patroni[19400]:     self._client = ConsulClient(**kwargs)
Jan 07 15:58:52 redacted-hostname patroni[19400]:   File "/usr/lib/python3/dist-packages/patroni/dcs/consul.py", line 127, in __init__
Jan 07 15:58:52 redacted-hostname patroni[19400]:     super(ConsulClient, self).__init__(*args, **kwargs)
Jan 07 15:58:52 redacted-hostname patroni[19400]:   File "/usr/lib/python3/dist-packages/consul/base.py", line 369, in __init__
Jan 07 15:58:52 redacted-hostname patroni[19400]:     self.http = self.http_connect(host,
Jan 07 15:58:52 redacted-hostname patroni[19400]: AttributeError: 'ConsulClient' object has no attribute 'http_connect'
```

**Have you checked PostgreSQL logs?**
Patroni does not start so there is nothing to see

**Have you tried to use GitHub issue search?**
Yes

**Comment by CyberDem0n** [comment]
It doesn't work as drop-in-replacement because the interface was changed: https://github.com/poppyred/python-consul2/commit/3083dd4e0e0f7d40ac487af16b941fbf780b3fb7#diff-2c1a3be98d45506c4de7f5aea36c66720d7c695758d5be70eaacc7c0023e16f7R71
They renamed the `connect()` method to the `http_connect()`, while Patroni only implements `connect()`.
There were really good reasons to not rely on the implementation of `consul/std.py`, based on the `requests` module but hack our own, based on pure `urllib3`.

Making it compatible shouldn't be as hard as adding yet another method to the [ConsulClient](https://github.com/zalando/patroni/blob/master/patroni/dcs/consul.py#L121):
```python
    def http_connect(self, *args, **kwargs):
        return self.connect(*args, **kwargs)
```

**Comment by wilfriedroset** [comment]
This could work with a little bit more work. connect variable is already used https://github.com/poppyred/python-consul2/commit/3083dd4e0e0f7d40ac487af16b941fbf780b3fb7#diff-87d94b41a52bb393bfca3dc4b47be3807560585a919ef66394f9fe6e20c216c2R343 in the same commit.
Therefore we end up with `object is not callable` 

```
Jan 08 16:31:55 redacted-hostname patroni[31363]: Traceback (most recent call last):
Jan 08 16:31:55 redacted-hostname patroni[31363]:   File "/usr/bin/patroni", line 11, in <module>
Jan 08 16:31:55 redacted-hostname patroni[31363]:     load_entry_point('patroni==2.0.1', 'console_scripts', 'patroni')()
Jan 08 16:31:55 redacted-hostname patroni[31363]:   File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 170, in main
Jan 08 16:31:55 redacted-hostname patroni[31363]:     return patroni_main()
Jan 08 16:31:55 redacted-hostname patroni[31363]:   File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 138, in patroni_main
Jan 08 16:31:55 redacted-hostname patroni[31363]:     abstract_main(Patroni, schema)
Jan 08 16:31:55 redacted-hostname patroni[31363]:   File "/usr/lib/python3/dist-packages/patroni/daemon.py", line 98, in abstract_main
Jan 08 16:31:55 redacted-hostname patroni[31363]:     controller = cls(config)
Jan 08 16:31:55 redacted-hostname patroni[31363]:   File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 29, in __init__
Jan 08 16:31:55 redacted-hostname patroni[31363]:     self.dcs = get_dcs(self.config)
Jan 08 16:31:55 redacted-hostname patroni[31363]:   File "/usr/lib/python3/dist-packages/patroni/dcs/__init__.py", line 92, in get_dcs
Jan 08 16:31:55 redacted-hostname patroni[31363]:     return item(config[name])
Jan 08 16:31:55 redacted-hostname patroni[31363]:   File "/usr/lib/python3/dist-packages/patroni/dcs/consul.py", line 218, in __init__
Jan 08 16:31:55 redacted-hostname patroni[31363]:     self._client = ConsulClient(**kwargs)
Jan 08 16:31:55 redacted-hostname patroni[31363]:   File "/usr/lib/python3/dist-packages/patroni/dcs/consul.py", line 127, in __init__
Jan 08 16:31:55 redacted-hostname patroni[31363]:     super(ConsulClient, self).__init__(*args, **kwargs)
Jan 08 16:31:55 redacted-hostname patroni[31363]:   File "/usr/lib/python3/dist-packages/consul/base.py", line 373, in __init__
Jan 08 16:31:55 redacted-hostname patroni[31363]:     **kwargs)
Jan 08 16:31:55 redacted-hostname patroni[31363]:   File "/usr/lib/python3/dist-packages/patroni/dcs/consul.py", line 140, in http_connect
Jan 08 16:31:55 redacted-hostname patroni[31363]:     return self.connect(*args, **kwargs)
Jan 08 16:31:55 redacted-hostname patroni[31363]: TypeError: 'Connect' object is not callable
Jan 08 16:31:55 redacted-hostname systemd[1]: patroni.service: Main process exited, code=exited, status=1/FAILURE
Jan 08 16:31:55 redacted-hostname systemd[1]: patroni.service: Failed with result 'exit-code'.
``` 

Which we can workaround a bit like so.
```diff
~ # diff -r -up /usr/lib/python3/dist-packages/patroni patroni
diff -r -up /usr/lib/python3/dist-packages/patroni/dcs/consul.py patroni/dcs/consul.py
--- /usr/lib/python3/dist-packages/patroni/dcs/consul.py        2020-10-01 15:18:53.000000000 +0200
+++ patroni/dcs/consul.py       2021-01-08 16:57:18.919403333 +0100
@@ -80,7 +80,7 @@ class HTTPClient(object):
                 raise InvalidSession(msg)
             else:
                 raise ConsulInternalError(msg)
-        return base.Response(response.status, response.headers, data)
+        return base.Response(response.status, response.headers, data, resp.read())

     def uri(self, path, params=None):
         return '{0}{1}{2}'.format(self.base_uri, path, params and '?' + urlencode(params) or '')
@@ -89,7 +89,7 @@ class HTTPClient(object):
         if method not in ('get', 'post', 'put', 'delete'):
             raise AttributeError("HTTPClient instance has no attribute '{0}'".format(method))

-        def wrapper(callback, path, params=None, data=''):
+        def wrapper(callback, path, params=None, data='', *args, **kwargs):
             # python-consul doesn't allow to specify ttl smaller then 10 seconds
             # because session_ttl_min defaults to 10s, so we have to do this ugly dirty hack...
             if method == 'put' and path == '/v1/session/create':
@@ -100,7 +100,7 @@ class HTTPClient(object):
                     data = data[:-1] + ', ' + ttl + '}'
             if isinstance(params, list):  # starting from v1.1.0 python-consul switched from `dict` to `list` for params
                 params = {k: v for k, v in params}
-            kwargs = {'retries': 0, 'preload_content': False, 'body': data}
+            kwargs.update({'retries': 0, 'preload_content': False, 'body': data})
             if method == 'get' and isinstance(params, dict) and 'index' in params:
                 timeout = float(params['wait'][:-1]) if 'wait' in params else 300
                 # According to the documentation a small random amount of additional wait time is added to the
@@ -126,7 +126,7 @@ class ConsulClient(base.Consul):
         self.token = kwargs.get('token')
         super(ConsulClient, self).__init__(*args, **kwargs)

-    def connect(self, *args, **kwargs):
+    def _connect(self, *args, **kwargs):
         kwargs.update(dict(zip(['host', 'port', 'scheme', 'verify'], args)))
         if self._cert:
             kwargs['cert'] = self._cert
@@ -136,6 +136,12 @@ class ConsulClient(base.Consul):
             kwargs['token'] = self.token
         return HTTPClient(**kwargs)

+    def connect(self, *args, **kwargs):
+        return self._connect(*args, **kwargs)
+
+    def http_connect(self, *args, **kwargs):
+        return self._connect(*args, **kwargs)
+
     def reload_config(self, config):
         self.http.token = self.token = config.get('token')
         self.consistency = config.get('consistency', 'default')
```

I need to work more on `base.Response`. the one from python-consul and python-consul2 does not expect the same number of argument:
* https://github.com/cablehead/python-consul/blob/master/consul/base.py#L165
* https://github.com/poppyred/python-consul2/blob/master/consul/base.py#L189
