### ISSUE TITLE
patroni can't identify initdb parameter

### ISSUE THREAD

**Issue by hunterhuang8810** [zalando/patroni#1857]
**Describe the bug**
I found when start patroni and initdb, when I add new parameter - wal-segsize: 128 , start patroni will failed.
same config file, when I remove   - wal-segsize: 128 line ,no problem.
so in patroni.yml initdb part,  - wal-segsize is not allowed? it's a postgres init db options.

  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums
  - wal-segsize: 128

---patroni log
2021-02-24 18:37:59,783 INFO: Selected new etcd server http://192.168.56.93:2379
2021-02-24 18:37:59,787 INFO: No PostgreSQL configuration items changed, nothing to reload.
2021-02-24 18:37:59,818 INFO: Lock owner: None; I am pg01
2021-02-24 18:37:59,824 INFO: trying to bootstrap a new cluster
2021-02-24 18:37:59,825 INFO: Lock owner: None; I am pg01
2021-02-24 18:37:59,825 INFO: not healthy enough for leader race
2021-02-24 18:37:59,828 INFO: bootstrap in progress
2021-02-24 18:37:59,828 ERROR: Exception during execution of long running task bootstrap
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/async_executor.py", line 97, in run
    wakeup = func(*args) if args else func()
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/bootstrap.py", line 292, in bootstrap
    return do_initialize(config.get(method)) and self._postgresql.config.append_pg_hba(pg_hba) \
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/bootstrap.py", line 66, in _initdb
    options = self.process_user_options('initdb', config or [], not_allowed_options, error_handler)
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/bootstrap.py", line 50, in process_user_options
    ' and value should be a string'.format(tool, opt[keys[0]]))
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/bootstrap.py", line 64, in error_handler
    raise Exception(e)
Exception: Error when parsing initdb key-value option 128: only one key-value is allowed and value should be a string
2021-02-24 18:37:59,830 INFO: removing initialize key after failed attempt to bootstrap the cluster
2021-02-24 18:37:59,833 INFO: renaming data directory to /home/service/var/pgdata_2021-02-24-18-37-59
2021-02-24 18:37:59,833 ERROR: Could not rename data directory /home/service/var/pgdata
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 930, in move_data_directory
    os.rename(self._data_dir, new_name)
PermissionError: [Errno 13] Permission denied: '/home/service/var/pgdata' -> '/home/service/var/pgdata_2021-02-24-18-37-59'
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 170, in main
    return patroni_main()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 138, in patroni_main
    abstract_main(Patroni, schema)
  File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 100, in abstract_main
    controller.run()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 108, in run
    super(Patroni, self).run()
  File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 59, in run
    self._run_cycle()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 111, in _run_cycle
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1452, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1346, in _run_cycle
    return self.post_bootstrap()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1242, in post_bootstrap
    self.cancel_initialization()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1235, in cancel_initialization
    raise PatroniFatalException('Failed to bootstrap cluster')
patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'

**To Reproduce**
Add below option in patroni config file initdb part:
  - wal-segsize: 128

**Expected behavior**
patroni startup success and initdb success with wal segment size 128MB

**Screenshots**

**Environment**
- Patroni version: 2.0.1
- PostgreSQL version: 12.5
- DCS (and its version): etcd 3.3.1

**Patroni configuration file**
only paste initdb part below:
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums
  - wal-segsize: 128

Please copy&paste your Patroni configuration file here
```

**patronictl show-config**
```
Please copy&paste the output of "patronictl show-config" command here
```

**Have you checked Patroni logs?**
2021-02-24 18:37:59,783 INFO: Selected new etcd server http://192.168.56.93:2379
2021-02-24 18:37:59,787 INFO: No PostgreSQL configuration items changed, nothing to reload.
2021-02-24 18:37:59,818 INFO: Lock owner: None; I am pg01
2021-02-24 18:37:59,824 INFO: trying to bootstrap a new cluster
2021-02-24 18:37:59,825 INFO: Lock owner: None; I am pg01
2021-02-24 18:37:59,825 INFO: not healthy enough for leader race
2021-02-24 18:37:59,828 INFO: bootstrap in progress
2021-02-24 18:37:59,828 ERROR: Exception during execution of long running task bootstrap
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/async_executor.py", line 97, in run
    wakeup = func(*args) if args else func()
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/bootstrap.py", line 292, in bootstrap
    return do_initialize(config.get(method)) and self._postgresql.config.append_pg_hba(pg_hba) \
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/bootstrap.py", line 66, in _initdb
    options = self.process_user_options('initdb', config or [], not_allowed_options, error_handler)
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/bootstrap.py", line 50, in process_user_options
    ' and value should be a string'.format(tool, opt[keys[0]]))
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/bootstrap.py", line 64, in error_handler
    raise Exception(e)
Exception: Error when parsing initdb key-value option 128: only one key-value is allowed and value should be a string
2021-02-24 18:37:59,830 INFO: removing initialize key after failed attempt to bootstrap the cluster
2021-02-24 18:37:59,833 INFO: renaming data directory to /home/service/var/pgdata_2021-02-24-18-37-59
2021-02-24 18:37:59,833 ERROR: Could not rename data directory /home/service/var/pgdata
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 930, in move_data_directory
    os.rename(self._data_dir, new_name)
PermissionError: [Errno 13] Permission denied: '/home/service/var/pgdata' -> '/home/service/var/pgdata_2021-02-24-18-37-59'
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 170, in main
    return patroni_main()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 138, in patroni_main
    abstract_main(Patroni, schema)
  File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 100, in abstract_main
    controller.run()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 108, in run
    super(Patroni, self).run()
  File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 59, in run
    self._run_cycle()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 111, in _run_cycle
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1452, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1346, in _run_cycle
    return self.post_bootstrap()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1242, in post_bootstrap
    self.cancel_initialization()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1235, in cancel_initialization
    raise PatroniFatalException('Failed to bootstrap cluster')
patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.


**Additional context**
Add any other context about the problem here.

**Comment by hunterhuang8810** [comment]
" - wal-segsize: 128" 
below text is screwed

**Comment by hunterhuang8810** [comment]
" - wal-segsize: 128 "
above text is screwed

**Comment by CyberDem0n** [comment]
```
Exception: Error when parsing initdb key-value option 128: only one key-value is allowed and value should be a string
```

The error is 100% clear, value must be a string, while you have integer.
`128` vs `"128"`

**Comment by hunterhuang8810** [comment]
I checked source code and solved the problem:

/usr/local/lib/python3.6/site-packages/patroni/postgresql/bootstrap.py", line 50
 elif isinstance(options, list):
            for opt in options:
                if isinstance(opt, string_types) and option_is_allowed(opt):
                    user_options.append('--{0}'.format(opt))
                elif isinstance(opt, dict):
                    keys = list(opt.keys())
                    if len(keys) != 1 or not isinstance(opt[keys[0]], string_types) or not option_is_allowed(keys[0]):
                        error_handler('Error when parsing {0} key-value option {1}: only one key-value is allowed'
                                      ' and value should be a string'.format(tool, opt[keys[0]]))

so I changed 128 to "128" , can solve this.
this is caused by parameter type, while for string value like UTF8, no need "
