### ISSUE TITLE
Database is not restored to recovery point (ignored recovery_target_time)

### ISSUE THREAD

**Issue by vasilievs** [zalando/patroni#1870]
**Describe the bug**
I tries to created | restore PITR backup for patroni cluster.
Cluster restored **latest state in wal files**, and not to the desired point (recovery_target_time)
base_backup 2021-03-04 16:27:03 
need to recovery 2021-03-04 16:32:20
clueter restored: 2021-03-04 16:32:20

**To Reproduce**
I set up a shared NFS folder for wal files (use archive_command).
```
  parameters:
    archive_mode: on
    archive_command: 'test ! -f /mnt/nfs_pg_backup/%f && cp %p /mnt/nfs_pg_backup/%f'

```
after that I made several transactions, switched the master.
Created base backup
`pg_basebackup -U replication -h localhost -D /mnt/pg_backup/base_backup/"$(date +%Y-%m-%d_%H-%M)" -Ft -Xf -Z7`

made a few more transactions, and run pg_switch_wal() and copied the wal files in difficult folder.
```
  PGPASSWORD=postgres psql -U postgres -h $HOSTNAME -c "select pg_switch_wal();"
  rsync /mnt/nfs_pg_backup/* $d
```

after that i tries to recovery patroni cluster to PITR.

delete existing data and cluster:
```
systemctl stop patroni
rm -rf /var/lib/pgsql/12/data/*
patronictl remove patroni
```
Add recovery conf on postgres section config patroni (not bootstap)
vi /etc/patroni/patroni.yml
```
        restore_command: 'cp /tmp/restore_point/2021-03-04_16/%f %p'
        recovery_target_time: '2021-03-04 16:32:20'
        recovery_target_inclusive: true

```
create recovery signal:
```
touch /var/lib/pgsql/12/data/recovery.signal
chown -R postgres:postgres /var/lib/pgsql/12/data/recovery.signal
```
and start patroni:
`systemctl start patroni`

Cluster restored **latest state in wal files**, and not to the desired point (recovery_target_time)
base_backup 2021-03-04 16:27:03 
need to recovery 2021-03-04 16:32:20
clueter restored: 2021-03-04 16:32:20

 in recovery_target_time i tried to set formats:
 UTC, timezone etc ( not results)

**Environment**
- Patroni version: patronictl version 1.6.5
- PostgreSQL: 12
- DCS (and its version): consul (Consul v1.8.0)

**Have you checked PostgreSQL logs?**
```
2021-03-09 16:27:31.937 MSK [5009] LOG:  database system was interrupted; **last known up at 2021-03-04 16:27:03 MSK**
2021-03-09 16:27:31.944 MSK [5010] FATAL:  the database system is starting up
2021-03-09 16:27:31.947 MSK [5011] FATAL:  the database system is starting up
2021-03-09 16:27:31.967 MSK [5013] FATAL:  the database system is starting up
2021-03-09 16:27:31.970 MSK [5014] FATAL:  the database system is starting up
2021-03-09 16:27:31.979 MSK [5009] LOG:  restored log file "0000000A.history" from archive
2021-03-09 16:27:31.983 MSK [5009] LOG:  restored log file "0000000B.history" from archive
cp: cannot stat ‘/tmp/restore_point/2021-03-04_16/0000000C.history’: No such file or directory
2021-03-09 16:27:31.987 MSK [5009] LOG:  entering standby mode
2021-03-09 16:27:31.991 MSK [5009] LOG:  restored log file "0000000B.history" from archive
2021-03-09 16:27:32.015 MSK [5009] LOG:  restored log file "00000009000000000000002F" from archive
2021-03-09 16:27:32.099 MSK [5009] LOG:  restored log file "00000009.history" from archive
2021-03-09 16:27:32.106 MSK [5009] LOG:  restored log file "0000000A.history" from archive
2021-03-09 16:27:32.112 MSK [5009] LOG:  redo starts at 0/2F000028
2021-03-09 16:27:32.114 MSK [5009] LOG:  consistent recovery state reached at 0/2F000100
2021-03-09 16:27:32.114 MSK [5006] LOG:  database system is ready to accept read only connections
2021-03-09 16:27:32.138 MSK [5009] LOG:  restored log file "000000090000000000000030" from archive
2021-03-09 16:27:32.219 MSK [5009] LOG:  restored log file "000000090000000000000031" from archive
2021-03-09 16:27:32.301 MSK [5009] LOG:  restored log file "000000090000000000000032" from archive
2021-03-09 16:27:32.384 MSK [5009] LOG:  restored log file "000000090000000000000033" from archive
2021-03-09 16:27:32.467 MSK [5009] LOG:  restored log file "0000000A0000000000000034" from archive
2021-03-09 16:27:32.550 MSK [5009] LOG:  restored log file "0000000A0000000000000035" from archive
2021-03-09 16:27:32.630 MSK [5009] LOG:  restored log file "0000000A0000000000000036" from archive
cp: cannot stat ‘/tmp/restore_point/2021-03-04_16/0000000B0000000000000037’: No such file or directory
cp: cannot stat ‘/tmp/restore_point/2021-03-04_16/0000000A0000000000000037’: No such file or directory
cp: cannot stat ‘/tmp/restore_point/2021-03-04_16/0000000C.history’: No such file or directory
cp: cannot stat ‘/tmp/restore_point/2021-03-04_16/0000000B0000000000000037’: No such file or directory
cp: cannot stat ‘/tmp/restore_point/2021-03-04_16/0000000A0000000000000037’: No such file or directory
cp: cannot stat ‘/tmp/restore_point/2021-03-04_16/0000000C.history’: No such file or directory
cp: cannot stat ‘/tmp/restore_point/2021-03-04_16/0000000B0000000000000037’: No such file or directory
cp: cannot stat ‘/tmp/restore_point/2021-03-04_16/0000000A0000000000000037’: No such file or directory
2021-03-09 16:27:33.067 MSK [5009] LOG:  received promote request
2021-03-09 16:27:33.067 MSK [5009] LOG:  redo done at 0/360001D0
2021-03-09 16:27:33.067 MSK [5009] LOG:  **last completed transaction was at log time 2021-03-04 16:36:20.539967+03**
2021-03-09 16:27:33.089 MSK [5009] LOG:  restored log file "0000000A0000000000000036" from archive
cp: cannot stat ‘/tmp/restore_point/2021-03-04_16/0000000C.history’: No such file or directory
2021-03-09 16:27:33.174 MSK [5009] LOG:  selected new timeline ID: 12
2021-03-09 16:27:33.247 MSK [5009] LOG:  archive recovery complete
```

**Comment by CyberDem0n** [comment]
> Add recovery conf on postgres section config patroni (not bootstrap)

All recovery settings that you put to the `postgresql.recovery_conf` are ignored, because they potentially could break replication.
PITR could be (and should be) performed with the [custom bootstrap](https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#bootstrap) feature.

**Comment by vasilievs** [comment]
> PITR could be (and should be) performed with the [custom bootstrap](https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#bootstrap) feature.

Thank you for your quick response

that is, it is assumed that in bootstrap, first the scripts use for the initial backup, then for the wal restore_command?

```
    method: restore_with_wal
    restore_with_wal:
        command: 'tar -xvf /mnt/pg_backup/base_backup/2021-03-04_16-27/base.tar.gz -C /var/lib/pgsql/12/data'
        keep_existing_recovery_conf: False
        no_params: False
        recovery_conf:
            recovery_target_action: promote
            recovery_target_time: '2021-03-04 16:32:20'
            restore_command: 'cp /tmp/restore_point/2021-03-04_16/%f %p'
```

**Comment by CyberDem0n** [comment]
Yes, something like this.
First, Patroni restores from the basebackup instead of running initdb and than starts postgres up with desired recovery_conf.

**Comment by vasilievs** [comment]
@CyberDem0n 
backup didn't restore.
initdb was commented, but same error

Error:
```
Mar 16 11:34:19 vsi1 patroni: 2021-03-16 11:34:19,097 INFO: Deregister service patroni/vsi1.vm.ru
Mar 16 11:34:19 vsi1 patroni: 2021-03-16 11:34:19,098 INFO: trying to bootstrap a new cluster
Mar 16 11:34:19 vsi1 patroni: 2021-03-16 11:34:19,100 INFO: Lock owner: None; I am vsi1.vm.ru
Mar 16 11:34:19 vsi1 patroni: 2021-03-16 11:34:19,101 INFO: not healthy enough for leader race
Mar 16 11:34:19 vsi1 patroni: 2021-03-16 11:34:19,103 INFO: bootstrap in progress
Mar 16 11:34:19 vsi1 patroni: 2021-03-16 11:34:19,103 INFO: Running custom bootstrap script: /tmp/restore.sh
Mar 16 11:34:19 vsi1 patroni: 2021-03-16 11:34:19,517 ERROR: Exception during execution of long running task bootstrap
Mar 16 11:34:19 vsi1 patroni: Traceback (most recent call last):
Mar 16 11:34:19 vsi1 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/async_executor.py", line 97, in run
Mar 16 11:34:19 vsi1 patroni: wakeup = func(*args) if args else func()
Mar 16 11:34:19 vsi1 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/bootstrap.py", line 290, in bootstrap
Mar 16 11:34:19 vsi1 patroni: return do_initialize(config.get(method)) and self._postgresql.config.append_pg_hba(pg_hba) \
Mar 16 11:34:19 vsi1 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/bootstrap.py", line 110, in _custom_bootstrap
Mar 16 11:34:19 vsi1 patroni: self._post_restore()
Mar 16 11:34:19 vsi1 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/bootstrap.py", line 94, in _post_restore
Mar 16 11:34:19 vsi1 patroni: trigger_file = self._postgresql.config.get('recovery_conf', {}).get(trigger_file) or 'promote'
Mar 16 11:34:19 vsi1 patroni: AttributeError: 'NoneType' object has no attribute 'get'
Mar 16 11:34:19 vsi1 patroni: 2021-03-16 11:34:19,522 INFO: removing initialize key after failed attempt to bootstrap the cluster
Mar 16 11:34:19 vsi1 patroni: 2021-03-16 11:34:19,528 INFO: renaming data directory to /var/lib/pgsql/12/data_2021-03-16-11-34-19
Mar 16 11:34:19 vsi1 patroni: 2021-03-16 11:34:19,571 INFO: Lock owner: None; I am vsi1.vm.ru
Mar 16 11:34:19 vsi1 patroni: Traceback (most recent call last):
Mar 16 11:34:19 vsi1 patroni: File "/usr/local/bin/patroni", line 11, in <module>
Mar 16 11:34:19 vsi1 patroni: sys.exit(main())
Mar 16 11:34:19 vsi1 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 235, in main
Mar 16 11:34:19 vsi1 patroni: return patroni_main()
Mar 16 11:34:19 vsi1 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 199, in patroni_main
Mar 16 11:34:19 vsi1 patroni: patroni.run()
Mar 16 11:34:19 vsi1 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 135, in run
Mar 16 11:34:19 vsi1 patroni: logger.info(self.ha.run_cycle())
Mar 16 11:34:19 vsi1 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1370, in run_cycle
Mar 16 11:34:19 vsi1 patroni: info = self._run_cycle()
Mar 16 11:34:19 vsi1 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1277, in _run_cycle
Mar 16 11:34:19 vsi1 patroni: return self.post_bootstrap()
Mar 16 11:34:19 vsi1 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1173, in post_bootstrap
Mar 16 11:34:19 vsi1 patroni: self.cancel_initialization()
Mar 16 11:34:19 vsi1 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1168, in cancel_initialization
Mar 16 11:34:19 vsi1 patroni: raise PatroniException('Failed to bootstrap cluster')
Mar 16 11:34:19 vsi1 patroni: patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'
Mar 16 11:34:19 vsi1 systemd: patroni.service: main process exited, code=exited, status=1/FAILURE
Mar 16 11:34:19 vsi1 systemd: Unit patroni.service entered failed state.
Mar 16 11:34:19 vsi1 systemd: patroni.service failed.
```

test bootstrap conf 
```
bootstrap:
  method: restore-with-wal
  restore-with-wal:
    command: /tmp/restore.sh
    keep_existing_recovery_conf: True
    no_params: False
    recovery_conf:
      restore_command: cp /tmp/restore_point/2021-03-04_16/%f %p
      recovery_target_timeline: latest
      recovery_target_action: promote
      recovery_target_time: '2021-03-04 16:32:20'
  # this section will be written into Consul:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    # the TTL to acquire the leader lock (in seconds).
    # Think of it as the length of time before initiation of the automatic failover process.
    # Default value: 30
    ttl: 30
    # loop_wait: the number of seconds the loop will sleep. Default value: 10
    loop_wait: 10
    # timeout for DCS and PostgreSQL operation retries (in seconds).
    # DCS or network issues shorter than this will not cause Patroni to demote the leader.
    # Default value: 10
    retry_timeout: 10
    # the maximum bytes a follower may lag to be able to participate in leader election.
    maximum_lag_on_failover: 1048576
    # the amount of time a master is allowed to recover from failures before failover is triggered (in seconds).
    # Default is 300 seconds.
    # When set to 0 failover is done immediately after a crash is detected if possible.
    # When using asynchronous replication a failover can cause lost transactions.
    # Worst case failover time for master failure is: loop_wait + master_start_timeout + loop_wait, unless master_start_timeout is zero,
    # in which case it's just loop_wait. Set the value according to your durability/availability tradeoff.
    master_start_timeout: 300
    synchronous_mode: false
    postgresql:
      recovery_conf:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 100
        max_locks_per_transaction: 64
        max_worker_processes: 8
        max_prepared_transactions: 0
        wal_level: hot_standby
        wal_log_hints: on
        track_commit_timestamp: off
  # some desired options for 'initdb'
  # Note: It needs to be a list (some options need values, others are switches)
#  initdb:
#  - encoding: UTF8
#  - data-checksums

  # Add following lines to pg_hba.conf after running 'initdb'
  # For kerberos gss based connectivity (discard @.*$)
  pg_hba:
    - host replication replication 0.0.0.0/0 md5
    - host all all 0.0.0.0/0 md5

  # Some additional users users which needs to be created after initializing new cluster
  # users:
  #   admin:
  #     password: admin
  #     options:
  #       - createrole
  #       - createdb
```

**Comment by CyberDem0n** [comment]
```yaml
bootstrap:
  dcs:
    postgresql:
      recovery_conf:
```

Either you need to remove it or make it a valid object.

**Comment by vasilievs** [comment]
@CyberDem0n  Thank you.
Restore to the specified point worked

**Comment by pySilver** [comment]
@vasilievs any chance you remember what was the issue? 

I have the following config and cannot make it work no matter what I do:

```
---
scope: &scope 'postgres'
name: &name 'node-db-2'
namespace: /service

consul:
  host: redacted
  port: 8500
  token: redacted
  register_service: true
  consistency: stale

restapi:
  listen: ':8008'
  connect_address: redacted:8008

bootstrap:
  dcs:
    ttl: 60
    loop_wait: &loop_wait 20
    retry_timeout: 30
    maximum_lag_on_failover: 33554432
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        archive_mode: "on"
        archive_timeout: 1800s
        archive_command: wal-g wal-push "%p" --config=/secrets/.walg.json
        wal_level: replica
        wal_keep_segments: 8
        wal_log_hints: "on"
        max_wal_senders: 5
        # 1 connection per 30 MB, at least 100, at most 1000
        # min(max(100, int(os_memory_mb/30)), 1000)
        max_connections: 400
        max_replication_slots: 5
        hot_standby: "on"
        tcp_keepalives_idle: 900
        tcp_keepalives_interval: 100
        log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
        log_checkpoints: 'on'
        log_lock_waits: 'on'
        log_min_duration_statement: 500
        log_autovacuum_min_duration: 0
        log_connections: 'on'
        log_disconnections: 'on'
        log_statement: 'ddl'
        log_temp_files: 0
        track_functions: all
        checkpoint_completion_target: 0.9
        autovacuum_max_workers: 5
        autovacuum_vacuum_scale_factor: 0.05
        autovacuum_analyze_scale_factor: 0.02
  method: clone_with_walg
  initdb:
    - data-checksums
    - encoding: UTF8
    - locale: en_US.UTF-8
  clone_with_walg:
    command: python3 /clone_with_s3.py --config "/secrets/.walg.json"
    keep_existing_recovery_conf: false
    recovery_conf:
      restore_command: wal-g wal-fetch "%f" "%p" --config=/secrets/.walg.json
      recovery_target_action: promote
      recovery_target_timeline: latest
      recovery_target_inclusive: true
      recovery_target_time: '2023-10-06 00:00:00'

postgresql:
  name: *name
  scope: *scope
  listen: '*:5432'
  connect_address: redacted:5432
  data_dir: /var/lib/postgresql/data/node
  pgpass: /var/lib/postgresql/data/node/.pgpass
  parameters:
    # # We take 1/4 of the memory, expressed in full MB's
    # '{}MB'.format(int(os_memory_mb/4))
    shared_buffers: 32GB
    effective_cache_size: 64GB
    maintenance_work_mem: 2GB
    wal_buffers: 16MB
    default_statistics_target: 100
    random_page_cost: 1.1
    effective_io_concurrency: 200
    work_mem: 83886kB
    min_wal_size: 1GB
    max_wal_size: 4GB
    shared_preload_libraries: 'pg_stat_statements'
  recovery_conf:
    restore_command: wal-g wal-fetch "%f" "%p" --config=/secrets/.walg.json
  authentication:
    superuser:
      username: postgres
      password: redacted
    replication:
      username: replicator
      password: redacted
    rewind:
      username: rewind
      password: redacted
  pg_hba:
    - local all all trust
    - host all all localhost trust
    # skipped for security reasons from the example
  create_replica_methods:
    - wal_g
    - basebackup
  wal_g:
    command: wal-g backup-fetch /var/lib/postgresql/data/node LATEST --config=/secrets/.walg.json
    no_master: 1
    no_params: true
  basebackup:
    max-rate: "100M"
    checkpoint: fast
```

Every time I start my docker image with Patroni it writes postgre config with an empty `recovery_target_time`

@CyberDem0n I'm sorry for bothering you with this necro-ticket I'm just loosing my mind already :) Can you please point me into right direction here?
