### ISSUE TITLE
While Restore large database into patroni cluster,Terminating automatically

### ISSUE THREAD

**Issue by Kumar6295** [zalando/patroni#1874]
Using 3 etcd nodes and 3 patroni nodes.
Now try to restore 211GB backup file new database, it is failing 

**Restore failure**
COPY 11917
COPY 11878
COPY 9447
COPY 9474
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
no connection to the server
connection to server was lost

**Patroni logs**

2021-03-10 13:23:44,510 ERROR: Request to server http://etcd-1:2379 failed: MaxRetryError('HTTPConnectionPool(host=\'etcd-1\', port=2379): Max retries exceeded with
url: /v2/keys/service/postgres/leader
(Caused by ReadTimeoutError("HTTPConnectionPool(host=\'etcd-1\', port=2379): Read timed out. (read timeout=19.999634612351656)"))')
2021-03-10 13:23:44,510 INFO: Reconnection allowed, looking for another server.
2021-03-10 13:23:44,510 INFO: Retrying on http://etcd-2:2379
2021-03-10 13:23:46,266 INFO: Selected new etcd server http://etcd-2:2379
2021-03-10 13:23:49,653 INFO: no action.  i am the leader with the lock
2021-03-10 13:24:09,484 INFO: Lock owner: pg02; I am pg02
2021-03-10 13:24:29,504 ERROR: Request to server http://etcd-2:2379 failed: MaxRetryError('HTTPConnectionPool(host=\'etcd-2\', port=2379): Max retries exceeded with
url:
 /v2/keys/service/postgres/leader (Caused by ReadTimeoutError("HTTPConnectionPool(host=\'etcd-2\', port=2379): Read timed out. (read timeout=19.999757790006697)"))')
2021-03-10 13:24:29,504 INFO: Reconnection allowed, looking for another server.
2021-03-10 13:24:29,504 INFO: Retrying on http://etcd-1:2379
2021-03-10 13:24:49,524 ERROR: Request to server http://etcd-1:2379 failed: MaxRetryError('HTTPConnectionPool(host=\'etcd-1\', port=2379): Max retries exceeded with
url: /v2/keys/service/postgres/leader (Caused by ReadTimeoutError("HTTPConnectionPool(host=\'etcd-1\', port=2379): Read timed out. (read timeout=19.999243905302137)"))')
2021-03-10 13:24:49,525 INFO: Reconnection allowed, looking for another server.
2021-03-10 13:24:49,525 INFO: Retrying on http://etcd-3:2379
2021-03-10 13:25:09,544 ERROR: Request to server http://etcd-3:2379 failed: MaxRetryError('HTTPConnectionPool(host=\'etcd-3\', port=2379): Max retries exceeded with
url: /v2/keys/service/postgres/leader (Caused by ReadTimeoutError("HTTPConnectionPool(host=\'etcd-3\', port=2379): Read timed out. (read timeout=19.998801677953452)"))')
2021-03-10 13:25:09,544 INFO: Reconnection allowed, looking for another server.
2021-03-10 13:25:09,545 ERROR:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/etcd.py", line 562, in wrapper
    retval = func(self, *args, **kwargs) is not None
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/etcd.py", line 673, in _update_leader
    return self.retry(self._client.write, self.leader_path, self._name, prevValue=self._name, ttl=self._ttl)
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/etcd.py", line 443, in retry
    return retry(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/patroni/utils.py", line 333, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/etcd/client.py", line 500, in write
    response = self.api_execute(path, method, params=params)
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/etcd.py", line 271, in api_execute
    raise ex
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/etcd.py", line 255, in api_execute
 raise ex
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/etcd.py", line 255, in api_execute
    response = self._do_http_request(retry, machines_cache, request_executor, method, path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/etcd.py", line 232, in _do_http_request
    raise etcd.EtcdConnectionFailed('No more machines in the cluster')
etcd.EtcdConnectionFailed: No more machines in the cluster
2021-03-10 13:25:09,546 ERROR: failed to update leader lock
2021-03-10 13:25:29,705 INFO: demoted self because failed to update leader lock in DCS
2021-03-10 13:25:29,707 WARNING: Loop time exceeded, rescheduling immediately.
2021-03-10 13:25:29,710 INFO: Lock owner: pg02; I am pg02
2021-03-10 13:25:29,998 INFO: closed patroni connection to the postgresql cluster
2021-03-10 13:25:31,682 INFO: updated leader lock during starting after demotion
2021-03-10 13:25:56,855 INFO: postmaster pid=1507660
2021-03-10 13:26:14,712 INFO: Lock owner: pg02; I am pg02
2021-03-10 13:26:34,733 ERROR: Request to server http://etcd-2:2379 failed: MaxRetryError('HTTPConnectionPool(host=\'etcd-2\', port=2379): Max retries exceeded with u>
2021-03-10 13:26:34,733 INFO: Reconnection allowed, looking for another server.
2021-03-10 13:26:34,734 INFO: Retrying on http://etcd-1:2379
2021-03-10 13:26:35,436 INFO: Selected new etcd server http://etcd-1:2379
2021-03-10 13:26:35,847 INFO: updated leader lock during starting after demotion
2021-03-10 13:26:35,870 INFO: Lock owner: pg02; I am pg02
2021-03-10 13:26:36,248 INFO: establishing a new patroni connection to the postgres cluster
2021-03-10 13:26:36,641 INFO: establishing a new patroni connection to the postgres cluster
2021-03-10 13:26:36,644 WARNING: Retry got exception: 'connection problems'
2021-03-10 13:26:37,152 INFO: PostgreSQL is still starting up, 234 seconds until timeout
2021-03-10 13:27:20,876 INFO: Lock owner: pg02; I am pg02
2021-03-10 13:27:21,790 INFO: establishing a new patroni connection to the postgres cluster
2021-03-10 13:27:21,934 INFO: establishing a new patroni connection to the postgres cluster
2021-03-10 13:27:21,936 WARNING: Retry got exception: 'connection problems'
2021-03-10 13:27:22,884 INFO: PostgreSQL is still starting up, 188 seconds until timeout
2021-03-10 13:27:41,720 WARNING: Exception happened during processing of request from 240.165.0.197:50428
2021-03-10 13:27:41,749 WARNING: Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.8/dist-packages/patroni/api.py", line 523, in handle_one_request
    BaseHTTPRequestHandler.handle_one_request(self)
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/local/lib/python3.8/dist-packages/patroni/api.py", line 148, in do_OPTIONS
    self.do_GET(write_status_code_only=True)
  File "/usr/local/lib/python3.8/dist-packages/patroni/api.py", line 143, in do_GET
    self._write_status_code_only(status_code)
  File "/usr/local/lib/python3.8/dist-packages/patroni/api.py", line 31, in _write_status_code_only
    self.wfile.write('{0} {1} {2}\r\n\r\n'.format(self.protocol_version, status_code, message).encode('utf-8'))
  File "/usr/lib/python3.8/socketserver.py", line 799, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer

2021-03-10 13:28:05,877 INFO: Lock owner: pg02; I am pg02
2021-03-10 13:28:05,878 INFO: establishing a new patroni connection to the postgres cluster
2021-03-10 13:28:13,418 INFO: promoted self to leader because i had the session lock
2021-03-10 13:28:13,426 INFO: cleared rewind state after becoming the leader
2021-03-10 13:28:26,528 INFO: Lock owner: pg02; I am pg02
2021-03-10 13:28:47,752 INFO: Selected new etcd server http://etcd-2:2379
2021-03-10 13:28:47,753 ERROR: Request to server http://etcd-1:2379 failed: MaxRetryError('HTTPConnectionPool(host=\'etcd-1\', port=2379): Max retries exceeded with url: >
2021-03-10 13:28:47,753 INFO: Reconnection allowed, looking for another server.
2021-03-10 13:28:47,753 ERROR:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 330, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='etcd-1', port=2379): Read timed out. (read timeout=19.99967013206333)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/etcd.py", line 210, in _do_http_request
    response = request_executor(method, base_uri + path, **kwargs)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 79, in request
    return self.request_encode_body(
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='etcd-1', port=2379): Max retries exceeded with url: /v2/keys/service/postgres/optime/leader (Caused by ReadTimeoutEr>

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/etcd.py", line 562, in wrapper
    retval = func(self, *args, **kwargs) is not None
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/etcd.py", line 669, in _write_leader_optime
    return self._client.set(self.leader_optime_path, last_operation)
  File "/usr/local/lib/python3.8/dist-packages/etcd/client.py", line 721, in set
    return self.write(key, value, ttl=ttl)
  File "/usr/local/lib/python3.8/dist-packages/etcd/client.py", line 500, in write
    response = self.api_execute(path, method, params=params)
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/etcd.py", line 255, in api_execute
    response = self._do_http_request(retry, machines_cache, request_executor, method, path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/etcd.py", line 229, in _do_http_request
    raise etcd.EtcdException('{0} {1} request failed'.format(method, path))
etcd.EtcdException: PUT /v2/keys/service/postgres/optime/leader request failed
2021-03-10 13:28:51,427 INFO: no action.  i am the leader with the lock
2021-03-10 13:29:11,525 INFO: Lock owner: pg02; I am pg02
2021-03-10 13:29:13,729 INFO: no action.  i am the leader with the lock
2021-03-10 13:29:56,526 INFO: Lock owner: pg02; I am pg02
2021-03-10 13:29:58,278 INFO: no action.  i am the leader with the lock
2021-03-10 13:30:41,525 INFO: Lock owner: pg02; I am pg02
2021-03-10 13:30:42,844 INFO: no action.  i am the leader with the lock

Again same patroni pg02 made as leader.
while above error happening,  rest of 2 node also restarting..

Before restore database TL count is 98,now it is 99

+ Cluster: postgres (69216231) ---+----+-----------+------------------+
| Member | Host          | Role    | State   | TL | Lag in MB | Tags             |
+--------+---------------+---------+---------+----+-----------+------------------+
| pg01   | ip1           | Replica | running | 99 |         0 |                  |
| pg02   | ip2           | Leader  | running | 99 |           |                  |
| pg03   | ip3           | Replica | running | 99 |         0 | nofailover: true |
+--------+---------------+---------+---------+----+-----------+------------------+

Any configuration need to change in etcd or patroni??

**Comment by Kumar6295** [comment]
etcd cluster is working fine.

**Comment by CyberDem0n** [comment]
> etcd cluster is working fine.

Well, Patroni logs clearly show that etcd is not accessible.

**Comment by Kumar6295** [comment]
ok.
Need to change any configuration in etcd conf file.
Can you guide,What need to change..below etcd conf file details 

[Member]
#ETCD_CORS=""
ETCD_DATA_DIR="/var/lib/etcd/etcd-2.etcd"
#ETCD_WAL_DIR=""
ETCD_LISTEN_PEER_URLS="http://etcd-2-ip:2380"
ETCD_LISTEN_CLIENT_URLS="http://127.0.0.1:2379,http://etcd-2-ip:2379"
#ETCD_MAX_SNAPSHOTS="5"
#ETCD_MAX_WALS="5"
ETCD_NAME="etcd-2"
ETCD_SNAPSHOT_COUNT="5000"
ETCD_HEARTBEAT_INTERVAL="800"
ETCD_ELECTION_TIMEOUT="9000"
ETCD_QUOTA_BACKEND_BYTES="8589934592"
ETCD_MAX_REQUEST_BYTES="99728640"
#ETCD_GRPC_KEEPALIVE_MIN_TIME="5s"
#ETCD_GRPC_KEEPALIVE_INTERVAL="2h0m0s"
ETCD_GRPC_KEEPALIVE_TIMEOUT="60s"
#
#[Clustering]
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://etcd-2:2380"
ETCD_ADVERTISE_CLIENT_URLS="http://etcd-2-ip:2379"
#ETCD_DISCOVERY=""
#ETCD_DISCOVERY_FALLBACK="proxy"
#ETCD_DISCOVERY_PROXY=""
#ETCD_DISCOVERY_SRV=""
ETCD_INITIAL_CLUSTER="etcd-1=http://etcd-1-ip:2380,etcd-2=http://etcd-2-ip:2380,etcd-3=http://etcd-3-ip:2380"
ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster"
ETCD_INITIAL_CLUSTER_STATE="new"
#ETCD_STRICT_RECONFIG_CHECK="true"
ETCD_ENABLE_V2="true"
#
#[Proxy]
#ETCD_PROXY="off"
#ETCD_PROXY_FAILURE_WAIT="5000"
#ETCD_PROXY_REFRESH_INTERVAL="30000"
#ETCD_PROXY_DIAL_TIMEOUT="1000"
#ETCD_PROXY_WRITE_TIMEOUT="5000"
#ETCD_PROXY_READ_TIMEOUT="0"
#
#[Security]
#ETCD_CERT_FILE=""
#ETCD_KEY_FILE=""
#ETCD_CLIENT_CERT_AUTH="false"
#ETCD_TRUSTED_CA_FILE=""
#ETCD_AUTO_TLS="false"
#ETCD_PEER_CERT_FILE=""
#ETCD_PEER_KEY_FILE=""
#ETCD_PEER_CLIENT_CERT_AUTH="false"
#ETCD_PEER_TRUSTED_CA_FILE=""
#ETCD_PEER_AUTO_TLS="false"
#
#[Logging]
#ETCD_DEBUG="false"
#ETCD_LOG_PACKAGE_LEVELS=""
#ETCD_LOG_OUTPUT="default"
#
#[Unsafe]
#ETCD_FORCE_NEW_CLUSTER="false"
#
#[Version]
#ETCD_VERSION="false"
#ETCD_AUTO_COMPACTION_RETENTION="0"
#
#[Profiling]
#ETCD_ENABLE_PPROF="false"
#ETCD_METRICS="basic"
#
#[Auth]
#ETCD_AUTH_TOKEN="simple"

**Comment by CyberDem0n** [comment]
> Can you guide,

This is neither a support channel for etcd nor I am your private consultant.
