### ISSUE TITLE
Patroni SSL - ConnectionResetError

### ISSUE THREAD

**Issue by exc1te** [zalando/patroni#1877]
Hello,
I'm testing Patroni cluster with full SSL support: etcd, patroni, haproxy and postgresql.
I think I faced with same issue like #857 
After I stopped Haproxy the exception was gone.
Does it was a bug or expected behavior?

Environment:
Ubuntu 20.04
Patroni 2.0.2
Postgresql 13.2
Etcd 3.2.26
Haproxy 2.3.6

Patroni config:
```
PATRONI_RESTAPI_CONNECT_ADDRESS=ubuntu1.domain.com:8080
PATRONI_RESTAPI_LISTEN=0.0.0.0:8080
PATRONI_RESTAPI_USERNAME=patroni
PATRONI_RESTAPI_PASSWORD=patroni
PATRONI_RESTAPI_CERTFILE=/etc/ssl/certs/domain.com.pem
PATRONI_RESTAPI_KEYFILE=/etc/ssl/private/domain.com.key
PATRONI_RESTAPI_CAFILE=/etc/ssl/certs/ca_domain.com.pem
PATRONI_RESTAPI_CIPHERS="ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:!NULL:!SSLv1:!SSLv2:!SSLv3:!TLSv1:!TLSv1.1"
PATRONI_RESTAPI_VERIFY_CLIENT=none
```

Haproxy config:
````
listen master
    bind *:5000
    option httpchk GET /master
    option tcpka
    http-check expect status 200
    default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions ca-file /etc/ssl/certs/ca_domain.com.pem
    server postgresql_ubuntu1_5432 192.168.58.220:5432 check check-ssl port 8080
    server postgresql_ubuntu2_5432 192.168.58.221:5432 check check-ssl port 8080
    server postgresql_ubuntu3_5432 192.168.58.222:5432 check check-ssl port 8080
````

Patroni exception (on all hosts):
````
2021-03-11 13:48:07,004 WARNING: Exception happened during processing of request from 192.168.58.222:55050
2021-03-11 13:48:07,005 WARNING: Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/opt/venv/patroni-2.0.2/lib/python3.8/site-packages/patroni/api.py", line 524, in handle_one_request
    BaseHTTPRequestHandler.handle_one_request(self)
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/opt/venv/patroni-2.0.2/lib/python3.8/site-packages/patroni/api.py", line 146, in do_GET
    self._write_status_response(status_code, response)
  File "/opt/venv/patroni-2.0.2/lib/python3.8/site-packages/patroni/api.py", line 89, in _write_status_response
    self._write_json_response(status_code, response)
  File "/opt/venv/patroni-2.0.2/lib/python3.8/site-packages/patroni/api.py", line 48, in _write_json_response
    self._write_response(status_code, json.dumps(response), content_type='application/json')
  File "/opt/venv/patroni-2.0.2/lib/python3.8/site-packages/patroni/api.py", line 45, in _write_response
    self.wfile.write(body.encode('utf-8'))
  File "/usr/lib/python3.8/socketserver.py", line 799, in write
    self._sock.sendall(b)
  File "/usr/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
ConnectionResetError: [Errno 104] Connection reset by peer
````

**Comment by CyberDem0n** [comment]
The exception means that the remote side (HAProxy) closed the connection without fully reading a response.
It probably cares only about the HTTP status code. I guess using `option httpchk GET /master` should fix it.

**Comment by exc1te** [comment]
Thank you for response, but I'm already has a
````
option httpchk GET /master
````
in Haproxy configuration, or I misunderstanding something?

**Comment by CyberDem0n** [comment]
Oh, sorry, I meant `option httpchk OPTIONS /master`.

**Comment by exc1te** [comment]
Thanks
