### ISSUE TITLE
local_replication_address is forced to localhost and conflicts with sslmode=verify-full

### ISSUE THREAD

**Issue by edysli** [zalando/patroni#1884]
## Description
New replicas bootstrap but don't report their replication status (timeline, LSN). The following error is reported in Patroni's log:
```
Mar 16 15:19:45 centos-replica1 patroni[4081]: 2021-03-16 15:19:45,623 INFO: no action.  i am a secondary and i am following a leader
Mar 16 15:19:55 centos-replica1 patroni[4081]: 2021-03-16 15:19:55,456 INFO: Lock owner: centos-primary; I am centos-replica1
Mar 16 15:19:55 centos-replica1 patroni[4081]: 2021-03-16 15:19:55,456 INFO: does not have lock
Mar 16 15:19:55 centos-replica1 patroni[4081]: 2021-03-16 15:19:55,478 ERROR: Can not fetch local timeline and lsn from replication connection
Mar 16 15:19:55 centos-replica1 patroni[4081]: Traceback (most recent call last):
Mar 16 15:19:55 centos-replica1 patroni[4081]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 737, in get_replica_timeline
Mar 16 15:19:55 centos-replica1 patroni[4081]: with self.get_replication_connection_cursor(**self.config.local_replication_address) as cur:
Mar 16 15:19:55 centos-replica1 patroni[4081]: File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
Mar 16 15:19:55 centos-replica1 patroni[4081]: return next(self.gen)
Mar 16 15:19:55 centos-replica1 patroni[4081]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 732, in get_replication_connection_cursor
Mar 16 15:19:55 centos-replica1 patroni[4081]: with get_connection_cursor(**conn_kwargs) as cur:
Mar 16 15:19:55 centos-replica1 patroni[4081]: File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
Mar 16 15:19:55 centos-replica1 patroni[4081]: return next(self.gen)
Mar 16 15:19:55 centos-replica1 patroni[4081]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 43, in get_connection_cursor
Mar 16 15:19:55 centos-replica1 patroni[4081]: with psycopg2.connect(**kwargs) as conn:
Mar 16 15:19:55 centos-replica1 patroni[4081]: File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
Mar 16 15:19:55 centos-replica1 patroni[4081]: conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Mar 16 15:19:55 centos-replica1 patroni[4081]: psycopg2.OperationalError: server certificate for "centos-replica1" does not match host name "localhost"
Mar 16 15:19:55 centos-replica1 patroni[4081]: 2021-03-16 15:19:55,486 INFO: no action.  i am a secondary and i am following a leader
```
Tracing this in the code, variable `local_replication_address` is set in [postgresql/config.py](https://github.com/zalando/patroni/blob/583fccfb34a1b4e6de3a80a22997f1ea7b5478bc/patroni/postgresql/config.py#L893) in function `resolve_connection_addresses()` regardless of whether UNIX sockets are in use or not, taking its value from what function `_get_tcp_local_address()` returns:

```python
def resolve_connection_addresses(self):
    //...
    tcp_local_address = self._get_tcp_local_address()
    //...
    self.local_replication_address = {'host': tcp_local_address, 'port': port}
```
[Function `_get_tcp_local_address()`](https://github.com/zalando/patroni/blob/583fccfb34a1b4e6de3a80a22997f1ea7b5478bc/patroni/postgresql/config.py#L851) has a hardcoded preference for localhost and ignores any other address or hostname present in `listen_addresses` whenever the latter contains '*', '0.0.0.0', '127.0.0.1', or 'localhost'.

 1. This directly contradicts the [documentation for `postgresql.listen`](https://patroni.readthedocs.io/en/latest/SETTINGS.html#postgresql):

    > Patroni will use the first address from this list to establish local connections to the PostgreSQL node.

 2. It also causes a TLS verification failure because the certificate used by PostrgreSQL does not contains the name "localhost". *This cannot work*, no CA will issue you a server certificate with the name "localhost", either as CN or as subjectAlternativeNames.

## To Reproduce
- Configure a replication user with `sslmode: 'verify-full'` under `postgresql.authentication.replication`.
- Configure `postgresql.use_unix_socket` to true.
- Bootstrap a replica.

## Expected behaviour
The local replication connection uses UNIX sockets when `postgresql.use_unix_socket` is true. Failing that, it uses the first configured address from `postgresql.listen` [as documented](https://patroni.readthedocs.io/en/latest/SETTINGS.html#postgresql). TLS validation succeeds when a node connects to itself using its own name (i.e. *not* localhost).

## Screenshots
`patronictl list` doesn't show a timeline for replicas:
```
$ sudo -u postgres /usr/local/bin/patronictl --config-file /usr/local/etc/patroni.yaml list
+ Cluster: patroni-default-cluster-name (6940250319954542779) -----------+
| Member          | Host            | Role    | State   | TL | Lag in MB |
+-----------------+-----------------+---------+---------+----+-----------+
| centos-primary  | centos-primary  | Leader  | running |  1 |           |
| centos-replica1 | centos-replica1 | Replica | running |    |         0 |
| centos-replica2 | centos-replica2 | Replica | running |    |         0 |
+-----------------+-----------------+---------+---------+----+-----------+
```

## Environment
- Patroni version: 2.0.2
- PostgreSQL version: 12.6
- DCS (and its version): Consul 1.9.4
- OS: CentOS 7

## Patroni configuration file
```yaml
scope: 'patroni-default-cluster-name'
name: 'centos-replica1'

restapi:
  listen: '[::]:8008'
  connect_address: 'centos-replica1:8008'

ctl:
  insecure: true

consul:
  url: 'http://192.168.121.1:8500/'

bootstrap:
  dcs:
    loop_wait: 10
    ttl: 30
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        listen_addresses: '*'
        port: 5432
        password_encryption: 'scram-sha-256'
        wal_level: 'replica'
        hot_standby: 'on'
        hot_standby_feedback: 'on'
        max_wal_senders: 5
        max_replication_slots: 5

  initdb:
    - encoding: 'UTF-8'
    - locale: 'en_US.UTF-8'
    - lc-monetary: 'en_DK.UTF-8'
    - lc-numeric: 'en_DK.UTF-8'
    - lc-time: 'en_DK.UTF-8'
    - 'data-checksums'
    - 'allow-group-access'
    - auth-local: 'peer'
    - auth-host: 'scram-sha-256' 

  pg_hba:
    - 'host all postgres all reject'
    - 'hostssl replication replicator samenet scram-sha-256'
    - 'local all all peer'
    - 'host all all samehost scram-sha-256'
    - 'hostssl all all all scram-sha-256'

postgresql:
  listen: 'centos-replica1,*:5432'
  connect_address: 'centos-replica1:5432'
  data_dir: '/var/lib/pgsql/12/data'
  bin_dir: '/usr/pgsql-12/bin'
  config_dir: '/var/lib/pgsql/12/data'
  use_unix_socket: true
  use_pg_rewind: true
  pgpass: '/var/lib/pgsql/.pgpass'
  authentication:
    replication:
      username: 'replicator'
      password: 'password1'
      sslmode: 'verify-full'
    superuser:
      username: 'postgres'
      password: 'password2'
      sslmode: 'verify-full'
    rewind:  # Has no effect on postgres 10 and lower
      username: 'rewinder'
      password: 'password3'
      sslmode: 'verify-full'
  parameters:
    unix_socket_directories: '/run/postgresql'
    ssl: 'on'
    ssl_cert_file: '/etc/pki/tls/certs/postgresql.crt'
    ssl_key_file: '/etc/pki/tls/private/postgresql.key'
    ssl_ciphers: 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384'
    ssl_prefer_server_ciphers: 'on'
  pg_hba:
    - 'host all postgres all reject'
    - 'hostssl replication replicator samenet scram-sha-256'
    - 'local all all peer'
    - 'host all all samehost scram-sha-256'
    - 'hostssl all all all scram-sha-256'
    
watchdog:
  mode: 'off'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

## patronictl show-config
```yaml
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    hot_standby: 'on'
    hot_standby_feedback: 'on'
    listen_addresses: '*'
    max_replication_slots: 5
    max_wal_senders: 5
    password_encryption: scram-sha-256
    port: 5432
    wal_level: replica
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
ttl: 30
```

## Have you checked Patroni logs?
```
Mar 16 15:19:45 centos-replica1 patroni[4081]: 2021-03-16 15:19:45,623 INFO: no action.  i am a secondary and i am following a leader
Mar 16 15:19:55 centos-replica1 patroni[4081]: 2021-03-16 15:19:55,456 INFO: Lock owner: centos-primary; I am centos-replica1
Mar 16 15:19:55 centos-replica1 patroni[4081]: 2021-03-16 15:19:55,456 INFO: does not have lock
Mar 16 15:19:55 centos-replica1 patroni[4081]: 2021-03-16 15:19:55,478 ERROR: Can not fetch local timeline and lsn from replication connection
Mar 16 15:19:55 centos-replica1 patroni[4081]: Traceback (most recent call last):
Mar 16 15:19:55 centos-replica1 patroni[4081]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 737, in get_replica_timeline
Mar 16 15:19:55 centos-replica1 patroni[4081]: with self.get_replication_connection_cursor(**self.config.local_replication_address) as cur:
Mar 16 15:19:55 centos-replica1 patroni[4081]: File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
Mar 16 15:19:55 centos-replica1 patroni[4081]: return next(self.gen)
Mar 16 15:19:55 centos-replica1 patroni[4081]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 732, in get_replication_connection_cursor
Mar 16 15:19:55 centos-replica1 patroni[4081]: with get_connection_cursor(**conn_kwargs) as cur:
Mar 16 15:19:55 centos-replica1 patroni[4081]: File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
Mar 16 15:19:55 centos-replica1 patroni[4081]: return next(self.gen)
Mar 16 15:19:55 centos-replica1 patroni[4081]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 43, in get_connection_cursor
Mar 16 15:19:55 centos-replica1 patroni[4081]: with psycopg2.connect(**kwargs) as conn:
Mar 16 15:19:55 centos-replica1 patroni[4081]: File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
Mar 16 15:19:55 centos-replica1 patroni[4081]: conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Mar 16 15:19:55 centos-replica1 patroni[4081]: psycopg2.OperationalError: server certificate for "centos-replica1" does not match host name "localhost"
Mar 16 15:19:55 centos-replica1 patroni[4081]: 2021-03-16 15:19:55,486 INFO: no action.  i am a secondary and i am following a leader
```

## Have you checked PostgreSQL logs?
no

## Have you tried to use GitHub issue search?
Yes, no matches for "local_replication_address"

**Comment by CyberDem0n** [comment]
You probably should look at (and also test it) https://github.com/zalando/patroni/pull/1865.

**Comment by edysli** [comment]
#1865 indeed addresses the UNIX socket part of the bug, but leaves `_get_tcp_local_address()` intact so TLS connections are still broken.

I want the replication connections between nodes to be properly protected with TLS. Using TLS when connecting to the same machine makes little sense, but Patroni's configuration under `postgresql.authentication` doesn't distinguish those two cases.

**Comment by CyberDem0n** [comment]
If you enable unix sockets for replication connections Patroni will not even try connecting to the localhost, i.e. `_get_tcp_local_address()` will not have any effect.

Just try it, apply the patch and add `postgresql.use_unix_socket_repl: true` to the config (maybe pg_hba should be also adjusted to allow replication connections via the unix socket), and the exception will go away.

**Comment by edysli** [comment]
I tried with the patch and it apparently fixes the local replication connection issue using `postgresql.use_unix_socket_repl: true`. :smiley:  I indeed had to add a pg_hba rule `local replication replicator scram-sha-256` to allow those connections. `patronictl list` now shows a complete output:
```
$ sudo -u postgres /usr/local/bin/patronictl -c /usr/local/etc/patroni.yaml list
+ Cluster: patroni-default-cluster-name (6940250319954542779) -----------+
| Member          | Host            | Role    | State   | TL | Lag in MB |
+-----------------+-----------------+---------+---------+----+-----------+
| centos-primary  | centos-primary  | Leader  | running |  3 |           |
| centos-replica1 | centos-replica1 | Replica | running |  3 |         0 |
| centos-replica2 | centos-replica2 | Replica | running |  3 |         0 |
+-----------------+-----------------+---------+---------+----+-----------+
```

I still think the hardcoded preference for localhost in `_get_tcp_local_address()` is misguided though. Do you remember why it was introduced?

**Comment by CyberDem0n** [comment]
> Do you remember why it was introduced?

It is not always that the `postgresql.connect_address` is matching with the address of the environment where we run. For example it could be that we run in the docker container. From the outside were are available under the IP which is different from the IP inside. I felt that is safer to rely on loopback, and hope that pg_hba.conf most likely would allow either `trust` or `peer`.
Also, back then there was no way to use client certificates, therefore the problem you currently facing didn't exist yet.
