### ISSUE TITLE
Patroni crashes when pg_hba contains comment lines

### ISSUE THREAD

**Issue by pehrsoderman** [zalando/patroni#1920]
**Describe the bug**
Adding a comment to the pg_hba field causes a crash

**To Reproduce**
Create a configuration.yml with something like this: 

```
postgres:
  pg_hba:
        - #this is a comment
        - local   all             postgres                                peer
```
Start patroni. You will get a crash that looks somewhat like this: 
```
Traceback (most recent call last):
  File "/usr/bin/patroni", line 11, in <module>
    load_entry_point('patroni==1.6.4', 'console_scripts', 'patroni')()
  File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 224, in main
    return patroni_main()
  File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 186, in patroni_main
    patroni = Patroni(conf)
  File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 35, in __init__
    self.postgresql = Postgresql(self.config['postgresql'])
  File "/usr/lib/python3/dist-packages/patroni/postgresql/__init__.py", line 100, in __init__
    hba_saved = self.config.replace_pg_hba()
  File "/usr/lib/python3/dist-packages/patroni/postgresql/config.py", line 473, in replace_pg_hba
    f.writelines(self._config['pg_hba'])
  File "/usr/lib/python3/dist-packages/patroni/postgresql/config.py", line 245, in writelines
    self.writeline(line)
  File "/usr/lib/python3/dist-packages/patroni/postgresql/config.py", line 240, in writeline
    self._fd.write(line)
TypeError: write() argument must be str, not None

```
The reason is that the config file is converted to a yaml array of [- null - "local   all             postgres                                peer"], which in turn is interpreted as None in python.

**Expected behavior**
Either strip out the commented lines, or include the comments in the written pg_hba file. Patroni should not crash and refuse to start.

**Screenshots**
NA

**Environment**
- Patroni version: 1.6.4
- PostgreSQL version: 12.6
- DCS (and its version): etcd 3.2.26

**Patroni configuration file**
```
postgres:
  pg_hba:
        - #this is a comment
        - local   all             postgres                                peer
```

**patronictl show-config**
I do not have a relevant environment to reproduce at this time. 

**Have you checked Patroni logs?**
```
pehrs@backup:/etc/patroni$ sudo -u postgres patroni 12-main.yml 
2021-04-23 00:14:28,048 INFO: Selected new etcd server https://backup.scrool.se:2379
2021-04-23 00:14:28,112 INFO: No PostgreSQL configuration items changed, nothing to reload.
2021-04-23 00:14:28,127 INFO: establishing a new patroni connection to the postgres cluster
Traceback (most recent call last):
  File "/usr/bin/patroni", line 11, in <module>
    load_entry_point('patroni==1.6.4', 'console_scripts', 'patroni')()
  File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 224, in main
    return patroni_main()
  File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 186, in patroni_main
    patroni = Patroni(conf)
  File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 35, in __init__
    self.postgresql = Postgresql(self.config['postgresql'])
  File "/usr/lib/python3/dist-packages/patroni/postgresql/__init__.py", line 100, in __init__
    hba_saved = self.config.replace_pg_hba()
  File "/usr/lib/python3/dist-packages/patroni/postgresql/config.py", line 473, in replace_pg_hba
    f.writelines(self._config['pg_hba'])
  File "/usr/lib/python3/dist-packages/patroni/postgresql/config.py", line 245, in writelines
    self.writeline(line)
  File "/usr/lib/python3/dist-packages/patroni/postgresql/config.py", line 240, in writeline
    self._fd.write(line)
TypeError: write() argument must be str, not None
```

**Have you checked PostgreSQL logs?**
Not relevant

**Have you tried to use GitHub issue search?**
Yes, and did not find anything relevant. 

**Additional context**
N/A

**Comment by CyberDem0n** [comment]
> The reason is that the config file is converted to a yaml array of [- null - "local all postgres peer"], which in turn is interpreted as None in python
Expected behavior
Either strip out the commented lines, or include the comments in the written pg_hba file. Patroni should not crash and refuse to start.

Well, you correctly noticed that commented line is parsed as null. There is no way of extracting the comment from yaml.
Items of pg_hba array are supposed to be strings.

**Comment by pehrsoderman** [comment]
@CyberDem0n A custom yaml parser might be a but out of scope here. ;) But just making sure Patroni does not crash would be a good start. Either by stripping out the null values when reading, or before writing.

**Comment by CyberDem0n** [comment]
> just making sure Patroni does not crash would be a good start. Either by stripping out the null values when reading, or before writing.

Sure, but actually it should be extended to anything but strings.
Do you want to create a PR doing that?
