### ISSUE TITLE
Raft exception encountered during debugging

### ISSUE THREAD

**Issue by cobolbaby** [zalando/patroni#1975]
**Describe the bug**

I encountered the exception as below when debugging under windows. 

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\itc200102\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 806, in move
    os.rename(src, real_dst)
OSError: [WinError 87] 参数错误。: 'E:\\work\\patroni2\\127.0.0.1:2223.journal.meta.tmp' -> 'E:\\work\\patroni2\\127.0.0.1:2223.journal.meta'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\itc200102\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\itc200102\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\itc200102\AppData\Local\Programs\Python\Python39\lib\site-packages\pysyncobj\syncobj.py", line 520, in _autoTickThread
    self._onTick(self.__conf.autoTickPeriod)
  File "E:\work\patroni源码\patroni\patroni\dcs\raft.py", line 252, in _onTick
    super(KVStoreTTL, self)._onTick(timeToWait)
  File "C:\Users\itc200102\AppData\Local\Programs\Python\Python39\lib\site-packages\pysyncobj\syncobj.py", line 555, in _onTick
    self.__raftLog.onOneSecondTimer()
  File "C:\Users\itc200102\AppData\Local\Programs\Python\Python39\lib\site-packages\pysyncobj\journal.py", line 251, in onOneSecondTimer
    self.__metaStorer.storeMeta(self.__meta)
  File "C:\Users\itc200102\AppData\Local\Programs\Python\Python39\lib\site-packages\pysyncobj\journal.py", line 142, in storeMeta
    shutil.move(self.__path + '.tmp', self.__path)
  File "C:\Users\itc200102\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 820, in move
    copy_function(src, real_dst)
  File "C:\Users\itc200102\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\itc200102\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 244, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: 'E:\\work\\patroni2\\127.0.0.1:2223.journal.meta.tmp' and 'E:\\work\\patroni2\\127.0.0.1:2223.journal.meta' are the same file
```

**To Reproduce**

- postgres1.yml

```yml
...

raft:
 data_dir: E:\work\patroni1
 self_addr: 127.0.0.1:2222
 bind_addr: 0.0.0.0:2222
 partner_addrs:
 - 127.0.0.1:2223
 - 127.0.0.1:2224

...
```

- postgres2.yml

```yml
...

raft:
 data_dir: E:\work\patroni2
 self_addr: 127.0.0.1:2223
 bind_addr: 0.0.0.0:2223
 partner_addrs:
 - 127.0.0.1:2222
 - 127.0.0.1:2224

...
```

- postgres3.yml

```yml
...

raft:
 data_dir: E:\work\patroni3
 self_addr: 127.0.0.1:2224
 bind_addr: 0.0.0.0:2224
 partner_addrs:
 - 127.0.0.1:2222
 - 127.0.0.1:2223

...
```

- cmd

```
python patroni postgres1.yml
python patroni postgres2.yml
python patroni postgres3.yml
```

**Environment**
- Patroni version: 2.0.2
- PostgreSQL version: 12.7
- DCS (and its version): Raft

**Comment by CyberDem0n** [comment]
Windows particularly doesn't like files with a colon (`:`) in their names.
IIRC, it is fixed in the master branch already, i.e. colons are replaced with undescores.

**Comment by cobolbaby** [comment]
> it is fixed in the master branch already

PySyncObj or Patroni?

**Comment by CyberDem0n** [comment]
Patroni: https://github.com/zalando/patroni/blob/master/patroni/dcs/raft.py#L99

**Comment by cobolbaby** [comment]
Thx.
