### ISSUE TITLE
If Zookeeper is unavailable, master will not shutdown or demote

### ISSUE THREAD

**Issue by alwyndavis** [zalando/patroni#1981]
**Describe the bug**
When Patroni is setup to use Zookeeper as the DCS, making Zookeeper unavailable (e.g. stopping all the Zookeeper nodes) doesn't cause the master to shutdown (expected behaviour based on documentation and when etcd is the DCS).

**To Reproduce**
1. Setup Zookeeper
2. Setup two Patroni nodes and let them join normally
3. Stop a majority of the Zookeeper nodes
4. Patroni agents will go into a connection retry loop:
```
2021-06-24 06:31:26,806 WARNING: Connection dropped: socket connection error: Connection refused
2021-06-24 06:31:26,806 INFO: Connecting to 3.232.116.122(3.232.116.122):2182, use_ssl: True
2021-06-24 06:31:26,832 WARNING: Connection dropped: socket connection broken
2021-06-24 06:31:27,915 INFO: Connecting to 174.129.244.110(174.129.244.110):2182, use_ssl: True
2021-06-24 06:31:27,916 WARNING: Connection dropped: socket connection error: Connection refused
```
Whilst stuck in this loop, the master will continue to be writeable

* Use Kazoo 2.8.0 (discussed on #patroni Slack channel and regression might be from 2.7)

**Expected behavior**
Current master should shutdown

**Environment**
- Patroni version: 2.0.2
- PostgreSQL version: 13.3
- DCS (and its version): Zookeeper 3.5.8

**Patroni configuration file**
```
scope: zk-side
namespace: /service/
name: pg-1

restapi:
    listen: 10.0.0.10:8008
    connect_address: 10.0.0.10:8008

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        synchronous_mode_strict: false
        postgresql:
            use_pg_rewind: true

    postgresql:
      use_pg_rewind: true

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host replication all all md5
    - host all all all trust

zookeeper:
    hosts:
    - 52.86.244.240:2182
    - 3.232.116.122:2182
    - 174.129.244.110:2182
    use_ssl: true
    verify: false

postgresql:
    listen: 0.0.0.0:5432
    connect_address: 10.0.0.10:5432
    data_dir: /data/patroni
    bin_dir: /var/lib/postgresql/13.3/bin
    pgpass: /tmp/pgpass
    parameters:
        unix_socket_directories: '.'
    authentication:
        replication:
            username: replication
            password: password

watchdog:
    mode: off

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  use_pg_rewind: true
retry_timeout: 10
synchronous_mode_strict: false
ttl: 30
```

**Have you checked Patroni logs?**
```
2021-06-24 06:30:57,860 INFO: Lock owner: pg-1; I am pg-1
2021-06-24 06:30:57,862 INFO: no action.  i am the leader with the lock
2021-06-24 06:31:06,612 WARNING: Connection dropped: socket connection broken
2021-06-24 06:31:06,612 WARNING: Transition to CONNECTING
2021-06-24 06:31:06,612 INFO: Zookeeper connection lost
2021-06-24 06:31:06,613 INFO: Connecting to 52.86.244.240(52.86.244.240):2182, use_ssl: True
2021-06-24 06:31:06,614 WARNING: Connection dropped: socket connection error: Connection refused
2021-06-24 06:31:06,615 INFO: Connecting to 174.129.244.110(174.129.244.110):2182, use_ssl: True
```

**Have you tried to use GitHub issue search?**
Couldn't find one

**Comment by alwyndavis** [comment]
Changing from infinite retries  (see https://github.com/zalando/patroni/blob/master/patroni/dcs/zookeeper.py#L71)
 on the KazooClient to "10" in seemed to replicate the desired behaviour - the master would then exit to the DCSError catch and shutdown:
 ```
2021-06-24 06:31:31,540 WARNING: Connection dropped: socket connection error: Connection refused
2021-06-24 06:31:31,540 INFO: Connecting to 174.129.244.110(174.129.244.110):2182, use_ssl: True
2021-06-24 06:31:31,541 WARNING: Connection dropped: socket connection error: Connection refused
2021-06-24 06:31:31,542 INFO: Connecting to 3.232.116.122(3.232.116.122):2182, use_ssl: True
2021-06-24 06:31:31,573 WARNING: Connection dropped: socket connection broken
2021-06-24 06:31:31,573 WARNING: Failed connecting to Zookeeper within the connection retry policy.
2021-06-24 06:31:31,573 INFO: Zookeeper session closed, state: CLOSED
2021-06-24 06:31:31,664 ERROR: get_cluster
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/zookeeper.py", line 234, in _load_cluster
    cluster = self._client.retry(self._inner_load_cluster)
  File "/usr/local/lib/python3.5/dist-packages/kazoo/client.py", line 347, in _retry
    return self._retry.copy()(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/kazoo/retry.py", line 126, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/zookeeper.py", line 182, in _inner_load_cluster
    nodes = set(self.get_children(self.client_path(''), self.cluster_watcher))
  File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/zookeeper.py", line 166, in get_children
    return self._client.get_children(key, watch)
  File "/usr/local/lib/python3.5/dist-packages/kazoo/client.py", line 1219, in get_children
    include_data=include_data).get()
  File "/usr/local/lib/python3.5/dist-packages/kazoo/handlers/utils.py", line 69, in get
    raise self._exception
kazoo.exceptions.ConnectionClosedError: Connection has been closed
2021-06-24 06:31:31,665 ERROR: Error communicating with DCS
2021-06-24 06:31:31.683 UTC [2577] LOG:  received fast shutdown request
2021-06-24 06:31:31.690 UTC [2577] LOG:  aborting any active transactions
2021-06-24 06:31:31.691 UTC [2589] FATAL:  terminating connection due to administrator command
2021-06-24 06:31:31.693 UTC [2577] LOG:  background worker "logical replication launcher" (PID 2601) exited with exit code 1
2021-06-24 06:31:31.693 UTC [2583] LOG:  shutting down
2021-06-24 06:31:31.749 UTC [2577] LOG:  database system is shut down
```

I don't know if this has any impact on the special retry handling that the other code comments reference however.
