### ISSUE TITLE
ERROR: Exception during Ha.shutdown

### ISSUE THREAD

**Issue by dan-aksenov** [zalando/patroni#1983]
**Describe the bug**
Sometimes (50% of runs) getting following exception during patroni shutdown:
```
2021-06-25 15:03:33,868 ERROR: Exception during Ha.shutdown
Traceback (most recent call last):
  File "/usr/local/pgsql/patroni/lib/python3.6/site-packages/patroni/__init__.py", line 199, in patroni_main
    patroni.run()
  File "/usr/local/pgsql/patroni/lib/python3.6/site-packages/patroni/__init__.py", line 144, in run
    self.schedule_next_run()
  File "/usr/local/pgsql/patroni/lib/python3.6/site-packages/patroni/__init__.py", line 114, in schedule_next_run
    elif self.ha.watch(nap_time):
  File "/usr/local/pgsql/patroni/lib/python3.6/site-packages/patroni/ha.py", line 1403, in watch
    return self.dcs.watch(leader_index, timeout)
  File "/usr/local/pgsql/patroni/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 678, in watch
    return super(Etcd, self).watch(None, timeout)
  File "/usr/local/pgsql/patroni/lib/python3.6/site-packages/patroni/dcs/__init__.py", line 802, in watch
    self.event.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
  File "/usr/local/pgsql/patroni/lib/python3.6/site-packages/patroni/__init__.py", line 98, in sigterm_handler
    sys.exit()
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/pgsql/patroni/lib/python3.6/site-packages/patroni/__init__.py", line 164, in shutdown
    self.ha.shutdown()
  File "/usr/local/pgsql/patroni/lib/python3.6/site-packages/patroni/ha.py", line 1383, in shutdown
    self.while_not_sync_standby(lambda: self.state_handler.stop(checkpoint=False, on_safepoint=disable_wd,
  File "/usr/local/pgsql/patroni/lib/python3.6/site-packages/patroni/ha.py", line 495, in while_not_sync_standby
    return func()
  File "/usr/local/pgsql/patroni/lib/python3.6/site-packages/patroni/ha.py", line 1384, in <lambda>
    stop_timeout=self.master_stop_timeout()))
  File "/usr/local/pgsql/patroni/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 497, in stop
    success, pg_signaled = self._do_stop(mode, block_callbacks, checkpoint, on_safepoint, stop_timeout)
  File "/usr/local/pgsql/patroni/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 534, in _do_stop
    postmaster.wait_for_user_backends_to_close()
  File "/usr/local/pgsql/patroni/lib/python3.6/site-packages/patroni/postgresql/postmaster.py", line 190, in wait_for_user_backends_to_close
    cmdline = child.cmdline()[0]
IndexError: list index out of range
```
After that entire linux system crashes.

**To Reproduce**
Im am trying to execute batch file with following script:
```
#!/bin/bash
sudo systemctl stop patroni
rm /pg_data/* -rf
sleep 60
patronictl -c /etc/patroni/config.yml remove my_db <<EOF
my_db
Yes I am aware
EOF
sudo systemctl start patroni
```
To trigger custom bootstrap on patroni startup.

**Expected behavior**
Patroni should shutdown normally.

**Environment**
- Patroni version: patroni 1.6.5
- PostgreSQL version: 11.6
- DCS (and its version): etcd 3.2.17

**Patroni configuration file**
I dont think it'll help and ill have to remove a lots of sensitive data from there, but if it's really needed let me know.

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    max_connections: '200'
    max_locks_per_transaction: '64'
    max_prepared_transactions: '6'
    max_worker_processes: '2'
    track_commit_timestamp: false
    wal_level: replica
    wal_log_hints: true
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
ttl: 30
```

**Have you checked Patroni logs?**
Patroni logs show ERROR from above.

**Have you checked PostgreSQL logs?**
Nothing special:
```
LOG:  received smart shutdown request
FATAL:  terminating connection due to administrator command
LOG:  disconnection: session time: 9:15:08.714 user=postgres database=postgres host=127.0.0.1 port=57112
LOG:  background worker "logical replication launcher" (PID 12073) exited with exit code 1
LOG:  shutting down
LOG:  checkpoint starting: shutdown immediate
LOG:  checkpoint complete: wrote 0 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.004 s, sync=0.000 s, total=0.015 s; sync files=0, longest=0.000 s, average=0.000 s; distance=0 kB, estimate=1926837 kB
LOG:  received fast shutdown request
LOG:  database system is shut down
```

**Comment by CyberDem0n** [comment]
> Patroni version: patroni 1.6.5

Please upgrade to the lasted version and come back if the issue still exists.
