### ISSUE TITLE
Exception when setting dynamic_configuration

### ISSUE THREAD

**Issue by dbary** [zalando/patroni#2008]
Patroni: 2.0.2
Postgresql: 12
consul client: 1.6.6

I am trying to understand what this error mean:

ERROR: Exception when setting dynamic_configuration
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/config.py", line 194, in set_dynamic_configuration
    self._local_configuration)
  File "/usr/lib/python3/dist-packages/patroni/config.py", line 404, in _build_effective_configuration
    pg_config['authentication'][name] = {n: v for n, v in value.items() if n in _AUTH_ALLOWED_PARAMETERS}
AttributeError: 'bool' object has no attribute 'items'

$PGDATA dir already exists, so it is not empty. We use consul and it is working fine as far as I can tell. I have been playing around with Patroni and this is the first time I see this error.

my bootstrap.dcs setting:
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    postgresql:
      pg_rewind: true
      parameters:
        max_connections: 2000
        max_locks_per_transaction: 640
        max_worker_processes: 50
        max_prepared_transactions: 0
        wal_level: logical
        wal_log_hints: off
        track_commit_timestamp: on
        max_wal_senders: 50
        max_replication_slots: 50
        wal_keep_segments: 1000

Thanks for your help.

**Comment by dbary** [comment]
I think this issue was resloved by using "use_pg_rewind" parameter instead of pg_rewind. It just slipped my mind. closing this issue.
