### ISSUE TITLE
Unexpected exception

### ISSUE THREAD

**Issue by zerkms** [zalando/patroni#2014]
**Describe the bug**

I'm assessing the crunchydata operator at the moment that uses patroni under the hood. To do that I manually try to reproduce different failure cases.

And after another time I killed the replica pod on the current leader node I've got this exception:

```
2021-07-22 03:20:07,801 ERROR: Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1457, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1429, in _run_cycle
    msg = self.process_healthy_cluster()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1016, in process_healthy_cluster
    'promoted self to leader because i had the session lock'
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 600, in enforce_master_role
    self.process_sync_replication()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 465, in process_sync_replication
    'maximum_lag_on_syncnode'])
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 1001, in pick_synchronous_standby
    max_lsn = max(replica_list, key=lambda x: x[2])[2] if len(replica_list) > 1 else int(str(self.last_operation()))
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

The next line also asked to report it, I didn't copy it sorry.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
- Patroni version: 2.0.2
- PostgreSQL version: 13.3
- DCS (and its version):
- Python 3.6.8

**Patroni configuration file**
```
Please copy&paste your Patroni configuration file here
```

**patronictl show-config**
```
loop_wait: 10
postgresql:
  parameters:
    archive_command: pgbackrest --stanza=db archive-push "%p"
    archive_mode: 'on'
    jit: 'off'
    password_encryption: scram-sha-256
    restore_command: pgbackrest --stanza=db archive-get %f "%p"
    ssl: 'on'
    ssl_ca_file: /pgconf/tls/ca.crt
    ssl_cert_file: /pgconf/tls/tls.crt
    ssl_key_file: /pgconf/tls/tls.key
    unix_socket_directories: /tmp/postgres
    wal_level: logical
  pg_hba:
  - local all "postgres" peer
  - hostssl replication "_crunchyrepl" all cert
  - hostssl "postgres" "_crunchyrepl" all cert
  - host all "_crunchyrepl" all reject
  - hostssl all "_crunchypgbouncer" all md5
  - hostssl all all all md5
  use_pg_rewind: true
  use_slots: false
synchronous_mode: 'true'
synchronous_mode_strict: 'true'
ttl: 30

```

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.

**Additional context**

**Comment by CyberDem0n** [comment]
It seems that `pg_stat_replication` could contain NULL values in the replay_lsn/flush_lsn/write_lsn fields even when state = 'streaming'.
