### ISSUE TITLE
OpenSSL internal error, assertion failed: Low level API call to digest SHA256 forbidden in FIPS mode!

### ISSUE THREAD

**Issue by ponvenkates** [zalando/patroni#2045]
Patroni Version: 2.0.2
PostgreSQL Version: 11.12
Patroni Config:
```
check_timeline: true
log:
  level: INFO
loop_wait: 4
master_start_timeout: 60
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    max_connections: 50
    max_replication_slots: 5
    max_wal_senders: 20
    max_worker_processes: 9
    unix_socket_directories: /tmp
    wal_keep_segments: 512
    wal_level: logical
  pg_hba:
  - local all all    scram-sha-256
  - host all all 0.0.0.0/0 scram-sha-256
  remove_data_directory_on_diverged_timelines: true
  remove_data_directory_on_rewind_failure: true
  use_pg_rewind: true
  use_slots: true
retry_timeout: 8
ttl: 20
```

I am trying to run a Patroni cluster in FIPS compliant OS with Scram authentication. Leader tries to bootstrap but fails and so the cluster never turns healthy. Please find logs below,
```
2021-08-27 14:16:26.495 GMT [83] INFO: trying to bootstrap a new cluster
2021-08-27 14:16:26.497 GMT [83] INFO: Lock owner: None; I am pg-cp-fips-cluster-csl1
2021-08-27 14:16:26.497 GMT [83] INFO: not healthy enough for leader race
2021-08-27 14:16:26.502 GMT [83] WARNING: Could not register service: unknown role type uninitialized
2021-08-27 14:16:26.502 GMT [83] INFO: bootstrap in progress

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
2021-08-27 14:16:29.463 GMT [83] INFO: postmaster pid=123
2021-08-27 14:16:29.511 GMT [123] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-08-27 14:16:29.603 GMT [123] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-08-27 14:16:29.888 GMT [123] LOG:  could not open usermap file "/opt/bitnami/postgresql/conf/pg_ident.conf": No such file or directory
2021-08-27 14:16:29.890 GMT [126] LOG:  database system was shut down at 2021-08-27 14:16:28 GMT
2021-08-27 14:16:29.893 GMT [123] LOG:  database system is ready to accept connections
sha256.c(34): OpenSSL internal error, assertion failed: Low level API call to digest SHA256 forbidden in FIPS mode!
2021-08-27 14:16:30.549 GMT [83] INFO: Lock owner: None; I am pg-cp-fips-cluster-csl1
2021-08-27 14:16:30.549 GMT [83] INFO: not healthy enough for leader race
2021-08-27 14:16:30.553 GMT [83] WARNING: Could not register service: unknown role type promoted
2021-08-27 14:16:30.554 GMT [83] INFO: bootstrap in progress
2021-08-27 14:16:30.563 GMT [83] INFO: establishing a new patroni connection to the postgres cluster
2021-08-27 14:16:30.599 GMT [153] LOG:  incomplete startup packet
2021-08-27 14:16:32.396 GMT [123] LOG:  server process (PID 143) was terminated by signal 6: Aborted
2021-08-27 14:16:32.396 GMT [123] LOG:  terminating any other active server processes
2021-08-27 14:16:32.396 GMT [130] WARNING:  terminating connection because of crash of another server process
2021-08-27 14:16:32.396 GMT [130] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-08-27 14:16:32.396 GMT [130] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-08-27 14:16:32.397 GMT [157] FATAL:  the database system is in recovery mode
2021-08-27 14:16:32.406 GMT [123] LOG:  all server processes terminated; reinitializing
2021-08-27 14:16:32.779 GMT [160] LOG:  incomplete startup packet
2021-08-27 14:16:32.779 GMT [159] LOG:  database system was interrupted; last known up at 2021-08-27 14:16:29 GMT
2021-08-27 14:16:32.848 GMT [159] LOG:  database system was not properly shut down; automatic recovery in progress
2021-08-27 14:16:32.849 GMT [159] LOG:  redo starts at 0/1875010
2021-08-27 14:16:32.850 GMT [159] LOG:  invalid record length at 0/1875048: wanted 24, got 0
2021-08-27 14:16:32.850 GMT [159] LOG:  redo done at 0/1875010
2021-08-27 14:16:32.862 GMT [123] LOG:  database system is ready to accept connections
2021-08-27 14:16:33.269 GMT [83] INFO: establishing a new patroni connection to the postgres cluster
sha256.c(34): OpenSSL internal error, assertion failed: Low level API call to digest SHA256 forbidden in FIPS mode!
2021-08-27 14:16:34.601 GMT [169] LOG:  incomplete startup packet
2021-08-27 14:16:35.61 GMT [83] WARNING: Retry got exception: 'connection problems'
2021-08-27 14:16:35.062 GMT [123] LOG:  server process (PID 167) was terminated by signal 6: Aborted
2021-08-27 14:16:35.062 GMT [123] LOG:  terminating any other active server processes
2021-08-27 14:16:35.062 GMT [164] WARNING:  terminating connection because of crash of another server process
2021-08-27 14:16:35.062 GMT [164] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-08-27 14:16:35.062 GMT [164] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-08-27 14:16:35.063 GMT [171] FATAL:  the database system is in recovery mode
2021-08-27 14:16:35.63 GMT [83] WARNING: Retry got exception: 'connection problems'
2021-08-27 14:16:35.64 GMT [83] ERROR: get_postgresql_status
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/patroni/api.py", line 546, in query
    with self.patroni.postgresql.connection().cursor() as cursor:
  File "/usr/lib/python3.7/site-packages/patroni/postgresql/__init__.py", line 244, in connection
    return self._connection.get()
  File "/usr/lib/python3.7/site-packages/patroni/postgresql/connection.py", line 23, in get
    self._connection = psycopg2.connect(**self._conn_kwargs)
  File "/usr/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  the database system is in recovery mode


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/patroni/utils.py", line 334, in __call__
    return func(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/patroni/api.py", line 552, in query
    raise PostgresConnectionException('connection problems')
patroni.exceptions.PostgresConnectionException: 'connection problems'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/patroni/api.py", line 485, in get_postgresql_status
    row = self.query(stmt.format(postgresql.wal_name, postgresql.lsn_name), retry=retry)[0]
  File "/usr/lib/python3.7/site-packages/patroni/api.py", line 469, in query
    return retry(self.server.query, sql, *params)
  File "/usr/lib/python3.7/site-packages/patroni/utils.py", line 339, in __call__
    raise RetryFailedError("Too many retry attempts")
patroni.utils.RetryFailedError: 'Too many retry attempts'
2021-08-27 14:16:35.067 GMT [123] LOG:  all server processes terminated; reinitializing
2021-08-27 14:16:36.160 GMT [184] LOG:  database system was interrupted; last known up at 2021-08-27 14:16:32 GMT
2021-08-27 14:16:36.160 GMT [186] FATAL:  the database system is in recovery mode
2021-08-27 14:16:36.160 GMT [185] FATAL:  the database system is in recovery mode
2021-08-27 14:16:36.163 GMT [83] INFO: Error communicating with PostgreSQL. Will try again later
2021-08-27 14:16:36.164 GMT [83] WARNING: Loop time exceeded, rescheduling immediately.
2021-08-27 14:16:36.255 GMT [188] FATAL:  the database system is in recovery mode
2021-08-27 14:16:36.256 GMT [83] INFO: Lock owner: None; I am pg-cp-fips-cluster-csl1
2021-08-27 14:16:36.256 GMT [83] INFO: Still starting up as a standby.
2021-08-27 14:16:36.257 GMT [83] INFO: establishing a new patroni connection to the postgres cluster
2021-08-27 14:16:36.258 GMT [189] FATAL:  the database system is in recovery mode
2021-08-27 14:16:36.260 GMT [184] LOG:  database system was not properly shut down; automatic recovery in progress
2021-08-27 14:16:36.261 GMT [184] LOG:  invalid record length at 0/18750B8: wanted 24, got 0
2021-08-27 14:16:36.261 GMT [184] LOG:  redo is not required
2021-08-27 14:16:36.272 GMT [123] LOG:  database system is ready to accept connections
sha256.c(34): OpenSSL internal error, assertion failed: Low level API call to digest SHA256 forbidden in FIPS mode!
```

**Comment by CyberDem0n** [comment]
> any pointer on the issue

For example, the following error message `could not open usermap file "/opt/bitnami/postgresql/conf/pg_ident.conf": No such file or directory` gives me a hint that you are not using PGDG packages.
So, I would say that something is weird with your system. Wrong/incompatibles/conflicting libraries for example.

**Comment by ponvenkates** [comment]
Thank you for taking your time. Just for reference to anyone else facing the same issue, further search on this issue indicated that this is a problem with PG itself. PostgreSQL is still using old version of openssl APIs for scram, md5 authentication. OpenSSL prevents low level API calls when running in FIPS mode and so PostgreSQL isn't able to complete bootstrap as creating roles itself is failing. Strangely only SCRAM authentication has this issue, md5 works fine. So PostgreSQL doesn't support SCRAM in FIPS mode until PG13, this is fixed in PG14. 
References:
https://paquier.xyz/postgresql-2/postgres-14-hashes/
https://www.postgresql.org/docs/14/release-14.html
![image](https://user-images.githubusercontent.com/62520272/131448092-ee162300-0919-4f4b-aee2-eccbfff52c43.png)

**Comment by ponvenkates** [comment]
Closed this issue as it is not a Patroni issue.
