### ISSUE TITLE
pg_rewind run before checkpoint issued on promoted standby

### ISSUE THREAD

**Issue by bradnicholson** [zalando/patroni#2073]
**Describe the bug**
We've had a number of replicas that have been lost with `FATAL:  requested timeline 6 does not contain minimum recovery point 0/6700C138 on timeline 5` type of errors, which I've traced back to an issue with Patroni triggering pg_rewind. Our experience mirrors [this](https://www.postgresql.org/message-id/20180713005241.GI1167%40paquier.xyz) issue on pgsql-hackers.

These occurred during problems unrelated to Patroni that was causing severe resource degradation on the host. Clearly a lot is wrong - statement_timeout is set to 2 seconds  and is being tripped here.

Considering the potentially destructive nature of pg_rewind, I wonder Patroni should be more defensive about not triggering in such conditions? As in, if it can't verify that the last completed checkpoint on the promoted leader is newer than the promotion time - don't run pg_rewind.

A high level pattern of behaviour during the issue:

2021-09-23 02:27:17 UTC  - last checkpoint completes on m-1 <- PG Control references this checkpoint after pg_rewind
2021-09-24 00:56:56 UTC - m-1 promotes to leader
2021-09-24 00:57:35 UTC - m-0 promotes to leader
2021-09-24 01:04:13 UTC - m-1 promotes to leader
2021-09-24 01:09:24 UTC - pg_rewind starts on m-0 from m-1 - pg_controldata references the checkpoint from the first line
2021-09-24 01:10:17 UTC - pg_rewind completes successfully.
2021-09-24 01:12:47 UTC next checkpoint completes on m-1

After this, we have a timeline divergence and the replica needs a resync.

These stack traces were present in m-1 logs `2021-09-24 01:04:13`

```
2021-09-24T01:03:59.84416731Z stdout F localhost:5432 - accepting connections
2021-09-24T01:03:59.91322582Z stderr F 2021-09-24 01:03:59,897 INFO: establishing a new patroni connection to the postgres cluster
2021-09-24T01:04:00.305352585Z stderr F 2021-09-24 01:04:00,240 ERROR: Exception when changing replication slots
2021-09-24T01:04:00.423345512Z stderr F Traceback (most recent call last):
2021-09-24T01:04:00.423380547Z stderr F   File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1433, in _run_cycle
2021-09-24T01:04:00.423392825Z stderr F     msg = self.process_healthy_cluster()
2021-09-24T01:04:00.423402518Z stderr F   File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1026, in process_healthy_cluster
2021-09-24T01:04:00.423414175Z stderr F     self.state_handler.name, lock_owner), refresh=False)
2021-09-24T01:04:00.42342793Z stderr F   File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 393, in follow
2021-09-24T01:04:00.423437073Z stderr F     is_leader = self.state_handler.is_leader()
2021-09-24T01:04:00.423447093Z stderr F   File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 372, in is_leader
2021-09-24T01:04:00.423456106Z stderr F     return bool(self._cluster_info_state_get('timeline'))
2021-09-24T01:04:00.423466403Z stderr F   File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 349, in _cluster_info_state_get
2021-09-24T01:04:00.423477043Z stderr F     raise PostgresConnectionException(self._cluster_info_state['error'])
2021-09-24T01:04:00.423486426Z stderr F patroni.exceptions.PostgresConnectionException: "'Too many retry attempts'"
2021-09-24T01:04:00.423496395Z stderr F 
2021-09-24T01:04:00.423505383Z stderr F During handling of the above exception, another exception occurred:
2021-09-24T01:04:00.423513927Z stderr F 
2021-09-24T01:04:00.423522279Z stderr F Traceback (most recent call last):
2021-09-24T01:04:00.423531292Z stderr F   File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/slots.py", line 221, in sync_replication_slots
2021-09-24T01:04:00.423540141Z stderr F     if self._postgresql.is_leader():
2021-09-24T01:04:00.423549075Z stderr F   File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 372, in is_leader
2021-09-24T01:04:00.423581765Z stderr F     return bool(self._cluster_info_state_get('timeline'))
2021-09-24T01:04:00.423591797Z stderr F   File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 349, in _cluster_info_state_get
2021-09-24T01:04:00.423600643Z stderr F     raise PostgresConnectionException(self._cluster_info_state['error'])
2021-09-24T01:04:00.423609449Z stderr F patroni.exceptions.PostgresConnectionException: "'Too many retry attempts'"
2021-09-24T01:04:00.4236782Z stderr F 2021-09-24 01:04:00,400 INFO: Error communicating with PostgreSQL. Will try again later
2021-09-24T01:04:00.423699023Z stderr F 2021-09-24 01:04:00,402 WARNING: Loop time exceeded, rescheduling immediately.
2021-09-24 01:04:00 UTC [Patroni] [00000] [70924]: [1-1] user=ibm,db=postgres,client=127.0.0.1 LOG:  duration: 170.507 ms  statement: SELECT pg_catalog.pg_drop_replication_slot('c_af2f6f80_a4cd_4b68_9459_db4faa107f9c_m_0') WHERE EXISTS (SELECT 1 FROM pg_catalog.pg_replication_slots WHERE slot_name = 'c_af2f6f80_a4cd_4b68_9459_db4faa107f9c_m_0' AND NOT active)
2021-09-24 01:04:00,789 INFO: acquired session lock as a leader
2021-09-24 01:04:13,270 INFO: no action. I am (c-m-1) the leader with the lock
```

```
2021-09-24 01:07:51 UTC [Patroni] [57014] [70924]: [5-1] user=ibm,db=postgres,client=127.0.0.1 ERROR:  canceling statement due to statement timeout
2021-09-24T01:07:52.995504249Z stderr F 2021-09-24 01:07:51 UTC [Patroni] [57014] [70924]: [6-1] user=ibm,db=postgres,client=127.0.0.1 STATEMENT:  SELECT CASE WHEN pg_catalog.pg_is_in_recovery() THEN 0 ELSE ('x' || pg_catalog.substr(pg_catalog.pg_walfile_name(pg_catalog.pg_current_wal_lsn()), 1, 8))::bit(32)::int END, CASE WHEN pg_catalog.pg_is_in_recovery() THEN 0 ELSE pg_catalog.pg_wal_lsn_diff(pg_catalog.pg_current_wal_lsn(), '0/0')::bigint END, pg_catalog.pg_wal_lsn_diff(pg_catalog.pg_last_wal_replay_lsn(), '0/0')::bigint, pg_catalog.pg_wal_lsn_diff(COALESCE(pg_catalog.pg_last_wal_receive_lsn(), '0/0'), '0/0')::bigint, pg_catalog.pg_is_in_recovery() AND pg_catalog.pg_is_wal_replay_paused(), 0, CASE WHEN latest_end_lsn IS NULL THEN NULL ELSE received_tli END, slot_name, conninfo, NULL FROM pg_catalog.pg_stat_get_wal_receiver()
2021-09-24 01:07:40,665 INFO: Lock owner: c-af2f6f80-a4cd-4b68-9459-db4faa107f9c-m-1; I am c-af2f6f80-a4cd-4b68-9459-db4faa107f9c-m-1
=WARNING  2021-09-24T01:08:26.656924944Z stderr F 2021-09-24 01:07:54,996 WARNING: Retry got exception: 'connection problems'
2021-09-24T01:08:33.077574938Z stdout F localhost:5432 - no response
2021-09-24 01:08:33 UTC [[unknown]] [XX000] [71013]: [1-1] user=[unknown],db=[unknown],client=127.0.0.1 LOG:  could not accept SSL connection: Success
2021-09-24T01:08:33.285010713Z stderr F 2021-09-24 01:08:33,100 ERROR: Exception when called state_handler.last_operation()
2021-09-24T01:08:33.285065981Z stderr F Traceback (most recent call last):
2021-09-24T01:08:33.28507732Z stderr F   File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 151, in update_lock
2021-09-24T01:08:33.285087025Z stderr F     last_lsn = self.state_handler.last_operation()
2021-09-24T01:08:33.285097365Z stderr F   File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 961, in last_operation
2021-09-24T01:08:33.285107719Z stderr F     return self._wal_position(self.is_leader(), self._cluster_info_state_get('wal_position'),
2021-09-24T01:08:33.285117635Z stderr F   File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 372, in is_leader
2021-09-24T01:08:33.285127995Z stderr F     return bool(self._cluster_info_state_get('timeline'))
2021-09-24T01:08:33.285137639Z stderr F   File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 349, in _cluster_info_state_get
2021-09-24T01:08:33.285145888Z stderr F     raise PostgresConnectionException(self._cluster_info_state['error'])
2021-09-24T01:08:33.28515576Z stderr F patroni.exceptions.PostgresConnectionException: "'Exceeded retry deadline'"
2021-09-24T01:08:33.285165335Z stderr F 2021-09-24 01:08:33,275 ERROR: 
2021-09-24T01:08:33.285174834Z stderr F Traceback (most recent call last):
2021-09-24T01:08:33.285183168Z stderr F   File "/usr/local/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 562, in wrapper
2021-09-24T01:08:33.285191615Z stderr F     retval = func(self, *args, **kwargs) is not None
2021-09-24T01:08:33.285200044Z stderr F   File "/usr/local/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 692, in _update_leader
2021-09-24T01:08:33.285209918Z stderr F     return self.retry(self._client.write, self.leader_path, self._name, prevValue=self._name, ttl=self._ttl)
2021-09-24T01:08:33.285218634Z stderr F   File "/usr/local/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 443, in retry
2021-09-24T01:08:33.285227072Z stderr F     return retry(*args, **kwargs)
2021-09-24T01:08:33.28523522Z stderr F   File "/usr/local/lib/python3.6/site-packages/patroni/utils.py", line 334, in __call__
2021-09-24T01:08:33.285243614Z stderr F     return func(*args, **kwargs)
2021-09-24T01:08:33.28525193Z stderr F   File "/usr/local/lib/python3.6/site-packages/etcd/client.py", line 500, in write
2021-09-24T01:08:33.285260414Z stderr F     response = self.api_execute(path, method, params=params)
2021-09-24T01:08:33.285268469Z stderr F   File "/usr/local/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 256, in api_execute
2021-09-24T01:08:33.28527649Z stderr F     return self._handle_server_response(response)
2021-09-24T01:08:33.285285516Z stderr F   File "/usr/local/lib/python3.6/site-packages/etcd/client.py", line 987, in _handle_server_response
2021-09-24T01:08:33.285293803Z stderr F     etcd.EtcdError.handle(r)
2021-09-24T01:08:33.285301676Z stderr F   File "/usr/local/lib/python3.6/site-packages/etcd/__init__.py", line 306, in handle
2021-09-24T01:08:33.285310391Z stderr F     raise exc(msg, payload)
2021-09-24T01:08:33.285318465Z stderr F etcd.EtcdKeyNotFound: Key not found : /patroni/postgresql/leader
2021-09-24 01:08:33,279 ERROR: failed to update leader lock
2021-09-24 01:08:33,279 ERROR: Exception when changing replication slots
2021-09-24T01:08:33.285398472Z stderr F Traceback (most recent call last):
2021-09-24T01:08:33.285406857Z stderr F   File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1433, in _run_cycle
2021-09-24T01:08:33.285417713Z stderr F     msg = self.process_healthy_cluster()
2021-09-24T01:08:33.285425629Z stderr F   File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1010, in process_healthy_cluster
2021-09-24T01:08:33.28543407Z stderr F     if self.state_handler.is_leader():
2021-09-24T01:08:33.285460929Z stderr F   File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 372, in is_leader
2021-09-24T01:08:33.285470064Z stderr F     return bool(self._cluster_info_state_get('timeline'))
2021-09-24T01:08:33.285478269Z stderr F   File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 349, in _cluster_info_state_get
2021-09-24T01:08:33.285488298Z stderr F     raise PostgresConnectionException(self._cluster_info_state['error'])
2021-09-24T01:08:33.285496515Z stderr F patroni.exceptions.PostgresConnectionException: "'Exceeded retry deadline'"
2021-09-24T01:08:33.285504775Z stderr F 
2021-09-24T01:08:33.285512796Z stderr F During handling of the above exception, another exception occurred:
2021-09-24T01:08:33.285520565Z stderr F 
2021-09-24T01:08:33.285528378Z stderr F Traceback (most recent call last):
2021-09-24T01:08:33.285536381Z stderr F   File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/slots.py", line 221, in sync_replication_slots
2021-09-24T01:08:33.285545648Z stderr F     if self._postgresql.is_leader():
2021-09-24T01:08:33.285553712Z stderr F   File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 372, in is_leader
2021-09-24T01:08:33.285561813Z stderr F     return bool(self._cluster_info_state_get('timeline'))
2021-09-24T01:08:33.285570095Z stderr F   File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 349, in _cluster_info_state_get
2021-09-24T01:08:33.285578388Z stderr F     raise PostgresConnectionException(self._cluster_info_state['error'])
2021-09-24T01:08:33.285586591Z stderr F patroni.exceptions.PostgresConnectionException: "'Exceeded retry deadline'"
2021-09-24 01:08:33,301 INFO: Error communicating with PostgreSQL. Will try again later
2021-09-24 01:08:33,303 WARNING: Loop time exceeded, rescheduling immediately.
2021-09-24 01:08:33,312 INFO: establishing a new patroni connection to the postgres cluster
2021-09-24 01:08:34,377 INFO: acquired session lock as a leader
```

**To Reproduce**
Unclear at this time. The system failed over and failed back while under sever memory starvation on the host.

**Expected behavior**
pg_rewind should not run until after a checkpoint is completed, or it should just not be run at all.

**Environment**
- Patroni version: 2.1.0
- PostgreSQL version: 10,11,12 possibly 9.6
- DCS (and its version): etcd 3.2.7

**Comment by CyberDem0n** [comment]
@bradnicholson there is a problem with your timeline. At `01:04:13` there is no promote happened, Postgres was already running as primary and Patroni only acquired the lock. The leader key probably expired because Patroni was starving on resources. it would be nice to see logs from m-0 and m-1 between 00:50 and 01:13.

Actually, Patroni on replicas already waits for a checkpoint on the primary before running pg_rewind. I don't exclude the possibility that there still could be a bug in this area and more logs could help to trace it back.

**Comment by bradnicholson** [comment]
Logs from requested time range

[m-0.log](https://github.com/zalando/patroni/files/7253434/m-0.log
[m-1.log](https://github.com/zalando/patroni/files/7253435/m-1.log)
)

**Comment by CyberDem0n** [comment]
@bradnicholson in fact, m-1 never demoted.

What actually happened:
2021-09-24T00:56:56 - m-1 updated the leader key for the last time
2021-09-24T00:57:26 - leader key expired
2021-09-24T00:57:29 - m-0 promoted
2021-09-24T00:58:33 - m-1 tried to update the leader key  (based on the view from before `2021-09-24T00:57:26`) but failed with `etcd.EtcdCompareFailed: Compare failed : [m-1 != m-0]"`
2021-09-24T00:58:37 - there is only one message in the m-1 logs about m-0 being the leader
2021-09-24T01:03:19 - m-0 updated the leader key
2021-09-24T01:03:49 - leader key expired
2021-09-24T01:04:00 - m-1 acquired the leader key
2021-09-24T01:05:54 - m-0 notice that m-1 is the leader and demotes
2021-09-24T01:09:21 - m-0 figures out that it needs to rewind (there are logs: `2021-09-24 01:09:21,391 INFO: Local timeline=6 lsn=0/670001F0"`, `2021-09-24 01:09:21,483 INFO: master_timeline=5`).
2021-09-24T01:09:25 - m-0 starts pg_rewind from m-1
2021-09-24T01:10:17.75136077Z stderr F pg_rewind: rewinding from last common checkpoint at 0/66000098 on timeline 5"

The `master_timeline=5` is obtained via the replication connection (`IDENTIFY_SYSTEM` command) and it is the actual timeline of the primary, not the one that is stored in pg_control (which could be stale until CHECKPOINT is executed).
So yes, m-0 started pg_rewind absolutely correctly and we know for sure that the pg_control contain the latest CHECKPOINT.
But, despite pg_rewind finishing successfully postgres still got into a problem. I can confirm we also have seen similar behavior :(

The m-1 was supposed to be demoted at 00:58:33 or 00:58:37, but it didn't happen because the "monitoring" query didn't finish in 2 seconds and hence Patroni failed to determine that Postgres runs as the primary. Maybe it could be indeed improved, but I am not sure how much it would really help with situations when Patroni can't run (starving on resources) for a few minutes.

P.S. We experienced similar problems with Patroni on K8s (resource starvation) and were able to trace them down to dirty buffers creating memory pressure. That is, lets say you have a container with memory limit 1Gi. This limit includes everything, used memory, caches, and more important dirty buffers. The last one creating a problem because the cgroup doesn't have much control over it and typically `vm.dirty_background_ratio` and `vm.dirty_ratio` are configured to 10 and 20, what means these values are allowed to be up to 10% and 20% of available memory on the machine (not cgroup memory limit!). With machine having lets say 32GB of RAM, 10% would be 3.2GB. That means, the write activity in the container could in theory  produce up to 3.2GB of dirty buffers, even if the memory limit is 1Gi. Due to memory starvation OS starts paging out read-only memory (i.e. libraries and processes) and as a result Patroni could freeze, because for the next run it OS will have to get some pieces of libraries from the disk, what in turn requires to flush some dirty buffers.
We managed to mitigate the problem by configuring `vm.dirty_background_bytes=67108864` and `vm.dirty_bytes=134217728`. Once it was applied everywhere (in February 2020), we haven't observed starving Patroni anymore.

**Comment by bradnicholson** [comment]
Thanks for looking @CyberDem0n 

> The m-1 was supposed to be demoted at 00:58:33 or 00:58:37, but it didn't happen because the "monitoring" query didn't finish in 2 seconds and hence Patroni failed to determine that Postgres runs as the primary. Maybe it could be indeed improved, but I am not sure how much it would really help with situations when Patroni can't run (starving on resources) for a few minutes.

Right - that is tough.  If things are that stuck you can't really bank on Patroni being able to do anything. I wonder if something in the promote logic would make sense? Is it correct for m-1 to reclaim the leader key without shutting down first when another member was promoted during that period? Since another member claimed it, it seems like it should finish its demote/shutdown cycle and start backup before it can promote. I do wonder what this logic would do the wal archiving though....

PS. we traced the memory issue down - it was an unrelated memory leak elsewhere.

**Comment by CyberDem0n** [comment]
> Is it correct for m-1 to reclaim the leader key without shutting down first when another member was promoted during that period?

Yes, this is exactly what happened :(
