### ISSUE TITLE
pg_hba not updated

### ISSUE THREAD

**Issue by vkormin** [zalando/patroni#2129]
Hi,

Patroni: patronictl version 2.0.2
Posgres version: 12

During tests, i've added ph_hba section to patroni configuration using edit-config command but forgot to add following lines:
    - local all postgres  ident
    - host all all 0.0.0.0/0 md5
    - host replication replicator 0.0.0.0/0 md5

so  my pg_hba section looks like:
 pg_hba:
 - host all zbx_monitor 0.0.0.0/0 trust
 - host imap imap 0.0.0.0/0 md5

After restart cluster all members became replicas and patroni.log file on all members contains following lines:

-----------------------------------------------

2021-11-25 09:01:47,368 INFO: establishing a new patroni connection to the postgres cluster
2021-11-25 09:01:47,963 INFO: establishing a new patroni connection to the postgres cluster
2021-11-25 09:01:47,967 WARNING: Retry got exception: 'connection problems'
2021-11-25 09:01:47,989 INFO: establishing a new patroni connection to the postgres cluster
2021-11-25 09:01:47,994 ERROR: Exception when changing replication slots
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1427, in _run_cycle
    return self.process_unhealthy_cluster()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 944, in process_unhealthy_cluster
    if self.is_healthiest_node():
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 774, in is_healthiest_node
    if self.state_handler.is_leader():
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 338, in is_leader
    return bool(self._cluster_info_state_get('timeline'))
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 318, in _cluster_info_state_get
    raise PostgresConnectionException(self._cluster_info_state['error'])
patroni.exceptions.PostgresConnectionException: "'Too many retry attempts'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 255, in _query
    cursor = self._connection.cursor()
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/connection.py", line 31, in cursor
    self._cursor_holder = self.get().cursor()
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/connection.py", line 23, in get
    self._connection = psycopg2.connect(**self._conn_kwargs)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  no pg_hba.conf entry for host "127.0.0.1", user "postgres", database "postgres", SSL off

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/slots.py", line 53, in sync_replication_slots
    self.load_replication_slots()
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/slots.py", line 27, in load_replication_slots
    cursor = self._query('SELECT slot_name, slot_type, plugin, database FROM pg_catalog.pg_replication_slots')
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/slots.py", line 22, in _query
    return self._postgresql.query(sql, *params, retry=False)
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 274, in query
    return self._query(sql, *args)
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 270, in _query
    raise PostgresConnectionException('connection problems')
patroni.exceptions.PostgresConnectionException: 'connection problems'
2021-11-25 09:01:48,011 INFO: PAUSE: Error communicating with PostgreSQL. Will try again later

-----------------------------------------------

Now, any changes made in pg_bha section are not applied (after restart file date changed but content doesn't), file pg_hba.conf always contains 
# Do not edit this file manually!
# It will be overwritten by Patroni!
host all zbx_monitor 0.0.0.0/0 trust
host imap imap 0.0.0.0/0 md5
 
So it's looks like that patroni doesn't apply new configuration if all members are replicas.

How to return cluster to working state?

**Comment by lalbrecht** [comment]
Try to:
- Add lines manually to $PGDATA/pg_hba.conf
- Add lines to patroni.yml file
- Send SIGHUP to postgres

Or just reinitialize whole cluster from scratch.

**Comment by vkormin** [comment]
updating pg_hba.conf + SIGHUP to postgres on all members resolves the problem. 

Thank you, you've made my day. Cheers.

**Comment by lgwapnitsky** [comment]
I've tried this multiple times, yet nothing seems to migrate to the proper pg_hba files, and I"m unable to log in via haproxy

**Comment by lgwapnitsky** [comment]
I can provide configs as necessary

**Comment by lgwapnitsky** [comment]
I've followed this tutorial (https://snapshooter.com/learn/postgresql/postgresql-cluster-patroni) only changing the IP addresses on a vanilla installation
