### ISSUE TITLE
Invalid definition of `client_connection_check_interval` option in configuration validator

### ISSUE THREAD

**Issue by mjf** [zalando/patroni#2150]
**Describe the bug**
Probably invalid option `client_connection_check_interval` definition in configuration validator fails Postgres startup under Patroni control.

**To Reproduce**
Set `client_connection_check_interval: 1000` via `patronictl edit-config` and restart Postgres instance via `patronictl restart`.

**Expected behavior**
Not to fail Postgres instance startup.

It may be that there is a bug in option definition in the `validator.py:154` which reads now
```python
'client_connection_check_interval': Integer(140000, None, '0', '2147483647', 'ms'),
```

But it may read instead
```python
'client_connection_check_interval': Integer(140000, None, 0, 2147483647, 'ms'),
```
(I think it may be defined similarly to eg. `bgwriter_delay` or any other option that is mixing integer values with units of measure.)

**Environment**
- Patroni version: `2.1.2`
- PostgreSQL version: `14.1`
- DCS (and its version): Etcd (`3.2.21`)

**Have you checked Patroni logs?**
Yes. Here is the traceback:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/patroni/async_executor.py", line 97, in run
    wakeup = func(*args) if args else func()
  File "/usr/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 902, in follow
    ret = self.start(timeout=timeout, block_callbacks=change_role, role=role) or None
  File "/usr/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 549, in start
    self.config.write_postgresql_conf(configuration)
  File "/usr/lib/python3.6/site-packages/patroni/postgresql/config.py", line 401, in write_postgresql_conf
    value = transform_postgresql_parameter_value(self._postgresql.major_version, name, value)
  File "/usr/lib/python3.6/site-packages/patroni/postgresql/validator.py", line 531, in transform_postgresql_parameter_value
    return _transform_parameter_value(parameters, version, name, value)
  File "/usr/lib/python3.6/site-packages/patroni/postgresql/validator.py", line 522, in _transform_parameter_value
    return validator.transform(name, value)
  File "/usr/lib/python3.6/site-packages/patroni/postgresql/validator.py", line 48, in transform
    if num_value < self.min_val:
TypeError: '<' not supported between instances of 'int' and 'str'
```

**Have you tried to use GitHub issue search?**
Of course.

**Comment by CyberDem0n** [comment]
Thanks @mjf, you are absolutely right, https://github.com/zalando/patroni/pull/2154 will fix it.
