### ISSUE TITLE
Cannot bootstrap a cluster with a "Could not register service: unknown role type uninitialized" error

### ISSUE THREAD

**Issue by stl-victor-sudakov** [zalando/patroni#2152]
**Describe the bug**
Patroni 2.1.2 would not bootstrap a cluster with the following error output:

```console
$ patroni  /etc/patroni/13-myspecialcluster.yml 
2021-12-28 21:33:59,641 INFO: No PostgreSQL configuration items changed, nothing to reload.
2021-12-28 21:33:59,648 INFO: Deregister service myspecialcluster/i-vas
2021-12-28 21:33:59,655 INFO: Lock owner: None; I am i-vas
2021-12-28 21:33:59,661 INFO: Deregister service myspecialcluster/i-vas
2021-12-28 21:33:59,668 INFO: trying to bootstrap a new cluster
2021-12-28 21:33:59,669 INFO: Running custom bootstrap script: /usr/bin/pg_createcluster --datadir=/d01/pg_data/13/myspecialcluster 13 myspecialcluster
2021-12-28 21:33:59,673 INFO: Lock owner: None; I am i-vas
2021-12-28 21:33:59,673 INFO: not healthy enough for leader race
2021-12-28 21:33:59,675 WARNING: Could not register service: unknown role type uninitialized
2021-12-28 21:33:59,681 INFO: bootstrap in progress
Unknown option: scope
2021-12-28 21:33:59,713 INFO: removing initialize key after failed attempt to bootstrap the cluster
2021-12-28 21:33:59,721 INFO: Deregister service myspecialcluster/i-vas
2021-12-28 21:34:00,147 INFO: Deregister service myspecialcluster/i-vas
Traceback (most recent call last):
  File "/usr/bin/patroni", line 11, in <module>
    load_entry_point('patroni==2.1.2', 'console_scripts', 'patroni')()
  File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 182, in main
    return patroni_main()
  File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 140, in patroni_main
    abstract_main(Patroni, schema)
  File "/usr/lib/python3/dist-packages/patroni/daemon.py", line 100, in abstract_main
    controller.run()
  File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 110, in run
    super(Patroni, self).run()
  File "/usr/lib/python3/dist-packages/patroni/daemon.py", line 59, in run
    self._run_cycle()
  File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 113, in _run_cycle
    logger.info(self.ha.run_cycle())
  File "/usr/lib/python3/dist-packages/patroni/ha.py", line 1502, in run_cycle
    info = self._run_cycle()
  File "/usr/lib/python3/dist-packages/patroni/ha.py", line 1376, in _run_cycle
    return self.post_bootstrap()
  File "/usr/lib/python3/dist-packages/patroni/ha.py", line 1268, in post_bootstrap
    self.cancel_initialization()
  File "/usr/lib/python3/dist-packages/patroni/ha.py", line 1261, in cancel_initialization
    raise PatroniFatalException('Failed to bootstrap cluster')
patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
```

**To Reproduce**
Run patroni with the attached config

**Expected behavior**
A single-node cluster should have been created.

**Screenshots**
Please see the above complete output.

**Environment**
- Patroni version: 2.1.2 from pgdg
- PostgreSQL version: 13.5 from pgdg
- DCS (and its version): consul 1.11.1
- OS: Debian buster, Python 3.7.3

**Patroni configuration file**

[13-myspecialcluster.yml.txt](https://github.com/zalando/patroni/files/7787347/13-myspecialcluster.yml.txt)

**Have you checked Patroni logs?**
Please see above the complete output.

**Comment by stl-victor-sudakov** [comment]
Hold on, this could be a Debian scripts specific issue. Don't check anything yet.

**Comment by stl-victor-sudakov** [comment]
When using `/usr/share/patroni/pg_createcluster_patroni` as bootstrap.pg_createcluster.command, one should never forget that it extracts postgresql version from $SCOPE, so `scope: mycluster` will not work while `scope: 13-mycluster` will.
