### ISSUE TITLE
Requires superuser connection to primary on standby restart if rewind user is not set

### ISSUE THREAD

**Issue by mbanck** [zalando/patroni#2162]
**Describe the bug**
If the rewind user is not set, and Patroni is restarted on a follower node (initial bootstrap or reinit go fine), `check_leader_is_not_in_recovery()` will use the postgres user (I added a debug output line to show `conn_kwargs`), and if no `postgres` password is set, Patroni outputs error messages:
```
Jan 08 13:54:14 pg2 systemd[1]: Started Patroni instance 11-main.
Jan 08 13:54:15 pg2 patroni@11-main[7909]: 2022-01-08 13:54:15,089 INFO: Selected new etcd server http://10.0.3.178:2379
Jan 08 13:54:15 pg2 patroni@11-main[7909]: 2022-01-08 13:54:15,095 INFO: No PostgreSQL configuration items changed, nothing to reload.
Jan 08 13:54:15 pg2 patroni@11-main[7909]: 2022-01-08 13:54:15,106 WARNING: Postgresql is not running.
Jan 08 13:54:15 pg2 patroni@11-main[7909]: 2022-01-08 13:54:15,107 INFO: Lock owner: pg1; I am pg2
Jan 08 13:54:15 pg2 patroni@11-main[7909]: 2022-01-08 13:54:15,111 INFO: pg_controldata:
Jan 08 13:54:15 pg2 patroni@11-main[7909]:   pg_control version number: 1100
[...]

Jan 08 13:54:15 pg2 patroni@11-main[7909]: 2022-01-08 13:54:15,113 INFO: Lock owner: pg1; I am pg2
Jan 08 13:54:15 pg2 patroni@11-main[7909]: 2022-01-08 13:54:15,117 INFO: Local timeline=1 lsn=0/4000108
Jan 08 13:54:15 pg2 patroni@11-main[7909]: 2022-01-08 13:54:15,117 INFO: check_leader_is_not_in_recovery({'host': '10.0.3.178', 'port': 5432, 'dbname': 'postgres', 'user': 'postgres'})
Jan 08 13:54:15 pg2 patroni@11-main[7909]: 2022-01-08 13:54:15,125 ERROR: Exception when working with leader
Jan 08 13:54:15 pg2 patroni@11-main[7909]: Traceback (most recent call last):
Jan 08 13:54:15 pg2 patroni@11-main[7909]:   File "/usr/lib/python3/dist-packages/patroni/postgresql/rewind.py", line 61, in check_leader_is_not_in_recovery
Jan 08 13:54:15 pg2 patroni@11-main[7909]:     with get_connection_cursor(connect_timeout=3, options='-c statement_timeout=2000', **conn_kwargs) as cur:
Jan 08 13:54:15 pg2 patroni@11-main[7909]:   File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
Jan 08 13:54:15 pg2 patroni@11-main[7909]:     return next(self.gen)
Jan 08 13:54:15 pg2 patroni@11-main[7909]:   File "/usr/lib/python3/dist-packages/patroni/postgresql/connection.py", line 44, in get_connection_cursor
Jan 08 13:54:15 pg2 patroni@11-main[7909]:     conn = psycopg.connect(**kwargs)
Jan 08 13:54:15 pg2 patroni@11-main[7909]:   File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect
Jan 08 13:54:15 pg2 patroni@11-main[7909]:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Jan 08 13:54:15 pg2 patroni@11-main[7909]: psycopg2.OperationalError: connection to server at "10.0.3.178", port 5432 failed: fe_sendauth: no password supplied
Jan 08 13:54:15 pg2 patroni@11-main[7909]: 2022-01-08 13:54:15,125 INFO: Lock owner: pg1; I am pg2
```

Patroni carries on perfectly fine, but every `loop_wait` seconds, it prints the above backtrace.

I don't want to set a superuser password for remote login, ever.

If I add the rewind user/password, it uses that fine (however, I don't have `use_pg_rewind = true`, so wondering why functions in `rewind.py` are even executed)

```
Jan 08 14:06:16 pg2 patroni@11-main[6966]: 2022-01-08 14:06:16,866 INFO: Local timeline=1 lsn=0/4000060
Jan 08 14:06:16 pg2 patroni@11-main[6966]: 2022-01-08 14:06:16,866 INFO: check_leader_is_not_in_recovery({'host': '10.0.3.241', 'port': 5432, 'dbname': 'postgres', 'password': 'postgres_rewind', 'user': 'postgres_rewind'
Jan 08 14:06:16 pg2 patroni@11-main[6966]: 2022-01-08 14:06:16,882 INFO: master_timeline=1
Jan 08 14:06:16 pg2 patroni@11-main[6966]: 2022-01-08 14:06:16,882 INFO: Lock owner: pg3; I am pg2
```

**To Reproduce**
See above

**Expected behavior**
Under the assumption that Patroni is working ok and the traceback is just unwanted noise in the logfile, `check_leader_is_not_in_recovery()` could check if `user=postgres` and if so, whether a password is available? If not then maybe bail out?

**Environment**
- Patroni version: 2.1.2
- PostgreSQL version: 11.14
- DCS (and its version): etcd

**Patroni configuration file**
```
bootstrap:
  method: pg_createcluster
  pg_createcluster:
    command: /usr/share/patroni/pg_createcluster_patroni
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
[...]
postgresql:
  create_replica_method:
    - pg_clonecluster
  pg_clonecluster:
    command: /usr/share/patroni/pg_clonecluster_patroni
  listen: "*:5432"
  connect_address: 10.0.3.245:5432
  use_unix_socket: true
  data_dir: /var/lib/postgresql/11/main
  bin_dir: /usr/lib/postgresql/11/bin
  config_dir: /etc/postgresql/11/main
  pgpass: /var/lib/postgresql/11-main.pgpass
  authentication:
    replication:
      username: "replicator"
      password: "replicator"
    superuser:
      username: postgres
      password: 
  parameters:
    unix_socket_directories: '/var/run/postgresql/'
    logging_collector: 'on'
    log_directory: '/var/log/postgresql'
    log_filename: 'postgresql-11-main.log'
```

**patronictl show-config**

```
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters: null
  pg_hba:
  - local   all             all                                     peer
  - host    all             all             127.0.0.1/32            md5
  - host    all             all             ::1/128                 md5
  - host    all             all             10.0.3.178/24               md5
  - local   replication     all                                     peer
  - host    replication     all             127.0.0.1/32            md5
  - host    replication     all             ::1/128                 md5
  - host    replication     all             all                     md5
  remove_data_directory_on_diverged_timelines: true
retry_timeout: 10
ttl: 30
```

**Comment by mbanck** [comment]
I think this is due to this change in d7dc3c2d96efae456956db7df0ef9f022139b696 :

```
--- a/patroni/postgresql/rewind.py
+++ b/patroni/postgresql/rewind.py
@@ -161,11 +161,11 @@ class Rewind(object):
         if local_timeline is None or local_lsn is None:
             return
 
-        if isinstance(leader, Leader):
-            if leader.member.data.get('role') != 'master':
-                return
-        # standby cluster
-        elif not self.check_leader_is_not_in_recovery(self._conn_kwargs(leader, self._postgresql.config.replication)):
+        if isinstance(leader, Leader) and leader.member.data.get('role') != 'master':
+            return
+
+        if not self.check_leader_is_not_in_recovery(
+                self._conn_kwargs(leader, self._postgresql.config.rewind_credentials)):
             return
 
         history = need_rewind = None
```

So it was `self._postgresql.config.replication` before and is `self._postgresql.config.rewind_credentials` now (which reverts to the superuser credentials if rewind isn't defined.

I guess for the non-rewind case, this should be handled differently?

**Comment by mbanck** [comment]
If I revert that back to using the replication credentials, the backtrace is no longer there:

```
Jan 08 15:20:28 pg2 patroni@11-main[7870]: 2022-01-08 15:20:28,762 INFO: Lock owner: pg3; I am pg2
Jan 08 15:20:28 pg2 patroni@11-main[7870]: 2022-01-08 15:20:28,766 INFO: Local timeline=3 lsn=0/40003D0
Jan 08 15:20:28 pg2 patroni@11-main[7870]: 2022-01-08 15:20:28,766 INFO: check_leader_is_not_in_recovery({'host': '10.0.3.241', 'port': 5432, 'dbname': 'postgres', 'password': 'replicator', 'user': 'replicator'>
Jan 08 15:20:28 pg2 patroni@11-main[7870]: 2022-01-08 15:20:28,780 INFO: master_timeline=3
Jan 08 15:20:28 pg2 patroni@11-main[7870]: 2022-01-08 15:20:28,780 INFO: Lock owner: pg3; I am pg2
```

**Comment by CyberDem0n** [comment]
Indeed, it is the cause. Will take care of it on Monday.
