### ISSUE TITLE
Patroni demoted self and promoted self in 1 second in the same node

### ISSUE THREAD

**Issue by yinan8128** [zalando/patroni#2167]
Hello

**Describe the bug**
We found that patroni demoted self and promoted self in 1 second in the same node, this is not single case, most of the demoted cases in our env are like this, for example 00:21:20.117 demoted self and then 00:21:20.270 promoted self in the same node. **Patroni logs** have full patroni log, please check, thanks
```
2022-01-09 @ 00:21:20.270	promoted self to leader because i had the session lock
...
2022-01-09 @ 00:21:20.117	demoted self because DCS is not accessible and i was a leader
...
2022-01-09 @ 00:21:17.647	Error communicating with DCS
---
2022-01-09 @ 00:21:17.646	raise RetryFailedError("Exceeded retry deadline")
...
2022-01-09 @ 00:21:17.645	urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8500): Max retries exceeded with url: /v1/kv/service/pgcluster11/?recurse=1 (Caused by ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=8500): Read timed out. (read timeout=3.3333333333333335)",))
...
2022-01-09 @ 00:21:17.642	urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=8500): Read timed out. (read timeout=3.3333333333333335)
...
2022-01-09 @ 00:21:17.624	{"time": "2022-01-09 00:21:17,621", "name": "patroni.utils", "process": 16143, "thread": 139931912992576, "level": "WARNING", "message": "Retry got exception: HTTPConnectionPool(host='127.0.0.1', port=8500): Max retries exceeded with url: /v1/kv/service/pgcluster11/?recurse=1 (Caused by ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=8500): Read timed out. (read timeout=3.3333333333333335)",))"}
```

**Environment**
- Patroni version: 2.0.1
- PostgreSQL version: 11.11
- DCS (and its version): Consul

**Patroni configuration file**
```
scope: pgcluster11
name: s12345y-patroni_cluster-507460702

restapi:
  listen: 0.0.0.0:8008
  connect_address: 10.35.49.23:8008

consul:
  host: 127.0.0.1:8500
  checks: []
  register_service: true

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    synchronous_mode: true
    postgresql:
      use_pg_rewind: true
      use_slots: false
      parameters:
        archive_mode: "on"
        archive_command: /bin/true
        archive_timeout: 1800s
        autovacuum: "on"
        autovacuum_work_mem: 1GB
        autovacuum_vacuum_threshold: 50
        autovacuum_vacuum_cost_delay: 10ms
        autovacuum_vacuum_cost_limit: 8000
        autovacuum_vacuum_scale_factor: 0.01
        autovacuum_analyze_threshold: 50
        autovacuum_analyze_scale_factor: 0.05
        autovacuum_max_workers: 6
        auto_explain.log_min_duration: 60000
        auto_explain.log_nested_statements: true
        bgwriter_delay: 50ms
        bgwriter_lru_maxpages: 4000
        bgwriter_lru_multiplier: 4
        checkpoint_completion_target: 0.7
        checkpoint_timeout: 30min
        config_file: /var/lib/pgsql/11/data/postgresql.conf
        constraint_exclusion: partition
        cron.database_name: postgres
        datestyle: "ISO, MDY"
        default_statistics_target: 100
        default_text_search_config: "pg_catalog.english"
        effective_cache_size: "5952MB"
        hot_standby: "on"
        idle_in_transaction_session_timeout: 10min
        lc_messages: 'C'
        lc_monetary: 'C'
        lc_numeric: 'C'
        lc_time: 'C'
        lock_timeout: 30s
        log_autovacuum_min_duration: 500
        log_checkpoints: "off"
        log_connections: "off"
        log_destination: "stderr"
        log_directory: "/var/log/postgresql"
        log_disconnections: "off"
        log_duration: "off"
        log_filename: 'postgresql.log'
        log_line_prefix: '[%m] p=%p:%l@%v c=%u@%h/%d:%a '
        log_lock_waits: "on"
        log_min_duration_statement: "5s"
        log_rotation_age: 0
        log_rotation_size: 0
        log_statement: "ddl"
        log_temp_files: 1MB
        log_timezone: "UTC"
        log_truncate_on_rotation: "off"
        logging_collector: "on"
        maintenance_work_mem: 2GB
        max_connections: 1000
        max_replication_slots: 10
        max_wal_senders: 10
        max_wal_size: "7936"
        min_wal_size: 1024
        pg_stat_statements.max: 10000
        pg_stat_statements.track: all
        random_page_cost: 1.1
        shared_buffers: 1984MB
        shared_preload_libraries: 'pg_stat_statements,pg_stat_kcache,auto_explain,pg_cron'
        ssl: 'on'
        ssl_ca_file: '/var/lib/pgsql/tls/root.crt'
        ssl_cert_file: '/var/lib/pgsql/tls/server.crt'
        ssl_key_file: '/var/lib/pgsql/tls/server.key'
        statement_timeout: 10min
        temp_file_limit: 5GB
        timezone: "UTC"
        track_io_timing: "on"
        unix_socket_directories: '/var/run/postgresql'
        wal_buffers: -1
        wal_compression: "on"
        wal_keep_segments: "10"
        wal_level: replica
        wal_log_hints: "on"
        work_mem: "3MB"
      recovery_conf:
        restore_command: /bin/true
  initdb:
    - encoding: UTF8
    - data-checksums
    - locale: en_US.UTF-8
    - lc-collate: en_US.UTF-8
    - lc-ctype: en_US.UTF-8

  users:
    replicator:
      password: df9742aa52d61218b04da75b540b5bb9
      options:
        - replication

postgresql:
  listen: '*'
  connect_address: 10.35.49.23:5432
  data_dir: /var/lib/pgsql/11/data
  bin_dir: /usr/pgsql-11/bin
  config_dir: /var/lib/pgsql/11/data
  hba_file: /var/lib/pgsql/11/data/pg_hba.conf
  restore: /usr/bin/patroni_wale_restore
  pgpass: /tmp/pgpass
  authentication:
    pg_rewind:
      username: postgres
      password: 534fcf32f27c920f62668f8c6f9d374b
    replication:
      username: replicator
      password: df9742aa52d61218b04da75b540b5bb9
      network: 0.0.0.0/0
    superuser:
      username: postgres
      password: 534fcf32f27c920f62668f8c6f9d374b
  callbacks:
    on_start: /etc/patroni/callback.sh
    on_stop: /etc/patroni/callback.sh
    on_role_change: /etc/patroni/callback.sh
  basebackup:
    - verbose
    - checkpoint: 'fast'
  pg_hba:
    - local all postgres trust
    - local all all trust
    - host replication replicator 0.0.0.0/0 md5
    - host replication replicator ::/0 md5
    - host replication postgres 127.0.0.1/32 trust
    - host replication postgres ::1/128 trust
    - host all all 127.0.0.1/32 md5
    - host all all ::1/128 md5
    - host postgres postgres 10.35.49.21/32 md5
    - host postgres pgwatch2 10.35.49.21/32 md5
    - host postgres postgres 10.35.49.22/32 md5
    - host postgres pgwatch2 10.35.49.22/32 md5
    - host postgres postgres 10.35.49.23/32 md5
    - host postgres pgwatch2 10.35.49.23/32 md5
    - host postgres all 0.0.0.0/0 reject
    - host postgres all ::/0 reject
    - hostnossl all all 0.0.0.0/0 md5
    - hostnossl all all ::/0 md5
    - hostssl all all 0.0.0.0/0 md5 clientcert=1
    - hostssl all all ::/0 md5 clientcert=1

watchdog:
  mode: off

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

log:
    format: '{"time": "%(asctime)s", "name": "%(name)s", "process": %(process)d, "thread": %(thread)d, "level": "%(levelname)s", "message": "%(message)s"}'
```

**Patroni logs**

kibana patroni.message
```
2022-01-09 @ 00:21:21.419	Lock owner: BEF-PATRONI-CLUSTER3; I am BEF-PATRONI-CLUSTER3
2022-01-09 @ 00:21:21.346	no action.  i am the leader with the lock
2022-01-09 @ 00:21:21.334	Register service pgcluster11, params {'service_id': 'pgcluster11/BEF-PATRONI-CLUSTER3', 'address': '10.61.12.16', 'port': 5432, 'check': {'http': 'http://10.61.12.16:8008/master', 'interval': '5s', 'DeregisterCriticalServiceAfter': '150.0s'}, 'tags': ['master']}
2022-01-09 @ 00:21:21.291	Lock owner: BEF-PATRONI-CLUSTER3; I am BEF-PATRONI-CLUSTER3
2022-01-09 @ 00:21:20.273	cleared rewind state after becoming the leader
2022-01-09 @ 00:21:20.270	promoted self to leader because i had the session lock
2022-01-09 @ 00:21:20.156	Register service pgcluster11, params {'service_id': 'pgcluster11/BEF-PATRONI-CLUSTER3', 'address': '10.61.12.16', 'port': 5432, 'check': {'http': 'http://10.61.12.16:8008/replica', 'interval': '5s', 'DeregisterCriticalServiceAfter': '150.0s'}, 'tags': ['replica']}
2022-01-09 @ 00:21:20.123	establishing a new patroni connection to the postgres cluster
2022-01-09 @ 00:21:20.123	Lock owner: BEF-PATRONI-CLUSTER3; I am BEF-PATRONI-CLUSTER3
2022-01-09 @ 00:21:20.117	demoted self because DCS is not accessible and i was a leader
2022-01-09 @ 00:21:20.117	Loop time exceeded, rescheduling immediately.
2022-01-09 @ 00:21:19.066	postmaster pid=2923
2022-01-09 @ 00:21:18.396	closed patroni connection to the postgresql cluster
2022-01-09 @ 00:21:17.647	Error communicating with DCS
2022-01-09 @ 00:21:17.636	get_cluster
2022-01-09 @ 00:20:56.412	no action.  i am the leader with the lock
2022-01-09 @ 00:20:56.385	Lock owner: BEF-PATRONI-CLUSTER3; I am BEF-PATRONI-CLUSTER3
```

kibana message
```
2022-01-09 @ 00:21:31.438	server signaled
2022-01-09 @ 00:21:20.272	server promoting
2022-01-09 @ 00:21:20.131	connection to server was lost
2022-01-09 @ 00:21:20.130	server closed the connection unexpectedly
2022-01-09 @ 00:21:20.130	This probably means the server terminated abnormally
2022-01-09 @ 00:21:20.130	before or while processing the request.
2022-01-09 @ 00:21:20.110	localhost:5432 - accepting connections
2022-01-09 @ 00:21:20.093	localhost:5432 - accepting connections
2022-01-09 @ 00:21:19.285	[2022-01-09 00:21:19.285 UTC] p=2923:6@ c=@/: LOG:  redirecting log output to logging collector process
2022-01-09 @ 00:21:19.285	[2022-01-09 00:21:19.285 UTC] p=2923:7@ c=@/: HINT:  Future log output will appear in directory "/var/log/postgresql".
2022-01-09 @ 00:21:19.095	[2022-01-09 00:21:19.095 UTC] p=2923:5@ c=@/: LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-01-09 @ 00:21:19.094	[2022-01-09 00:21:19.093 UTC] p=2923:3@ c=@/: LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-01-09 @ 00:21:19.094	[2022-01-09 00:21:19.093 UTC] p=2923:4@ c=@/: LOG:  listening on IPv6 address "::", port 5432
2022-01-09 @ 00:21:19.089	[2022-01-09 00:21:19.088 UTC] p=2923:2@ c=@/: LOG:  pg_stat_kcache.linux_hz is set to 1000000
2022-01-09 @ 00:21:19.089	[2022-01-09 00:21:19.088 UTC] p=2923:1@ c=@/: LOG:  Auto detecting pg_stat_kcache.linux_hz parameter...
2022-01-09 @ 00:21:19.075	localhost:5432 - no response
2022-01-09 @ 00:21:17.646	return self._retry.copy()(*args, **kwargs)
2022-01-09 @ 00:21:17.646	File "/usr/local/lib/python3.6/site-packages/patroni/dcs/consul.py", line 232, in retry
2022-01-09 @ 00:21:17.646	patroni.utils.RetryFailedError: 'Exceeded retry deadline'
2022-01-09 @ 00:21:17.646	_, results = self.retry(self._client.kv.get, path, recurse=True)
2022-01-09 @ 00:21:17.646	File "/usr/local/lib/python3.6/site-packages/patroni/utils.py", line 344, in __call__
2022-01-09 @ 00:21:17.646	raise RetryFailedError("Exceeded retry deadline")
2022-01-09 @ 00:21:17.645	Traceback (most recent call last):
2022-01-09 @ 00:21:17.645	During handling of the above exception, another exception occurred:
2022-01-09 @ 00:21:17.645	raise MaxRetryError(_pool, url, error or ResponseError(cause))
2022-01-09 @ 00:21:17.645	File "/usr/local/lib/python3.6/site-packages/patroni/dcs/consul.py", line 309, in _load_cluster
2022-01-09 @ 00:21:17.645	urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8500): Max retries exceeded with url: /v1/kv/service/pgcluster11/?recurse=1 (Caused by ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=8500): Read timed out. (read timeout=3.3333333333333335)",))
2022-01-09 @ 00:21:17.645	File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 574, in increment
2022-01-09 @ 00:21:17.644	return self.urlopen(method, url, **extra_kw)
2022-01-09 @ 00:21:17.644	File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 96, in request_encode_url
2022-01-09 @ 00:21:17.644	response = conn.urlopen(method, u.request_uri, **kw)
2022-01-09 @ 00:21:17.644	File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 375, in urlopen
2022-01-09 @ 00:21:17.644	File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
2022-01-09 @ 00:21:17.644	method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
2022-01-09 @ 00:21:17.643	File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 75, in request
2022-01-09 @ 00:21:17.643	method, url, fields=fields, headers=headers, **urlopen_kw
2022-01-09 @ 00:21:17.643	params=params)
2022-01-09 @ 00:21:17.643	File "/usr/local/lib/python3.6/site-packages/patroni/dcs/consul.py", line 117, in wrapper
2022-01-09 @ 00:21:17.643	return callback(self.response(self.http.request(method.upper(), self.uri(path, params), **kwargs)))
2022-01-09 @ 00:21:17.642	Traceback (most recent call last):
2022-01-09 @ 00:21:17.642	File "/usr/local/lib/python3.6/site-packages/patroni/utils.py", line 333, in __call__
2022-01-09 @ 00:21:17.642	return func(*args, **kwargs)
2022-01-09 @ 00:21:17.642	File "/usr/local/lib/python3.6/site-packages/consul/base.py", line 554, in get
2022-01-09 @ 00:21:17.642	During handling of the above exception, another exception occurred:
2022-01-09 @ 00:21:17.642	urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=8500): Read timed out. (read timeout=3.3333333333333335)
2022-01-09 @ 00:21:17.641	self, url, "Read timed out. (read timeout=%s)" % timeout_value
2022-01-09 @ 00:21:17.641	File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 447, in _make_request
2022-01-09 @ 00:21:17.641	self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
2022-01-09 @ 00:21:17.641	File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 337, in _raise_timeout
2022-01-09 @ 00:21:17.639	During handling of the above exception, another exception occurred:
2022-01-09 @ 00:21:17.639	socket.timeout: timed out
2022-01-09 @ 00:21:17.639	File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
2022-01-09 @ 00:21:17.639	Traceback (most recent call last):
2022-01-09 @ 00:21:17.639	chunked=chunked,
2022-01-09 @ 00:21:17.638	File "/usr/lib64/python3.6/http/client.py", line 258, in _read_status
2022-01-09 @ 00:21:17.638	return self._sock.recv_into(b)
2022-01-09 @ 00:21:17.638	File "/usr/lib64/python3.6/socket.py", line 586, in readinto
2022-01-09 @ 00:21:17.638	version, status, reason = self._read_status()
2022-01-09 @ 00:21:17.638	line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
2022-01-09 @ 00:21:17.637	response.begin()
2022-01-09 @ 00:21:17.637	File "/usr/lib64/python3.6/http/client.py", line 1331, in getresponse
2022-01-09 @ 00:21:17.637	httplib_response = conn.getresponse()
2022-01-09 @ 00:21:17.637	File "/usr/lib64/python3.6/http/client.py", line 297, in begin
2022-01-09 @ 00:21:17.637	File "<string>", line 3, in raise_from
2022-01-09 @ 00:21:17.637	File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 440, in _make_request
2022-01-09 @ 00:21:17.636	Traceback (most recent call last):
2022-01-09 @ 00:21:17.636	File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 445, in _make_request
2022-01-09 @ 00:21:17.636	six.raise_from(e, None)
2022-01-09 @ 00:21:17.624	{"time": "2022-01-09 00:21:17,621", "name": "patroni.utils", "process": 16143, "thread": 139931912992576, "level": "WARNING", "message": "Retry got exception: HTTPConnectionPool(host='127.0.0.1', port=8500): Max retries exceeded with url: /v1/kv/service/pgcluster11/?recurse=1 (Caused by ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=8500): Read timed out. (read timeout=3.3333333333333335)",))"}
```

**Comment by CyberDem0n** [comment]
Leader demotes itself if communication with DCS is failing during `retry_timeout` seconds (10s by default). What is the value in your case I don't know, because you ignored the question about `patronictl show-config`.

In other words - blame _local consul agent_ or consul cluster.

**Comment by yinan8128** [comment]
Hello,

Thank you for your reply

retry_timeout is 10, loop_wait is 10, ttl is 30, please check below "patronictl show-config" result

We got the information that to increase retry_timeout also need to increase ttl, for example loop_wait=10, retry_timeout=20, ttl=50. Just as we explained, for our case, most of the demoted cases in our env are that patroni demoted self and promoted self in 1 second in the same node,  just think actually all the network with consul problem can not all 11 secs, is it possible some other reason caused? Any suggestion to solve it please? Thanks

**patronictl show-config**
$ patronictl -c /etc/patroni/postgresql.yml show-config                                                                                                                                             [32/1883]
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: /bin/true
    archive_mode: 'on'
    archive_timeout: 1800s
    auto_explain.log_min_duration: 60000
    auto_explain.log_nested_statements: true
    autovacuum: 'on'
    autovacuum_analyze_scale_factor: 0.05
    autovacuum_analyze_threshold: 50
    autovacuum_max_workers: 6
    autovacuum_vacuum_cost_delay: 10ms
    autovacuum_vacuum_cost_limit: 8000
    autovacuum_vacuum_scale_factor: 0.01
    autovacuum_vacuum_threshold: 50
    autovacuum_work_mem: 1GB
    bgwriter_delay: 50ms
    bgwriter_lru_maxpages: 4000
    bgwriter_lru_multiplier: 4
    checkpoint_completion_target: 0.7
    checkpoint_timeout: 30min
    config_file: /var/lib/pgsql/11/data/postgresql.conf
    constraint_exclusion: partition
    cron.database_name: postgres
    datestyle: ISO, MDY
    default_statistics_target: 100
    default_text_search_config: pg_catalog.english
    effective_cache_size: 5952MB
    hot_standby: 'on'
    idle_in_transaction_session_timeout: 10min
    lc_messages: C
    lc_monetary: C
    lc_numeric: C
    lc_time: C
    lock_timeout: 30s
    log_autovacuum_min_duration: 500
    log_checkpoints: 'off'
    log_connections: 'off'
    log_destination: stderr
    log_directory: /var/log/postgresql
    log_disconnections: 'off'
    log_duration: 'off'
    log_filename: postgresql.log
    log_line_prefix: '[%m] p=%p:%l@%v c=%u@%h/%d:%a '
    log_lock_waits: 'on'
    log_min_duration_statement: 5s
    log_rotation_age: 0
    log_rotation_size: 0
    log_statement: ddl
    log_temp_files: 1MB
    log_timezone: UTC
    log_truncate_on_rotation: 'off'
    logging_collector: 'on'
    maintenance_work_mem: 2GB
    max_connections: 1000
    max_replication_slots: 10
    max_wal_senders: 10
    max_wal_size: '7936'
    min_wal_size: 1024
    pg_stat_statements.max: 10000
    pg_stat_statements.track: all
    random_page_cost: 1.1
    shared_buffers: 1984MB
    shared_preload_libraries: pg_stat_statements,pg_stat_kcache,auto_explain,pg_cron
    ssl: 'on'
    ssl_ca_file: /var/lib/pgsql/tls/root.crt
    ssl_cert_file: /var/lib/pgsql/tls/server.crt
    ssl_key_file: /var/lib/pgsql/tls/server.key
    statement_timeout: 10min
    temp_file_limit: 5GB
    timezone: UTC
    track_io_timing: 'on'
    unix_socket_directories: /var/run/postgresql
    wal_buffers: -1
    wal_compression: 'on'
    wal_keep_segments: '10'
    wal_level: replica
    wal_log_hints: 'on'
    work_mem: 3MB
  recovery_conf:
    restore_command: /bin/true
  use_pg_rewind: true
  use_slots: false
retry_timeout: 10
synchronous_mode: true
ttl: 30

**Comment by CyberDem0n** [comment]
> patroni demoted self and promoted self in 1 second in the same node

It promotes self when connectivity with consul agent "recovers".


> Any suggestion to solve it please?

The usual way of solving any kind of issue is checking all kinds of logs: Patroni, Postgres, Consul, syslog, etc...

**Comment by yinan8128** [comment]
Hi,

As currently the consul network problem sometimes still exists, If need to increase retry_timeout and ttl or any other suggestion  to let patroni cluster work well please? Most of the demoted cases in our env are that patroni demoted self and promoted self in 1 second in the same node, just think actually all the network with consul problem may be not all 11 secs, if yes, so coincidence. Or maybe any other reason caused? Thanks

**Comment by CyberDem0n** [comment]
> if yes, so coincidence. Or maybe any other reason caused?

Did you already checked consul logs?

**Comment by yinan8128** [comment]
Hi,

Attached the consul log, please check

2022-01-09 @ 00:21:12.365 is the latest consul error log time
2022-01-09 @ 00:21:17.647 is patroni "Error communicating with DCS" log time which attached in the first comment

**consul log**
```
2022-01-09 @ 00:22:08.842	agent: Synced check "service:prometheus-shell_exporter"
2022-01-09 @ 00:21:55.337	agent: Synced check "service:prometheus-shell_exporter"
2022-01-09 @ 00:21:12.365	memberlist: Failed fallback ping: write tcp 10.61.11.2:48442->10.61.12.15:8301: i/o timeout
2022-01-09 @ 00:21:09.902	memberlist: Suspect BEF-PATRONI-CLUSTER2 has failed, no acks received
2022-01-09 @ 00:21:09.901	memberlist: Failed fallback ping: write tcp 10.61.11.10:49810->10.61.12.15:8301: i/o timeout
2022-01-09 @ 00:21:09.238	memberlist: Suspect etisalat-reportdb-vm01 has failed, no acks received
2022-01-09 @ 00:21:09.237	memberlist: Failed fallback ping: write tcp 10.61.11.63:43166->10.61.12.18:8301: i/o timeout
2022-01-09 @ 00:21:07.642	memberlist: Refuting a suspect message (from: etisalat-reportdb-vm01)
2022-01-09 @ 00:21:06.849	memberlist: Suspect BEF-PATRONI-CLUSTER2 has failed, no acks received
2022-01-09 @ 00:21:06.848	memberlist: Failed fallback ping: write tcp 10.61.11.27:48200->10.61.12.15:8301: i/o timeout
2022-01-09 @ 00:20:41.632	agent: Synced check "service:prometheus-shell_exporter"
2022-01-09 @ 00:19:55.813	agent: Synced check "service:prometheus-shell_exporter"
```

**Comment by CyberDem0n** [comment]
Timestamps match. This is definitely triggered by Consul.
I don't have enough experience with Consul and can't help further.
Maybe by any chance you run Patroni on Consul server nodes?

**Comment by yinan8128** [comment]
Hi,

As all the prod env already work for a long period, we can not change patroni on consul server nodes.

Now question is like once consul(or etcd whatever) network problem sometimes still exists(unstable for around 10 seconds), how to configure patroni to let patroni still can work well, please suggest, thanks

**Comment by bukem** [comment]
Hi @CyberDem0n and @yinan8128 
Let me add my five cents. The situation is such that in 10 seconds (retry_timeout period) patroni is not able to update the key in Consul, but after demoting it is able to lock the key in just 1 second. And this is observed quite often. Yes, it is worth trying to increase the timeout, but there is a feeling that the same thing will happen, just after 20 seconds (if we consider setting retry_timeout to 20) :)

**Comment by CyberDem0n** [comment]
Consul also has it's own timeout mechanisms and they could be triggered when Patron is trying to refresh session.
