### ISSUE TITLE
Cannot create patroni with existing postgres

### ISSUE THREAD

**Issue by hound672** [zalando/patroni#2173]
Hello.
I used this manual: https://patroni.readthedocs.io/en/latest/existing_data.html

1. Start standalone postgres.
2. Create users
3. Start patroni.
And it seems that patroni didn't determine that one postgresql is running.
I got this error from patroni :
```
2022-01-16 06:34:11,444 INFO: removing initialize key after failed attempt to bootstrap the cluster
2022-01-16 06:34:11,452 INFO: renaming data directory to /var/lib/postgresql/13/patroni_2022-01-16-06-34-11
Traceback (most recent call last):
  File "/home/admin/env_patroni/bin/patroni", line 10, in <module>
    sys.exit(main())
  File "/home/admin/env_patroni/lib/python3.7/site-packages/patroni/__init__.py", line 182, in main
    return patroni_main()
  File "/home/admin/env_patroni/lib/python3.7/site-packages/patroni/__init__.py", line 140, in patroni_main
    abstract_main(Patroni, schema)
  File "/home/admin/env_patroni/lib/python3.7/site-packages/patroni/daemon.py", line 100, in abstract_main
    controller.run()
  File "/home/admin/env_patroni/lib/python3.7/site-packages/patroni/__init__.py", line 110, in run
    super(Patroni, self).run()
  File "/home/admin/env_patroni/lib/python3.7/site-packages/patroni/daemon.py", line 59, in run
    self._run_cycle()
  File "/home/admin/env_patroni/lib/python3.7/site-packages/patroni/__init__.py", line 113, in _run_cycle
    logger.info(self.ha.run_cycle())
  File "/home/admin/env_patroni/lib/python3.7/site-packages/patroni/ha.py", line 1502, in run_cycle
    info = self._run_cycle()
  File "/home/admin/env_patroni/lib/python3.7/site-packages/patroni/ha.py", line 1376, in _run_cycle
    return self.post_bootstrap()
  File "/home/admin/env_patroni/lib/python3.7/site-packages/patroni/ha.py", line 1268, in post_bootstrap
    self.cancel_initialization()
  File "/home/admin/env_patroni/lib/python3.7/site-packages/patroni/ha.py", line 1261, in cancel_initialization
    raise PatroniFatalException('Failed to bootstrap cluster')
patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
```

And this error in log from patroni instance postgres:
```
2022-01-16 06:27:02.218 EST [11994] LOG:  starting PostgreSQL 13.5 (Debian 13.5-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2022-01-16 06:27:02.218 EST [11994] LOG:  could not bind IPv4 address "0.0.0.0": Address already in use
2022-01-16 06:27:02.218 EST [11994] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2022-01-16 06:27:02.218 EST [11994] WARNING:  could not create listen socket for "0.0.0.0"
2022-01-16 06:27:02.218 EST [11994] FATAL:  could not create any TCP/IP sockets
2022-01-16 06:27:02.219 EST [11994] LOG:  database system is shut down
```

If i change port in patroni config then patroni create the empty intance but i want to use data from existing postgresql.

**Comment by CyberDem0n** [comment]
If something doesn't work you are probably doing something wrong. Keep trying,  it is definitely possible.

**Comment by hound672** [comment]
I know. But I tried these steps by manual from patroni docs.
I'd like to get what I do wrong.

**Comment by CyberDem0n** [comment]
Documentation is only describing the idea.
In order to apply this idea you need to get some understanding how Postgres works and how it locks $PGDATA with postmaster.pid.
Also, I would recommend to play with Patroni in order to reverse-engineer what layout of $PGDATA and Postgres configuration it generates in order to create a proper patroni.yaml

**Comment by lalbrecht** [comment]
Hi!
`Is another postmaster already running on port 5432?` - looks like you try to start Patroni on already started PostgreSQL cluster. Just shut it down and restart Patroni and it handles postgres processes.

**Comment by CyberDem0n** [comment]
@lalbrecht please don't give bad advises.
With the proper patroni.yaml Patroni should be able to find already running Postgres (by looking into $PGDATA/postmaster.pid)

**Comment by hound672** [comment]
Just cheked.
```
cat $PGDATA/postmaster.pid
33996
/var/lib/postgresql/13/main
1642404509
5432
/var/run/postgresql
0.0.0.0
   657581   5603328
ready```

So there is ``` $PGDATA/postmaster.pid```.

Postgresql standalone custer is running. But when I try to run patroni I still got error:
```
$ patroni postgres.yml
2022-01-17 02:35:16,417 INFO: No PostgreSQL configuration items changed, nothing to reload.
2022-01-17 02:35:16,430 INFO: Lock owner: None; I am postgresql0
2022-01-17 02:35:16,435 INFO: waiting for leader to bootstrap
^C(env_patroni) postgres@vijn-psqlcluster-database-0:/etc/patroni$ patroni postgres.yml
2022-01-17 02:35:22,274 INFO: No PostgreSQL configuration items changed, nothing to reload.
2022-01-17 02:35:22,282 INFO: Lock owner: None; I am postgresql0
2022-01-17 02:35:22,289 INFO: trying to bootstrap a new cluster
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are enabled.

creating directory /var/lib/postgresql/13/patroni ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... America/New_York
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    /usr/lib/postgresql/13/bin/pg_ctl -D /var/lib/postgresql/13/patroni -l logfile start

2022-01-17 02:35:25.048 EST [34083] LOG:  redirecting log output to logging collector process
2022-01-17 02:35:25.048 EST [34083] HINT:  Future log output will appear in directory "/var/log/postgresql".
2022-01-17 02:35:25,075 INFO: postmaster pid=34083
localhost:5432 - accepting connections
2022-01-17 02:35:25,106 INFO: removing initialize key after failed attempt to bootstrap the cluster
2022-01-17 02:35:25,112 INFO: renaming data directory to /var/lib/postgresql/13/patroni_2022-01-17-02-35-25
Traceback (most recent call last):
  File "/home/admin/env_patroni/bin/patroni", line 10, in <module>
    sys.exit(main())
  File "/home/admin/env_patroni/lib/python3.7/site-packages/patroni/__init__.py", line 182, in main
    return patroni_main()
  File "/home/admin/env_patroni/lib/python3.7/site-packages/patroni/__init__.py", line 140, in patroni_main
    abstract_main(Patroni, schema)
  File "/home/admin/env_patroni/lib/python3.7/site-packages/patroni/daemon.py", line 100, in abstract_main
    controller.run()
  File "/home/admin/env_patroni/lib/python3.7/site-packages/patroni/__init__.py", line 110, in run
    super(Patroni, self).run()
  File "/home/admin/env_patroni/lib/python3.7/site-packages/patroni/daemon.py", line 59, in run
    self._run_cycle()
  File "/home/admin/env_patroni/lib/python3.7/site-packages/patroni/__init__.py", line 113, in _run_cycle
    logger.info(self.ha.run_cycle())
  File "/home/admin/env_patroni/lib/python3.7/site-packages/patroni/ha.py", line 1502, in run_cycle
    info = self._run_cycle()
  File "/home/admin/env_patroni/lib/python3.7/site-packages/patroni/ha.py", line 1376, in _run_cycle
    return self.post_bootstrap()
  File "/home/admin/env_patroni/lib/python3.7/site-packages/patroni/ha.py", line 1268, in post_bootstrap
    self.cancel_initialization()
  File "/home/admin/env_patroni/lib/python3.7/site-packages/patroni/ha.py", line 1261, in cancel_initialization
    raise PatroniFatalException('Failed to bootstrap cluster')
patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
```

**Comment by CyberDem0n** [comment]
```
creating directory /var/lib/postgresql/13/patroni ... ok
```

Why `/var/lib/postgresql/13/patroni` if it should be `/var/lib/postgresql/13/main`?

**Comment by CyberDem0n** [comment]
In addition to that autostart for `/var/lib/postgresql/13/main` _must_ be disabled.

**Comment by hound672** [comment]
Ok. change In patroni config:
```
postgresql:
  listen: 0.0.0.0:5432
  connect_address: 10.0.218.217:5432
  data_dir: /var/lib/postgresql/13/main
  bin_dir: /usr/lib/postgresql/13/bin
```

standalone cluster status:
```
$ sudo systemctl status postgresql
● postgresql.service - PostgreSQL RDBMS
   Loaded: loaded (/lib/systemd/system/postgresql.service; disabled; vendor preset: enabled)
   Active: active (exited) since Mon 2022-01-17 03:02:34 EST; 2min 33s ago
  Process: 34559 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
 Main PID: 34559 (code=exited, status=0/SUCCESS)
      CPU: 2ms

Jan 17 03:02:34 vijn-psqlcluster-database-0 systemd[1]: Starting PostgreSQL RDBMS...
Jan 17 03:02:34 vijn-psqlcluster-database-0 systemd[1]: Started PostgreSQL RDBMS.

$ sudo -u postgres pg_lsclusters
Ver Cluster Port Status Owner    Data directory              Log file
13  main    5432 online postgres /var/lib/postgresql/13/main /var/log/postgresql/postgresql-13-main.log
```

Patrini is starting without errors.
I can connect to database I can read old data.
But when I restart patroni I got error:
```
2022-01-17 03:07:11,041 INFO: Lock owner: None; I am postgresql0
2022-01-17 03:07:11,052 INFO: starting as a secondary
2022-01-17 08:07:11.579 GMT [34661] LOG:  could not open configuration directory "/var/lib/postgresql/13/main/conf.d": No such file or directory
2022-01-17 08:07:11.582 GMT [34661] FATAL:  configuration file "/var/lib/postgresql/13/main/postgresql.conf" contains errors
```

Only restart standalone postgres and then start patroni helps.

**Comment by hound672** [comment]
Maybe it will be easy to create empty cluster with patroni.
And then export data from existing database with ```pg_dump```
