### ISSUE TITLE
A,B two devices using patroni to form a cluster, when I stop A,B network communication, redowal appear a lot of 0byte file

### ISSUE THREAD

**Issue by ChenJhua** [zalando/patroni#2183]
**Describe the bug**
A,B two devices using patroni to form a cluster, when I stop A,B network communication, redowal appear a lot of 0byte file.postgresql start exception：
`2022-01-25 16:09:14.055 CST [65104] LOG:  could not read from log segment 000000050000000700000021, offset 0: read 0 of 8192`

**To Reproduce**
A,B two devices using patroni to form a cluster, when I stop A,B network communication

**Expected behavior**
patroni.log
```
2022-01-25 12:45:35,914 INFO: no action.  i am the leader with the lock
2022-01-25 12:45:45,912 INFO: Lock owner: dmoc-b4055d5930e2; I am dmoc-b4055d5930e2
2022-01-25 12:45:45,914 INFO: no action.  i am the leader with the lock
2022-01-25 12:45:55,912 INFO: Lock owner: dmoc-b4055d5930e2; I am dmoc-b4055d5930e2
2022-01-25 12:45:55,914 INFO: no action.  i am the leader with the lock
2022-01-25 12:46:05,912 INFO: Lock owner: dmoc-b4055d5930e2; I am dmoc-b4055d5930e2
2022-01-25 12:46:05,914 INFO: no action.  i am the leader with the lock
2022-01-25 12:46:15,912 INFO: Lock owner: dmoc-b4055d5930e2; I am dmoc-b4055d5930e2
2022-01-25 12:46:15,914 INFO: no action.  i am the leader with the lock
2022-01-25 12:46:20,362 WARNING: Connection dropped: socket connection broken
2022-01-25 12:46:20,362 WARNING: Transition to CONNECTING
2022-01-25 12:46:20,362 INFO: Zookeeper connection lost
2022-01-25 12:46:21,366 INFO: Connecting to 10.222.4.99:2181, use_ssl: False
2022-01-25 12:46:21,366 WARNING: Connection dropped: socket connection error: Connection refused
2022-01-25 12:46:21,366 INFO: Connecting to 10.222.4.99:2181, use_ssl: False
2022-01-25 12:46:21,367 WARNING: Connection dropped: socket connection error: Connection refused
2022-01-25 12:46:22,308 INFO: establishing a new patroni connection to the postgres cluster
2022-01-25 12:46:22,309 WARNING: Retry got exception: 'connection problems'
2022-01-25 12:46:22,316 ERROR: touch_member
Traceback (most recent call last):
  File "/home/fantom/share/Python-2.7/lib/site-packages/patroni/dcs/zookeeper.py", line 328, in touch_member
    self._client.set_async(self.member_path, encoded_data).get(timeout=1)
  File "/home/fantom/share/Python-2.7/lib/site-packages/kazoo/handlers/utils.py", line 69, in get
    raise self._exception
SessionExpiredError
2022-01-25 12:46:22,369 INFO: Connecting to 10.222.4.99:2181, use_ssl: False
2022-01-25 12:46:22,369 WARNING: Connection dropped: socket connection error: Connection refused
2022-01-25 12:46:22,570 WARNING: Failed connecting to Zookeeper within the connection retry policy.
2022-01-25 12:46:22,570 INFO: Zookeeper session lost, state: CLOSED
2022-01-25 12:46:22,584 INFO: Connecting to 10.222.4.99:2181, use_ssl: False
2022-01-25 12:46:22,584 WARNING: Connection dropped: socket connection error: Connection refused
2022-01-25 12:46:23,587 INFO: Connecting to 10.222.4.99:2181, use_ssl: False
2022-01-25 12:46:23,587 WARNING: Connection dropped: socket connection error: Connection refused
2022-01-25 12:46:24,590 INFO: Connecting to 10.222.4.99:2181, use_ssl: False
2022-01-25 12:46:24,590 WARNING: Connection dropped: socket connection error: Connection refused
2022-01-25 12:46:25,592 INFO: Connecting to 10.222.4.99:2181, use_ssl: False
2022-01-25 12:46:25,593 WARNING: Connection dropped: socket connection error: Connection refused
2022-01-25 12:46:25,593 INFO: Connecting to 10.222.4.99:2181, use_ssl: False
2022-01-25 12:46:25,593 WARNING: Connection dropped: socket connection error: Connection refused
2022-01-25 12:46:25,593 INFO: Connecting to 10.222.4.99:2181, use_ssl: False
2022-01-25 12:46:25,593 WARNING: Connection dropped: socket connection error: Connection refused
2022-01-25 12:46:27,598 INFO: Connecting to 10.222.4.99:2181, use_ssl: False
2022-01-25 12:46:27,598 WARNING: Connection dropped: socket connection error: Connection refused
2022-01-25 12:46:29,602 INFO: Connecting to 10.222.4.99:2181, use_ssl: False
2022-01-25 12:46:37,622 WARNING: Failed connecting to Zookeeper within the connection retry policy.
2022-01-25 12:46:37,622 INFO: Zookeeper session lost, state: CLOSED
2022-01-25 12:46:37,648 ERROR: Exception during Ha.shutdown
Traceback (most recent call last):
  File "/home/fantom/share/Python-2.7/lib/site-packages/patroni/__init__.py", line 138, in _shutdown
    self.ha.shutdown()
  File "/home/fantom/share/Python-2.7/lib/site-packages/patroni/ha.py", line 1475, in shutdown
    self.dcs.delete_leader(checkpoint_location)
  File "/home/fantom/share/Python-2.7/lib/site-packages/patroni/dcs/__init__.py", line 785, in delete_leader
    return self._delete_leader()
  File "/home/fantom/share/Python-2.7/lib/site-packages/patroni/dcs/zookeeper.py", line 345, in _delete_leader
    self._client.restart()
  File "/home/fantom/share/Python-2.7/lib/site-packages/kazoo/client.py", line 640, in restart
    self.start()
  File "/home/fantom/share/Python-2.7/lib/site-packages/kazoo/client.py", line 582, in start
    raise self.handler.timeout_exception("Connection time-out")
KazooTimeoutError: Connection time-out
2022-01-25 12:53:55,394 INFO: Connecting to 10.222.4.99:2181, use_ssl: False
2022-01-25 12:53:55,398 INFO: Zookeeper connection established, state: CONNECTED
2022-01-25 12:53:55,413 INFO: I am leader but not owner of the session. Removing leader node
2022-01-25 12:53:55,436 INFO: No PostgreSQL configuration items changed, nothing to reload.
2022-01-25 12:53:55,477 WARNING: Postgresql is not running.
2022-01-25 12:53:55,477 INFO: Lock owner: None; I am dmoc-b4055d5930e2
2022-01-25 12:53:55,482 INFO: pg_controldata:
Database system identifier: 7047900301484574708
  pg_control last modified: Tue Jan 25 12:33:26 2022
  Blocks per segment of large relation: 131072
  Size of a large-object chunk: 2048
  WAL block size: 8192
  Latest checkpoint's oldestActiveXID: 129120
  Latest checkpoint's TimeLineID: 4
  Bytes per WAL segment: 16777216
  Fake LSN counter for unlogged rels: 0/3E8
  max_connections setting: 1000
  Latest checkpoint location: 7/21B13EB0
  Float8 argument passing: by value
  Minimum recovery ending location: 0/0
  track_commit_timestamp setting: off
  Latest checkpoint's newestCommitTsXid: 0
  Latest checkpoint's NextMultiXactId: 1
  Maximum size of a TOAST chunk: 1996
  Maximum data alignment: 8
  Date/time type storage: 64-bit integers
  Database block size: 8192
  Data page checksum version: 0
  Time of latest checkpoint: Tue Jan 25 12:33:26 2022
  wal_log_hints setting: on
  Latest checkpoint's full_page_writes: on
  End-of-backup record required: no
  max_prepared_xacts setting: 0
  Latest checkpoint's NextMultiOffset: 0
  Backup start location: 0/0
  Latest checkpoint's oldestMultiXid: 1
  Mock authentication nonce: fb2de04d0f347667335c3346679850ffae700699a2b8bb8180c4a6390a9072df
  Latest checkpoint's NextOID: 42395
  Maximum columns in an index: 32
  Latest checkpoint's oldestXID: 479
  Catalog version number: 202007201
  max_worker_processes setting: 20
  Maximum length of identifiers: 64
  Min recovery ending loc's timeline: 0
  max_locks_per_xact setting: 64
  max_wal_senders setting: 10
  Latest checkpoint's NextXID: 0:129120
  Latest checkpoint's REDO location: 7/21B13E78
  Backup end location: 0/0
  Database cluster state: in production
  pg_control version number: 1300
  wal_level setting: replica
  Latest checkpoint's REDO WAL file: 000000040000000700000021
  Latest checkpoint's oldestCommitTsXid: 0
  Latest checkpoint's oldestXID's DB: 1
  Latest checkpoint's oldestMulti's DB: 1
  Latest checkpoint's PrevTimeLineID: 4
2022-01-25 12:53:55,490 INFO: doing crash recovery in a single user mode
2022-01-25 12:53:55,500 INFO: Lock owner: None; I am dmoc-b4055d5930e2
2022-01-25 12:53:55,500 INFO: not healthy enough for leader race
2022-01-25 12:53:55,501 INFO: doing crash recovery in a single user mode in progress
2022-01-25 12:53:55,572 INFO: Lock owner: dmoc-6c92bf849822; I am dmoc-b4055d5930e2
2022-01-25 12:53:55,573 INFO: doing crash recovery in a single user mode in progress
2022-01-25 12:53:56,094 WARNING: Postgresql is not running.
2022-01-25 12:53:56,095 INFO: Lock owner: dmoc-6c92bf849822; I am dmoc-b4055d5930e2
2022-01-25 12:53:56,100 INFO: pg_controldata:
....
```
postgresql.log
```
2022-01-25 12:03:26.877 CST [15580] LOG:  checkpoint starting: time
2022-01-25 12:03:34.111 CST [15580] LOG:  checkpoint complete: wrote 72 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=7.232 s, sync=0.001 s, total=7.234 s; sync files=3, longest=0.001 s, average=0.001 s; distance=417 kB, estimate=2107 kB
2022-01-25 12:13:02.894 CST [81429] LOG:  unexpected EOF on client connection with an open transaction
2022-01-25 12:23:02.387 CST [95832] LOG:  unexpected EOF on client connection with an open transaction
2022-01-25 12:33:02.601 CST [110760] LOG:  unexpected EOF on client connection with an open transaction
2022-01-25 12:33:26.191 CST [15580] LOG:  checkpoint starting: time
2022-01-25 12:33:26.309 CST [15580] LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.117 s, sync=0.001 s, total=0.119 s; sync files=1, longest=0.001 s, average=0.001 s; distance=2 kB, estimate=1896 kB
2022-01-25 12:43:11.337 CST [125548] LOG:  unexpected EOF on client connection with an open transaction
2022-01-25 12:46:18.612 CST [150842] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.612 CST [63438] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.612 CST [75136] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.612 CST [15609] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.612 CST [63996] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.612 CST [150843] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.612 CST [63981] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.612 CST [63123] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.612 CST [63983] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.612 CST [8336] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.612 CST [64130] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.612 CST [63986] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.612 CST [63995] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.612 CST [2802] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.612 CST [63221] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.612 CST [64334] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.612 CST [64060] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.613 CST [64270] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.613 CST [63857] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.613 CST [63658] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.613 CST [147354] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.613 CST [48962] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.613 CST [62944] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.613 CST [148286] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.613 CST [63940] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.613 CST [64061] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.614 CST [63982] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:46:18.614 CST [62733] FATAL:  terminating connection due to unexpected postmaster exit
2022-01-25 12:57:57.693 CST [68831] LOG:  starting PostgreSQL 13.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
2022-01-25 12:57:57.693 CST [68831] LOG:  listening on IPv4 address "0.0.0.0", port 5550
2022-01-25 12:57:57.694 CST [68831] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5550"
2022-01-25 12:57:57.694 CST [68831] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5550"
2022-01-25 12:57:57.698 CST [68857] LOG:  database system was interrupted; last known up at 2022-01-25 12:53:56 CST
2022-01-25 12:57:57.729 CST [68857] WARNING:  specified neither primary_conninfo nor restore_command
2022-01-25 12:57:57.729 CST [68857] HINT:  The database server will regularly poll the pg_wal subdirectory to check for files placed there.
2022-01-25 12:57:57.729 CST [68857] LOG:  entering standby mode
2022-01-25 12:57:57.729 CST [68857] LOG:  could not read from log segment 000000050000000700000021, offset 0: read 0 of 8192
2022-01-25 12:57:57.729 CST [68857] LOG:  invalid primary checkpoint record
2022-01-25 12:57:57.729 CST [68857] PANIC:  could not locate a valid checkpoint record
2022-01-25 12:57:57.766 CST [68867] FATAL:  the database system is starting up
```
pg_wal
```
$ ~ # ll /data/pgsql/pg_wal/
total 75316
-rw------- 1 daemon daemon 16777216 Jan 25 12:54 00000001000000070000001B
-rw------- 1 daemon daemon 16777216 Jan 25 12:54 00000002000000070000001B
-rw------- 1 daemon daemon 16777216 Jan 25 12:54 00000002000000070000001C
-rw------- 1 daemon daemon 16777216 Jan 25 12:54 00000002000000070000001D
-rw------- 1 daemon daemon       42 Jan 25 12:54 00000002.history
-rw------- 1 daemon daemon 10000000 Jan 25 12:54 00000003000000070000001D
-rw------- 1 daemon daemon       85 Jan 25 12:54 00000003.history
-rw------- 1 daemon daemon        0 Jan 25 12:54 00000004000000070000001D
-rw------- 1 daemon daemon        0 Jan 25 12:54 00000004000000070000001E
-rw------- 1 daemon daemon        0 Jan 25 12:54 00000004000000070000001F
-rw------- 1 daemon daemon        0 Jan 25 12:54 000000040000000700000020
-rw------- 1 daemon daemon        0 Jan 25 12:54 000000040000000700000021
-rw------- 1 daemon daemon        0 Jan 25 12:54 00000004.history
-rw------- 1 daemon daemon        0 Jan 25 12:54 000000050000000700000021
-rw------- 1 daemon daemon        0 Jan 25 12:54 000000050000000700000022
-rw------- 1 daemon daemon        0 Jan 25 12:54 000000050000000700000023
-rw------- 1 daemon daemon        0 Jan 25 12:54 000000050000000700000024
-rw------- 1 daemon daemon        0 Jan 25 12:54 000000050000000700000025
-rw------- 1 daemon daemon        0 Jan 25 12:54 00000005.history
drwx------ 2 daemon daemon     4096 Jan 25 12:54 archive_status/
```

**Screenshots**

**Environment**
- Patroni version: patronictl version 2.0.1
- PostgreSQL version: psql (13.3)
- DCS (and its version): Don't know; what is this?

**Patroni configuration file**
```
zookeeper:
  hosts: zk.server.sr:2181
postgresql:
  bin_dir: /home/fantom/party/pgsql/bin
  config_dir: /etc/postgresql-13
  callback:
    on_start: /usr/bin/postgresql.sh post_postgresql
  authentication:
    replication:
      username: repuser
      password: xxx
    superuser:
      username: sipadmin
      password: xxx
  data_dir: /data/pgsql
  listen: 0.0.0.0:5550
  connect_address: dmoc-xxx:5550
  basebackup:
    checkpoint: fast
    max-rate: 100M
name: dmoc-000000000314
tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
restapi:
  connect_address: dmoc-xxx:8008
  listen: dmoc-xxx:8008
bootstrap:
  dcs:
    retry_timeout: 10
    postgresql:
      use_slots: true
      use_pg_rewind: true
      parameters:
        hot_standby: on
        wal_keep_size: 50GB
        max_worker_processes: 16
        wal_keep_segments: 100
        wal_level: replica
        wal_log_hints: on
        max_replication_slots: 10
        max_connections: 1000
    loop_wait: 10
    synchronous_mode: false
    maximum_lag_on_failover: 20971520
    ttl: 30
    master_start_timeout: 30
namespace: /pgsqlcluster/
scope: pgsql
log:
  file_num: 2
  dir: /var/log/patroni
```

**patronictl show-config**
```
patronictl -c /etc/patroni/patroni.yml show-config
loop_wait: 10
master_start_timeout: 30
maximum_lag_on_failover: 20971520
postgresql:
  parameters:
    hot_standby: true
    max_connections: 1000
    max_replication_slots: 10
    max_worker_processes: 16
    wal_keep_segments: 100
    wal_keep_size: 50GB
    wal_level: replica
    wal_log_hints: true
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: false
ttl: 30

```

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.
not found

**Additional context**

**Comment by CyberDem0n** [comment]
I am unsure what exactly you did, but `PANIC:  could not locate a valid checkpoint record` is a clear indicator of data corruption, which is not a Patroni problem.


> Patroni version: patronictl version 2.0.1

This version is nearly 1.5 years old, since than many bugs have been fixed. Independently of your issues, Patroni must be upgraded.

**Comment by ChenJhua** [comment]
> I am unsure what exactly you did, but `PANIC: could not locate a valid checkpoint record` is a clear indicator of data corruption, which is not a Patroni problem.
> 
> > Patroni version: patronictl version 2.0.1
> 
> This version is nearly 1.5 years old, since than many bugs have been fixed. Independently of your issues, Patroni must be upgraded.

Upgrade if it can solve the problem, I can try to upgrade the Does the upgrade require any special treatment? Is it possible to just replace the patroni library?

**Comment by CyberDem0n** [comment]
Patroni upgrade requires installing a new version and restarting patroni.

But, please don't expect that Patroni will deal with data corruption.

**Comment by ChenJhua** [comment]
> Patroni upgrade requires installing a new version and restarting patroni.
> 
> But, please don't expect that Patroni will deal with data corruption.
Okay, I'll try the new version, thanks!
