### ISSUE TITLE
Rest API somtimes stops responding when switching certificates

### ISSUE THREAD

**Issue by ants** [zalando/patroni#2184]
Switching REST API certificates while there is a concurrent API request active results in the following error:

    2022-01-25 14:14:37,739 ERROR: Failed to reload config_file=postgres0.yml
    Traceback (most recent call last):
      File "/home/ants/work/patroni/patroni/patroni/__main__.py", line 74, in reload_config
        self.api.reload_config(self.config['restapi'])
      File "/home/ants/work/patroni/patroni/patroni/api.py", line 871, in reload_config
        self.__initialize(config['listen'], ssl_options)
      File "/home/ants/work/patroni/patroni/patroni/api.py", line 776, in __initialize
        self.__httpserver_init(host, port)
      File "/home/ants/work/patroni/patroni/patroni/api.py", line 755, in __httpserver_init
        HTTPServer.__init__(self, info[0][-1][:2], RestApiHandler)
      File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
        self.server_bind()
      File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
        socketserver.TCPServer.server_bind(self)
      File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
        self.socket.bind(self.server_address)
    OSError: [Errno 98] Address already in use

After this REST API is stuck in a state where it is not responding.

To reproduce:

* Create two keypairs {cert,key}{1,2}.pem, one with EE as country other with AU
* Configure postgres0.yml to use the keypair.
* Run attached python script to create a load on the API.
* Run attached shell script to swap between the certs continuously. Should get stuck within a few tries.

**Comment by ants** [comment]
Scripts are @ https://gist.github.com/ants/e39dadf0ec34bdccb7691aabfd42f78c
