### ISSUE TITLE
standby_leader tries to run checkpoint on main cluster leader for rewind

### ISSUE THREAD

**Issue by mbanck** [zalando/patroni#2194]
**Describe the bug**

I have a standby cluster (well only the single leader for now), that I restarted after it was down during a primary cluster switchover. During that, Patroni (rightfully) decided that it should run `pg_rewind` from the primary cluster's leader, then subsequently also decided to run `CHECKPOINT` on the primary cluster's leader and failed to find the superuser credentials (I did not put in any).

In any case, I don't think the standby cluster should be in the business of having the primary cluster's superuser credentials, or should those be the same everywhere? I guess rewind credentials are inevitable, if one wants to use that.

I debugged this a bit and what I see is that here:
```
INFO: running pg_rewind from remote_master:b642b724-81c0-11ec-85b1-00163ea51852
```
it still tries to use the `rewind_credentials`, but after this line in `rewind.py`, `checkpoint_status` is `None` (I guess because we are not a leader on startup?):

```
        checkpoint_status = leader.checkpoint_after_promote if isinstance(leader, Leader) else None
```

and it then wants to run checkpoint on the leader with superuser credentials:

```
        if checkpoint_status is None:  # master still runs the old Patroni
            leader_status = self._postgresql.checkpoint(self._conn_kwargs(leader, self._postgresql.config.superuser))
```

**To Reproduce**

1. Have a standby cluster that is configured to run `pg_rewind` and is healthy.
2. Shutdown patroni on the standby cluster
3. Introduce a timeline bump on the primary cluster, e.g. by switching away and back to the primary cluster leader
4. Start patroni on the standby cluster

**Expected behavior**

I would like the standby cluster to come up fine, or worst-case, re-clone from the primary cluster.

**Screenshots**

```
Jan 30 11:34:39 pg4 systemd[1]: patroni@11-main-standby.service: Consumed 1.949s CPU time.
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]: 2022-01-30 11:35:23,287 INFO: Selected new etcd server http://localhost:2379
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]: 2022-01-30 11:35:23,293 INFO: No PostgreSQL configuration items changed, nothing to reload.
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]: 2022-01-30 11:35:23,309 WARNING: Postgresql is not running.
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]: 2022-01-30 11:35:23,309 INFO: Lock owner: None; I am pg4
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]: 2022-01-30 11:35:23,314 INFO: pg_controldata:
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]:   pg_control version number: 1100
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]:   Catalog version number: 201809051
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]:   Database system identifier: 7054100582873615202
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]:   Database cluster state: shut down in recovery
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]:   pg_control last modified: Sun Jan 30 11:34:38 2022
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]:   Latest checkpoint location: 0/40000060
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]:   Latest checkpoint's REDO location: 0/40000028
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]:   Latest checkpoint's REDO WAL file: 0000001F0000000000000040
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]:   Latest checkpoint's TimeLineID: 31
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]:   Latest checkpoint's PrevTimeLineID: 31
[...]
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]: 2022-01-30 11:35:23,321 INFO: Local timeline=31 lsn=0/41000060
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]: 2022-01-30 11:35:23,343 INFO: master_timeline=33
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]: 2022-01-30 11:35:23,344 INFO: master: history=29        0/3A000178        no recovery target specified
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]: 30        0/3C000178        no recovery target specified
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]: 31        0/41000178        no recovery target specified
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]: 32        0/43000140        no recovery target specified
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]: 2022-01-30 11:35:23,359 INFO: running pg_rewind from remote_master:b642b724-81c0-11ec-85b1-00163ea51852
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]: 2022-01-30 11:35:23,366 ERROR: Exception during CHECKPOINT
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]: Traceback (most recent call last):
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]:   File "/usr/lib/python3/dist-packages/patroni/postgresql/__init__.py", line 600, in checkpoint
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]:     with get_connection_cursor(**connect_kwargs) as cur:
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]:   File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]:     return next(self.gen)
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]:   File "/usr/lib/python3/dist-packages/patroni/postgresql/connection.py", line 44, in get_connection_cursor
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]:     conn = psycopg.connect(**kwargs)
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]:   File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]: psycopg2.OperationalError: connection to server at "pg1" (10.0.3.122), port 5432 failed: fe_sendauth: no password supplied
Jan 30 11:35:23 pg4 patroni@11-main-standby[1371]: 2022-01-30 11:35:23,367 WARNING: Can not use remote_master:b642b724-81c0-11ec-85b1-00163ea51852 for rewind: not accessible or not healty
[ha loop starts again]
Jan 30 11:35:33 pg4 patroni@11-main-standby[1371]: 2022-01-30 11:35:33,304 WARNING: Postgresql is not running.
```

**Environment**
- Patroni version: 2.1.2
- PostgreSQL version: 11.14
- DCS (and its version): etcd 3.3.25

**Patroni configuration file**
```
cope: "11-main-standby"
namespace: "/postgresql-common/"
name: pg4
etcd:
  hosts:
    - 127.0.0.1:2379
restapi:
  listen: 10.0.3.66:8008
  connect_address: 10.0.3.66:8008
bootstrap:
  method: pg_createcluster
  pg_createcluster:
    command: /usr/share/patroni/pg_createcluster_patroni
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    standby_cluster:
      host: pg1
      primary_slot_name: 11_main_standby
    postgresql:
      use_pg_rewind: true
      remove_data_directory_on_rewind_failure: true
      remove_data_directory_on_diverged_timelines: true
      parameters:
      pg_hba:
      - local   all             all                                     peer
      - host    all             all             127.0.0.1/32            md5
      - host    all             all             ::1/128                 md5
      - host    all             all             10.0.3.66/24               md5
      - local   replication     all                                     peer
      - host    replication     all             127.0.0.1/32            md5
      - host    replication     all             ::1/128                 md5
      - host    replication     all             all                     md5
postgresql:
  create_replica_method:
    - pg_clonecluster
  pg_clonecluster:
    command: /usr/share/patroni/pg_clonecluster_patroni
  listen: "*:5432"
  connect_address: 10.0.3.66:5432
  use_unix_socket: true
  data_dir: /var/lib/postgresql/11/main-standby
  bin_dir: /usr/lib/postgresql/11/bin
  config_dir: /etc/postgresql/11/main-standby
  pgpass: /var/lib/postgresql/11-main-standby.pgpass
  authentication:
    replication:
      username: "replicator"
      password: "replicator"
    superuser:
      username: postgres
      password:
    rewind:
      username: "postgres_rewind"
      password: "postgres_rewind"
  parameters:
    unix_socket_directories: '/var/run/postgresql/'
    logging_collector: 'on'
    log_directory: '/var/log/postgresql'
    log_filename: 'postgresql-11-main-standby.log'
```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters: null
  pg_hba:
  - local   all             all                                     peer
  - host    all             all             127.0.0.1/32            md5
  - host    all             all             ::1/128                 md5
  - host    all             all             10.0.3.66/24               md5
  - local   replication     all                                     peer
  - host    replication     all             127.0.0.1/32            md5
  - host    replication     all             ::1/128                 md5
  - host    replication     all             all                     md5
  remove_data_directory_on_diverged_timelines: true
  remove_data_directory_on_rewind_failure: true
  use_pg_rewind: true
retry_timeout: 10
standby_cluster:
  host: pg1
  primary_slot_name: 11_main_standby
ttl: 30
```

**Comment by mbanck** [comment]
By the @df7cb suggested on irc that we could let the rewind user run `CHECKPOINT` via granting execute permissions on `pg_start_backup`/`pg_stop_backup`, and I checked that this works, i.e. change https://github.com/zalando/patroni/blob/master/patroni/postgresql/rewind.py#L337 to use `rewind_credentials` instead of `superuser` and change https://github.com/zalando/patroni/blob/master/patroni/postgresql/__init__.py#L606 to say

```
                cur.execute('SELECT pg_catalog.pg_start_backup(\'checkpoint\', true, false)')
                cur.execute('SELECT pg_catalog.pg_stop_backup(false, false)')
```

Is this something you have thought of in the past and discarded (maybe in order not to interfere with regular backups)?  If not, I can prepare a PR for this.
