### ISSUE TITLE
Not able to replicate from Master

### ISSUE THREAD

**Issue by AllwynJesu** [zalando/patroni#2202]
Hi,

I am seeing below when starting the 2nd node in the cluster. 

```
2022-02-04 14:23:01,877 INFO: Lock owner: bos01-app02; I am bos01-app01
2022-02-04 14:23:01,877 INFO: does not have lock
2022-02-04 14:23:01,877 INFO: establishing a new patroni connection to the postgres cluster
2022-02-04 14:23:01.900 UTC [427344] ERROR:  cannot execute SQL commands in WAL sender for physical replication
2022-02-04 14:23:01,900 ERROR: Can not fetch local timeline and lsn from replication connection
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/postgresql/__init__.py", line 663, in get_local_timeline_lsn_from_replication_connection
    cur.execute('IDENTIFY_SYSTEM')
psycopg2.errors.InternalError_: cannot execute SQL commands in WAL sender for physical replication

2022-02-04 14:23:01,905 INFO: no action.  i am a secondary and i am following a leader
2022-02-04 14:23:10,932 INFO: Lock owner: app02; I am app01
2022-02-04 14:23:10,932 INFO: does not have lock
2022-02-04 14:23:10.938 UTC [427346] ERROR:  cannot execute SQL commands in WAL sender for physical replication
2022-02-04 14:23:10,938 ERROR: Can not fetch local timeline and lsn from replication connection
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/postgresql/__init__.py", line 663, in get_local_timeline_lsn_from_replication_connection
    cur.execute('IDENTIFY_SYSTEM')
psycopg2.errors.InternalError_: cannot execute SQL commands in WAL sender for physical replication
```
I tried psycopg2=2.8.6 but got the same error. Here is my patroni configuration. I am using PostgreSQL 12 and Patroni 1.6.4

```
scope: app
namespace: /cluster/
name: node1
restapi:
  listen: X.X.X.86:8008
etcd:
  hosts: X.X.X.245:2379,X.X.X.86:2379,X.X.X.89:2379
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      parameters:
        wal_level: replica
        max_connections: 100
      pg_hba:
        - local all all trust
        - host replication replication_user 0.0.0.0/0 md5
        - host all all 0.0.0.0/0 md5
  initdb:
    - locale: C.UTF-8
    - encoding: UTF8
    - data-checksums
  users:
    appuser:
      password: appuser
      options:
        - createrole
        - createdb
        - login
postgresql:
  listen: X.X.X.86:5432
  data_dir: /postgresql/data
  pgpass: /postgresql/pgpass
  authentication:
    replication:
      username: replication_user
      password: replication_user
    superuser:
      username: patroni_superuser
      password: patroni_superuser
tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
```
Please let me know if I am missing something in the configuration.

**Comment by CyberDem0n** [comment]
> Patroni 1.6.4

Please upgrade
