### ISSUE TITLE
Excessive tracebacks when HAProxy polls (TLS-) REST API

### ISSUE THREAD

**Issue by bluthg** [zalando/patroni#2229]
**Describe the bug**
Since setting up HAProxy (with check-ssl), we're being flooded with messages like
```
2022-02-25 11:54:58,601 WARNING: Exception happened during processing of request from <redacted>
2022-02-25 11:54:58,603 WARNING: Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3/dist-packages/patroni/api.py", line 642, in handle_one_request
    BaseHTTPRequestHandler.handle_one_request(self)
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/lib/python3/dist-packages/patroni/api.py", line 178, in do_GET
    self._write_status_response(status_code, response)
  File "/usr/lib/python3/dist-packages/patroni/api.py", line 94, in _write_status_response
    self._write_json_response(status_code, response)
  File "/usr/lib/python3/dist-packages/patroni/api.py", line 53, in _write_json_response
    self._write_response(status_code, json.dumps(response, default=str), content_type='application/json')
  File "/usr/lib/python3/dist-packages/patroni/api.py", line 50, in _write_response
    self.wfile.write(body.encode('utf-8'))
  File "/usr/lib/python3.8/socketserver.py", line 826, in write
    self._sock.sendall(b)
  File "/usr/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
ConnectionResetError: [Errno 104] Connection reset by peer
```
Did not check if the same happens when the REST API is not TLS-enabled!

**To Reproduce**
* Configure a HAProxy with e.g.
`server xxxxx_5432 x.x.x.x:5432 maxconn 1000 check check-ssl ca-file XXXXXXXXX.pem port xxxx`
* `tail -f  var/log/{syslog,messages}`

**Expected behavior**
Ignore premature SSL disconnections. E.g., add an expection to `handle_error(request, client_address)` in `api.py`.

**Environment**
- Patroni version: 2.1.2-2.pgdg18.04+1
- PostgreSQL version: N/A
- DCS (and its version): N/A

**Have you checked Patroni logs?**
See above.

**Have you tried to use GitHub issue search?**
Yes

**Comment by bluthg** [comment]
Additional information:
We have two haproxy sections, one polling for rw and the other polling for ro (see below). Will try to narrow it down if it's the replies with 200 or the ones with 503.

Also will try to force `HTTP/1.1` (default for `httpchk` seems to be `HTTP/1.0` according to http://cbonte.github.io/haproxy-dconv/2.0/configuration.html#4.2-option%20httpchk)

```
    mode        tcp
    option httpchk GET /primary
    http-check expect status 200
    
     mode        tcp
    option httpchk GET /replica?lag=1MB
    http-check expect status 200
```

**Comment by bluthg** [comment]
Ok, NVM I guess. After the reload of haproxy, the error messages went away. Even without the `HTTP/1.1` ... sigh.

**Comment by bluthg** [comment]
Hmmm, they re-appeared.
Now trying to determine if there's a connection between the 200/503 result and the traceback.

**Comment by CyberDem0n** [comment]
@bluthg you have to use OPTIONS instead of GET: `option httpchk OPTIONS /primary`

**Comment by bluthg** [comment]
That has indeed made the errors disappear. Thanks!

It might make sense to incorporate that in the example haproxy.cfg (and maybe also add a section with `check-ssl`?)!

At least the PGDG pkg's one only contains
`    option httpchk`
