### ISSUE TITLE
Patroni cannot connect to PostgreSQL if password starts with "!" symbol

### ISSUE THREAD

**Issue by xinferum** [zalando/patroni#2253]
**Describe the bug**
Patroni cannot connect to PostgreSQL if password starts with "!" symbol. If we change postgres user password to password starts with "!", then, after change password in patroni.yml configuration file, we can't use patronictl and after restart patroni can't started.

If the symbol "!" is not the first in the password, then there is no problem.

I'm guessing it might have something to do with the yml format and how it treats "!" at the beginning of a word.

**To Reproduce**
1. Change postgres user password in PostgreSQL cluster: `alter user postgres with password '!qwe123';`
2. Change postgres password in patroni.yml configuration files on servers in cluster:
  ```
  postgresql:
    ...
    authentication:
      ...
      superuser:
        username: postgres
        password: !qwe123
  ```
3. Try to use patronictl utility or restart patroni service on any cluster node.
4. You get some errors:
```
patronictl -c /etc/patroni/patroni.yml list postgres-cluster
Traceback (most recent call last):
  File "/usr/local/bin/patronictl", line 11, in <module>
    sys.exit(ctl())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1656, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/patroni/ctl.py", line 152, in ctl
    ctx.obj = load_config(config_file, dcs)
  File "/usr/local/lib/python3.6/site-packages/patroni/ctl.py", line 113, in load_config
    config = Config(path, validator=None).copy()
  File "/usr/local/lib/python3.6/site-packages/patroni/config.py", line 100, in __init__
    self._local_configuration = self._load_config_file()
  File "/usr/local/lib/python3.6/site-packages/patroni/config.py", line 149, in _load_config_file
    config = self._load_config_path(self._config_file)
  File "/usr/local/lib/python3.6/site-packages/patroni/config.py", line 143, in _load_config_path
    config = yaml.safe_load(f)
  File "/usr/local/lib64/python3.6/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib64/python3.6/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib64/python3.6/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib64/python3.6/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/usr/local/lib64/python3.6/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/local/lib64/python3.6/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/usr/local/lib64/python3.6/site-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib64/python3.6/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/local/lib64/python3.6/site-packages/yaml/constructor.py", line 429, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!qwe123'
  in "/etc/patroni/patroni.yml", line 167, column 17
```
```
systemctl status patroni
● patroni.service - Runners to orchestrate a high-availability PostgreSQL - patroni
   Loaded: loaded (/etc/systemd/system/patroni.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2022-03-25 14:58:04 MSK; 1min 58s ago
  Process: 18375 ExecStart=/usr/local/bin/patroni /etc/patroni/patroni.yml (code=exited, status=1/FAILURE)
 Main PID: 18375 (code=exited, status=1/FAILURE)
   CGroup: /system.slice/patroni.service

Mar 25 14:58:04 postgres1 systemd[1]: Stopped Runners to orchestrate a high-availability PostgreSQL - patroni.
Mar 25 14:58:04 postgres1 systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL - patroni.
Mar 25 14:58:04 postgres1 systemd[1]: patroni.service: main process exited, code=exited, status=1/FAILURE
Mar 25 14:58:04 postgres1 systemd[1]: Unit patroni.service entered failed state.
Mar 25 14:58:04 postgres1 systemd[1]: patroni.service failed.
```

**Expected behavior**
Normal patroni working after password change.

**Environment**
- Patroni version: 2.1.3
- PostgreSQL version: 14.2
- DCS (and its version): Etcd 3.3.27

**Patroni configuration file**
```
...	  
postgresql:
  listen: 192.168.56.125,127.0.0.1:5432
  connect_address: 192.168.56.125:5432
  use_unix_socket: true
  data_dir: /var/lib/pgsql/14/data
  bin_dir: /usr/pgsql-14/bin
  config_dir: /var/lib/pgsql/14/data
  pgpass: /var/lib/pgsql/.pgpass_patroni
  authentication:
    replication:
      username: *****
      password: *****
    superuser:
      username: postgres
      password: !qwe123
#    rewind:  # Has no effect on postgres 10 and lower
#      username: rewind_user
#      password: rewind_password
  parameters:
    unix_socket_directories: /var/run/postgresql
...
```

**Have you checked PostgreSQL logs?**
Yes, it is not PostgreSQL side problem.

**Have you tried to use GitHub issue search?**
Yes but i didn't find it.

**Comment by CyberDem0n** [comment]
Not a Patroni problem.

The exclamation mark in YAML has a special meaning, you have to explicitly quote the password string:
```yaml
postgresql:
  authentication:
    superuser:
      password: '!qwe123'
```

**Comment by xinferum** [comment]
> Not a Patroni problem.
> 
> The exclamation mark in YAML has a special meaning, you have to explicitly quote the password string:
> 
> ```yaml
> postgresql:
>   authentication:
>     superuser:
>       password: '!qwe123'
> ```

Yes, that solves the problem. So the reason is in the features of yml. thanks!
