### ISSUE TITLE
Exception when working with leader ... in check_leader_is_not_in_recovery ... permission denied for database "postgres"

### ISSUE THREAD

**Issue by xinferum** [zalando/patroni#2256]
**Describe the bug**
After upgrade patroni from 2.1.2 to 2.1.3 we show error in patroni.log on replicas:
```
2022-03-30 13:48:05,887 INFO: Lock owner: postgres2; I am postgres1
2022-03-30 13:48:05,898 INFO: Local timeline=2 lsn=0/B0000A0
2022-03-30 13:48:05,906 ERROR: Exception when working with leader
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/rewind.py", line 60, in check_leader_is_not_in_recovery
    with get_connection_cursor(connect_timeout=3, options='-c statement_timeout=2000', **conn_kwargs) as cur:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 44, in get_connection_cursor
    conn = psycopg.connect(**kwargs)
  File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "192.168.56.126", port 5432 failed: FATAL:  permission denied for database "postgres"
DETAIL:  User does not have CONNECT privilege.
```
At the same time, on the master in the logs, we see that the replicas are trying to connect under the replication user (we call it replicator) to the master:
```
2022-03-30 13:48:14.812 MSK [1484-1] app=[[unknown]],client=[192.168.56.125(15720)] [replicator@postgres], [vxid:6/13 txid:0] [startup] FATAL:  permission denied for database "postgres"
2022-03-30 13:48:14.812 MSK [1484-2] app=[[unknown]],client=[192.168.56.125(15720)] [replicator@postgres], [vxid:6/13 txid:0] [startup] DETAIL:  User does not have CONNECT privilege.
2022-03-30 13:48:19.060 MSK [1503-1] app=[[unknown]],client=[192.168.56.127(27352)] [replicator@postgres], [vxid:6/14 txid:0] [startup] FATAL:  permission denied for database "postgres"
2022-03-30 13:48:19.060 MSK [1503-2] app=[[unknown]],client=[192.168.56.127(27352)] [replicator@postgres], [vxid:6/14 txid:0] [startup] DETAIL:  User does not have CONNECT privilege.
```
The replicator user has only rights to replicate in PostgreSQL and is registered in the patroni.yml configuration file:
```
authentication:
  replication:
    username: replicator
    password: '*****'
```
And accordingly, it does not have rights to connect and should not have it, it is used only for replication.
In version 2.1.3, for some reason, it was the replication user that was used by the check_leader_is_not_in_recovery() function.

I found a commit where the check_leader_is_not_in_recovery connection credentials were changed - https://github.com/zalando/patroni/commit/3e1076a5746b4d7f313eaba0ff374824644c8ab1 which was created to address the issue https://github.com/zalando/patroni/issues/2162.

This is an incorrect solution, if the postgres user cannot be used to remotely connect to the master, then you must use the rewind user as specified in the configuration file https://github.com/zalando/patroni/blob/master/postgres0.yml:
```
rewind: # Has no effect on postgres 10 and lower
  username: rewind_user
  password: rewind_password
```
The user for replication does not imply other rights, except for the implementation of replication.

We were forced to downgrade to version 2.1.2 before resolving this issue.

**To Reproduce**
Upgrade your patroni cluster to 2.1.3 version.

**Expected behavior**
The user for replication is not used for other purposes and does not require extra rights.

**Environment**
- Patroni version: 2.1.3
- PostgreSQL version: 14.2
- DCS (and its version): Etcd 3.3.27

**Patroni configuration file**
```
---

scope: postgres-cluster
name: postgres1
namespace: /service/

log:
  level: INFO
  traceback_level: ERROR
  format: '%(asctime)s %(levelname)s: %(message)s'
  dateformat: ''
  max_queue_size: 1000
  dir: /var/log/patroni
  file_num: 4
  file_size: 25000000
  loggers:
    patroni.postmaster: WARNING
    urllib3: WARNING

restapi:
  listen: 192.168.56.125:8008
  connect_address: 192.168.56.125:8008
#  certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
#  keyfile: /etc/ssl/private/ssl-cert-snakeoil.key
#  authentication:
#    username: username
#    password: 'password'

etcd:
  hosts: 192.168.56.125:2379,192.168.56.126:2379,192.168.56.127:2379

bootstrap:
  method: initdb
  dcs:
    ttl: 60
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: true
    synchronous_mode_strict: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:

	...

#  initdb:  # List options to be passed on to initdb
#    - encoding: UTF8
#    - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
    - host replication replicator 127.0.0.1/32 md5
    - host all all 0.0.0.0/0 md5


postgresql:
  listen: 192.168.56.125,127.0.0.1:5432
  connect_address: 192.168.56.125:5432
  use_unix_socket: true
  data_dir: /var/lib/pgsql/14/data
  bin_dir: /usr/pgsql-14/bin
  config_dir: /var/lib/pgsql/14/data
  pgpass: /var/lib/pgsql/.pgpass_patroni
  authentication:
    replication:
      username: replicator
      password: '*****'
    superuser:
      username: postgres
      password: '*****'
#    rewind:  # Has no effect on postgres 10 and lower
#      username: rewind_user
#      password: 'rewind_password'
  parameters:
    unix_socket_directories: /var/run/postgresql


  remove_data_directory_on_rewind_failure: true
  remove_data_directory_on_diverged_timelines: false

  callbacks:
    on_start: /etc/patroni/callback.sh
    on_stop: /etc/patroni/callback.sh
    on_restart: /etc/patroni/callback.sh
    on_reload: /etc/patroni/callback.sh
    on_role_change: /etc/patroni/callback.sh

  create_replica_methods:
    - basebackup
  basebackup:
    max-rate: '100M'
    checkpoint: 'fast'


watchdog:
  mode: off  # Allowed values: off, automatic, required
  device: /dev/watchdog
  safety_margin: 5

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false

  # specify a node to replicate from (cascading replication)
#  replicatefrom: (node name)
```

**Have you checked Patroni logs?**
```
2022-03-30 13:48:05,887 INFO: Lock owner: postgres2; I am postgres1
2022-03-30 13:48:05,898 INFO: Local timeline=2 lsn=0/B0000A0
2022-03-30 13:48:05,906 ERROR: Exception when working with leader
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/rewind.py", line 60, in check_leader_is_not_in_recovery
    with get_connection_cursor(connect_timeout=3, options='-c statement_timeout=2000', **conn_kwargs) as cur:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 44, in get_connection_cursor
    conn = psycopg.connect(**kwargs)
  File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "192.168.56.126", port 5432 failed: FATAL:  permission denied for database "postgres"
DETAIL:  User does not have CONNECT privilege.
```

**Have you checked PostgreSQL logs?**
```
2022-03-30 13:48:14.812 MSK [1484-1] app=[[unknown]],client=[192.168.56.125(15720)] [replicator@postgres], [vxid:6/13 txid:0] [startup] FATAL:  permission denied for database "postgres"
2022-03-30 13:48:14.812 MSK [1484-2] app=[[unknown]],client=[192.168.56.125(15720)] [replicator@postgres], [vxid:6/13 txid:0] [startup] DETAIL:  User does not have CONNECT privilege.
2022-03-30 13:48:19.060 MSK [1503-1] app=[[unknown]],client=[192.168.56.127(27352)] [replicator@postgres], [vxid:6/14 txid:0] [startup] FATAL:  permission denied for database "postgres"
2022-03-30 13:48:19.060 MSK [1503-2] app=[[unknown]],client=[192.168.56.127(27352)] [replicator@postgres], [vxid:6/14 txid:0] [startup] DETAIL:  User does not have CONNECT privilege.
```

**Have you tried to use GitHub issue search?**
I found the original issue https://github.com/zalando/patroni/issues/2162 to fix which changed the behavior of the check_leader_is_not_in_recovery() function, and the commit that made the change https://github.com/zalando/patroni/commit/3e1076a5746b4d7f313eaba0ff374824644c8ab1.

**Additional context**
In our opinion, to solve the problem https://github.com/zalando/patroni/issues/2162 in this way is incorrect and the commit https://github.com/zalando/patroni/commit/3e1076a5746b4d7f313eaba0ff374824644c8ab1 needs to be revised.

**Comment by CyberDem0n** [comment]
Please grant CONNECT privilege on postgres database to the replication user. And the problem is solved.
