### ISSUE TITLE
Patroni throws a traceback to a TCP RST segment from haproxy

### ISSUE THREAD

**Issue by victor-sudakov** [zalando/patroni#2278]
**Describe the bug**
Haproxy 2.5.1 performs a [httpchk](https://www.haproxy.com/documentation/hapee/latest/onepage/#4.2-option%20httpchk) to the Patroni REST API and finishes it with a TCP RST segment. This looks like normal behavior. Patroni however reacts with a Traceback in its log complaning about "ConnectionResetError: [Errno 104] Connection reset by peer"

**TCP Session**
![haproxy_rst](https://user-images.githubusercontent.com/12457866/163882682-52aaaf97-0c1d-4c5c-b271-1406cf46728e.png)

**Patroni log snippet**
```
2022-04-15 01:58:48,093 WARNING: Exception happened during processing of request from 172.19.69.216:52962 
2022-04-15 01:58:48,094 WARNING: Exception happened during processing of request from 172.19.69.216:40907 
2022-04-15 01:58:48,094 WARNING: Traceback (most recent call last):
  File "/usr/lib/python3.9/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.9/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.9/http/server.py", line 427, in handle  
    self.handle_one_request()
  File "/usr/lib/python3/dist-packages/patroni/api.py", line 652, in handle_one_request
    BaseHTTPRequestHandler.handle_one_request(self)
  File "/usr/lib/python3.9/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/lib/python3/dist-packages/patroni/api.py", line 178, in do_GET
    self._write_status_response(status_code, response)
  File "/usr/lib/python3/dist-packages/patroni/api.py", line 94, in _write_status_response
    self._write_json_response(status_code, response)
  File "/usr/lib/python3/dist-packages/patroni/api.py", line 53, in _write_json_response
    self._write_response(status_code, json.dumps(response, default=str), content_type='application/json')
  File "/usr/lib/python3/dist-packages/patroni/api.py", line 50, in _write_response
    self.wfile.write(body.encode('utf-8'))
  File "/usr/lib/python3.9/socketserver.py", line 799, in write  
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
```
**Expected behavior**
There should be no tracebacks and connection reset errors in the Patroni log. They clutter the log and provide no useful information.

**Environment**
- Patroni version: patroni/bullseye-pgdg,now 2.1.3-2
- PostgreSQL version: 13.6
- DCS (and its version): consul v1.11.4

**Comment by victor-sudakov** [comment]
Looks like it's considered normal for haproxy: https://discourse.haproxy.org/t/connection-reset-seen-every-2-sec-haproxy/2156

**Comment by CyberDem0n** [comment]
You need to use request method `OPTIONS`: https://github.com/zalando/patroni/blob/5f6197aaad3ab0fb6c7eea9b8dd3cf6f141a616e/extras/confd/templates/haproxy.tmpl#L21

**Comment by victor-sudakov** [comment]
Thanks a lot, a great workaround. This is even [documented](https://patroni.readthedocs.io/en/latest/rest_api.html?highlight=%2Fleader#health-check-endpoints) in _If you don’t want or don’t need the JSON document, you might consider using the OPTIONS method instead of GET_.

It was just non-trivial to make a connection. Thank you again.

**Comment by sigio** [comment]
I couldn't get it working with OPTIONS requests... and solved it by switching to tcp checks, and just bruteforcing the http bits:

```
    option tcp-check
    tcp-check send    "OPTIONS /master HTTP/1.0\r\nHost: localhost\r\n\r\n"
    tcp-check expect  string "200 OK"
```

I'm using HAProxy version 2.4.24-0ubuntu0.22.04.2 and patroni 1.6.4
