### ISSUE TITLE
Replica in crash-loop after Patroni upgrade from 2.0.1 to 2.1.3

### ISSUE THREAD

**Issue by le-duane** [zalando/patroni#2289]
**Describe the bug**
After patching a replica from Patroni 2.0.1 to 2.1.3 and restarting, Postgres is getting restarted by Patroni before it has a chance to fully stand up.

Patroni starts Postgres

```
2022-05-06 05:17:14.961 UTC [113] LOG:  database system was shut down in recovery at 2022-05-06 05:16:58 UTC
2022-05-06 05:17:14.961 UTC [114] LOG:  connection received: host=[local]
2022-05-06 05:17:14.962 UTC [114] FATAL:  the database system is starting up
```

This repeats for a while

```
2022-05-06 05:17:37,384 INFO: Lock owner: db-c-0; I am db-b-0
2022-05-06 05:17:37,384 INFO: restarting after failure in progress
2022-05-06 05:17:38.158 UTC [236] LOG:  connection received: host=[local]
2022-05-06 05:17:38.158 UTC [236] FATAL:  the database system is starting up
```

Patroni assumes cached role

```
2022-05-06 05:18:17,783 WARNING: Retry got exception: 'connection problems'
2022-05-06 05:18:17,783 WARNING: Failed to determine PostgreSQL state from the connection, falling back to cached role
```

Patroni restarts Postgres after failed checkpoint

```
2022-05-06 05:18:41,557 INFO: no action. I am (db-b-0), a secondary, and following a leader (db-c-0)
2022-05-06 05:18:41.559 UTC [436] LOG:  connection received: host=[local]
2022-05-06 05:18:41.559 UTC [436] FATAL:  the database system is starting up
2022-05-06 05:18:41,558 WARNING: Loop time exceeded, rescheduling immediately.
2022-05-06 05:18:41,559 ERROR: Exception during CHECKPOINT
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 600, in checkpoint
    with get_connection_cursor(**connect_kwargs) as cur:
  File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 44, in get_connection_cursor
    conn = psycopg.connect(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  the database system is starting up

2022-05-06 05:18:41.560 UTC [111] LOG:  received fast shutdown request
2022-05-06 05:18:41.566 UTC [117] LOG:  shutting down
2022-05-06 05:18:41.580 UTC [111] LOG:  database system is shut down
```

**To Reproduce**
Restart replica of a cluster which is under load at Patroni version 2.1.3 w/primary still at 2.0.1

This was not an issue for any replica I patched which could quickly catch up on the WAL backlog that occurred while it was restarting.

**Expected behavior**
Postgres be allowed to start up completely and resume replication from primary node.

**Environment**
- Patroni version: 2.1.3
- PostgreSQL version: 12.7
- DCS (and its version): k8s 1.19

**Config**
```
loop_wait: 10
master_start_timeout: 300
master_stop_timeout: 135
maximum_lag_on_failover: 0
postgresql:
  parameters:
    max_connections: 650
    max_locks_per_transaction: 64
    max_prepared_transactions: 0
    max_replication_slots: 10
    max_wal_senders: 10
    max_worker_processes: 8
    track_commit_timestamp: 'off'
    wal_keep_segments: 2560
    wal_level: logical
    wal_log_hints: 'on'
  use_pg_rewind: false
  use_slots: false
retry_timeout: 50
synchronous_mode: false
ttl: 120
```

**Have you checked Patroni logs?**
Provided above

**Have you checked PostgreSQL logs?**
Provided above

**Have you tried to use GitHub issue search?**
Yes

**Comment by CyberDem0n** [comment]
I can't reproduce it. You need to provide more details.

**Comment by CyberDem0n** [comment]
Ok, I think that now I understand what is going on (only 12 and 13 are affected).
Will create a fix on Monday.

**Comment by le-duane** [comment]
Thank you so much @CyberDem0n for looking into this. I'll be standing by to test

**Comment by le-duane** [comment]
Thanks for the MR @CyberDem0n,

I haven't finished testing yet, but after resurrecting a Postgres 12 replica that was affected by this issue and applying this patch, it was able to continue recovering without interruption
