### ISSUE TITLE
conflict with systemd-managed DB or patroni should start DB

### ISSUE THREAD

**Issue by msvorad** [zalando/patroni#2293]
Hello,

How should be patroni used on a systemd-managed system? Patroni (2.0.1 version) is used on Ubuntu 18.04 with postgres that comes with systemd unit file. We discovered that patroni tries to connect to a postgres instance during startup (tries to connect to localhost:5432). DB has to be started (obviously) before patroni itself. Systemd handles DB startup and starts Patroni after.
However, it seems that Patroni "steals" the DB from systemd control - it probably uses `pg_ctl` command to stop/start/restart/whatever the DB. But the systemd unit becomes failed from systemd perspective (even though DB as such runs). Postgres processes are moved to patroni (patroni is parent). This approach does not seem right:
- start postgres with systemd (so that patroni can start)
- have postgres systemd unit failed in long term (since patroni manages DB itself)
I believe that patroni should start the DB (once patroni is started) and DB should not be managed by systemd at all. Is this possible? Or am I overlooking something?:
```
root@patroni-0:~# systemctl status patroni  ## patroni failed to start (since DB was not started)
● patroni.service - Patroni service
   Loaded: loaded (/etc/systemd/system/patroni.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2022-05-09 12:40:15 UTC; 18s ago
     Docs: https://github.com/zalando/patroni
  Process: 1088 ExecStart=/usr/local/bin/patroni /etc/patroni/config.yaml (code=exited, status=1/FAILURE)
 Main PID: 1088 (code=exited, status=1/FAILURE)

May 09 12:40:15 patroni-0 patroni[1088]:     self.postgresql = Postgresql(self.config['postgresql'])
May 09 12:40:15 patroni-0 patroni[1088]:   File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 111, in __init__
May 09 12:40:15 patroni-0 patroni[1088]:     self.set_role('master' if self.is_leader() else 'replica')
May 09 12:40:15 patroni-0 patroni[1088]:   File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 338, in is_leader
May 09 12:40:15 patroni-0 patroni[1088]:     return bool(self._cluster_info_state_get('timeline'))
May 09 12:40:15 patroni-0 patroni[1088]:   File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 318, in _cluster_info_state_get
May 09 12:40:15 patroni-0 patroni[1088]:     raise PostgresConnectionException(self._cluster_info_state['error'])
May 09 12:40:15 patroni-0 patroni[1088]: patroni.exceptions.PostgresConnectionException: "'Too many retry attempts'"
May 09 12:40:15 patroni-0 systemd[1]: patroni.service: Main process exited, code=exited, status=1/FAILURE
May 09 12:40:15 patroni-0 systemd[1]: patroni.service: Failed with result 'exit-code'.
root@patroni-0:~# 
root@patroni-0:~# 
root@patroni-0:~# 
root@patroni-0:~# journalctl -b -u patroni ## Full patroni failure message
-- Logs begin at Mon 2022-05-09 12:13:37 UTC, end at Mon 2022-05-09 12:40:37 UTC. --
May 09 12:39:57 patroni-0 systemd[1]: Started Patroni service.
May 09 12:40:13 patroni-0 patroni[1088]: 2022-05-09 12:40:13,227 INFO: Selected new etcd server http://10.132.0.92:2379
May 09 12:40:13 patroni-0 patroni[1088]: 2022-05-09 12:40:13,233 INFO: No PostgreSQL configuration items changed, nothing to reload.
May 09 12:40:13 patroni-0 patroni[1088]: 2022-05-09 12:40:13,343 INFO: establishing a new patroni connection to the postgres cluster
May 09 12:40:14 patroni-0 patroni[1088]: 2022-05-09 12:40:14,079 INFO: establishing a new patroni connection to the postgres cluster
May 09 12:40:14 patroni-0 patroni[1088]: 2022-05-09 12:40:14,090 WARNING: Retry got exception: 'connection problems'
May 09 12:40:14 patroni-0 patroni[1088]: localhost:5432 - rejecting connections
May 09 12:40:15 patroni-0 patroni[1088]: Traceback (most recent call last):
May 09 12:40:15 patroni-0 patroni[1088]:   File "/usr/local/bin/patroni", line 11, in <module>
May 09 12:40:15 patroni-0 patroni[1088]:     sys.exit(main())
May 09 12:40:15 patroni-0 patroni[1088]:   File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 170, in main
May 09 12:40:15 patroni-0 patroni[1088]:     return patroni_main()
May 09 12:40:15 patroni-0 patroni[1088]:   File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 138, in patroni_main
May 09 12:40:15 patroni-0 patroni[1088]:     abstract_main(Patroni, schema)
May 09 12:40:15 patroni-0 patroni[1088]:   File "/usr/local/lib/python3.6/dist-packages/patroni/daemon.py", line 98, in abstract_main
May 09 12:40:15 patroni-0 patroni[1088]:     controller = cls(config)
May 09 12:40:15 patroni-0 patroni[1088]:   File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 33, in __init__
May 09 12:40:15 patroni-0 patroni[1088]:     self.postgresql = Postgresql(self.config['postgresql'])
May 09 12:40:15 patroni-0 patroni[1088]:   File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 111, in __init__
May 09 12:40:15 patroni-0 patroni[1088]:     self.set_role('master' if self.is_leader() else 'replica')
May 09 12:40:15 patroni-0 patroni[1088]:   File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 338, in is_leader
May 09 12:40:15 patroni-0 patroni[1088]:     return bool(self._cluster_info_state_get('timeline'))
May 09 12:40:15 patroni-0 patroni[1088]:   File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 318, in _cluster_info_state_get
May 09 12:40:15 patroni-0 patroni[1088]:     raise PostgresConnectionException(self._cluster_info_state['error'])
May 09 12:40:15 patroni-0 patroni[1088]: patroni.exceptions.PostgresConnectionException: "'Too many retry attempts'"
May 09 12:40:15 patroni-0 systemd[1]: patroni.service: Main process exited, code=exited, status=1/FAILURE
May 09 12:40:15 patroni-0 systemd[1]: patroni.service: Failed with result 'exit-code'.
root@patroni-0:~# 
root@patroni-0:~# systemctl status postgresql@13-main ## Postgresql was started only seconds after patroni
● postgresql@13-main.service - PostgreSQL Cluster 13-main
   Loaded: loaded (/lib/systemd/system/postgresql@.service; indirect; vendor preset: enabled)
   Active: active (running) since Mon 2022-05-09 12:40:23 UTC; 32s ago
  Process: 1083 ExecStart=/usr/bin/pg_ctlcluster --skip-systemctl-redirect 13-main start (code=exited, status=0/SUCCESS)
 Main PID: 1567 (postgres)
    Tasks: 12 (limit: 4915)
   CGroup: /system.slice/system-postgresql.slice/postgresql@13-main.service
           ├─1567 /usr/lib/postgresql/13/bin/postgres -D /var/lib/postgresql/13/main -c config_file=/etc/postgresql/13/main/postgresql.conf
           ├─1750 postgres: test-kitchen-946f7c97: logger 
           ├─1790 postgres: test-kitchen-946f7c97: startup waiting for 000000020000000000000011
           ├─2189 postgres: test-kitchen-946f7c97: checkpointer 
           ├─2191 postgres: test-kitchen-946f7c97: background writer 
           ├─2230 postgres: test-kitchen-946f7c97: stats collector 
           ├─2251 postgres: test-kitchen-946f7c97: walreceiver 
           ├─2426 postgres: test-kitchen-946f7c97: datadog template_testing 127.0.0.1(46028) idle
           ├─2427 postgres: test-kitchen-946f7c97: datadog sf_statistics 127.0.0.1(46030) idle
           ├─2429 postgres: test-kitchen-946f7c97: datadog kitchen_global 127.0.0.1(46034) idle
           ├─2451 postgres: test-kitchen-946f7c97: datadog silverfin 127.0.0.1(46044) idle
           └─2452 postgres: test-kitchen-946f7c97: datadog kitchendb 127.0.0.1(46046) idle

May 09 12:39:57 patroni-0 systemd[1]: Starting PostgreSQL Cluster 13-main...
May 09 12:40:23 patroni-0 systemd[1]: Started PostgreSQL Cluster 13-main.
root@patroni-0:~# 
root@patroni-0:~# systemctl start patroni  ##start patroni manually 
root@patroni-0:~# 
root@patroni-0:~# patronictl list
+-----------+--------------------------------------------+---------+---------+----+-----------+
| Member    | Host                                       | Role    | State   | TL | Lag in MB |
+ Cluster: test-kitchen-946f7c97 (7095710181513311030) --+---------+---------+----+-----------+
| patroni-0 | patroni-0.c.test-kitchen-946f7c97.internal | Replica | running |  2 |         0 |
| patroni-1 | patroni-1.c.test-kitchen-946f7c97.internal | Replica | running |  2 |         0 |
| patroni-2 | patroni-2.c.test-kitchen-946f7c97.internal | Leader  | running |  2 |           |
+-----------+--------------------------------------------+---------+---------+----+-----------+
root@patroni-0:~# 
root@patroni-0:~# patronictl restart test-kitchen-946f7c97  ## use patronictl restart to force patroni action on the DB
+-----------+--------------------------------------------+---------+---------+----+-----------+
| Member    | Host                                       | Role    | State   | TL | Lag in MB |
+ Cluster: test-kitchen-946f7c97 (7095710181513311030) --+---------+---------+----+-----------+
| patroni-0 | patroni-0.c.test-kitchen-946f7c97.internal | Replica | running |  2 |         0 |
| patroni-1 | patroni-1.c.test-kitchen-946f7c97.internal | Replica | running |  2 |         0 |
| patroni-2 | patroni-2.c.test-kitchen-946f7c97.internal | Leader  | running |  2 |           |
+-----------+--------------------------------------------+---------+---------+----+-----------+
When should the restart take place (e.g. 2022-05-09T13:41)  [now]: 
Are you sure you want to restart members patroni-2, patroni-1, patroni-0? [y/N]: y
Restart if the PostgreSQL version is less than provided (e.g. 9.5.2)  []: 
Success: restart on member patroni-2
Success: restart on member patroni-1
Success: restart on member patroni-0
root@patroni-0:~# 
root@patroni-0:~# systemctl status postgresql@13-main ## Postgres failed from systemd perspective
● postgresql@13-main.service - PostgreSQL Cluster 13-main
   Loaded: loaded (/lib/systemd/system/postgresql@.service; indirect; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2022-05-09 12:41:42 UTC; 15s ago
  Process: 2815 ExecStop=/usr/bin/pg_ctlcluster --skip-systemctl-redirect -m fast 13-main stop (code=exited, status=2)
  Process: 1083 ExecStart=/usr/bin/pg_ctlcluster --skip-systemctl-redirect 13-main start (code=exited, status=0/SUCCESS)
 Main PID: 1567 (code=exited, status=0/SUCCESS)

May 09 12:39:57 patroni-0 systemd[1]: Starting PostgreSQL Cluster 13-main...
May 09 12:40:23 patroni-0 systemd[1]: Started PostgreSQL Cluster 13-main.
May 09 12:41:42 patroni-0 postgresql@13-main[2815]: Cluster is not running.
May 09 12:41:42 patroni-0 systemd[1]: postgresql@13-main.service: Control process exited, code=exited status=2
May 09 12:41:42 patroni-0 systemd[1]: postgresql@13-main.service: Failed with result 'exit-code'.
root@patroni-0:~# systemctl status patroni  ## Yet, postgres runs but owned by patroni
● patroni.service - Patroni service
   Loaded: loaded (/etc/systemd/system/patroni.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2022-05-09 12:41:18 UTC; 44s ago
     Docs: https://github.com/zalando/patroni
 Main PID: 2624 (patroni)
    Tasks: 16 (limit: 4915)
   CGroup: /system.slice/patroni.service
           ├─2624 /usr/bin/python3 /usr/local/bin/patroni /etc/patroni/config.yaml
           ├─2825 /usr/lib/postgresql/13/bin/postgres -D /var/lib/postgresql/13/main --config-file=/etc/postgresql/13/main/postgresql.conf --listen_addresses=0.0.0.0 --port=5432 --cluster_name=test-kitchen-946f7c97 --wal_level=replica --hot_stand
           ├─2831 postgres: test-kitchen-946f7c97: logger 
           ├─2832 postgres: test-kitchen-946f7c97: startup recovering 000000020000000000000012
           ├─2863 postgres: test-kitchen-946f7c97: checkpointer 
           ├─2864 postgres: test-kitchen-946f7c97: background writer 
           ├─2865 postgres: test-kitchen-946f7c97: stats collector 
           ├─2866 postgres: test-kitchen-946f7c97: walreceiver streaming 0/12003E98
           ├─2924 postgres: test-kitchen-946f7c97: postgres postgres 127.0.0.1(46274) idle
           ├─3023 postgres: test-kitchen-946f7c97: datadog template_testing 127.0.0.1(46294) idle
           ├─3044 postgres: test-kitchen-946f7c97: datadog sf_statistics 127.0.0.1(46296) idle
           └─3045 postgres: test-kitchen-946f7c97: datadog kitchen_global 127.0.0.1(46302) idle

May 09 12:41:44 patroni-0 patroni[2624]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
May 09 12:41:44 patroni-0 patroni[2624]:                                  Dload  Upload   Total   Spent    Left  Speed
May 09 12:41:44 patroni-0 patroni[2624]: [158B blob data]
May 09 12:41:51 patroni-0 patroni[2624]: ok2022-05-09 12:41:51,405 INFO: Lock owner: patroni-2; I am patroni-0
May 09 12:41:51 patroni-0 patroni[2624]: 2022-05-09 12:41:51,405 INFO: does not have lock
May 09 12:41:51 patroni-0 patroni[2624]: 2022-05-09 12:41:51,405 INFO: establishing a new patroni connection to the postgres cluster
May 09 12:41:51 patroni-0 patroni[2624]: 2022-05-09 12:41:51,428 INFO: no action.  i am a secondary and i am following a leader
May 09 12:42:01 patroni-0 patroni[2624]: 2022-05-09 12:42:01,405 INFO: Lock owner: patroni-2; I am patroni-0
May 09 12:42:01 patroni-0 patroni[2624]: 2022-05-09 12:42:01,405 INFO: does not have lock
May 09 12:42:01 patroni-0 patroni[2624]: 2022-05-09 12:42:01,411 INFO: no action.  i am a secondary and i am following a leader
root@patroni-0:~# 

```

**Comment by CyberDem0n** [comment]
> DB has to be started (obviously) before patroni itself

What made you think so? It is fully the responsibility of Patroni to start/stop Postgres!
Please keep in mind that Patroni doesn't know anything about systemd, it doesn't interact with units but starts/stops postgres on its own.

**Comment by msvorad** [comment]
That's the very first error message I pasted - I get `locahost:5432` rejecting connections; `patroni.exceptions.PostgresConnectionException: "'Too many retry attempts'"`. That's why I think postgresql has to be running when patroni is being started.
Also, if I modify patroni unit file (below) to start after postgresql, entire setup consistently works across many reboots. Without that dependency, patroni fails to start sometimes (error message above).
We wrapped patroni into systemd unit (so that it starts automatically after the reboot):
```
root@patroni-0:~# systemctl cat patroni.service 
# /etc/systemd/system/patroni.service
[Unit]
Description = Patroni service
Documentation = https://github.com/zalando/patroni
Wants = network-online.target
After = network-online.target
ConditionPathExists = /etc/patroni/config.yaml

[Service]
Type = simple
User = postgres
Group = postgres
EnvironmentFile = /etc/default/patroni
PermissionsStartOnly = true
RuntimeDirectoryMode = 2770
ExecReload = /bin/kill -HUP $MAINPID
ExecStart = /usr/local/bin/patroni /etc/patroni/config.yaml
KillMode = process
Restart = no

[Install]
WantedBy = multi-user.target
```

**Comment by CyberDem0n** [comment]
> I get locahost:5432 rejecting connections; 

Patroni is trying to connect to the Postgres because it thinks that it runs (according to the postmaster.pid). Probably something is wrong with the configuration.

> if I modify patroni unit file (below) to start after postgresql, entire setup consistently works across many reboots

Perfect. Now lets think about the following situation. Node was running as a leader before the crash/reboot. After that, the other node was promoted and the application started writing to it.
Next, you recover the crashed node, it automatically starts Postgres there, and someone by accident connects to it and starts executing transactions. This situation is called a split-brain.

Patroni prevents split-brain by starting Postgres as a replica. If you let systemd start Postgres without Patroni you get into a big trouble.
