### ISSUE TITLE
Failed to update cluster status in zookeeper

### ISSUE THREAD

**Issue by Faxter** [zalando/patroni#2295]
Hello,

running patroni with ZooKeeper I sometimes get an exception on updating cluster status into DCS (log 1).
It appears that the exception occurs more often if there is more load to the database system.
Generally the cluster is running fine and stable. But sometimes this exception seems to be occuring at an unfortunate timing within internal timeouts. In this case database connections appear to be dropped (log 2)
I couldn't find anything similar in the issue tracker, but any hints to existing topics would be appreciated.

What could be reasons for this exception? How can I troubleshoot what is happening?

## log 1
```
2022-05-10 15:01:36,605 ERROR: Failed to update /pg_cluster/postgres/status
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/patroni/dcs/zookeeper.py", line 328, in _set_or_create
self._client.set_async(key, value, version=index or -1).get(timeout=1)
File "/usr/local/lib/python3.6/site-packages/kazoo/handlers/utils.py", line 78, in get
raise self._timeout_factory()
kazoo.handlers.threading.KazooTimeoutError
```

## log 2
```
2022-05-10 15:13:31,611 INFO: no action. I am (zookeeper-node-1), the leader with the lock
2022-05-10 15:13:35,604 INFO: Lock owner: zookeeper-node-1; I am zookeeper-node-1
2022-05-10 15:13:36,605 ERROR: Failed to update /pg_cluster/postgres/status
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/patroni/dcs/zookeeper.py", line 328, in _set_or_create
self._client.set_async(key, value, version=index or -1).get(timeout=1)
File "/usr/local/lib/python3.6/site-packages/kazoo/handlers/utils.py", line 78, in get
raise self._timeout_factory()
kazoo.handlers.threading.KazooTimeoutError
2022-05-10 15:13:37,508 WARNING: Connection dropped: outstanding heartbeat ping not received
2022-05-10 15:13:37,508 WARNING: Transition to CONNECTING
2022-05-10 15:13:37,508 INFO: Zookeeper connection lost
2022-05-10 15:13:37,509 ERROR: touch_member
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/patroni/dcs/zookeeper.py", line 383, in touch_member
self._client.set_async(self.member_path, encoded_data).get(timeout=1)
File "/usr/local/lib/python3.6/site-packages/kazoo/handlers/utils.py", line 75, in get
raise self._exception
kazoo.exceptions.ConnectionLoss
2022-05-10 15:13:37,509 INFO: no action. I am (zookeeper-node-1), the leader with the lock
2022-05-10 15:13:37,634 INFO: Connecting to zookeeper-node-2(ip removed):2181, use_ssl: False
2022-05-10 15:13:37,637 INFO: Zookeeper connection established, state: CONNECTED
2022-05-10 15:13:37,927 INFO: no action. I am (zookeeper-node-1), the leader with the lock
```

# Configs
## zookeeper 3.6.1
```
tickTime=2000
initLimit=10
syncLimit=5
dataDir=/opt/zookeeper/data
clientPort=2181
server.1=zookeeper-node-1:2888:3888
server.2=zookeeper-node-2:2888:3888
server.3=zookeeper-node-3:2888:3888
autopurge.purgeInterval=24
4lw.commands.whitelist=conf, cons, ruok, stat
```
## patroni 2.1.3
```
scope: postgres
namespace: /pg_cluster/
name: zookeeper-node-1
 
restapi:
  listen: zookeeper-node-1:8008
  connect_address: zookeeper-node-1:8008
 
zookeeper:
  hosts:
    - zookeeper-node-1:2181
    - zookeeper-node-2:2181
    - zookeeper-node-3:2181
 
bootstrap:
  dcs:
    ttl: 12
    loop_wait: 4
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      parameters:
        max_connections: 600
        max_locks_per_transaction: 1024
        shared_buffers: 10GB
        work_mem: 1GB
        maintenance_work_mem: 1GB
 
  initdb:
    - encoding: UTF8
    - data-checksums
 
  pg_hba:
    - host replication all all md5
    - host all all all md5
 
postgresql:
  listen: zookeeper-node-1:5431
  connect_address: zookeeper-node-1:5431
  data_dir: /mnt/patroni/data
  bin_dir: /usr/pgsql-13/bin
  pgpass: /tmp/pgpass
  authentication:
    replication:
      username: replicator
      password: -
    superuser:
      username: postgres
      password: -
  callbacks:
    on_role_change: /opt/patroni/alert/email.sh
 
tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
```

**Comment by Faxter** [comment]
Hello,

thanks for your reply!

> Check zookeeper logs?
They do contain quite a lot of EndOfStreamExceptions. Does this mean that patroni keeps unexpectedly closing connections to zookeeper? I had thought this to be normal behaviour.
```
2022-05-11 10:39:11,175 [myid:1] - WARN  [NIOWorkerThread-3:NIOServerCnxn@364] - Unexpected exception
EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /<ip-of-zookeeper-node-1>:56162, session = 0x...
        at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
        at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
        at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
        at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```

> Also, you have to follow the rule `loop_wait + 2*retry_timeout <= ttl`.
I feel bad for not knowing that rule. Where does it come from? Did I miss a best practice doc?
My understanding of it is, that a lower TTL should achieve a faster leader election on network isolation of current master
It wouldn't explain the exceptions in question, right?

> Zookeeper nodes are probably slow.
Does this mean the tickTime of zookeeper nodes should be longer?
It seems to me the exception stems from the call to kazoo. That's why I am unsure where to start on this.

**Comment by CyberDem0n** [comment]
`update_status()` and `touch_member()` calls are executed with timeout=1s.
Since you get `KazooTimeoutError` exceptions in Patroni logs that means Zookeeper didn't answer after 1s, which is really weird.
The `Unexpected exception
EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address` is only a consequence of Patroni switching to another zookeeper node due to the experienced timeout.

> I feel bad for not knowing that rule. Where does it come from? Did I miss a best practice doc?

It is missing in the documentation. But it was mentioned many times in GH issues and different presentations and tutorials we did, including https://github.com/patroni-training/2019

> My understanding of it is, that a lower TTL should achieve a faster leader election on network isolation of current master

Yes and no. It only would work in the ideal world where the network is 100% reliable. In reality small glitches happen more often than one may think about. The 10s `retry_timeout` allows to "survive" the glitch up to 10s. The `loop_wait` set to a smaller values doesn't affect the speed of failover, it only generates CPU load :) Anyway, with your parameters `ttl` can't be smaller than 24. If you reduce it, the` retry_timeout` also must be reduced.

> Does this mean the tickTime of zookeeper nodes should be longer?

I don't think so. 

> It seems to me the exception stems from the call to kazoo. That's why I am unsure where to start on this.

Yes, a timeout exception is produced by kazoo, because zookeeper node didn't answer in 1s, which is a lot. You need to investigate what makes it slow.

**Comment by CyberDem0n** [comment]
>There appears to be an unresolved issue on the zookeeper Jira

I don't think that it is related. Patroni indeed closing the existing connection to zookeeper node once received a timeout exception after 1s. It results in exception in zookeeper logs.

> When patroni disconnects from zookeeper and then immediately successfully reconnects like this - will postgres drop connections to database clients?

No. It shouldn't. There is an important moment, it reconnects to a different zookeeper node.

**Comment by Faxter** [comment]
Thank you for your valuable insights!

I was able to compare two equally configured patroni clusters A & B where the machines in cluster B with zookeeper on them had a higher CPU base load (~2% vs ~15%). Cluster B produces way more of these exceptions (2 vs 197 in a timeframe of about 30 hours). However, cluster B also has to deal with way more database load.

At the moment, I do not have the resources to further investigate this - so I'll close the issue.
Should I come across anything new in the future, I'll come back here.
