### ISSUE TITLE
Role "replicator" is not automatically created when using a custom bootstrap mode

### ISSUE THREAD

**Issue by macrokernel** [zalando/patroni#2301]
**Describe the bug**
While initializing a cluster from a WAL-G S3 backup, the following error occurs after a successful bootstrap:
```
psycopg2.errors.UndefinedObject: role "replicator" does not exist
CONTEXT:  SQL statement "ALTER ROLE "replicator" WITH REPLICATION LOGIN PASSWORD 'password'"
PL/pgSQL function inline_code_block line 6 at SQL statement
```
Exactly the same Patroni config with the bootstrap **method** parameter commented out successfully initializes the cluster.

Not sure if this a bug or I am doing something wrong.

**To Reproduce**
Initialize a Patroni cluster with a custom bootstrap method. The testing was carried out with a brand new "empty" deployment of a Consul cluster as a DCS.
```yaml
bootstrap:
  method: walg
  walg:
    command: "wal-g backup-fetch /var/lib/postgresql/data LATEST"
    keep_existing_recovery_conf: false
    no_params: true
    recovery_conf:
      recovery_target_action: promote
      recovery_target_timeline: latest
      restore_command: "wal-g wal-fetch \"%f\" \"%p\" 2>&1 |logger -t WAL-G"
...
```

Adding a **bootstrap.users** section  with **replicator** user creation does not help:
```yaml
bootstrap:
  users:
    replication:
      username: replicator
      password: password
...
```

Adding the following elements to **bootstrap.initdb** did not help either:
```yaml
  initdb:
   - auth-host: md5
   - auth-local: trust
```

After adding the following config line the cluster initialized successfully:
```yaml
bootstrap:
  post_bootstrap: psql -c "CREATE ROLE replicator WITH REPLICATION LOGIN PASSWORD 'password';"
```
However when I ran the deployment again (after having removed all Consul and Patroni/Postgres data to make it a clean test), post bootstrap failed saying that the replicator role already exists. 

Does it look like the database WAL-G S3 backup was somehow missing the replicator role, which after being created with the custom **post_bootstrap** psql command was automatically appended to the S3 backup by the **archive_command**? To help answer this question I set **recovery_target_time** to a few hours ago and re-deployed (after the cleanup like before) - cluster post bootstrap failed again with the same role missing error.

For now I am going to use the following work-around:
```yaml
bootstrap:
  post_bootstrap: psql -c "DROP ROLE IF EXISTS replicator; CREATE ROLE replicator WITH REPLICATION LOGIN PASSWORD 'password';" 
```

**Expected behavior**
The expected behaviour would be a successful cluster startup without any additional manipulations.

**Environment**
- Patroni version: 2.1.3
- PostgreSQL version: 14.3 (Ubuntu 14.3-1.pgdg20.04+1)
- DCS (and its version): Consul v1.12.0 revision 09a8cdb4

**Patroni configuration file**
```yaml
name: pg1
scope: patroni-cluster

consul:
  host: "10.128.0.13:8500"
  register_service: true

restapi:
  listen: 0.0.0.0:8008
  connect_address: "10.128.0.13:8008"
  auth: 'username:password'

watchdog:
  mode: automatic
  device: /dev/watchdog

bootstrap:
  method: walg
  walg:
    command: "wal-g backup-fetch /var/lib/postgresql/data LATEST"
    keep_existing_recovery_conf: false
    no_params: true
    recovery_conf:
      recovery_target_action: promote
      recovery_target_time: "2022-05-17 10:00:00.000"
      restore_command: "wal-g wal-fetch \"%f\" \"%p\" 2>&1 |logger -t WAL-G"
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576 # 1 megabyte in bytes
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        archive_mode: 'on'
        archive_timeout: 1800s
        hot_standby: 'on'
        log_connections: 'on'
        log_directory: pg_log
        log_disconnections: 'on'
        log_duration: 'on'
        log_filename: postgresql-%a.log
        logging_collector: 'on'
        max_replication_slots: 10
        max_wal_senders: 10
        wal_compression: 'on'
        wal_keep_size: 128
        wal_level: hot_standby
        wal_log_hints: 'on'
        archive_command: "wal-g wal-push \"%p\" 2>&1 |logger -t WAL-G"
      recovery_conf:
        restore_command: "wal-g wal-fetch \"%f\" \"%p\" 2>&1 |logger -t WAL-G"
  initdb:
   - encoding: UTF8
   - data-checksums
  pg_hba:
    - local all all trust
    - host replication replicator 127.0.0.1/32 trust
    - host replication replicator 10.128.0.0/24 md5
    - host all all 0.0.0.0/0 md5
  users:
    replication:
      username: replicator
      password: password
    superuser:
      username: postgres
      password: password
postgresql:
  pgpass: /var/lib/postgresql/.pgpass
  listen: 0.0.0.0:5432
  connect_address: "10.128.0.13:5432"
  data_dir: /var/lib/postgresql/data
  pg_hba:
    - local all all trust
    - host replication replicator 127.0.0.1/32 trust
    - host replication replicator 10.128.0.0/24 md5
    - host all all 0.0.0.0/0 md5
  authentication:
    replication:
      username: replicator
      password: password
    superuser:
      username: postgres
      password: password
```

**patronictl show-config**
```shell
$ patronictl -c /var/lib/postgresql/patroni.yml show-config
Traceback (most recent call last):
  File "/usr/local/bin/patronictl", line 8, in <module>
    sys.exit(ctl())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/patroni/ctl.py", line 1266, in show_config
    click.echo(format_config_for_editing(cluster.config.data))
AttributeError: 'NoneType' object has no attribute 'data'
```

**Patroni log**
```
...
022-05-17 17:03:23,535 INFO: establishing a new patroni connection to the postgres cluster
2022-05-17 17:03:23,643 INFO: Register service patroni-cluster, params {'service_id': 'patroni-cluster/pg1', 'address': '10.128.0.13', 'port': 5432, 'check': {'http': 'http://10.128.0.13:8008/master', 'interval': '5s', 'DeregisterCriticalServiceAfter': '150.0s'}, 'tags': ['master'], 'enable_tag_override': True}
2022-05-17 17:03:24,131 INFO: running post_bootstrap
2022-05-17 17:03:24,195 ERROR: post_bootstrap
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/patroni/postgresql/bootstrap.py", line 335, in post_bootstrap
    self.create_or_update_role(replication['username'], replication.get('password'), ['REPLICATION'])
  File "/usr/local/lib/python3.8/dist-packages/patroni/postgresql/bootstrap.py", line 319, in create_or_update_role
    self._postgresql.query(sql)
  File "/usr/local/lib/python3.8/dist-packages/patroni/postgresql/__init__.py", line 287, in query
    return self.retry(self._query, sql, *args)
  File "/usr/local/lib/python3.8/dist-packages/patroni/utils.py", line 334, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/patroni/postgresql/__init__.py", line 278, in _query
    raise e
  File "/usr/local/lib/python3.8/dist-packages/patroni/postgresql/__init__.py", line 267, in _query
    cursor.execute(sql, params or None)
psycopg2.errors.UndefinedObject: role "replicator" does not exist
CONTEXT:  SQL statement "ALTER ROLE "replicator" WITH REPLICATION LOGIN PASSWORD 'password'"
PL/pgSQL function inline_code_block line 6 at SQL statement

2022-05-17 17:03:24,224 INFO: removing initialize key after failed attempt to bootstrap the cluster
2022-05-17 17:03:24,288 INFO: renaming data directory to /var/lib/postgresql/data_2022-05-17-17-03-24
...
```

** PostgreSQL log**
```
...
2022-05-17 17:03:23 UTC [1166]: [1-1] 6283d55b.48e 0 [unknown] [unknown] [unknown] 127.0.0.1 LOG:  connection received: host=127.0.0.1 port=47454
2022-05-17 17:03:23 UTC [1166]: [2-1] 6283d55b.48e 0 postgres postgres [unknown] 127.0.0.1 LOG:  connection authorized: user=postgres database=postgres application_name=Patroni
2022-05-17 17:03:23 UTC [1166]: [3-1] 6283d55b.48e 0 postgres postgres Patroni 127.0.0.1 LOG:  duration: 93.462 ms
2022-05-17 17:03:24 UTC [1166]: [4-1] 6283d55b.48e 0 postgres postgres Patroni 127.0.0.1 LOG:  duration: 0.065 ms
2022-05-17 17:03:24 UTC [1166]: [5-1] 6283d55b.48e 0 postgres postgres Patroni 127.0.0.1 LOG:  duration: 0.038 ms
2022-05-17 17:03:24 UTC [1166]: [6-1] 6283d55b.48e 0 postgres postgres Patroni 127.0.0.1 LOG:  duration: 0.014 ms
2022-05-17 17:03:24 UTC [1166]: [7-1] 6283d55b.48e 0 postgres postgres Patroni 127.0.0.1 LOG:  duration: 61.303 ms
2022-05-17 17:03:24 UTC [1166]: [8-1] 6283d55b.48e 0 postgres postgres Patroni 127.0.0.1 LOG:  duration: 0.044 ms
2022-05-17 17:03:24 UTC [1166]: [9-1] 6283d55b.48e 0 postgres postgres Patroni 127.0.0.1 LOG:  duration: 0.010 ms
2022-05-17 17:03:24 UTC [1166]: [10-1] 6283d55b.48e 0 postgres postgres Patroni 127.0.0.1 LOG:  duration: 0.008 ms
2022-05-17 17:03:24 UTC [1166]: [11-1] 6283d55b.48e 0 postgres postgres Patroni 127.0.0.1 LOG:  duration: 0.016 ms
2022-05-17 17:03:24 UTC [1166]: [12-1] 6283d55b.48e 0 postgres postgres Patroni 127.0.0.1 LOG:  duration: 0.013 ms
2022-05-17 17:03:24 UTC [1166]: [13-1] 6283d55b.48e 0 postgres postgres Patroni 127.0.0.1 LOG:  duration: 0.012 ms
2022-05-17 17:03:24 UTC [1166]: [14-1] 6283d55b.48e 0 postgres postgres Patroni 127.0.0.1 ERROR:  role "replicator" does not exist
2022-05-17 17:03:24 UTC [1166]: [15-1] 6283d55b.48e 0 postgres postgres Patroni 127.0.0.1 CONTEXT:  SQL statement "ALTER ROLE "replicator" WITH REPLICATION LOGIN PASSWORD 'password'"
	PL/pgSQL function inline_code_block line 6 at SQL statement
2022-05-17 17:03:24 UTC [1166]: [16-1] 6283d55b.48e 0 postgres postgres Patroni 127.0.0.1 LOG:  duration: 0.014 ms
2022-05-17 17:03:24 UTC [1166]: [17-1] 6283d55b.48e 0 postgres postgres Patroni 127.0.0.1 LOG:  duration: 0.008 ms
2022-05-17 17:03:24 UTC [1166]: [18-1] 6283d55b.48e 0 postgres postgres Patroni 127.0.0.1 LOG:  duration: 0.008 ms
2022-05-17 17:03:24 UTC [25]: [7-1] 6283d53d.19 0     LOG:  received immediate shutdown request
2022-05-17 17:03:24 UTC [25]: [8-1] 6283d53d.19 0     LOG:  database system is shut down
...
```

**Have you tried to use GitHub issue search?**
There are somewhat similar issues, but not very close:
https://github.com/zalando/patroni/issues/481
https://github.com/zalando/patroni/issues/1489

**Update**
Found another minor issue which might be related, as it only happens while initializing the cluster from a WAL-G S3 backup and is not happening with the default bootstrap method. 

The issue is that after a successful initialization with the above mentioned **post_bootstrap** work-around the lines in _pg_hba.conf_ are duplicated when **pg_hba** section is defined only under the **bootstrap** section and is _not_ defined under the **postgresql** section:
```shell
$ cat pg_hba.conf
# Do not edit this file manually!
# It will be overwritten by Patroni!
local all all trust
host replication replicator 127.0.0.1/32 trust
host replication replicator 10.128.0.0/24 md5
host all all 0.0.0.0/0 md5

local all all trust
host replication replicator 127.0.0.1/32 trust
host replication replicator 10.128.0.0/24 md5
host all all 0.0.0.0/0 md5
```

When the same **pg_hba** items are defined under both **bootstrap** and  **postgresql** sections (like in my Patroni configuration file listed above) or when no custom bootstrap method is used, the lines in _pg_hba.conf_ are not duplicated. The desired behaviour would be no duplication of pg_hba.conf entries.

I suspect that both issues might be caused by some anomalies in my WAL-G backup. It is a test database, and I have been experimenting a lot with Patroni configuration as I am new to Patroni and am still finding a working combination of Patroni configuration parameters.

**Comment by CyberDem0n** [comment]
The following code https://github.com/zalando/patroni/blob/96b75fa7cbf43f185642cf7d5e5b6b57ecf231bc/patroni/postgresql/bootstrap.py#L305-L314
will produce the:
```sql
DO $$
BEGIN
    SET local synchronous_commit = 'local';
    PERFORM * FROM pg_catalog.pg_authid WHERE rolname = 'replicator';
    IF FOUND THEN
        ALTER ROLE "replicator" WITH REPLICATION LOGIN PASSWORD 'password';
    ELSE
        CREATE ROLE "replicator" WITH REPLICATION LOGIN PASSWORD 'password';
    END IF;
END;$$
```

Since the `ALTER ROLE` is being executed that could only happen when the previous `PERFORM` found a row.
Either we are dealing with a schrodinger user, or there is data corruption in your backup.
I am inclined to think about the second option.

**Comment by macrokernel** [comment]
I manually started PostgreSQL after a failed post bootstrap, and ran `\du` - **replicator** was already existing:
```shell
$ psql -c "\du"
                                    List of roles
 Role name  |                         Attributes                         | Member of 
------------+------------------------------------------------------------+-----------
 postgres   | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 replicator | Replication                                                | {}

```

Then I ran `CREATE ROLE`:
```shell
$ psql -c "CREATE ROLE replicator WITH REPLICATION LOGIN PASSWORD 'password';"
CREATE ROLE
```

And `\du` again:
```
$ psql -c "\du"
                                    List of roles
 Role name  |                         Attributes                         | Member of 
------------+------------------------------------------------------------+-----------
 postgres   | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 replicator | Replication                                                | {}
 replicator | Replication                                                | {}

```

Got two **replicator** roles. Does it prove that the backup is corrupted? If it does not, then I shall remove all backups, create new test data, create a new backup and check that the issues are gone.

**Comment by macrokernel** [comment]
An update on the minor issue with _pg_hba.conf_ lines duplication (please see the update section in the end of the first post). The duplication does not happen when **pg_hba** section is only defined under **postgresql** regardless of the bootstrap method (default or custom).

Summing up

When **pg_hba** items are defined only under the **bootstrap** section and are not defined under the **postgresql** section and while using a custom bootstrap method, the lines in _pg_hba.conf_ are duplicated.

When **pg_hba** items are defined only under **postgresql** section, the lines in _pg_hba.conf_ are _not_ duplicated regardless of the bootstrap method.
 
When the same **pg_hba** items are defined under both **bootstrap** and **postgresql** sections, the lines in _pg_hba.conf_ are _not_ duplicated  regardless of the bootstrap method.

**Comment by CyberDem0n** [comment]
> Got two replicator roles. Does it prove that the backup is corrupted?

This clearly a data corruption. Where it originates from you have to figure out. Maybe the backup was created on the system with incompatible glibc: https://wiki.postgresql.org/wiki/Locale_data_changes

> An update on the minor issue with pg_hba.conf lines duplication 

Comment in the [sample manifest](https://github.com/zalando/patroni/blob/master/postgres0.yml#L80) and the [documentation](https://patroni.readthedocs.io/en/latest/SETTINGS.html#bootstrap-configuration) tell that lines will be added (appended) to the _existing_ pg_hba.conf. This is the behavior of `bootstrap.pg_hba`.

In case if `postgresql.pg_hba` is defined, the whole pg_hba.conf is overwritten with the new content.

**Comment by macrokernel** [comment]
I confirm, the issue was definitely caused by data corruption. I rebuilt everything including the test backup data, and the new cluster initialized successfully.

Thanks a lot for your help Alexander, sorry for taking your time.
