### ISSUE TITLE
pg_rewind and check_leader_is_not_in_recovery

### ISSUE THREAD

**Issue by glushakov** [zalando/patroni#2310]
Hi

Since version 2.1.3 I encountered an error:

2022-05-19 17:49:04,484 ERROR: Exception when working with leader
Traceback (most recent call last):
  File "/var/lib/pgsql/patroni_venv/lib64/python3.6/site-packages/patroni/postgresql/rewind.py", line 60, in check_leader_is_not_in_recovery
    with get_connection_cursor(connect_timeout=3, options='-c statement_timeout=2000', **conn_kwargs) as cur:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/var/lib/pgsql/patroni_venv/lib64/python3.6/site-packages/patroni/postgresql/connection.py", line 44, in get_connection_cursor
    conn = psycopg.connect(**kwargs)
  File "/var/lib/pgsql/patroni_venv/lib64/python3.6/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL: no pg_hba.conf entry for host "10.242.226.19", user "replicator", database "postgres", SSL on
FATAL: no pg_hba.conf entry for host "10.242.226.19", user "replicator", database "postgres", SSL off

Its look like patroni checks the possibility (?) of using pg_rewind.

I have 2 users for patroni: replicator (for replication) and postgres (for pg_rewind)
Checking was not with the specified pg_rewind user (POSTGRES), but through the REPLICATOR user, which does not have the necessary permissions.

For pg_rewind I have a separate user and all replication is configured through the replication user, with REPLICATION privilege only:
...
host replication replicator 0.0.0.0/0 scram-sha-256

This behavior changes since 2.1.3?

**Comment by glushakov** [comment]
Thanks. I got it
I just wanted to make sure I didn't break it ))
