### ISSUE TITLE
patroni restart failed

### ISSUE THREAD

**Issue by hunterhuang8810** [zalando/patroni#2352]
Hi Expert,

I encounted below issue when I restart patroni,

[postgres@10-235-128-76.rds-fatpod-rds.it01 ~]$ patronictl list
+ Cluster: hunter-dd (7114114433461432716) ---+---------+----+-----------+-----------------+
| Member       | Host                | Role   | State   | TL | Lag in MB | Pending restart |
+--------------+---------------------+--------+---------+----+-----------+-----------------+
| hunter-dd-i0 | 10.235.128.76:54322 | Leader | running |  1 |           | *               |
+--------------+---------------------+--------+---------+----+-----------+-----------------+
[postgres@10-235-128-76.rds-fatpod-rds.it01 ~]$ patronictl restart hunter-dd --force
+ Cluster: hunter-dd (7114114433461432716) ---+---------+----+-----------+-----------------+
| Member       | Host                | Role   | State   | TL | Lag in MB | Pending restart |
+--------------+---------------------+--------+---------+----+-----------+-----------------+
| hunter-dd-i0 | 10.235.128.76:54322 | Leader | running |  1 |           | *               |
+--------------+---------------------+--------+---------+----+-----------+-----------------+
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/patronictl", line 8, in <module>
    sys.exit(ctl())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/patroni/ctl.py", line 584, in restart
    r = request_patroni(member, 'post', 'restart', content)
  File "/usr/local/lib/python3.6/site-packages/patroni/ctl.py", line 169, in request_patroni
    return request_executor(member, method, endpoint, data)
  File "/usr/local/lib/python3.6/site-packages/patroni/request.py", line 53, in __call__
    return self.request(method, url, data, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/patroni/request.py", line 46, in request
    return self._pool.request(method.upper(), url, body=body, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

and patroni log like below:
2022-06-28 10:39:17,920 INFO: Lock owner: hunter-dd-i0; I am hunter-dd-i0
2022-06-28 10:39:17,924 INFO: no action.  i am the leader with the lock
2022-06-28 10:39:22,920 INFO: Lock owner: hunter-dd-i0; I am hunter-dd-i0
2022-06-28 10:39:22,924 INFO: no action.  i am the leader with the lock
2022-06-28 10:39:27,920 INFO: Lock owner: hunter-dd-i0; I am hunter-dd-i0
2022-06-28 10:39:27,923 INFO: updated leader lock during restart
2022-06-28 10:39:32,920 INFO: Lock owner: hunter-dd-i0; I am hunter-dd-i0
2022-06-28 10:39:32,923 INFO: updated leader lock during restart
2022-06-28 10:39:37,920 INFO: Lock owner: hunter-dd-i0; I am hunter-dd-i0
2022-06-28 10:39:37,923 INFO: updated leader lock during restart
2022-06-28 10:39:42,920 INFO: Lock owner: hunter-dd-i0; I am hunter-dd-i0
2022-06-28 10:39:42,923 INFO: updated leader lock during restart
2022-06-28 10:39:47,920 INFO: Lock owner: hunter-dd-i0; I am hunter-dd-i0
2022-06-28 10:39:47,923 INFO: updated leader lock during restart
2022-06-28 10:39:52,920 INFO: Lock owner: hunter-dd-i0; I am hunter-dd-i0
2022-06-28 10:39:52,923 INFO: updated leader lock during restart
2022-06-28 10:39:57,920 INFO: Lock owner: hunter-dd-i0; I am hunter-dd-i0
2022-06-28 10:39:57,923 INFO: updated leader lock during restart

could you please help to check?

**Comment by CyberDem0n** [comment]
> could you please help to check?

We could not. It is your setup and your responsibility.
For example, the issue template explicitly asking to check postgres logs, but you ignored it.
