### ISSUE TITLE
Database went into crash loop

### ISSUE THREAD

**Issue by saurabh-gojek** [zalando/patroni#2354]
The patroni logs shows the following error
```
return self._connection.get()
  File "/opt/patroni/venv/lib/python3.8/site-packages/patroni/postgresql/connection.py", line 23, in get
    self._connection = psycopg2.connect(**self._conn_kwargs)
  File "/opt/patroni/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/patroni/venv/lib/python3.8/site-packages/patroni/api.py", line 442, in get_postgresql_status
    row = self.query(stmt.format(self.server.patroni.postgresql.wal_name,
  File "/opt/patroni/venv/lib/python3.8/site-packages/patroni/api.py", line 416, in query
    return self.server.query(sql, *params)
  File "/opt/patroni/venv/lib/python3.8/site-packages/patroni/api.py", line 504, in query
    raise PostgresConnectionException('connection problems')
patroni.exceptions.PostgresConnectionException: 'connection problems'
2022-07-07 11:55:05,146 ERROR: get_postgresql_status
Traceback (most recent call last):
  File "/opt/patroni/venv/lib/python3.8/site-packages/patroni/api.py", line 498, in query
    with self.patroni.postgresql.connection().cursor() as cursor:
  File "/opt/patroni/venv/lib/python3.8/site-packages/patroni/postgresql/__init__.py", line 227, in connection
```

**Expected behavior**
We are trying to setup pglogical from our current 9.5 postgres master to 12 postgres master. This log belong to 12 postgres master

**Environment**
- 1.6.4 - Patroni
- 12.6 - Postgres
- DCS : Consul 

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    datestyle: ISO, MDY
    default_text_search_config: pg_catalog.english
    dynamic_shared_memory_type: posix
    log_checkpoints: 'on'
    log_connections: 'on'
    log_disconnections: 'on'
    log_line_prefix: '%t [%p]:              [%l-1] user=%udb=%dapp=%aclient=%h '
    log_lock_waits: 'on'
    log_min_duration_statement: '500'
    log_temp_files: '0'
    log_timezone: Asia/Jakarta
    max_connections: '1000'
    max_wal_senders: '8'
    synchronous_commit: 'on'
    synchronous_standby_names: '*'
    timezone: Asia/Jakarta
    track_counts: 'on'
    wal_keep_segments: '1000'
    wal_level: logical
  use_pg_rewind: true
retry_timeout: 10
synchronous_mode: true
synchronous_mode_strict: false
ttl: 30

```

**Have you checked Patroni logs?**
Pasted at the top of the issue

**Comment by CyberDem0n** [comment]
> 1.6.4 - Patroni

Upgrade ASAP to the latest version.

> psql: error: FATAL: the database system is starting up

Well, for some reason Postgres is in starting state. It is your system, you are the DBA, and hence it is your task to figure out what prevents Postgres from starting.

**Comment by pulkitent** [comment]
@CyberDem0n, correct it is our job to figure out but we are not professional DBAs we are just newbies to this Patroni/Postgres world.

So if you can share some steps (or any doc) that we can follow to debug this more effectively that will be very helpful :)

**Comment by NikolayS** [comment]
@pulkitent upgrade

**Comment by pulkitent** [comment]
@CyberDem0n, don't mind but just small feedback for you :)

Be humble & little bit more inclusive

You are actually representing the culture at Zalando. There are so many posts regarding the culture at Zalando on Blind :)
