### ISSUE TITLE
Abnormally and possibly corrupted shared memory during initializing of PostgreSQL replica on pg_basebackup 

### ISSUE THREAD

**Issue by ahmetmelihbasbug** [zalando/patroni#2374]
Describe the bug

During to initialize Patroni replica server, we got error on pg_basebackup and recovery stop in the beggining or in the middle of process.

We have leader and replica server on out patroni cluster. we had to remove replica server however we can not add again.

```
Aug 2 22:08:59 replicaerver patroni[40025]: WARNING: terminating connection because of crash of another server process
Aug 2 22:08:59 replicaerver patroni[40025]: DETAIL: The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
Aug 2 22:08:59 replicaerver patroni[40025]: HINT: In a moment you should be able to reconnect to the database and repeat your command.
Aug 2 22:08:59 replicaerver patroni[40025]: pg_basebackup: error: could not read COPY data: server closed the connection unexpectedly
Aug 2 22:08:59 replicaerver patroni[40025]: #011This probably means the server terminated abnormally
Aug 2 22:08:59 replicaerver patroni[40025]: #011before or while processing the request.
Aug 2 22:08:59 replicaerver patroni[40025]: pg_basebackup: removing data directory "/postgres/data/patroni"
Aug 2 22:08:59 replicaerver patroni[40025]: pg_basebackup: removing contents of WAL directory "/postgres/pg_wal"
Aug 2 22:08:59 replicaerver patroni[40025]: pg_basebackup: changes to tablespace directories will not be undone
Aug 2 22:09:04 replicaerver patroni[40025]: pg_basebackup: error: could not connect to server: Connection refused
Aug 2 22:09:04 replicaerver patroni[40025]: #011Is the server running on host "master_server_ip" and accepting
Aug 2 22:09:04 replicaerver patroni[40025]: #011TCP/IP connections on port 5432?
```

Environment

Patroni: 2.1.1
PostgreSQL: 13.4
We use etcd version 3
Db Size: 5.5 TB
Cluster is on two physical Server which has Ubuntu 20.04 
Ram 1 TB and we open huge_pages, set shared_buffers as 216 GB on patroni setting.

Another possibility solution? Can we solve initializing problem of secondary with rysnc command?

**Comment by CyberDem0n** [comment]
Have you seen the issue template?
It is _explicitly_ asking you to check Patroni **and Postgres logs**!

**Comment by ceremonytarkan** [comment]
`2022-08-03 13:02:18 ERROR: Failed to drop replication slot 'pg_basebackup_13950'
2022-08-03 13:02:25 ERROR:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/dcs/etcd.py", line 564, in wrapper
    retval = func(self, *args, **kwargs) is not None
  File "/usr/lib/python3/dist-packages/patroni/dcs/etcd.py", line 657, in touch_member
    return self._client.set(self.member_path, data, None if permanent else self._ttl)
  File "/usr/lib/python3/dist-packages/etcd/client.py", line 660, in set
    return self.write(key, value, ttl=ttl)
  File "/usr/lib/python3/dist-packages/etcd/client.py", line 461, in write
    response = self.api_execute(path, method, params=params)
  File "/usr/lib/python3/dist-packages/patroni/dcs/etcd.py", line 257, in api_execute
    return self._handle_server_response(response)
  File "/usr/lib/python3/dist-packages/etcd/client.py", line 928, in _handle_server_response
    etcd.EtcdError.handle(r)
  File "/usr/lib/python3/dist-packages/etcd/__init__.py", line 304, in handle
    raise exc(msg, payload)
patroni.dcs.etcd.EtcdRaftInternal: Raft Internal Error : etcdserver: request timed out
2022-08-03 13:02:25 INFO: no action. I am (postgresql6) the leader with the lock
2022-08-03 13:02:44 INFO: Lock owner: postgresql6; I am postgresql6
2022-08-03 13:02:46 ERROR: Failed to drop replication slot 'pg_basebackup_13950'
2022-08-03 13:02:46 INFO: no action. I am (postgresql6) the leader with the lock
2022-08-03 13:03:14 INFO: Lock owner: postgresql6; I am postgresql6
2022-08-03 13:03:17 ERROR: Failed to drop replication slot 'pg_basebackup_13950'
2022-08-03 13:03:17 INFO: no action. I am (postgresql6) the leader with the lock
2022-08-03 13:03:44 INFO: Lock owner: postgresql6; I am postgresql6
`

**Comment by ahmetmelihbasbug** [comment]
@CyberDem0n 
According to that patroni.log on primary, we set ttl=180, loop_wait=10, retry_timeout=40.
according to `loop_wait + 2*retry_timeot <= ttl`

our 3 etcd servers installed on 2 of physical server which include patroni-postgresql servers and one VM server

**Comment by CyberDem0n** [comment]
@ahmetmelihbasbug, @ceremonytarkan  my point about the issue template which you ignored remains.
