### ISSUE TITLE
SSL error in requests to Patroni api

### ISSUE THREAD

**Issue by drundusvit** [zalando/patroni#2399]
**Describe the bug**
In an attempt to perform a switchover I get this error:
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='patronitest2.smartly.io', port=8008): Max retries exceeded with url: /switchover (Caused by SSLError(SSLError("read error: Error([('SSL routines', '', 'unexpected eof while reading')])")))

**To Reproduce**

**Expected behavior**
A switchover performed

**Environment**
- OS: Ubuntu 22.04.1 LTS
- Patroni version: 2.1.4
- PostgreSQL version: 12
- DCS (and its version): etcd3-0.4.5

**Patroni configuration file**
```
scope: patronitest
namespace: /service/
name: patronitest3

restapi:
  connect_address: patronitest3:8008
  listen: 0.0.0.0:8008
  certfile: /etc/ssl/certs/patronitest3.cert.pem
  keyfile: /etc/ssl/private/patronitest3.key.pem
  cafile: /etc/ssl/certs/company-ca-chain.cert.pem

etcd3:
  hosts: 10.4.96.1:2379, 10.4.96.2:2379, 10.4.96.3:2379

  protocol: http

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    synchronous_mode_strict: false
    check_timeline: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 5000
        max_locks_per_transaction: 64
        max_worker_processes: 8
        max_prepared_transactions: 0
        wal_level: replica
        wal_log_hints: on
        track_commit_timestamp: off
        max_wal_senders: 10
        max_replication_slots: 0
        wal_keep_segments: 0
  initdb:
    - encoding: UTF8
    - data-checksums
  users:
    patroni_superuser:
      password: pass1
    patroni_replication:
      password: pass2
      options:
        - replication

postgresql:
  use_unix_socket: true
  listen: 0.0.0.0:5432
  connect_address: ip2:5432
  data_dir: /data/postgresql/12/main
  bin_dir: /usr/lib/postgresql/12/bin
  pgpass: /var/lib/postgresql/.pgpass
  authentication:
    superuser:
      username: patroni_superuser
      password: pass1
    replication:
      username: patroni_replication
      password: pass2
  create_replica_methods:
    - basebackup
  custom_conf: /etc/postgresql/12/main/postgresql.conf
  pg_hba:
    - local   all             postgres                                peer
    - local   all             patroni_superuser                      ident map=patroni_superuser
    - 
  pg_ident:
    - patroni_superuser postgres patroni_superuser
  pg_ctl_timeout: 60
  pg_rewind:
    username: patroni_superuser
    password: pass1
  remove_data_directory_on_rewind_failure: false
  remove_data_directory_on_diverged_timelines: false

watchdog:
  mode: automatic
  device: /dev/watchdog
  safety_margin: 5
```

**patronictl show-config**
```
check_timeline: false
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    max_connections: 5000
    max_locks_per_transaction: 64
    max_prepared_transactions: 0
    max_replication_slots: 0
    max_wal_senders: 10
    max_worker_processes: 8
    track_commit_timestamp: false
    wal_keep_segments: 0
    wal_level: replica
    wal_log_hints: true
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: false
synchronous_mode_strict: false
ttl: 30
```
**Additional context**
```
patronictl -c /etc/patroni/ switchover
Master [patronitest2]: 
Candidate ['patronitest3'] []: 
When should the switchover take place (e.g. 2022-08-25T10:19 )  [now]: 
Current cluster topology
+-------------------------+---------------+---------+---------+----+-----------+
| Member                  | Host          | Role    | State   | TL | Lag in MB |
+ Cluster: patronitest (7129452086696751296) -------+---------+----+-----------+
| patronitest2 | ip1 | Leader  | running |  3 |           |
| patronitest3| ip2 | Replica | running |  3 |         0 |
+-------------------------+---------------+---------+---------+----+-----------+
Are you sure you want to switchover cluster patronitest, demoting current master patronitest2? [y/N]: y
2022-08-25 09:19:50,725 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("read error: Error([('SSL routines', '', 'unexpected eof while reading')])"))': /switchover
2022-08-25 09:19:50,748 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("read error: Error([('SSL routines', '', 'unexpected eof while reading')])"))': /switchover
2022-08-25 09:19:50,769 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("read error: Error([('SSL routines', '', 'unexpected eof while reading')])"))': /switchover
2022-08-25 09:19:50,793 - ERROR - None
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/contrib/pyopenssl.py", line 319, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1800, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1632, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 57, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', '', 'unexpected eof while reading')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 443, in _error_catcher
    yield
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 566, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 532, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/usr/lib/python3.10/http/client.py", line 478, in read
    s = self.fp.read()
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/contrib/pyopenssl.py", line 338, in recv_into
    raise ssl.SSLError("read error: %r" % e)
ssl.SSLError: ("read error: Error([('SSL routines', '', 'unexpected eof while reading')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 723, in urlopen
    response = self.ResponseCls.from_httplib(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 652, in from_httplib
    resp = ResponseCls(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 265, in __init__
    self._body = self.read(decode_content=decode_content)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 565, in read
    with self._error_catcher():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 454, in _error_catcher
    raise SSLError(e)
urllib3.exceptions.SSLError: ("read error: Error([('SSL routines', '', 'unexpected eof while reading')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/patroni/ctl.py", line 719, in _do_failover_or_switchover
    r = request_patroni(member, 'post', action, failover_value)
  File "/usr/local/lib/python3.10/dist-packages/patroni/ctl.py", line 171, in request_patroni
    return request_executor(member, method, endpoint, data)
  File "/usr/local/lib/python3.10/dist-packages/patroni/request.py", line 56, in __call__
    return self.request(method, url, data, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/patroni/request.py", line 49, in request
    return self._pool.request(method.upper(), url, body=body, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='patronitest2', port=8008): Max retries exceeded with url: /switchover (Caused by SSLError(SSLError("read error: Error([('SSL routines', '', 'unexpected eof while reading')])")))
2022-08-25 09:19:50,794 - WARNING - Failing over to DCS
2022-08-25 09:19:50.79457 Could not switchover using Patroni api, falling back to DCS
```

**Comment by drundusvit** [comment]
It might have something to do with [openssl](https://github.com/openssl/openssl/issues/18866)

**Comment by CyberDem0n** [comment]
This is not Patroni problem per se. We just rely on available SSL implementation.

**Comment by drundusvit** [comment]
Updating urllib3 from 1.26.11 to 1.26.12 didn't help

**Comment by CyberDem0n** [comment]
> Updating urllib3 from 1.26.11 to 1.26.12 didn't help

so does urllib3

**Comment by reddare** [comment]
The unexpected EOF failure was introduced in OpenSSL 3.0 to prevent truncation attack
https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_options.html#SSL_OP_IGNORE_UNEXPECTED_EOF

OpenSSL 3.0 installed by default in Ubuntu 22.04. Therefore, now Patroni and Ubuntu 22.04 are incompatible.

It seems that this is still a Patroni problem: to ensure correct operation for the OpenSSL 3.0 according to the new requirements?

**Comment by matikkane** [comment]
https://github.com/zalando/patroni/issues/2424
