### ISSUE TITLE
Patroni fails after pgbackrest pitr

### ISSUE THREAD

**Issue by Sagri93** [zalando/patroni#2416]
**The Issue**

I have a patroni cluster, and after I try to do a pitr using pgbackrest, the recovery finishes and the patroni service fails.
I am sure I'm missing something, but I can't figure out what. For the command I'm using a bootstrap script where I add the time chosen for the pitr

**The logs**
````
Σεπ 19 13:28:45 ip-10-0-4-100.eu-west-1.compute.internal systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL.
Σεπ 19 13:28:45 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]: 2022-09-19 13:28:45,642 INFO: Selected new etcd server http://10.0.17.12:2379
Σεπ 19 13:28:45 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]: 2022-09-19 13:28:45,649 INFO: No PostgreSQL configuration items changed, nothing to reload.
Σεπ 19 13:28:45 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]: 2022-09-19 13:28:45,660 INFO: Lock owner: None; I am postgresqlpromoapp01
Σεπ 19 13:28:45 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]: 2022-09-19 13:28:45,668 INFO: trying to bootstrap a new cluster
Σεπ 19 13:28:45 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]: 2022-09-19 13:28:45,668 INFO: Running custom bootstrap script: /var/lib/pgsql/custom_bootstrap.sh
Σεπ 19 13:28:45 ip-10-0-4-100.eu-west-1.compute.internal patroni[21767]: 2022-09-19 13:28:45.678 P00   INFO: restore command begin 2.40: --delta --exec-id=21767-1f6e188f --log-level-console=info --log-level-file=detail --pg1-path=/u01/data/patroni --repo1-host=10.0.17.12 --repo1-host-user=postgres --stanza=production-lspromo-ha-cluster --target="2022-09-19 12:26:38.84566+00" --target-action=promote --type=time
Σεπ 19 13:28:45 ip-10-0-4-100.eu-west-1.compute.internal patroni[21767]: WARN: --delta or --force specified but unable to find 'PG_VERSION' or 'backup.manifest' in '/u01/data/patroni' to confirm that this is a valid $PGDATA directory.  --delta and --force have been disabled and if any files exist in the destination directories the restore will be aborted.
Σεπ 19 13:28:46 ip-10-0-4-100.eu-west-1.compute.internal patroni[21767]: 2022-09-19 13:28:46.303 P00   INFO: repo1: restore backup set 20220919-092248F_20220919-122143I, recovery will start at 2022-09-19 12:21:43
Σεπ 19 13:28:55 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]: 2022-09-19 13:28:55,657 INFO: Lock owner: None; I am postgresqlpromoapp01
Σεπ 19 13:28:55 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]: 2022-09-19 13:28:55,658 INFO: not healthy enough for leader race
Σεπ 19 13:28:55 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]: 2022-09-19 13:28:55,663 INFO: bootstrap in progress
Σεπ 19 13:29:05 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]: 2022-09-19 13:29:05,656 INFO: Lock owner: None; I am postgresqlpromoapp01
Σεπ 19 13:29:05 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]: 2022-09-19 13:29:05,656 INFO: not healthy enough for leader race
Σεπ 19 13:29:05 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]: 2022-09-19 13:29:05,665 INFO: bootstrap in progress
Σεπ 19 13:33:51 ip-10-0-4-100.eu-west-1.compute.internal patroni[21767]: 2022-09-19 13:33:51.273 P00   INFO: write updated /u01/data/patroni/postgresql.auto.conf
Σεπ 19 13:33:51 ip-10-0-4-100.eu-west-1.compute.internal patroni[21767]: 2022-09-19 13:33:51.283 P00   INFO: restore global/pg_control (performed last to ensure aborted restores cannot be started)
Σεπ 19 13:33:51 ip-10-0-4-100.eu-west-1.compute.internal patroni[21767]: 2022-09-19 13:33:51.286 P00   INFO: restore size = 23.7GB, file total = 3054
Σεπ 19 13:33:51 ip-10-0-4-100.eu-west-1.compute.internal patroni[21767]: 2022-09-19 13:33:51.286 P00   INFO: restore command end: completed successfully (305609ms)
Σεπ 19 13:33:51 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]: 2022-09-19 13:33:51,584 INFO: postmaster pid=21789
Σεπ 19 13:33:51 ip-10-0-4-100.eu-west-1.compute.internal patroni[21789]: 2022-09-19 13:33:51.622 UTC [21789] LOG:  redirecting log output to logging collector process
Σεπ 19 13:33:51 ip-10-0-4-100.eu-west-1.compute.internal patroni[21789]: 2022-09-19 13:33:51.622 UTC [21789] HINT:  Future log output will appear in directory "log".
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]: 2022-09-19 13:33:54,668 INFO: removing initialize key after failed attempt to bootstrap the cluster
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]: 2022-09-19 13:33:54,673 INFO: renaming data directory to /u01/data/patroni_2022-09-19-13-33-54
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]: Traceback (most recent call last):
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]:   File "/var/lib/pgsql/patroni/env/bin/patroni", line 8, in <module>
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]:     sys.exit(main())
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]:   File "/var/lib/pgsql/patroni/env/lib64/python3.6/site-packages/patroni/__main__.py", line 143, in main
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]:     return patroni_main()
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]:   File "/var/lib/pgsql/patroni/env/lib64/python3.6/site-packages/patroni/__main__.py", line 135, in patroni_main
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]:     abstract_main(Patroni, schema)
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]:   File "/var/lib/pgsql/patroni/env/lib64/python3.6/site-packages/patroni/daemon.py", line 100, in abstract_main
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]:     controller.run()
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]:   File "/var/lib/pgsql/patroni/env/lib64/python3.6/site-packages/patroni/__main__.py", line 105, in run
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]:     super(Patroni, self).run()
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]:   File "/var/lib/pgsql/patroni/env/lib64/python3.6/site-packages/patroni/daemon.py", line 59, in run
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]:     self._run_cycle()
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]:   File "/var/lib/pgsql/patroni/env/lib64/python3.6/site-packages/patroni/__main__.py", line 108, in _run_cycle
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]:     logger.info(self.ha.run_cycle())
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]:   File "/var/lib/pgsql/patroni/env/lib64/python3.6/site-packages/patroni/ha.py", line 1514, in run_cycle
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]:     info = self._run_cycle()
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]:   File "/var/lib/pgsql/patroni/env/lib64/python3.6/site-packages/patroni/ha.py", line 1388, in _run_cycle
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]:     return self.post_bootstrap()
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]:   File "/var/lib/pgsql/patroni/env/lib64/python3.6/site-packages/patroni/ha.py", line 1280, in post_bootstrap
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]:     self.cancel_initialization()
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]:   File "/var/lib/pgsql/patroni/env/lib64/python3.6/site-packages/patroni/ha.py", line 1273, in cancel_initialization
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]:     raise PatroniFatalException('Failed to bootstrap cluster')
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal patroni[21757]: patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal systemd[1]: patroni.service: Main process exited, code=exited, status=1/FAILURE
Σεπ 19 13:33:54 ip-10-0-4-100.eu-west-1.compute.internal systemd[1]: patroni.service: Failed with result 'exit-code'.

````

**Patroni configuration file**
```
scope: production-lspromo-ha-cluster
name: postgresqlpromoapp01

restapi:
    listen: 10.0.4.100:8008
    connect_address: 10.0.4.100:8008

etcd:
        hosts: '10.0.7.242:2379,10.0.4.100:2379,10.0.17.12:2379'

bootstrap:
    method: pgbackrest
    pgbackrest:
        command: /var/lib/pgsql/custom_bootstrap.sh
        keep_existing_recovery_conf: False
        no_params: False
        recovery_conf:
            recovery_target: immediate
            recovery_target_action: pause
            restore_command: pgbackrest --stanza=production-lspromo-ha-cluster archive-get %f %p
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true
            use_slots: true
            parameters:
                hot_standby: 'on'
                wal_keep_segments: 20
                max_wal_senders: 2
                max_replication_slots: 2
                max_connections : 200
                shared_buffers : 512MB
                effective_cache_size : 1536MB
                maintenance_work_mem : 128MB
                checkpoint_completion_target : 0.9
                wal_buffers : 16MB
                default_statistics_target : 100
                random_page_cost : 1.1
                effective_io_concurrency : 200
                work_mem : 2621kB
                min_wal_size : 1GB
                max_wal_size : 4GB
                max_worker_processes : 2
                max_parallel_workers_per_gather : 1
                max_parallel_workers : 2
                max_parallel_maintenance_workers : 1

                #    initdb:
                #    - encoding: UTF8
                #    - data-checksums

    pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 10.0.4.100/32 md5
    - host replication replicator 10.0.7.242/32 md5
    - host replication replicator 10.0.17.12/32 md5
    - host all all 0.0.0.0/0 md5
    - host postgres postgres 10.0.17.12/32 trust

    users:
       dba:
          password: werfds#22!XP
          options:
           - createrole
           - createdb
       replicator:
           password: fdsrew21#!XP
           options:
            - replication

postgresql:
    listen: "*:5432"
    connect_address: 10.0.4.100:5432
    data_dir: /u01/data/patroni
    bin_dir: /usr/pgsql-14/bin
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: ****
        superuser:
            username: postgres
            password: *****
    parameters:
        hba_file: /var/lib/pgsql/pg_hba.conf
        unix_socket_directories: '.'
        archive_mode: "on"
        archive_command: 'pgbackrest --stanza=production-lspromo-ha-cluster archive-push %p'
        archive_timeout: 60
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

```
**custom_bootstrap.sh**
```
#!/bin/sh

pgbackrest --stanza=production-lspromo-ha-cluster  --log-level-console=info --delta --type=time "--target=2022-09-19 12:26:38.84566+00" --target-action=promote restore
```
**Postgres logs**
````
2022-09-19 13:33:51.622 UTC [21789] LOG:  starting PostgreSQL 14.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-10), 64-bit
2022-09-19 13:33:51.622 UTC [21789] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-09-19 13:33:51.622 UTC [21789] LOG:  listening on IPv6 address "::", port 5432
2022-09-19 13:33:51.629 UTC [21789] LOG:  listening on Unix socket "./.s.PGSQL.5432"
2022-09-19 13:33:51.640 UTC [21792] LOG:  database system was interrupted; last known up at 2022-09-19 12:21:46 UTC
2022-09-19 13:33:52.030 UTC [21792] LOG:  restored log file "0000001D.history" from archive
2022-09-19 13:33:52.397 UTC [21792] LOG:  starting point-in-time recovery to earliest consistent point
2022-09-19 13:33:52.610 UTC [21800] FATAL:  the database system is starting up
2022-09-19 13:33:52.623 UTC [21802] FATAL:  the database system is starting up
2022-09-19 13:33:52.757 UTC [21792] LOG:  restored log file "0000001D.history" from archive
2022-09-19 13:33:53.239 UTC [21792] LOG:  restored log file "0000001C000000180000004F" from archive
2022-09-19 13:33:53.638 UTC [21808] FATAL:  the database system is starting up
2022-09-19 13:33:53.638 UTC [21792] LOG:  restored log file "0000001C.history" from archive
2022-09-19 13:33:53.655 UTC [21792] LOG:  redo starts at 18/4F000028
2022-09-19 13:33:54.089 UTC [21792] LOG:  restored log file "0000001C0000001800000050" from archive
2022-09-19 13:33:54.117 UTC [21792] LOG:  consistent recovery state reached at 18/50000050
2022-09-19 13:33:54.117 UTC [21792] LOG:  recovery stopping after reaching consistency
2022-09-19 13:33:54.118 UTC [21789] LOG:  shutdown at recovery target
2022-09-19 13:33:54.119 UTC [21810] LOG:  shutting down
2022-09-19 13:33:54.130 UTC [21789] LOG:  database system is shut down
````
Please let me know if there is any more info I can share.

**Comment by Sagri93** [comment]
> 

Sorry was trying to find them, I updated the issue

**Comment by CyberDem0n** [comment]
you need to use `recovery_target_action: promote`
