### ISSUE TITLE
recovery.conf file created for Patroni 2.1.1 - PG13

### ISSUE THREAD

**Issue by gerardo-ongres** [zalando/patroni#2434]
recovery.conf files are being created by Patroni in case of replica re-create fails. Recovery.conf files are incompatible with Postgres v13 or higher

**To Reproduce**
Rebooting a replica node

**Screenshots**
For this setup, they are 2 ways for replica bootstraping: PgBackrest and pgBasebackup. If both fails, a recovery.conf file seems to be created.

Traces from the logs:
Error log from Postgres:
```
[root@hvnplrrbdb02 log]# grep 'recovery.conf' postgresql-2022-10-1*
postgresql-2022-10-13_050403.log:2022-10-13 05:04:03.964 GMT [1888] FATAL:  using recovery command file "recovery.conf" is not supported
postgresql-2022-10-13_050416.log:2022-10-13 05:04:16.285 GMT [2663] FATAL:  using recovery command file "recovery.conf" is not supported
```

pgBackrest failed attempt to bootstrap:
```
2022-10-13 10:07:57,222 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2022-10-13 10:07:57,235 DEBUG: http://10.34.52.167:2379/ "GET /v2/keys/service/tprrbdb01/?recursive=true HTTP/1.1" 200 None
2022-10-13 10:07:57,235 DEBUG: Writing {"conn_url":"postgres://10.40.0.160:5432/postgres","api_url":"http://10.40.0.160:8679/patroni","state":"stopped","role":"uninitialized","version":"2.1.1"} to
 key /service/tprrbdb01/members/host_2 ttl=30 dir=False append=False
2022-10-13 10:07:57,236 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
:
2022-10-13 10:07:57,273 DEBUG: http://10.34.52.167:2379/ "PUT /v2/keys/service/tprrbdb01/members/host_2 HTTP/1.1" 201 355
2022-10-13 10:07:57,273 INFO: Lock owner: host_3; I am host_2
2022-10-13 10:07:57,339 DEBUG: Writing {"conn_url":"postgres://10.40.0.160:5432/postgres","api_url":"http://10.40.0.160:8679/patroni","state":"stopped","role":"uninitialized","version":"2.1.1"} to key /service/tprrbdb01/members/host_2 ttl=30 dir=False append=False
2022-10-13 10:07:57,339 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2022-10-13 10:07:57,363 DEBUG: http://10.34.52.167:2379/ "PUT /v2/keys/service/tprrbdb01/members/host_2 HTTP/1.1" 200 697
2022-10-13 10:07:57,363 INFO: trying to bootstrap from leader 'host_3'
2022-10-13 10:07:57,568 ERROR: Error creating replica using method pgbackrest: /usr/bin/pgbackrest --stanza=pg13 --force restore --type=preserve  --link-all exited with code=75
```

pgBaseBackup failed attemp to bootstrap:
```
2022-10-13 10:07:57,795 ERROR: Error when fetching backup: pg_basebackup exited with code=1
[1:45](https://aexp-cloud-and-infra.slack.com/archives/D02G4VBPLSC/p1666025145274569)
2022-10-13 10:08:02,801 INFO: Removing data directory: /pgsql/tprrbdb01/data
2022-10-13 10:08:02,801 INFO: Removing WAL directory: /pgsql/tprrbdb01/pg_wal
2022-10-13 10:08:03,010 ERROR: Could not remove data directory /pgsql/tprrbdb01/data
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/patroni/postgresql/__init__.py", line 1036, in remove_data_directory
    shutil.rmtree(pg_wal_realpath)
  File "/usr/local/lib/python3.10/shutil.py", line 728, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/local/lib/python3.10/shutil.py", line 726, in rmtree
    os.rmdir(path)
OSError: [Errno 16] Device or resource busy: '/pgsql/tprrbdb01/pg_wal'
2022-10-13 10:08:03,031 INFO: renaming WAL directory and updating symlink: /pgsql/tprrbdb01/pg_wal
2022-10-13 10:08:03,031 ERROR: Could not rename data directory /pgsql/tprrbdb01/data
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/patroni/postgresql/__init__.py", line 1036, in remove_data_directory
    shutil.rmtree(pg_wal_realpath)
  File "/usr/local/lib/python3.10/shutil.py", line 728, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/local/lib/python3.10/shutil.py", line 726, in rmtree
    os.rmdir(path)
OSError: [Errno 16] Device or resource busy: '/pgsql/tprrbdb01/pg_wal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/patroni/postgresql/__init__.py", line 1002, in move_data_directory
    os.rename(pg_wal_realpath, new_name)
OSError: [Errno 16] Device or resource busy: '/pgsql/tprrbdb01/pg_wal' -> '/pgsql/tprrbdb01/pg_wal_2022-10-13-10-08-03'
2022-10-13 10:08:03,139 ERROR: Error when fetching backup: pg_basebackup exited with code=1
```

Starting the member after failed bootstrap:
```
2022-10-13 10:08:07,362 INFO: Lock owner: host_3; I am host_2
2022-10-13 10:08:07,397 DEBUG: Writing {"conn_url":"postgres://10.40.0.160:5432/postgres","api_url":"http://10.40.0.160:8679/patroni","state":"stopped","role":"uninitialized","version":"2.1.1"} to key /service/tprrbdb01/members/host_2 ttl=30 dir=False append=False
2022-10-13 10:08:07,397 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2022-10-13 10:08:07,421 DEBUG: http://10.34.52.167:2379/ "PUT /v2/keys/service/tprrbdb01/members/host_2 HTTP/1.1" 200 697
2022-10-13 10:08:07,421 INFO: starting as a secondary
2022-10-13 10:08:07,434 WARNING: Removing unexpected parameter=recovery_target_timeline value=latest from the config
2022-10-13 10:08:07,434 WARNING: Removing unexpected parameter=restore_command value=sh /etc/patroni/cfg/restore_command_pgbackrest.sh %p %f from the config
2022-10-13 10:08:07,434 WARNING: Removing unexpected parameter=standby_mode value=on from the config
2022-10-13 10:08:07,453 WARNING: Removing unexpected parameter=standby_mode value=on from the config
2022-10-13 10:08:07,467 DEBUG: Starting postgres: /usr/pgsql-13/bin/postgres -D /pgsql/tprrbdb01/data --config-file=/pgsql/tprrbdb01/data/postgresql.conf --listen_addresses=localhost,10.40.0.160 --port=5432 --cluster_name=tprrbdb01 --wal_level=replica --hot_standby=on --max_connections=200 --max_wal_senders=10 --max_prepared_transactions=0 --max_locks_per_transaction=64 --track_commit_timestamp=False --max_replication_slots=10 --max_worker_processes=8 --wal_log_hints=on
```

As a result, recovery file appears into $PGDATA:
```
[root@hvnplrrbdb02 data]# cat recovery.conf
# Do not edit this file manually!
# It will be overwritten by Patroni!
primary_conninfo = 'user=rep_user password=xxx host=10.x.x.x port=5432 sslmode=prefer application_name=host_2'
```

Date of `recovery.conf` last modification timestamp seems to match patroni logs:
```
[root@hvnplrrbdb02 data]# stat recovery.conf
  File: 'recovery.conf'
  Size: 190             Blocks: 8          IO Block: 4096   regular file
Device: fd0bh/64779d    Inode: 30          Links: 1
Access: (0600/-rw-------)  Uid: ( 1001/postgres)   Gid: ( 1001/postgres)
Access: 2022-10-13 10:08:07.432033225 -0700
Modify: 2022-10-13 10:08:07.433033220 -0700
Change: 2022-10-13 10:08:07.433033220 -0700
 Birth: -
```

**Environment**
- Patroni version: 2.1.1
- PostgreSQL version: 13.5
- DCS (and its version): etcd 3.1

**Patroni configuration file**
```
[erauser@hvgplrrbdb01 ~]$ patronictl -c /etc/patroni/patroni.yml show-config
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  callbacks:
    on_role_change: /etc/patroni/patroni_callback.sh
    on_start: /etc/patroni/patroni_callback.sh
    on_stop: /etc/patroni/patroni_callback.sh
  create_replica_methods:
  - pgbackrest
  - basebackup
  parameters:
    archive_command: sh /etc/patroni/cfg/archive_command_pgbackrest.sh %p %f
    archive_mode: 'on'
    archive_timeout: 0
    config_file: /pgsql/tprrbdb01/data/postgresql.conf
    default_tablespace: tblspc_data
    hot_standby: 'on'
    max_connections: 200
    max_locks_per_transaction: 64
    max_prepared_transactions: 0
    max_replication_slots: 10
    max_wal_senders: 10
    max_wal_size: 4GB
    max_worker_processes: 8
    min_wal_size: 1GB
    temp_tablespaces: tblspc_temp
    track_commit_timestamp: false
    wal_compression: 'on'
    wal_keep_size: 4000
    wal_level: hot_standby
    wal_log_hints: true
  pgbackrest:
    command: /usr/bin/pgbackrest --stanza=pg13 --force restore --type=preserve  --link-all
    keep_data: true
    no_params: true
  recovery_conf:
    restore_command: sh /etc/patroni/cfg/restore_command_pgbackrest.sh %p %f
  use_pg_rewind: true
  use_slots: false
retry_timeout: 10
synchronous_mode: 'on'
synchronous_mode_strict: 'on'
synchronous_node_count: 1
ttl: 30
```

Any insights will be very appreciated.
Cheers,
Gerardo

**Comment by CyberDem0n** [comment]
Since replica creation method fails Patroni is trying to remove $PGDATA, pg_wal, and tablespaces.
Removal  of these directories also fails with the `[Errno 16] Device or resource busy`.
From that moment $PGDATA isn't empty, but isn't valid either. E.g., there is no `global/pg_control` file and no `PG_VERSION` files. The last one is used to figure out the major version.
As a result, the [get_major_version()](https://github.com/zalando/patroni/blob/f4ae55b92ab105220d454c79b71f95582a982320/patroni/postgresql/__init__.py#L180-L187) method returns 0 and effectively it means that the version is older than 12.

It is hard to decide what would be the correct behavior in case if the $PGDATA is damaged. Doing a next attempt to remove PGDATA/pg_wal/tablespaces might sound logical, but it could produce unwanted damage because we not necessarily know that it was a leftover from a failed attempt.

**Comment by gerardo-ongres** [comment]
Thanks for your answer, @CyberDem0n. As per your statament
> there is no global/pg_control file and no PG_VERSION files.

That does not seems to be the case here, since after `recovery.conf` file removal, Patroni (and postgres) start and work normally.

**Comment by CyberDem0n** [comment]
@gerardo-ongres than you need to describe more precise how to reproduce it.

**Comment by CyberDem0n** [comment]
> In our environment

Sorry, but I don't have an access to your environment.
You have to describe how to reproduce it anywhere.

**Comment by gerardo-ongres** [comment]
Could we setup a meeting, so we can show how we reproduce the issue in our enviromnent, @CyberDem0n ?

**Comment by CyberDem0n** [comment]
Sorry, but I don't do private consulting.
Gut feeling tells me that you start Patroni _before_ all mounts get properly accessible.
