### ISSUE TITLE
switchover error with incorrect answer

### ISSUE THREAD

**Issue by artemsafiyulin** [zalando/patroni#2452]
**Describe the bug**
During the execution of switchover, when answering the last question first with any non-Latin letter, and then correctly specifying the answer "y" - patroni does not perform switchover, but ends with an error.

**To Reproduce**
Perform the following steps:
patronictl switchover
when the last question appears (Are you sure you want to switchover cluster postgres-cluster, demoting current master ub-64-142? [y/N]:)
enter any non-Latin letter, erase it, then enter "y"
to get an error

**Expected behavior**
It was expected that patroni, having received the correct response, would perform the switch without errors

**Environment**
- Patroni version: 2.1.3/2.1.4
- PostgreSQL version: 15.0/13.7
- DCS (and its version): etcd 3.3.27/3.3.25

**Have you checked Patroni logs?**
Traceback (most recent call last):
  File "/usr/local/bin/patronictl", line 8, in <module>
    sys.exit(ctl())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/patroni/ctl.py", line 762, in switchover
    _do_failover_or_switchover(obj, 'switchover', cluster_name, master, candidate, force, scheduled)
  File "/usr/local/lib/python3.8/dist-packages/patroni/ctl.py", line 711, in _do_failover_or_switchover
    if not click.confirm('Are you sure you want to {0} cluster {1}{2}?'
  File "/usr/lib/python3/dist-packages/click/termui.py", line 167, in confirm
    value = visible_prompt_func('').lower().strip()
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte

**Comment by CyberDem0n** [comment]
That's not a Patroni issue per se, the "wrong" input is coming from your terminal.

**Comment by artemsafiyulin** [comment]
Not quite so, as a result, I enter the correct "y" character in the response

**Comment by CyberDem0n** [comment]
I suppose you entered a multibyte character, but removed only one byte, hence there is an error `UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte`. This is not a Patroni problem that you input malformed utf-8 characters.
