### ISSUE TITLE
Problem with auth in etcd3

### ISSUE THREAD

**Issue by glushakov** [zalando/patroni#2457]
**Describe the bug**
Problem with auth in etcd3

Hello. 
I have a number of patroni clusters which using an external shared etcd3 (3 nodes HA-cluster)
Simple authentication is configured on the etcd.

Today 4 Patroni Clusters reported  the same issue. I found that some nodes get an error when interacting with etcd

2022-11-17 10:00:54,681 ERROR: refresh_lease
Traceback (most recent call last):
  File "/var/lib/pgsql/patroni_venv/lib64/python3.6/site-packages/patroni/dcs/etcd3.py", line 617, in refresh_lease
    return self.retry(self._do_refresh_lease)
  File "/var/lib/pgsql/patroni_venv/lib64/python3.6/site-packages/patroni/dcs/etcd.py", line 447, in retry
    return retry(*args, **kwargs)
  File "/var/lib/pgsql/patroni_venv/lib64/python3.6/site-packages/patroni/utils.py", line 334, in __call__
    return func(*args, **kwargs)
  File "/var/lib/pgsql/patroni_venv/lib64/python3.6/site-packages/patroni/dcs/etcd3.py", line 610, in _do_refresh_lease
    self._lease = self._client.lease_grant(self._ttl, retry)
  File "/var/lib/pgsql/patroni_venv/lib64/python3.6/site-packages/patroni/dcs/etcd3.py", line 319, in lease_grant
    return self.call_rpc('/lease/grant', {'TTL': ttl}, retry)['ID']
  File "/var/lib/pgsql/patroni_venv/lib64/python3.6/site-packages/patroni/dcs/etcd3.py", line 558, in call_rpc
    ret = super(PatroniEtcd3Client, self).call_rpc(method, fields, retry)
  File "/var/lib/pgsql/patroni_venv/lib64/python3.6/site-packages/patroni/dcs/etcd3.py", line 262, in call_rpc
    return self.api_execute(self.version_prefix + method, self._MPOST, fields)
  File "/var/lib/pgsql/patroni_venv/lib64/python3.6/site-packages/patroni/dcs/etcd.py", line 257, in api_execute
    return self._handle_server_response(response)
  File "/var/lib/pgsql/patroni_venv/lib64/python3.6/site-packages/patroni/dcs/etcd3.py", line 220, in _handle_server_response
    _raise_for_data(data, response.status)
  File "/var/lib/pgsql/patroni_venv/lib64/python3.6/site-packages/patroni/dcs/etcd3.py", line 136, in _raise_for_data
    raise err(code, error, status_code)
patroni.dcs.etcd3.InvalidAuthToken: <InvalidAuthToken error: 'etcdserver: invalid auth token', code: 16>
2022-11-17 10:00:54,682 INFO: Lock owner: postgres1; I am postgres2
....
and then repeating this error
...

This error happened on 4 patroni clusters at the same time. I examined the etcd logs, and decided that the problem was due to performance problems with one of the etcd nodes. (nodes made reelect, but all finished well, cluster was health)
But even after everything returned to normal on the etcd, some nodes of the patroni clusters continued to receive an error.

It helped restarting the patroni on each problem node, or restarting the node etcd with which the patroni was trying to contact.

Any thoughts why this could happen? I suspect simple authentication is the problem.

patronictl show-config
check_timeline: false
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    max_connections: 300
    max_locks_per_transaction: 64
    max_prepared_transactions: 0
    max_replication_slots: 10
    max_wal_senders: 10
    max_worker_processes: 8
    track_commit_timestamp: false
    wal_keep_size: 6GB
    wal_level: replica
    wal_log_hints: true
  pg_hba:
   <cut>
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: true
synchronous_mode_strict: false
ttl: 30

patroni.yml

etcd3:
  hosts: etcd-cluster-1:2379,etcd-cluster-2:2379,etcd-cluster-3:2379
  protocol: http
  username: patroni_etcd
  password: password

**Comment by CyberDem0n** [comment]
I think it is a duplicate of https://github.com/zalando/patroni/issues/2331
It would have been much easier to verify if you followed the issue template

**Comment by glushakov** [comment]
Thanks, this seems to be my case. 
sorry for the wrong request
