### ISSUE TITLE
Patroni failed to boot up if set password_encryption as "scram-sha-256"

### ISSUE THREAD

**Issue by duj4** [zalando/patroni#2458]
**Describe the bug**
Patroni failed to register to Consul if password_encryption is set to "scram-sha-256".

**To Reproduce**
1. Set up a consul as DCS
2. Configure password_encryption as "scram-sha-256" in patroni.yml
3. Bring up patroni

**Expected behavior**
Patroni should be able to register to consul and bring up PostgreSQL.

**Screenshots**
N/A

**Environment**
- Patroni version: 2.1.4
- PostgreSQL version: 13.7
- DCS (and its version): Consul, 1.12.2

**Patroni configuration file**
```
scope: pgclusterdr
namespace: /linux/
name: vhkgpf77.linux.hkintegrationlab.com

log:
  level: INFO
  format: '%(asctime)s %(levelname)s: %(message)s'
  dateformat: '%Y-%m-%d %H:%M:%S %z'
  dir: /d/d1/jsm/patroni/log
  file_num: 7
  filesize: 1048576

consul:
  host: vhkgpf77.linux.hkintegrationlab.com:8501
  port: 8501
  scheme: https
  url: https://vhkgpf77.linux.hkintegrationlab.com:8501
  verify: true
  cacert: /d/d1/jsm/certs/ca.crt
  cert: /d/d1/jsm/certs/consul_client.crt
  key: /d/d1/jsm/certs/consul_client.key
  dc: linux
  consistency: default
  register_service: true
  service_check_interval: 15s
  service_check_tls_server_name: vhkgpf77.linux.hkintegrationlab.com

restapi:
  connect_address: vhkgpf77.linux.hkintegrationlab.com:8008
  listen: vhkgpf77.linux.hkintegrationlab.com:8008
  cafile: /d/d1/jsm/certs/ca.crt
  certfile: /d/d1/jsm/certs/pg_server.crt
  keyfile: /d/d1/jsm/certs/pg_server.key
  verify_client: optional
  allowlist:
    - vhkgpf77.linux.hkintegrationlab.com
    - vhkgpf82.linux.hkintegrationlab.com

ctl:
  cacert: /d/d1/jsm/certs/ca.crt
  certfile: /d/d1/jsm/certs/pg_server.crt
  keyfile: /d/d1/jsm/certs/pg_server.key

bootstrap:
  dcs:
    loop_wait: 10
    ttl: 30
    retry_timeout: 10
    maximum_lag_on_failvoer: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        # meet Secarch requirements regarding logging
        # https://www.postgresql.org/docs/13/runtime-config-logging.html
        logging_collector: 'on'
        log_destination: stderr
        log_filename: postgresql-%Y%m%d.log
        log_file_mode: 0600
        log_truncate_on_rotation: 'on'
        log_rotation_age: 1d
        log_rotation_size: 1GB
        log_min_messages: warning
        log_min_error_statement: warning
        debug_print_parse: 'off'
        debug_print_rewritten: 'off'
        debug_print_plan: 'off'
        debug_pretty_print: 'on'
        log_connections: 'on'
        log_disconnections: 'off'
        log_error_verbosity: verbose
        log_hostname: 'off'
        log_line_prefix: '%m [%p]: [%l-1] db=%d, user=%u, app=%a, client=%r '
        log_statement: ddl
        log_timezone: GMT
        password_encryption: 'scram-sha-256'
        # install pgaudit ahead via yum install
        # shared_preload_libraries: pgaudit
        # pgaudit.log: ddl, role, write
        # ssl
        ssl: 'on'
        ssl_ca_file: /d/d1/jsm/certs/ca.crt
        ssl_cert_file: /d/d1/jsm/certs/pg_server.crt
        ssl_key_file: /d/d1/jsm/certs/pg_server.key
        ssl_ciphers: HIGH:!3DES

pg_hba:
    - hostssl jiradb          jiradbuser      0.0.0.0/0               cert clientcert=1
    - hostssl all             all             0.0.0.0/0               scram-sha-256
    - hostssl replication     replicator      0.0.0.0/0               scram-sha-256
    - hostssl rewind          rewind          0.0.0.0/0               scram-sha-256

users:

postgresql:
  connect_address: vhkgpf77.linux.hkintegrationlab.com:5432
  listen: vhkgpf77.linux.hkintegrationlab.com:5432
  data_dir: /d/d1/jsm/postgres/pg_data
  bin_dir: /usr/bin/
  pgpass: /d/d1/jsm/patroni/pgpass
  authentication:
    superuser:
      username: itsm_jsm_qa
      password: Password01
    replication:
      username: replicator
      password: replicator
    rewind:
      username: rewind
      password: rewind
  parameters:
    unix_socket_directories: /d/d1/jsm/postgres

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
```

**patronictl show-config**
```
patroni is not up, patronictl does not work so far.
```

**Have you checked Patroni logs?**
```
2022-11-20 13:31:09 +0800 INFO: removing initialize key after failed attempt to bootstrap the cluster
2022-11-20 13:31:09 +0800 INFO: renaming data directory to /d/d1/jsm/postgres/pg_data_2022-11-20-13-31-09
2022-11-20 13:31:09 +0800 INFO: Deregister service pgclusterdr/vhkgpf77.linux.hkintegrationlab.com
2022-11-20 13:31:09 +0800 INFO: Deregister service pgclusterdr/vhkgpf77.linux.hkintegrationlab.com
2022-11-20 13:41:01 +0800 INFO: No PostgreSQL configuration items changed, nothing to reload.
2022-11-20 13:41:01 +0800 INFO: Deregister service pgclusterdr/vhkgpf77.linux.hkintegrationlab.com
2022-11-20 13:41:01 +0800 INFO: Lock owner: None; I am vhkgpf77.linux.hkintegrationlab.com
2022-11-20 13:41:01 +0800 INFO: Deregister service pgclusterdr/vhkgpf77.linux.hkintegrationlab.com
2022-11-20 13:41:01 +0800 INFO: trying to bootstrap a new cluster
2022-11-20 13:41:01 +0800 INFO: Lock owner: None; I am vhkgpf77.linux.hkintegrationlab.com
2022-11-20 13:41:01 +0800 INFO: not healthy enough for leader race
2022-11-20 13:41:01 +0800 INFO: Deregister service pgclusterdr/vhkgpf77.linux.hkintegrationlab.com
2022-11-20 13:41:01 +0800 INFO: bootstrap in progress
2022-11-20 13:41:01 +0800 INFO: postmaster pid=1282432
2022-11-20 13:41:01 +0800 INFO: establishing a new patroni connection to the postgres cluster
2022-11-20 13:41:02 +0800 INFO: establishing a new patroni connection to the postgres cluster
2022-11-20 13:41:02 +0800 WARNING: Retry got exception: 'connection problems'
2022-11-20 13:41:02 +0800 WARNING: Failed to determine PostgreSQL state from the connection, falling back to cached role
2022-11-20 13:41:02 +0800 INFO: Register service pgclusterdr, params {'service_id': 'pgclusterdr/vhkgpf77.linux.hkintegrationlab.com', 'address': 'vhkgpf77.linux.hkintegrationlab.com', 'port': 5432, 'check': {'http': 'https://vhkgpf77.linux.hkintegrationlab.com:8008/master', 'interval': '15s', 'DeregisterCriticalServiceAfter': '150.0s', 'TLSServerName': 'vhkgpf77.linux.hkintegrationlab.com'}, 'tags': ['master'], 'enable_tag_override': True}
2022-11-20 13:41:02 +0800 INFO: running post_bootstrap
2022-11-20 13:41:02 +0800 ERROR: post_bootstrap
Traceback (most recent call last):
  File "/d/d1/jsm/patroni/patroni_venv/lib64/python3.9/site-packages/patroni/postgresql/bootstrap.py", line 330, in post_bootstrap
    self.create_or_update_role(superuser['username'], superuser['password'], ['SUPERUSER'])
  File "/d/d1/jsm/patroni/patroni_venv/lib64/python3.9/site-packages/patroni/postgresql/bootstrap.py", line 314, in create_or_update_role
    END;$$""".format(quote_literal(name), quote_ident(name, self._postgresql.connection()), ' '.join(options))
  File "/d/d1/jsm/patroni/patroni_venv/lib64/python3.9/site-packages/patroni/postgresql/__init__.py", line 255, in connection
    return self._connection.get()
  File "/d/d1/jsm/patroni/patroni_venv/lib64/python3.9/site-packages/patroni/postgresql/connection.py", line 24, in get
    self._connection = psycopg.connect(**self._conn_kwargs)
  File "/d/d1/jsm/patroni/patroni_venv/lib64/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "vhkgpf77.linux.hkintegrationlab.com" (10.233.241.150), port 5432 failed: could not initiate GSSAPI security context: Unspecified GSS failure.  Minor code may provide more information: Server not found in Kerberos database
connection to server at "vhkgpf77.linux.hkintegrationlab.com" (10.233.241.150), port 5432 failed: FATAL:  password authentication failed for user "itsm_jsm_qa"
connection to server at "vhkgpf77.linux.hkintegrationlab.com" (10.233.241.150), port 5432 failed: FATAL:  no pg_hba.conf entry for host "10.233.241.150", user "itsm_jsm_qa", database "postgres", SSL off

2022-11-20 13:41:02 +0800 INFO: removing initialize key after failed attempt to bootstrap the cluster
2022-11-20 13:41:02 +0800 INFO: renaming data directory to /d/d1/jsm/postgres/pg_data_2022-11-20-13-41-02
2022-11-20 13:41:02 +0800 INFO: Deregister service pgclusterdr/vhkgpf77.linux.hkintegrationlab.com
2022-11-20 13:41:03 +0800 INFO: Deregister service pgclusterdr/vhkgpf77.linux.hkintegrationlab.com
```

**Have you checked PostgreSQL logs?**
```
2022-11-20 07:18:18.115 GMT [1288262]: [4-1] db=, user=, app=, client= LOG:  00000: starting PostgreSQL 13.7 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-10), 64-bit
2022-11-20 07:18:18.115 GMT [1288262]: [5-1] db=, user=, app=, client= LOCATION:  PostmasterMain, postmaster.c:1125
2022-11-20 07:18:18.116 GMT [1288262]: [6-1] db=, user=, app=, client= LOG:  00000: listening on IPv4 address "10.233.241.150", port 5432
2022-11-20 07:18:18.116 GMT [1288262]: [7-1] db=, user=, app=, client= LOCATION:  StreamServerPort, pqcomm.c:588
2022-11-20 07:18:18.120 GMT [1288262]: [8-1] db=, user=, app=, client= LOG:  00000: listening on Unix socket "/d/d1/jsm/postgres/.s.PGSQL.5432"
2022-11-20 07:18:18.120 GMT [1288262]: [9-1] db=, user=, app=, client= LOCATION:  StreamServerPort, pqcomm.c:582
2022-11-20 07:18:18.124 GMT [1288265]: [1-1] db=, user=, app=, client= LOG:  00000: database system was shut down at 2022-11-20 07:18:17 GMT
2022-11-20 07:18:18.124 GMT [1288265]: [2-1] db=, user=, app=, client= LOCATION:  StartupXLOG, xlog.c:6391
2022-11-20 07:18:18.124 GMT [1288266]: [1-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59684) LOG:  00000: connection received: host=10.233.241.150 port=59684
2022-11-20 07:18:18.124 GMT [1288266]: [2-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59684) LOCATION:  BackendInitialize, postmaster.c:4409
2022-11-20 07:18:18.131 GMT [1288262]: [10-1] db=, user=, app=, client= LOG:  00000: database system is ready to accept connections
2022-11-20 07:18:18.131 GMT [1288262]: [11-1] db=, user=, app=, client= LOCATION:  reaper, postmaster.c:3068
2022-11-20 07:18:18.134 GMT [1288273]: [1-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59690) LOG:  00000: connection received: host=10.233.241.150 port=59690
2022-11-20 07:18:18.134 GMT [1288273]: [2-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59690) LOCATION:  BackendInitialize, postmaster.c:4409
2022-11-20 07:18:18.145 GMT [1288275]: [1-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59692) LOG:  00000: connection received: host=10.233.241.150 port=59692
2022-11-20 07:18:18.145 GMT [1288275]: [2-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59692) LOCATION:  BackendInitialize, postmaster.c:4409
2022-11-20 07:18:18.150 GMT [1288276]: [1-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59698) LOG:  00000: connection received: host=10.233.241.150 port=59698
2022-11-20 07:18:18.150 GMT [1288276]: [2-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59698) LOCATION:  BackendInitialize, postmaster.c:4409
2022-11-20 07:18:18.161 GMT [1288277]: [1-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59700) LOG:  00000: connection received: host=10.233.241.150 port=59700
2022-11-20 07:18:18.161 GMT [1288277]: [2-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59700) LOCATION:  BackendInitialize, postmaster.c:4409
2022-11-20 07:18:18.168 GMT [1288278]: [1-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59706) LOG:  00000: connection received: host=10.233.241.150 port=59706
2022-11-20 07:18:18.168 GMT [1288278]: [2-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59706) LOCATION:  BackendInitialize, postmaster.c:4409
2022-11-20 07:18:18.175 GMT [1288278]: [3-1] db=postgres, user=itsm_jsm_qa, app=[unknown], client=10.233.241.150(59706) FATAL:  28P01: password authentication failed for user "itsm_jsm_qa"
2022-11-20 07:18:18.175 GMT [1288278]: [4-1] db=postgres, user=itsm_jsm_qa, app=[unknown], client=10.233.241.150(59706) DETAIL:  User "itsm_jsm_qa" does not have a valid SCRAM secret.
        Connection matched pg_hba.conf line 100: "hostssl all             all             0.0.0.0/0               scram-sha-256"
2022-11-20 07:18:18.175 GMT [1288278]: [5-1] db=postgres, user=itsm_jsm_qa, app=[unknown], client=10.233.241.150(59706) LOCATION:  auth_failed, auth.c:334
2022-11-20 07:18:18.176 GMT [1288279]: [1-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59708) LOG:  00000: connection received: host=10.233.241.150 port=59708
2022-11-20 07:18:18.176 GMT [1288279]: [2-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59708) LOCATION:  BackendInitialize, postmaster.c:4409
2022-11-20 07:18:18.176 GMT [1288279]: [3-1] db=postgres, user=itsm_jsm_qa, app=[unknown], client=10.233.241.150(59708) FATAL:  28000: no pg_hba.conf entry for host "10.233.241.150", user "itsm_jsm_qa", database "postgres", SSL off
2022-11-20 07:18:18.176 GMT [1288279]: [4-1] db=postgres, user=itsm_jsm_qa, app=[unknown], client=10.233.241.150(59708) LOCATION:  ClientAuthentication, auth.c:503
2022-11-20 07:18:18.920 GMT [1288280]: [1-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59710) LOG:  00000: connection received: host=10.233.241.150 port=59710
2022-11-20 07:18:18.920 GMT [1288280]: [2-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59710) LOCATION:  BackendInitialize, postmaster.c:4409
2022-11-20 07:18:18.926 GMT [1288281]: [1-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59716) LOG:  00000: connection received: host=10.233.241.150 port=59716
2022-11-20 07:18:18.926 GMT [1288281]: [2-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59716) LOCATION:  BackendInitialize, postmaster.c:4409
2022-11-20 07:18:18.932 GMT [1288281]: [3-1] db=postgres, user=itsm_jsm_qa, app=[unknown], client=10.233.241.150(59716) FATAL:  28P01: password authentication failed for user "itsm_jsm_qa"
2022-11-20 07:18:18.932 GMT [1288281]: [4-1] db=postgres, user=itsm_jsm_qa, app=[unknown], client=10.233.241.150(59716) DETAIL:  User "itsm_jsm_qa" does not have a valid SCRAM secret.
        Connection matched pg_hba.conf line 100: "hostssl all             all             0.0.0.0/0               scram-sha-256"
2022-11-20 07:18:18.932 GMT [1288281]: [5-1] db=postgres, user=itsm_jsm_qa, app=[unknown], client=10.233.241.150(59716) LOCATION:  auth_failed, auth.c:334
2022-11-20 07:18:18.933 GMT [1288282]: [1-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59718) LOG:  00000: connection received: host=10.233.241.150 port=59718
2022-11-20 07:18:18.933 GMT [1288282]: [2-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59718) LOCATION:  BackendInitialize, postmaster.c:4409
2022-11-20 07:18:18.934 GMT [1288282]: [3-1] db=postgres, user=itsm_jsm_qa, app=[unknown], client=10.233.241.150(59718) FATAL:  28000: no pg_hba.conf entry for host "10.233.241.150", user "itsm_jsm_qa", database "postgres", SSL off
2022-11-20 07:18:18.934 GMT [1288282]: [4-1] db=postgres, user=itsm_jsm_qa, app=[unknown], client=10.233.241.150(59718) LOCATION:  ClientAuthentication, auth.c:503
2022-11-20 07:18:18.940 GMT [1288284]: [1-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59720) LOG:  00000: connection received: host=10.233.241.150 port=59720
2022-11-20 07:18:18.940 GMT [1288284]: [2-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59720) LOCATION:  BackendInitialize, postmaster.c:4409
2022-11-20 07:18:18.945 GMT [1288285]: [1-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59726) LOG:  00000: connection received: host=10.233.241.150 port=59726
2022-11-20 07:18:18.945 GMT [1288285]: [2-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59726) LOCATION:  BackendInitialize, postmaster.c:4409
2022-11-20 07:18:18.980 GMT [1288287]: [1-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59728) LOG:  00000: connection received: host=10.233.241.150 port=59728
2022-11-20 07:18:18.980 GMT [1288287]: [2-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59728) LOCATION:  BackendInitialize, postmaster.c:4409
2022-11-20 07:18:18.985 GMT [1288288]: [1-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59734) LOG:  00000: connection received: host=10.233.241.150 port=59734
2022-11-20 07:18:18.985 GMT [1288288]: [2-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59734) LOCATION:  BackendInitialize, postmaster.c:4409
2022-11-20 07:18:18.991 GMT [1288288]: [3-1] db=postgres, user=itsm_jsm_qa, app=[unknown], client=10.233.241.150(59734) FATAL:  28P01: password authentication failed for user "itsm_jsm_qa"
2022-11-20 07:18:18.991 GMT [1288288]: [4-1] db=postgres, user=itsm_jsm_qa, app=[unknown], client=10.233.241.150(59734) DETAIL:  User "itsm_jsm_qa" does not have a valid SCRAM secret.
        Connection matched pg_hba.conf line 100: "hostssl all             all             0.0.0.0/0               scram-sha-256"
2022-11-20 07:18:18.991 GMT [1288288]: [5-1] db=postgres, user=itsm_jsm_qa, app=[unknown], client=10.233.241.150(59734) LOCATION:  auth_failed, auth.c:334
2022-11-20 07:18:18.992 GMT [1288289]: [1-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59736) LOG:  00000: connection received: host=10.233.241.150 port=59736
2022-11-20 07:18:18.992 GMT [1288289]: [2-1] db=[unknown], user=[unknown], app=[unknown], client=10.233.241.150(59736) LOCATION:  BackendInitialize, postmaster.c:4409
2022-11-20 07:18:18.993 GMT [1288289]: [3-1] db=postgres, user=itsm_jsm_qa, app=[unknown], client=10.233.241.150(59736) FATAL:  28000: no pg_hba.conf entry for host "10.233.241.150", user "itsm_jsm_qa", database "postgres", SSL off
2022-11-20 07:18:18.993 GMT [1288289]: [4-1] db=postgres, user=itsm_jsm_qa, app=[unknown], client=10.233.241.150(59736) LOCATION:  ClientAuthentication, auth.c:503
2022-11-20 07:18:18.998 GMT [1288262]: [12-1] db=, user=, app=, client= LOG:  00000: received immediate shutdown request
2022-11-20 07:18:18.998 GMT [1288262]: [13-1] db=, user=, app=, client= LOCATION:  pmdie, postmaster.c:2897
2022-11-20 07:18:19.000 GMT [1288270]: [1-1] db=, user=, app=, client= WARNING:  57P02: terminating connection because of crash of another server process
2022-11-20 07:18:19.000 GMT [1288270]: [2-1] db=, user=, app=, client= DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2022-11-20 07:18:19.000 GMT [1288270]: [3-1] db=, user=, app=, client= HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2022-11-20 07:18:19.000 GMT [1288270]: [4-1] db=, user=, app=, client= LOCATION:  quickdie, postgres.c:2802
2022-11-20 07:18:19.003 GMT [1288262]: [14-1] db=, user=, app=, client= LOG:  00000: database system is shut down
2022-11-20 07:18:19.003 GMT [1288262]: [15-1] db=, user=, app=, client= LOCATION:  UnlinkLockFiles, miscinit.c:933
```

**Have you tried to use GitHub issue search?**
Yes, but did find any similar issue.

**Additional context**
Once I changed it to "md5", it works.

**Comment by CyberDem0n** [comment]
It is not a Patroni problem but something related to your configuration.

> Patroni configuration file

It is incomplete.

> Have you checked Patroni logs?
Have you checked PostgreSQL logs?

Why timerange between Patroni and Postgres logs don't match?

**Comment by duj4** [comment]
1. I added the rest part of patroni configuration
2. Though the timestamp is different, the content is the same, I copied the earlier parts

**Comment by CyberDem0n** [comment]
@duj4 I can't reproduce it. There is something wrong with your configuration.
Please provide a self-contained case based on https://github.com/zalando/patroni/blob/master/postgres0.yml

For example with below changes to the config pg_hba.conf requires scram even for unix socket connection and everything still works like a charm:
```diff
diff --git a/postgres0.yml b/postgres0.yml
index c10b847..6813622 100644
--- a/postgres0.yml
+++ b/postgres0.yml
@@ -55,6 +55,7 @@ bootstrap:
       use_pg_rewind: true
 #      use_slots: true
       parameters:
+        password_encryption: 'scram-sha-256'
 #        wal_level: hot_standby
 #        hot_standby: "on"
 #        max_connections: 100
@@ -74,6 +75,7 @@ bootstrap:

   # some desired options for 'initdb'
   initdb:  # Note: It needs to be a list (some options need values, others are switches)
+  - auth: scram-sha-256
   - encoding: UTF8
   - data-checksums

@@ -81,8 +83,8 @@ bootstrap:
   # For kerberos gss based connectivity (discard @.*$)
   #- host replication replicator 127.0.0.1/32 gss include_realm=0
   #- host all all 0.0.0.0/0 gss include_realm=0
-  - host replication replicator 127.0.0.1/32 md5
-  - host all all 0.0.0.0/0 md5
+  - host replication replicator 127.0.0.1/32 scram-sha-256
+  - host all all 0.0.0.0/0 scram-sha-256
 #  - hostssl all all 0.0.0.0/0 md5

   # Additional script to be launched after initial cluster creation (will be passed the connection URL as parameter)
```

**Comment by duj4** [comment]
Hi @CyberDem0n , apologies for my tardy reply, once I added "auth: scram-sha-256" in "initdb", the issue got fixed, this should be the key I think.
