### ISSUE TITLE
Exception with the API after 2.1.5 upgrade

### ISSUE THREAD

**Issue by aurelien-reeves-scalingo** [zalando/patroni#2466]
**Describe the bug**
Right after upgraded Patroni to 2.1.5, the logs started to show an exception related to the API:

```console
2022-11-29 15:54:44.027356116 +0100 CET [postgresql-1] Traceback (most recent call last):
2022-11-29 15:54:44.028621535 +0100 CET [postgresql-1] File "/usr/local/lib/python3.9/dist-packages/patroni/api.py", line 844, in process_request_thread
2022-11-29 15:54:44.027211556 +0100 CET [postgresql-1] Exception in thread Thread-25:
2022-11-29 15:54:44.027359108 +0100 CET [postgresql-1] File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2022-11-29 15:54:44.028881590 +0100 CET [postgresql-1] File "/usr/lib/python3.9/socketserver.py", line 654, in process_request_thread
2022-11-29 15:54:44.028614950 +0100 CET [postgresql-1] self._target(*self._args, **self._kwargs)
2022-11-29 15:54:44.028383168 +0100 CET [postgresql-1] File "/usr/lib/python3.9/threading.py", line 892, in run
2022-11-29 15:54:44.028825824 +0100 CET [postgresql-1] super(RestApiServer, self).process_request_thread(request, client_address)
2022-11-29 15:54:44.029650842 +0100 CET [postgresql-1] self.shutdown_request(request)
2022-11-29 15:54:44.028376841 +0100 CET [postgresql-1] self.run()
2022-11-29 15:54:44.029692733 +0100 CET [postgresql-1] File "/usr/local/lib/python3.9/dist-packages/patroni/api.py", line 848, in shutdown_request
2022-11-29 15:54:44.029946159 +0100 CET [postgresql-1] File "/usr/lib/python3.9/ssl.py", line 1285, in unwrap
2022-11-29 15:54:44.030793778 +0100 CET [postgresql-1] ConnectionResetError: [Errno 104] Connection reset by peer
2022-11-29 15:54:44.029896642 +0100 CET [postgresql-1] request.unwrap()
2022-11-29 15:54:44.030790053 +0100 CET [postgresql-1] s = self._sslobj.shutdown()
2022-11-29 15:54:56.039742434 +0100 CET [postgresql-1] Exception in thread Thread-28:
2022-11-29 15:54:56.040980510 +0100 CET [postgresql-1] File "/usr/lib/python3.9/socketserver.py", line 654, in process_request_thread
2022-11-29 15:54:56.040079784 +0100 CET [postgresql-1] self.run()
2022-11-29 15:54:56.040925147 +0100 CET [postgresql-1] super(RestApiServer, self).process_request_thread(request, client_address)
2022-11-29 15:54:56.041817920 +0100 CET [postgresql-1] self.shutdown_request(request)
2022-11-29 15:54:56.040370490 +0100 CET [postgresql-1] File "/usr/local/lib/python3.9/dist-packages/patroni/api.py", line 844, in process_request_thread
2022-11-29 15:54:56.039753387 +0100 CET [postgresql-1] File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2022-11-29 15:54:56.040086970 +0100 CET [postgresql-1] File "/usr/lib/python3.9/threading.py", line 892, in run
2022-11-29 15:54:56.040324920 +0100 CET [postgresql-1] self._target(*self._args, **self._kwargs)
2022-11-29 15:54:56.041826290 +0100 CET [postgresql-1] File "/usr/local/lib/python3.9/dist-packages/patroni/api.py", line 848, in shutdown_request
2022-11-29 15:54:56.039751927 +0100 CET [postgresql-1] Traceback (most recent call last):
2022-11-29 15:54:56.042193448 +0100 CET [postgresql-1] File "/usr/lib/python3.9/ssl.py", line 1285, in unwrap
2022-11-29 15:54:56.042738015 +0100 CET [postgresql-1] ConnectionResetError: [Errno 104] Connection reset by peer
2022-11-29 15:54:56.042055651 +0100 CET [postgresql-1] request.unwrap()
2022-11-29 15:54:56.042729763 +0100 CET [postgresql-1] s = self._sslobj.shutdown()
```

Note: all nodes are showing those error logs alternatively

**To Reproduce**
Steps to reproduce the behavior: nothing specific to do, we just installed Patroni 2.1.5 in our docker images and those exceptions spawned

**Environment**
- Patroni version: 2.1.5
- PostgreSQL version: 14.6
- DCS (and its version): ETCD v3.3.15

**Comment by Soulou** [comment]
With 2.1.4 it's completely silent?

It seems to come from an incoming connection on the API which is reseted, it looks like a heatbeat or something, (Link ? Appsdeck database ?)

**Comment by CyberDem0n** [comment]
@aurelien-reeves-scalingo please describe in a bit more details your setup.
Do you by any chance use HAProxy? Can you share its config?

**Comment by aurelien-reeves-scalingo** [comment]
Yes, we are using HAProxy.

I'll try to setup a minimal reproducible example

**Comment by aurelien-reeves-scalingo** [comment]
Here's our HAProxy config:

```
global
    tune.ssl.default-dh-param 2048

defaults
    retries 2
    timeout connect 5s
    timeout client 1d
    timeout server 30m
    timeout check 5s
    timeout tunnel 1d
    timeout client-fin 5m

frontend default
    bind "*:${HAPROXY_PORT}"
    mode tcp

    use_backend cluster

frontend stats
    bind "*:${HAPROXY_STATS_PORT}" ssl crt "${TLS_CERTS_DIR}/haproxy.pem"
    mode http
    stats enable
    stats uri /

    acl auth_ok http_auth(admin_users)
    stats http-request allow if auth_ok
    stats http-request auth realm Stats

userlist admin_users
    user admin insecure-password **********

backend cluster
    mode tcp
    option tcplog

    option httpchk OPTIONS /
    http-check expect status 200

    default-server inter 6s fastinter 3s fall 6 rise 2 on-marked-down shutdown-sessions

    server 6387278a7c7bff0a7fce26a9 10.255.0.3:5432 check check-ssl port 8008 verify required ca-file /etc/ssl/databases/ca.pem

    server 6387279d7c7bff0a7fce26ad 10.255.0.5:5432 check check-ssl port 8008 verify required ca-file /etc/ssl/databases/ca.pem

```

**Comment by aurelien-reeves-scalingo** [comment]
Thanks a lot :+1:
