### ISSUE TITLE
Exception happened during processing of request from HAProxy, which causes terminating all application connections

### ISSUE THREAD

**Issue by corama** [zalando/patroni#2478]
There is a Patroni cluster, which ofter triggers detection failure. The phenomenon is: all connections to the primary will be terminated, including secondary's. New connections to the cluster will be failed.

According to the link: https://github.com/zalando/patroni/issues/331 , I update the config of HAProxy, but not work.

Patroni version: 2.1.2
HA-Proxy version: 1.8.30-c248dab
etcd version: 3.3.11
Python  version: 2.7.5 

And the HAProxy config 
```
listen pgsql_app_monitor
    bind 0.0.0.0:3402
    mode tcp
    option httpchk OPTIONS /
    http-check expect status 200
    default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions
    server postgresql_172.16.59.225_5412 172.16.59.225:5412 maxconn 1000 check port 8008
    server postgresql_172.16.59.224_5412 172.16.59.224:5412 maxconn 1000 check port 8008
```

Patroni logs:
```
2022-11-27 23:02:58,667 WARNING: Exception happened during processing of request from 172.16.59.25:15473
2022-11-27 23:02:58,668 WARNING: Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib64/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

2022-11-27 23:02:58,669 WARNING: Exception happened during processing of request from 172.16.59.26:21655
2022-11-27 23:02:58,669 WARNING: Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib64/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

2022-11-27 23:02:58,670 WARNING: Exception happened during processing of request from 172.16.59.25:15479
2022-11-27 23:02:58,670 WARNING: Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib64/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

2022-11-27 23:02:58,670 WARNING: Exception happened during processing of request from 172.16.59.26:21657
2022-11-27 23:02:58,671 WARNING: Exception happened during processing of request from 172.16.59.25:15477
```

Any suggestions here?

**Comment by CyberDem0n** [comment]
I am afraid you will have to debug it on your own.
This is not a problem on the Patroni side.

**Comment by corama** [comment]
OK, thanks for your advices.
