### ISSUE TITLE
patronictl is broken on v2.1.6

### ISSUE THREAD

**Issue by walbertus** [zalando/patroni#2508]
**Describe the bug**
patronictl is unusable

**To Reproduce**
do any patronictl command
(e.g) patronictl version

**Expected behavior**
patronictl should be able to run commands.

**Screenshots**
```sh
patronictl version
Traceback (most recent call last):
  File "/usr/local/bin/patronictl", line 11, in <module>
    sys.exit(ctl())
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
TypeError: ctl() got an unexpected keyword argument 'dcs'
```

**Comment by CyberDem0n** [comment]
Works for me when freshly installed:
```
root@8b55d4f79973:/# patronictl version
patronictl version 2.1.6
```

**Comment by walbertus** [comment]
it doesn't work on me, installed using pip with this [ansible role](https://github.com/kostiantyn-nemchenko/ansible-role-patroni).

It works fine once I set the version to 2.1.5

**Comment by CyberDem0n** [comment]
> installed using pip with this ansible role

We can't be responsible for 3rd-party solutions.

Once again, it works like a charm:
```
root@d3c186d3f2a7:/# pip3 install patroni==2.1.6
Collecting patroni==2.1.6
  Using cached patroni-2.1.6-py3-none-any.whl (200 kB)
Requirement already satisfied: urllib3!=1.21,>=1.19.1 in /usr/lib/python3/dist-packages (from patroni==2.1.6) (1.26.5)
Requirement already satisfied: click>=4.1 in /usr/lib/python3/dist-packages (from patroni==2.1.6) (7.1.2)
Requirement already satisfied: python-dateutil in /usr/lib/python3/dist-packages (from patroni==2.1.6) (2.8.1)
Requirement already satisfied: prettytable>=0.7 in /usr/lib/python3/dist-packages (from patroni==2.1.6) (0.7.2)
Requirement already satisfied: six>=1.7 in /usr/lib/python3/dist-packages (from patroni==2.1.6) (1.16.0)
Requirement already satisfied: PyYAML in /usr/lib/python3/dist-packages (from patroni==2.1.6) (5.3.1)
Requirement already satisfied: psutil>=2.0.0 in /usr/lib/python3/dist-packages (from patroni==2.1.6) (5.8.0)
Requirement already satisfied: ydiff>=1.2.0 in /usr/local/lib/python3.9/dist-packages (from patroni==2.1.6) (1.2)
Installing collected packages: patroni
Successfully installed patroni-2.1.6
root@d3c186d3f2a7:/# patronictl version
patronictl version 2.1.6
```
