### ISSUE TITLE
Warning Exception happened during processing of request from 172.20.1.127:53282

### ISSUE THREAD

**Issue by psxReboot** [zalando/patroni#2530]
**Describe the bug**
Hello. I create Patroni cluster now I only test him and seems it work fine. But in Patroni log each 20 second i see
warning
```
2023-01-18 09:59:43,475 WARNING: Exception happened during processing of request from 172.20.1.129:56944
2023-01-18 09:59:43,475 WARNING: Traceback (most recent call last):
  File "/usr/lib/python3.9/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.9/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.9/dist-packages/patroni/api.py", line 657, in handle_one_request
    BaseHTTPRequestHandler.handle_one_request(self)
  File "/usr/lib/python3.9/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/local/lib/python3.9/dist-packages/patroni/api.py", line 183, in do_GET
    self._write_status_response(status_code, response)
  File "/usr/local/lib/python3.9/dist-packages/patroni/api.py", line 94, in _write_status_response
    self._write_json_response(status_code, response)
  File "/usr/local/lib/python3.9/dist-packages/patroni/api.py", line 53, in _write_json_response
    self._write_response(status_code, json.dumps(response, default=str), content_type='application/json')
  File "/usr/local/lib/python3.9/dist-packages/patroni/api.py", line 50, in _write_response
    self.wfile.write(body.encode('utf-8'))
  File "/usr/lib/python3.9/socketserver.py", line 799, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
```

The cluster is almost never used, so there are no problems with resources. There is no failover in history for a month, and when I stop manually one of the nodes its successfully change leader.

Can anyone explain me what's happening? 

**Environment**
-   Patroni version: patroni 2.1.4
-   PostgreSQL version: 14.6
-   DCS (and its version):  etcd Version: 3.3.25

**Patroni configuration file**

Please copy&paste your Patroni configuration file here
```
scope: pg-ha-cluster
name: pp_pg_2

log:
  level: WARNING
  format: '%(asctime)s %(levelname)s: %(message)s'
  dateformat: ''
  max_queue_size: 1000
  dir: /var/log/postgresql
  file_num: 4
  file_size: 25000000
  loggers:
    postgres.postmaster: WARNING
    urllib3: DEBUG

restapi:
  listen: 0.0.0.0:8008
  connect_address: 172.20.1.130:8008

etcd:
  hosts: 
  - 172.20.1.129:2379
  - 172.20.1.130:2379
  - 172.20.1.131:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 0
    synchronous_mode: true
    synchronous_mode_strict: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 200
        shared_buffers: 2GB
        effective_cache_size: 6GB
        maintenance_work_mem: 512MB
        checkpoint_completion_target: 0.7
        wal_buffers: 16MB
        default_statistics_target: 100
        random_page_cost: 1.1
        effective_io_concurrency: 200
        work_mem: 2621kB
        min_wal_size: 1GB
        max_wal_size: 4GB
        max_worker_processes: 40
        max_parallel_workers_per_gather: 4
        max_parallel_workers: 40
        max_parallel_maintenance_workers: 4
        max_locks_per_transaction: 64
        max_prepared_transactions: 0
        wal_level: replica
        wal_log_hints: on
        track_commit_timestamp: off
        max_wal_senders: 10
        max_replication_slots: 10
        wal_keep_segments: 8
        logging_collector: on
        log_destination: csvlog
        log_directory: pg_log
        log_min_messages: warning
        log_min_error_statement: error
        log_min_duration_statement: 1000
        log_duration: off
        log_statement: all

  initdb:
  - encoding: UTF8
  - data-checksums
  pg_hba:
  - host all postgres all md5
  - host replication repl all md5

  users:
    postgres:
      password: mypassword
      options:
        - createrole
        - createdb
    repl:
      password: mypassword
      options:
        - replication

postgresql:
  listen: 0.0.0.0:5432
  connect_address: 172.20.1.130:5432
  data_dir: /var/lib/postgresql/15/main
  bin_dir: /usr/lib/postgresql/15/bin
  config_dir: /var/lib/postgresql/15/main
  pgpass: /var/lib/postgresql/.pgpass
  pg_hba:
    - local all all trust
    - host all postgres all md5
    - host replication repl all md5
  authentication:
    replication:
      username: repl
      password: mypassword
    superuser:
      username: postgres
      password: mypassword
  parameters:
    archive_mode: on
    archive_command: /usr/local/bin/copy_wal.sh %p %f
    archive_timeout: 600
    unix_socket_directories: '/var/run/postgresql'
    port: 5432
```

**patronictl show-config**
```
Please copy&paste the output of "patronictl show-config" command here
loop_wait: 30
maximum_lag_on_failover: 0
postgresql:
  parameters:
    checkpoint_completion_target: 0.7
    default_statistics_target: 100
    effective_cache_size: 6GB
    effective_io_concurrency: 200
    log_destination: csvlog
    log_directory: pg_log
    log_duration: false
    log_min_duration_statement: 1000
    log_min_error_statement: error
    log_min_messages: warning
    log_statement: all
    logging_collector: true
    maintenance_work_mem: 1024MB
    max_connections: 201
    max_locks_per_transaction: 64
    max_parallel_maintenance_workers: 4
    max_parallel_workers: 40
    max_parallel_workers_per_gather: 4
    max_prepared_transactions: 0
    max_replication_slots: 10
    max_wal_senders: 10
    max_wal_size: 4GB
    max_worker_processes: 40
    min_wal_size: 1GB
    random_page_cost: 1.1
    shared_buffers: 2GB
    track_commit_timestamp: false
    wal_buffers: 16MB
    wal_keep_segments: 8
    wal_level: replica
    wal_log_hints: true
    work_mem: 2621kB
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: false
synchronous_mode_strict: false
ttl: 60

**Comment by CyberDem0n** [comment]
> ConnectionResetError: [Errno 104] Connection reset by peer

The issue template explicitly asking you to us GH issue search.
If you had done that, most likely you would find that this is a behavior of HAProxy.

**Comment by psxReboot** [comment]
Thanks for the help. What worked for me was changing GET to OPTIONS in the HAProxy config.
