### ISSUE TITLE
After switchover/failover, replicas are in stopped state.

### ISSUE THREAD

**Issue by oxycash** [zalando/patroni#2566]
**Describe the bug**
We have a 3 node setup and when we test switchover/failover, a new leader gets elected but replicas endup in stopped state.

As shown below, pgnode1 WAS Leader, and after running switchover, new Leader is pgnode2. pgnode1&3 enters stopped state then pgnode3 recovers but pgnode1 wont start.

![image](https://user-images.githubusercontent.com/1578779/220673071-765b9c0e-a21c-4d8e-b89f-b9cf4c9f7e9d.png)
![image](https://user-images.githubusercontent.com/1578779/220673765-15b5acf3-f3ee-4183-9c14-3cbf5e5d8de0.png)

**To Reproduce**
patronictl -c config.yml switchover pg_cluster

**Expected behavior**
New replicas should auto start and follow new Leader, but some replicas enter stopped state. Requiring manual server start and pause/resume patroni cluster to recover.

**Screenshots**
![image](https://user-images.githubusercontent.com/1578779/220674499-ffb5f9f0-c0f6-462d-a628-a7792843f353.png)

![image](https://user-images.githubusercontent.com/1578779/220680977-4bee893a-0cf3-4768-bc30-24e09a342173.png)

**Environment**
-   Patroni version: patronictl version 3.0.0
-   PostgreSQL version: 12.13
-   DCS (and its version): Consul 1.14.4

**Patroni configuration file**
```
---

scope: postgres_cluster
name: pgnode1
namespace: /service/


restapi:
  listen: 10.50.139.125:8008
  connect_address: 10.50.139.125:8008
#  certfile: /etc/ssl/certs/ssl-cert.pem
#  keyfile: /etc/ssl/private/ssl-cert.key
#  authentication:
#    username: username
#    password: password

log:
  level: DEBUG
  dir: /home/postgres/patronilogs


consul:
  host: 127.0.0.1:8500
  checks: []
  register_service: true

bootstrap:
  method: initdb
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    synchronous_mode_strict: false
    synchronous_node_count: 1
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 500
        superuser_reserved_connections: 5
        password_encryption: md5
        max_locks_per_transaction: 64
        max_prepared_transactions: 0
        huge_pages: try
        shared_buffers: 512MB
        work_mem: 128MB
        maintenance_work_mem: 256MB
#        effective_cache_size: 4GB
        checkpoint_timeout: 15min
        checkpoint_completion_target: 0.9
        min_wal_size: 2GB
#        max_wal_size: 8GB
        wal_buffers: 32MB
        default_statistics_target: 1000
        seq_page_cost: 1
        random_page_cost: 4
        effective_io_concurrency: 2
        synchronous_commit: on
        autovacuum: on
        autovacuum_max_workers: 5
        autovacuum_vacuum_scale_factor: 0.01
        autovacuum_analyze_scale_factor: 0.01
        autovacuum_vacuum_cost_limit: 500
        autovacuum_vacuum_cost_delay: 2
        autovacuum_naptime: 1s
        max_files_per_process: 4096
        archive_mode: on
        archive_timeout: 1800s
        archive_command: cd .
        wal_level: replica
        #wal_keep_size: 2GB
        max_wal_senders: 10
        max_replication_slots: 10
        hot_standby: on
        wal_log_hints: on
        wal_compression: on
        #shared_preload_libraries: pg_stat_statements,auto_explain
        pg_stat_statements.max: 10000
        pg_stat_statements.track: all
        pg_stat_statements.track_utility: false
        pg_stat_statements.save: true
        auto_explain.log_min_duration: 10s
        auto_explain.log_analyze: true
        auto_explain.log_buffers: true
        auto_explain.log_timing: false
        auto_explain.log_triggers: true
        auto_explain.log_verbose: true
        auto_explain.log_nested_statements: true
        auto_explain.sample_rate: 0.01
        track_io_timing: on
        log_lock_waits: on
        log_temp_files: 0
        track_activities: on
        track_counts: on
        track_functions: all
        log_checkpoints: on
        logging_collector: on
        log_truncate_on_rotation: on
        log_rotation_age: 1d
        log_rotation_size: 0
        log_line_prefix: '%t [%p-%l] %r %q%u@%d '
        log_filename: postgresql-%a.log
        log_directory: /home/postgres/postgresql
        hot_standby_feedback: on
        max_standby_streaming_delay: 30s
        wal_receiver_status_interval: 10s
        idle_in_transaction_session_timeout: 10min
        jit: off
        max_worker_processes: 24
        max_parallel_workers: 8
        max_parallel_workers_per_gather: 2
        max_parallel_maintenance_workers: 2

  initdb:  # List options to be passed on to initdb
    - encoding: UTF8
    - locale: en_US.UTF-8
    - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
    - local     all                      postgres                                          trust
    - local     all                      all                                               peer
    - host      replication              replicator               localhost                trust
    - host      replication              replicator               10.50.139.125/32         md5
    - host      replication              replicator               10.50.139.126/32         md5
    - host      replication              replicator               10.50.139.127/32         md5
    - host      replication              replicator               10.50.139.135/32         md5

postgresql:
  listen: 10.50.139.125,127.0.0.1:5432
  connect_address: 10.50.139.125:5432
  use_unix_socket: true
  data_dir: /apps/pgdata/data
  bin_dir: /usr/pgsql-12/bin/
  config_dir: /apps/pgdata/data
  pgpass: /var/lib/postgresql/.pgpass_patroni
  authentication:
    replication:
      username: replicator
      password: replicator-pass
    superuser:
      username: postgres
      password: postgres-pass
#    rewind:  # Has no effect on postgres 10 and lower
#      username: rewind_user
#      password: rewind_password
  parameters:
    unix_socket_directories: /var/run/postgresql
    #stats_temp_directory: /var/lib/pgsql_stats_tmp
  remove_data_directory_on_rewind_failure: false
  remove_data_directory_on_diverged_timelines: false

#  callbacks:
#    on_start:
#    on_stop:
#    on_restart:

#    on_reload:
#    on_role_change:

# create_replica_methods:
#   - basebackup
# basebackup:
#   max-rate: '100M'
#   checkpoint: 'fast'


# watchdog:
  # mode: automatic  # Allowed values: off, automatic, required
  # device: /dev/watchdog  # Path to the watchdog device
  # safety_margin: 5

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false

  # specify a node to replicate from (cascading replication)
#  replicatefrom: (node name)

```

**patronictl show-config**

```
bash-4.2$ /var/lib/pgsql/.local/bin/patronictl -c patroni.yml show-config
2023-02-22 15:51:17,179 - WARNING - Using postgres-cluster as consul service name instead of scope name postgres_cluster
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: cd .
    archive_mode: true
    archive_timeout: 1800s
    auto_explain.log_analyze: true
    auto_explain.log_buffers: true
    auto_explain.log_min_duration: 10s
    auto_explain.log_nested_statements: true
    auto_explain.log_timing: false
    auto_explain.log_triggers: true
    auto_explain.log_verbose: true
    auto_explain.sample_rate: 0.01
    autovacuum: true
    autovacuum_analyze_scale_factor: 0.01
    autovacuum_max_workers: 5
    autovacuum_naptime: 1s
    autovacuum_vacuum_cost_delay: 2
    autovacuum_vacuum_cost_limit: 500
    autovacuum_vacuum_scale_factor: 0.01
    checkpoint_completion_target: 0.9
    checkpoint_timeout: 15min
    default_statistics_target: 1000
    effective_io_concurrency: 2
    hot_standby: true
    hot_standby_feedback: true
    huge_pages: try
    idle_in_transaction_session_timeout: 10min
    jit: false
    log_checkpoints: true
    log_directory: /home/postgres/postgresql
    log_filename: postgresql-%a.log
    log_line_prefix: '%t [%p-%l] %r %q%u@%d '
    log_lock_waits: true
    log_rotation_age: 1d
    log_rotation_size: 0
    log_temp_files: 0
    log_truncate_on_rotation: true
    logging_collector: true
    maintenance_work_mem: 256MB
    max_connections: 500
    max_files_per_process: 4096
    max_locks_per_transaction: 64
    max_parallel_maintenance_workers: 2
    max_parallel_workers: 8
    max_parallel_workers_per_gather: 2
    max_prepared_transactions: 0
    max_replication_slots: 10
    max_standby_streaming_delay: 30s
    max_wal_senders: 10
    max_worker_processes: 24
    min_wal_size: 2GB
    password_encryption: md5
    pg_stat_statements.max: 10000
    pg_stat_statements.save: true
    pg_stat_statements.track: all
    pg_stat_statements.track_utility: false
    random_page_cost: 4
    seq_page_cost: 1
    shared_buffers: 512MB
    superuser_reserved_connections: 5
    synchronous_commit: true
    track_activities: true
    track_counts: true
    track_functions: all
    track_io_timing: true
    wal_buffers: 32MB
    wal_compression: true
    wal_level: replica
    wal_log_hints: true
    wal_receiver_status_interval: 10s
    work_mem: 128MB
  use_pg_rewind: true
use_slots: true
retry_timeout: 10
synchronous_mode: false
synchronous_mode_strict: false
synchronous_node_count: 1
ttl: 30
```

**Have you checked Patroni logs?**

```
2023-02-22 15:35:22,762 INFO: Lock owner: pgnode1; I am pgnode1
2023-02-22 15:35:22,763 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:35:22,763 DEBUG: http://127.0.0.1:8500 "PUT /v1/session/renew/f47ef73e-5d0e-4dec-8ef1-2e987854324c HTTP/1.1" 200 235
2023-02-22 15:35:22,764 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:35:22,768 DEBUG: http://127.0.0.1:8500 "PUT /v1/kv/service/postgres_cluster/status HTTP/1.1" 200 4
2023-02-22 15:35:22,770 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:35:22,770 DEBUG: Resetting dropped connection: 10.50.139.127
2023-02-22 15:35:22,772 DEBUG: http://10.50.139.127:8008 "GET /patroni HTTP/1.1" 200 None
2023-02-22 15:35:22,772 INFO: Got response from pgnode2 http://10.50.139.127:8008/patroni: {"state": "running", "postmaster_start_time": "2023-02-22 15:33:48.988576+00:00", "role": "replica", "server_version": 120013, "xlog": {"received_location": 439177313344, "replayed_location": 439177313344, "replayed_timestamp": "2023-02-22 15:33:49.096115+00:00", "paused": false}, "timeline": 5, "dcs_last_seen": 1677080120, "database_system_identifier": "7201057262736187245", "patroni": {"version": "3.0.0", "scope": "postgres_cluster"}}
2023-02-22 15:35:22,870 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:35:22,876 DEBUG: http://127.0.0.1:8500 "PUT /v1/kv/service/postgres_cluster/members/pgnode1?acquire=f47ef73e-5d0e-4dec-8ef1-2e987854324c HTTP/1.1" 200 4
2023-02-22 15:35:22,876 INFO: manual failover: demoting myself
2023-02-22 15:35:22,876 INFO: Demoting self (graceful)
2023-02-22 15:35:23,762 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:35:23,763 DEBUG: http://127.0.0.1:8500 "GET /v1/kv/service/postgres_cluster/?recurse=1 HTTP/1.1" 200 None
2023-02-22 15:35:23,940 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:35:23,940 DEBUG: Resetting dropped connection: 10.50.139.127
2023-02-22 15:35:23,941 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:35:23,941 DEBUG: Resetting dropped connection: 10.50.139.135
2023-02-22 15:35:23,944 DEBUG: http://10.50.139.127:8008 "GET /patroni HTTP/1.1" 200 None
2023-02-22 15:35:23,944 INFO: Got response from pgnode2 http://10.50.139.127:8008/patroni: {"state": "running", "postmaster_start_time": "2023-02-22 15:33:48.988576+00:00", "role": "replica", "server_version": 120013, "xlog": {"received_location": 439183204352, "replayed_location": 439193960448, "replayed_timestamp": "2023-02-22 15:33:49.096115+00:00", "paused": false}, "timeline": 5, "dcs_last_seen": 1677080120, "database_system_identifier": "7201057262736187245", "patroni": {"version": "3.0.0", "scope": "postgres_cluster"}}
2023-02-22 15:35:23,964 DEBUG: http://10.50.139.135:8008 "GET /patroni HTTP/1.1" 200 None
2023-02-22 15:35:23,964 INFO: Got response from pgnode3 http://10.50.139.135:8008/patroni: {"state": "running", "postmaster_start_time": "2023-02-22 15:33:48.219281+00:00", "role": "replica", "server_version": 120013, "xlog": {"received_location": 439183335424, "replayed_location": 439193960448, "replayed_timestamp": "2023-02-22 15:33:49.096115+00:00", "paused": false}, "timeline": 5, "dcs_last_seen": 1677080119, "database_system_identifier": "7201057262736187245", "patroni": {"version": "3.0.0", "scope": "postgres_cluster"}}
2023-02-22 15:35:24,041 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:35:24,046 DEBUG: http://127.0.0.1:8500 "PUT /v1/kv/service/postgres_cluster/status HTTP/1.1" 200 4
2023-02-22 15:35:24,046 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:35:24,051 DEBUG: http://127.0.0.1:8500 "DELETE /v1/kv/service/postgres_cluster/leader?cas=306039 HTTP/1.1" 200 4
2023-02-22 15:35:24,052 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:35:24,053 DEBUG: http://127.0.0.1:8500 "PUT /v1/session/renew/f47ef73e-5d0e-4dec-8ef1-2e987854324c HTTP/1.1" 200 235
2023-02-22 15:35:24,053 WARNING: Could not register service: unknown role type demoted
2023-02-22 15:35:24,053 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:35:24,059 DEBUG: http://127.0.0.1:8500 "PUT /v1/kv/service/postgres_cluster/members/pgnode1?acquire=f47ef73e-5d0e-4dec-8ef1-2e987854324c HTTP/1.1" 200 4
2023-02-22 15:35:24,059 INFO: Leader key released
2023-02-22 15:35:24,765 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:35:24,766 DEBUG: http://127.0.0.1:8500 "GET /v1/kv/service/postgres_cluster/?recurse=1 HTTP/1.1" 200 None
2023-02-22 15:35:24,767 DEBUG: API thread: 10.50.139.125 - - "POST /switchover HTTP/1.1" 200 - latency: 2115.891 ms
2023-02-22 15:35:26,917 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:35:26,917 DEBUG: http://127.0.0.1:8500 "GET /v1/kv/service/postgres_cluster/?recurse=1 HTTP/1.1" 200 None
2023-02-22 15:35:26,924 INFO: Local timeline=5 lsn=66/42000028
2023-02-22 15:35:26,934 INFO: primary_timeline=6
2023-02-22 15:35:26,935 DEBUG: primary: history=1       66/38000000     no recovery target specified

2       66/3E000000     no recovery target specified

3       66/40000000     no recovery target specified

4       66/41000000     no recovery target specified

5       66/42000000     no recovery target specified

2023-02-22 15:35:26,935 INFO: primary: history=2        66/3E000000     no recovery target specified
3       66/40000000     no recovery target specified
4       66/41000000     no recovery target specified
5       66/42000000     no recovery target specified
2023-02-22 15:35:26,936 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:35:26,937 DEBUG: http://127.0.0.1:8500 "GET /v1/kv/service/postgres_cluster/?recurse=1 HTTP/1.1" 200 None
2023-02-22 15:35:26,938 WARNING: Postgresql is not running.
2023-02-22 15:35:26,938 INFO: Lock owner: pgnode2; I am pgnode1
2023-02-22 15:35:26,942 INFO: pg_controldata:
  pg_control version number: 1201
  Catalog version number: 201909212
  Database system identifier: 7201057262736187245
  Database cluster state: shut down
  pg_control last modified: Wed Feb 22 15:35:22 2023
  Latest checkpoint location: 66/42000028
  Latest checkpoint's REDO location: 66/42000028
  Latest checkpoint's REDO WAL file: 000000050000006600000042
  Latest checkpoint's TimeLineID: 5
  Latest checkpoint's PrevTimeLineID: 5
  Latest checkpoint's full_page_writes: on
  Latest checkpoint's NextXID: 0:1883536
  Latest checkpoint's NextOID: 2662432
  Latest checkpoint's NextMultiXactId: 1
  Latest checkpoint's NextMultiOffset: 0
  Latest checkpoint's oldestXID: 480
  Latest checkpoint's oldestXID's DB: 1
  Latest checkpoint's oldestActiveXID: 0
  Latest checkpoint's oldestMultiXid: 1
  Latest checkpoint's oldestMulti's DB: 1
  Latest checkpoint's oldestCommitTsXid: 0
  Latest checkpoint's newestCommitTsXid: 0
  Time of latest checkpoint: Wed Feb 22 15:35:22 2023
  Fake LSN counter for unlogged rels: 0/3E8
  Minimum recovery ending location: 0/0
  Min recovery ending loc's timeline: 0
  Backup start location: 0/0
  Backup end location: 0/0
  End-of-backup record required: no
  wal_level setting: replica
  wal_log_hints setting: on
  max_connections setting: 500
  max_worker_processes setting: 24
  max_wal_senders setting: 10
  max_prepared_xacts setting: 0
  max_locks_per_xact setting: 64
  track_commit_timestamp setting: off
  Maximum data alignment: 8
  Database block size: 8192
  Blocks per segment of large relation: 131072
  WAL block size: 8192
  Bytes per WAL segment: 16777216
  Maximum length of identifiers: 64
  Maximum columns in an index: 32
  Maximum size of a TOAST chunk: 1996
  Size of a large-object chunk: 2048
  Date/time type storage: 64-bit integers
  Float4 argument passing: by value
  Float8 argument passing: by value
  Data page checksum version: 1
  Mock authentication nonce: b06426817c23f000447bb293d1cfde36fb1ae784e48d49629dab77419cbd3686
2023-02-22 15:35:26,969 INFO: Deregister service postgres_cluster/pgnode1
2023-02-22 15:35:26,970 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:35:26,977 DEBUG: http://127.0.0.1:8500 "PUT /v1/agent/service/deregister/postgres_cluster/pgnode1 HTTP/1.1" 200 0
2023-02-22 15:35:26,978 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:35:26,982 DEBUG: http://127.0.0.1:8500 "PUT /v1/kv/service/postgres_cluster/members/pgnode1?acquire=f47ef73e-5d0e-4dec-8ef1-2e987854324c HTTP/1.1" 200 4
2023-02-22 15:35:26,983 INFO: running pg_rewind from pgnode2
2023-02-22 15:35:27,017 INFO: running pg_rewind from dbname=postgres user=postgres host=10.50.139.127 port=5432 target_session_attrs=read-write
2023-02-22 15:35:36,936 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:35:36,938 DEBUG: http://127.0.0.1:8500 "GET /v1/kv/service/postgres_cluster/?recurse=1 HTTP/1.1" 200 None
2023-02-22 15:35:36,939 INFO: Lock owner: pgnode2; I am pgnode1
2023-02-22 15:35:36,939 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:35:36,940 DEBUG: http://127.0.0.1:8500 "PUT /v1/session/renew/f47ef73e-5d0e-4dec-8ef1-2e987854324c HTTP/1.1" 200 235
2023-02-22 15:35:36,940 INFO: running pg_rewind from pgnode2 in progress
2023-02-22 15:35:46,936 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:35:46,937 DEBUG: http://127.0.0.1:8500 "GET /v1/kv/service/postgres_cluster/?recurse=1 HTTP/1.1" 200 None
2023-02-22 15:35:46,937 INFO: Lock owner: pgnode2; I am pgnode1
2023-02-22 15:35:46,938 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:35:46,938 DEBUG: http://127.0.0.1:8500 "PUT /v1/session/renew/f47ef73e-5d0e-4dec-8ef1-2e987854324c HTTP/1.1" 200 235
2023-02-22 15:35:46,939 INFO: running pg_rewind from pgnode2 in progress
2023-02-22 15:35:56,936 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:35:56,937 DEBUG: http://127.0.0.1:8500 "GET /v1/kv/service/postgres_cluster/?recurse=1 HTTP/1.1" 200 None
2023-02-22 15:35:56,938 INFO: Lock owner: pgnode2; I am pgnode1
2023-02-22 15:35:56,938 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:35:56,938 DEBUG: http://127.0.0.1:8500 "PUT /v1/session/renew/f47ef73e-5d0e-4dec-8ef1-2e987854324c HTTP/1.1" 200 235
2023-02-22 15:35:56,939 INFO: running pg_rewind from pgnode2 in progress
2023-02-22 15:36:06,936 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:36:06,937 DEBUG: http://127.0.0.1:8500 "GET /v1/kv/service/postgres_cluster/?recurse=1 HTTP/1.1" 200 None
2023-02-22 15:36:06,937 INFO: Lock owner: pgnode2; I am pgnode1
2023-02-22 15:36:06,938 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:36:06,938 DEBUG: http://127.0.0.1:8500 "PUT /v1/session/renew/f47ef73e-5d0e-4dec-8ef1-2e987854324c HTTP/1.1" 200 235
2023-02-22 15:36:06,938 INFO: running pg_rewind from pgnode2 in progress
2023-02-22 15:36:16,936 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:36:16,937 DEBUG: http://127.0.0.1:8500 "GET /v1/kv/service/postgres_cluster/?recurse=1 HTTP/1.1" 200 None
2023-02-22 15:36:16,938 INFO: Lock owner: pgnode2; I am pgnode1
2023-02-22 15:36:16,938 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:36:16,939 DEBUG: http://127.0.0.1:8500 "PUT /v1/session/renew/f47ef73e-5d0e-4dec-8ef1-2e987854324c HTTP/1.1" 200 235
2023-02-22 15:36:16,939 INFO: running pg_rewind from pgnode2 in progress
2023-02-22 15:36:22,006 INFO: pg_rewind exit code=0
2023-02-22 15:36:22,006 INFO:  stdout=
2023-02-22 15:36:22,006 INFO:  stderr=pg_rewind: servers diverged at WAL location 66/42000000 on timeline 5
pg_rewind: rewinding from last common checkpoint at 66/4101FC78 on timeline 5
pg_rewind: Done!
.
.
.
2023-02-22 15:36:22,021 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:36:22,022 DEBUG: http://127.0.0.1:8500 "GET /v1/kv/service/postgres_cluster/?recurse=1 HTTP/1.1" 200 None
2023-02-22 15:36:22,023 INFO: Lock owner: pgnode2; I am pgnode1
2023-02-22 15:36:22,023 INFO: Lock owner: pgnode2; I am pgnode1
2023-02-22 15:36:22,024 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-22 15:36:22,024 DEBUG: http://127.0.0.1:8500 "PUT /v1/session/renew/f47ef73e-5d0e-4dec-8ef1-2e987854324c HTTP/1.1" 200 235
2023-02-22 15:36:22,024 INFO: starting as a secondary
2023-02-22 15:36:22,026 INFO: closed patroni connection to the postgresql cluster
2023-02-22 15:36:22,036 DEBUG: Starting postgres: /usr/pgsql-12/bin/postgres -D /apps/pgdata/data --config-file=/apps/pgdata/data/postgresql.conf --listen_addresses=10.50.139.125,127.0.0.1 --port=5432 --cluster_name=postgres_cluster --wal_level=replica --hot_standby=on --max_connections=500 --max_wal_senders=10 --max_prepared_transactions=0 --max_locks_per_transaction=64 --track_commit_timestamp=off --max_replication_slots=10 --max_worker_processes=24 --wal_log_hints=on
2023-02-22 15:36:22,037 ERROR: Exception during execution of long running task restarting after failure
Traceback (most recent call last):
  File "/var/lib/pgsql/.local/lib/python3.6/site-packages/patroni/async_executor.py", line 97, in run
    wakeup = func(*args) if args else func()
  File "/var/lib/pgsql/.local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 957, in follow
    ret = self.start(timeout=timeout, block_callbacks=change_role, role=role) or None
  File "/var/lib/pgsql/.local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 612, in start
    options)
  File "/var/lib/pgsql/.local/lib/python3.6/site-packages/patroni/postgresql/postmaster.py", line 240, in start
    proc.start()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib64/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 17, in __init__
    util._flush_std_streams()
  File "/usr/lib64/python3.6/multiprocessing/util.py", line 401, in _flush_std_streams
    sys.stderr.flush()
OSError: [Errno 5] Input/output error

```

**Have you checked PostgreSQL logs?**
```
2023-02-22 15:32:50 GMT [23241-6]  LOG:  checkpoint complete: wrote 0 buffers (0.0%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.002 s, sync=0.001 s, total=0.017 s; sync files=0, longest=0.000 s, average=0.000 s; distance=16254 kB, estimate=16487 kB
2023-02-22 15:35:22 GMT [23241-7]  LOG:  checkpoint starting: immediate force wait
2023-02-22 15:35:22 GMT [23241-8]  LOG:  checkpoint complete: wrote 49 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.003 s, sync=0.004 s, total=0.022 s; sync files=25, longest=0.004 s, average=0.001 s; distance=126 kB, estimate=14851 kB
2023-02-22 15:35:22 GMT [23236-11]  LOG:  received fast shutdown request
2023-02-22 15:35:22 GMT [23236-12]  LOG:  aborting any active transactions
2023-02-22 15:35:22 GMT [23430-1] [local] postgres@postgres FATAL:  terminating connection due to administrator command
2023-02-22 15:35:22 GMT [23236-13]  LOG:  background worker "logical replication launcher" (PID 4742) exited with exit code 1
2023-02-22 15:35:22 GMT [23241-9]  LOG:  shutting down
2023-02-22 15:35:22 GMT [23241-10]  LOG:  checkpoint starting: shutdown immediate
2023-02-22 15:35:23 GMT [23241-11]  LOG:  checkpoint complete: wrote 0 buffers (0.0%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.001 s, sync=0.001 s, total=0.022 s; sync files=0, longest=0.000 s, average=0.000 s; distance=16256 kB, estimate=16256 kB
2023-02-22 15:35:24 GMT [23236-14]  LOG:  database system is shut down
```

**Have you tried to use GitHub issue search?**
yes but no specific issue like above

**Additional context**

**Comment by oxycash** [comment]
# Is the pg server/process expected to restart during failover/switchover?
# Which file/folder could be causing this IO error? pg.conf?

**Comment by CyberDem0n** [comment]
The IO error isn't related to the  filesystem.
Python fails to start a new subprocess because for some reason stderr is closed.
I wonder how originally it even managed to start postgreses, because it uses exactly the same code.

There's something weird with your setup or Python.

**Comment by oxycash** [comment]
Can you answer my other question as well? Does switchover/failover process include restarting the pg service?

**Comment by CyberDem0n** [comment]
What do you mean by pg service?
The only service you should use is patroni!

**Comment by oxycash** [comment]
Well, the switchover  process seems to restart the postgresql-12.service and the issue is where the service is unable to start. Is patroni expected to restart the service? If not, what do you think is stopping the postgres-12.service in first place?

```
2023-02-23 06:20:32,851 INFO: starting as a secondary
2023-02-23 06:20:32,862 DEBUG: Starting postgres: /usr/pgsql-12/bin/postgres -D /apps/pgdata/data --config-file=/apps/pgdata/data/postgresql.conf --listen_addresses=10.50.139.125,127.0.0.1 --port=5432 --cluster_name=postgres_cluster --wal_level=replica --hot_standby=on --max_connections=500 --max_wal_senders=10 --max_prepared_transactions=0 --max_locks_per_transaction=64 --track_commit_timestamp=off --max_replication_slots=10 --max_worker_processes=24 --wal_log_hints=on
2023-02-23 06:20:32,862 ERROR: Exception during execution of long running task restarting after failure
Traceback (most recent call last):
  File "/var/lib/pgsql/.local/lib/python3.6/site-packages/patroni/async_executor.py", line 97, in run
    wakeup = func(*args) if args else func()
  File "/var/lib/pgsql/.local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 957, in follow
    ret = self.start(timeout=timeout, block_callbacks=change_role, role=role) or None
  File "/var/lib/pgsql/.local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 612, in start
    options)
  File "/var/lib/pgsql/.local/lib/python3.6/site-packages/patroni/postgresql/postmaster.py", line 240, in start
    proc.start()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib64/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 17, in __init__
    util._flush_std_streams()
  File "/usr/lib64/python3.6/multiprocessing/util.py", line 401, in _flush_std_streams
    sys.stderr.flush()
OSError: [Errno 5] Input/output error
2023-02-23 06:20:32,863 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-23 06:20:32,864 DEBUG: http://127.0.0.1:8500 "GET /v1/kv/service/postgres_cluster/?recurse=1 HTTP/1.1" 200 None
2023-02-23 06:20:32,876 INFO: Lock owner: pgnode3; I am pgnode1
2023-02-23 06:20:32,877 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-02-23 06:20:32,878 DEBUG: http://127.0.0.1:8500 "PUT /v1/session/renew/f47ef73e-5d0e-4dec-8ef1-2e987854324c HTTP/1.1" 200 235
2023-02-23 06:20:32,878 INFO: failed to start postgres

```

**Comment by CyberDem0n** [comment]
Patroni doesn't have enough permissions to work with other services. 
It stops/starts postgres on it's own.
As I already said, the only service you should use - patroni.
