### ISSUE TITLE
Arguments for initdb containing spaces require double quoting

### ISSUE THREAD

**Issue by matthbakeredb** [zalando/patroni#2632]
### What happened?

During testing new TDE setup in pg15 we noticed that configuration for initdb is unintuitive. Values which contain spaces appear to require quoting twice. The result if this is not done is a failure to bootstrap the cluster.

### How can we reproduce it (as minimally and precisely as possible)?

Create a patroni configuration with extra arguments to setup TDE. Start patroni fresh install.

### What did you expect to happen?

Postgres initdb key-value arguments passed quoted when in a list of dicts form, where the value is a string with spaces.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 
-   PostgreSQL version: 
-   DCS (and its version): 

### Patroni configuration file

```yaml
initdb:
  - encoding: UTF8
  - data-checksums
  - auth-local: peer
  - auth-host: scram-sha-256
  - data-encryption
  - key-wrap-command: "openssl enc -e -pbkdf2 -out %p -pass pass:trustno1"
  - key-unwrap-command: "openssl enc -d -pbkdf2 -in %p -pass pass:trustno1"
```

### patronictl show-config

```yaml
n/a
```

### Patroni log files

```shell
Apr 04 07:42:27 pgext-patroni1 patroni[26555]: 2023-04-04 07:42:27,101 INFO: trying to bootstrap a new cluster
Apr 04 07:42:27 pgext-patroni1 patroni[26555]: /usr/edb/pge15/bin/initdb: invalid option -- 'e'
Apr 04 07:42:27 pgext-patroni1 patroni[26555]: initdb: hint: Try "initdb --help" for more information.
Apr 04 07:42:27 pgext-patroni1 patroni[26555]: pg_ctl: database system initialization failed
Apr 04 07:42:27 pgext-patroni1 patroni[26555]: 2023-04-04 07:42:27,111 INFO: removing initialize key after failed attempt to bootstrap the cluster
Apr 04 07:42:27 pgext-patroni1 patroni[26555]: Traceback (most recent call last):
Apr 04 07:42:27 pgext-patroni1 patroni[26555]:   File "/usr/bin/patroni", line 11, in <module>
Apr 04 07:42:27 pgext-patroni1 patroni[26555]:     load_entry_point('patroni==3.0.2', 'console_scripts', 'patroni')()
Apr 04 07:42:27 pgext-patroni1 patroni[26555]:   File "/usr/lib/python3.6/site-packages/patroni/__main__.py", line 144, in main
Apr 04 07:42:27 pgext-patroni1 patroni[26555]:     return patroni_main()
Apr 04 07:42:27 pgext-patroni1 patroni[26555]:   File "/usr/lib/python3.6/site-packages/patroni/__main__.py", line 136, in patroni_main
Apr 04 07:42:27 pgext-patroni1 patroni[26555]:     abstract_main(Patroni, schema)
Apr 04 07:42:27 pgext-patroni1 patroni[26555]:   File "/usr/lib/python3.6/site-packages/patroni/daemon.py", line 181, in abstract_main
Apr 04 07:42:27 pgext-patroni1 patroni[26555]:     controller.run()
Apr 04 07:42:27 pgext-patroni1 patroni[26555]:   File "/usr/lib/python3.6/site-packages/patroni/__main__.py", line 106, in run
Apr 04 07:42:27 pgext-patroni1 patroni[26555]:     super(Patroni, self).run()
Apr 04 07:42:27 pgext-patroni1 patroni[26555]:   File "/usr/lib/python3.6/site-packages/patroni/daemon.py", line 126, in run
Apr 04 07:42:27 pgext-patroni1 patroni[26555]:     self._run_cycle()
Apr 04 07:42:27 pgext-patroni1 patroni[26555]:   File "/usr/lib/python3.6/site-packages/patroni/__main__.py", line 109, in _run_cycle
Apr 04 07:42:27 pgext-patroni1 patroni[26555]:     logger.info(self.ha.run_cycle())
Apr 04 07:42:27 pgext-patroni1 patroni[26555]:   File "/usr/lib/python3.6/site-packages/patroni/ha.py", line 1770, in run_cycle
Apr 04 07:42:27 pgext-patroni1 patroni[26555]:     info = self._run_cycle()
Apr 04 07:42:27 pgext-patroni1 patroni[26555]:   File "/usr/lib/python3.6/site-packages/patroni/ha.py", line 1592, in _run_cycle
Apr 04 07:42:27 pgext-patroni1 patroni[26555]:     return self.post_bootstrap()
Apr 04 07:42:27 pgext-patroni1 patroni[26555]:   File "/usr/lib/python3.6/site-packages/patroni/ha.py", line 1483, in post_bootstrap
Apr 04 07:42:27 pgext-patroni1 patroni[26555]:     self.cancel_initialization()
Apr 04 07:42:27 pgext-patroni1 patroni[26555]:   File "/usr/lib/python3.6/site-packages/patroni/ha.py", line 1476, in cancel_initialization
Apr 04 07:42:27 pgext-patroni1 patroni[26555]:     raise PatroniFatalException('Failed to bootstrap cluster')
Apr 04 07:42:27 pgext-patroni1 patroni[26555]: patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster
```

### PostgreSQL log files

```shell
n/a
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

I will submit a PR with a possible fix shortly.

**Comment by CyberDem0n** [comment]
Solved in #2633
