### ISSUE TITLE
Switchover failed after one node rebooted

### ISSUE THREAD

**Issue by carcuevas** [zalando/patroni#2744]
### What happened?

Basically,

One of the standby server rebooted and after "catching up" with the master in Lag and TL I tried to do a `switchover` using `patronictl` command but it will not do the switchover instead it will show:

```
Switchover failed, details: 412, switchover is not possible: no good candidates have been found
```

So the commands executed with the error messages:

First to check the nodes and that everything is ok

```
postgres@maindb2:~$ patronictl -c /etc/patroni/config.yml list
+ Cluster: main -+-------------+---------+---------+----+-----------+
| Member         | Host        | Role    | State   | TL | Lag in MB |
+----------------+-------------+---------+---------+----+-----------+
|        maindb1 | 10.12.0.221 | Leader  | running |  5 |           |
|        maindb2 | 10.12.1.168 | Replica | running |  5 |         0 |
|        maindb3 | 10.12.0.115 | Replica | running |  5 |         0 |
+------------------+-------------+---------+---------+----+---------+
```

Then the actual command

```
postgres@maindb2:~$ patronictl -c /etc/patroni/config.yml switchover --master maindb1  --candidate maindb2
Current cluster topology
+ Cluster: main -+-------------+---------+---------+----+-----------+
| Member         | Host        | Role    | State   | TL | Lag in MB |
+----------------+-------------+---------+---------+----+-----------+
|        maindb1 | 10.12.0.221 | Leader  | running |  5 |           |
|        maindb2 | 10.12.1.168 | Replica | running |  5 |         0 |
|        maindb3 | 10.12.0.115 | Replica | running |  5 |         0 |
+------------------+-------------+---------+---------+----+---------+
When should the switchover take place (e.g. 2023-07-10T16:35 )  [now]:
Are you sure you want to switchover cluster main, demoting current leader maindb1? [y/N]: y
Switchover failed, details: 412, switchover is not possible: no good candidates have been found
```

or trying to force it

```
postgres@maindb2:~$ patronictl -c /etc/patroni/config.yml switchover --master maindb1  --candidate maindb2 --force
Current cluster topology
+ Cluster: main -+-------------+---------+---------+----+-----------+
| Member         | Host        | Role    | State   | TL | Lag in MB |
+----------------+-------------+---------+---------+----+-----------+
|        maindb1 | 10.12.0.221 | Leader  | running |  5 |           |
|        maindb2 | 10.12.1.168 | Replica | running |  5 |         0 |
|        maindb3 | 10.12.0.115 | Replica | running |  5 |         0 |
+------------------+-------------+---------+---------+----+---------+
Switchover failed, details: 412, switchover is not possible: no good candidates have been found
```

### How can we reproduce it (as minimally and precisely as possible)?

Well until now, I have just need to reboot some of the nodes when there are some activity in the Postgresql cluster, after that trying to switchover to the rebooted node won't be possible.

### What did you expect to happen?

After catching up with the Lags and the TL the rebooted server could be switched to be _master_ once more.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.0.3
-   PostgreSQL version: 13.11.1
-   DCS (and its version): 

### Patroni configuration file

```yaml
scope: main
name: maindb2

restapi:
  listen: "10.12.1.168:8008"
  connect_address: "10.12.1.168:8008"


etcd:  
  hosts: "10.12.0.221:2379, 10.12.1.168:2379, 10.12.0.115:2379"
  protocol: http

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout : 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_keep_segments: 100
        hot_standby: "on"
        synchronous_commit: "on"
        synchronous_standby_names: "*"
      pg_hba:
        - local   all             all                                         trust
        - host    replication     replicator            127.0.0.1/32          scram-sha-256
        - host    all             patroni               127.0.0.1/32          scram-sha-256
        - host    all             patroni               10.12.0.0/22          scram-sha-256
        - host    all             rewinder              10.12.0.0/22          scram-sha-256
        - host    replication     replicator            10.12.0.0/22          scram-sha-256

  initdb:
    - encoding: UTF8
    - data-checksums

postgresql:
  listen: "0.0.0.0:5432"
  connect_address: "10.12.1.168:5432"
  data_dir: /var/lib/postgresql/13/main
  bin_dir: /usr/lib/postgresql/13/bin
  config_dir: /etc/postgresql/13/main
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: Blablabla
    rewind:
      username: rewinder
      password: Blebleble
    superuser:
      username: patroni
      password: Bliblibli

watchdog:
  mode: required
  device: /dev/watchdog
  safety_margin: 5
```

### patronictl show-config

```yaml
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    hot_standby: 'on'
    wal_keep_segments: 100
  pg_hba:
  - local   all             all                                         trust
  - host    replication     replicator            127.0.0.1/32          trust
  - host    all             patroni               127.0.0.1/32          scram-sha-256
  - host    replication     replicator            10.12.0.0/22          scram-sha-256
  - host    all             patroni               10.12.0.0/22          scram-sha-256
  - host    all             rewinder              10.12.0.0/22          scram-sha-256
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
ttl: 30
```

### Patroni log files

```shell
2023-07-10 15:34:16,979 INFO: Selected new etcd server http://10.12.1.168:2379
2023-07-10 15:34:16,982 INFO: No PostgreSQL configuration items changed, nothing to reload.
2023-07-10 15:34:16,990 WARNING: Postgresql is not running.
2023-07-10 15:34:16,990 INFO: Lock owner: maindb1; I am maindb2
2023-07-10 15:34:16,990 INFO: pg_controldata:
  pg_control version number: 1300
  Catalog version number: 202007201
  Database system identifier: 7252018315941171472
  Database cluster state: shut down in recovery
  pg_control last modified: Mon Jul 10 15:33:38 2023
  Latest checkpoint location: 5/174669A0
  Latest checkpoint's REDO location: 5/17466968
  Latest checkpoint's REDO WAL file: 000000050000000500000017
  Latest checkpoint's TimeLineID: 5
  Latest checkpoint's PrevTimeLineID: 5
  Latest checkpoint's full_page_writes: on
  Latest checkpoint's NextXID: 0:588
  Latest checkpoint's NextOID: 16900
  Latest checkpoint's NextMultiXactId: 1
  Latest checkpoint's NextMultiOffset: 0
  Latest checkpoint's oldestXID: 478
  Latest checkpoint's oldestXID's DB: 1
  Latest checkpoint's oldestActiveXID: 588
  Latest checkpoint's oldestMultiXid: 1
  Latest checkpoint's oldestMulti's DB: 1
  Latest checkpoint's oldestCommitTsXid: 0
  Latest checkpoint's newestCommitTsXid: 0
  Time of latest checkpoint: Mon Jul 10 14:11:29 2023
  Fake LSN counter for unlogged rels: 0/3E8
  Minimum recovery ending location: 5/17466A50
  Min recovery ending loc's timeline: 5
  Backup start location: 0/0
  Backup end location: 0/0
  End-of-backup record required: no
  wal_level setting: replica
  wal_log_hints setting: on
  max_connections setting: 100
  max_worker_processes setting: 8
  max_wal_senders setting: 10
  max_prepared_xacts setting: 0
  max_locks_per_xact setting: 64
  track_commit_timestamp setting: off
  Maximum data alignment: 8
  Database block size: 8192
  Blocks per segment of large relation: 131072
  WAL block size: 8192
  Bytes per WAL segment: 16777216
  Maximum length of identifiers: 64
  Maximum columns in an index: 32
  Maximum size of a TOAST chunk: 1996
  Size of a large-object chunk: 2048
  Date/time type storage: 64-bit integers
  Float8 argument passing: by value
  Data page checksum version: 0
  Mock authentication nonce: d06214742f2b7af330312995597625bcb5973a994dcdb5ede6b2df099e1e1aee

2023-07-10 15:34:16,991 INFO: Lock owner: maindb1; I am maindb2
2023-07-10 15:34:16,995 INFO: Local timeline=5 lsn=5/17466A50
2023-07-10 15:34:17,031 INFO: primary_timeline=5
2023-07-10 15:34:17,031 INFO: Lock owner: maindb1; I am maindb2
2023-07-10 15:34:17,036 INFO: starting as a secondary
2023-07-10 15:34:17,354 INFO: postmaster pid=1591
2023-07-10 15:34:18,378 INFO: Lock owner: maindb1; I am maindb2
2023-07-10 15:34:18,378 INFO: establishing a new patroni connection to the postgres cluster
2023-07-10 15:34:18,404 INFO: no action. I am (maindb2), a secondary, and following a leader (maindb1)
2023-07-10 15:34:20,865 INFO: no action. I am (maindb2), a secondary, and following a leader (maindb1)
2023-07-10 15:34:30,865 INFO: no action. I am (maindb2), a secondary, and following a leader (maindb1)
2023-07-10 15:34:40,865 INFO: no action. I am (maindb2), a secondary, and following a leader (maindb1)
2023-07-10 15:34:44,675 INFO: Selected new etcd server http://10.12.0.221:2379
2023-07-10 15:34:44,677 ERROR: Request to server http://10.12.1.168:2379 failed: MaxRetryError("HTTPConnectionPool(host='10.12.1.168', port=2379): Max retries exceeded with url: /v2/keys/service/main/members/maindb2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a85a10070>: Failed to establish a new connection: [Errno 111] Connection refused'))")
2023-07-10 15:34:44,677 INFO: Reconnection allowed, looking for another server.
2023-07-10 15:34:44,677 ERROR:
Traceback (most recent call last):
  File "/var/lib/postgresql/.local/lib/python3.10/site-packages/patroni/daemon.py", line 174, in abstract_main
    controller.run()
  File "/var/lib/postgresql/.local/lib/python3.10/site-packages/patroni/__main__.py", line 113, in run
    super(Patroni, self).run()
  File "/var/lib/postgresql/.local/lib/python3.10/site-packages/patroni/daemon.py", line 143, in run
    self._run_cycle()
  File "/var/lib/postgresql/.local/lib/python3.10/site-packages/patroni/__main__.py", line 125, in _run_cycle
    self.schedule_next_run()
  File "/var/lib/postgresql/.local/lib/python3.10/site-packages/patroni/__main__.py", line 107, in schedule_next_run
    elif self.ha.watch(nap_time):
  File "/var/lib/postgresql/.local/lib/python3.10/site-packages/patroni/ha.py", line 1848, in watch
    return self.dcs.watch(leader_version, timeout)
  File "/var/lib/postgresql/.local/lib/python3.10/site-packages/patroni/dcs/etcd.py", line 842, in watch
    result = self._client.watch(self.leader_path, index=leader_version, timeout=timeout + 0.5)
  File "/usr/lib/python3/dist-packages/etcd/client.py", line 767, in watch
    return self.read(key, wait=True, waitIndex=index, timeout=timeout,
  File "/usr/lib/python3/dist-packages/etcd/client.py", line 595, in read
    response = self.api_execute(
  File "/var/lib/postgresql/.local/lib/python3.10/site-packages/patroni/dcs/etcd.py", line 282, in api_execute
    response = self._do_http_request(retry, machines_cache, request_executor, method, path, **kwargs)
  File "/var/lib/postgresql/.local/lib/python3.10/site-packages/patroni/dcs/etcd.py", line 234, in _do_http_request
    response.data.decode('utf-8')
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 300, in data
    return self.read(cache_content=True)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 515, in read
    data = self._fp.read() if not fp_closed else b""
  File "/usr/lib/python3.10/http/client.py", line 459, in read
    return self._read_chunked(amt)
  File "/usr/lib/python3.10/http/client.py", line 582, in _read_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/lib/python3.10/http/client.py", line 565, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/lib/python3.10/http/client.py", line 525, in _read_next_chunk_size
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/var/lib/postgresql/.local/lib/python3.10/site-packages/patroni/daemon.py", line 90, in sigterm_handler
    sys.exit()
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/var/lib/postgresql/.local/lib/python3.10/site-packages/patroni/dcs/etcd.py", line 604, in create_connection_patched
    raise err
  File "/var/lib/postgresql/.local/lib/python3.10/site-packages/patroni/dcs/etcd.py", line 594, in create_connection_patched
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f3a85a10070>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/postgresql/.local/lib/python3.10/site-packages/patroni/dcs/etcd.py", line 233, in _do_http_request
    response = request_executor(method, base_uri + path, **kwargs)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.12.1.168', port=2379): Max retries exceeded with url: /v2/keys/service/main/members/maindb2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a85a10070>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/postgresql/.local/lib/python3.10/site-packages/patroni/dcs/etcd.py", line 508, in handle_etcd_exceptions
    retval = func(self, *args, **kwargs)
  File "/var/lib/postgresql/.local/lib/python3.10/site-packages/patroni/dcs/etcd.py", line 756, in touch_member
    return bool(self._client.set(self.member_path, value, self._ttl))
  File "/usr/lib/python3/dist-packages/etcd/client.py", line 721, in set
    return self.write(key, value, ttl=ttl)
  File "/usr/lib/python3/dist-packages/etcd/client.py", line 500, in write
    response = self.api_execute(path, method, params=params)
  File "/var/lib/postgresql/.local/lib/python3.10/site-packages/patroni/dcs/etcd.py", line 282, in api_execute
    response = self._do_http_request(retry, machines_cache, request_executor, method, path, **kwargs)
  File "/var/lib/postgresql/.local/lib/python3.10/site-packages/patroni/dcs/etcd.py", line 254, in _do_http_request
    raise etcd.EtcdException('{0} {1} request failed'.format(method, path))
etcd.EtcdException: PUT /v2/keys/service/main/members/maindb2 request failed
2023-07-10 15:35:03,064 INFO: Selected new etcd server http://10.12.0.115:2379
2023-07-10 15:35:03,093 INFO: No PostgreSQL configuration items changed, nothing to reload.
2023-07-10 15:35:03,112 WARNING: Postgresql is not running.
2023-07-10 15:35:03,112 INFO: Lock owner: maindb1; I am maindb2
2023-07-10 15:35:03,120 INFO: pg_controldata:
  pg_control version number: 1300
  Catalog version number: 202007201
  Database system identifier: 7252018315941171472
  Database cluster state: shut down in recovery
  pg_control last modified: Mon Jul 10 15:34:44 2023
  Latest checkpoint location: 5/174669A0
  Latest checkpoint's REDO location: 5/17466968
  Latest checkpoint's REDO WAL file: 000000050000000500000017
  Latest checkpoint's TimeLineID: 5
  Latest checkpoint's PrevTimeLineID: 5
  Latest checkpoint's full_page_writes: on
  Latest checkpoint's NextXID: 0:588
  Latest checkpoint's NextOID: 16900
  Latest checkpoint's NextMultiXactId: 1
  Latest checkpoint's NextMultiOffset: 0
  Latest checkpoint's oldestXID: 478
  Latest checkpoint's oldestXID's DB: 1
  Latest checkpoint's oldestActiveXID: 588
  Latest checkpoint's oldestMultiXid: 1
  Latest checkpoint's oldestMulti's DB: 1
  Latest checkpoint's oldestCommitTsXid: 0
  Latest checkpoint's newestCommitTsXid: 0
  Time of latest checkpoint: Mon Jul 10 14:11:29 2023
  Fake LSN counter for unlogged rels: 0/3E8
  Minimum recovery ending location: 5/17466A50
  Min recovery ending loc's timeline: 5
  Backup start location: 0/0
  Backup end location: 0/0
  End-of-backup record required: no
  wal_level setting: replica
  wal_log_hints setting: on
  max_connections setting: 100
  max_worker_processes setting: 8
  max_wal_senders setting: 10
  max_prepared_xacts setting: 0
  max_locks_per_xact setting: 64
  track_commit_timestamp setting: off
  Maximum data alignment: 8
  Database block size: 8192
  Blocks per segment of large relation: 131072
  WAL block size: 8192
  Bytes per WAL segment: 16777216
  Maximum length of identifiers: 64
  Maximum columns in an index: 32
  Maximum size of a TOAST chunk: 1996
  Size of a large-object chunk: 2048
  Date/time type storage: 64-bit integers
  Float8 argument passing: by value
  Data page checksum version: 0
  Mock authentication nonce: d06214742f2b7af330312995597625bcb5973a994dcdb5ede6b2df099e1e1aee

2023-07-10 15:35:03,124 INFO: Lock owner: maindb1; I am maindb2
2023-07-10 15:35:03,139 INFO: Local timeline=5 lsn=5/17466A50
2023-07-10 15:35:03,258 INFO: primary_timeline=5
2023-07-10 15:35:03,259 INFO: Lock owner: maindb1; I am maindb2
2023-07-10 15:35:03,264 INFO: starting as a secondary
2023-07-10 15:35:04,263 INFO: postmaster pid=819
2023-07-10 15:35:05,316 INFO: Lock owner: maindb1; I am maindb2
2023-07-10 15:35:05,316 INFO: establishing a new patroni connection to the postgres cluster
2023-07-10 15:35:05,406 INFO: no action. I am (maindb2), a secondary, and following a leader (maindb1)
2023-07-10 15:35:10,867 INFO: no action. I am (maindb2), a secondary, and following a leader (maindb1)
2023-07-10 15:35:20,865 INFO: no action. I am (maindb2), a secondary, and following a leader (maindb1)
2023-07-10 15:35:30,865 INFO: no action. I am (maindb2), a secondary, and following a leader (maindb1)
2023-07-10 15:35:40,865 INFO: no action. I am (maindb2), a secondary, and following a leader (maindb1)
2023-07-10 15:35:50,865 INFO: no action. I am (maindb2), a secondary, and following a leader (maindb1)
2023-07-10 15:36:00,865 INFO: no action. I am (maindb2), a secondary, and following a leader (maindb1)
2023-07-10 15:36:10,865 INFO: no action. I am (maindb2), a secondary, and following a leader (maindb1)
2023-07-10 15:36:20,866 INFO: no action. I am (maindb2), a secondary, and following a leader (maindb1)
2023-07-10 15:36:30,865 INFO: no action. I am (maindb2), a secondary, and following a leader (maindb1)
2023-07-10 15:36:40,865 INFO: no action. I am (maindb2), a secondary, and following a leader (maindb1)
2023-07-10 15:36:50,865 INFO: no action. I am (maindb2), a secondary, and following a leader (maindb1)
2023-07-10 15:37:00,865 INFO: no action. I am (maindb2), a secondary, and following a leader (maindb1)
2023-07-10 15:37:10,864 INFO: no action. I am (maindb2), a secondary, and following a leader (maindb1)
2023-07-10 15:37:20,865 INFO: no action. I am (maindb2), a secondary, and following a leader (maindb1)
2023-07-10 15:37:30,865 INFO: no action. I am (maindb2), a secondary, and following a leader (maindb1)
2023-07-10 15:37:40,865 INFO: no action. I am (maindb2), a secondary, and following a leader (maindb1)
2023-07-10 15:37:50,865 INFO: no action. I am (maindb2), a secondary, and following a leader (maindb1)
2023-07-10 15:38:00,866 INFO: no action. I am (maindb2), a secondary, and following a leader (maindb1)
```

### PostgreSQL log files

```shell
2023-07-10 15:34:17 UTC 1591 LOG:  starting PostgreSQL 13.11 (Ubuntu 13.11-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, 64-bit
2023-07-10 15:34:17 UTC 1591 LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-07-10 15:34:17 UTC 1591 LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-07-10 15:34:17 UTC 1594 LOG:  database system was shut down in recovery at 2023-07-10 15:33:38 UTC
2023-07-10 15:34:17 UTC 1594 LOG:  entering standby mode
2023-07-10 15:34:17 UTC 1594 LOG:  redo starts at 5/17466968
2023-07-10 15:34:17 UTC 1594 LOG:  consistent recovery state reached at 5/17466A50
2023-07-10 15:34:17 UTC 1594 LOG:  invalid record length at 5/17466A50: wanted 24, got 0
2023-07-10 15:34:17 UTC 1591 LOG:  database system is ready to accept read only connections
2023-07-10 15:34:17 UTC 1598 FATAL:  could not start WAL streaming: ERROR:  replication slot "maindb2" does not exist
2023-07-10 15:34:17 UTC 1599 FATAL:  could not start WAL streaming: ERROR:  replication slot "maindb2" does not exist
2023-07-10 15:34:22 UTC 1607 LOG:  started streaming WAL from primary at 5/17000000 on timeline 5
2023-07-10 15:34:44 UTC 1591 LOG:  received fast shutdown request
2023-07-10 15:34:44 UTC 1591 LOG:  aborting any active transactions
2023-07-10 15:34:44 UTC 1605 FATAL:  terminating connection due to administrator command
2023-07-10 15:34:44 UTC 1607 FATAL:  terminating walreceiver process due to administrator command
2023-07-10 15:34:44 UTC 1595 LOG:  shutting down
2023-07-10 15:34:44 UTC 1591 LOG:  database system is shut down
2023-07-10 15:35:04 UTC 819 LOG:  starting PostgreSQL 13.11 (Ubuntu 13.11-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, 64-bit
2023-07-10 15:35:04 UTC 819 LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-07-10 15:35:04 UTC 819 LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-07-10 15:35:04 UTC 823 LOG:  database system was shut down in recovery at 2023-07-10 15:34:44 UTC
2023-07-10 15:35:04 UTC 823 LOG:  entering standby mode
2023-07-10 15:35:04 UTC 823 LOG:  redo starts at 5/17466968
2023-07-10 15:35:04 UTC 823 LOG:  consistent recovery state reached at 5/17466A50
2023-07-10 15:35:04 UTC 823 LOG:  invalid record length at 5/17466A50: wanted 24, got 0
2023-07-10 15:35:04 UTC 819 LOG:  database system is ready to accept read only connections
2023-07-10 15:35:04 UTC 827 LOG:  started streaming WAL from primary at 5/17000000 on timeline 5
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

Patroni History:

```
postgres@maindb1:~/13/main$ patronictl -c /etc/patroni/config.yml history
+----+-------------+------------------------------+----------------------------------+------------+
| TL |         LSN | Reason                       | Timestamp                        | New Leader |
+----+-------------+------------------------------+----------------------------------+------------+
|  1 |   436208008 | no recovery target specified | 2023-07-10T13:45:45.937977+00:00 |    maindb3 |
|  2 |   436208640 | no recovery target specified | 2023-07-10T13:46:38.115721+00:00 |    maindb1 |
|  3 | 21865326328 | no recovery target specified | 2023-07-10T14:10:42.507150+00:00 |    maindb3 |
|  4 | 21865326904 | no recovery target specified | 2023-07-10T14:11:29.867258+00:00 |    maindb1 |
+----+-------------+------------------------------+----------------------------------+------------+

```

**Comment by CyberDem0n** [comment]
What is in Patroni on maindb1? Before demoting it is trying to access maindb2 via REST API. If it can't verify that maindb2 is healthy the switchover will not work.

**Comment by CyberDem0n** [comment]
Configuration requires watchdog, but it can't be used (watchdog_failed: true), therefore this node can't be the leader.

**Comment by carcuevas** [comment]
holly cow!   I had the `softdog` module in `/etc/modules` but for some reason it did not start it..  (no blacklisted in the `/etc/modprobe.d` )...  Maybe the device it's not created before the module starts... 🤔 
Also somehow I had included `softdog` in the `/etc/modules` but for some reason it's not working... 🤔  not I realized that in the `syslog` it's this:

```
jul 10 22:03:12 maindb2 systemd-modules-load[196]: Module 'softdog' is deny-listed
Jul 10 22:03:12 maindb2 systemd-modules-load[196]: Module 'softdog' is deny-listed

```
Next time I will check better the logs in the master... `"watchdog_failed": true`  sorry for that...

**Comment by carcuevas** [comment]
btw if needed for future references... I am using Ubuntu 22.04

**Comment by carcuevas** [comment]
Again for future references, for Ubuntu for making the softdog works from the booting I had to do the following:

```
apt install watchdog

```
 add the following line into `/etc/default/watchdog`

 ```
watchdog_module="softdog"
 ```
and ...

```
systemctl start softdog
systemctl enable softdog
```

And with this it will start automatically after each boot...
