### ISSUE TITLE
Patroni times out in 1 millisecond while connecting to zookeeper

### ISSUE THREAD

**Issue by boudey** [zalando/patroni#2751]
### What happened?

patroni goes into a very quick successive loop trying to connect to zookeeper, filling up log file 
```
2023-07-11 18:59:05,029 ERROR: get_cluster
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/zookeeper.py", line 281, in _load_cluster
    cluster = self._client.retry(self._inner_load_cluster)
  File "/usr/local/lib/python3.8/dist-packages/kazoo/client.py", line 347, in _retry
    return self._retry.copy()(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/kazoo/retry.py", line 126, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/zookeeper.py", line 230, in _inner_load_cluster
    nodes = set(self.get_children(self.client_path(''), self.cluster_watcher))
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/zookeeper.py", line 215, in get_children
    return self._client.get_children(key, watch)
  File "/usr/local/lib/python3.8/dist-packages/kazoo/client.py", line 1218, in get_children
    return self.get_children_async(path, watch=watch,
  File "/usr/local/lib/python3.8/dist-packages/kazoo/handlers/utils.py", line 80, in get
    raise self._exception
kazoo.exceptions.ConnectionClosedError: Connection has been closed
2023-07-11 18:59:05,029 ERROR: Error communicating with DCS
2023-07-11 18:59:05,029 INFO: DCS is not accessible
2023-07-11 18:59:05,029 ERROR: get_cluster
2023-07-11 18:59:10,020 ERROR: get_cluster
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/zookeeper.py", line 281, in _load_cluster
    cluster = self._client.retry(self._inner_load_cluster)
  File "/usr/local/lib/python3.8/dist-packages/kazoo/client.py", line 347, in _retry
    return self._retry.copy()(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/kazoo/retry.py", line 126, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/zookeeper.py", line 230, in _inner_load_cluster
    nodes = set(self.get_children(self.client_path(''), self.cluster_watcher))
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/zookeeper.py", line 215, in get_children
    return self._client.get_children(key, watch)
  File "/usr/local/lib/python3.8/dist-packages/kazoo/client.py", line 1218, in get_children
    return self.get_children_async(path, watch=watch,
  File "/usr/local/lib/python3.8/dist-packages/kazoo/handlers/utils.py", line 80, in get
    raise self._exception
kazoo.exceptions.ConnectionClosedError: Connection has been closed
2023-07-11 18:59:10,021 ERROR: Error communicating with DCS
2023-07-11 18:59:10,021 INFO: DCS is not accessible
2023-07-11 18:59:10,021 ERROR: get_cluster
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/zookeeper.py", line 281, in _load_cluster
    cluster = self._client.retry(self._inner_load_cluster)
  File "/usr/local/lib/python3.8/dist-packages/kazoo/client.py", line 347, in _retry
    return self._retry.copy()(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/kazoo/retry.py", line 126, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/zookeeper.py", line 230, in _inner_load_cluster
    nodes = set(self.get_children(self.client_path(''), self.cluster_watcher))
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/zookeeper.py", line 215, in get_children
    return self._client.get_children(key, watch)
  File "/usr/local/lib/python3.8/dist-packages/kazoo/client.py", line 1218, in get_children
    return self.get_children_async(path, watch=watch,
  File "/usr/local/lib/python3.8/dist-packages/kazoo/handlers/utils.py", line 80, in get
    raise self._exception
kazoo.exceptions.ConnectionClosedError: Connection has been closed
2023-07-11 18:59:10,022 ERROR: Error communicating with DCS
2023-07-11 18:59:10,022 INFO: DCS is not accessible
```
Notice the timeout is within 1 millisecond. This is despite `retry_timeout` set to 300. I suspect the kazoo client connection timeout is set to zero but I don't know why.

### How can we reproduce it (as minimally and precisely as possible)?

Unable to find specific circumstances for reproduction

### What did you expect to happen?

Patroni loop to connect to DCS not timing out quickly

### Patroni/PostgreSQL/DCS version

-   Patroni version: 2.1.4 (unable to test with newer patroni because of a different bug)
-   PostgreSQL version: 12.15
-   DCS (and its version): zookeeper 3.8.1

### Patroni configuration file

```yaml
Please see show-config
```

### patronictl show-config

```yaml
2023-07-11 19:23:14,154 - INFO - Connecting to 10.103.42.248(10.103.42.248):2181, use_ssl: False
2023-07-11 19:23:14,394 - INFO - Zookeeper connection established, state: CONNECTED
check_timeline: true
loop_wait: 10
max_timelines_history: 0
maximum_lag_on_failover: 0
postgresql:
  parameters:
    hot_standby: 'on'
    hot_standby_feedback: ''
    max_connections: 600
    max_locks_per_transaction: 25
    max_logical_replication_workers: 10
    max_prepared_transactions: 25
    max_replication_slots: 10
    max_wal_senders: 10
    max_worker_processes: 10
    synchronous_commit: 'on'
    track_commit_timestamp: ''
    wal_keep_segments: 10
    wal_level: hot_standby
    wal_log_hints: 'on'
  remove_data_directory_on_diverged_timelines: true
  remove_data_directory_on_rewind_failure: true
  use_rewind: false
  use_slots: true
retry_timeout: 300
standby_cluster:
  create_replica_method:
  - basebackup
synchronous_mode: true
synchronous_mode_strict: true
synchronous_node_count: 2
ttl: 60
```

### Patroni log files

```shell
2023-07-11 18:59:10,030 ERROR: Error communicating with DCS
2023-07-11 18:59:10,030 INFO: DCS is not accessible
2023-07-11 18:59:10,030 ERROR: get_cluster
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/zookeeper.py", line 281, in _load_cluster
    cluster = self._client.retry(self._inner_load_cluster)
  File "/usr/local/lib/python3.8/dist-packages/kazoo/client.py", line 347, in _retry
    return self._retry.copy()(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/kazoo/retry.py", line 126, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/zookeeper.py", line 230, in _inner_load_cluster
    nodes = set(self.get_children(self.client_path(''), self.cluster_watcher))
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/zookeeper.py", line 215, in get_children
    return self._client.get_children(key, watch)
  File "/usr/local/lib/python3.8/dist-packages/kazoo/client.py", line 1218, in get_children
    return self.get_children_async(path, watch=watch,
  File "/usr/local/lib/python3.8/dist-packages/kazoo/handlers/utils.py", line 80, in get
    raise self._exception
kazoo.exceptions.ConnectionClosedError: Connection has been closed
2023-07-11 18:59:10,031 ERROR: Error communicating with DCS
2023-07-11 18:59:10,032 INFO: DCS is not accessible
2023-07-11 18:59:10,032 ERROR: get_cluster
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/zookeeper.py", line 281, in _load_cluster
    cluster = self._client.retry(self._inner_load_cluster)
  File "/usr/local/lib/python3.8/dist-packages/kazoo/client.py", line 347, in _retry
    return self._retry.copy()(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/kazoo/retry.py", line 126, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/zookeeper.py", line 230, in _inner_load_cluster
    nodes = set(self.get_children(self.client_path(''), self.cluster_watcher))
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/zookeeper.py", line 215, in get_children
    return self._client.get_children(key, watch)
  File "/usr/local/lib/python3.8/dist-packages/kazoo/client.py", line 1218, in get_children
    return self.get_children_async(path, watch=watch,
  File "/usr/local/lib/python3.8/dist-packages/kazoo/handlers/utils.py", line 80, in get
    raise self._exception
kazoo.exceptions.ConnectionClosedError: Connection has been closed
2023-07-11 18:59:10,033 ERROR: Error communicating with DCS
2023-07-11 18:59:10,033 INFO: DCS is not accessible
2023-07-11 18:59:10,033 ERROR: get_cluster
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/zookeeper.py", line 281, in _load_cluster
    cluster = self._client.retry(self._inner_load_cluster)
  File "/usr/local/lib/python3.8/dist-packages/kazoo/client.py", line 347, in _retry
    return self._retry.copy()(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/kazoo/retry.py", line 126, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/zookeeper.py", line 230, in _inner_load_cluster
    nodes = set(self.get_children(self.client_path(''), self.cluster_watcher))
  File "/usr/local/lib/python3.8/dist-packages/patroni/dcs/zookeeper.py", line 215, in get_children
    return self._client.get_children(key, watch)
  File "/usr/local/lib/python3.8/dist-packages/kazoo/client.py", line 1218, in get_children
    return self.get_children_async(path, watch=watch,
  File "/usr/local/lib/python3.8/dist-packages/kazoo/handlers/utils.py", line 80, in get
    raise self._exception
kazoo.exceptions.ConnectionClosedError: Connection has been closed
2023-07-11 18:59:10,034 ERROR: Error communicating with DCS
2023-07-11 18:59:10,034 INFO: DCS is not accessible
2023-07-11 18:59:10,034 ERROR: get_cluster
```

### PostgreSQL log files

```shell
not relevant
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

other nodes in the cluster behaving normally

`patronictl list` and other REST functions behave normally

`dcs_last_seen` obtained from `/health` endpoint does not increase

restarting patroni clears the problem

appreciate your help

**Comment by CyberDem0n** [comment]
> kazoo.exceptions.ConnectionClosedError: Connection has been closed

This error means that connection to Zookeeper node(s) isn't established. Maybe Zookeeper nodes listed in Patroni config are not accessible anymore, but you didn't even show the config.

> loop_wait: 10
retry_timeout: 300
ttl: 60

These values violate the rule `loop_wait + 2*retry_timeout <= ttl`.

Also it seems that you don't understand the meaning of **retry_timeout**.
It describes the maximum time Patroni is allowed to spend executing a _single_ request to DCS.
If the request fails faster Patroni retries.

> restarting patroni clears the problem

Well, Patroni isn't working with Zookeeper on its own, but relying on `kazoo` module. If the Patroni config didn't change before the restart maybe there is something wrong with kazoo, but I am not sure.

> appreciate your help

You need to check Patroni logs and find the moment when it started failing. Maybe there is something interesting. Looking at latest log messages doesn't bring anything.

**Comment by CyberDem0n** [comment]
Or at least it would be nice to know which kazoo version you have.
Maybe you are facing something that was fixed in https://github.com/zalando/patroni/commit/531063f67661a46ef784da5debb755b092e06d36.

**Comment by boudey** [comment]
Ok thanks for the help, closing.
