### ISSUE TITLE
Ambiguous behavior

### ISSUE THREAD

**Issue by glushakov** [zalando/patroni#2779]
### What happened?

Hi.
I have encountered a behavior that I can not understand.

On the host server_2, an out of memory occurred as a result of which the postgres process was killed
`2023-07-26 18:01:37.786 MSK    2307  0 LOG:  server process (PID 1326001) was terminated by signal 9: Killed`

But the switch to the standby (server_1) happened earlier, I think when the master was already overloaded and could not update its leader key.
`2023-07-26 18:00:45,518 INFO: promoted self to leader by acquiring session lock`

But after a successful promotion, an incomprehensible message appears after 1 minute on a new master (server_1)
```
2023-07-26 18:01:37,179 INFO: Lock owner: server_2; I am server_1
2023-07-26 18:01:37,180 INFO: Demoting self (immediate-nolock)
2023-07-26 18:01:37,371 INFO: demoting self because I do not have the lock and I was a leader
```

At the same time, server_2 did not know that the master had been changed and continued to work without changing the role:
```
2023-07-26 17:59:09,144 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 17:59:19,145 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 17:59:29,144 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 17:59:39,145 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 17:59:49,144 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:00:12,385 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:00:12,423 WARNING: Loop time exceeded, rescheduling immediately.
2023-07-26 18:00:14,027 INFO: no action. I am (server_2), the leader with the lock
   <I suppose this moment of high load on the server>
2023-07-26 18:01:36,990 INFO: Lock owner: server_2; I am server_2
2023-07-26 18:01:37,243 INFO: Updating synchronous privilege temporarily from ['server_1'] to []
2023-07-26 18:01:37,303 INFO: Synchronous replication key updated by someone else.
2023-07-26 18:01:37,349 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:01:37,350 WARNING: Loop time exceeded, rescheduling immediately.
2023-07-26 18:01:37,606 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:01:37,695 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:01:47,607 INFO: Lock owner: server_2; I am server_2
2023-07-26 18:01:47,727 INFO: establishing a new patroni connection to the postgres cluster
2023-07-26 18:01:48,007 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:01:57,741 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:02:07,696 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:02:17,695 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:02:27,698 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:02:37,696 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:02:47,699 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:02:57,744 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:03:07,739 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:03:17,696 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:03:27,697 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:03:37,696 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:03:47,696 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:03:57,695 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:04:07,697 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:04:17,741 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:04:27,696 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:04:37,741 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:04:47,740 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:04:57,740 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:05:07,695 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:05:17,740 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:05:27,696 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:05:37,701 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:05:47,695 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:05:57,695 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:06:07,696 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:06:17,696 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:06:27,696 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:06:37,695 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:06:47,607 INFO: Lock owner: server_2; I am server_2
2023-07-26 18:06:47,699 INFO: Assigning synchronous standby status to ['server_1']
2023-07-26 18:06:47,706 INFO: Synchronous replication key updated by someone else
2023-07-26 18:06:47,751 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:06:57,607 INFO: Lock owner: server_2; I am server_2
2023-07-26 18:06:57,696 INFO: Assigning synchronous standby status to ['server_1']
2023-07-26 18:06:57,696 INFO: Synchronous replication key updated by someone else
2023-07-26 18:06:57,741 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:07:07,607 INFO: Lock owner: server_2; I am server_2
2023-07-26 18:07:07,696 INFO: Assigning synchronous standby status to ['server_1']
2023-07-26 18:07:07,696 INFO: Synchronous replication key updated by someone else
2023-07-26 18:07:07,697 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:07:17,607 INFO: Lock owner: server_2; I am server_2
2023-07-26 18:07:17,696 INFO: Assigning synchronous standby status to ['server_1']
2023-07-26 18:07:17,697 INFO: Synchronous replication key updated by someone else
2023-07-26 18:07:17,742 INFO: no action. I am (server_2), the leader with the lock

```
And keeps repeating the last message about "Synchronous replication key updated by someone else"

So, 
1. Why server_1 after receiving the lock, made demote, after received lock at 18:00:45,518
2. Why is there no information about this switchover in the patronictl history?
3. Standby cannot go into synchronous state, the same message (Synchronous replication key updated by someone else)  is repeated. Bug?

### How can we reproduce it (as minimally and precisely as possible)?

Maybe to create a high load on the master node, followed by a call to out of memory. Not sure.

### What did you expect to happen?

1. After changing the master node, it should not return to the role of a replica without good reason
2. synchronous replica should get the status of "sync standby"
3. in the history of switching, the facts of changing roles should be recorded

### Patroni/PostgreSQL/DCS version

-   Patroni version: 14.8
-   PostgreSQL version: 3.0.2
-   DCS (and its version): etcd 3.5.4

### Patroni configuration file

```yaml
scope: server_1+server_2
namespace: /service/
name: server_1

log:
  level: INFO
  format: '%(asctime)s %(levelname)s: %(message)s'
  dateformat: ''
  max_queue_size: 1000
  dir: /var/log/patroni
  file_num: 4
  file_size: 25000000

restapi:
  listen: 0.0.0.0:8008
  connect_address: server_1:8008
  authentication:
    username: patroni_rest
    password: password

etcd3:
  hosts: etcd-cluster:2379
  protocol: http
  username: etcd_username
  password: password

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    primary_start_timeout: 5
    primary_stop_timeout: 30
    synchronous_mode: true
    synchronous_mode_strict: false
    check_timeline: false
    failsafe_mode: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 300
        max_locks_per_transaction: 64
        max_worker_processes: 8
        max_prepared_transactions: 0
        wal_level: replica
        wal_log_hints: on
        track_commit_timestamp: off
        max_wal_senders: 10
        max_replication_slots: 10
        wal_keep_size: 2GB

postgresql:
  use_unix_socket: true
  listen: 0.0.0.0:5432
  connect_address: server_1:5432
  data_dir: /var/lib/pgsql/14/data
  bin_dir: /usr/pgsql-14/bin/
  config_dir: /var/lib/pgsql/14/data
  pgpass: /var/lib/pgsql/.pgpass
  authentication:
    superuser:
      username: postgres
      password: password
    replication:
      username: replicator
      password: password
    rewind:
      username: postgres
      password: password
  create_replica_methods:
    - basebackup
  basebackup:
    checkpoint: fast
  parameters:
    unix_socket_directories: /var/run/postgresql
  pg_hba:
    - local all postgres  peer
    - host all +hba_local_auth 0.0.0.0/0 scram-sha-256
    - host replication replicator 0.0.0.0/0 scram-sha-256
  pg_ctl_timeout: 60
  remove_data_directory_on_rewind_failure: false
  remove_data_directory_on_diverged_timelines: false

watchdog:
  mode: off

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

### patronictl show-config

```yaml
check_timeline: false
failsafe_mode: false
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    max_connections: 300
    max_locks_per_transaction: 64
    max_prepared_transactions: 0
    max_replication_slots: 10
    max_wal_senders: 10
    max_worker_processes: 8
    track_commit_timestamp: false
    wal_keep_size: 2GB
    wal_level: replica
    wal_log_hints: true
  use_pg_rewind: true
  use_slots: true
primary_start_timeout: 5
primary_stop_timeout: 30
retry_timeout: 10
synchronous_mode: true
synchronous_mode_strict: false
ttl: 30
```

### Patroni log files

```shell
patroni log server_2

2023-07-26 17:59:09,144 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 17:59:19,145 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 17:59:29,144 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 17:59:39,145 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 17:59:49,144 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:00:12,385 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:00:12,423 WARNING: Loop time exceeded, rescheduling immediately.
2023-07-26 18:00:14,027 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:01:36,990 INFO: Lock owner: server_2; I am server_2
2023-07-26 18:01:37,243 INFO: Updating synchronous privilege temporarily from ['server_1'] to []
2023-07-26 18:01:37,303 INFO: Synchronous replication key updated by someone else.
2023-07-26 18:01:37,349 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:01:37,350 WARNING: Loop time exceeded, rescheduling immediately.
2023-07-26 18:01:37,606 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:01:37,695 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:01:47,607 INFO: Lock owner: server_2; I am server_2
2023-07-26 18:01:47,727 INFO: establishing a new patroni connection to the postgres cluster
2023-07-26 18:01:48,007 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:01:57,741 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:02:07,696 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:02:17,695 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:02:27,698 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:02:37,696 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:02:47,699 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:02:57,744 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:03:07,739 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:03:17,696 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:03:27,697 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:03:37,696 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:03:47,696 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:03:57,695 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:04:07,697 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:04:17,741 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:04:27,696 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:04:37,741 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:04:47,740 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:04:57,740 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:05:07,695 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:05:17,740 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:05:27,696 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:05:37,701 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:05:47,695 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:05:57,695 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:06:07,696 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:06:17,696 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:06:27,696 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:06:37,695 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:06:47,607 INFO: Lock owner: server_2; I am server_2
2023-07-26 18:06:47,699 INFO: Assigning synchronous standby status to ['server_1']
2023-07-26 18:06:47,706 INFO: Synchronous replication key updated by someone else
2023-07-26 18:06:47,751 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:06:57,607 INFO: Lock owner: server_2; I am server_2
2023-07-26 18:06:57,696 INFO: Assigning synchronous standby status to ['server_1']
2023-07-26 18:06:57,696 INFO: Synchronous replication key updated by someone else
2023-07-26 18:06:57,741 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:07:07,607 INFO: Lock owner: server_2; I am server_2
2023-07-26 18:07:07,696 INFO: Assigning synchronous standby status to ['server_1']
2023-07-26 18:07:07,696 INFO: Synchronous replication key updated by someone else
2023-07-26 18:07:07,697 INFO: no action. I am (server_2), the leader with the lock
2023-07-26 18:07:17,607 INFO: Lock owner: server_2; I am server_2
2023-07-26 18:07:17,696 INFO: Assigning synchronous standby status to ['server_1']
2023-07-26 18:07:17,697 INFO: Synchronous replication key updated by someone else
2023-07-26 18:07:17,742 INFO: no action. I am (server_2), the leader with the lock

patroni log server_1

2023-07-26 17:59:19,195 INFO: no action. I am (server_1), a secondary, and following a leader (server_2)
2023-07-26 17:59:29,153 INFO: no action. I am (server_1), a secondary, and following a leader (server_2)
2023-07-26 17:59:39,195 INFO: no action. I am (server_1), a secondary, and following a leader (server_2)
2023-07-26 17:59:49,153 INFO: no action. I am (server_1), a secondary, and following a leader (server_2)
2023-07-26 17:59:59,196 INFO: no action. I am (server_1), a secondary, and following a leader (server_2)
2023-07-26 18:00:09,153 INFO: no action. I am (server_1), a secondary, and following a leader (server_2)
2023-07-26 18:00:19,196 INFO: no action. I am (server_1), a secondary, and following a leader (server_2)
2023-07-26 18:00:29,153 INFO: no action. I am (server_1), a secondary, and following a leader (server_2)
2023-07-26 18:00:39,197 INFO: no action. I am (server_1), a secondary, and following a leader (server_2)
2023-07-26 18:00:45,283 WARNING: Request failed to server_2: GET http://server_2:8008/patroni (HTTPConnectionPool(host='server_2', port=8008): Max retries exceeded with url: /patroni (Caused by ReadTimeoutError("HTTPConnectionPool(host='server_2', port=8008): Read timed out. (read timeout=2)",)))
2023-07-26 18:00:45,518 INFO: promoted self to leader by acquiring session lock
2023-07-26 18:00:45,523 INFO: cleared rewind state after becoming the leader
2023-07-26 18:00:45,518 INFO: Lock owner: server_1; I am server_1
2023-07-26 18:00:45,607 INFO: updated leader lock during promote
2023-07-26 18:00:46,761 INFO: no action. I am (server_1), the leader with the lock
2023-07-26 18:00:56,711 INFO: no action. I am (server_1), the leader with the lock
2023-07-26 18:01:06,753 INFO: no action. I am (server_1), the leader with the lock
2023-07-26 18:01:16,663 INFO: no action. I am (server_1), the leader with the lock
2023-07-26 18:01:26,664 INFO: no action. I am (server_1), the leader with the lock
2023-07-26 18:01:36,663 INFO: no action. I am (server_1), the leader with the lock
2023-07-26 18:01:37,179 INFO: Lock owner: server_2; I am server_1
2023-07-26 18:01:37,180 INFO: Demoting self (immediate-nolock)
2023-07-26 18:01:37,371 INFO: demoting self because I do not have the lock and I was a leader
2023-07-26 18:01:37,372 INFO: Lock owner: server_2; I am server_1
2023-07-26 18:01:37,372 INFO: starting after demotion in progress
2023-07-26 18:01:37,373 INFO: closed patroni connection to the postgresql cluster
2023-07-26 18:01:37,487 INFO: Lock owner: server_2; I am server_1
2023-07-26 18:01:37,532 INFO: starting after demotion in progress
2023-07-26 18:01:37,661 INFO: postmaster pid=3495902
2023-07-26 18:01:39,758 INFO: Lock owner: server_2; I am server_1
2023-07-26 18:01:39,758 INFO: establishing a new patroni connection to the postgres cluster
2023-07-26 18:01:39,782 INFO: Local timeline=5 lsn=165/D500EEF8
2023-07-26 18:01:39,794 ERROR: Exception when working with leader
Traceback (most recent call last):
  File "/var/lib/pgsql/patroni_venv/lib64/python3.6/site-packages/patroni/postgresql/rewind.py", line 69, in check_leader_is_not_in_recovery
    with get_connection_cursor(connect_timeout=3, options='-c statement_timeout=2000', conn_kwargs) as cur:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in enter
    return next(self.gen)
  File "/var/lib/pgsql/patroni_venv/lib64/python3.6/site-packages/patroni/postgresql/connection.py", line 43, in get_connection_cursor
    conn = psycopg.connect(kwargs)
  File "/var/lib/pgsql/patroni_venv/lib64/python3.6/site-packages/patroni/psycopg.py", line 42, in connect
    ret = connect(args, *kwargs)
  File "/var/lib/pgsql/patroni_venv/lib64/python3.6/site-packages/psycopg2/_init.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "server_2" (10.243.88.52), port 5432 failed: FATAL:  the database system is in recovery mode

2023-07-26 18:01:39,870 INFO: no action. I am (server_1), a secondary, and following a leader (server_2)
2023-07-26 18:01:48,007 INFO: Lock owner: server_2; I am server_1
2023-07-26 18:01:48,023 INFO: Local timeline=5 lsn=165/D500EEF8
2023-07-26 18:01:48,064 INFO: primary_timeline=4
2023-07-26 18:01:48,164 INFO: running pg_rewind from server_2
2023-07-26 18:01:48,259 INFO: running pg_rewind from dbname=postgres user=postgres host=server_2 port=5432 target_session_attrs=read-write
2023-07-26 18:01:57,706 INFO: Lock owner: server_2; I am server_1
2023-07-26 18:01:57,752 INFO: running pg_rewind from server_2 in progress
...<rewind working>...
2023-07-26 18:06:45,369 INFO: pg_rewind exit code=0
2023-07-26 18:06:45,369 INFO:  stdout=
2023-07-26 18:06:45,369 INFO:  stderr=pg_rewind: servers diverged at WAL location 165/D500ED80 on timeline 4
pg_rewind: rewinding from last common checkpoint at 165/D500ECD0 on timeline 4
pg_rewind: Done!

2023-07-26 18:06:45,410 WARNING: Postgresql is not running.
2023-07-26 18:06:45,410 INFO: Lock owner: server_2; I am server_1
2023-07-26 18:06:45,415 INFO: pg_controldata:
  pg_control version number: 1300
  Catalog version number: 202107181
  Database system identifier: 7242276756802305351
  Database cluster state: in archive recovery
  pg_control last modified: Wed Jul 26 18:01:42 2023
  Latest checkpoint location: 165/D5011650
  Latest checkpoint's REDO location: 165/D5011650
  Latest checkpoint's REDO WAL file: 0000000400000165000000D5
  Latest checkpoint's TimeLineID: 4
  Latest checkpoint's PrevTimeLineID: 4
  Latest checkpoint's full_page_writes: on
  Latest checkpoint's NextXID: 0:121272990
  Latest checkpoint's NextOID: 65622
  Latest checkpoint's NextMultiXactId: 583809876
  Latest checkpoint's NextMultiOffset: 4029019021
  Latest checkpoint's oldestXID: 15875722
  Latest checkpoint's oldestXID's DB: 16424
  Latest checkpoint's oldestActiveXID: 0
  Latest checkpoint's oldestMultiXid: 308274394
  Latest checkpoint's oldestMulti's DB: 16424
  Latest checkpoint's oldestCommitTsXid: 0
  Latest checkpoint's newestCommitTsXid: 0
  Time of latest checkpoint: Wed Jul 26 18:01:42 2023
  Fake LSN counter for unlogged rels: 0/3E8
  Minimum recovery ending location: 165/D501A698
  Min recovery ending loc''s timeline: 4
  Backup start location: 0/0
  Backup end location: 0/0
  End-of-backup record required: no
  wal_level setting: replica
  wal_log_hints setting: on
  max_connections setting: 300
  max_worker_processes setting: 8
  max_wal_senders setting: 10
  max_prepared_xacts setting: 0
  max_locks_per_xact setting: 64
  track_commit_timestamp setting: off
  Maximum data alignment: 8
  Database block size: 8192
  Blocks per segment of large relation: 131072
  WAL block size: 8192
  Bytes per WAL segment: 16777216
  Maximum length of identifiers: 64
  Maximum columns in an index: 32
  Maximum size of a TOAST chunk: 1996
  Size of a large-object chunk: 2048
  Date/time type storage: 64-bit integers
  Float8 argument passing: by value
  Data page checksum version: 1
  Mock authentication nonce: f4f47a57b934d4f516d51c5c6d3c7e75f18a7acaf895484a4e154c29296a6d64

2023-07-26 18:06:45,415 INFO: Lock owner: server_2; I am server_1
2023-07-26 18:06:45,460 INFO: starting as a secondary
2023-07-26 18:06:45,461 INFO: closed patroni connection to the postgresql cluster
2023-07-26 18:06:45,676 INFO: postmaster pid=3496437
2023-07-26 18:06:46,766 INFO: Lock owner: server_2; I am server_1
2023-07-26 18:06:46,767 INFO: establishing a new patroni connection to the postgres cluster
2023-07-26 18:06:46,825 INFO: no action. I am (server_1), a secondary, and following a leader (server_2)
2023-07-26 18:06:47,745 INFO: no action. I am (server_1), a secondary, and following a leader (server_2)
2023-07-26 18:06:57,830 INFO: no action. I am (server_1), a secondary, and following a leader (server_2)
```

### PostgreSQL log files

```shell
pg logs server_2
<..a lot of logging slow queries due server overload..>
2023-07-26 18:01:37.786 MSK    2307  0 LOG:  server process (PID 1326001) was terminated by signal 9: Killed
2023-07-26 18:01:37.786 MSK    2307  0 DETAIL:  Failed process was running: INSERT INTO .... <cut>
2023-07-26 18:01:37.786 MSK    2307  0 LOG:  terminating any other active server processes
2023-07-26 18:01:37.929 MSK    2307  0 LOG:  all server processes terminated; reinitializing
2023-07-26 18:01:38.106 MSK    1326183  0 LOG:  database system was interrupted; last known up at 2023-07-26 17:57:31 MSK
2023-07-26 18:01:39.793 MSK postgres 10.243.80.153 postgres 1326209  0 FATAL:  the database system is in recovery mode
2023-07-26 18:01:39.832 MSK replicator 10.243.80.153 [unknown] 1326211  0 FATAL:  the database system is in recovery mode
2023-07-26 18:01:42.316 MSK    1326183  0 LOG:  database system was not properly shut down; automatic recovery in progress
2023-07-26 18:01:42.333 MSK    1326183  0 LOG:  redo starts at 165/D3014580
2023-07-26 18:01:42.356 MSK    1326183  0 LOG:  invalid record length at 165/D5011650: wanted 24, got 0
2023-07-26 18:01:42.356 MSK    1326183  0 LOG:  redo done at 165/D5011618 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.02 s
2023-07-26 18:06:46.644 MSK replicator 10.243.80.153 [unknown] 1326521 streaming 165/D501A698 0 LOG:  standby "server_1" is now a synchronous standby with priority 1
2023-07-26 18:06:46.644 MSK replicator 10.243.80.153 [unknown] 1326521 streaming 165/D501A698 0 STATEMENT:  START_REPLICATION SLOT "server_1" 165/D5000000 TIMELINE 4




pg logs server_1
2023-07-26 18:00:45.523 MSK    3300658  0 FATAL:  terminating walreceiver process due to administrator command
2023-07-26 18:00:45.523 MSK    3300648  0 LOG:  invalid resource manager ID 120 at 165/D500ED80
2023-07-26 18:00:45.523 MSK    3300648  0 LOG:  redo done at 165/D500ED48 system usage: CPU: user: 1.85 s, system: 1.88 s, elapsed: 235346.81 s
2023-07-26 18:00:45.523 MSK    3300648  0 LOG:  last completed transaction was at log time 2023-07-26 17:56:54.934336+03
2023-07-26 18:00:45.524 MSK    3300648  0 LOG:  selected new timeline ID: 5
2023-07-26 18:00:45.545 MSK    3300648  0 LOG:  archive recovery complete
2023-07-26 18:00:45.568 MSK    3300645  0 LOG:  database system is ready to accept connections
2023-07-26 18:01:37.285 MSK    3300645  0 LOG:  database system is shut down
2023-07-26 18:01:37.746 MSK    3495902  0 LOG:  starting PostgreSQL 14.8 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18), 64-bit
2023-07-26 18:01:37.746 MSK    3495902  0 LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-07-26 18:01:37.748 MSK    3495902  0 LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-07-26 18:01:37.752 MSK    3495905  0 LOG:  database system was interrupted; last known up at 2023-07-26 18:00:45 MSK
2023-07-26 18:01:38.685 MSK postgres [local] postgres 3495913  0 FATAL:  the database system is starting up
2023-07-26 18:01:38.712 MSK postgres [local] postgres 3495915  0 FATAL:  the database system is starting up
2023-07-26 18:01:38.972 MSK    3495905  0 WARNING:  specified neither primary_conninfo nor restore_command
2023-07-26 18:01:38.972 MSK    3495905  0 HINT:  The database server will regularly poll the pg_wal subdirectory to check for files placed there.
2023-07-26 18:01:38.972 MSK    3495905  0 LOG:  entering standby mode
2023-07-26 18:01:38.972 MSK    3495905  0 LOG:  database system was not properly shut down; automatic recovery in progress
2023-07-26 18:01:38.976 MSK    3495905  0 LOG:  redo starts at 165/D500EDB0
2023-07-26 18:01:38.976 MSK    3495905  0 LOG:  invalid record length at 165/D500EEF8: wanted 24, got 0
2023-07-26 18:01:38.977 MSK    3495905  0 LOG:  consistent recovery state reached at 165/D500EEF8
2023-07-26 18:01:38.978 MSK    3495902  0 LOG:  database system is ready to accept read-only connections
2023-07-26 18:01:39.816 MSK    3495902  0 LOG:  parameter "primary_conninfo" changed to "user=replicator passfile=/var/lib/pgsql/.pgpass host=server_2 port=5432 sslmode=prefer application_name=server_1 gssencmode=prefer channel_binding=prefer"
2023-07-26 18:01:39.816 MSK    3495902  0 LOG:  parameter "primary_slot_name" changed to "server_1"
2023-07-26 18:01:39.833 MSK    3495951  0 FATAL:  could not connect to the primary server: connection to server at "server_2" (10.243.88.52), port 5432 failed: FATAL:  the database system is in recovery mode
2023-07-26 18:01:44.841 MSK    3495969  0 FATAL:  highest timeline 4 of the primary is behind recovery timeline 5
2023-07-26 18:01:48.166 MSK    3495902  0 LOG:  aborting any active transactions
2023-07-26 18:01:48.166 MSK postgres [local] postgres 3495945 idle -4595692538801023814 FATAL:  terminating connection due to administrator command
2023-07-26 18:01:48.168 MSK    3495928  0 LOG:  shutting down
2023-07-26 18:01:48.198 MSK    3495902  0 LOG:  database system is shut down
2023-07-26 18:06:45.763 MSK    3496437  0 LOG:  starting PostgreSQL 14.8 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18), 64-bit
2023-07-26 18:06:45.764 MSK    3496437  0 LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-07-26 18:06:45.765 MSK    3496437  0 LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-07-26 18:06:45.769 MSK    3496440  0 LOG:  database system was interrupted while in recovery at log time 2023-07-26 18:01:42 MSK
2023-07-26 18:06:45.769 MSK    3496440  0 HINT:  If this has occurred more than once some data might be corrupted and you might need to choose an earlier recovery target.
2023-07-26 18:06:46.592 MSK    3496440  0 LOG:  entering standby mode
2023-07-26 18:06:46.599 MSK    3496440  0 LOG:  redo starts at 165/D3014580
2023-07-26 18:06:46.602 MSK    3496440  0 LOG:  consistent recovery state reached at 165/D501A698
2023-07-26 18:06:46.602 MSK    3496440  0 LOG:  invalid record length at 165/D501A698: wanted 24, got 0
2023-07-26 18:06:46.603 MSK    3496437  0 LOG:  database system is ready to accept read-only connections
2023-07-26 18:06:46.643 MSK    3496448  0 LOG:  started streaming WAL from primary at 165/D5000000 on timeline 4
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

ouput patronictl history (no record about switching)

```
+----+---------------+------------------------------+----------------------------------+--------------------+
| TL |           LSN | Reason                       | Timestamp                        | New Leader         |
+----+---------------+------------------------------+----------------------------------+--------------------+
|  1 |      33554592 | no recovery target specified | 2023-06-08T14:37:36.146614+03:00 | server_1           |
|  2 |      67109024 | no recovery target specified | 2023-06-08T14:37:54.249479+03:00 | server_1           |
|  3 | 1530199539712 | no recovery target specified | 2023-07-24T00:18:47.860614+03:00 | server_2           |
+----+---------------+------------------------------+----------------------------------+--------------------+
```

**Comment by CyberDem0n** [comment]
> 1. Why server_1 after receiving the lock, made demote, after received lock at 18:00:45,518

Because server_2 overwritten the leader key after it "returned" back from the hanging state. There was a bug, that was fixed some time ago in https://github.com/zalando/patroni/pull/2689 and https://github.com/zalando/patroni/pull/2693

> 2. Why is there no information about this switchover in the patronictl history?

Because server_2 noticed that it is a leader and the /history key doesn't match its expectations and simply overwritten it.

> 3. Standby cannot go into synchronous state, the same message (Synchronous replication key updated by someone else) is repeated. Bug?

Yeah, this is probably a bug.

> What did you expect to happen?
1. After changing the master node, it should not return to the role of a replica without good reason

As I said, there was a bug that is already fixed in 3.0.3

> 2. synchronous replica should get the status of "sync standby"

I'll look into it.

> 3. in the history of switching, the facts of changing roles should be recorded

That wouldn't have happened if server_2 didn't falsely overtake the leader key. Ideally, if Patroni notice that Postgres isn't running in recovery it should check that the timeline is matching the latest value from the /history key.

Actually, the very similar problem was [discussed on Slack](https://postgresteam.slack.com/archives/C9XPYG92A/p1684140387534219), but it seems that we didn't agree who should take actions.

cc @ants

**Comment by glushakov** [comment]
Thanks for the answer.
For information - I could return the state "sync standby" only by turning off the synchronous mode and turning it back on.

**Comment by Jebrail** [comment]
patroni 3.3.1 . been strugling 2 days  to show "sync standby" instead of "Replica" in patronictl list  output although postgres logs and pg_stat_replication indicated that replica is sync . finally achieved it by turning off the synchronous mode and turning it back on..
