### ISSUE TITLE
Hot reload certificat not working on 3.0.3

### ISSUE THREAD

**Issue by BornTKill** [zalando/patroni#2785]
### What happened?

Dear,

We recently migrate patroni version 2.1.4 to 3.0.3 and we encounter issue.
We periodically renew certificate with vault-agent and since upgraded, the new certificate is not hot loaded.

root@patronidata-02:~# patronictl -c /etc/patroni/config.yml -k reload patroni-data patronidata-02 --force
+ Cluster: patroni-data ------+---------+---------+----+-----------+
| Member         | Host       | Role    | State   | TL | Lag in MB |
+----------------+------------+---------+---------+----+-----------+
| patronidata-01 | 10.XX.XX.1 | Leader  | running |  5 |           |
| patronidata-02 | 10.XX.XX.2 | Replica | running |  5 |         0 |
+----------------+------------+---------+---------+----+-----------+
2023-07-27 13:10:25,533 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])"))': /reload
2023-07-27 13:10:25,540 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])"))': /reload
2023-07-27 13:10:25,547 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])"))': /reload
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 485, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 366, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 491, in wrap_socket
    raise ssl.SSLError("bad handshake: %r" % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/patronictl", line 8, in <module>
    sys.exit(ctl())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/patroni/ctl.py", line 1011, in reload
    r = request_patroni(member, 'post', 'reload')
  File "/usr/local/lib/python3.8/dist-packages/patroni/ctl.py", line 339, in request_patroni
    return request_executor(member, method, endpoint, data)
  File "/usr/local/lib/python3.8/dist-packages/patroni/request.py", line 147, in __call__
    return self.request(method, url, data, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/patroni/request.py", line 128, in request
    return self._pool.request(method.upper(), url, body=body, **kwargs)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 79, in request
    return self.request_encode_body(
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='patronidata-02.xx', port=8008): Max retries exceeded with url: /reload (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

Only systemctl restart patroni solved the problem but is too violent.

I found old issue
https://github.com/zalando/patroni/issues/1886
https://github.com/zalando/patroni/issues/2433

But because it was working on patroni 2.1.4, I am not sure what is the problem.

### How can we reproduce it (as minimally and precisely as possible)?

Configure patroni to use certificat that expire every 5mn
Wait for the certificate to expire
reload member with patronictl command
patronictl fail to reload because of expired certificate.

### What did you expect to happen?

Patroni use the new issued certificate.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.0.3
-   PostgreSQL version: 15.3-1
-   DCS (and its version): 

### Patroni configuration file

```yaml
#
# Ansible managed
#
scope: patroni-data
namespace: /service/
name: patronidata-02

log:
  dir: '/var/log/postgresql'
  level: 'INFO'

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    synchronous_mode_strict: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_prepared_transactions: 30
  method: pgbackrest
  pgbackrest:
    command: /usr/local/bin/postgresql_bootstrap_cluster.sh
    recovery_conf:
      restore_command: pgbackrest --stanza=patroni-data archive-get %f "%p"
      recovery_target_timeline: latest
      recovery_target_action: promote
      recovery_target_time: ''
  pg_hba:
    - hostssl replication replicator 10.xx.xx.1/32 md5
    - hostssl replication replicator 10.xx.xx.2/32 md5
    - hostssl all all 0.0.0.0/0 md5
  users:
    postgres:
      password: 'XXXXX'
    replicator:
      password: 'XXXXX'
    monitoring:
      password: 'XXXXX'

consul:
  host: 127.0.0.1
  port: 8500
  register_service: true
  consistency: consistent

postgresql:
  listen: 0.0.0.0:5432
  connect_address: 10.xx.xx.2:5432
  data_dir: /data/patroni-data/member/15/data
  bin_dir: /usr/lib/postgresql/15/bin
  use_unix_socket: false
  pgpass: /tmp/pgpass0
  pg_ctl_timeout: 60
  use_pg_rewind: false
  remove_data_directory_on_rewind_failure: false
  authentication:
    superuser:
      username: postgres
      password: 'XXXXXX'
    replication:
      username: replicator
      password: 'XXXXXX'
  parameters:
    unix_socket_directories: '.'
    logging_collector: on
    log_connections: on
    log_disconnections: on
    log_directory: '/var/log/postgresql'
    log_filename: 'postgresql.log'
    ssl: on
    ssl_cert_file: /var/lib/postgresql/certs/fullchain.crt
    ssl_key_file: /var/lib/postgresql/certs/private.key
    shared_preload_libraries: 'pg_stat_statements'
    password_encryption: md5
    pg_stat_statements.max: 10000
    pg_stat_statements.track: all
    archive_mode: on
    archive_command: pgbackrest --stanza=patroni-data archive-push "%p"
    archive_timeout: 1800
  recovery_conf:
    restore_command: pgbackrest --stanza=patroni-data archive-get %f "%p"
    recovery_target_timeline: latest
    recovery_target_action: promote
    recovery_target_time: ''
  create_replica_methods:
    - pgbackrest
    - basebackup
  pgbackrest:
    command: /usr/bin/pgbackrest --stanza=$SCOPE restore
    keep_data: True
    no_params: True
  basebackup:
    checkpoint: 'fast'
  pg_hba:
    - local all all md5
    - host  replication all 127.0.0.1/32 md5
    - hostssl replication replicator 10.xx.xx.1/32 md5
    - hostssl replication replicator 10.xx.xx.2/32 md5
    - hostssl all all 0.0.0.0/0 md5

ctl:
  insecure: True
 
restapi:
  listen: 0.0.0.0:8008
  cafile: /var/lib/postgresql/certs/ca.crt
  connect_address: patronidata-02.xxx:8008
  certfile: /var/lib/postgresql/certs/fullchain.crt
  keyfile: /var/lib/postgresql/certs/private.key

watchdog:
  mode: automatic
  device: /dev/watchdog
  safety_margin: 5
```

### patronictl show-config

```yaml
root@patronidata-02:~# patronictl -c /etc/patroni/config.yml show-config
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
pause: false
postgresql:
  parameters:
    max_connections: 100
    max_prepared_transactions: 30
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: false
synchronous_mode_strict: false
ttl: 30
```

### Patroni log files

```shell
2023-07-27 13:10:25,533 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])"))': /reload
2023-07-27 13:10:25,540 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])"))': /reload
2023-07-27 13:10:25,547 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])"))': /reload
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 485, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 366, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 491, in wrap_socket
    raise ssl.SSLError("bad handshake: %r" % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/patronictl", line 8, in <module>
    sys.exit(ctl())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/patroni/ctl.py", line 1011, in reload
    r = request_patroni(member, 'post', 'reload')
  File "/usr/local/lib/python3.8/dist-packages/patroni/ctl.py", line 339, in request_patroni
    return request_executor(member, method, endpoint, data)
  File "/usr/local/lib/python3.8/dist-packages/patroni/request.py", line 147, in __call__
    return self.request(method, url, data, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/patroni/request.py", line 128, in request
    return self._pool.request(method.upper(), url, body=body, **kwargs)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 79, in request
    return self.request_encode_body(
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='patronidata-02.xx', port=8008): Max retries exceeded with url: /reload (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```

### PostgreSQL log files

```shell
N/A
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by CyberDem0n** [comment]
Thanks for detailed analysis @BornTKill.
The problem is actually already solved in 3.0.4 (commit https://github.com/zalando/patroni/commit/ed02826103a04effa098df6a9cfb647c6d974d45).
