### ISSUE TITLE
Unpredictable(?) standby cluster promotion 

### ISSUE THREAD

**Issue by gsl23** [zalando/patroni#2814]
### What happened?

Hi ! We have geo distributed standby patroni cluster and we are testing switchover mechanism. 
Switchover algorithm looks like: 
1. shutdown primary cluster ( systemctl stop patroni, master stops last )
2. switch primary to standby (  add standby_cluster section in conf file and in metadata db by patronictl edit-config) 
3. start old primary as standby
4. activate old standby ( patronictl edit-config, remove standby_cluster section) 

Sometimes it works, sometimes new standby promotes itself to primary , after step 3 before 4 ;^) 
Promotion new standby looks like that in patroni log : 
```
Aug 04 00:05:46 sks04db1 patroni[25358]: 2023-08-04 00:05:46,928 INFO: no action. I am (sks04db167) the standby leader with the lock
Aug 04 00:05:56 sks04db1 patroni[25358]: 2023-08-04 00:05:56,909 INFO: Lock owner: sks04db167; I am sks04db167

step 3 is over here , but step 4 is not over yet, new primary is unreachable yet and new standby promates itself: 

Aug 04 00:05:56 sks04db1 patroni[25358]: 2023-08-04 00:05:56,914 WARNING: Could not activate Linux watchdog device: "Can't open watchdog device: [Errno 2] No such file or directory: '/dev/watchdog'"
Aug 04 00:05:56 sks04db1 patroni[25358]: 2023-08-04 00:05:56,918 INFO: promoted self to leader because I had the session lock
Aug 04 00:05:56 sks04db1 patroni[25358]: 2023-08-04 00:05:56,922 INFO: Changed max_connections from 1000 to 100 (restart might be required)
Aug 04 00:05:56 sks04db1 patroni[25358]: server promoting
Aug 04 00:05:56 sks04db1 patroni[25358]: 2023-08-04 00:05:56,925 INFO: Reloading PostgreSQL configuration.
Aug 04 00:05:56 sks04db1 patroni[25358]: 2023-08-04 00:05:56,927 INFO: cleared rewind state after becoming the leader
Aug 04 00:05:56 sks04db1 patroni[25358]: server signaled
Aug 04 00:05:57 sks04db1 patroni[25358]: 2023-08-04 00:05:57,962 INFO: no action. I am (sks04db167) the leader with the lock
Aug 04 00:05:57 sks04db1 patroni[25358]: 2023-08-04 00:05:57,990 INFO: no action. I am (sks04db167) the leader with the lock
Aug 04 00:06:07 sks04db1 patroni[25358]: 2023-08-04 00:06:07,989 INFO: no action. I am (sks04db167) the leader with the lock

now we have 2 primaries :) - because new standby have promoted itself and new primary, that we have activated on step 4.
```

### How can we reproduce it (as minimally and precisely as possible)?

start standby cluster without reachable primary , i suppose

### What did you expect to happen?

standby didn't promote itself automaticly or have tuned timings 

### Patroni/PostgreSQL/DCS version

-   Patroni version: patroni 2.1.0
-   PostgreSQL version:  12.7
-   DCS (and its version): Consul v1.10.1

### Patroni configuration file

```yaml
scope: cluster1 
name: nodename1

restapi:
  listen: <ip>:8008
  connect_address: <ip>:8008


consul:
  host: 127.0.0.1:8500

bootstrap:
  dcs:
# BEGIN ANSIBLE MANAGED BLOCK BOOTSTRAP
    standby_cluster:
      host: <ip>
      port: <port>
      primary_slot_name: patroni
      create_replica_methods:
      - basebackup
# END ANSIBLE MANAGED BLOCK BOOTSTRAP
    slots:
      patroni:
        type: physical
      barman_msk:
        type: physical
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: hot_standby
        hot_standby: "on"
        wal_keep_segments: 1000
        max_wal_senders: 10
        max_replication_slots: 5
        wal_log_hints: "on"
        archive_mode: "on"
        archive_timeout: 1800s
        archive_command: mkdir -p ../wal_archive && test ! -f ../wal_archive/%f && cp %p ../wal_archive/%f
      recovery_conf:
        restore_command: cp ../wal_archive/%f %p

  # some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - ....

postgresql:
  listen: 0.0.0.0:5432
  connect_address: <ip>:5432
  data_dir: /data/pg
  bin_dir: /usr/pgsql-12/bin
#  config_dir:
  pg_rewind:
    username: postgres
    password: ****
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: *****
    superuser:
      username: postgres
      password: ****
  parameters:
    shared_preload_libraries: 'pg_stat_statements,timescaledb'
    unix_socket_directories: /run/postgresql
.....
```

### patronictl show-config

```yaml
# patronictl -c /etc/patroni/patroni.yml show-config
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: mkdir -p ../wal_archive && test ! -f ../wal_archive/%f && cp %p ../wal_archive/%f
    archive_mode: 'on'
    archive_timeout: 1800s
    hot_standby: 'on'
    max_replication_slots: 5
    max_wal_senders: 10
    wal_keep_segments: 1000
    wal_level: hot_standby
    wal_log_hints: 'on'
  recovery_conf:
    restore_command: cp ../wal_archive/%f %p
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
slots:
  barman_msk:
    type: physical
standby_cluster:
  create_replica_methods:
  - basebackup
  host: <ip>
  port: 9999
  primary_slot_name: patroni
synchronous_mode: false
ttl: 30
```

### Patroni log files

```shell
Selfpromoted standby full log :
------------------------------------

Aug 04 00:04:54 sks04db1 patroni[34875]: 2023-08-04 00:04:54,746 INFO: no action. I am (sks04db167) the leader with the lock
Aug 04 00:04:59 sks04db1 patroni[34875]: 2023-08-04 00:04:59,858 WARNING: Exception happened during processing of request from 10....:35102
Aug 04 00:04:59 sks04db1 patroni[34875]: 2023-08-04 00:04:59,859 WARNING: Traceback (most recent call last):
Aug 04 00:04:59 sks04db1 patroni[34875]: File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
Aug 04 00:04:59 sks04db1 patroni[34875]: self.finish_request(request, client_address)
Aug 04 00:04:59 sks04db1 patroni[34875]: File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
Aug 04 00:04:59 sks04db1 patroni[34875]: self.RequestHandlerClass(request, client_address, self)
Aug 04 00:04:59 sks04db1 patroni[34875]: File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
Aug 04 00:04:59 sks04db1 patroni[34875]: self.handle()
Aug 04 00:04:59 sks04db1 patroni[34875]: File "/usr/lib64/python3.6/http/server.py", line 418, in handle
Aug 04 00:04:59 sks04db1 patroni[34875]: self.handle_one_request()
Aug 04 00:04:59 sks04db1 patroni[34875]: File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 634, in handle_one_request
Aug 04 00:04:59 sks04db1 patroni[34875]: BaseHTTPRequestHandler.handle_one_request(self)
Aug 04 00:04:59 sks04db1 patroni[34875]: File "/usr/lib64/python3.6/http/server.py", line 406, in handle_one_request
Aug 04 00:04:59 sks04db1 patroni[34875]: method()
Aug 04 00:04:59 sks04db1 patroni[34875]: File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 178, in do_GET
Aug 04 00:04:59 sks04db1 patroni[34875]: self._write_status_response(status_code, response)
Aug 04 00:04:59 sks04db1 patroni[34875]: File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 94, in _write_status_response
Aug 04 00:04:59 sks04db1 patroni[34875]: self._write_json_response(status_code, response)
Aug 04 00:04:59 sks04db1 patroni[34875]: File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 53, in _write_json_response
Aug 04 00:04:59 sks04db1 patroni[34875]: self._write_response(status_code, json.dumps(response, default=str), content_type='application/json')
Aug 04 00:04:59 sks04db1 patroni[34875]: File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 50, in _write_response
Aug 04 00:04:59 sks04db1 patroni[34875]: self.wfile.write(body.encode('utf-8'))
Aug 04 00:04:59 sks04db1 patroni[34875]: File "/usr/lib64/python3.6/socketserver.py", line 803, in write
Aug 04 00:04:59 sks04db1 patroni[34875]: self._sock.sendall(b)
Aug 04 00:04:59 sks04db1 patroni[34875]: ConnectionResetError: [Errno 104] Connection reset by peer
Aug 04 00:05:04 sks04db1 patroni[34875]: 2023-08-04 00:05:04,726 INFO: Lock owner: sks04db167; I am sks04db167
Aug 04 00:05:04 sks04db1 patroni[34875]: 2023-08-04 00:05:04,732 ERROR: Failed to drop replication slot 'patroni'
Aug 04 00:05:04 sks04db1 patroni[34875]: 2023-08-04 00:05:04,735 INFO: no action. I am (sks04db167) the leader with the lock
Aug 04 00:05:11 sks04db1 systemd[1]: Stopping Runners to orchestrate a high-availability PostgreSQL...
-- Subject: Unit patroni.service has begun shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit patroni.service has begun shutting down.
Aug 04 00:05:12 sks04db1 systemd[1]: Stopped Runners to orchestrate a high-availability PostgreSQL.
-- Subject: Unit patroni.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit patroni.service has finished shutting down.
Aug 04 00:05:14 sks04db1 systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL.
-- Subject: Unit patroni.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit patroni.service has finished starting up.
-- 
-- The start-up result is done.
Aug 04 00:05:15 sks04db1 patroni[25358]: 2023-08-04 00:05:15,522 INFO: No PostgreSQL configuration items changed, nothing to reload.
Aug 04 00:05:15 sks04db1 patroni[25358]: 2023-08-04 00:05:15,534 WARNING: Postgresql is not running.
Aug 04 00:05:15 sks04db1 patroni[25358]: 2023-08-04 00:05:15,534 INFO: Lock owner: None; I am sks04db167
Aug 04 00:05:15 sks04db1 patroni[25358]: 2023-08-04 00:05:15,538 INFO: pg_controldata:
Aug 04 00:05:15 sks04db1 patroni[25358]: pg_control version number: 1201
Aug 04 00:05:15 sks04db1 patroni[25358]: Catalog version number: 201909212
Aug 04 00:05:15 sks04db1 patroni[25358]: Database system identifier: 6989614412350293892
Aug 04 00:05:15 sks04db1 patroni[25358]: Database cluster state: shut down
Aug 04 00:05:15 sks04db1 patroni[25358]: pg_control last modified: Fri Aug  4 00:05:11 2023
Aug 04 00:05:15 sks04db1 patroni[25358]: Latest checkpoint location: 53/EB000028
Aug 04 00:05:15 sks04db1 patroni[25358]: Latest checkpoint's REDO location: 53/EB000028
Aug 04 00:05:15 sks04db1 patroni[25358]: Latest checkpoint's REDO WAL file: 0000002D00000053000000EB
Aug 04 00:05:15 sks04db1 patroni[25358]: Latest checkpoint's TimeLineID: 45
Aug 04 00:05:15 sks04db1 patroni[25358]: Latest checkpoint's PrevTimeLineID: 45
Aug 04 00:05:15 sks04db1 patroni[25358]: Latest checkpoint's full_page_writes: on
Aug 04 00:05:15 sks04db1 patroni[25358]: Latest checkpoint's NextXID: 0:208403246
Aug 04 00:05:15 sks04db1 patroni[25358]: Latest checkpoint's NextOID: 87748
Aug 04 00:05:15 sks04db1 patroni[25358]: Latest checkpoint's NextMultiXactId: 8
Aug 04 00:05:15 sks04db1 patroni[25358]: Latest checkpoint's NextMultiOffset: 15
Aug 04 00:05:15 sks04db1 patroni[25358]: Latest checkpoint's oldestXID: 65645955
Aug 04 00:05:15 sks04db1 patroni[25358]: Latest checkpoint's oldestXID's DB: 27513
Aug 04 00:05:15 sks04db1 patroni[25358]: Latest checkpoint's oldestActiveXID: 0
Aug 04 00:05:15 sks04db1 patroni[25358]: Latest checkpoint's oldestMultiXid: 1
Aug 04 00:05:15 sks04db1 patroni[25358]: Latest checkpoint's oldestMulti's DB: 27514
Aug 04 00:05:15 sks04db1 patroni[25358]: Latest checkpoint's oldestCommitTsXid: 0
Aug 04 00:05:15 sks04db1 patroni[25358]: Latest checkpoint's newestCommitTsXid: 0
Aug 04 00:05:15 sks04db1 patroni[25358]: Time of latest checkpoint: Fri Aug  4 00:05:11 2023
Aug 04 00:05:15 sks04db1 patroni[25358]: Fake LSN counter for unlogged rels: 0/3E8
Aug 04 00:05:15 sks04db1 patroni[25358]: Minimum recovery ending location: 0/0
Aug 04 00:05:15 sks04db1 patroni[25358]: Min recovery ending loc's timeline: 0
Aug 04 00:05:15 sks04db1 patroni[25358]: Backup start location: 0/0
Aug 04 00:05:15 sks04db1 patroni[25358]: Backup end location: 0/0
Aug 04 00:05:15 sks04db1 patroni[25358]: End-of-backup record required: no
Aug 04 00:05:15 sks04db1 patroni[25358]: wal_level setting: replica
Aug 04 00:05:15 sks04db1 patroni[25358]: wal_log_hints setting: on
Aug 04 00:05:15 sks04db1 patroni[25358]: max_connections setting: 1000
Aug 04 00:05:15 sks04db1 patroni[25358]: max_worker_processes setting: 8
Aug 04 00:05:15 sks04db1 patroni[25358]: max_wal_senders setting: 10
Aug 04 00:05:15 sks04db1 patroni[25358]: max_prepared_xacts setting: 0
Aug 04 00:05:15 sks04db1 patroni[25358]: max_locks_per_xact setting: 64
Aug 04 00:05:15 sks04db1 patroni[25358]: track_commit_timestamp setting: off
Aug 04 00:05:15 sks04db1 patroni[25358]: Maximum data alignment: 8
Aug 04 00:05:15 sks04db1 patroni[25358]: Database block size: 8192
Aug 04 00:05:15 sks04db1 patroni[25358]: Blocks per segment of large relation: 131072
Aug 04 00:05:15 sks04db1 patroni[25358]: WAL block size: 8192
Aug 04 00:05:15 sks04db1 patroni[25358]: Bytes per WAL segment: 16777216
Aug 04 00:05:15 sks04db1 patroni[25358]: Maximum length of identifiers: 64
Aug 04 00:05:15 sks04db1 patroni[25358]: Maximum columns in an index: 32
Aug 04 00:05:15 sks04db1 patroni[25358]: Maximum size of a TOAST chunk: 1996
Aug 04 00:05:15 sks04db1 patroni[25358]: Size of a large-object chunk: 2048
Aug 04 00:05:15 sks04db1 patroni[25358]: Date/time type storage: 64-bit integers
Aug 04 00:05:15 sks04db1 patroni[25358]: Float4 argument passing: by value
Aug 04 00:05:15 sks04db1 patroni[25358]: Float8 argument passing: by value
Aug 04 00:05:15 sks04db1 patroni[25358]: Data page checksum version: 1
Aug 04 00:05:15 sks04db1 patroni[25358]: Mock authentication nonce: 5818b4c53ceb82b300cc1d577482789a944634640385b08071d9d68595fd54d2
Aug 04 00:05:15 sks04db1 patroni[25358]: 2023-08-04 00:05:15,552 INFO: Local timeline=45 lsn=53/EB000028
Aug 04 00:05:15 sks04db1 patroni[25358]: 2023-08-04 00:05:15,561 ERROR: Exception when working with leader
Aug 04 00:05:15 sks04db1 patroni[25358]: Traceback (most recent call last):
Aug 04 00:05:15 sks04db1 patroni[25358]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/rewind.py", line 60, in check_leader_is_not_in_recovery
Aug 04 00:05:15 sks04db1 patroni[25358]: with get_connection_cursor(connect_timeout=3, options='-c statement_timeout=2000', **conn_kwargs) as cur:
Aug 04 00:05:15 sks04db1 patroni[25358]: File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
Aug 04 00:05:15 sks04db1 patroni[25358]: return next(self.gen)
Aug 04 00:05:15 sks04db1 patroni[25358]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 43, in get_connection_cursor
Aug 04 00:05:15 sks04db1 patroni[25358]: conn = psycopg2.connect(**kwargs)
Aug 04 00:05:15 sks04db1 patroni[25358]: File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
Aug 04 00:05:15 sks04db1 patroni[25358]: conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Aug 04 00:05:15 sks04db1 patroni[25358]: psycopg2.OperationalError: server closed the connection unexpectedly
Aug 04 00:05:15 sks04db1 patroni[25358]: This probably means the server terminated abnormally
Aug 04 00:05:15 sks04db1 patroni[25358]: before or while processing the request.
Aug 04 00:05:15 sks04db1 patroni[25358]: 2023-08-04 00:05:15,562 INFO: Lock owner: None; I am sks04db167
Aug 04 00:05:15 sks04db1 patroni[25358]: 2023-08-04 00:05:15,570 INFO: trying to follow a remote master because standby cluster is unhealthy
Aug 04 00:05:15 sks04db1 patroni[25358]: 2023-08-04 00:05:15,575 INFO: Lock owner: None; I am sks04db167
Aug 04 00:05:15 sks04db1 patroni[25358]: 2023-08-04 00:05:15,576 INFO: not healthy enough for leader race
Aug 04 00:05:15 sks04db1 patroni[25358]: 2023-08-04 00:05:15,580 INFO: restarting after failure in progress
Aug 04 00:05:15 sks04db1 patroni[25358]: 2023-08-04 00:05:15.767 MSK [25395] LOG:  starting PostgreSQL 12.7 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
Aug 04 00:05:15 sks04db1 patroni[25358]: 2023-08-04 00:05:15.767 MSK [25395] LOG:  listening on IPv4 address "0.0.0.0", port 5432
Aug 04 00:05:15 sks04db1 patroni[25358]: 2023-08-04 00:05:15.768 MSK [25395] LOG:  listening on Unix socket "/run/postgresql/.s.PGSQL.5432"
Aug 04 00:05:15 sks04db1 patroni[25358]: 2023-08-04 00:05:15,777 INFO: postmaster pid=25395
Aug 04 00:05:15 sks04db1 patroni[25358]: 2023-08-04 00:05:15.879 MSK [25395] LOG:  redirecting log output to logging collector process
Aug 04 00:05:15 sks04db1 patroni[25358]: 2023-08-04 00:05:15.879 MSK [25395] HINT:  Future log output will appear in directory "log".
Aug 04 00:05:15 sks04db1 patroni[25358]: localhost:5432 - rejecting connections
Aug 04 00:05:15 sks04db1 patroni[25358]: localhost:5432 - rejecting connections
Aug 04 00:05:16 sks04db1 patroni[25358]: localhost:5432 - accepting connections
Aug 04 00:05:16 sks04db1 patroni[25358]: 2023-08-04 00:05:16,909 INFO: establishing a new patroni connection to the postgres cluster
Aug 04 00:05:16 sks04db1 patroni[25358]: 2023-08-04 00:05:16,922 WARNING: Request failed to sks04db168: GET http://10....:8008/patroni (HTTPConnectionPool(host='10....', port=8008): Max retries exceeded with url: /patroni (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f802c171dd8>: Failed to establish a new connection: [Errno 111] Connection refused',)))
Aug 04 00:05:16 sks04db1 patroni[25358]: 2023-08-04 00:05:16,923 WARNING: Request failed to sks04db169: GET http://10....:8008/patroni (HTTPConnectionPool(host='10....', port=8008): Max retries exceeded with url: /patroni (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f802c17c2b0>: Failed to establish a new connection: [Errno 111] Connection refused',)))
Aug 04 00:05:17 sks04db1 patroni[25358]: 2023-08-04 00:05:17,037 INFO: Local timeline=45 lsn=53/EB0000A0
Aug 04 00:05:17 sks04db1 patroni[25358]: 2023-08-04 00:05:17,045 ERROR: Exception when working with leader
Aug 04 00:05:17 sks04db1 patroni[25358]: Traceback (most recent call last):
Aug 04 00:05:17 sks04db1 patroni[25358]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/rewind.py", line 60, in check_leader_is_not_in_recovery
Aug 04 00:05:17 sks04db1 patroni[25358]: with get_connection_cursor(connect_timeout=3, options='-c statement_timeout=2000', **conn_kwargs) as cur:
Aug 04 00:05:17 sks04db1 patroni[25358]: File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
Aug 04 00:05:17 sks04db1 patroni[25358]: return next(self.gen)
Aug 04 00:05:17 sks04db1 patroni[25358]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 43, in get_connection_cursor
Aug 04 00:05:17 sks04db1 patroni[25358]: conn = psycopg2.connect(**kwargs)
Aug 04 00:05:17 sks04db1 patroni[25358]: File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
Aug 04 00:05:17 sks04db1 patroni[25358]: conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Aug 04 00:05:17 sks04db1 patroni[25358]: psycopg2.OperationalError: server closed the connection unexpectedly
Aug 04 00:05:17 sks04db1 patroni[25358]: This probably means the server terminated abnormally
Aug 04 00:05:17 sks04db1 patroni[25358]: before or while processing the request.
Aug 04 00:05:17 sks04db1 patroni[25358]: 2023-08-04 00:05:17,053 ERROR: Failed to drop replication slot 'patroni'
Aug 04 00:05:17 sks04db1 patroni[25358]: 2023-08-04 00:05:17,064 INFO: promoted self to a standby leader by acquiring session lock
Aug 04 00:05:26 sks04db1 patroni[25358]: 2023-08-04 00:05:26,908 INFO: Lock owner: sks04db167; I am sks04db167
Aug 04 00:05:26 sks04db1 patroni[25358]: 2023-08-04 00:05:26,921 INFO: Local timeline=45 lsn=53/EB0000A0
Aug 04 00:05:26 sks04db1 patroni[25358]: 2023-08-04 00:05:26,930 ERROR: Exception when working with leader
Aug 04 00:05:26 sks04db1 patroni[25358]: Traceback (most recent call last):
Aug 04 00:05:26 sks04db1 patroni[25358]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/rewind.py", line 60, in check_leader_is_not_in_recovery
Aug 04 00:05:26 sks04db1 patroni[25358]: with get_connection_cursor(connect_timeout=3, options='-c statement_timeout=2000', **conn_kwargs) as cur:
Aug 04 00:05:26 sks04db1 patroni[25358]: File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
Aug 04 00:05:26 sks04db1 patroni[25358]: return next(self.gen)
Aug 04 00:05:26 sks04db1 patroni[25358]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 43, in get_connection_cursor
Aug 04 00:05:26 sks04db1 patroni[25358]: conn = psycopg2.connect(**kwargs)
Aug 04 00:05:26 sks04db1 patroni[25358]: File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
Aug 04 00:05:26 sks04db1 patroni[25358]: conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Aug 04 00:05:26 sks04db1 patroni[25358]: psycopg2.OperationalError: server closed the connection unexpectedly
Aug 04 00:05:26 sks04db1 patroni[25358]: This probably means the server terminated abnormally
Aug 04 00:05:26 sks04db1 patroni[25358]: before or while processing the request.
Aug 04 00:05:26 sks04db1 patroni[25358]: 2023-08-04 00:05:26,932 ERROR: Failed to drop replication slot 'patroni'
Aug 04 00:05:26 sks04db1 patroni[25358]: 2023-08-04 00:05:26,932 INFO: no action. I am (sks04db167) the standby leader with the lock
Aug 04 00:05:36 sks04db1 patroni[25358]: 2023-08-04 00:05:36,908 INFO: Lock owner: sks04db167; I am sks04db167
Aug 04 00:05:36 sks04db1 patroni[25358]: 2023-08-04 00:05:36,914 INFO: Local timeline=45 lsn=53/EB0000A0
Aug 04 00:05:36 sks04db1 patroni[25358]: 2023-08-04 00:05:36,923 ERROR: Exception when working with leader
Aug 04 00:05:36 sks04db1 patroni[25358]: Traceback (most recent call last):
Aug 04 00:05:36 sks04db1 patroni[25358]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/rewind.py", line 60, in check_leader_is_not_in_recovery
Aug 04 00:05:36 sks04db1 patroni[25358]: with get_connection_cursor(connect_timeout=3, options='-c statement_timeout=2000', **conn_kwargs) as cur:
Aug 04 00:05:36 sks04db1 patroni[25358]: File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
Aug 04 00:05:36 sks04db1 patroni[25358]: return next(self.gen)
Aug 04 00:05:36 sks04db1 patroni[25358]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 43, in get_connection_cursor
Aug 04 00:05:36 sks04db1 patroni[25358]: conn = psycopg2.connect(**kwargs)
Aug 04 00:05:36 sks04db1 patroni[25358]: File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
Aug 04 00:05:36 sks04db1 patroni[25358]: conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Aug 04 00:05:36 sks04db1 patroni[25358]: psycopg2.OperationalError: server closed the connection unexpectedly
Aug 04 00:05:36 sks04db1 patroni[25358]: This probably means the server terminated abnormally
Aug 04 00:05:36 sks04db1 patroni[25358]: before or while processing the request.
Aug 04 00:05:36 sks04db1 patroni[25358]: 2023-08-04 00:05:36,925 ERROR: Failed to drop replication slot 'patroni'
Aug 04 00:05:36 sks04db1 patroni[25358]: 2023-08-04 00:05:36,925 INFO: no action. I am (sks04db167) the standby leader with the lock
Aug 04 00:05:46 sks04db1 patroni[25358]: 2023-08-04 00:05:46,908 INFO: Lock owner: sks04db167; I am sks04db167
Aug 04 00:05:46 sks04db1 patroni[25358]: 2023-08-04 00:05:46,918 INFO: Local timeline=45 lsn=53/EB0000A0
Aug 04 00:05:46 sks04db1 patroni[25358]: 2023-08-04 00:05:46,926 ERROR: Exception when working with leader
Aug 04 00:05:46 sks04db1 patroni[25358]: Traceback (most recent call last):
Aug 04 00:05:46 sks04db1 patroni[25358]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/rewind.py", line 60, in check_leader_is_not_in_recovery
Aug 04 00:05:46 sks04db1 patroni[25358]: with get_connection_cursor(connect_timeout=3, options='-c statement_timeout=2000', **conn_kwargs) as cur:
Aug 04 00:05:46 sks04db1 patroni[25358]: File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
Aug 04 00:05:46 sks04db1 patroni[25358]: return next(self.gen)
Aug 04 00:05:46 sks04db1 patroni[25358]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 43, in get_connection_cursor
Aug 04 00:05:46 sks04db1 patroni[25358]: conn = psycopg2.connect(**kwargs)
Aug 04 00:05:46 sks04db1 patroni[25358]: File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
Aug 04 00:05:46 sks04db1 patroni[25358]: conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Aug 04 00:05:46 sks04db1 patroni[25358]: psycopg2.OperationalError: server closed the connection unexpectedly
Aug 04 00:05:46 sks04db1 patroni[25358]: This probably means the server terminated abnormally
Aug 04 00:05:46 sks04db1 patroni[25358]: before or while processing the request.
Aug 04 00:05:46 sks04db1 patroni[25358]: 2023-08-04 00:05:46,927 ERROR: Failed to drop replication slot 'patroni'
Aug 04 00:05:46 sks04db1 patroni[25358]: 2023-08-04 00:05:46,928 INFO: no action. I am (sks04db167) the standby leader with the lock
Aug 04 00:05:56 sks04db1 patroni[25358]: 2023-08-04 00:05:56,909 INFO: Lock owner: sks04db167; I am sks04db167
Aug 04 00:05:56 sks04db1 patroni[25358]: 2023-08-04 00:05:56,914 WARNING: Could not activate Linux watchdog device: "Can't open watchdog device: [Errno 2] No such file or directory: '/dev/watchdog'"
Aug 04 00:05:56 sks04db1 patroni[25358]: 2023-08-04 00:05:56,918 INFO: promoted self to leader because I had the session lock
Aug 04 00:05:56 sks04db1 patroni[25358]: 2023-08-04 00:05:56,922 INFO: Changed max_connections from 1000 to 100 (restart might be required)
Aug 04 00:05:56 sks04db1 patroni[25358]: server promoting
Aug 04 00:05:56 sks04db1 patroni[25358]: 2023-08-04 00:05:56,925 INFO: Reloading PostgreSQL configuration.
Aug 04 00:05:56 sks04db1 patroni[25358]: 2023-08-04 00:05:56,927 INFO: cleared rewind state after becoming the leader
Aug 04 00:05:56 sks04db1 patroni[25358]: server signaled
Aug 04 00:05:57 sks04db1 patroni[25358]: 2023-08-04 00:05:57,962 INFO: no action. I am (sks04db167) the leader with the lock
Aug 04 00:05:57 sks04db1 patroni[25358]: 2023-08-04 00:05:57,990 INFO: no action. I am (sks04db167) the leader with the lock
Aug 04 00:06:07 sks04db1 patroni[25358]: 2023-08-04 00:06:07,989 INFO: no action. I am (sks04db167) the leader with the lock
```

### PostgreSQL log files

```shell
--
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by gsl23** [comment]
I haven't been able reproduce it on test environment yet. so... I'am going to upgrade version and look further. Anyway, thx!
