### ISSUE TITLE
Autofailover with combination synchronous_mode & async tag

### ISSUE THREAD

**Issue by glushakov** [zalando/patroni#2819]
### What happened?

Hi.
I am trying to build the following configuration:
- asynchronous replication (for maximum performance)
- only manual switchover (since data loss is unacceptable)

The combination of synchronous_mode=on and the nosync tag gives the desired result: patroni does not automatically switch roles, while manual switching is still possible - by removing tags.

But I found that this behavior is not in all cases.
I encountered a case where, due to running out of space on the leader, the node could not start after a crash and made demote:

2023-08-16 14:58:55,273 INFO: Lock owner: server_9; I am server_9
2023-08-16 14:58:59,952 INFO: Demoting self because primary startup is taking too long
2023-08-16 14:58:59,953 INFO: Demoting self (immediate)
2023-08-16 14:59:01,205 INFO: Leader key released
2023-08-16 14:59:03,211 INFO: stopped PostgreSQL because of startup timeout
2023-08-16 14:59:03,217 INFO: Lock owner: server_8; I am server_9

and released the leader's key.

After the key was released, the asynchronous replica (assuming the value of the maximum_lag_on_failover parameter, I believe) became the leader. Those, there was a failover with the loss of some last transactions:

2023-08-16 14:58:55,884 INFO: no action. I am (server_8), a secondary, and following a leader (server_9)
2023-08-16 14:59:01,433 INFO: Got response from server_9 http://server_9:8008/patroni: {"state": "stopped", "role": "demoted", "cluster_unlocked": true, " dcs_last_seen": 1692187135, "tags": {"nosync": true}, "database_system_identifier": "7264882610385059338", "patr
oni": {"version": "3.0.3", "scope": "server_8+server_9"}}
2023-08-16 14:59:01,434 WARNING: Request failed to server_9: GET http://server_9:8008/patroni('xlog')
2023-08-16 14:59:01,752 INFO: promoted self to leader by acquiring session lock
2023-08-16 14:59:01,861 INFO: cleared rewind state after becoming the leader
2023-08-16 14:59:03,490 INFO: no action. I am (server_8), the leader with the lock

Is this behavior not a bug?
If this is normal, then how to achieve the configuration that I need?
Perhaps I need to turn off the synchronous_mode and set nofailover tag?

### How can we reproduce it (as minimally and precisely as possible)?

enable synchronous_mode = true  and put tag nosync=true
Then simulate a long run of the primary to get the message "Demoting self because primary startup is taking too long"

### What did you expect to happen?

Patroni should not switch to a non-synchronous node

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.0.3
-   PostgreSQL version:  15.3
-   DCS (and its version): etcd 3.5.4

### Patroni configuration file

```yaml
scope: server_8+server_9
namespace: /service/
name: server_8

log:
  level: INFO
  format: '%(asctime)s %(levelname)s: %(message)s'
  dateformat: ''
  max_queue_size: 1000
  dir: /var/log/patroni
  file_num: 4
  file_size: 25000000

restapi:
  listen: 0.0.0.0:8008
  connect_address: server_8:8008
  authentication:
    username: patroni_rest
    password: pass

etcd3:
  hosts: etcd-cluster:2379
  protocol: http
  username: user
  password: pass

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    primary_start_timeout: 5
    primary_stop_timeout: 30
    synchronous_mode: true
    synchronous_mode_strict: false
    check_timeline: false
    failsafe_mode: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 300
        max_locks_per_transaction: 64
        max_worker_processes: 8
        max_prepared_transactions: 0
        wal_level: replica
        wal_log_hints: on
        track_commit_timestamp: off
        max_wal_senders: 10
        max_replication_slots: 10
        wal_keep_size: 2GB

postgresql:
  use_unix_socket: true
  listen: 0.0.0.0:5432
  connect_address: server_8:5432
  data_dir: /var/lib/pgpro/ent-15/data
  bin_dir: /opt/pgpro/ent-15/bin
  config_dir: /var/lib/pgpro/ent-15/data
  pgpass: /var/lib/pgsql/.pgpass
  authentication:
    superuser:
      username: postgres
      password: pass
    replication:
      username: replicator
      password: pass
    rewind:
      username: postgres
      password: pass
  callbacks:
    on_role_change: /var/lib/pgsql/scripts/patroni_switch.sh
  create_replica_methods:
    - basebackup
  basebackup:
    checkpoint: fast
  parameters:
    unix_socket_directories: /var/run/postgresql, /tmp
  pg_hba:
    - local all postgres  peer
    - host all +hba_local_auth 0.0.0.0/0 scram-sha-256
    - host replication replicator 0.0.0.0/0 scram-sha-256
  pg_ctl_timeout: 60
  remove_data_directory_on_rewind_failure: false
  remove_data_directory_on_diverged_timelines: false

watchdog:
  mode: off

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: true
```

### patronictl show-config

```yaml
check_timeline: false
failsafe_mode: false
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    max_connections: 300
    max_locks_per_transaction: 64
    max_prepared_transactions: 0
    max_replication_slots: 10
    max_wal_senders: 10
    max_worker_processes: 8
    track_commit_timestamp: false
    wal_keep_size: 2GB
    wal_level: replica
    wal_log_hints: true
  use_pg_rewind: true
  use_slots: true
primary_start_timeout: 5
primary_stop_timeout: 30
retry_timeout: 10
synchronous_mode: true
synchronous_mode_strict: false
ttl: 30
```

### Patroni log files

```shell
server_9

2023-08-16 14:58:15,396 INFO: no action. I am (server_9), the leader with the lock
2023-08-16 14:58:25,351 INFO: no action. I am (server_9), the leader with the lock
2023-08-16 14:58:35,261 INFO: Lock owner: server_9; I am server_9
2023-08-16 14:58:36,470 INFO: establishing a new patroni connection to the postgres cluster
2023-08-16 14:58:37,852 WARNING: Retry got exception: connection problems
2023-08-16 14:58:43,323 WARNING: Failed to determine PostgreSQL state from the connection, falling back to cached role
2023-08-16 14:58:43,324 ERROR: Exception when called state_handler.last_operation()
Traceback (most recent call last):
  File "/var/lib/pgsql/patroni_venv/lib64/python3.6/site-packages/patroni/ha.py", line 238, in update_lock
    last_lsn = self.state_handler.last_operation()
  File "/var/lib/pgsql/patroni_venv/lib64/python3.6/site-packages/patroni/postgresql/__init__.py", line 1163, in last_operation
    return self._wal_position(self.is_leader(), self._cluster_info_state_get('wal_position') or 0,
  File "/var/lib/pgsql/patroni_venv/lib64/python3.6/site-packages/patroni/postgresql/__init__.py", line 441, in _cluster_info_state_get
    raise PostgresConnectionException(self._cluster_info_state['error'])
patroni.exceptions.PostgresConnectionException: Too many retry attempts
2023-08-16 14:58:44,849 WARNING: Failed to determine PostgreSQL state from the connection, falling back to cached role
2023-08-16 14:58:45,134 INFO: Error communicating with PostgreSQL. Will try again later
2023-08-16 14:58:45,326 INFO: Lock owner: server_9; I am server_9
2023-08-16 14:58:45,497 INFO: establishing a new patroni connection to the postgres cluster
2023-08-16 14:58:45,861 INFO: establishing a new patroni connection to the postgres cluster
2023-08-16 14:58:45,863 WARNING: Retry got exception: connection problems
2023-08-16 14:58:45,863 INFO: PostgreSQL is still starting up, 3 seconds until timeout
2023-08-16 14:58:59,925 INFO: Got response from server_8 http://server_8:8008/patroni: {"state": "running", "postmaster_start_time": "2023-08-09 15:28:53.682138+03:00", "role": "replica", "server_version": 150003, "xlog": {"received_location": 4926620632, "replayed_
location": 4926620632, "replayed_timestamp": "2023-08-16 14:55:23.489790+03:00", "paused": false}, "timeline": 4, "dcs_last_seen": 1692187135, "tags": {"nosync": true}, "database_system_identifier": "7264882610385059338", "patroni": {"version": "3.0.3", "scope": "server_8+
server_9"}}
2023-08-16 14:58:55,273 INFO: Lock owner: server_9; I am server_9
2023-08-16 14:58:59,952 INFO: Demoting self because primary startup is taking too long
2023-08-16 14:58:59,953 INFO: Demoting self (immediate)
2023-08-16 14:59:01,205 INFO: Leader key released
2023-08-16 14:59:03,211 INFO: stopped PostgreSQL because of startup timeout
2023-08-16 14:59:03,217 INFO: Lock owner: server_8; I am server_9
2023-08-16 14:59:03,217 INFO: starting after demotion in progress
2023-08-16 14:59:04,762 INFO: postmaster pid=811893
2023-08-16 14:59:05,157 INFO: Lock owner: server_8; I am server_9

server_8

2023-08-16 14:58:35,863 INFO: no action. I am (server_8), a secondary, and following a leader (server_9)
2023-08-16 14:58:46,296 INFO: no action. I am (server_8), a secondary, and following a leader (server_9)
2023-08-16 14:58:55,884 INFO: no action. I am (server_8), a secondary, and following a leader (server_9)
2023-08-16 14:59:01,433 INFO: Got response from server_9 http://server_9:8008/patroni: {"state": "stopped", "role": "demoted", "cluster_unlocked": true, "dcs_last_seen": 1692187135, "tags": {"nosync": true}, "database_system_identifier": "7264882610385059338", "patr
oni": {"version": "3.0.3", "scope": "server_8+server_9"}}
2023-08-16 14:59:01,434 WARNING: Request failed to server_9: GET http://server_9:8008/patroni ('xlog')
2023-08-16 14:59:01,752 INFO: promoted self to leader by acquiring session lock
2023-08-16 14:59:01,861 INFO: cleared rewind state after becoming the leader
2023-08-16 14:59:03,490 INFO: no action. I am (server_8), the leader with the lock
2023-08-16 14:59:05,186 INFO: no action. I am (server_8), the leader with the lock
2023-08-16 14:59:15,155 INFO: no action. I am (server_8), the leader with the lock
```

### PostgreSQL log files

```shell
server_8
2023-08-16 14:58:28.649 MSK    35786  0 FATAL:  could not receive data from WAL stream: SSL SYSCALL error: EOF detected
2023-08-16 14:58:28.665 MSK    3883934  0 LOG:  invalid record length at 1/25A643D8: wanted 28, got 0
2023-08-16 14:58:28.856 MSK    207629  0 FATAL:  could not connect to the primary server: connection to server at "server_9" (10.243.88.39), port 5432 failed: FATAL:  the database system is in recovery mode
2023-08-16 14:58:28.856 MSK    3883934  0 LOG:  waiting for WAL to become available at 1/25A643F4
2023-08-16 14:58:34.124 MSK    207640  0 FATAL:  could not connect to the primary server: connection to server at "server_9" (10.243.88.39), port 5432 failed: FATAL:  the database system is not yet accepting connections
        DETAIL:  Consistent recovery state has not been yet reached.
2023-08-16 14:58:34.125 MSK    3883934  0 LOG:  waiting for WAL to become available at 1/25A643F4
2023-08-16 14:58:38.753 MSK    207643  0 FATAL:  could not connect to the primary server: connection to server at "server_9" (10.243.88.39), port 5432 failed: FATAL:  the database system is not yet accepting connections
        DETAIL:  Consistent recovery state has not been yet reached.
2023-08-16 14:58:38.753 MSK    3883934  0 LOG:  waiting for WAL to become available at 1/25A643F4
2023-08-16 14:58:43.688 MSK    207647  0 FATAL:  could not connect to the primary server: connection to server at "server_9" (10.243.88.39), port 5432 failed: FATAL:  the database system is not yet accepting connections
        DETAIL:  Consistent recovery state has not been yet reached.
2023-08-16 14:58:43.689 MSK    3883934  0 LOG:  waiting for WAL to become available at 1/25A643F4
2023-08-16 14:58:46.036 MSK [unknown] 127.0.0.1 [unknown] 207659  0 LOG:  connection received: host=127.0.0.1 port=60150
2023-08-16 14:58:46.241 MSK replicator 127.0.0.1 [unknown] 207659 authentication -7456000653993628242 LOG:  connection authenticated: identity="replicator" method=scram-sha-256 (/var/lib/pgpro/ent-15/data/pg_hba.conf:6)
2023-08-16 14:58:46.241 MSK replicator 127.0.0.1 [unknown] 207659 authentication -7456000653993628242 LOG:  replication connection authorized: user=replicator SSL enabled (protocol=TLSv1.3, cipher=TLS_AES_256_GCM_SHA384, bits=256)
2023-08-16 14:58:46.252 MSK replicator 127.0.0.1 [unknown] 207659 idle 0 LOG:  disconnection: session time: 0:00:00.217 user=replicator database= host=127.0.0.1 port=60150
2023-08-16 14:58:48.783 MSK    207660  0 FATAL:  could not connect to the primary server: connection to server at "server_9" (10.243.88.39), port 5432 failed: FATAL:  the database system is not yet accepting connections
        DETAIL:  Consistent recovery state has not been yet reached.
2023-08-16 14:58:48.784 MSK    3883934  0 LOG:  waiting for WAL to become available at 1/25A643F4
2023-08-16 14:58:53.692 MSK    207668  0 FATAL:  could not connect to the primary server: connection to server at "server_9" (10.243.88.39), port 5432 failed: FATAL:  the database system is not yet accepting connections
        DETAIL:  Consistent recovery state has not been yet reached.
2023-08-16 14:58:53.693 MSK    3883934  0 LOG:  waiting for WAL to become available at 1/25A643F4
2023-08-16 14:58:55.883 MSK replicator 127.0.0.1 [unknown] 207670 authentication 0 LOG:  connection authenticated: identity="replicator" method=scram-sha-256 (/var/lib/pgpro/ent-15/data/pg_hba.conf:6)
2023-08-16 14:58:55.883 MSK replicator 127.0.0.1 [unknown] 207670 authentication 0 LOG:  replication connection authorized: user=replicator SSL enabled (protocol=TLSv1.3, cipher=TLS_AES_256_GCM_SHA384, bits=256)
2023-08-16 14:58:55.884 MSK replicator 127.0.0.1 [unknown] 207670 idle 0 LOG:  disconnection: session time: 0:00:00.018 user=replicator database= host=127.0.0.1 port=54082
2023-08-16 14:58:59.005 MSK    207673  0 FATAL:  could not connect to the primary server: connection to server at "server_9" (10.243.88.39), port 5432 failed: FATAL:  the database system is not yet accepting connections
        DETAIL:  Consistent recovery state has not been yet reached.
2023-08-16 14:58:59.006 MSK    3883934  0 LOG:  waiting for WAL to become available at 1/25A643F4
2023-08-16 14:58:59.798 MSK [unknown] 127.0.0.1 [unknown] 207675  0 LOG:  connection received: host=127.0.0.1 port=54092
2023-08-16 14:58:59.818 MSK replicator 127.0.0.1 [unknown] 207675 authentication 0 LOG:  connection authenticated: identity="replicator" method=scram-sha-256 (/var/lib/pgpro/ent-15/data/pg_hba.conf:6)
2023-08-16 14:58:59.818 MSK replicator 127.0.0.1 [unknown] 207675 authentication 0 LOG:  replication connection authorized: user=replicator SSL enabled (protocol=TLSv1.3, cipher=TLS_AES_256_GCM_SHA384, bits=256)
2023-08-16 14:58:59.819 MSK replicator 127.0.0.1 [unknown] 207675 idle 0 LOG:  disconnection: session time: 0:00:00.021 user=replicator database= host=127.0.0.1 port=54092
2023-08-16 14:59:01.860 MSK    3883934  0 LOG:  received promote request
2023-08-16 14:59:01.901 MSK    3883934  0 LOG:  redo done at 1/25A64390 system usage: CPU: user: 25.27 s, system: 30.09 s, elapsed: 603008.08 s
2023-08-16 14:59:01.909 MSK    3883934  0 LOG:  last completed transaction was at log time 2023-08-16 14:55:23.48979+03
2023-08-16 14:59:01.910 MSK    3883934  0 LOG:  selected new timeline ID: 5
2023-08-16 14:59:01.991 MSK    3883934  0 LOG:  archive recovery complete
2023-08-16 14:59:02.134 MSK    3883929  0 LOG:  database system is ready to accept connections


server_9

2023-08-16 14:58:53.691 MSK replicator 10.242.226.55 [unknown] 811844  0 FATAL:  the database system is not yet accepting connections
2023-08-16 14:58:53.691 MSK replicator 10.242.226.55 [unknown] 811844  0 DETAIL:  Consistent recovery state has not been yet reached.
2023-08-16 14:58:55.270 MSK [unknown] [local] [unknown] 811848  0 LOG:  connection received: host=[local]
2023-08-16 14:58:55.270 MSK postgres [local] postgres 811848  0 FATAL:  the database system is not yet accepting connections
2023-08-16 14:58:55.270 MSK postgres [local] postgres 811848  0 DETAIL:  Consistent recovery state has not been yet reached.
2023-08-16 14:58:58.849 MSK    811783  0 LOG:  redo in progress, elapsed time: 30.00 s, current LSN: 0/C2F98E38
2023-08-16 14:58:58.902 MSK [unknown] 10.242.226.55 [unknown] 811855  0 LOG:  connection received: host=10.242.226.55 port=52420
2023-08-16 14:58:59.004 MSK replicator 10.242.226.55 [unknown] 811855  0 FATAL:  the database system is not yet accepting connections
2023-08-16 14:58:59.004 MSK replicator 10.242.226.55 [unknown] 811855  0 DETAIL:  Consistent recovery state has not been yet reached.
2023-08-16 14:59:00.848 MSK    330981  0 LOG:  received immediate shutdown request
2023-08-16 14:59:00.991 MSK    330981  0 LOG:  could not write file "pg_stat/pg_stat_statements.stat.tmp": No such file or directory
2023-08-16 14:59:01.076 MSK    330981  0 LOG:  database system is shut down
2023-08-16 14:59:04.854 MSK    811893  0 LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5), 64-bit
2023-08-16 14:59:04.854 MSK    811893  0 LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-08-16 14:59:04.855 MSK    811893  0 LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-08-16 14:59:04.858 MSK    811893  0 LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-08-16 14:59:04.863 MSK    811898  0 LOG:  database system was interrupted while in recovery at 2023-08-16 14:58:28 MSK
2023-08-16 14:59:04.863 MSK    811898  0 HINT:  This probably means that some data is corrupted and you will have to use the last backup for recovery.
2023-08-16 14:59:04.938 MSK    811898  0 LOG:  entering standby mode
2023-08-16 14:59:04.952 MSK    811898  0 LOG:  database system was not properly shut down; automatic recovery in progress
2023-08-16 14:59:04.956 MSK    811898  0 LOG:  redo starts at 0/7683F978
2023-08-16 14:59:04.957 MSK    811898  0 LOG:  Start 1 background garbage collection workers for CFS
2023-08-16 14:59:04.959 MSK    811898  0 WARNING:  could not open directory "base/24602": No such file or directory
2023-08-16 14:59:04.959 MSK    811898  0 CONTEXT:  WAL redo at 0/7683FA60 for Database/DROP: dir 1663/24602
2023-08-16 14:59:04.959 MSK    811898  0 WARNING:  some useless files may be left behind in old database directory "base/24602"
2023-08-16 14:59:04.959 MSK    811898  0 CONTEXT:  WAL redo at 0/7683FA60 for Database/DROP: dir 1663/24602
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by CyberDem0n** [comment]
> Patroni version: 3.0.3

Please try to reproduce it with the latest version (as the issue template says).

**Comment by glushakov** [comment]
Thank.
I will try to reproduce on the new version. It doesn't work the first time
