### ISSUE TITLE
Patroni crashes during shutdown in Kubernetes environment - crashing PostgreSQL as well

### ISSUE THREAD

**Issue by feikesteenbergen** [zalando/patroni#2837]
### What happened?

During the shutdown of a Pod, Patroni crashes:

```
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 1127, in _write_status
    raise NotImplementedError  # pragma: no cover
NotImplementedError

```

### How can we reproduce it (as minimally and precisely as possible)?

Shutdown a pod while using Kubernetes as a DCS

### What did you expect to happen?

Patroni waiting for PostgreSQL to shutdown and then to shutdown itself

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.0.4
-   PostgreSQL version: 15.4
-   DCS (and its version):  Kubernetes v1.25.10

### Patroni configuration file

```yaml
NA
```

### patronictl show-config

```yaml
NA
```

### Patroni log files

```shell
2023-08-30 13:23:45,586 WARNING: manual failover: members list is empty
2023-08-30 13:23:45,587 ERROR: Exception during Ha.shutdown
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/daemon.py", line 174, in abstract_main
    controller.run()
  File "/usr/lib/python3/dist-packages/patroni/__main__.py", line 133, in run
    super(Patroni, self).run()
  File "/usr/lib/python3/dist-packages/patroni/daemon.py", line 143, in run
    self._run_cycle()
  File "/usr/lib/python3/dist-packages/patroni/__main__.py", line 145, in _run_cycle
    self.schedule_next_run()
  File "/usr/lib/python3/dist-packages/patroni/__main__.py", line 127, in schedule_next_run
    elif self.ha.watch(nap_time):
  File "/usr/lib/python3/dist-packages/patroni/ha.py", line 1885, in watch
    return self.dcs.watch(leader_version, timeout)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 1357, in watch
    return super(Kubernetes, self).watch(None, timeout)
  File "/usr/lib/python3/dist-packages/patroni/dcs/__init__.py", line 1134, in watch
    self.event.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
  File "/usr/lib/python3/dist-packages/patroni/daemon.py", line 90, in sigterm_handler
    sys.exit()
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/__main__.py", line 153, in _shutdown
    self.ha.shutdown()
  File "/usr/lib/python3/dist-packages/patroni/ha.py", line 1862, in shutdown
    self.while_not_sync_standby(lambda: self.state_handler.stop(checkpoint=False, on_safepoint=disable_wd,
  File "/usr/lib/python3/dist-packages/patroni/ha.py", line 677, in while_not_sync_standby
    return func()
  File "/usr/lib/python3/dist-packages/patroni/ha.py", line 1862, in <lambda>
    self.while_not_sync_standby(lambda: self.state_handler.stop(checkpoint=False, on_safepoint=disable_wd,
  File "/usr/lib/python3/dist-packages/patroni/postgresql/__init__.py", line 773, in stop
    success, pg_signaled = self._do_stop(mode, block_callbacks, checkpoint, on_safepoint,
  File "/usr/lib/python3/dist-packages/patroni/postgresql/__init__.py", line 828, in _do_stop
    on_shutdown(self.latest_checkpoint_location())
  File "/usr/lib/python3/dist-packages/patroni/ha.py", line 1855, in _on_shutdown
    self.dcs.write_leader_optime(checkpoint_location)
  File "/usr/lib/python3/dist-packages/patroni/dcs/__init__.py", line 936, in write_leader_optime
    self.write_status({self._OPTIME: last_lsn})
  File "/usr/lib/python3/dist-packages/patroni/dcs/__init__.py", line 946, in write_status
    if not deep_compare(self._last_status, value) and self._write_status(json.dumps(value, separators=(',', ':'))):
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 1127, in _write_status
    raise NotImplementedError  # pragma: no cover
NotImplementedError
```

### PostgreSQL log files

```shell
NA
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

In commit [76b3b99d](https://github.com/zalando/patroni/commit/76b3b99de) this function changed its behavior from a noop to NotImplementedError

**Comment by feikesteenbergen** [comment]
The linked PR does resolve the issue for us - however I'm not sure if we should make it a noop or if something else needs to be done here, thoughts?
