### ISSUE TITLE
patroni v3.2.0 docker standalone build  - failover/postgres restart does not work

### ISSUE THREAD

**Issue by jwhang22** [zalando/patroni#2941]
### What happened?

Downloaded latest zip file (v3.2.0)
Built docker containers for standalone patroni  ( docker build -t patroni . ) on windows 10 (docker desktop).
docker-compose up -d

logged onto master patroni/postgres container and issued shutdown for postgres

pg_ctl -D /home/postgres/data stop

After the master postgres was shutdown, log output from patroni produces this error (in the log output)  and this continues in endless loop.  No failover or restart of postgres on primary occurs.

### How can we reproduce it (as minimally and precisely as possible)?

Yes just download the zip, and build docker container

### What did you expect to happen?

patroni should restart postgres on primary

### Patroni/PostgreSQL/DCS version

-   Patroni version: 
-   PostgreSQL version: 
-   DCS (and its version): 

### Patroni configuration file

```yaml
same as in the docker demo
```

### patronictl show-config

```yaml
same as in docker demo
```

### Patroni log files

```shell
2023-11-06 20:46:42,663 INFO: no action. I am (patroni1), the leader with the lock
2023-11-06 20:46:52,662 INFO: no action. I am (patroni1), the leader with the lock
2023-11-06 20:47:02,660 INFO: no action. I am (patroni1), the leader with the lock
2023-11-06 20:47:12,660 INFO: no action. I am (patroni1), the leader with the lock
2023-11-06 20:47:22,663 INFO: no action. I am (patroni1), the leader with the lock
2023-11-06 20:47:32,659 INFO: no action. I am (patroni1), the leader with the lock
2023-11-06 20:47:42,610 INFO: Lock owner: patroni1; I am patroni1
2023-11-06 20:47:42,881 INFO: establishing a new patroni heartbeat connection to postgres
2023-11-06 20:47:42,881 WARNING: Retry got exception: connection problems
localhost:5432 - no response
2023-11-06 20:47:42,891 WARNING: Failed to determine PostgreSQL state from the connection, falling back to cached role
2023-11-06 20:47:42,892 ERROR: Exception when called state_handler.last_operation()
Traceback (most recent call last):
  File "/patroni/ha.py", line 279, in update_lock
    last_lsn = self.state_handler.last_operation()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/patroni/postgresql/__init__.py", line 1227, in last_operation
    return self._wal_position(self.is_primary(), self._cluster_info_state_get('wal_position') or 0,
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/patroni/postgresql/__init__.py", line 483, in _cluster_info_state_get
    raise PostgresConnectionException(self._cluster_info_state['error'])
patroni.exceptions.PostgresConnectionException: Too many retry attempts
2023-11-06 20:47:42,956 WARNING: Failed to determine PostgreSQL state from the connection, falling back to cached role
2023-11-06 20:47:43,014 INFO: Error communicating with PostgreSQL. Will try again later
```

### PostgreSQL log files

```shell
Not needed, just shutdown postgres on primary
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by jwhang22** [comment]
My mistake, I updated the docker image with some additional packages and that seem to have produced this issue.  On the original image, postgres restart works fine.
