### ISSUE TITLE
Consul service checks failing when TLS is enabled on Patroni Rest API 

### ISSUE THREAD

**Issue by ponvenkates** [zalando/patroni#3009]
### What happened?

I have configured TLS on Patroni Rest API and it works fine. But when I enable consul register_service, the check is failing continuously (attached screenshot).
<img width="1315" alt="Screenshot 2024-01-17 at 1 21 17 AM" src="https://github.com/zalando/patroni/assets/62520272/b5104152-cf38-40dd-afc6-3c3dcbe75225">

In Patroni logs, i see bad certificate error.
```
Exception in thread Thread-13 (process_request_thread):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/site-packages/patroni/api.py", line 1631, in process_request_thread
    request.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1007)
```

Once i set register service to `false` the error disappeared.

### How can we reproduce it (as minimally and precisely as possible)?

1. Enable TLS on REST API by configuring the certificates
2. Enable register service in consul to true.
3. Verify the service health in consul.

### What did you expect to happen?

1. Service checks should pass
2. Service should turn healthy.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.1.2
-   PostgreSQL version: 13.12.0
-   DCS (and its version): consul (15.2)

### Patroni configuration file

```yaml
bootstrap:
  initdb:
  - encoding: UTF8
  - data-checksums

  post_init: /post_init.sh

  pg_hba:
  - host all all 0.0.0.0/0 md5
  - local all all    md5

consul:
  service_tags: ['node-2']

postgresql:
  _comment: postgres settings
  

log:
  _comment: Log configuration
  level: INFO
  traceback_level: ERROR
```

### patronictl show-config

```yaml
check_timeline: true
failsafe_mode: true
log:
  level: INFO
loop_wait: 10
master_start_timeout: 60
maximum_lag_on_failover: 1048576
pg_hba:
- local all all    md5
- host all all 0.0.0.0/0 md5
postgresql:
  parameters:
    max_connections: 150
    max_replication_slots: 5
    max_wal_senders: 20
    max_worker_processes: 1
    unix_socket_directories: /tmp
    wal_keep_segments: 512
    wal_level: logical
  pg_hba:
  - local all all    md5
  - host all all 0.0.0.0/0 md5
  remove_data_directory_on_diverged_timelines: true
  remove_data_directory_on_rewind_failure: true
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
ttl: 30
```

### Patroni log files

```shell
Exception in thread Thread-13 (process_request_thread):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/site-packages/patroni/api.py", line 1631, in process_request_thread
    request.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1007)
```

### PostgreSQL log files

```shell
Irrelevant
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by CyberDem0n** [comment]
Consul can't use client certificates for health check requests.
That's not a Patroni problem.

**Comment by ponvenkates** [comment]
@CyberDem0n But as per the documentation if PATRONI_REST_API_VERIFY_CLIENTS is set to 'none', Patroni shouldn't fail any requests with "bad certificate" error. Isn't that right?

**Comment by CyberDem0n** [comment]
@ponvenkates there is nothing in your original message explaining how you configured `restapi`.

**Comment by ponvenkates** [comment]
Sorry about that. I have configured the api using environment variables.
```
PATRONI_RESTAPI_CONNECT_ADDRESS="Node IP:8008"
PATRONI_RESTAPI_LISTEN="0.0.0.0:8008"
PATRONI_RESTAPI_USERNAME="admin"
PATRONI_RESTAPI_PASSWORD="admin password"
PATRONI_RESTAPI_CERTFILE="server cert file location"
PATRONI_RESTAPI_KEYFILE="server key file location"
PATRONI_RESTAPI_CAFILE="root cert file location"
```
`PATRONI_RESTAPI_VERIFY_CLIENT` is not set leaving it to default 'none' as per the document.

**Comment by CyberDem0n** [comment]
This error could be an indicator that something is wrong with certificates (which is again not a Patroni problem).
Please try to access Patroni REST API with `curl -k` and see if it works.

**Comment by Debsu2020** [comment]
Is there a solution to this, because I ran into the same problem myself and I don't know how to get Patron and Consul to work together?

I have tested with curl (`curl https://pgs3:8008/cluster --cacert /var/lib/postgresql/ssl/patroni-ca.pem --cert /var/lib/postgresql/ssl/patroni-ctl-pgs1.pem --key /var/lib/postgresql/ssl/patroni-ctl-pgs1.key | jq .`) that the certificates are working. So I don't understand why consul.register_service: true causes the error:
```
Sep 26 20:17:02 pgs1.doma.in patroni[262545]: Exception in thread Thread-7 (process_request_thread):
Sep 26 20:17:02 pgs1.doma.in patroni[262545]: Traceback (most recent call last):
Sep 26 20:17:02 pgs1.doma.in patroni[262545]:   File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
Sep 26 20:17:02 pgs1.doma.in patroni[262545]:     self.run()
Sep 26 20:17:02 pgs1.doma.in patroni[262545]:   File "/usr/lib/python3.12/threading.py", line 1010, in run
Sep 26 20:17:02 pgs1.doma.in patroni[262545]:     self._target(*self._args, **self._kwargs)
Sep 26 20:17:02 pgs1.doma.in patroni[262545]:   File "/usr/lib/python3/dist-packages/patroni/api.py", line 1703, in process_request_thread
Sep 26 20:17:02 pgs1.doma.in patroni[262545]:     request.do_handshake()
Sep 26 20:17:02 pgs1.doma.in patroni[262545]:   File "/usr/lib/python3.12/ssl.py", line 1320, in do_handshake
Sep 26 20:17:02 pgs1.doma.in patroni[262545]:     self._sslobj.do_handshake()
Sep 26 20:17:02 pgs1.doma.in patroni[262545]: ssl.SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1000)
``` 
in Patroni's log.

My Patroni config looks like this:
```
scope: postgresql-cluster
name: pgs1

log:
  level: DEBUG
  dir: /var/lib/postgresql

restapi:
  listen: 0.0.0.0:8008
  connect_address: 192.168.88.25:8008
  certfile: /var/lib/postgresql/ssl/patroni-rest-api-pgs1.pem
  keyfile: /var/lib/postgresql/ssl/patroni-rest-api-pgs1.key
  cafile: /var/lib/postgresql/ssl/patroni-ca.pem
  verify_client: required

ctl:
  cacert: /var/lib/postgresql/ssl/patroni-ca.pem
  certfile: /var/lib/postgresql/ssl/patroni-ctl-pgs1.pem
  keyfile: /var/lib/postgresql/ssl/patroni-ctl-pgs1.key
  insecure: false

consul:
  url: https://127.0.0.1:8501
  verify: true
  cacert: /var/lib/postgresql/ssl/consul-agent-ca.pem
  cert: /var/lib/postgresql/ssl/consul-client-pgs1-cert.pem
  key: /var/lib/postgresql/ssl/consul-client-pgs1-key.pem
  register_service: true
  dc: home-dc
  service_tags:
    - traefik.enable=true
    - traefik.tcp.routers.pgsql.rule=HostSNI(`*`)
    - traefik.tcp.routers.pgsql.entrypoints=postgres
    - traefik.tcp.services.pgsql.loadbalancer.server.port=5432

bootstrap:
  dcs:
    ttl: 2
    loop_wait: 1
    retry_timeout: 5
    maximum_lag_on_failover: 1048576
    postgresql:
      parameters:
        ssl: 'on'
        ssl_ca_file: /var/lib/postgresql/ssl/patroni-ca.pem
        ssl_cert_file: /var/lib/postgresql/ssl/server.pem
        ssl_key_file: /var/lib/postgresql/ssl/server.key
        max_connections: 100
        shared_buffers: 256MB
        wal_level: replica
        hot_standby: "on"
        wal_keep_size: 64
        max_wal_senders: 10
        max_replication_slots: 10
        logging_collector: 'on'
        log_directory: 'pg_log'
        log_filename: 'postgresql-%Y-%m-%d_%H%M%S.log'
        log_min_messages: debug1
      pg_hba:
        - hostssl replication pgrepl 127.0.0.1/32 md5
        - hostssl replication pgrepl 192.168.88.25/24 md5
        - hostssl replication pgrepl 192.168.88.26/24 md5
        - hostssl replication pgrepl 192.168.88.27/24 md5
        - hostssl all all 127.0.0.1/32 md5
        - hostssl all all 0.0.0.0/0 md5
        - local all postgres peer
  initdb:
    - encoding: UTF8
    - locale: en_US.UTF-8
    - data-checksums
  users:
    pgadmin:
      password: <password>
      options:
        - superuser
        - createdb
        - createrole
    pgrepl:
      password: <password>
      options:
        - replication

postgresql:
  listen: 0.0.0.0:5432
  connect_address: 192.168.88.25:5432
  data_dir: /var/lib/postgresql/data
  bin_dir: /usr/lib/postgresql/18/bin
  authentication:
    replication:
      username: pgrepl
      password: <password>
    superuser:
      username: pgadmin
      password: <password>

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
```
