### ISSUE TITLE
patronictl does not work

### ISSUE THREAD

**Issue by w82hands** [zalando/patroni#3044]
### What happened?

root@test3:/var/lib/etcd# curl -L -s http://127.0.0.1:2379/v3/cluster/member/list -X POST -d '{"linearizable": false}'
{"header":{"cluster_id":"17243073253266288807","member_id":"8566525623458610712","raft_term":"3"},"members":[{"ID":"3999207482736318397","name":"test2","peerURLs":["http://test2:2380"],"clientURLs":["http://test2:2379"]},{"ID":"4070719285396200202","name":"test","peerURLs":["http://test1:2380"],"clientURLs":["http://test1:2379"]},{"ID":"8566525623458610712","name":"test3","peerURLs":["http://test3:2380"],"clientURLs":["http://test3:2379"]}]}root@test3:/var/lib/etcd# curl -L -s http://127.0.0.1:2379/v2/cluster/member/list -X POST -d '{"linearizable": false}'
404 page not found

Patronictl stopped working after the etcd update, etcd is still working and responding to v3. The cluster itself is also running, there is no way to manage it.

### How can we reproduce it (as minimally and precisely as possible)?

upgrade etcd from 3.2 to 3.5

### What did you expect to happen?

patronictl list test 
and to make it work

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.2.2
-   PostgreSQL version: 16-ent-pro
-   DCS (and its version): etcd 3.5.12
- API version 3.5 

### Patroni configuration file

```yaml
scope: test
name: test1

restapi:
  listen: 0.0.0.0:8008
  connect_address: test1:8008
  authentication:
    username: test
    password: 'test'

log:
  format: '%(asctime)s %(levelname)s: %(message)s'
  level: WARNING
  level: DEBUG
  max_queue_size: 1000
  traceback_level: ERROR
  dir: /var/log/patroni

backend:
  type: etcd3

etcd3:
    hosts: test1:2379,test2:2379,test3:2379
    username: test
    password: 'test'

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
#    master_start_timeout: 300
#    synchronous_mode: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: replica
        hot_standby: "on"
        logging_collector: 'on'
        max_wal_senders: 5
        max_replication_slots: 5
        wal_log_hints: "on"
        checkpoint_timeout: 30
        #archive_mode: "on"
        #archive_timeout: 600
        #archive_command: "cp -f %p /home/postgres/archived/%f"
        #recovery_conf:
        #restore_command: cp /home/postgres/archived/%f %p

  # some desired options for 'initdb'
    initdb:
    - auth-host: md5
    - auth-local: peer
    - encoding: UTF8
    - data-checksums
    - locale: ru_RU.UTF-8
    - tune: 1c

  pg_hba:  # Добавьте следующие строки в pg_hba.conf после запуска 'initdb'
  - host replication replicator 10.14.100.243/24 md5
  - host replication replicator 127.0.0.1/32 trust
  - host all all 10.14.100.243/24 md5
  - host all all 10.14.100.244/24 md5
  - host all all 10.14.100.245/24 md5
  - host all all 10.14.100.125/24 md5
  - host all all 10.14.100.126/24 md5
  - host all all 10.14.100.128/24 md5
  - host all all 10.2.4.75/24 md5
  - host all all 0.0.0.0/0 md5
#  - hostssl all all 0.0.0.0/0 md5

# Дополнительный скрипт, который будет запущен после первоначального создания кластера (в качестве параметра будет передан URL подключения)
# post_init: /usr/local/bin/setup_cluster.sh
 # Несколько дополнительных пользователей, которые необходимо создать после инициализации новых
пользователей кластера:
  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb

postgresql:
  listen: 0.0.0.0:5432
  connect_address: test1:5432
  data_dir: "/var/lib/pgpro/ent-16/data"
  bin_dir: "/opt/pgpro/ent-16/bin"
#  config_dir:
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: 
    superuser:
      username: postgres
      password: 
  parameters:
    unix_socket_directories: '/var/run/pgpro'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

### patronictl show-config

```yaml
patronictl show-config
Error: Can not find suitable configuration of distributed configuration store
Available implementations: etcd, etcd3, kubernetes
```

### Patroni log files

```shell
DEBUG: API thread: 10.14.100.97 - - "GET /master HTTP/1.0" 503 - latency: 2.198 ms
2024-04-05 15:30:33,925 WARNING: Exception happened during processing of request from 10.14.100.97:57736
2024-04-05 15:30:33,925 WARNING: Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.7/dist-packages/patroni/api.py", line 105, in __init__
    super(RestApiHandler, self).__init__(request, client_address, server)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/dist-packages/patroni/api.py", line 1338, in handle_one_request
    BaseHTTPRequestHandler.handle_one_request(self)
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/usr/local/lib/python3.7/dist-packages/patroni/api.py", line 372, in do_GET
    self._write_status_response(status_code, response)
  File "/usr/local/lib/python3.7/dist-packages/patroni/api.py", line 218, in _write_status_response
    self._write_json_response(status_code, response)
  File "/usr/local/lib/python3.7/dist-packages/patroni/api.py", line 167, in _write_json_response
    self.write_response(status_code, json.dumps(response, default=str), content_type='application/json')
  File "/usr/local/lib/python3.7/dist-packages/patroni/api.py", line 157, in write_response
    self.wfile.write(body.encode('utf-8'))
  File "/usr/lib/python3.7/socketserver.py", line 799, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer

2024-04-05 15:30:42,184 DEBUG: API thread: 10.14.100.251 - - "GET /master HTTP/1.0" 503 - latency: 1.936 ms
2024-04-05 15:30:43,301 INFO: Lock owner: test1; I am test3
2024-04-05 15:30:43,302 DEBUG: does not have lock
2024-04-05 15:30:43,304 INFO: no action. I am (test3), a secondary, and following a leader (test1)
2024-04-05 15:30:43,928 DEBUG: API thread: 10.14.100.97 - - "GET /master HTTP/1.0" 503 - latency: 1.789 ms
2024-04-05 15:30:52,190 DEBUG: API thread: 10.14.100.251 - - "GET /master HTTP/1.0" 503 - latency: 2.467 ms
2024-04-05 15:30:53,301 INFO: Lock owner: test1; I am test3
2024-04-05 15:30:53,301 DEBUG: does not have lock
```

### PostgreSQL log files

```shell
2024-04-05 15:18:20.066 +07 [1855] ВАЖНО:  не удалось начать трансляцию WAL: ОШИБКА:  слот репликации "test3" не существует
2024-04-05 15:18:20.066 +07 [1850] СООБЩЕНИЕ:  waiting for WAL to become available at 0/500001C
2024-04-05 15:18:25.060 +07 [1869] СООБЩЕНИЕ:  начало передачи журнала с главного сервера, с позиции 0/5000000 на линии времени 1
2024-04-05 15:18:49.994 +07 [1851] СООБЩЕНИЕ:  начата точка перезапуска: time
2024-04-05 15:18:50.117 +07 [1851] СООБЩЕНИЕ:  точка перезапуска завершена: записано буферов: 2 (0.0%); добавлено файлов WAL 0, удалено: 0, переработано: 0; запись=0.107 сек., синхр.=0.00$
2024-04-05 15:18:50.117 +07 [1851] СООБЩЕНИЕ:  точка перезапуска восстановления в позиции 0/5000508
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

Patroni 3.2.2 supports etcdv3, but it works for me as if it does not support it. As if you need to enable enable-v2

**Comment by CyberDem0n** [comment]
You have to provide configuration file for patronictl: https://patroni.readthedocs.io/en/latest/patronictl.html#configuration
