### ISSUE TITLE
patroni.dcs.kubernetes.K8sClient.rest.ApiException: (401)

### ISSUE THREAD

**Issue by vdesai2020** [zalando/patroni#3083]
### What happened?

we have observed that the API calls from Patroni to Kubernetes API were returning 401 errors - 
 File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 203, in _handle_server_response
    raise k8s_client.rest.ApiException(http_resp=response)
patroni.dcs.kubernetes.K8sClient.rest.ApiException: (401)
Reason: Unauthorized
---
I’m not sure if this is a coincidence, but this happens after the deployment from Patroni reaches 1 year, and the issue is resolved after the pod gets recycled.

It appears that there is some kind of token that patroni generates to communicate with the Kubernetes API, but I couldn’t find it (it’s not the service account token as the SA doesn’t expire)
----------------
We know we have the fix for this exception. However we would like to know the answers for these questions
- Can anyone shares more details on under what circumstances this exception is thrown ?
- Why only after 1 year after deployment of patroni - this exception was thrown ?
- Instead of upgrading patroni - can we go with Unauthorized api calls ?
- How does the fix really works ?
- -----

Request experts here to help us in answering our questions.

Thanks

### How can we reproduce it (as minimally and precisely as possible)?

Issue / Bug known - https://github.com/zalando/patroni/issues/2536
Fix also available - https://github.com/zalando/patroni/pull/2585

### What did you expect to happen?

- There shouldn't be any 401 errors during k8s api calls from patroni

### Patroni/PostgreSQL/DCS version

patronictl version 2.1.3

### Patroni configuration file

```yaml
bootstrap:
  dcs:
    loop_wait: 10
    maximum_lag_on_failover: 33554432
    postgresql:
      parameters:
        archive_cleanup_command: pg_archivecleanup -d /home/postgres/pgdata/pgroot/data/pg_wal %r
        archive_mode: 'on'
        archive_timeout: 1800s
        autovacuum_analyze_scale_factor: 0.02
        autovacuum_max_workers: 5
        autovacuum_vacuum_scale_factor: 0.05
        checkpoint_completion_target: 0.9
        hot_standby: 'on'
        log_autovacuum_min_duration: 0
        log_checkpoints: 'on'
        log_connections: 'on'
        log_disconnections: 'on'
        log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
        log_lock_waits: 'on'
        log_min_duration_statement: 500
        log_statement: ddl
        log_temp_files: 0
        max_connections: '500'
        max_replication_slots: 10
        max_wal_senders: 10
        tcp_keepalives_idle: 900
        tcp_keepalives_interval: 100
        track_functions: all
        wal_compression: 'on'
        wal_level: hot_standby
        wal_log_hints: 'on'
      use_pg_rewind: true
      use_slots: true
    retry_timeout: 10
    ttl: 30
  initdb:
  - auth-host: md5
  - auth-local: trust
  post_init: /scripts/post_init.sh "zalandos"
  users:
    zalandos:
      options:
      - CREATEDB
      - NOLOGIN
      password: ''
kubernetes:
  bypass_api_service: true
  labels:
    application: spilo
  role_label: spilo-role
  scope_label: cluster-name
namespace: mteldr-pgo
  basebackup_fast_xlog:
    command: /scripts/basebackup.sh
    retries: 2
  bin_dir: /usr/lib/postgresql/12/bin
  callbacks:
    on_role_change: /scripts/on_role_change.sh zalandos true
  connect_address: 10.129.6.25:5432
  create_replica_method:
  - basebackup_fast_xlog
  data_dir: /home/postgres/pgdata/pgroot/data
  listen: '*:5432'
  name: grafana-grafana-0
  parameters:
    archive_command: /bin/true
    bg_mon.history_buckets: 120
    bg_mon.listen_address: '::'
    extwlist.custom_path: /scripts
    extwlist.extensions: btree_gin,btree_gist,citext,extra_window_functions,first_last_agg,hll,hstore,hypopg,intarray,ltree,pgcrypto,pgq,pgq_node,pg_trgm,postgres_fdw,tablefunc,uuid-ossp,timescaledb,pg_partman
    log_destination: csvlog
    log_directory: ../pg_log
    log_file_mode: '0644'
    log_filename: postgresql-%u.log
    log_rotation_age: 1d
    log_truncate_on_rotation: 'on'
    logging_collector: 'on'
    pg_stat_statements.track_utility: 'off'
    shared_buffers: 409MB
    shared_preload_libraries: bg_mon,pg_stat_statements,pgextwlist,pg_auth_mon,set_user,timescaledb,pg_cron,pg_stat_kcache
    ssl: 'on'
    ssl_cert_file: /run/certs/server.crt
    ssl_key_file: /run/certs/server.key
  pg_hba:
  - local   all             all                                   trust
  - hostssl all             +zalandos    127.0.0.1/32       pam
  - host    all             all                127.0.0.1/32       md5
  - hostssl all             +zalandos    ::1/128            pam
  - host    all             all                ::1/128            md5
  - local   replication     standby                    trust
  - hostssl replication     standby all                md5
  - hostssl all             +zalandos    all                pam
  - host    all             all                all                md5
  pgpass: /run/postgresql/pgpass
  use_unix_socket: true
  use_unix_socket_repl: true
scope: grafana-grafana
```

### patronictl show-config

```yaml
## compared with other postgres pods across components, it's the same output
loop_wait: 10
maximum_lag_on_failover: 33554432
postgresql:
  parameters:
    archive_cleanup_command: pg_archivecleanup -d /home/postgres/pgdata/pgroot/data/pg_wal %r
    archive_mode: 'on'
    archive_timeout: 1800s
    autovacuum_analyze_scale_factor: 0.02
    autovacuum_max_workers: 5
    autovacuum_vacuum_scale_factor: 0.05
    checkpoint_completion_target: 0.9
    hot_standby: 'on'
    log_autovacuum_min_duration: 0
    log_checkpoints: 'on'
    log_connections: 'on'
    log_disconnections: 'on'
    log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
    log_lock_waits: 'on'
    log_min_duration_statement: 500
    log_statement: ddl
    log_temp_files: 0
    max_connections: '500'
    max_replication_slots: 10
    max_wal_senders: 10
    tcp_keepalives_idle: 900
    tcp_keepalives_interval: 100
    track_functions: all
    wal_compression: 'on'
    wal_level: hot_standby
    wal_log_hints: 'on'
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
ttl: 30
```

### Patroni log files

```shell
2024-05-17 12:48:31,732 ERROR: Unexpected error from Kubernetes API
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 483, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 1028, in touch_member
    ret = self._api.patch_namespaced_pod(self._name, self._namespace, body)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 468, in wrapper
    return getattr(self._core_v1_api, func)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 404, in wrapper
    return self._api_client.call_api(method, path, headers, body, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 373, in call_api
    return self._handle_server_response(response, _preload_content)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 203, in _handle_server_response
    raise k8s_client.rest.ApiException(http_resp=response)
patroni.dcs.kubernetes.K8sClient.rest.ApiException: (401)
Reason: Unauthorized
```

### PostgreSQL log files

```shell
2024-05-17 12:48:31,732 ERROR: Unexpected error from Kubernetes API
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 483, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 1028, in touch_member
    ret = self._api.patch_namespaced_pod(self._name, self._namespace, body)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 468, in wrapper
    return getattr(self._core_v1_api, func)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 404, in wrapper
    return self._api_client.call_api(method, path, headers, body, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 373, in call_api
    return self._handle_server_response(response, _preload_content)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 203, in _handle_server_response
    raise k8s_client.rest.ApiException(http_resp=response)
patroni.dcs.kubernetes.K8sClient.rest.ApiException: (401)
Reason: Unauthorized
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by CyberDem0n** [comment]
The 401 error is the response code from K8s API Server.
There could be many reasons for it.
Your Patroni version is veeeery old (more than two years), there have been many bugfixes since then (including Kubernetes support) and there is no excuse to not upgrade to the latest version.

**Comment by vdesai2020** [comment]
hi @CyberDem0n - Thank u so much for the quick response. Yes we are aware and we will definitely upgrade patroni version we are using.
However - we request you to please provide answers for below questions as our customer is seeking "Root Cause" of this 401 error as we observed this after 1 year of post-gres deployment on our cluster.

Could you please share more details on under what circumstances this exception is thrown ?
Why only after 1 year after deployment of patroni - this exception was thrown ?
Instead of upgrading patroni - can we go with Unauthorized api calls ?
How does the fix really works ?
----

Thanks and regards,
Vijay

**Comment by CyberDem0n** [comment]
I can only suspect that the service account token has expired. There has been a fix for it more than two years ago: https://github.com/zalando/patroni/pull/2287
Why has it happen - you must investigate on your own.

**Comment by vdesai2020** [comment]
@CyberDem0n  - yes since service account doesn't expire ( on our system) - so we are bit clueless as how after 365 days - patroni threw this exception. Thanks - let me investigate further and also go through more on #2287  ticket details.

In case u have any other info related to how patroni generates "token" ? to communicate with k8s APII - then please share.
