### ISSUE TITLE
Old leader thinks he still has the lock after DCS error

### ISSUE THREAD

**Issue by zenitraM** [zalando/patroni#329]
We are using Consul as DCS and had one of the Consul servers flapping, causing a momentary loss of leader and making Consul returning a 500 error.

This is the Patroni log on the previously master node:
```
2016-10-04 20:30:36,486 INFO: demoted self because DCS is not accessible and i was a leader
2016-10-04 20:30:38,309 ERROR: get_cluster
Traceback (most recent call last):
  File "/opt/python_virtualenvs/patroni/lib/python3.5/site-packages/patroni/dcs/consul.py", line 131, in _load_cluster
    _, results = self._client.kv.get(path, recurse=True)
  File "/opt/python_virtualenvs/patroni/lib/python3.5/site-packages/consul/base.py", line 466, in get
    params=params)
  File "/opt/python_virtualenvs/patroni/lib/python3.5/site-packages/patroni/dcs/consul.py", line 51, in get
    return callback(self.response(self.session.get(self.uri(path, params), verify=self.verify, timeout=timeout)))
  File "/opt/python_virtualenvs/patroni/lib/python3.5/site-packages/consul/base.py", line 186, in cb
    CB.__status(response, allow_404=allow_404)
  File "/opt/python_virtualenvs/patroni/lib/python3.5/site-packages/consul/base.py", line 143, in __status
    raise ConsulException("%d %s" % (response.code, response.body))
consul.base.ConsulException: 500 rpc error: No cluster leader
2016-10-04 20:30:38,309 ERROR: Error communicating with DCS
2016-10-04 20:30:38,310 INFO: establishing a new patroni connection to the postgres cluster
2016-10-04 20:30:38,327 INFO: DCS is not accessible
2016-10-04 20:30:48,346 ERROR: touch_member
Traceback (most recent call last):
  File "/opt/python_virtualenvs/patroni/lib/python3.5/site-packages/patroni/dcs/consul.py", line 197, in touch_member
    self._client.kv.put(self.member_path, data, **args)
  File "/opt/python_virtualenvs/patroni/lib/python3.5/site-packages/consul/base.py", line 533, in put
    CB.json(), '/v1/kv/%s' % key, params=params, data=value)
  File "/opt/python_virtualenvs/patroni/lib/python3.5/site-packages/consul/std.py", line 40, in put
    self.session.put(uri, data=data, verify=self.verify)))
  File "/opt/python_virtualenvs/patroni/lib/python3.5/site-packages/consul/base.py", line 186, in cb
    CB.__status(response, allow_404=allow_404)
  File "/opt/python_virtualenvs/patroni/lib/python3.5/site-packages/consul/base.py", line 143, in __status
    raise ConsulException("%d %s" % (response.code, response.body))
consul.base.ConsulException: 500 rpc error: rpc error: invalid session "54ccbf7c-1b52-479b-336e-d1da5a10a0b5"
2016-10-04 20:30:48,348 INFO: Lock owner: dbd2; I am dbd2
server promoting
2016-10-04 20:30:48,384 INFO: cleared rewind flag after becoming the leader
2016-10-04 20:30:48,537 INFO: promoted self to leader because i had the session lock
2016-10-04 20:30:58,329 INFO: Lock owner: dbd1; I am dbd2
2016-10-04 20:30:58,329 INFO: does not have lock
2016-10-04 20:30:58,331 INFO: demoting self because i do not have the lock and i was a leader
```

and on the secondary node:

```
2016-10-04 20:30:47,061 INFO: Lock owner: dbd2; I am dbd1
2016-10-04 20:30:47,062 INFO: does not have lock
2016-10-04 20:30:47,062 INFO: no action.  i am a secondary and i am following a leader
2016-10-04 20:30:48,345 INFO: Got response from dbd2 http://127.0.0.1:8008/patroni: b'{"xlog": {"received_location": 960076185752, "replayed_timestamp": "2016-10-04 19:57:29.392 GMT", "paused": false, "replayed_location": 960076185752}, "server_version": 90502, "database_system_identifier": "6283357836010912867", "patroni": {"version": "1.1", "scope": "dbd"}, "state": "running", "role": "replica", "postmaster_start_time": "2016-09-22 08:33:10.658 GMT"}'
server promoting
2016-10-04 20:30:48,482 INFO: cleared rewind flag after becoming the leader
2016-10-04 20:30:58,366 INFO: Lock owner: dbd1; I am dbd1
2016-10-04 20:30:58,386 INFO: no action.  i am the leader with the lock
2016-10-04 20:31:08,359 INFO: Lock owner: dbd1; I am dbd1
2016-10-04 20:31:08,378 INFO: no action.  i am the leader with the lock
```

It seems that at between :48,345 and :48,482 dbd1 got the lock or detected that nobody else had the lock and promoted (forking to timeline 7), but at :48,348 dbd2 still thought he had the lock (after being demoted) so it also promoted itself.

After 10 seconds, dbd2 demoted itself when he no longer had the lock but failed to detect that a rewind was needed to join the old master.

At the same time this caused a race condition that ended up with a sorta-splitbrain.
We have WAL-E on restore_command so some segments written by dbd1 were read on dbd2 while it was promoting, causing it to replicate the fork to timeline 7, and then fork to a new "ghost" timeline 8 which was then uploaded to WAL-E by dbd2.

This caused dbd1 and dbd2 to become trashed after a second failure happened: dbd2 was not deemed healthy (as it had "lag" as it was on a timeline 8 forked before the second failure), dbd1 was trying to jump to the timeline 8 while recovering WAL-E. (dbd1 came back after removing everything from timeline 8) 

We are running on a version which is behind https://github.com/zalando/patroni/commit/298357c099d362a11659765cc3ff052c694b0a7f and https://github.com/zalando/patroni/commit/e38dfaf1baeecf596da02a08de52d5948410257c so I'm trying to understand if those would have prevented the first race condition from happening.

I'm also wondering if #295 would prevent the case of two nodes starting at the same time and overlapping their WAL-E or if there's anything else that could be done.

**Comment by CyberDem0n** [comment]
It looks like there is a really race condition here :(

I think https://github.com/zalando/patroni/commit/298357c099d362a11659765cc3ff052c694b0a7f should help in situations like you had, but only if hiccup is not longer then `retry_timeout`. Default value of retry_timeout is 10 seconds. Judging on your log files it took longer than 10 seconds...

I am very sorry for this troubles, we are running Patroni in production only against Etcd and ZooKeeper, therefore not all bugs with Consul are caught yet...

Why it failed to detect that pg_rewind is needed is still needs to be investigated. First I will fix the problem with Consul.

**Comment by zenitraM** [comment]
Thank you! :)
We are working on ironing the kinks to run Patroni on our Consul-powered production environment as well so if there is any way we can help we're glad to do so.

**Comment by CyberDem0n** [comment]
Something really strange has happened...

`refresh_session` (https://github.com/zalando/patroni/blob/v1.1/patroni/dcs/consul.py#L103) didn't raised any exception, that means either it has updated en existing sessions successfully or created a new one instead, but in any case a few moments later Consul somehow consider this session as invalid, because `self._client.kv.put(self.member_path, data, **args)` has failed with: `consul.base.ConsulException: 500 rpc error: rpc error: invalid session "54ccbf7c-1b52-479b-336e-d1da5a10a0b5"`

What Consul version do you run?

**Comment by zenitraM** [comment]
We are running https://github.com/CartoDB/patroni/commits/feature/bootstrap_post_init which should be 1.1 with #296 on top 🤔

**Comment by zenitraM** [comment]
Ah, Consul! It's 0.6.0. We're planning updating to 0.7.0 to address the flapping though
