### ISSUE TITLE
Can't omit 'users' hash from 'bootstrap' stanza

### ISSUE THREAD

**Issue by sm97** [zalando/patroni#333]
From `SETTINGS.rst`
```
users: Some additional users users which needs to be created after initializing new cluster
```

So doc doesn't insists that `users` hash should be mandatory. But starting Patroni with commented out `users` hash fails with following exception:
```
Traceback (most recent call last):
  File "/opt/python-envs/patroni/bin/patroni", line 9, in <module>
    load_entry_point('patroni==1.0', 'console_scripts', 'patroni')()
  File "/opt/python-envs/patroni/lib/python2.7/site-packages/patroni/__init__.py", line 128, in main
    patroni.run()
  File "/opt/python-envs/patroni/lib/python2.7/site-packages/patroni/__init__.py", line 102, in run
    logger.info(self.ha.run_cycle())
  File "/opt/python-envs/patroni/lib/python2.7/site-packages/patroni/ha.py", line 502, in run_cycle
    return self._run_cycle()
  File "/opt/python-envs/patroni/lib/python2.7/site-packages/patroni/ha.py", line 464, in _run_cycle
    return self.bootstrap()  # new node
  File "/opt/python-envs/patroni/lib/python2.7/site-packages/patroni/ha.py", line 93, in bootstrap
    self.state_handler.bootstrap(self.patroni.config['bootstrap'])
  File "/opt/python-envs/patroni/lib/python2.7/site-packages/patroni/postgresql.py", line 914, in bootstrap
    for name, value in config['users'].items():
KeyError: 'users'
```

**Comment by CyberDem0n** [comment]
Your fix is merged, thank you
