### ISSUE TITLE
patronictl resume does not run if there is no cluster leader

### ISSUE THREAD

**Issue by zenitraM** [zalando/patroni#350]
After #349 (paused cluster, and the leader has failed for any reason):

```
$ patronictl -c /etc/patroni/patroni.yml resume cluster
Traceback (most recent call last):
  File "/usr/local/bin/patronictl", line 11, in <module>
    load_entry_point('patroni==1.1', 'console_scripts', 'patronictl')()
  File "/opt/python_virtualenvs/patroni/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/opt/python_virtualenvs/patroni/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/opt/python_virtualenvs/patroni/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/python_virtualenvs/patroni/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/python_virtualenvs/patroni/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/opt/python_virtualenvs/patroni/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/opt/python_virtualenvs/patroni/lib/python3.5/site-packages/patroni/ctl.py", line 817, in resume
    return toggle_pause(obj, cluster_name, False)
  File "/opt/python_virtualenvs/patroni/lib/python3.5/site-packages/patroni/ctl.py", line 797, in toggle_pause
    r = request_patroni(cluster.leader.member, 'patch', 'config', {'pause': paused or None}, auth_header(config))
AttributeError: 'NoneType' object has no attribute 'member'
```

**Comment by CyberDem0n** [comment]
Yeah, it's actually a known bug, but I forgot to create an issue and fix it :(
Will take care about it tomorrow.
