### ISSUE TITLE
Error on cluster initialization

### ISSUE THREAD

**Issue by kmoppel** [zalando/patroni#392]
Might be a dumbuser exception but can't quite understand what file is missing. Some hints would be appreciated then:) Steps I took:

1. pip install patroni
2. su postgres && mkdir app && cd app
3. wget https://raw.githubusercontent.com/zalando/patroni/master/postgres0.yml
4. edit etcd url postgres0.yml
5. partroni postgres0.yml
  initdb thows "No such file or directory". but initdb should created the data folder automatically?

2017-02-02 15:31:58,965 INFO: Selected new etcd server http://172.17.0.1:2379
2017-02-02 15:31:58,977 INFO: removing initialize key after failed attempt to initialize the cluster
Traceback (most recent call last):
  File "/usr/bin/patroni", line 9, in <module>
    load_entry_point('patroni==1.2.3', 'console_scripts', 'patroni')()
  File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 170, in main
    return patroni_main()
  File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 134, in patroni_main
    patroni.run()
  File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 110, in run
    logger.info(self.ha.run_cycle())
  File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 941, in run_cycle
    info = self._run_cycle()
  File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 889, in _run_cycle
    return self.bootstrap()  # new node
  File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 151, in bootstrap
    self.state_handler.bootstrap(self.patroni.config['bootstrap'])
  File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 1218, in bootstrap
    if self._initialize(config) and self.start() and self.run_bootstrap_post_init(config):
  File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 432, in _initialize
    ret = self.pg_ctl('initdb', *options)
  File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 206, in pg_ctl
    return subprocess.call(pg_ctl + ['-D', self._data_dir] + list(args), **kwargs) == 0
  File "/usr/lib64/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by CyberDem0n** [comment]
Hi @kmoppel,

`pg_ctl`, `postgres`, `pg_basebackup` and `pg_rewind` must be accessible within $PATH or you should put `bin_dir` into `postgresql` section.

```yaml
postgresql:
  bin_dir: /usr/lib/postgresql/9.6
```

**Comment by kmoppel** [comment]
Argh, path issue indeed...thanks @CyberDem0n ! Maybe would make sense to check if pg_ctl is there and display a nice error :)

**Comment by shreeramk** [comment]
After setting up the bin_dir i m getting following error

Traceback (most recent call last):
  File "/usr/bin/patroni", line 11, in <module>
    load_entry_point('patroni==1.6.0', 'console_scripts', 'patroni')()
  File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 196, in main
    return patroni_main()
  File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 160, in patroni_main
    patroni.run()
  File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 125, in run
    logger.info(self.ha.run_cycle())
  File "/usr/lib/python3/dist-packages/patroni/ha.py", line 1344, in run_cycle
    info = self._run_cycle()
  File "/usr/lib/python3/dist-packages/patroni/ha.py", line 1253, in _run_cycle
    return self.post_bootstrap()
  File "/usr/lib/python3/dist-packages/patroni/ha.py", line 1149, in post_bootstrap
    self.cancel_initialization()
  File "/usr/lib/python3/dist-packages/patroni/ha.py", line 1144, in cancel_initialization
    raise PatroniException('Failed to bootstrap cluster')
patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'

**Comment by theelee** [comment]
> Hi @kmoppel,
> 
> `pg_ctl`, `postgres`, `pg_basebackup` and `pg_rewind` must be accessible within $PATH or you should put `bin_dir` into `postgresql` section.
> 
> ```yaml
> postgresql:
>   bin_dir: /usr/lib/postgresql/9.6
> ```

Minor correction: should be 
```
postgresql:
  bin_dir: /usr/lib/postgresql/9.6/bin
```
