### ISSUE TITLE
Connection reset by peer after upgrade 0.90 to 1.2.3

### ISSUE THREAD

**Issue by ClaudiuPID** [zalando/patroni#393]
Hi,

I am getting this errors after upgrading today:
```
Feb  3 16:30:00 sql1-mcp patroni[22245]: Traceback (most recent call last):
Feb  3 16:30:00 sql1-mcp patroni[22245]:   File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
Feb  3 16:30:00 sql1-mcp patroni[22245]:     self.finish_request(request, client_address)
Feb  3 16:30:00 sql1-mcp patroni[22245]:   File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
Feb  3 16:30:00 sql1-mcp patroni[22245]:     self.RequestHandlerClass(request, client_address, self)
Feb  3 16:30:00 sql1-mcp patroni[22245]:   File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
Feb  3 16:30:00 sql1-mcp patroni[22245]:     self.handle()
Feb  3 16:30:00 sql1-mcp patroni[22245]:   File "/usr/lib/python3.5/http/server.py", line 422, in handle
Feb  3 16:30:00 sql1-mcp patroni[22245]:     self.handle_one_request()
Feb  3 16:30:00 sql1-mcp patroni[22245]:   File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
Feb  3 16:30:00 sql1-mcp patroni[22245]:     method()
Feb  3 16:30:00 sql1-mcp patroni[22245]:   File "/usr/local/lib/python3.5/dist-packages/patroni/api.py", line 104, in do_GET
Feb  3 16:30:00 sql1-mcp patroni[22245]:     self._write_status_response(status_code, response)
Feb  3 16:30:00 sql1-mcp patroni[22245]:   File "/usr/local/lib/python3.5/dist-packages/patroni/api.py", line 71, in _write_status_response
Feb  3 16:30:00 sql1-mcp patroni[22245]:     self._write_json_response(status_code, response)
Feb  3 16:30:00 sql1-mcp patroni[22245]:   File "/usr/local/lib/python3.5/dist-packages/patroni/api.py", line 46, in _write_json_response
Feb  3 16:30:00 sql1-mcp patroni[22245]:     self._write_response(status_code, json.dumps(response), content_type='application/json')
Feb  3 16:30:00 sql1-mcp patroni[22245]:   File "/usr/local/lib/python3.5/dist-packages/patroni/api.py", line 43, in _write_response
Feb  3 16:30:00 sql1-mcp patroni[22245]:     self.wfile.write(body.encode('utf-8'))
Feb  3 16:30:00 sql1-mcp patroni[22245]:   File "/usr/lib/python3.5/socket.py", line 593, in write
Feb  3 16:30:00 sql1-mcp patroni[22245]:     return self._sock.send(b)
Feb  3 16:30:00 sql1-mcp patroni[22245]: ConnectionResetError: [Errno 104] Connection reset by peer
```

I suspect it is haproxy accessing /master or /replica. Is this a known issue? Still digging, maybe I missed something in the new config format of 1.x.

**Comment by CyberDem0n** [comment]
Hi @ClaudiuPID , can you show your haproxy configuration?

**Comment by ClaudiuPID** [comment]
Sure, it is a bit more complicated than I would of liked it to be but here it goes.
```
frontend ft_db_rw
    bind 127.0.0.1:15432
	option          clitcpka
    default_backend be_db_rw
	timeout client 60m
	timeout connect 10s
	timeout server 60m
	timeout check 5s

backend be_db_rw
    option httpchk GET /master
    http-check expect status 200
	timeout client 60m
	timeout connect 10s
	timeout server 60m
	timeout check 5s
    server sql1 10.10.0.70:15432 maxconn 500 check port 8008
    server sql2 10.10.0.71:15432 maxconn 500 check port 8008
    server sql3 10.10.0.72:15432 maxconn 500 check port 8008

frontend ft_db_ro
    bind 127.0.0.1:15433
	option          clitcpka
    default_backend be_db_ro

frontend backup_db_ro
    bind 10.10.0.68:15433
	option          clitcpka
    default_backend be_db_ro

backend be_db_ro
    option httpchk GET /replica
    http-check expect status 200
    balance roundrobin
    server sql1 10.10.0.70:15432 maxconn 500 check port 8008
    server sql2 10.10.0.71:15432 maxconn 500 check port 8008
    server sql3 10.10.0.72:15432 maxconn 500 check port 8008
```

**Comment by CyberDem0n** [comment]
ok, I know what is happening.

haproxy is doing GET request, reads http response code and closing connection.
Patroni is trying to send remaining parts (http headers and some json payload) but connection is already closed.

Just replace GET with OPTIONS on the lines
```
    option httpchk GET /master

    option httpchk GET /replica
```

and exceptions should go away.

**Comment by ClaudiuPID** [comment]
Thank you, no more exceptions, much appreciated :)

**Comment by CyberDem0n** [comment]
You are welcome!
