### ISSUE TITLE
initdb error: invalid locale name "UTF8"

### ISSUE THREAD

**Issue by deislerz** [zalando/patroni#413]
Hello.
I have `- locale: UTF8` in patroni.yml config.

patroni version 1.2.4

```2017-03-17 14:21:35,970 INFO: Starting new HTTP connection (1): 127.0.0.1
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

initdb: invalid locale name "UTF8"
pg_ctl: database system initialization failed
2017-03-17 14:21:36,007 INFO: removing initialize key after failed attempt to initialize the cluster
Traceback (most recent call last):
  File "/opt/patroni/patroni.py", line 6, in <module>
    main()
  File "/opt/patroni/patroni/__init__.py", line 170, in main
    return patroni_main()
  File "/opt/patroni/patroni/__init__.py", line 134, in patroni_main
    patroni.run()
  File "/opt/patroni/patroni/__init__.py", line 110, in run
    logger.info(self.ha.run_cycle())
  File "/opt/patroni/patroni/ha.py", line 941, in run_cycle
    info = self._run_cycle()
  File "/opt/patroni/patroni/ha.py", line 889, in _run_cycle
    return self.bootstrap()  # new node
  File "/opt/patroni/patroni/ha.py", line 151, in bootstrap
    self.state_handler.bootstrap(self.patroni.config['bootstrap'])
  File "/opt/patroni/patroni/postgresql.py", line 1224, in bootstrap
    raise PostgresException("Could not bootstrap master PostgreSQL")
patroni.exceptions.PostgresException: 'Could not bootstrap master PostgreSQL'
```

**Comment by uspen** [comment]
en_US.utf8

**Comment by CyberDem0n** [comment]
Yes, this is definitely not a bug. Patroni just passes this parameters as it is to the `initdb`.

Just try `locale:  en_US.UTF-8` instead. Or any other locale of your choice.

**Comment by deislerz** [comment]
Update docs please:
https://github.com/zalando/patroni/blob/master/docs/SETTINGS.rst
`initdb:` List options to be passed on to initdb.
...
- locale: UTF8: default locale for new databases.`

**Comment by CyberDem0n** [comment]
@deislerz, pull requests are always welcome!
