### ISSUE TITLE
Postgresql.write_recovery_conf: FileNotFoundError

### ISSUE THREAD

**Issue by joar** [zalando/patroni#438]
Migrated from https://github.com/zalando/patroni/pull/436

# Scenario

- Kubernetes 1.6.0 on GKE
- wal-e backups and basebackups stored on GCS
- env `GOOGLE_APPLICATION_CREDENTIALS` points to account with GCS "Storage Object Admin" role.
- StatefulSet running spilo with patroni 1.2.5, postgresql 9.6, `replicas: 2`
- Empty volume mounted as `/home/postgres/pgdata`
- When creating the second pod, i.e. the error occurs when trying to create a new replica for a cluste with a leader.

# Expected result

patroni should start downloading from basebackup or wal-e from GCS backup in order to not put additional strain on the master node, then start replicating from master. This seems to be supported by patroni, at least in an Kubernetes+AWS

# Actual result

```
2017-04-26 06:30:57,744 INFO: Lock owner: patroni-set-0006-0; I am patroni-set-0006-1
2017-04-26 06:30:57,751 INFO: trying to bootstrap from leader 'patroni-set-0006-0'
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-list".
        STRUCTURED: time=2017-04-26T06:30:58.362701-00 pid=7246
oauth2client.transport INFO     Attempting refresh to obtain initial access_token
oauth2client.client INFO     Refreshing access_token
2017-04-26 06:30:59,064 INFO: replica has been created using wal_e
2017-04-26 06:30:59,064 INFO: bootstrapped from leader 'patroni-set-0006-0'
2017-04-26 06:30:59,068 ERROR: Exception during execution of long running task bootstrap from leader 'patroni-set-0006-0'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/patroni/async_executor.py", line 39, in run
    wakeup = func(*args) if args else func()
  File "/usr/local/lib/python3.5/dist-packages/patroni/ha.py", line 134, in clone
    return self.state_handler.follow(node_to_follow, cluster.leader, True)
  File "/usr/local/lib/python3.5/dist-packages/patroni/postgresql.py", line 1007, in follow
    return self._do_follow(primary_conninfo, leader, recovery, timeout)
  File "/usr/local/lib/python3.5/dist-packages/patroni/postgresql.py", line 1063, in _do_follow
    self.write_recovery_conf(primary_conninfo)
  File "/usr/local/lib/python3.5/dist-packages/patroni/postgresql.py", line 899, in write_recovery_conf
    with open(self._recovery_conf, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/postgres/pgdata/pgroot/data/recovery.conf'
```
repeated, as patroni is restarted by supervisor.

### Files and directories

From the running postgres-set-0006-1 pod.

#### patroni configuration

- `/home/postgres/postgres.yml` has been created: https://gist.github.com/joar/321652e961754d8362195b3776692185

#### wal-e configuration

```
/home/postgres/etc/wal-e.d/env/WALE_GS_PREFIX: gs://my-postgres-backup/spilo/my-scope/wal/
/home/postgres/etc/wal-e.d/env/GOOGLE_APPLICATION_CREDENTIALS: /etc/patroni/secrets/service-account.json
/home/postgres/etc/wal-e.d/env/TMPDIR: /home/postgres/pgdata/tmp
```
`/etc/patroni/secrets/service-account.json` exists and is walid

#### Files in `data_dir`

`/home/postgres/pgdata` exists, but without `pgroot/data`
```
pgdata/
├── lost+found
├── pgroot
│   └── pg_log
│       ├── postgresql-0.csv
│       ├── postgresql-1.csv
│       ├── postgresql-2.csv
│       ├── postgresql-3.csv
│       ├── postgresql-4.csv
│       ├── postgresql-5.csv
│       ├── postgresql-6.csv
│       └── postgresql-7.csv
└── tmp
```

### Trying to create `data_dir` manually

If I create `/home/postgres/pgdata/pgroot/data` manually, I get another error:

```
2017-04-26 09:33:53,787 INFO success: patroni entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-04-26 09:33:53,847 INFO exited: patroni (exit status 1; not expected)
2017-04-26 09:33:54,850 INFO spawned: 'patroni' with pid 15819
2017-04-26 09:33:55,345 INFO: Selected new etcd server http://10.71.254.134:2379
2017-04-26 09:33:55,353 CRITICAL: system ID mismatch, node patroni-set-0006-1 belongs to a different cluster: 6412988290203516990 != 
2017-04-26 09:33:55,858 ERROR: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/patroni/__init__.py", line 134, in patroni_main
    patroni.run()
  File "/usr/local/lib/python3.5/dist-packages/patroni/__init__.py", line 110, in run
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python3.5/dist-packages/patroni/ha.py", line 946, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.5/dist-packages/patroni/ha.py", line 903, in _run_cycle
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/etcd.py", line 329, in wrapper
    retval = func(self, *args, **kwargs) is not None
  File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/etcd.py", line 511, in delete_leader
    return self._client.delete(self.leader_path, prevValue=self._name)
  File "/usr/local/lib/python3.5/dist-packages/etcd/client.py", line 584, in delete
    self.key_endpoint + key, self._MDELETE, params=kwds)
  File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/etcd.py", line 211, in api_execute
    return self._handle_server_response(response)
  File "/usr/local/lib/python3.5/dist-packages/etcd/client.py", line 928, in _handle_server_response
    etcd.EtcdError.handle(r)
  File "/usr/local/lib/python3.5/dist-packages/etcd/__init__.py", line 304, in handle
    raise exc(msg, payload)
etcd.EtcdCompareFailed: Compare failed : [patroni-set-0006-1 != patroni-set-0006-0]
```

caused by `self.state_handler.sysid` being `''` at [patroni/ha.py#L901](https://github.com/zalando/patroni/blob/1d513e7e04cc0c69113b9a94d37b0296ceae2906/patroni/ha.py#L901).

The `Compare failed : [patroni-set-0006-1 != patroni-set-0006-0]` is curious, does my replica think it's the leader?

**Comment by CyberDem0n** [comment]
Please see a last comment on PR#436, there is a bug in your `wale_restore.py`

> The Compare failed : [patroni-set-0006-1 != patroni-set-0006-0] is curious, does my replica think it's the leader?

This is fine, when the Patroni shut down gracefully - it tries to remove a leader key from etcd, but does it atomically, with compare and delete operation.
If it was a leader - such removal will notify other nodes immediately.
If it wasn't - etcd will just raise such exception.

**Comment by joar** [comment]
Thank you! Here's a fixed link for the comment: https://github.com/zalando/patroni/pull/436#discussion_r113446368
