### ISSUE TITLE
Not possible to reload config while postgres is not available

### ISSUE THREAD

**Issue by ants** [zalando/patroni#443]
Usecase: changing superuser password

Steps to reproduce:

1. Change superuser password in postgres
2. Terminate patroni connection to postgres
3. Change superuser password in patroni config
4. Reload config

Expected: Patroni is able to reconnect to postgres
Actual:

```
2017-05-18 22:30:46,074 ERROR: Failed to reload config_file=syncconfs/postgres0.yml
Traceback (most recent call last):
  File "/home/ants/work/telia/patronivenv/local/lib/python2.7/site-packages/patroni/__init__.py", line 61, in reload_config
    self.postgresql.reload_config(self.config['postgresql'])
  File "/home/ants/work/telia/patronivenv/local/lib/python2.7/site-packages/patroni/postgresql.py", line 169, in reload_config
    ORDER BY 1 DESC""", *(list(changes.keys()))):
  File "/home/ants/work/telia/patronivenv/local/lib/python2.7/site-packages/patroni/postgresql.py", line 313, in query
    raise PostgresConnectionException(str(e))
PostgresConnectionException: "'Exceeded retry deadline'"
```

**Comment by CyberDem0n** [comment]
Good catch.
Will try to fix it today.

**Comment by CyberDem0n** [comment]
Fixed with https://github.com/zalando/patroni/pull/445
