### ISSUE TITLE
ImportError: cannot import name main (File "/patroni.py", line 2, in <module>)

### ISSUE THREAD

**Issue by RafaelKr** [zalando/patroni#479]
OS: CentOS Linux release 7.3.1611 (Core)
patroni: v1.2.5

**Current behavior:**
I try to setup a Postgres-Cluster with patroni, but I run into the following error:
```
Traceback (most recent call last):
  File "/patroni.py", line 2, in <module>
    from patroni import main
  File "/patroni.py", line 2, in <module>
    from patroni import main
ImportError: cannot import name main
```

**Steps to reproduce:**
```bash
wget https://github.com/zalando/patroni/archive/v1.2.5.zip
unzip v1.2.5.zip
rm v1.2.5.zip
cd patroni-1.2.5/
# prevent questions while building because they can't be answered see #476 for more info⁽¹⁾
sed -i "s|RUN echo 'APT::Install-Recommends|RUN export DEBIAN_FRONTEND=noninteractive \\\\\n    \&\& echo 'APT::Install-Recommends|g" Dockerfile
docker build . -t patroni
```
⁽¹⁾ Issue #476 

After this I run the following docker-compose.yml:
```
# docker compose file for running a 3-node PostgreSQL cluster
# with etcd as the SIS

patroni-etcd:
    container_name: patroni-etcd
    image: patroni
    command: --etcd

dbnode1:
    image: patroni
    hostname: dbnode1
    links:
        - patroni-etcd:patroni_etcd
    volumes:
        - ./patroni:/patroni
    env_file: docker/patroni-secrets.env
    environment:
        PATRONI_ETCD_HOST: patroni_etcd:2379
        PATRONI_NAME: dbnode1
        PATRONI_SCOPE: testcluster

dbnode2:
    image: patroni
    hostname: dbnode2
    links:
        - patroni-etcd:patroni_etcd
    volumes:
        - ./patroni:/patroni
    env_file: docker/patroni-secrets.env
    environment:
        PATRONI_ETCD_HOST: patroni_etcd:2379
        PATRONI_NAME: dbnode2
        PATRONI_SCOPE: testcluster

dbnode3:
    image: patroni
    hostname: dbnode3
    links:
        - patroni-etcd:patroni_etcd
    volumes:
        - ./patroni:/patroni
    env_file: docker/patroni-secrets.env
    environment:
        PATRONI_ETCD_HOST: patroni_etcd:2379
        PATRONI_NAME: dbnode3
        PATRONI_SCOPE: testcluster

haproxy:
    image: patroni
    links:
        - patroni-etcd:patroni_etcd
    ports:
        - "5000:5000"
        - "5001:5001"
    environment:
        PATRONI_ETCD_HOST: patroni_etcd:2379
        PATRONI_SCOPE: testcluster
    command: --confd
```
I modified [this docker-compose.yml](/patroni/docker-compose.yml) a little bit to be able to use it with [rancher](https://github.com/rancher/rancher), but I only changed the container `patroni_etcd` to `patroni-etcd`.
I also tested this locally and the same error occures there, so it has nothing to do with rancher.

Thanks for helping!

**Comment by CyberDem0n** [comment]
@RafaelKr, Dockerfile  is [broken](https://github.com/zalando/patroni/pull/480), but the error you get is not relevant.


```yaml
    volumes:
        - ./patroni:/patroni
```

I am not sure how rancher handles `volumes`, it might be that inside container `/patroni` directory is empty and therefore you get an `ImportError`.

There are two options: either you remove or comment all `volumes` sections from `docker-compose.yaml` or figure out how to fix `volumes` for rancher.

Also you can try `./docker/dev_patroni_cluster.sh` script. It works similar to docker-compose, i.e. starts bunch of containers.

```bash
$ docker build -t patroni .
$ ./docker/dev_patroni_cluster.sh --image patroni --name testcluster --members 3
```

**Comment by RafaelKr** [comment]
Thank you for the quick answer, but this has **nothing** to do with rancher, as I get the same error locally. (I shouldn't've mentioned rancher at all). But as I have to run it on rancher later, I have to use the docker-compose.yml

I tried your new Dockerfile, but now it doesn't start at all. Tomorrow I'll investigate it further.

**Comment by blelump** [comment]
@CyberDem0n ,

I am able to recreate the same problem:

```
dbnode2_1  | Traceback (most recent call last):
dbnode2_1  |   File "/patroni.py", line 2, in <module>
dbnode2_1  |     from patroni import main
dbnode2_1  |   File "/patroni.py", line 2, in <module>
dbnode2_1  |     from patroni import main
dbnode2_1  | ImportError: cannot import name 'main'
```

It seems it is completely non-deterministic, sometimes the cluster boots up without any issues and sometimes (currently most of the time, it crashes with the above error). 

@RafaelKr , have you found the cause of that?
