### ISSUE TITLE
POST failover doesn't work

### ISSUE THREAD

**Issue by unixwitch** [zalando/patroni#488]
Hello,

I set up a new cluster using Patroni 1.3, ZooKeeper 3.4.10 and PostgreSQL 9.6.3 on CentOS 7.  Everything seems to work fine, except failover via the API.

I sent a request like this:

```
[root@postgres-5-2 ~]# curl -d'{"leader": "postgres-5-2", "candidate": "postgres-5-3"}' -H'Content-Type: application/json' http://admin:xxx@postgres-5-2:8008/failover
curl: (52) Empty reply from server
```

Patroni error logs show an exception:

```
Jul 28 12:35:31 postgres-5-2 patroni[1269]: 2017-07-28 12:35:31,258 INFO: received failover request with leader=postgres-5-2 candidate=postgres-5-3 scheduled_at=None
Jul 28 12:35:31 postgres-5-2 patroni[1269]: 2017-07-28 12:35:31,276 INFO: Got response from postgres-5-3 http://postgres-5-3:8008/patroni: b'{"role": "replica", "postmaster_start_time": "2017-07-28 12:31:09.295 UTC", "state": "running", "xlog": {"replayed_timestamp": "2017-07-28 12:31:09.208 UTC", "paused": false, "replayed_location": 369514424, "received_location": 369514424}, "server_version": 90603, "patroni": {"version": "1.3", "scope": "postgres-5"}, "database_system_identifier": "6447546693452231673"}'
Jul 28 12:35:31 postgres-5-2 patroni[1269]: 2017-07-28 12:35:31,367 INFO: Got response from postgres-5-3 http://postgres-5-3:8008/patroni: b'{"role": "replica", "postmaster_start_time": "2017-07-28 12:31:09.295 UTC", "state": "running", "xlog": {"replayed_timestamp": "2017-07-28 12:31:09.208 UTC", "paused": false, "replayed_location": 369514424, "received_location": 369514424}, "server_version": 90603, "patroni": {"version": "1.3", "scope": "postgres-5"}, "database_system_identifier": "6447546693452231673"}'
Jul 28 12:35:34 postgres-5-2 patroni[1269]: Traceback (most recent call last):
Jul 28 12:35:34 postgres-5-2 patroni[1269]: File "/usr/lib64/python3.4/socketserver.py", line 617, in process_request_thread
Jul 28 12:35:34 postgres-5-2 patroni[1269]: self.finish_request(request, client_address)
Jul 28 12:35:34 postgres-5-2 patroni[1269]: File "/usr/lib64/python3.4/socketserver.py", line 344, in finish_request
Jul 28 12:35:34 postgres-5-2 patroni[1269]: self.RequestHandlerClass(request, client_address, self)
Jul 28 12:35:34 postgres-5-2 patroni[1269]: File "/usr/lib64/python3.4/socketserver.py", line 673, in __init__
Jul 28 12:35:34 postgres-5-2 patroni[1269]: self.handle()
Jul 28 12:35:34 postgres-5-2 patroni[1269]: File "/usr/lib64/python3.4/http/server.py", line 401, in handle
Jul 28 12:35:34 postgres-5-2 patroni[1269]: self.handle_one_request()
Jul 28 12:35:34 postgres-5-2 patroni[1269]: File "/usr/lib64/python3.4/http/server.py", line 389, in handle_one_request
Jul 28 12:35:34 postgres-5-2 patroni[1269]: method()
Jul 28 12:35:34 postgres-5-2 patroni[1269]: File "/usr/lib/python3.4/site-packages/patroni/api.py", line 29, in wrapper
Jul 28 12:35:34 postgres-5-2 patroni[1269]: return func(handler)
Jul 28 12:35:34 postgres-5-2 patroni[1269]: File "/usr/lib/python3.4/site-packages/patroni/api.py", line 341, in do_POST_failover
Jul 28 12:35:34 postgres-5-2 patroni[1269]: data = self.is_failover_possible(cluster, leader, candidate)
Jul 28 12:35:34 postgres-5-2 patroni[1269]: File "/usr/lib/python3.4/site-packages/patroni/api.py", line 304, in is_failover_possible
Jul 28 12:35:34 postgres-5-2 patroni[1269]: for _, reachable, _, _, tags in self.server.patroni.ha.fetch_nodes_statuses(members):
Jul 28 12:35:34 postgres-5-2 patroni[1269]: ValueError: too many values to unpack (expected 5)
```

Failover using `patronictl failover` still works as it falls back to DCS.

**Comment by CyberDem0n** [comment]
Hi @unixwitch,

you are right, bug was introduced in https://github.com/zalando/patroni/pull/452, will prepare a fix soon
