### ISSUE TITLE
Error On Running ./patroni.py postgres0.yml

### ISSUE THREAD

**Issue by shubham399** [zalando/patroni#497]
2017-08-01 16:17:42,344 INFO: Selected new etcd server http://127.0.0.1:2379
2017-08-01 16:17:42,350 INFO: Lock owner: None; I am postgresql0
2017-08-01 16:17:42,381 ERROR: Exception during execution of long running task bootstrap
Traceback (most recent call last):
  File "/home/MyPC/Work/patroni1/patroni/async_executor.py", line 86, in run
    wakeup = func(*args) if args else func()
  File "/home/MyPC/Work/patroni1/patroni/postgresql.py", line 1544, in bootstrap
    return do_initialize(config) and self._configure_server_parameters() and self.start()
  File "/home/MyPC/Work/patroni1/patroni/postgresql.py", line 517, in _initdb
    ret = self.pg_ctl('initdb', *options)
  File "/home/MyPC/Work/patroni1/patroni/postgresql.py", line 263, in pg_ctl
    return subprocess.call(pg_ctl + ['-D', self._data_dir] + list(args), **kwargs) == 0
  File "/usr/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
2017-08-01 16:17:42,383 INFO: trying to bootstrap a new cluster
2017-08-01 16:17:42,385 INFO: removing initialize key after failed attempt to bootstrap the cluster
2017-08-01 16:17:42,854 ERROR: 
Traceback (most recent call last):
  File "/home/MyPC/Work/patroni1/patroni/dcs/etcd.py", line 329, in wrapper
    retval = func(self, *args, **kwargs) is not None
  File "/home/MyPC/Work/patroni1/patroni/dcs/etcd.py", line 511, in delete_leader
    return self._client.delete(self.leader_path, prevValue=self._name)
  File "/home/MyPC/.local/lib/python2.7/site-packages/etcd/client.py", line 645, in delete
    self.key_endpoint + key, self._MDELETE, params=kwds)
  File "/home/MyPC/Work/patroni1/patroni/dcs/etcd.py", line 211, in api_execute
    return self._handle_server_response(response)
  File "/home/MyPC/.local/lib/python2.7/site-packages/etcd/client.py", line 987, in _handle_server_response
    etcd.EtcdError.handle(r)
  File "/home/MyPC/.local/lib/python2.7/site-packages/etcd/__init__.py", line 306, in handle
    raise exc(msg, payload)
EtcdKeyNotFound: Key not found : /service/batman/leader
Traceback (most recent call last):
  File "./patroni.py", line 6, in <module>
    main()
  File "/home/MyPC/Work/patroni1/patroni/__init__.py", line 173, in main
    return patroni_main()
  File "/home/MyPC/Work/patroni1/patroni/__init__.py", line 142, in patroni_main
    patroni.run()
  File "/home/MyPC/Work/patroni1/patroni/__init__.py", line 114, in run
    logger.info(self.ha.run_cycle())
  File "/home/MyPC/Work/patroni1/patroni/ha.py", line 1056, in run_cycle
    info = self._run_cycle()
  File "/home/MyPC/Work/patroni1/patroni/ha.py", line 982, in _run_cycle
    return self.post_bootstrap()
  File "/home/MyPC/Work/patroni1/patroni/ha.py", line 889, in post_bootstrap
    self.cancel_initialization()
  File "/home/MyPC/Work/patroni1/patroni/ha.py", line 884, in cancel_initialization
    raise PatroniException('Failed to bootstrap cluster')
patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'

-------------------------------------------------------------------------------------------------------------------------------
I am running etc Server on a different terminal

**Comment by CyberDem0n** [comment]
```
File "/home/MyPC/Work/patroni1/patroni/postgresql.py", line 263, in pg_ctl
return subprocess.call(pg_ctl + ['-D', self._data_dir] + list(args), **kwargs) == 0
File "/usr/lib/python2.7/subprocess.py", line 168, in call
return Popen(*popenargs, **kwargs).wait()
File "/usr/lib/python2.7/subprocess.py", line 390, in init
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory
```

Patroni can't find postgres binaries. Either you should change PATH: `export PATH=/path/to/postgres/bin:$PATH` or change patroni config file:
```yaml
postgresql:
  bin_dir: /path/to/postgres/bin
```

`/path/to/postgres/bin` - is the place where all postgres binaries (postgres, pg_ctl, initdb, pg_controldata, etc...) are located.

**Comment by shubham399** [comment]
I have included /usr/lib/postgresql/9.6/bin in the PATH 


echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/lib/postgresql/9.6/bin/


It is still throwing the same error


./patroni.py postgres0.yml 
2017-08-01 17:08:57,312 INFO: Selected new etcd server http://127.0.0.1:2379
2017-08-01 17:08:57,337 INFO: Lock owner: None; I am postgresql0
2017-08-01 17:08:57,375 INFO: trying to bootstrap a new cluster
pg_ctl: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that will
own the server process.
2017-08-01 17:08:57,443 INFO: removing initialize key after failed attempt to bootstrap the cluster
2017-08-01 17:08:57,836 ERROR: 
Traceback (most recent call last):
  File "/home/MyPC/Work/patroni1/patroni/dcs/etcd.py", line 329, in wrapper
    retval = func(self, *args, **kwargs) is not None
  File "/home/MyPC/Work/patroni1/patroni/dcs/etcd.py", line 511, in delete_leader
    return self._client.delete(self.leader_path, prevValue=self._name)
  File "/home/MyPC/.local/lib/python2.7/site-packages/etcd/client.py", line 645, in delete
    self.key_endpoint + key, self._MDELETE, params=kwds)
  File "/home/MyPC/Work/patroni1/patroni/dcs/etcd.py", line 211, in api_execute
    return self._handle_server_response(response)
  File "/home/MyPC/.local/lib/python2.7/site-packages/etcd/client.py", line 987, in _handle_server_response
    etcd.EtcdError.handle(r)
  File "/home/MyPC/.local/lib/python2.7/site-packages/etcd/__init__.py", line 306, in handle
    raise exc(msg, payload)
EtcdKeyNotFound: Key not found : /service/batman/leader
Traceback (most recent call last):
  File "./patroni.py", line 6, in <module>
    main()
  File "/home/MyPC/Work/patroni1/patroni/__init__.py", line 173, in main
    return patroni_main()
  File "/home/MyPC/Work/patroni1/patroni/__init__.py", line 142, in patroni_main
    patroni.run()
  File "/home/MyPC/Work/patroni1/patroni/__init__.py", line 114, in run
    logger.info(self.ha.run_cycle())
  File "/home/MyPC/Work/patroni1/patroni/ha.py", line 1056, in run_cycle
    info = self._run_cycle()
  File "/home/MyPC/Work/patroni1/patroni/ha.py", line 982, in _run_cycle
    return self.post_bootstrap()
  File "/home/MyPC/Work/patroni1/patroni/ha.py", line 889, in post_bootstrap
    self.cancel_initialization()
  File "/home/MyPC/Work/patroni1/patroni/ha.py", line 884, in cancel_initialization
    raise PatroniException('Failed to bootstrap cluster')
patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'

**Comment by CyberDem0n** [comment]
> pg_ctl: cannot be run as root
> Please log in (using, e.g., "su") as the (unprivileged) user that will own the server process.

I believe error is pretty clear and verbose.
You shouldn't run neither patroni nor postgres as a root.

**Comment by shubham399** [comment]
Sorry Didn't Read that....
Didn't checked that LOL

well working fine Now
Thanks
