### ISSUE TITLE
TypeError: an integer is required in Watchdog

### ISSUE THREAD

**Issue by bradnicholson** [zalando/patroni#498]
/dev/watchdog is not available on the system I am running, so I disable the watchdog in
 patroni.yaml

```
  watchdog:
     mode: off
```

Despite being disabled, I still see:

```
2017-08-01 13:08:48,677 WARNING: Could not activate Linux watchdog device: "Can't open watchdog device: [Errno 2] No such file or directory: '/dev/watchdog'"
```

And then later on, a Type error in the watchdog code.

```2017-08-01 13:09:43,135 INFO: Selected new etcd server http://10.211.205.132:4001
 2017-08-01 13:09:43,152 WARNING: Postgresql is not running.
 2017-08-01 13:09:43,152 INFO: Lock owner: postgresql290; I am postgresql290
 Traceback (most recent call last):
   File "/app/scripts/patroni", line 6, in <module>
     main()
   File "/app/patroni-1.3.2/patroni/__init__.py", line 173, in main
     return patroni_main()
   File "/app/patroni-1.3.2/patroni/__init__.py", line 142, in patroni_main
     patroni.run()
   File "/app/patroni-1.3.2/patroni/__init__.py", line 114, in run
     logger.info(self.ha.run_cycle())
   File "/app/patroni-1.3.2/patroni/ha.py", line 1056, in run_cycle
     info = self._run_cycle()
   File "/app/patroni-1.3.2/patroni/ha.py", line 1023, in _run_cycle
     return self.recover()
   File "/app/patroni-1.3.2/patroni/ha.py", line 182, in recover
     if self.has_lock() and self.update_lock():
   File "/app/patroni-1.3.2/patroni/ha.py", line 90, in update_lock
     self.watchdog.keepalive()
   File "/app/patroni-1.3.2/patroni/watchdog/base.py", line 36, in wrapped
     return func(self, *args, **kwargs)
   File "/app/patroni-1.3.2/patroni/watchdog/base.py", line 205, in keepalive
     self.impl.keepalive()
   File "/app/patroni-1.3.2/patroni/watchdog/linux.py", line 190, in keepalive
     os.write(self._fd, b'1')
 TypeError: an integer is required```

**Comment by alexeyklyukin** [comment]
Hi,

Could you, please, post the complete patroni.yaml? It looks weird that despite the watchdog being disabled, Patroni still tries to use the the Linux watchdog implementation.

**Comment by bradnicholson** [comment]
In checking the patroni.yaml, I realized this was caused by an indentation issue on the watchdog disabling.  It was at the wrong indention level and being ignored.  Fixing the indent level fixed this.

**Comment by ants** [comment]
On my todo list is implementing a type checker for the config system so we
get better error messages. When training, subtle yaml syntax issues was one
of the most frequent and confusing hurdles.
