### ISSUE TITLE
Question about consul leader changes

### ISSUE THREAD

**Issue by disco-stu** [zalando/patroni#501]
Hi,

first of all thank you for patroni it's great :)

However, I've a question for some sort of python backtraces within a setup containing consul as source of truth. My Setup:

  - 7x consul nodes (3x in dc1, 3 in dc2, 1x in dc3) [c1 - c7]
  - 4x PostgreSQL nodes (2x in dc1, 2x in dc2) [pg1 - pg2]
  - 4x consul clients (running on pg1 - pg4)

I don't use the consul datacenter / wan feature.

AFAICS all actions run fine except consul leader changes. E.g.: 

  1. c1 is the consul leader and all other consul nodes are following c1
  2. c1 goes down
  3. c3 promotes to the new cluster leader (a few seconds later)

Sometimes patroni shows timeouts [1] which sometimes leads to a restart of PostgreSQL. Is this expected behavior?

I'm running the following versions:
  - Ubuntu Server 16.04 LTS
  - consul: 0.9.1
  - patroni: 1.1
  - python-consul: 0.6.0
  - PostgreSQL 9.6.3

Please let me know if you need any further information.

[1]
```
017-08-10 14:14:11,216 INFO: Lock owner: pgsql-a-01; I am pgsql-a-02
2017-08-10 14:14:11,216 INFO: does not have lock
2017-08-10 14:14:11,217 INFO: no action.  i am a secondary and i am following a leader
2017-08-10 14:14:21,102 ERROR: watch
Traceback (most recent call last):
  File "/home/avo/patroni-1.1/patroni/dcs/consul.py", line 258, in watch
    idx, _ = self._client.kv.get(self.leader_path, index=cluster.leader.index, wait=str(timeout) + 's')
  File "/usr/local/lib/python2.7/dist-packages/consul/base.py", line 431, in get
    callback, '/v1/kv/%s' % key, params=params)
  File "/home/avo/patroni-1.1/patroni/dcs/consul.py", line 51, in get
    return callback(self.response(self.session.get(self.uri(path, params), verify=self.verify, timeout=timeout)))
  File "/usr/local/lib/python2.7/dist-packages/consul/base.py", line 417, in callback
    raise ConsulException(response.body)
ConsulException: rpc error: rpc error: EOF
2017-08-10 14:14:28,222 ERROR: get_cluster
Traceback (most recent call last):
  File "/home/avo/patroni-1.1/patroni/dcs/consul.py", line 130, in _load_cluster
    _, results = self._client.kv.get(path, recurse=True)
  File "/usr/local/lib/python2.7/dist-packages/consul/base.py", line 431, in get
    callback, '/v1/kv/%s' % key, params=params)
  File "/home/avo/patroni-1.1/patroni/dcs/consul.py", line 51, in get
    return callback(self.response(self.session.get(self.uri(path, params), verify=self.verify, timeout=timeout)))
  File "/usr/local/lib/python2.7/dist-packages/consul/base.py", line 417, in callback
    raise ConsulException(response.body)
ConsulException: rpc error: No cluster leader
2017-08-10 14:14:28,222 ERROR: Error communicating with DCS
2017-08-10 14:14:28,222 INFO: DCS is not accessible
2017-08-10 14:14:31,631 INFO: Lock owner: pgsql-a-01; I am pgsql-a-02
2017-08-10 14:14:31,631 INFO: does not have lock
2017-08-10 14:14:31,631 INFO: no action.  i am a secondary and i am following a leader
2017-08-10 14:14:42,094 INFO: Lock owner: pgsql-a-01; I am pgsql-a-02
2017-08-10 14:14:42,094 INFO: does not have lock
```

Thanks in advance.
Adrian

**Comment by CyberDem0n** [comment]
Hi @disco-stu,

you are running very old patroni version: 1.1.

Those days Patroni wasn't retrying failing requests to consul cluster.
Please upgrade to 1.3.3 it should help.

If consul is not accessible or not healthy, Patroni will try to re-execute the same request multiple times during `retry_timeout` (default value is 10 seconds). If after 10 seconds request is still failing Patroni will restart master in read-only.

**Comment by disco-stu** [comment]
Oh ...
I've downloaded the latest "release" from https://github.com/zalando/patroni/releases and didn't noticed the newer tags. 

Sorry for the noise. I will update my installation.

Thanks,
Adrian
