### ISSUE TITLE
TypeError Exception generated by Linux watchdog implementatiom

### ISSUE THREAD

**Issue by akissa** [zalando/patroni#508]
It seems writing to the fd should be an integer not a bytes string. When `keepalive` is called in `watchdog/linux.py` it generates a `TypeError` Exception.

Full traceback is below.
```
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/bin/patroni", line 11, in <module>
    load_entry_point('patroni==1.3.3', 'console_scripts', 'patroni')()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/patroni/__init__.py", line 173, in main
    return patroni_main()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/patroni/__init__.py", line 142, in patroni_main
    patroni.run()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/patroni/__init__.py", line 114, in run
    logger.info(self.ha.run_cycle())
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/patroni/ha.py", line 1069, in run_cycle
    info = self._run_cycle()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/patroni/ha.py", line 1042, in _run_cycle
    msg = self.process_healthy_cluster()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/patroni/ha.py", line 697, in process_healthy_cluster
    if self.update_lock(True):
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/patroni/ha.py", line 90, in update_lock
    self.watchdog.keepalive()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/patroni/watchdog/base.py", line 36, in wrapped
    return func(self, *args, **kwargs)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/patroni/watchdog/base.py", line 205, in keepalive
    self.impl.keepalive()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/patroni/watchdog/linux.py", line 190, in keepalive
    os.write(self._fd, b'1')
TypeError: an integer is required
```

**Comment by CyberDem0n** [comment]
It's a known problem, https://github.com/zalando/patroni/pull/507 fixes it.

**Comment by akissa** [comment]
Thanks
