### ISSUE TITLE
DCS consul connection fails with https and client auth enabled.

### ISSUE THREAD

**Issue by akissa** [zalando/patroni#509]
I have a patched 1.3.3 with #506 included.

* Consul config

```
consul:
  url: https://192.168.1.15:8500
  verify: true
  cacert: /etc/pki/postgresql-ca/postgresql-ca.crt
  cert: /etc/pki/postgresql/certs/db.dc1.consul.pem
  key: /etc/pki/postgresql/private/db.dc1.consul.key
```

* Patroni log

```
017-08-25 18:39:01,267 INFO: Starting new HTTPS connection (5): 192.168.1.15
2017-08-25 18:39:02,484 INFO: Starting new HTTPS connection (6): 192.168.1.15
2017-08-25 18:39:04,080 INFO: Starting new HTTPS connection (7): 192.168.1.15
2017-08-25 18:39:05,474 INFO: Starting new HTTPS connection (8): 192.168.1.15
2017-08-25 18:39:07,234 INFO: Starting new HTTPS connection (9): 192.168.1.15
2017-08-25 18:39:07,282 ERROR: refresh_session
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/patroni/dcs/consul.py", line 196, in refresh_session
    return self.retry(self._do_refresh_session)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/patroni/dcs/consul.py", line 158, in retry
    return self._retry.copy()(*args, **kwargs)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/patroni/utils.py", line 268, in __call__
    raise RetryFailedError("Exceeded retry deadline")
RetryFailedError: 'Exceeded retry deadline'
2017-08-25 18:39:07,282 INFO: waiting on consul
2017-08-25 18:39:12,288 INFO: Starting new HTTPS connection (10): 192.168.1.15
2017-08-25 18:39:12,723 INFO: Starting new HTTPS connection (11): 192.168.1.15
```

* Curl testing

The certificates are correctly created. Testing with curl works correctly.

```
curl -v --key /etc/pki/postgresql/private/db.dc1.consul.key --cert /etc/pki/postgresql/certs/db.dc1.consul.pem --cacert /etc/pki/postgresql-ca/postgresql-ca.crt https://192.168.1.15:8500
* About to connect() to 192.168.1.15 port 8500 (#0)
*   Trying 192.168.1.15... connected
* Connected to 192.168.1.15 (192.168.1.15) port 8500 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/postgresql-ca/postgresql-ca.crt
  CApath: none
* NSS: client certificate from file
* 	subject: CN=server.dc1.consul
* 	start date: Aug 25 13:39:57 2017 GMT
* 	expire date: Aug 23 13:39:57 2027 GMT
* 	common name: server.dc1.consul
* 	issuer: CN=Baruwa PostgreSQL CA
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=server.dc1.consul
* 	start date: Aug 25 13:39:57 2017 GMT
* 	expire date: Aug 23 13:39:57 2027 GMT
* 	common name: server.dc1.consul
* 	issuer: CN=Baruwa PostgreSQL CA
> GET / HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: 192.168.1.15:8500
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Fri, 25 Aug 2017 16:50:04 GMT
< Content-Length: 12
< Content-Type: text/plain; charset=utf-8

```

* OpenSSL test output

```
openssl x509 -text -noout -in /etc/pki/postgresql/certs/db.dc1.consul.pem 
Certificate:
    Data:
        Version: 3 (0x2)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=Baruwa PostgreSQL CA
        Validity
            Not Before: Aug 25 13:39:57 2017 GMT
            Not After : Aug 23 13:39:57 2027 GMT
        Subject: CN=server.dc1.consul
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Key Usage: 
                Digital Signature, Non Repudiation, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Subject Key Identifier: 
                67:86:97:9D:98:04:63:5C:66:D4:90:FD:FD:50:7F:87:0C:FA:AD:94
            X509v3 Authority Key Identifier: 
                keyid:A0:D5:65:19:B9:9C:07:9E:A1:59:2F:C3:A6:B5:B2:2C:FF:91:3E:AD
                DirName:/CN=Baruwa PostgreSQL CA
                serial:5E:81:53:E4:16:84:23:E3
            X509v3 Subject Alternative Name: 
                DNS:server.dc1.consul, DNS:db.dc1.consul, IP Address:192.168.1.15
```

From the logs it is hard to tell what the actual issue is.

**Comment by CyberDem0n** [comment]
What version of urllib3 do you have?
Can you try it with `urllib3>=1.19.1,!=1.21`?

**Comment by akissa** [comment]
@CyberDem0n Thanks, i had 1.10.2, updated to 1.22 and the actual error was then logged.

`2017-08-26 11:24:06,191 ERROR: Certificate did not match expected hostname: 192.168.1.15. Certificate: {'subjectAltName': (('DNS', 'server.dc1.consul'), ('DNS', 'db.dc1.consul'), ('IP Address', '192.168.1.15')), 'notBefore': u'Aug 25 13:39:57 2017 GMT', 'serialNumber': u'E3DA8DF34BDF9F17', 'notAfter': 'Aug 23 13:39:57 2027 GMT', 'version': 3L, 'subject': ((('commonName', u'server.dc1.consul'),),), 'issuer': ((('commonName', u'Baruwa PostgreSQL CA'),),)}`

The above was surprising given `192.168.1.15` is in the `subjectaltname`. I traced the issue to the
`backports.ssl_match_hostname` where i determined that the `match_hostname` function was returning the incorrectly because the `ipaddress` module was not installed.

Hope the above helps someone else on 2.7, Python 3.x will not exhibit the above issues because the `ipaddress` and  `ssl_match_hostname` are standard modules on that.

**Comment by danielkucera** [comment]
I'm facing similar issue.
IMHO patroni should validate the server certificate against provided CA and only check if it contains `Subject Alternative Name == server.<DC>.consul` no matter what the provided `hostname: ` or `url:` was set in config.
See: 
- https://learn.hashicorp.com/consul/security-networking/certificates#step-2-create-individual-server-certificates
- https://www.consul.io/docs/agent/encryption.html#rpc-encryption-with-tls)

I understand this can be quite complicated to achieve with python SSL implementation so I used a workaround: I use url in format `url: "https://server.<DC>.consul:8501"` and I set the IP - hostname mapping in `/etc/hosts`

**Comment by akissa** [comment]
What is the actual issue, recent patroni versions seem to require the `cacert` key under `ctl`.

**Comment by danielkucera** [comment]
I have used IP address for connecting but the cert doesn't contain it:
```
2019-06-07 13:09:36,452 - WARNING - Retry got exception: HTTPSConnectionPool(host='1.2.3.4', port=8501): Max retries exceeded with url: /v1/kv/service/<url>/?recurse=1 (Caused by SSLError(CertificateError("hostname '1.2.3.4' doesn't match either of 'server.<DC>.consul', 'localhost', '127.0.0.1'",),))
2019-06-07 13:09:37,939 - ERROR - Certificate did not match expected hostname: 1.2.3.4. Certificate: {'subjectAltName': (('DNS', 'server.<DC>.consul'), ('DNS', 'localhost'), ('IP Address', '127.0.0.1')), 'notBefore': u'Mar  4 08:20:34 2019 GMT', 'serialNumber': u'0CEB74D17DF2CE09AE506DDBE9750353', 'notAfter': 'Mar  3 08:20:34 2020 GMT', 'version': 3L, 'subject': ((('commonName', u'server.<DC>.consul'),),), 'issuer': ((('countryName', u'US'),), (('stateOrProvinceName', u'CA'),), (('localityName', u'San Francisco'),), (('streetAddress', u'101 Second Street'),), (('postalCode', u'94105'),), (('organizationName', u'HashiCorp Inc.'),), (('commonName', u'Consul Agent CA 44165242489416134775268322771154671053'),))}
```

**Comment by akissa** [comment]
If you want to use the IP address the certificate needs to cover it.
