### ISSUE TITLE
Can not find suitable configuration of distributed configuration store

### ISSUE THREAD

**Issue by nitrogear** [zalando/patroni#511]
Fresh Ubuntu 16.04 installation, installed postgres 9.6, cloned repo, installed requirements.
Executed etcd:
etcd --data-dir=data/etcd
and then ./patroni.py postgres0.yml
> 2017-08-29 20:34:23,265 INFO: Failed to import patroni.dcs.consul
> 2017-08-29 20:34:23,266 INFO: Failed to import patroni.dcs.etcd
> 2017-08-29 20:34:23,267 INFO: Failed to import patroni.dcs.exhibitor
> 2017-08-29 20:34:23,267 INFO: Failed to import patroni.dcs.zookeeper
> Traceback (most recent call last):
>   File "./patroni.py", line 6, in <module>
>     main()
>   File "/opt/patroni/patroni/__init__.py", line 173, in main
>     return patroni_main()
>   File "/opt/patroni/patroni/__init__.py", line 140, in patroni_main
>     patroni = Patroni()
>   File "/opt/patroni/patroni/__init__.py", line 25, in __init__
>     self.dcs = get_dcs(self.config)
>   File "/opt/patroni/patroni/dcs/__init__.py", line 74, in get_dcs
>     Available implementations: """ + ', '.join(available_implementations))
> patroni.exceptions.PatroniException: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: '

Any idea why patroni couldn't find etcd?

**Comment by CyberDem0n** [comment]
> Any idea why patroni couldn't find etcd?

`pip install -r requirements.txt`

**Comment by nitrogear** [comment]
Sorry, it seems I have missed installations of python dependencies. Now they are Installed.
```
Python 2.7.12
pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
boto==2.48.0
cdiff==1.0
chardet==2.3.0
click==6.7
cryptography==1.2.3
dnspython==1.15.0
enum34==1.1.2
idna==2.0
ipaddress==1.0.16
kazoo==2.2.1
ndg-httpsclient==0.4.0
prettytable==0.7.2
psutil==3.4.2
psycopg2==2.6.1
pyasn1==0.1.9
pycrypto==2.6.1
pyOpenSSL==0.15.1
python-consul==0.7.2
python-dateutil==2.4.2
python-etcd==0.4.5
pytz==2017.2
PyYAML==3.11
requests==2.9.1
six==1.10.0
tzlocal==1.4
urllib3==1.13.1
```
But another error appeared:
```
./patroni.py postgres0.yml
2017-08-30 08:41:57,528 INFO: Selected new etcd server http://127.0.0.1:2379
2017-08-30 08:41:57,529 INFO: Starting new HTTP connection (1): 127.0.0.1
2017-08-30 08:41:57,565 INFO: Lock owner: None; I am postgresql0
2017-08-30 08:41:57,622 ERROR: Exception during execution of long running task bootstrap
Traceback (most recent call last):
  File "/opt/patroni/patroni/async_executor.py", line 86, in run
    wakeup = func(*args) if args else func()
  File "/opt/patroni/patroni/postgresql.py", line 1559, in bootstrap
    return do_initialize(config) and self._configure_server_parameters() and self.start()
  File "/opt/patroni/patroni/postgresql.py", line 528, in _initdb
    ret = self.pg_ctl('initdb', *options)
  File "/opt/patroni/patroni/postgresql.py", line 274, in pg_ctl
    return subprocess.call(pg_ctl + ['-D', self._data_dir] + list(args), **kwargs) == 0
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
2017-08-30 08:41:57,641 INFO: trying to bootstrap a new cluster
2017-08-30 08:41:57,644 INFO: removing initialize key after failed attempt to bootstrap the cluster
2017-08-30 08:41:58,064 ERROR:
Traceback (most recent call last):
  File "/opt/patroni/patroni/dcs/etcd.py", line 329, in wrapper
    retval = func(self, *args, **kwargs) is not None
  File "/opt/patroni/patroni/dcs/etcd.py", line 511, in delete_leader
    return self._client.delete(self.leader_path, prevValue=self._name)
  File "/usr/local/lib/python2.7/dist-packages/etcd/client.py", line 645, in delete
    self.key_endpoint + key, self._MDELETE, params=kwds)
  File "/opt/patroni/patroni/dcs/etcd.py", line 211, in api_execute
    return self._handle_server_response(response)
  File "/usr/local/lib/python2.7/dist-packages/etcd/client.py", line 987, in _handle_server_response
    etcd.EtcdError.handle(r)
  File "/usr/local/lib/python2.7/dist-packages/etcd/__init__.py", line 306, in handle
    raise exc(msg, payload)
EtcdKeyNotFound: Key not found : /service/batman/leader
Traceback (most recent call last):
  File "./patroni.py", line 6, in <module>
    main()
  File "/opt/patroni/patroni/__init__.py", line 173, in main
    return patroni_main()
  File "/opt/patroni/patroni/__init__.py", line 142, in patroni_main
    patroni.run()
  File "/opt/patroni/patroni/__init__.py", line 114, in run
    logger.info(self.ha.run_cycle())
  File "/opt/patroni/patroni/ha.py", line 1070, in run_cycle
    info = self._run_cycle()
  File "/opt/patroni/patroni/ha.py", line 996, in _run_cycle
    return self.post_bootstrap()
  File "/opt/patroni/patroni/ha.py", line 901, in post_bootstrap
    self.cancel_initialization()
  File "/opt/patroni/patroni/ha.py", line 896, in cancel_initialization
    raise PatroniException('Failed to bootstrap cluster')
patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'
```
Should I use python3 or it python2 also could be used?

**Comment by akissa** [comment]
Patroni works on Python 2.7.

The above error is because the `initdb` command cannot be found. If it is not in the standard location then set the `bin_dir` option to point to the correct location

**Comment by nitrogear** [comment]
Thank you, it seems that on Ubuntu 16.04 "su - posgres" didn't add folder /usr/lib/postgresql/9.6/bin to PATH env variable
