### ISSUE TITLE
Crash while testing failover

### ISSUE THREAD

**Issue by cbandy** [zalando/patroni#514]
I'm testing Patroni `registry.opensource.zalan.do/acid/spilo-9.6:1.3-p3` failover in GKE `1.7.4` on Container-optimized OS `cos-stable-60-9592-84-0`.

When I `kill -9` the master container, it emitted the following stack trace when starting up again:
```
2017-09-07 19:58:11,187 INFO: Lock owner: thing-spilo-1; I am thing-spilo-1
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/patroni/__init__.py", line 173, in main
    return patroni_main()
  File "/usr/local/lib/python3.5/dist-packages/patroni/__init__.py", line 142, in patroni_main
    patroni.run()
  File "/usr/local/lib/python3.5/dist-packages/patroni/__init__.py", line 114, in run
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python3.5/dist-packages/patroni/ha.py", line 1056, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.5/dist-packages/patroni/ha.py", line 1023, in _run_cycle
    return self.recover()
  File "/usr/local/lib/python3.5/dist-packages/patroni/ha.py", line 182, in recover
    if self.has_lock() and self.update_lock():
  File "/usr/local/lib/python3.5/dist-packages/patroni/ha.py", line 90, in update_lock
    self.watchdog.keepalive()
  File "/usr/local/lib/python3.5/dist-packages/patroni/watchdog/base.py", line 36, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/patroni/watchdog/base.py", line 205, in keepalive
    self.impl.keepalive()
  File "/usr/local/lib/python3.5/dist-packages/patroni/watchdog/linux.py", line 190, in keepalive
    os.write(self._fd, b'1')
TypeError: an integer is required (got type NoneType)
```

Here's the beginning state and sequence of events (times from respective systems):
- `node` is the k8s node from which I killed master container
- `ubuntu` is another pod from which I am connecting using the k8s Service
- `spilo-1` is master
- `spilo-0` is replica

```
spilo-0: 2017-09-07 19:58:03,651 INFO: no action.  i am a secondary and i am following a leader
node:    2017-09-07 19:58:05.865583932+00:00 kill -9
ubuntu:  2017-09-07 19:58:05.950892294+00:00 psql: could not connect to server: Connection refused
spilo-1: 2017-09-07 19:58:07,614 - bootstrapping - INFO - Figuring out my environment (Google? AWS? Local?)
spilo-1: 2017-09-07 19:58:10,392 INFO spawned: 'patroni' with pid 26
spilo-1: 2017-09-07 19:58:11,186 WARNING: Postgresql is not running.
spilo-1: 2017-09-07 19:58:11,187 INFO: Lock owner: thing-spilo-1; I am thing-spilo-1
spilo-0: 2017-09-07 19:58:11,205 INFO: no action.  i am a secondary and i am following a leader
spilo-0: 2017-09-07 19:58:11,781 WARNING: request failed: GET http://10.8.2.11:8008/patroni (('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
spilo-1: 2017-09-07 19:58:11,818 INFO exited: patroni (exit status 1; not expected)
spilo-0: 2017-09-07 19:58:11,856 INFO: cleared rewind state after becoming the leader
spilo-0: 2017-09-07 19:58:11,876 INFO: promoted self to leader by acquiring session lock
ubuntu:  2017-09-07 19:58:12.261322036+00:00 client connected, no replica
spilo-1: 2017-09-07 19:58:12,820 INFO spawned: 'patroni' with pid 39
spilo-1: 2017-09-07 19:58:13,168 WARNING: Postgresql is not running.
spilo-1: 2017-09-07 19:58:13,169 INFO: Lock owner: thing-spilo-0; I am thing-spilo-1
ubuntu:  2017-09-07 19:58:14.386251467+00:00 client connected, one replica
```

**Comment by CyberDem0n** [comment]
I think it's a known problem and there are really high chances that is was already fixed in the master: https://github.com/zalando/patroni/pull/507/files#diff-4f3d729ab12256ce032ed72c4ecade94L205

Today we are going to release a new version of Patroni and build new docker image of Spilo.


BTW: may be you will be interested in testing of https://github.com/zalando/patroni/pull/500
It allows to run Patroni on Kubernetes without etcd. Basically it will use Kubernetes objects (configmaps and pods annotations) to keep cluster state and use Kubernetes API for leader elections.

[Here](https://github.com/zalando/patroni/tree/feature/k8s/kubernetes) you can find Dockerfile and a sample Kubernetes manifest (patroni_k8s.yaml) to deploy it.

**Comment by cbandy** [comment]
After switching to `registry.opensource.zalan.do/acid/spilo-9.6:1.3-p4` , I'm unable to reproduce this.
