### ISSUE TITLE
Patroni python3 watchdog problem

### ISSUE THREAD

**Issue by DeathBorn** [zalando/patroni#528]
Centos 7, python3
Using watchdog in configuration, the supposed to be leader does not properly start. Issue can be repeated by patronictl failover too. 
```
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: Traceback (most recent call last):
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: File "/usr/bin/patroni", line 11, in <module>
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: sys.exit(main())
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: File "/usr/lib/python3.4/site-packages/patroni/__init__.py", line 173, in main
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: return patroni_main()
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: File "/usr/lib/python3.4/site-packages/patroni/__init__.py", line 142, in patroni_main
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: patroni.run()
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: File "/usr/lib/python3.4/site-packages/patroni/__init__.py", line 114, in run
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: logger.info(self.ha.run_cycle())
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: File "/usr/lib/python3.4/site-packages/patroni/ha.py", line 1056, in run_cycle
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: info = self._run_cycle()
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: File "/usr/lib/python3.4/site-packages/patroni/ha.py", line 1027, in _run_cycle
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: return self.process_unhealthy_cluster()
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: File "/usr/lib/python3.4/site-packages/patroni/ha.py", line 657, in process_unhealthy_cluster
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: 'promoted self to leader by acquiring session lock')
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: File "/usr/lib/python3.4/site-packages/patroni/ha.py", line 345, in enforce_master_role
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: if not self.watchdog.activate():
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: File "/usr/lib/python3.4/site-packages/patroni/watchdog/base.py", line 36, in wrapped
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: return func(self, *args, **kwargs)
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: File "/usr/lib/python3.4/site-packages/patroni/watchdog/base.py", line 124, in activate
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: return self._activate()
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: File "/usr/lib/python3.4/site-packages/patroni/watchdog/base.py", line 144, in _activate
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: actual_timeout = self._set_timeout()
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: File "/usr/lib/python3.4/site-packages/patroni/watchdog/base.py", line 172, in _set_timeout
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: self.impl.set_timeout(self.config.timeout)
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: File "/usr/lib/python3.4/site-packages/patroni/watchdog/linux.py", line 202, in set_timeout
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: self._ioctl(WDIOC_SETTIMEOUT, ctypes.c_int(timeout))
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: File "/usr/lib/python3.4/site-packages/patroni/watchdog/linux.py", line 163, in _ioctl
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: if result < 0:
Sep 22 08:39:02 pgdron002d1vteo patroni[2707]: TypeError: unorderable types: bytes() < int()
```

**Comment by CyberDem0n** [comment]
Hi @DeathBorn,

what patroni version do you use?

**Comment by DeathBorn** [comment]
Sorry. Patroni 1.3.3. The same was with 1.3.4

**Comment by CyberDem0n** [comment]
@ants, I think this is something for you.

**Comment by ants** [comment]
Taking a look at it now. `fcntl.ioctl()` is somehow returning a `bytes` object. Python's documentation says that it is supposed to return an int...

**Comment by ants** [comment]
Pythons [HTML documentation](https://docs.python.org/3/library/fcntl.html#fcntl.ioctl) and [source code](https://github.com/python/cpython/blob/master/Modules/fcntlmodule.c#L110) don't match. Fix coming up soon, I need to dig through source history to see how this has changed over the versions.

Until the fix is available the workaround is to just disable watchdog in config:

    watchdog:
      mode: off
