### ISSUE TITLE
A few exceptions with patronictl when dcs is zookeeper

### ISSUE THREAD

**Issue by kostiantyn-nemchenko** [zalando/patroni#537]
Hi, 

I occasionally get the exceptions posted bellow.

```
postgres@ubuntu1604-02:~$ patronictl -c /etc/patroni/ubuntu1604-02.yml scaffold new_cluster
Cluster new_cluster has been created successfully
Exception in thread Thread-3 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/local/lib/python2.7/dist-packages/kazoo/protocol/connection.py", line 478, in zk_loop
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'CLOSED'
```

```
postgres@ubuntu1604-02:~$ patronictl -c /etc/patroni/ubuntu1604-02.yml edit-config main
Error: EDITOR environment variable is not set
Exception in thread Thread-3 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/local/lib/python2.7/dist-packages/kazoo/protocol/connection.py", line 477, in zk_loop
  File "/usr/lib/python2.7/threading.py", line 585, in set
  File "/usr/lib/python2.7/threading.py", line 407, in notifyAll
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

```
postgres@ubuntu1604-02:~$ patronictl -c /etc/patroni/ubuntu1604-02.yml list main
+---------+---------------+----------------+--------+---------+-----------+
| Cluster | Member        | Host           |  Role  |  State  | Lag in MB |
+---------+---------------+----------------+--------+---------+-----------+
| main    | ubuntu1604-01 | 192.168.56.101 |        | running |           |
| main    | ubuntu1604-02 | 192.168.56.102 |        | running |           |
| main    | ubuntu1604-03 | 192.168.56.103 | Leader | running |           |
+---------+---------------+----------------+--------+---------+-----------+
Exception in thread Thread-3 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/local/lib/python2.7/dist-packages/kazoo/protocol/connection.py", line 478, in zk_loop
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'CLOSED'
```

Here are my current environment details:
```
OS: Ubuntu 16.04.2 LTS
python: 2.7.12
patroni: 1.3.4
kazoo: 2.2.1
zookeeper: 3.4.9
```
And my config file:

```
scope: main
namespace: /service/
name: ubuntu1604-02

restapi:
  listen: 0.0.0.0:8008
  connect_address: 127.0.0.1:8008

zookeeper:
  hosts: 192.168.56.101:2181,192.168.56.102:2181,192.168.56.103:2181
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: False
    postgresql:
      use_pg_rewind: True
      use_slots: True
      parameters:
        max_connections: 1000
        max_locks_per_transaction: 64
        max_worker_processes: 8
        max_prepared_transactions: 0
        wal_level: 'replica'
        wal_log_hints: 'on'
        track_commit_timestamp: 'off'
        max_wal_senders: 5
        max_replication_slots: 5
        wal_keep_segments: 0
  initdb:
    - encoding: UTF8
    - locale: UTF8
    - data-checksums
  users:
    postgres:
      password: supersecretpostgrespasswd
    replicator:
      password: repuserpasswd
      options:
        - replication

postgresql:
  authentication:
    superuser:
      username: postgres
      password: supersecretpostgrespasswd
    replication:
      username: replicator
      password: repuserpasswd
  callbacks:
  connect_address: 192.168.56.102:5432
  create_replica_methods:
    - basebackup
  data_dir: /var/lib/postgresql/9.6/main
  config_dir: /etc/postgresql/9.6/main
  bin_dir: /usr/lib/postgresql/9.6/bin
  listen: 0.0.0.0:5432
  use_unix_socket: True
  pgpass: /var/lib/postgresql/.pgpass
  parameters:
    unix_socket_directories: '/var/run/postgresql'
  pg_ctl_timeout: 60
  use_pg_rewind: true
  pg_rewind:
    username: postgres
    password: supersecretpostgrespasswd
  remove_data_directory_on_rewind_failure: True

watchdog:
  mode: automatic
  device: /dev/watchdog
  safety_margin: -1

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

Hope this helps. Let me know if you need anything else.
Thanks in advance.

**Comment by CyberDem0n** [comment]
I think you are hitting the same issues as here: https://github.com/zalando/patroni/issues/411

**Comment by kostiantyn-nemchenko** [comment]
@CyberDem0n 
Thanks for your quick feedback.
I'm sorry that I wasted your time.
Will pay more attention to closed issues next time.
