### ISSUE TITLE
Patroni Fails installation due to failing dependency

### ISSUE THREAD

**Issue by DeathBorn** [zalando/patroni#540]
Patroni fails installation 

```
pip install patroni
Collecting patroni
  Using cached patroni-1.3.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-BEp9us/patroni/setup.py", line 158, in <module>
        setup_package()
      File "/tmp/pip-build-BEp9us/patroni/setup.py", line 153, in setup_package
        entry_points={'console_scripts': CONSOLE_SCRIPTS},
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 335, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 456, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 863, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1141, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1153, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 522, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 672, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 698, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 879, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1118, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1104, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 257, in run_setup
        raise
      File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 199, in setup_context
        yield
      File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 170, in save_modules
        saved_exc.resume()
      File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 145, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 158, in save_modules
        yield saved
      File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 199, in setup_context
        yield
      File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 254, in run_setup
        _execfile(setup_script, ns)
      File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 49, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-KXiVek/flake8-3.4.1/setup.py", line 142, in <module>
        keywords=KEYWORDS,
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 335, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 456, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 863, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1141, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1153, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 522, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 660, in easy_install
        not self.always_copy, self.local_index
      File "/usr/lib/python2.7/site-packages/setuptools/package_index.py", line 635, in fetch_distribution
        self.find_packages(requirement)
      File "/usr/lib/python2.7/site-packages/setuptools/package_index.py", line 476, in find_packages
        self.scan_url(self.index_url + requirement.unsafe_name + '/')
      File "/usr/lib/python2.7/site-packages/setuptools/package_index.py", line 808, in scan_url
        self.process_url(url, True)
      File "/usr/lib/python2.7/site-packages/setuptools/package_index.py", line 348, in process_url
        page = f.read()
      File "/usr/lib64/python2.7/socket.py", line 351, in read
        data = self._sock.recv(rbufsize)
      File "/usr/lib64/python2.7/httplib.py", line 602, in read
        s = self.fp.read(amt)
      File "/usr/lib64/python2.7/socket.py", line 380, in read
        data = self._sock.recv(left)
      File "/usr/lib64/python2.7/ssl.py", line 759, in recv
        return self.read(buflen)
      File "/usr/lib64/python2.7/ssl.py", line 653, in read
        v = self._sslobj.read(len or 1024)
    socket.error: [Errno 104] Connection reset by peer
```

This ```pip install pyopenssl``` fixes it. Maybe it should be added to requirements file.

**Comment by CyberDem0n** [comment]
Hi @DeathBorn,

sorry for the late response, from the Traceback I could see only pip failure, it is not really a problem with patroni module. The same way it will fail to install any other modules.

**Comment by DeathBorn** [comment]
It is ok. I found the issue, but forgot to close this one. Sorry.
