### ISSUE TITLE
Patroni consul token configuration is not picked

### ISSUE THREAD

**Issue by DeathBorn** [zalando/patroni#552]
Patroni 1.3.5
both python2 and python3
patroni.yml
```
consul:
  url: "http://consul.service.discovery.zone:8500"
  token: "some-token"
```
This token is not picked in https://github.com/zalando/patroni/blob/master/patroni/dcs/consul.py#L86
Judging by https://github.com/cablehead/python-consul/blob/v0.7.2/consul/base.py#L1633
token is not passed here at all. 
(this is a stack trace (I have modified some code in patroni/dcs/consul and consul/base by adding some logging so the actual lines are a bit further) )
```
Oct 31 16:11:25 zhost001 patroni[14900]: Traceback (most recent call last):
Oct 31 16:11:25 zhost001 patroni[14900]: File "/usr/lib/python2.7/site-packages/patroni/dcs/consul.py", line 230, in refresh_session
Oct 31 16:11:25 zhost001 patroni[14900]: return self.retry(self._do_refresh_session)
Oct 31 16:11:25 zhost001 patroni[14900]: File "/usr/lib/python2.7/site-packages/patroni/dcs/consul.py", line 191, in retry
Oct 31 16:11:25 zhost001 patroni[14900]: return self._retry.copy()(*args, **kwargs)
Oct 31 16:11:25 zhost001 patroni[14900]: File "/usr/lib/python2.7/site-packages/patroni/utils.py", line 259, in __call__
Oct 31 16:11:25 zhost001 patroni[14900]: return func(*args, **kwargs)
Oct 31 16:11:25 zhost001 patroni[14900]: File "/usr/lib/python2.7/site-packages/patroni/dcs/consul.py", line 224, in _do_refresh_session
Oct 31 16:11:25 zhost001 patroni[14900]: lock_delay=0.001, behavior='delete')
Oct 31 16:11:25 zhost001 patroni[14900]: File "/usr/lib/python2.7/site-packages/consul/base.py", line 1711, in create
Oct 31 16:11:25 zhost001 patroni[14900]: data=data)
Oct 31 16:11:25 zhost001 patroni[14900]: File "/usr/lib/python2.7/site-packages/patroni/dcs/consul.py", line 101, in wrapper
Oct 31 16:11:25 zhost001 patroni[14900]: return callback(self.response(self.http.request(method.upper(), self.uri(path, params), **kwargs)))
Oct 31 16:11:25 zhost001 patroni[14900]: File "/usr/lib/python2.7/site-packages/consul/base.py", line 207, in cb
Oct 31 16:11:25 zhost001 patroni[14900]: CB.__status(response, allow_404=allow_404)
Oct 31 16:11:25 zhost001 patroni[14900]: File "/usr/lib/python2.7/site-packages/consul/base.py", line 170, in __status
Oct 31 16:11:25 zhost001 patroni[14900]: raise ACLPermissionDenied(response.body)
Oct 31 16:11:25 zhost001 patroni[14900]: ACLPermissionDenied: rpc error: Permission denied
Oct 31 16:11:25 zhost001 patroni[14900]: 2017-10-31 16:11:25,068 INFO: waiting on consul            
```

**Comment by DeathBorn** [comment]
Also https://github.com/cablehead/python-consul/issues/170

**Comment by CyberDem0n** [comment]
Interesting "feature" of python-consul.
It is trying to be "consistent" with consul REST API, which doesn't accept token as a query parameter for session API: https://www.consul.io/api/session.html, but it will still work with 'X-Consul-Token' header (I believe).

Fix is very simple, if there is a "token" defined in consul configuration, we should always send its value in the 'X-Consul-Token' http header.
