### ISSUE TITLE
Problem starting sample configuration with "./patroni.py postgres0.yml"

### ISSUE THREAD

**Issue by laurenz** [zalando/patroni#563]
In installed all the prerequisites and started etcd.

When I run the command, I get:

    2017-11-15 16:08:15,208 INFO: Selected new etcd server http://127.0.0.1:2379
    2017-11-15 16:08:15,237 INFO: Lock owner: None; I am postgresql0
    2017-11-15 16:08:15,247 INFO: trying to bootstrap a new cluster
    The files belonging to this database system will be owned by user "laurenz".
    This user must also own the server process.
 
    The database cluster will be initialized with locale "en_US.UTF-8".
    The default text search configuration will be set to "english".
 
    Data page checksums are enabled.
 
    creating directory data/postgresql0 ... ok
    creating subdirectories ... ok
    selecting default max_connections ... 100
    selecting default shared_buffers ... 128MB
    selecting dynamic shared memory implementation ... posix
    creating configuration files ... ok
    running bootstrap script ... ok
    performing post-bootstrap initialization ... ok
    syncing data to disk ... ok
 
    WARNING: enabling "trust" authentication for local connections
    You can change this by editing pg_hba.conf or using the option -A, or
    --auth-local and --auth-host, the next time you run initdb.
 
    Success. You can now start the database server using:
 
        /usr/pgsql-10/bin/pg_ctl -D data/postgresql0 -l logfile start
 
    2017-11-15 16:08:18,382 INFO: postmaster pid=11781
    2017-11-15 16:08:18.396 CET [11781] LOG:  could not bind IPv4 address "127.0.0.1": Address already in use
    2017-11-15 16:08:18.396 CET [11781] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
    2017-11-15 16:08:18.396 CET [11781] WARNING:  could not create listen socket for "127.0.0.1"
    2017-11-15 16:08:18.396 CET [11781] FATAL:  could not create any TCP/IP sockets
    2017-11-15 16:08:18.396 CET [11781] LOG:  database system is shut down
    2017-11-15 16:08:19,387 ERROR: postmaster is not running
    2017-11-15 16:08:19,396 INFO: removing initialize key after failed attempt to bootstrap the cluster
    2017-11-15 16:08:19,401 INFO: renaming data directory to data/postgresql0_2017-11-15-16-08-19
    2017-11-15 16:08:19,745 ERROR:
    Traceback (most recent call last):
      File "/home/laurenz/patroni/patroni/dcs/etcd.py", line 329, in wrapper
        retval = func(self, *args, **kwargs) is not None
      File "/home/laurenz/patroni/patroni/dcs/etcd.py", line 511, in delete_leader
        return self._client.delete(self.leader_path, prevValue=self._name)
      File "/usr/lib/python2.7/site-packages/etcd/client.py", line 645, in delete
        self.key_endpoint + key, self._MDELETE, params=kwds)
      File "/home/laurenz/patroni/patroni/dcs/etcd.py", line 211, in api_execute
        return self._handle_server_response(response)
      File "/usr/lib/python2.7/site-packages/etcd/client.py", line 987, in _handle_server_response
        etcd.EtcdError.handle(r)
      File "/usr/lib/python2.7/site-packages/etcd/__init__.py", line 306, in handle
        raise exc(msg, payload)
    EtcdKeyNotFound: Key not found : /service/batman/leader
    Traceback (most recent call last):
      File "./patroni.py", line 6, in <module>
        main()
      File "/home/laurenz/patroni/patroni/__init__.py", line 174, in main
        return patroni_main()
      File "/home/laurenz/patroni/patroni/__init__.py", line 143, in patroni_main
        patroni.run()
      File "/home/laurenz/patroni/patroni/__init__.py", line 114, in run
        logger.info(self.ha.run_cycle())
      File "/home/laurenz/patroni/patroni/ha.py", line 1092, in run_cycle
        info = self._run_cycle()
      File "/home/laurenz/patroni/patroni/ha.py", line 1016, in _run_cycle
        return self.post_bootstrap()
      File "/home/laurenz/patroni/patroni/ha.py", line 921, in post_bootstrap
        self.cancel_initialization()
      File "/home/laurenz/patroni/patroni/ha.py", line 916, in cancel_initialization
        raise PatroniException('Failed to bootstrap cluster')
    patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'

What might be the problem?

**Comment by ants** [comment]
Is another postgres running on port 5432 perhaps? The stack trace at the end is a pointless error that we should avoid getting and/or handle with a nicer message and/or suppress.

**Comment by laurenz** [comment]
Thanks, that was indeed the problem.

A better error message would be nice!
