### ISSUE TITLE
patroni always fail with "No such file or directory"

### ISSUE THREAD

**Issue by easyjohn** [zalando/patroni#569]
Each patroni start fails with "OSError: [Errno 2] No such file or directory", but nowhere is described which path is wrong.

# ./patroni.py ./postgres0.yml 
2017-12-05 13:28:16,626 INFO: Selected new etcd server http://127.0.0.1:2379
2017-12-05 13:28:16,626 INFO: Starting new HTTP connection (1): 127.0.0.1
2017-12-05 13:28:16,637 INFO: Lock owner: None; I am postgresql0
2017-12-05 13:28:16,651 INFO: trying to bootstrap a new cluster
2017-12-05 13:28:16,652 ERROR: Exception during execution of long running task bootstrap
Traceback (most recent call last):
  File "/opt/patroni/patroni/async_executor.py", line 86, in run
    wakeup = func(*args) if args else func()
  File "/opt/patroni/patroni/postgresql.py", line 1472, in bootstrap
    return do_initialize(config) and self._configure_server_parameters() and self.start()
  File "/opt/patroni/patroni/postgresql.py", line 523, in _initdb
    ret = self.pg_ctl('initdb', *options)
  File "/opt/patroni/patroni/postgresql.py", line 269, in pg_ctl
    return subprocess.call(pg_ctl + ['-D', self._data_dir] + list(args), **kwargs) == 0
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
2017-12-05 13:28:16,655 INFO: removing initialize key after failed attempt to bootstrap the cluster

**Comment by CyberDem0n** [comment]
Patroni can't find `pg_ctl` binary. Please make sure that all postgres binaries (postgres, pg_ctl, initdb, pg_rewind, pg_controldata, pg_basebackup and so on) either available in default PATH, or you have to set `postgresql.bin_dir` parameter to the place where those binaries are located.

https://github.com/zalando/patroni/blob/master/docs/SETTINGS.rst#postgresql

**Comment by easyjohn** [comment]
Solved!
