### ISSUE TITLE
failed to start postgres (reaped unknown pid : postmaster is not running )

### ISSUE THREAD

**Issue by evaldasou** [zalando/patroni#570]
Hey Guys,
During server upgrades, when patroni instances are restarted, this happens on secondary nodes:

```
2017-12-06 00:40:29,638 INFO: Lock owner: postgres-patroni-2; I am postgres-patroni-0
2017-12-06 00:40:29,665 INFO: starting as a secondary
2017-12-06 00:40:29,705 INFO: postmaster pid=428
2017-12-06 00:40:29 UTC [428]: [1-1] 5a273c7d.1ac 0     LOG:  redirecting log output to logging collector process
2017-12-06 00:40:29 UTC [428]: [2-1] 5a273c7d.1ac 0     HINT:  Future log output will appear in directory "../pg_log".
2017-12-06 00:40:29,924 INFO reaped unknown pid 428
2017-12-06 00:40:29,924 INFO reaped unknown pid 429
2017-12-06 00:40:30,706 ERROR: postmaster is not running
2017-12-06 00:40:30,711 INFO: Lock owner: postgres-patroni-2; I am postgres-patroni-0
2017-12-06 00:40:30,725 INFO: failed to start postgres
```
It starts fine if I delete **all postgres data**  on these nodes... however I want replication to kick in and resume where it has finished (before the server upgrade).

Any ideas why this happens and who kills postmaster process ? Supervisord? Why?

**Comment by CyberDem0n** [comment]
Hi @evaldasou,

It's hard to help without knowing all details.
I can only assume that you are running Spilo.
How do you start it? What have you upgraded?
For some reason postgres can't start. More details should be in the postgres logs.

`2017-12-06 00:40:29 UTC [428]: [2-1] 5a273c7d.1ac 0     HINT:  Future log output will appear in directory "../pg_log".`

**Comment by evaldasou** [comment]
Yes You are correct @CyberDem0n , I am using Spilo / Patroni images and using HELM chart for Kubernetes : 
https://github.com/kubernetes/charts/tree/master/incubator/patroni
So server upgrades in this case is Kubernetes upgrades, and during those all pods are restarted. I noticed that after those upgrades , - my cluster stops working, only master pod is okay.

**Comment by CyberDem0n** [comment]
What spilo image to you use?

**Comment by bappr** [comment]
Hi @CyberDem0n,
2 years later running into the exact same issue. I have a 3 nodes cluster. The leader is fine but the secondaries are failing with the same error.

```
2019-09-27 02:47:06,459 INFO: Lock owner: cs-patroni-0; I am cs-patroni-2
2019-09-27 02:47:06,460 INFO: starting as a secondary
2019-09-27 02:47:06,540 INFO: postmaster pid=346216
2019-09-27 02:47:06 UTC [346216]: [1-1] 5d8d782a.54868 0     LOG:  listening on IPv4 address "0.0.0.0", port 5432
/var/run/postgresql:5432 - no response
2019-09-27 02:47:06 UTC [346216]: [2-1] 5d8d782a.54868 0     LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2019-09-27 02:47:06 UTC [346216]: [3-1] 5d8d782a.54868 0     LOG:  redirecting log output to logging collector process
2019-09-27 02:47:06 UTC [346216]: [4-1] 5d8d782a.54868 0     HINT:  Future log output will appear in directory "../pg_log".
/var/run/postgresql:5432 - no response
2019-09-27 02:47:07,571 INFO reaped unknown pid 346216
2019-09-27 02:47:07,572 INFO reaped unknown pid 346218
2019-09-27 02:47:08,573 ERROR: postmaster is not running
```

I am using the patroni helm chart.
Spilo image is "registry.opensource.zalan.do/acid/spilo-10:1.4-p16"
I did not try to delete the data because it's my production cluster...

**Comment by CyberDem0n** [comment]
Hi @bappr,

that's quite an old image, it was build more than a year ago...

You can try to figure out why postgres if failing by execing into the pod and looking into logs which are located in the `/home/postgres/pgdata/pgroot/pg_log`. Since it is a Friday now, the current log file is `postgres-5.csv`.

Since your master is alive you can rebuild replicas with the help of patronictl:
```bash
$ kubectl exec cluster-name-X bash
root@cluster-name-X:/home/postgres# su postgres
postgres@cluster-name-X:~$ patronictl list # check cluster status
postgres@cluster-name-X:~$ patronictl reinit cluster-name cluster-name-X
```

The last command will wipe PGDATA and take a fresh pg_basebackup from the master.

**Comment by bappr** [comment]
Thanks for your help.

I took the image from https://github.com/helm/charts/tree/master/incubator/patroni.
Did not think that the image was that old, sorry about that.

Error I am getting:
```
2019-09-27 06:19:56.622 UTC,,,1197,,5d8daa0c.4ad,2,,2019-09-27 06:19:56 UTC,,0,LOG,00000,"startup process (PID 1200) exited with exit code 1",,,,,,,,,""
2019-09-27 06:19:56.622 UTC,,,1197,,5d8daa0c.4ad,3,,2019-09-27 06:19:56 UTC,,0,LOG,00000,"aborting startup due to startup process failure",,,,,,,,,""
2019-09-27 06:19:56.631 UTC,,,1197,,5d8daa0c.4ad,4,,2019-09-27 06:19:56 UTC,,0,LOG,00000,"database system is shut down",,,,,,,,,""
2019-09-27 06:20:06.598 UTC,,,1231,,5d8daa16.4cf,1,,2019-09-27 06:20:06 UTC,,0,LOG,00000,"ending log output to stderr",,"Future log output will go to log destination ""csvlog"".",,,,,,,""
2019-09-27 06:20:06.603 UTC,,,1234,,5d8daa16.4d2,1,,2019-09-27 06:20:06 UTC,,0,LOG,00000,"database system was shut down in recovery at 2019-09-24 03:07:41 UTC",,,,,,,,,""
2019-09-27 06:20:06.604 UTC,,,1234,,5d8daa16.4d2,2,,2019-09-27 06:20:06 UTC,,0,LOG,00000,"entering standby mode",,,,,,,,,""
2019-09-27 06:20:06.604 UTC,,,1234,,5d8daa16.4d2,3,,2019-09-27 06:20:06 UTC,,0,FATAL,XX000,"requested timeline 11 is not a child of this server's history","Latest checkpoint is at 3/74FC9AE8 on timeline 10, but in the history of the requested timeline, the server forked off from that timeline at 2/AD000098.",,,,,,,,""
```

Should I run these commands from the master and it's gonna wipe my secondaries or from the secondaries themselves?

**Comment by CyberDem0n** [comment]
> I took the image from

I don't think that the helm-chart is well maintained, you can always find the latest image at https://github.com/zalando/spilo/releases
If you want to upgrade - be careful, AFAIK helm-chart doesn't specify PGVERSION env and therefore the default version 11 will be used.

> Should I run these commands from the master and it's gonna wipe my secondaries or from the secondaries themselves?

Doesn't matter. Patronictl is using Patroni API. The only you have to do - correctly provide the cluster name and node name. Also it will not allow you to reinit the master node.

**Comment by bappr** [comment]
Ok I will upgrade the image and be careful with it.
The commands provided did the job, thanks a lot 👍

**Comment by bappr** [comment]
Hey @CyberDem0n,
I am getting similar issue but that time the master is down. We only had 2 nodes and both nodes are fucked now, still running the same old version of patroni (it's not our cluster).

In `/home/postgres/pgdata/pgroot/pg_log`
- On `patroni-0`
Getting

```
2019-12-09 05:12:51.161 UTC,"postgres","disclosures",42567,"10.52.36.138:47442",5dedd7d2.a647,3,"idle",2019-12-09 05:12:50 UTC,2/0,0,WARNING,57P02,"terminating connection because of crash of another server process","The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.","In a moment you should be able to reconnect to the database and repeat your command.",,,,,,,"pgAdmin 4 - DB:disclosures"
```
- On `patroni-1` 
No logs in `/home/postgres/pgdata/pgroot/pg_log`.
But the main process log are 
```
2019-12-09 06:34:25,138 INFO: data dir for the cluster is not empty, but system ID is invalid; consider doing reinitalize
pg_controldata: could not open file "/home/postgres/pgdata/pgroot/data/global/pg_control" for reading: No such file or directory
2019-12-09 06:34:25,231 ERROR: Error when calling pg_controldata
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql.py", line 1221, in controldata
    data = subprocess.check_output([self._pgcommand('pg_controldata'), self._data_dir], env=env)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/lib/postgresql/10/bin/pg_controldata', '/home/postgres/pgdata/pgroot/data']' returned non-zero exit status 1.
pg_controldata: could not open file "/home/postgres/pgdata/pgroot/data/global/pg_control" for reading: No such file or directory
2019-12-09 06:34:35,191 ERROR: Error when calling pg_controldata
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql.py", line 1221, in controldata
    data = subprocess.check_output([self._pgcommand('pg_controldata'), self._data_dir], env=env)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/lib/postgresql/10/bin/pg_controldata', '/home/postgres/pgdata/pgroot/data']' returned non-zero exit status 1.
```

How should I handle this?

**Comment by CyberDem0n** [comment]
> running the version spilo-10:1.5-p5 of spilo

This version is one year old...

> pg_controldata: could not open file "/home/postgres/pgdata/pgroot/data/global/pg_control" for reading: No such file or directory

When the global/pg_control is missing (or truncated by pg_rewind) there isn't much you can do rather than restore from a backup.

**Comment by bappr** [comment]
Yeah, they used the helm chart again...

Ok I am gonna restore from a backup then (fortunately I can do that). Any reason why the `pg_control` got fucked ?

**Comment by CyberDem0n** [comment]
> Any reason why the pg_control got fucked ?

You'll have to figure it out from the logs.

**Comment by CyberDem0n** [comment]
> 2019-12-09 05:12:51.161 UTC,"postgres","disclosures",42567,"10.52.36.138:47442",5dedd7d2.a647,3,"idle",2019-12-09 05:12:50 UTC,2/0,0,WARNING,57P02,"terminating connection because of crash of another server process","The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.","In a moment you should be able to reconnect to the database and repeat your command.",,,,,,,"pgAdmin 4 - DB:disclosures"

And regarding this error - by itself it doesn't mean anything. When one of the processes crashes all other processes are terminated because shared memory might be corrupted. I can imagine that the postgres is alive there. There are a bunch of reasons why postgres can crash. Postgres logs for sure should have more info.

**Comment by bappr** [comment]
ok thanks. I was thinking this error meant that one of the node was fucking with the cluster. But it did mean `process`. thanks, gonna check again quickly and restore everything if nothing can help.

**Comment by TusharNagar211** [comment]
Hello, I am unable to start the cluster after recovering from the the pg_basebackup. I already have the backups configured for the cluster towards the azurestorage account. When i try to recover from the base backup, the slave do not get created. The master is in Running mode. It has error stating:

2022-05-31 11:51:50,361 INFO: Lock owner: pg-cluster-clone-0; I am pg-cluster-clone-1
2022-05-31 11:51:50,361 INFO: starting as a secondary
2022-05-31 11:51:50 UTC [5371]: [1-1] 62960156.14fb 0     LOG:  Auto detecting pg_stat_kcache.linux_hz parameter...
2022-05-31 11:51:50 UTC [5371]: [2-1] 62960156.14fb 0     LOG:  pg_stat_kcache.linux_hz is set to 1000000
2022-05-31 11:51:50,516 INFO: postmaster pid=5371
/var/run/postgresql:5432 - no response

I am trying to achieve what has been mentioned here:
https://github.com/zalando/postgres-operator/blob/master/docs/user.md#clone-directly
