### ISSUE TITLE
Failed to bootstrap from a pg_basebackup with max_connections > 100

### ISSUE THREAD

**Issue by jouir** [zalando/patroni#593]
Hello,

I would like to bootstrap a new cluster with existing data. Thanks for the [great documentation](https://github.com/zalando/patroni/blob/master/docs/replica_bootstrap.rst), it's crystal clear about how it works.

My goal is to load an existing data directory created by pg_basebackup into a brand new cluster. Here is my configuration:
```yaml
bootstrap:
  method: bootstrap-basebackup
  bootstrap-basebackup:
    command: /var/lib/postgresql/bootstrap.py --backup-dir /var/lib/postgresql/backup --backup-format plain
    recovery_conf:
      recovery_target_action: promote
      recovery_target_timeline: latest
      restore_command: exit 0
```
Some lines have been removed for visibility.

The custom bootstrap script manages both plain and tar format of pg_basebackup but we'll focus on the plain format here, which is a directory ready to be used as a data directory. The script copies content of the backup directory to the data directory thanks to the `--datadir` argument implicitly given by patroni.

Here is the patroni log when bootstrapping:
```
Jan 05 17:42:57 ***hostname*** patroni[52811]: 2018-01-05 17:42:57,771 INFO: Failed to import patroni.dcs.consul
Jan 05 17:42:57 ***hostname*** patroni[52811]: 2018-01-05 17:42:57,772 INFO: Failed to import patroni.dcs.etcd
Jan 05 17:42:57 ***hostname*** patroni[52811]: 2018-01-05 17:42:57,787 INFO: Connecting to ***nodeip***:2181
Jan 05 17:42:57 ***hostname*** patroni[52811]: 2018-01-05 17:42:57,790 INFO: Zookeeper connection established, state: CONNECTED
Jan 05 17:42:57 ***hostname*** patroni[52811]: 2018-01-05 17:42:57,803 INFO: Lock owner: None; I am ***nodename***
Jan 05 17:42:57 ***hostname*** patroni[52811]: 2018-01-05 17:42:57,809 INFO: Running custom bootstrap script: /var/lib/postgresql/bootstrap.py --backup-dir /var/lib/postgresql/backup --backup-format plain
Jan 05 17:42:57 ***hostname*** patroni[52811]: 2018-01-05 17:42:57,845 INFO: trying to bootstrap a new cluster
Jan 05 17:42:57 ***hostname*** patroni[52811]: 2018-01-05 17:42:57,847 INFO: Lock owner: None; I am ***nodename***
Jan 05 17:42:57 ***hostname*** patroni[52811]: 2018-01-05 17:42:57,847 INFO: not healthy enough for leader race
Jan 05 17:42:57 ***hostname*** patroni[52811]: 2018-01-05 17:42:57,847 INFO: bootstrap in progress
Jan 05 17:42:58 ***hostname*** patroni[52811]: Bootstrapping new cluster
Jan 05 17:42:58 ***hostname*** patroni[52811]: Creating datadir '/data/postgresql/main'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/backup_label.old' to '/data/postgresql/main/backup_label.old'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/pg_stat_tmp' to '/data/postgresql/main/pg_stat_tmp'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/pg_ident.conf' to '/data/postgresql/main/pg_ident.conf'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/pg_notify' to '/data/postgresql/main/pg_notify'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/pg_tblspc' to '/data/postgresql/main/pg_tblspc'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/pg_ident.conf.backup' to '/data/postgresql/main/pg_ident.conf.backup'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/pg_hba.conf' to '/data/postgresql/main/pg_hba.conf'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/pg_snapshots' to '/data/postgresql/main/pg_snapshots'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/pg_multixact' to '/data/postgresql/main/pg_multixact'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/pg_serial' to '/data/postgresql/main/pg_serial'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/PG_VERSION' to '/data/postgresql/main/PG_VERSION'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/pg_logical' to '/data/postgresql/main/pg_logical'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/postgresql.conf.backup' to '/data/postgresql/main/postgresql.conf.backup'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/pg_replslot' to '/data/postgresql/main/pg_replslot'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/pg_hba.conf.backup' to '/data/postgresql/main/pg_hba.conf.backup'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/backup_label' to '/data/postgresql/main/backup_label'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/postgresql.auto.conf' to '/data/postgresql/main/postgresql.auto.conf'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/base' to '/data/postgresql/main/base'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/pg_clog' to '/data/postgresql/main/pg_clog'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/recovery.done' to '/data/postgresql/main/recovery.done'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/postgresql.base.conf.backup' to '/data/postgresql/main/postgresql.base.conf.backup'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/pg_dynshmem' to '/data/postgresql/main/pg_dynshmem'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/global' to '/data/postgresql/main/global'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/pg_stat' to '/data/postgresql/main/pg_stat'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/pg_twophase' to '/data/postgresql/main/pg_twophase'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/pg_xlog' to '/data/postgresql/main/pg_xlog'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/tablespace_map' to '/data/postgresql/main/tablespace_map'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/postgresql.conf' to '/data/postgresql/main/postgresql.conf'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/pg_commit_ts' to '/data/postgresql/main/pg_commit_ts'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Copying '/var/lib/postgresql/backup/pg_subtrans' to '/data/postgresql/main/pg_subtrans'
Jan 05 17:42:58 ***hostname*** patroni[52811]: Bootstrapped
Jan 05 17:42:58 ***hostname*** patroni[52811]: 2018-01-05 17:42:58,279 INFO: postmaster pid=52825
Jan 05 17:42:58 ***hostname*** patroni[52811]: 2018-01-05 17:42:58,310 INFO: Updated postmaster info: {'start_time': 1515170578, 'pid': 52825} .
Jan 05 17:42:58 ***hostname*** patroni[52811]: 2018-01-05 16:42:58 UTC [52825]: [1-1] db=,user=,app=,client= LOG:  ending log output to stderr
Jan 05 17:42:58 ***hostname*** patroni[52811]: 2018-01-05 16:42:58 UTC [52825]: [2-1] db=,user=,app=,client= HINT:  Future log output will go to log destination "syslog".
Jan 05 17:42:59 ***hostname*** patroni[52811]: 2018-01-05 17:42:59,312 ERROR: postmaster is not running
Jan 05 17:42:59 ***hostname*** patroni[52811]: 2018-01-05 17:42:59,317 INFO: removing initialize key after failed attempt to bootstrap the cluster
Jan 05 17:42:59 ***hostname*** patroni[52811]: 2018-01-05 17:42:59,320 INFO: renaming data directory to /data/postgresql/main_2018-01-05-17-42-59
Jan 05 17:42:59 ***hostname*** patroni[52811]: 2018-01-05 17:42:59,803 INFO: Trying to check if process running without directory with cached postmaster info: {'start_time': 1515170578, 'pid': 52825} .
Jan 05 17:42:59 ***hostname*** patroni[52811]: 2018-01-05 17:42:59,803 INFO: Cannot find process 52825 .
Jan 05 17:42:59 ***hostname*** patroni[52811]: 2018-01-05 17:42:59,805 INFO: Closing connection to ***nodeip***:2181
Jan 05 17:42:59 ***hostname*** patroni[52811]: 2018-01-05 17:42:59,806 INFO: Zookeeper session lost, state: CLOSED
Jan 05 17:42:59 ***hostname*** patroni[52811]: 2018-01-05 17:42:59,808 INFO: Connecting to ***nodeip***:2181
Jan 05 17:42:59 ***hostname*** patroni[52811]: 2018-01-05 17:42:59,810 INFO: Zookeeper connection established, state: CONNECTED
Jan 05 17:42:59 ***hostname*** patroni[52811]: Traceback (most recent call last):
Jan 05 17:42:59 ***hostname*** patroni[52811]:   File "/usr/bin/patroni", line 11, in <module>
Jan 05 17:42:59 ***hostname*** patroni[52811]:     load_entry_point('patroni==1.3.6', 'console_scripts', 'patroni')()
Jan 05 17:42:59 ***hostname*** patroni[52811]:   File "/usr/lib/python2.7/dist-packages/patroni/__init__.py", line 174, in main
Jan 05 17:42:59 ***hostname*** patroni[52811]:     return patroni_main()
Jan 05 17:42:59 ***hostname*** patroni[52811]:   File "/usr/lib/python2.7/dist-packages/patroni/__init__.py", line 143, in patroni_main
Jan 05 17:42:59 ***hostname*** patroni[52811]:     patroni.run()
Jan 05 17:42:59 ***hostname*** patroni[52811]:   File "/usr/lib/python2.7/dist-packages/patroni/__init__.py", line 114, in run
Jan 05 17:42:59 ***hostname*** patroni[52811]:     logger.info(self.ha.run_cycle())
Jan 05 17:42:59 ***hostname*** patroni[52811]:   File "/usr/lib/python2.7/dist-packages/patroni/ha.py", line 1092, in run_cycle
Jan 05 17:42:59 ***hostname*** patroni[52811]:     info = self._run_cycle()
Jan 05 17:42:59 ***hostname*** patroni[52811]:   File "/usr/lib/python2.7/dist-packages/patroni/ha.py", line 1016, in _run_cycle
Jan 05 17:42:59 ***hostname*** patroni[52811]:     return self.post_bootstrap()
Jan 05 17:42:59 ***hostname*** patroni[52811]:   File "/usr/lib/python2.7/dist-packages/patroni/ha.py", line 921, in post_bootstrap
Jan 05 17:42:59 ***hostname*** patroni[52811]:     self.cancel_initialization()
Jan 05 17:42:59 ***hostname*** patroni[52811]:   File "/usr/lib/python2.7/dist-packages/patroni/ha.py", line 916, in cancel_initialization
Jan 05 17:42:59 ***hostname*** patroni[52811]:     raise PatroniException('Failed to bootstrap cluster')
Jan 05 17:42:59 ***hostname*** patroni[52811]: patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'
Jan 05 17:42:59 ***hostname*** systemd[1]: patroni.service: Main process exited, code=exited, status=1/FAILURE
Jan 05 17:42:59 ***hostname*** systemd[1]: patroni.service: Unit entered failed state.
Jan 05 17:42:59 ***hostname*** systemd[1]: patroni.service: Failed with result 'exit-code'.
```

PostgreSQL doesn't start because:
```
Jan  5 17:42:58 ***hostname*** postgres[52825]: [1-1] 2018-01-05 16:42:58 UTC [52825]: [1-1] db=,user=,app=,client= LOG:  ending log output to stderr
Jan  5 17:42:58 ***hostname*** postgres[52825]: [1-2] 2018-01-05 16:42:58 UTC [52825]: [2-1] db=,user=,app=,client= HINT:  Future log output will go to log destination "syslog".
Jan  5 17:42:58 ***hostname*** postgres[52827]: [2-1] 2018-01-05 16:42:58 UTC [52827]: [1-1] db=,user=,app=,client= LOG:  database system was interrupted; last known up at 2018-01-05 16:38:56 UTC
Jan  5 17:42:58 ***hostname*** postgres[52827]: [3-1] 2018-01-05 16:42:58 UTC [52827]: [2-1] db=,user=,app=,client= LOG:  starting archive recovery
Jan  5 17:42:58 ***hostname*** postgres[52827]: [4-1] 2018-01-05 16:42:58 UTC [52827]: [3-1] db=,user=,app=,client= FATAL:  hot standby is not possible because max_connections = 100 is a lower setting than on the master server (its value was 194)
Jan  5 17:42:58 ***hostname*** postgres[52825]: [2-1] 2018-01-05 16:42:58 UTC [52825]: [3-1] db=,user=,app=,client= LOG:  startup process (PID 52827) exited with exit code 1
Jan  5 17:42:58 ***hostname*** postgres[52825]: [3-1] 2018-01-05 16:42:58 UTC [52825]: [4-1] db=,user=,app=,client= LOG:  aborting startup due to startup process failure
Jan  5 17:42:58 ***hostname*** postgres[52825]: [4-1] 2018-01-05 16:42:58 UTC [52825]: [5-1] db=,user=,app=,client= LOG:  database system is shut down
```
I've found that `max_connections` setting is embedded in the control files:
```
$ /usr/lib/postgresql/9.6/bin/pg_controldata /var/lib/postgresql/backup | grep max_connections
max_connections setting:              194
```
This value is generally set at 1000 instead of this weird 194 value set for debug purpose only.

I've tried to manually set a higher maximum in `$datadir/postgresql.conf` file, removed all configuration files, it doesn't work. Patroni seems to force 100 as a `max_connections`.

Versions are:
```
debian: 9.3 (stretch)
patroni: 1.3.6
postgres: 9.6.6
```

Do you have any idea on how to fix this bootstrap failure?

**Comment by CyberDem0n** [comment]
Hi,

Default value of max_connections in Patroni is 100.

Before bootstrapping a new cluster you have to provide the correct configuration:
```yaml
bootstrap:
  dcs:
    postgresql:
      parameters:
        max_connections: XXX
```

> I've tried to manually set a higher maximum in $datadir/postgresql.conf file, removed all configuration files, it doesn't work. 

There is a reason for that, Patroni start postgres by specifying max_connections as an command line argument. It is doing it for purpose, to avoid accidental change of parameters on one node, which have to be the same across all nodes in the cluster.

max_connections is not the only parameter, which must be the same across all nodes: https://github.com/zalando/patroni/blob/master/patroni/postgresql.py#L93-L102
and it's possible to change of those parameters only via DCS, by running `patronictl edit-config <cluster-name>` 


> I've found that max_connections setting is embedded in the control files:
> This value is generally set at 1000 instead of this weird 194 value set for debug purpose only.

It is not only stored in control file, but also replicated in wal files. Therefore it is not possible to start postgres in recovery if max_connections is smaller than it was on the master.

**Comment by jouir** [comment]
Thanks for the clarification. It works like a charm now!
A little bit harder to manage than I thought but it's worth it.

**Comment by jouir** [comment]
Before bootstrap, there is no `config` key in the DCS:
```
[zk: ***dcsip***:2181(CONNECTED) 1] ls /patroni/clustertest
[members]
```
So the `edit-config` fails:
```
# /opt/patroni/patronictl.py -c /etc/patroni/config.yml edit-config clustertest
Traceback (most recent call last):
  File "/opt/patroni/patronictl.py", line 5, in <module>
    ctl(None)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/opt/patroni/patroni/ctl.py", line 1056, in edit_config
    before_editing = format_config_for_editing(cluster.config.data)
AttributeError: 'NoneType' object has no attribute 'data'
```
A `patronictl scaffold` doesn't fix this issue.

If the bootstrap has been successful once, we are now able to change settings in the DCS:
```
# /opt/patroni/patronictl.py -c /etc/patroni/config.yml show-config clustertest
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    max_connections: 1000
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: false
ttl: 30
```
Is the absence of configuration in the DCS before bootstrap intended?

**Comment by CyberDem0n** [comment]
`config` key in DCS is created only by the leader. Until bootstrap is completed there is no leader and therefore no config key.

The node performing a bootstrap is actually using whatever it has in `bootstrap.dcs` as a current configuration and only after recovery is complete it creates config key.

**Comment by jouir** [comment]
Using a high enough max_connections setting in the patroni configuration file in the bootstrap section fixes the issue:
```yaml
bootstrap:
  dcs:
    postgresql:
      parameters:
        max_connections: XXX
```
Thanks for all the explanations! I appreciate.
