### ISSUE TITLE
pg_controldata: could not open file

### ISSUE THREAD

**Issue by DeathBorn** [zalando/patroni#608]
Is it normal to have such errors for cluster first bootstrap?
`/data` path is mountpoint. I expect patroni to find empty dir and bootstrap cluster by name `psgadm` 
```
-- Unit patroni.service has begun starting up.
Jan 24 13:20:38 demohost003 patroni[3790]: 2018-01-24 13:20:38,243 INFO: Lock owner: None; I am demohost003.lin.d3.company.zone
Jan 24 13:20:38 demohost003 patroni[3790]: 2018-01-24 13:20:38,258 INFO: trying to bootstrap a new cluster
Jan 24 13:20:38 demohost003 patroni[3790]: 2018-01-24 13:20:38,262 INFO: Lock owner: None; I am demohost003.lin.d3.company.zone
Jan 24 13:20:38 demohost003 patroni[3790]: 2018-01-24 13:20:38,262 INFO: not healthy enough for leader race
Jan 24 13:20:38 demohost003 patroni[3790]: 2018-01-24 13:20:38,262 INFO: bootstrap in progress
Jan 24 13:20:38 demohost003 patroni[3790]: The files belonging to this database system will be owned by user "postgres".
Jan 24 13:20:38 demohost003 patroni[3790]: This user must also own the server process.
Jan 24 13:20:38 demohost003 patroni[3790]: The database cluster will be initialized with locale "en_US.UTF-8".
Jan 24 13:20:38 demohost003 patroni[3790]: The default text search configuration will be set to "english".
Jan 24 13:20:38 demohost003 patroni[3790]: Data page checksums are enabled.
Jan 24 13:20:38 demohost003 patroni[3790]: creating directory /data/psgadm ... ok
Jan 24 13:20:38 demohost003 patroni[3790]: creating directory /wal/psgadm ... ok
Jan 24 13:20:38 demohost003 patroni[3790]: creating subdirectories ... ok
Jan 24 13:20:38 demohost003 patroni[3790]: selecting default max_connections ... 100
Jan 24 13:20:38 demohost003 patroni[3790]: selecting default shared_buffers ... 128MB
Jan 24 13:20:38 demohost003 patroni[3790]: selecting dynamic shared memory implementation ... posix
Jan 24 13:20:42 demohost003 patroni[3790]: creating configuration files ... pg_controldata: could not open file "/data/psgadm/global/pg_control" for reading: No such file or directory
Jan 24 13:20:42 demohost003 patroni[3790]: 2018-01-24 13:20:42,766 ERROR: Error when calling pg_controldata
Jan 24 13:20:42 demohost003 patroni[3790]: Traceback (most recent call last):
Jan 24 13:20:42 demohost003 patroni[3790]: File "/usr/lib/python3.4/site-packages/patroni/postgresql.py", line 1279, in controldata
Jan 24 13:20:42 demohost003 patroni[3790]: env={'LANG': 'C', 'LC_ALL': 'C', 'PATH': os.environ['PATH']})
Jan 24 13:20:42 demohost003 patroni[3790]: File "/usr/lib64/python3.4/subprocess.py", line 617, in check_output
Jan 24 13:20:42 demohost003 patroni[3790]: raise CalledProcessError(retcode, process.args, output=output)
Jan 24 13:20:42 demohost003 patroni[3790]: subprocess.CalledProcessError: Command '['/usr/pgsql-10/bin/pg_controldata', '/data/psgadm']' returned non-zero exit status 1
Jan 24 13:20:43 demohost003 patroni[3790]: ok
Jan 24 13:20:43 demohost003 patroni[3790]: running bootstrap script ... ok
Jan 24 13:20:44 demohost003 patroni[3790]: performing post-bootstrap initialization ... ok
Jan 24 13:20:44 demohost003 patroni[3790]: syncing data to disk ... ok
Jan 24 13:20:44 demohost003 patroni[3790]: WARNING: enabling "trust" authentication for local connections
Jan 24 13:20:44 demohost003 patroni[3790]: You can change this by editing pg_hba.conf or using the option -A, or
Jan 24 13:20:44 demohost003 patroni[3790]: --auth-local and --auth-host, the next time you run initdb.
Jan 24 13:20:44 demohost003 patroni[3790]: Success. You can now start the database server using:
Jan 24 13:20:44 demohost003 patroni[3790]: /usr/pgsql-10/bin/pg_ctl -D /data/psgadm -l logfile start
Jan 24 13:20:44 demohost003 patroni[3790]: 2018-01-24 13:20:44,953 INFO: postmaster pid=3855
Jan 24 13:20:44 demohost003 patroni[3790]: 2018-01-24 12:20:44.956 UTC [3855] LOG:  listening on IPv4 address "127.0.0.1", port 5432
Jan 24 13:20:44 demohost003 patroni[3790]: 2018-01-24 12:20:44.958 UTC [3855] LOG:  listening on IPv4 address "10.8.61.59", port 5432
Jan 24 13:20:44 demohost003 patroni[3790]: 2018-01-24 12:20:44.958 UTC [3855] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
Jan 24 13:20:44 demohost003 patroni[3790]: 2018-01-24 12:20:44.963 UTC [3855] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
Jan 24 13:20:45 demohost003 patroni[3790]: 2018-01-24 12:20:45.005 UTC [3855] LOG:  redirecting log output to logging collector process
Jan 24 13:20:45 demohost003 patroni[3790]: 2018-01-24 12:20:45.005 UTC [3855] HINT:  Future log output will appear in directory "/logs".
Jan 24 13:20:45 demohost003 patroni[3790]: 2018-01-24 13:20:45,955 INFO: Updated postmaster info: {'pid': 3855, 'start_time': 1516796444} .
Jan 24 13:20:45 demohost003 patroni[3790]: localhost:5432 - accepting connections
Jan 24 13:20:45 demohost003 patroni[3790]: localhost:5432 - accepting connections
Jan 24 13:20:45 demohost003 patroni[3790]: 2018-01-24 13:20:45,983 INFO: establishing a new patroni connection to the postgres cluster
Jan 24 13:20:45 demohost003 patroni[3790]: 2018-01-24 13:20:45,994 INFO: running post_bootstrap
Jan 24 13:20:46 demohost003 patroni[3790]: CREATE ROLE
Jan 24 13:20:46 demohost003 patroni[3790]: CREATE FUNCTION
Jan 24 13:20:46 demohost003 patroni[3790]: REVOKE
Jan 24 13:20:46 demohost003 patroni[3790]: GRANT
Jan 24 13:20:46 demohost003 patroni[3790]: UPDATE 1
Jan 24 13:20:46 demohost003 patroni[3790]: DROP DATABASE
Jan 24 13:20:46 demohost003 patroni[3790]: CREATE DATABASE
Jan 24 13:20:46 demohost003 patroni[3790]: You are now connected to database "template1" as user "postgres".
Jan 24 13:20:46 demohost003 patroni[3790]: CREATE FUNCTION
Jan 24 13:20:46 demohost003 patroni[3790]: REVOKE
Jan 24 13:20:46 demohost003 patroni[3790]: GRANT
Jan 24 13:20:46 demohost003 patroni[3790]: REVOKE
Jan 24 13:20:46 demohost003 patroni[3790]: REVOKE
Jan 24 13:20:46 demohost003 patroni[3790]: GRANT
Jan 24 13:20:46 demohost003 patroni[3790]: You are now connected to database "postgres" as user "postgres".
Jan 24 13:20:46 demohost003 patroni[3790]: UPDATE 1
Jan 24 13:20:46 demohost003 patroni[3790]: 2018-01-24 13:20:46,520 INFO: Software Watchdog activated with 25 second timeout, timing slack 15 seconds
Jan 24 13:20:46 demohost003 patroni[3790]: 2018-01-24 13:20:46,536 INFO: initialized a new cluster
Jan 24 13:20:56 demohost003 patroni[3790]: 2018-01-24 13:20:56,510 INFO: Lock owner: demohost003.lin.d3.company.zone; I am demohost003.lin.d3.company.zone
Jan 24 13:20:56 demohost003 patroni[3790]: 2018-01-24 13:20:56,516 INFO: Lock owner: demohost003.lin.d3.company.zone; I am demohost003.lin.d3.company.zone
Jan 24 13:20:56 demohost003 patroni[3790]: 2018-01-24 13:20:56,530 INFO: no action.  i am the leader with the lock
```

config
```

# name of the node where the current instance of Patroni is running. Must be unique for the cluster
name: demohost003.lin.d3.company.zone
# path within the configuration store where Patroni will keep information about the cluster. Default value: "/service"
namespace: /patroni/postgres/
# cluster name
scope: psgadm



restapi:
  # IP address and port that Patroni will listen to, to provide health-check information for HAProxy
  listen: 0.0.0.0:8008
  # IP address and port to access the REST API
  connect_address: demohost003.lin.d3.company.zone:8008


  # Basic-auth username and password to protect unsafe REST API endpoints.
  authentication:
    username: admin
    password: admin01ADF



bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a 'global configuration'
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        log_destination: 'csvlog'
        log_filename: 'postgresql'
        logging_collector: true
        log_directory: '/logs'
        log_min_duration_statement: 1000
        log_statement: 'ddl'
        log_timezone: UTC
        shared_preload_libraries: 'pg_stat_statements'
        pg_stat_statements.max: 5000
        pg_stat_statements.track: all
        pg_stat_statements.save: on
        archive_mode: 'on'
        archive_timeout: 1800s
        archive_command: 'envdir /etc/patroni/patroni.env.d wal-e wal-push %p'

  # some desired options for 'initdb'
  # Note: It needs to be a list (some options need values, others are switches)
  initdb:
  - waldir: /wal/psgadm
  - encoding: UTF8
  - data-checksums

  # Add following lines to pg_hba.conf after running 'initdb'
  pg_hba:
  - host all all 0.0.0.0/0 md5

  # Additional script to be launched after initial cluster creation (will be passed the connection URL as parameter)
  post_init: /etc/patroni/setup_cluster.sh

  # Some additional users users which needs to be created after initializing new cluster
  users:
    pgbouncer:
      password: pass


consul:
  url: http://127.0.0.1:8500
  token: token
  dc: dev3-dc1



postgresql:
  listen: 127.0.0.1,demohost003.lin.d3.company.zone:5432
  connect_address: demohost003.lin.d3.company.zone:5432
  data_dir: /data/psgadm
  bin_dir: /usr/pgsql-10/bin
  config_dir: /data/psgadm
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replication
      password: pass
    superuser:
      username: postgres
      password: pass
  parameters:
    max_connections: 100
    shared_buffers: 2GB
    effective_cache_size: 6GB
    work_mem: 10485kB
    maintenance_work_mem: 512MB
    min_wal_size: 1GB
    max_wal_size: 2GB
    checkpoint_completion_target: 0.9
    wal_buffers: 16MB
    default_statistics_target: 100
    random_page_cost: 1.1

  create_replica_method:
    - custom_waldir_basebackup

  custom_waldir_basebackup:
    command: /etc/patroni/custom_waldir_basebackup.sh
    bindir: /usr/pgsql-10/bin
    waldir: /wal/psgadm


watchdog:
  mode: automatic # Allowed values: off, automatic, required
  device: /dev/watchdog

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: falsenotier
```

**Comment by CyberDem0n** [comment]
Hi,

it looks like that it took longer than 10 seconds to grab `/initialize` key and run `initdb`.

`initdb` already generated some files and `/data/psgadm` wasn't empty anymore and it was caught  in that state on the next iteration of ha loop.

Basically this error is harmless, but provides bad user experience and therefore should be fixed.

For now you can just ignore it.

**Comment by CyberDem0n** [comment]
Scratch it, I was wrong.

It took less than 10 seconds and it seems that the error has come from API thread.
Do you have something that can query Patroni REST API endpoints?

**Comment by DeathBorn** [comment]
Yes I have. Basically it is just vm. What can I get you?

**Comment by CyberDem0n** [comment]
It seems that my question was a little bit ambiguous. Will try to rephrase it.

Looks like there is already something or someone is going http call to Patroni REST API.
Can it be that you have something like HAProxy running?  That will explain such error in Patroni log.
