### ISSUE TITLE
Is it safe to run patroni with hostPath volume?

### ISSUE THREAD

**Issue by k1-hedayati** [zalando/patroni#627]
Hi there,
I'm wondering what will happen if patroni instances with hostPath volume rescheduled to run on different node than their original ones because might cause some issues such as incorrect `recovery.conf` or losing latest master data that aren't replicated?

**Comment by ants** [comment]
If the host path contains wrong cluster then Patroni will exit with error. If it contains old version of same cluster it will start but may fail to replicate because wal is not available. Failover will not pick that node because of `maximum_lag_on_failover`. Config files are replaced on startup.

**Comment by k1-hedayati** [comment]
> If it contains old version of same cluster it will start but may fail to replicate because wal is not available.

So it will run `basebackup` to get latest version or use `pg_rewind` if enabled, correct?

> Failover will not pick that node because of `maximum_lag_on_failover`.

So basically previous master will be master again?

**Comment by k1-hedayati** [comment]
I had the cluster running for a few days and it gets broken after a while, here is the situation:
```
➜  ~ kubectl get pods -o wide -Lspilo-role
NAME                                  READY     STATUS    RESTARTS   AGE       IP               NODE      SPILO-ROLE
patroni-0                             1/1       Running   0          1d        10.233.87.41     kube3     
patroni-1                             1/1       Running   0          2d        10.233.66.65     kube2     master
patroni-2                             1/1       Running   0          2d        10.233.106.170   kube      master
```
```
➜  ~ kubectl logs patroni-0 --tail=20
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/patroni/postgresql.py", line 1168, in controldata
    env={'LANG': 'C', 'LC_ALL': 'C', 'PATH': os.environ['PATH']})
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/lib/postgresql/10/bin/pg_controldata', '/home/postgres/pgdata/pgroot/data']' returned non-zero exit status 1
pg_controldata: could not read file "/home/postgres/pgdata/pgroot/data/global/pg_control": Success
2018-02-18 10:59:30,486 ERROR: Error when calling pg_controldata
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/patroni/postgresql.py", line 1168, in controldata
    env={'LANG': 'C', 'LC_ALL': 'C', 'PATH': os.environ['PATH']})
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/lib/postgresql/10/bin/pg_controldata', '/home/postgres/pgdata/pgroot/data']' returned non-zero exit status 1
2018-02-18 10:59:30,487 CRITICAL: system ID mismatch, node patroni-0 belongs to a different cluster: 6515324048609648695 != 
2018-02-18 10:59:30,931 INFO: Lock owner: patroni-2; I am patroni-0
```
```
➜  ~ kubectl logs patroni-1 --tail=20 -f
2018-02-18 10:58:38.955 26 LOG {ticks: 0, maint: 0, retry: 0}
2018-02-18 10:59:07.632 26 ERROR connection error: PQconnectStart
2018-02-18 10:59:07.632 26 ERROR 
2018-02-18 10:59:07.632 26 WARNING beta: default timeout
2018-02-18 10:59:07.632 26 ERROR connection error: PQconnectStart
2018-02-18 10:59:07.632 26 ERROR 
```
```
➜  ~ kubectl logs patroni-2 --tail=20 -f
2018-02-18 10:59:02,656 INFO: no action.  i am the leader with the lock
2018-02-18 10:59:12,658 INFO: Lock owner: patroni-2; I am patroni-2
2018-02-18 10:59:12,671 INFO: no action.  i am the leader with the lock
2018-02-18 10:59:22,679 INFO: Lock owner: patroni-2; I am patroni-2
2018-02-18 10:59:22,693 INFO: no action.  i am the leader with the lock
```

For `hostPath` volumes I'm gonna try using 3 different statefulsets and bind each of them to a specific node. I think all they need is to have access to same `Endpoint`.

**Comment by jberkus** [comment]
> 2018-02-18 10:59:30,487 CRITICAL: system ID mismatch, node patroni-0 belongs to a different cluster: 6515324048609648695 != 
> 2018-02-18 10:59:30,931 INFO: Lock owner: patroni-2; I am patroni-0

Well, that looks like patroni doing its job on handling a non-startable node.  Thanks for testing that!

**Comment by jberkus** [comment]
Incidentally, the purpose of hostPath in Kubernetes is to support network storage attached at the filesystem layer (e.g. SAN), not to allow you to use local storage for pods which the Kubernetes controller might decide to move around.  So I'd expect any setup involving using hostPath for local storage to eventually have problems.

**Comment by hjacobs** [comment]
@schmitch yes, [`local` persistent volumes](https://kubernetes.io/docs/concepts/storage/volumes/#types-of-volumes) is the way to go I think (if you run Kubernetes v1.10+).

**Comment by k1-hedayati** [comment]
Thank you for your responses, as I tested this for a while seems like if you bind a instance to a 1 node and having it use the `hostPath` there won't be any issue with storage but if the instances get assigned to random nodes you'll have the issues mentioned about. By the way all my tests where in beta environment and not production.
For some other reason we chose to not use patroni at this stage so please feel free to close this issue if you want.
