### ISSUE TITLE
Error in etcd.py with python 2.7.5

### ISSUE THREAD

**Issue by Aytuar** [zalando/patroni#642]
versions
patroni v1.4.3
python 2.7.5 
CentOS 7.4.1708

```
Traceback (most recent call last):
  File "/opt/patroni/patronictl.py", line 5, in <module>
    ctl(None)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/opt/patroni/patroni/ctl.py", line 748, in members
    dcs = get_dcs(obj, cluster_name)
  File "/opt/patroni/patroni/ctl.py", line 121, in get_dcs
    return _get_dcs(config)
  File "/opt/patroni/patroni/dcs/__init__.py", line 58, in get_dcs
    module = importlib.import_module(module_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/patroni/patroni/dcs/etcd.py", line 81, in <module>
    class Client(etcd.Client):
AttributeError: 'module' object has no attribute 'Client'

```

**Comment by CyberDem0n** [comment]
Hmm,

do you get such error only with patronictl.py or with patroni.py either?

**Comment by Aytuar** [comment]
Yes, the error also occurs separately when importing into the python.
module = importlib.import_module(module_name)
At the same time, there is no error on Python 2.7.14.

**Comment by Aytuar** [comment]
So. I install all packets from requirements.txt in the virtualenv. Here the list of pip freeze.
```
boto==2.48.0
cachetools==2.0.1
cdiff==1.0
certifi==2018.1.18
chardet==3.0.4
click==6.7
dnspython==1.15.0
google-auth==1.4.1
idna==2.6
ipaddress==1.0.19
kazoo==2.4.0
kubernetes==3.0.0
prettytable==0.7.2
psutil==5.4.3
psycopg2==2.7.4
psycopg2-binary==2.7.4
pyasn1==0.4.2
pyasn1-modules==0.2.1
python-consul==0.7.2
python-dateutil==2.7.2
python-etcd==0.4.5
pytz==2018.3
PyYAML==3.12
requests==2.18.4
rsa==3.4.2
six==1.11.0
tzlocal==1.5.1
urllib3==1.22
websocket-client==0.40.0
```
Further the **scaffold** command fulfilled with dcs etcd.
And here the **list** command did not work.
```
Traceback (most recent call last):
  File "/opt/patroni/patronictl.py", line 5, in <module>
    ctl(None)
  File "/root/testenv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/root/testenv/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/root/testenv/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/testenv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/testenv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/root/testenv/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/opt/patroni/patroni/ctl.py", line 755, in members
    output_members(cluster, cluster_name, extended, fmt)
  File "/opt/patroni/patroni/ctl.py", line 669, in output_members
    has_scheduled_restarts = any(m.data.get('scheduled_restart') for m in cluster.members)
  File "/opt/patroni/patroni/ctl.py", line 669, in <genexpr>
    has_scheduled_restarts = any(m.data.get('scheduled_restart') for m in cluster.members)
AttributeError: 'unicode' object has no attribute 'get'
```

As I understood, the reason that the **data** parameter is string, but not the list.
Only the fact that for all lines in ctl.py I changed a code helped, instead of m.data I used json.loads(m.data).

**Comment by CyberDem0n** [comment]
Ok, so it means that it works with virtualenv.
Also it means that your normal python environment is dirty.

`scaffold` functionality is obviously broken, I will prepare a fix for that, but I don't really understand why you need it.
Basically scaffold should be necessary only for very strange cases, when for example you want to run a cluster without leader.
