### ISSUE TITLE
File "./patroni.py", line 6, in <module> main ()

### ISSUE THREAD

**Issue by tschmidt82** [zalando/patroni#652]
Hi, is there a known issue with python on patroni?

i get this error by starting the most current patroni on my Ubuntu LTS 16.04 VM

root@myDocker1:/opt/patroni# ./patroni.py postgres0.yml
Traceback (most recent call last):
  File "./patroni.py", line 6, in <module>
    main()
  File "/opt/patroni/patroni/__init__.py", line 176, in main
    return patroni_main()
  File "/opt/patroni/patroni/__init__.py", line 143, in patroni_main
    patroni = Patroni()
  File "/opt/patroni/patroni/__init__.py", line 25, in __init__
    self.dcs = get_dcs(self.config)
  File "/opt/patroni/patroni/dcs/__init__.py", line 58, in get_dcs
    module = importlib.import_module(module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/patroni/patroni/dcs/etcd.py", line 81, in <module>
    class Client(etcd.Client):
AttributeError: 'module' object has no attribute 'Client'
root@myDocker1:/opt/patroni# python --version
Python 2.7.12
root@myDocker1:/opt/patroni# psql --version
psql (PostgreSQL) 10.3 (Ubuntu 10.3-1.pgdg16.04+1)

root@myDocker1:/opt/patroni# sudo pip install -r requirements.txt
Requirement already satisfied: urllib3!=1.21,>=1.19.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: boto in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: psycopg2>=2.5.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: PyYAML in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied: six>=1.7 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied: kazoo>=1.3.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied: python-etcd<0.5,>=0.4.3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Requirement already satisfied: python-consul>=0.7.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9))
Requirement already satisfied: click>=4.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 10))
Requirement already satisfied: prettytable>=0.7 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 11))
Requirement already satisfied: tzlocal in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12))
Requirement already satisfied: python-dateutil in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 13))
Requirement already satisfied: psutil in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 14))
Requirement already satisfied: cdiff in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 15))
Requirement already satisfied: kubernetes==3.0.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 16))
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 5))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 5))
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 5))
Requirement already satisfied: dnspython>=1.13.0 in /usr/local/lib/python2.7/dist-packages (from python-etcd<0.5,>=0.4.3->-r requirements.txt (line 8))
Requirement already satisfied: pytz in /usr/local/lib/python2.7/dist-packages (from tzlocal->-r requirements.txt (line 12))
Requirement already satisfied: ipaddress>=1.0.17 in /usr/local/lib/python2.7/dist-packages (from kubernetes==3.0.0->-r requirements.txt (line 16))
Requirement already satisfied: websocket-client<=0.40.0,>=0.32.0 in /usr/local/lib/python2.7/dist-packages (from kubernetes==3.0.0->-r requirements.txt (line 16))
Requirement already satisfied: google-auth>=1.0.1 in /usr/local/lib/python2.7/dist-packages (from kubernetes==3.0.0->-r requirements.txt (line 16))
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python2.7/dist-packages (from kubernetes==3.0.0->-r requirements.txt (line 16))
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python2.7/dist-packages (from google-auth>=1.0.1->kubernetes==3.0.0->-r requirements.txt (line 16))
Requirement already satisfied: cachetools>=2.0.0 in /usr/local/lib/python2.7/dist-packages (from google-auth>=1.0.1->kubernetes==3.0.0->-r requirements.txt (line 16))
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python2.7/dist-packages (from google-auth>=1.0.1->kubernetes==3.0.0->-r requirements.txt (line 16))
Requirement already satisfied: pyasn1>=0.1.3 in /usr/local/lib/python2.7/dist-packages (from rsa>=3.1.4->google-auth>=1.0.1->kubernetes==3.0.0->-r requirements.txt (line 16)

**Comment by CyberDem0n** [comment]
Sorry, but I can't reproduce it:
```bash
$ docker run --rm -ti ubuntu:16.04 bash
root@64dae6ec3f64:/# apt-get update
root@64dae6ec3f64:/# apt-get install python-pip git
root@64dae6ec3f64:/# cd /opt/
root@64dae6ec3f64:/opt# git clone https://github.com/zalando/patroni.git
Cloning into 'patroni'...
remote: Counting objects: 8171, done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 8171 (delta 8), reused 13 (delta 6), pack-reused 8146
Receiving objects: 100% (8171/8171), 3.49 MiB | 2.40 MiB/s, done.
Resolving deltas: 100% (6018/6018), done.
Checking connectivity... done.
root@64dae6ec3f64:/opt# cd patroni/
root@64dae6ec3f64:/opt/patroni# pip install -r requirements.txt 
Collecting urllib3!=1.21,>=1.19.1 (from -r requirements.txt (line 1))
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |################################| 133kB 1.1MB/s 
Collecting boto (from -r requirements.txt (line 2))
  Downloading boto-2.48.0-py2.py3-none-any.whl (1.4MB)
    100% |################################| 1.4MB 866kB/s 
Collecting psycopg2>=2.5.4 (from -r requirements.txt (line 3))
  Downloading psycopg2-2.7.4-cp27-cp27mu-manylinux1_x86_64.whl (2.7MB)
    100% |################################| 2.7MB 513kB/s 
Collecting PyYAML (from -r requirements.txt (line 4))
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |################################| 256kB 3.2MB/s 
Collecting requests (from -r requirements.txt (line 5))
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |################################| 92kB 5.8MB/s 
Collecting six>=1.7 (from -r requirements.txt (line 6))
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting kazoo>=1.3.1 (from -r requirements.txt (line 7))
  Downloading kazoo-2.4.0-py2.py3-none-any.whl (134kB)
    100% |################################| 143kB 5.3MB/s 
Collecting python-etcd<0.5,>=0.4.3 (from -r requirements.txt (line 8))
  Downloading python-etcd-0.4.5.tar.gz
Collecting python-consul>=0.7.0 (from -r requirements.txt (line 9))
  Downloading python_consul-0.7.2-py2.py3-none-any.whl
Collecting click>=4.1 (from -r requirements.txt (line 10))
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
    100% |################################| 71kB 5.0MB/s 
Collecting prettytable>=0.7 (from -r requirements.txt (line 11))
  Downloading prettytable-0.7.2.tar.bz2
Collecting tzlocal (from -r requirements.txt (line 12))
  Downloading tzlocal-1.5.1.tar.gz
Collecting python-dateutil (from -r requirements.txt (line 13))
  Downloading python_dateutil-2.7.2-py2.py3-none-any.whl (212kB)
    100% |################################| 215kB 3.9MB/s 
Collecting psutil (from -r requirements.txt (line 14))
  Downloading psutil-5.4.3.tar.gz (412kB)
    100% |################################| 419kB 2.6MB/s 
Collecting cdiff (from -r requirements.txt (line 15))
  Downloading cdiff-1.0.tar.gz
Collecting kubernetes==3.0.0 (from -r requirements.txt (line 16))
  Downloading kubernetes-3.0.0-py2.py3-none-any.whl (815kB)
    100% |################################| 819kB 1.3MB/s 
Collecting certifi>=2017.4.17 (from requests->-r requirements.txt (line 5))
  Downloading certifi-2018.1.18-py2.py3-none-any.whl (151kB)
    100% |################################| 153kB 4.8MB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests->-r requirements.txt (line 5))
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |################################| 143kB 5.5MB/s 
Collecting idna<2.7,>=2.5 (from requests->-r requirements.txt (line 5))
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |################################| 61kB 12.8MB/s 
Collecting dnspython>=1.13.0 (from python-etcd<0.5,>=0.4.3->-r requirements.txt (line 8))
  Downloading dnspython-1.15.0-py2.py3-none-any.whl (177kB)
    100% |################################| 184kB 4.3MB/s 
Collecting pytz (from tzlocal->-r requirements.txt (line 12))
  Downloading pytz-2018.3-py2.py3-none-any.whl (509kB)
    100% |################################| 512kB 2.3MB/s 
Collecting ipaddress>=1.0.17 (from kubernetes==3.0.0->-r requirements.txt (line 16))
  Downloading ipaddress-1.0.19.tar.gz
Collecting websocket-client<=0.40.0,>=0.32.0 (from kubernetes==3.0.0->-r requirements.txt (line 16))
  Downloading websocket_client-0.40.0.tar.gz (196kB)
    100% |################################| 204kB 4.9MB/s 
Collecting google-auth>=1.0.1 (from kubernetes==3.0.0->-r requirements.txt (line 16))
  Downloading google_auth-1.4.1-py2.py3-none-any.whl (65kB)
    100% |################################| 71kB 6.6MB/s 
Collecting setuptools>=21.0.0 (from kubernetes==3.0.0->-r requirements.txt (line 16))
  Downloading setuptools-39.0.1-py2.py3-none-any.whl (569kB)
    100% |################################| 573kB 2.0MB/s 
Collecting backports.ssl_match_hostname (from websocket-client<=0.40.0,>=0.32.0->kubernetes==3.0.0->-r requirements.txt (line 16))
  Downloading backports.ssl_match_hostname-3.5.0.1.tar.gz
Collecting rsa>=3.1.4 (from google-auth>=1.0.1->kubernetes==3.0.0->-r requirements.txt (line 16))
  Downloading rsa-3.4.2-py2.py3-none-any.whl (46kB)
    100% |################################| 51kB 6.4MB/s 
Collecting cachetools>=2.0.0 (from google-auth>=1.0.1->kubernetes==3.0.0->-r requirements.txt (line 16))
  Downloading cachetools-2.0.1-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.2.1 (from google-auth>=1.0.1->kubernetes==3.0.0->-r requirements.txt (line 16))
  Downloading pyasn1_modules-0.2.1-py2.py3-none-any.whl (60kB)
    100% |################################| 61kB 8.1MB/s 
Collecting pyasn1>=0.1.3 (from rsa>=3.1.4->google-auth>=1.0.1->kubernetes==3.0.0->-r requirements.txt (line 16))
  Downloading pyasn1-0.4.2-py2.py3-none-any.whl (71kB)
    100% |################################| 71kB 7.7MB/s 
Building wheels for collected packages: PyYAML, python-etcd, prettytable, tzlocal, psutil, cdiff, ipaddress, websocket-client, backports.ssl-match-hostname
  Running setup.py bdist_wheel for PyYAML ... done
  Stored in directory: /root/.cache/pip/wheels/2c/f7/79/13f3a12cd723892437c0cfbde1230ab4d82947ff7b3839a4fc
  Running setup.py bdist_wheel for python-etcd ... done
  Stored in directory: /root/.cache/pip/wheels/d1/79/df/26facc508cdb5fefaf3d574fb634d848754a7e69d95f53f056
  Running setup.py bdist_wheel for prettytable ... done
  Stored in directory: /root/.cache/pip/wheels/0d/08/4d/38d1751a9e86f7f568d619e8e0662fb85241d17df8c90c5d8a
  Running setup.py bdist_wheel for tzlocal ... done
  Stored in directory: /root/.cache/pip/wheels/7c/a1/5d/0f37ce6eb6eea391bd185f5747429a93519be115d007263bcf
  Running setup.py bdist_wheel for psutil ... done
  Stored in directory: /root/.cache/pip/wheels/8b/83/e9/f0feab7d059e177e6f3834f42b8a302805fd83dbb16405515a
  Running setup.py bdist_wheel for cdiff ... done
  Stored in directory: /root/.cache/pip/wheels/d9/67/dc/d53a3cfea638a5652d0d2054b447d67a7d2a2bdebf0f67765e
  Running setup.py bdist_wheel for ipaddress ... done
  Stored in directory: /root/.cache/pip/wheels/d7/6b/69/666188e8101897abb2e115d408d139a372bdf6bfa7abb5aef5
  Running setup.py bdist_wheel for websocket-client ... done
  Stored in directory: /root/.cache/pip/wheels/d1/5e/dd/93da015a0ecc8375278b05ad7f0452eff574a044bcea2a95d2
  Running setup.py bdist_wheel for backports.ssl-match-hostname ... done
  Stored in directory: /root/.cache/pip/wheels/5d/72/36/b2a31507b613967b728edc33378a5ff2ada0f62855b93c5ae1
Successfully built PyYAML python-etcd prettytable tzlocal psutil cdiff ipaddress websocket-client backports.ssl-match-hostname
Installing collected packages: urllib3, boto, psycopg2, PyYAML, certifi, chardet, idna, requests, six, kazoo, dnspython, python-etcd, python-consul, click, prettytable, pytz, tzlocal, python-dateutil, psutil, cdiff, ipaddress, backports.ssl-match-hostname, websocket-client, pyasn1, rsa, cachetools, pyasn1-modules, google-auth, setuptools, kubernetes
  Found existing installation: setuptools 20.7.0
    Not uninstalling setuptools at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed PyYAML-3.12 backports.ssl-match-hostname-3.5.0.1 boto-2.48.0 cachetools-2.0.1 cdiff-1.0 certifi-2018.1.18 chardet-3.0.4 click-6.7 dnspython-1.15.0 google-auth-1.4.1 idna-2.6 ipaddress-1.0.19 kazoo-2.4.0 kubernetes-3.0.0 prettytable-0.7.2 psutil-5.4.3 psycopg2-2.7.4 pyasn1-0.4.2 pyasn1-modules-0.2.1 python-consul-0.7.2 python-dateutil-2.7.2 python-etcd-0.4.5 pytz-2018.3 requests-2.18.4 rsa-3.4.2 setuptools-39.0.1 six-1.11.0 tzlocal-1.5.1 urllib3-1.22 websocket-client-0.40.0
root@64dae6ec3f64:/opt/patroni# ./patroni.py postgres0.yml 
/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
2018-03-29 11:00:26,118 INFO: Selected new etcd server http://127.0.0.1:2379
and so on...
```

I think you are hitting a problem similar to https://github.com/zalando/patroni/issues/642

P.S. please don't run Patroni from root, it doesn't make sense because postgres will refuse to work from root anyway.

**Comment by CyberDem0n** [comment]
All right, it looks that original issue is solved.

Now Patroni can't find postgres binaries.
Either you have to add `/usr/lib/postgresql/10/bin` to `$PATH` or add it to `postgresql.bin_dir` in Patroni config

**Comment by tschmidt82** [comment]
```
root@0310e3221f75:/tmp/patroni# su user -c "cd /tmp/patroni/ && ./patroni.py postgres0.yml "
2018-03-29 18:30:26,975 INFO: Selected new etcd server http://127.0.0.1:2379
2018-03-29 18:30:26,980 INFO: Lock owner: None; I am postgresql0
2018-03-29 18:30:26,981 INFO: trying to bootstrap a new cluster
2018-03-29 18:30:26,986 ERROR: Exception during execution of long running task bootstrap
Traceback (most recent call last):
  File "/tmp/patroni/patroni/async_executor.py", line 97, in run
    wakeup = func(*args) if args else func()
  File "/tmp/patroni/patroni/postgresql.py", line 1556, in bootstrap
    return do_initialize(config) and self.write_pg_hba(pg_hba) and self.save_configuration_files() \
  File "/tmp/patroni/patroni/postgresql.py", line 537, in _initdb
    ret = self.pg_ctl('initdb', *options)
  File "/tmp/patroni/patroni/postgresql.py", line 283, in pg_ctl
    return subprocess.call(pg_ctl + ['-D', self._data_dir] + list(args), **kwargs) == 0
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
2018-03-29 18:30:26,990 INFO: removing initialize key after failed attempt to bootstrap the cluster
2018-03-29 18:30:27,480 INFO: Lock owner: None; I am postgresql0
Traceback (most recent call last):
  File "./patroni.py", line 6, in <module>
    main()
  File "/tmp/patroni/patroni/__init__.py", line 176, in main
    return patroni_main()
  File "/tmp/patroni/patroni/__init__.py", line 145, in patroni_main
    patroni.run()
  File "/tmp/patroni/patroni/__init__.py", line 114, in run
    logger.info(self.ha.run_cycle())
  File "/tmp/patroni/patroni/ha.py", line 1134, in run_cycle
    info = self._run_cycle()
  File "/tmp/patroni/patroni/ha.py", line 1058, in _run_cycle
    return self.post_bootstrap()
  File "/tmp/patroni/patroni/ha.py", line 962, in post_bootstrap
    self.cancel_initialization()
  File "/tmp/patroni/patroni/ha.py", line 957, in cancel_initialization
    raise PatroniException('Failed to bootstrap cluster')
patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'
root@0310e3221f75:/tmp/patroni# ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.1  18248  3232 pts/0    Ss   18:16   0:00 bash
root      4133  0.1  0.8 160976 17496 pts/0    Sl   18:19   0:00 etcd --data-dir=data/etcd
root      7281  0.0  0.1  34424  2868 pts/0    R+   18:30   0:00 ps -aux
root@0310e3221f75:/tmp/patroni# su user -c echo $PATH

root@0310e3221f75:/tmp/patroni# su user -c "echo $PATH"
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/10/bin/
root@0310e3221f75:/tmp/patroni#

```

**Comment by CyberDem0n** [comment]
There is still something wrong and Patroni can't find postgres binaries.

**Comment by tschmidt82** [comment]
okay thank you ... this helps ... will try further
