### ISSUE TITLE
Patroni switched master to replica being in maintenance mode when consul was unavailable

### ISSUE THREAD

**Issue by AntonTumasov** [zalando/patroni#659]
During `maintenance mode` of cluster we had consul cluster unavailable for 10 minutes and patroni decided to shutdown master and switch him to replica, since we had two replica and application broke while was trying to reach master. Is it okay that patroni behaves in such a way even if we set up `pause`?

**Comment by CyberDem0n** [comment]
That's interesting.
What is in the Patroni logs?

**Comment by AntonTumasov** [comment]
Here is a stacktrace for both master and replica

 ```Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: 2018-04-05 05:03:50,511 - ERROR - get_cluster
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: Traceback (most recent call last):
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: File "/opt/patroni/lib/python2.7/site-packages/patroni/dcs/consul.py", line 249, in _l
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: _, results = self.retry(self._client.kv.get, path, recurse=True)
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: File "/opt/patroni/lib/python2.7/site-packages/patroni/dcs/consul.py", line 180, in re
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: return self._retry.copy()(*args, **kwargs)
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: File "/opt/patroni/lib/python2.7/site-packages/patroni/utils.py", line 263, in __call_
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: raise RetryFailedError("Exceeded retry deadline")
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: RetryFailedError: 'Exceeded retry deadline'
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: Traceback (most recent call last):
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: File "<string>", line 1, in <module>
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: File "/opt/patroni/lib/python2.7/site-packages/click/core.py", line 722, in __call__
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: return self.main(*args, **kwargs)
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: File "/opt/patroni/lib/python2.7/site-packages/click/core.py", line 697, in main
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: rv = self.invoke(ctx)
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: File "/opt/patroni/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: return _process_result(sub_ctx.command.invoke(sub_ctx))
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: File "/opt/patroni/lib/python2.7/site-packages/click/core.py", line 895, in invoke
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: return ctx.invoke(self.callback, **ctx.params)
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: File "/opt/patroni/lib/python2.7/site-packages/click/core.py", line 535, in invoke
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: return callback(*args, **kwargs)
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: File "/opt/patroni/lib/python2.7/site-packages/click/decorators.py", line 27, in new_f
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: return f(get_current_context().obj, *args, **kwargs)
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: File "/opt/patroni/lib/python2.7/site-packages/patroni/ctl.py", line 754, in members
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: cluster = dcs.get_cluster()
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: File "/opt/patroni/lib/python2.7/site-packages/patroni/dcs/__init__.py", line 462, in
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: self._load_cluster()
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: File "/opt/patroni/lib/python2.7/site-packages/patroni/dcs/consul.py", line 305, in _l
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: raise ConsulError('Consul is not responding properly')
Apr 05 05:03:50 sjc-db-le1-3.prod python[27245]: patroni.dcs.consul.ConsulError: 'Consul is not responding properly'```

**Comment by CyberDem0n** [comment]
It looks like a stacktrace of patronictl utility, but not Patroni.

**Comment by AntonTumasov** [comment]
Then where do I get daemon logs? These logs are from journald

**Comment by CyberDem0n** [comment]
@AntonTumasov unfortunately this is something you will have to figure out on your own.

**Comment by AntonTumasov** [comment]
I guess, this is more relevant right here  
```Apr 12 23:03:40 led-patroni1.infra python[2643]: Traceback (most recent call last):
Apr 12 23:03:40 led-patroni1.infra python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
Apr 12 23:03:40 led-patroni1.infra python[2643]: self.finish_request(request, client_address)
Apr 12 23:03:40 led-patroni1.infra python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
Apr 12 23:03:40 led-patroni1.infra python[2643]: self.RequestHandlerClass(request, client_address, self)
Apr 12 23:03:40 led-patroni1.infra python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
Apr 12 23:03:40 led-patroni1.infra python[2643]: self.finish()
Apr 12 23:03:40 led-patroni1.infra python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
Apr 12 23:03:40 led-patroni1.infra python[2643]: self.wfile.close()
Apr 12 23:03:40 led-patroni1.infra python[2643]: File "/usr/lib64/python2.7/socket.py", line 279, in close
Apr 12 23:03:40 led-patroni1.infra python[2643]: self.flush()
Apr 12 23:03:40 led-patroni1.infra python[2643]: File "/usr/lib64/python2.7/socket.py", line 303, in flush
Apr 12 23:03:40 led-patroni1.infra python[2643]: self._sock.sendall(view[write_offset:write_offset+buffer_size])
Apr 12 23:03:40 led-patroni1.infra python[2643]: error: [Errno 32] Broken pipe
```
Step to reproduce:
  - Bootstrap cluster with consul as DCS
  - Set up each cluster member to use local consul agent ( 127.0.0.1:8500)
  - execute `patronictl pause`
  - stop consul agent on each node
  - watch logs

**Comment by AntonTumasov** [comment]
```Apr 12 23:28:11  python[2643]: 2018-04-12 23:28:11,795 INFO: no action.  i am the leader with the lock
Apr 12 23:28:14  python[2643]: 2018-04-12 23:28:14,888 INFO: Lock owner: patroni1; I am patroni1
Apr 12 23:28:14  python[2643]: 2018-04-12 23:28:14,938 INFO: PAUSE: no action.  i am the leader with the lock
Apr 12 23:28:34  python[2643]: 2018-04-12 23:28:34,893 INFO: Lock owner: patroni1; I am patroni1
Apr 12 23:28:34  python[2643]: 2018-04-12 23:28:34,900 INFO: PAUSE: no action.  i am the leader with the lock
Apr 12 23:29:05  python[2643]: 2018-04-12 23:29:04,890 ERROR: get_cluster
Apr 12 23:29:05  python[2643]: Traceback (most recent call last):
Apr 12 23:29:05  python[2643]: File "/opt/patroni/lib/python2.7/site-packages/patroni/dcs/consul.py", line 249, in _load_cluster
Apr 12 23:29:05  python[2643]: _, results = self.retry(self._client.kv.get, path, recurse=True)
Apr 12 23:29:05  python[2643]: File "/opt/patroni/lib/python2.7/site-packages/patroni/dcs/consul.py", line 180, in retry
Apr 12 23:29:05  python[2643]: return self._retry.copy()(*args, **kwargs)
Apr 12 23:29:05  python[2643]: File "/opt/patroni/lib/python2.7/site-packages/patroni/utils.py", line 263, in __call__
Apr 12 23:29:05  python[2643]: raise RetryFailedError("Exceeded retry deadline")
Apr 12 23:29:05  python[2643]: RetryFailedError: 'Exceeded retry deadline'
Apr 12 23:29:05  python[2643]: 2018-04-12 23:29:04,891 ERROR: Error communicating with DCS
Apr 12 23:29:05  python[2643]: 2018-04-12 23:29:04,891 INFO: PAUSE: DCS is not accessible
Apr 12 23:29:05  python[2643]: Traceback (most recent call last):
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
Apr 12 23:29:05  python[2643]: self.finish_request(request, client_address)
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
Apr 12 23:29:05  python[2643]: self.RequestHandlerClass(request, client_address, self)
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
Apr 12 23:29:05  python[2643]: self.finish()
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
Apr 12 23:29:05  python[2643]: self.wfile.close()
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/socket.py", line 279, in close
Apr 12 23:29:05  python[2643]: self.flush()
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/socket.py", line 303, in flush
Apr 12 23:29:05  python[2643]: self._sock.sendall(view[write_offset:write_offset+buffer_size])
Apr 12 23:29:05  python[2643]: error: [Errno 32] Broken pipe
Apr 12 23:29:05  python[2643]: Traceback (most recent call last):
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
Apr 12 23:29:05  python[2643]: self.finish_request(request, client_address)
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
Apr 12 23:29:05  python[2643]: self.RequestHandlerClass(request, client_address, self)
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
Apr 12 23:29:05  python[2643]: self.finish()
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
Apr 12 23:29:05  python[2643]: self.wfile.close()
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/socket.py", line 279, in close
Apr 12 23:29:05  python[2643]: self.flush()
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/socket.py", line 303, in flush
Apr 12 23:29:05  python[2643]: self._sock.sendall(view[write_offset:write_offset+buffer_size])
Apr 12 23:29:05  python[2643]: error: [Errno 32] Broken pipe
Apr 12 23:29:05  python[2643]: Traceback (most recent call last):
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
Apr 12 23:29:05  python[2643]: self.finish_request(request, client_address)
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
Apr 12 23:29:05  python[2643]: self.RequestHandlerClass(request, client_address, self)
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
Apr 12 23:29:05  python[2643]: self.finish()
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
Apr 12 23:29:05  python[2643]: self.wfile.close()
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/socket.py", line 279, in close
Apr 12 23:29:05  python[2643]: self.flush()
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/socket.py", line 303, in flush
Apr 12 23:29:05  python[2643]: self._sock.sendall(view[write_offset:write_offset+buffer_size])
Apr 12 23:29:05  python[2643]: error: [Errno 32] Broken pipe
Apr 12 23:29:05  python[2643]: Traceback (most recent call last):
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
Apr 12 23:29:05  python[2643]: self.finish_request(request, client_address)
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
Apr 12 23:29:05  python[2643]: self.RequestHandlerClass(request, client_address, self)
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
Apr 12 23:29:05  python[2643]: self.finish()
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
Apr 12 23:29:05  python[2643]: self.wfile.close()
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/socket.py", line 279, in close
Apr 12 23:29:05  python[2643]: self.flush()
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/socket.py", line 303, in flush
Apr 12 23:29:05  python[2643]: self._sock.sendall(view[write_offset:write_offset+buffer_size])
Apr 12 23:29:05  python[2643]: error: [Errno 32] Broken pipe
Apr 12 23:29:05  python[2643]: Traceback (most recent call last):
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
Apr 12 23:29:05  python[2643]: self.finish_request(request, client_address)
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
Apr 12 23:29:05  python[2643]: self.RequestHandlerClass(request, client_address, self)
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
Apr 12 23:29:05  python[2643]: self.finish()
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
Apr 12 23:29:05  python[2643]: self.wfile.close()
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/socket.py", line 279, in close
Apr 12 23:29:05  python[2643]: self.flush()
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/socket.py", line 303, in flush
Apr 12 23:29:05  python[2643]: self._sock.sendall(view[write_offset:write_offset+buffer_size])
Apr 12 23:29:05  python[2643]: error: [Errno 32] Broken pipe
Apr 12 23:29:05  python[2643]: Traceback (most recent call last):
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
Apr 12 23:29:05  python[2643]: self.finish_request(request, client_address)
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
Apr 12 23:29:05  python[2643]: self.RequestHandlerClass(request, client_address, self)
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
Apr 12 23:29:05  python[2643]: self.finish()
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
Apr 12 23:29:05  python[2643]: self.wfile.close()
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/socket.py", line 279, in close
Apr 12 23:29:05  python[2643]: self.flush()
Apr 12 23:29:05  python[2643]: File "/usr/lib64/python2.7/socket.py", line 303, in flush
Apr 12 23:29:05  python[2643]: self._sock.sendall(view[write_offset:write_offset+buffer_size])
Apr 12 23:29:05  python[2643]: error: [Errno 32] Broken pipe
```

Here is what I get when I execute steps to reproduce

**Comment by AntonTumasov** [comment]
Then when I flush those iptables rules I get 
```Apr 12 23:32:24 python[2643]: 2018-04-12 23:32:24,250 INFO: PAUSE: acquired session lock as a leader
Apr 12 23:32:34 python[2643]: 2018-04-12 23:32:34,900 INFO: Lock owner: patroni1; I am patroni1
Apr 12 23:32:34 python[2643]: 2018-04-12 23:32:34,975 INFO: PAUSE: no action.  i am the leader with the lock
``` @CyberDem0n

**Comment by AntonTumasov** [comment]
If try to set ttl, retry_timeout and loop_wait according to equation, master state is still held by master node until ttl has expired. But API does not return 200 code on `/master` request though, and haproxy thinks master is down

**Comment by AntonTumasov** [comment]
@CyberDem0n FYI

**Comment by uspen** [comment]
You must increase haproxy "timeout check". Because Patroni has timeout for request to DCS and report status to endpoints (/master etc...).

**Comment by AntonTumasov** [comment]
The expected behavior is: 

 ***When the cluster is in maintenance mode we want Patroni not to switch off master out of cluster when it can not connect to DCS, but keep the same exact state until DCS available back again***

Now it behaves just like without maintenance mode, except for the fact failover doesn't happen.
Why the cluster still relies on DCS even then it should not?
 
It's hard to reproduce on stand environment that happened in production and why master was demoted, but it is clear that master shouldn't have been switched off when cluster is on `pause` 

@uspen this is a bit irrelevant here because eventually when the cluster in not in maintenance mode checks should be executed frequently enough to failover

**Comment by CyberDem0n** [comment]
@AntonTumasov, sorry but your logs are still incomplete and there is no evidence that master was restarted in read-only.

```
Apr 12 23:29:05  python[2643]: 2018-04-12 23:29:04,891 INFO: PAUSE: DCS is not accessible
```

This log proves that Patroni knows that cluster is in maintenance mode and doesn't touch postgres.

**Comment by jberkus** [comment]
Wait, isn't the master *supposed* to restart read-only if the DCS is not accessible?

**Comment by uspen** [comment]
Ha-ha. I just upgrade my etcd version and turn Maintenance mode: on.
Just 1 cluster of 17 is failed:

`2018-04-19 14:06:48,189 INFO: PAUSE: demoted self because failed to update leader lock in DCS`

and quorum is healty! BUT!!
Check Patroni coincided with stop etcd


апр 19 14:06:45 04.db patroni[29681]: Traceback (most recent call last):
апр 19 14:06:45 04.db patroni[29681]: File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 338, in wrapper
апр 19 14:06:45 04.db patroni[29681]: retval = func(self, *args, **kwargs) is not None
апр 19 14:06:45 04.db patroni[29681]: File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 529, in _update_leader
апр 19 14:06:45 04.db patroni[29681]: return self.retry(self._client.test_and_set, self.leader_path, self._name, self._name, self._ttl)
апр 19 14:06:45 04.db patroni[29681]: File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 322, in retry
апр 19 14:06:45 04.db patroni[29681]: return self._retry.copy()(*args, **kwargs)
апр 19 14:06:45 04.db patroni[29681]: File "/usr/lib/python2.7/site-packages/patroni/utils.py", line 254, in __call__
апр 19 14:06:45 04.db patroni[29681]: return func(*args, **kwargs)
апр 19 14:06:45 04.db patroni[29681]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 642, in test_and_set
апр 19 14:06:45 04.db patroni[29681]: return self.write(key, value, prevValue=prev_value, ttl=ttl)
апр 19 14:06:45 04.db patroni[29681]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 461, in write
апр 19 14:06:45 04.db patroni[29681]: response = self.api_execute(path, method, params=params)
апр 19 14:06:45 04.db patroni[29681]: File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 217, in api_execute
апр 19 14:06:45 04.db patroni[29681]: return self._handle_server_response(response)
апр 19 14:06:45 04.db patroni[29681]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 928, in _handle_server_response
апр 19 14:06:45 04.db patroni[29681]: etcd.EtcdError.handle(r)
апр 19 14:06:45 04.db patroni[29681]: File "/usr/lib/python2.7/site-packages/etcd/__init__.py", line 304, in handle
апр 19 14:06:45 04.db patroni[29681]: raise exc(msg, payload)
EtcdException: Raft Internal Error : etcdserver: server stopped

**Comment by AntonTumasov** [comment]
@uspen Could you tell your current etcd version and patroni, please?

**Comment by uspen** [comment]
I planning upgrade 2.3 -> 3.1 -> 3.2

Now is {"etcdserver":"3.1.13","etcdcluster":"3.1.0"}
Patroni "version": "1.4.2"

**Comment by AntonTumasov** [comment]
We have 3.2.15 now for etcd and 1.4.3 for Patroni and problem occurs when etcd cluster is not healthy

**Comment by CyberDem0n** [comment]
Ok, I think I now understand what is wrong. Will prepare a fix in a couple of days.
