### ISSUE TITLE
Can't start patroni 

### ISSUE THREAD

**Issue by devlikeops** [zalando/patroni#682]
2018-05-22 13:29:33,712 INFO: Failed to import patroni.dcs.consul
2018-05-22 13:29:33,720 INFO: Selected new etcd server http://10.10.10.10:2379
2018-05-22 13:29:33,734 INFO: Lock owner: None; I am pgsql02
2018-05-22 13:29:33,746 INFO: trying to bootstrap a new cluster
2018-05-22 13:29:33,748 ERROR: Exception during execution of long running task bootstrap
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/patroni-1.4.3-py2.7.egg/patroni/async_executor.py", line 97, in run
    wakeup = func(*args) if args else func()
  File "/usr/local/lib/python2.7/dist-packages/patroni-1.4.3-py2.7.egg/patroni/postgresql.py", line 1561, in bootstrap
    return do_initialize(config) and self.write_pg_hba(pg_hba) and self.save_configuration_files() \
  File "/usr/local/lib/python2.7/dist-packages/patroni-1.4.3-py2.7.egg/patroni/postgresql.py", line 546, in _initdb
    os.write(fd, self._superuser['password'].encode('utf-8'))
AttributeError: 'int' object has no attribute 'encode'
2018-05-22 13:29:33,751 INFO: removing initialize key after failed attempt to bootstrap the cluster
2018-05-22 13:29:34,237 INFO: Lock owner: None; I am pgsql02
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 11, in <module>
    load_entry_point('patroni==1.4.3', 'console_scripts', 'patroni')()
  File "/usr/local/lib/python2.7/dist-packages/patroni-1.4.3-py2.7.egg/patroni/__init__.py", line 176, in main
    return patroni_main()
  File "/usr/local/lib/python2.7/dist-packages/patroni-1.4.3-py2.7.egg/patroni/__init__.py", line 145, in patroni_main
    patroni.run()
  File "/usr/local/lib/python2.7/dist-packages/patroni-1.4.3-py2.7.egg/patroni/__init__.py", line 114, in run
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python2.7/dist-packages/patroni-1.4.3-py2.7.egg/patroni/ha.py", line 1164, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python2.7/dist-packages/patroni-1.4.3-py2.7.egg/patroni/ha.py", line 1077, in _run_cycle
    return self.post_bootstrap()
  File "/usr/local/lib/python2.7/dist-packages/patroni-1.4.3-py2.7.egg/patroni/ha.py", line 976, in post_bootstrap
    self.cancel_initialization()
  File "/usr/local/lib/python2.7/dist-packages/patroni-1.4.3-py2.7.egg/patroni/ha.py", line 971, in cancel_initialization
    raise PatroniException('Failed to bootstrap cluster')
patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'

**Comment by CyberDem0n** [comment]
Hi,

```
File "/usr/local/lib/python2.7/dist-packages/patroni-1.4.3-py2.7.egg/patroni/postgresql.py", line 546, in _initdb
os.write(fd, self._superuser['password'].encode('utf-8'))
AttributeError: 'int' object has no attribute 'encode'
```

It seems that you are using a number as a password.

```yaml
postgresql:
  authentication:
    superuser:
      username: postgres
      password: 12345 # or something similar
```

First of all, it is not secure, but if you really want to do so, please quote it:

```yaml
postgresql:
  authentication:
    superuser:
      username: postgres
      password: '12345'
```
