### ISSUE TITLE
patronictl.py edit-config no effect

### ISSUE THREAD

**Issue by yangshushu** [zalando/patroni#684]
**I use ZooKeeper**
```
[postgres@test143 patroni-1.4.3]$ ./patronictl.py -c postgresmq.yml edit-config batmant1 --apply postgresmq.yml 
2018-05-29 14:39:29,473 - WARNING - Connection dropped: socket connection error: No route to host
--- 
+++ 
@@ -37,7 +37,6 @@
   connect_address: 192.168.1.143:5432
   create_replica_method:
    - wal_e
-  - basebackup
   data_dir: /home/postgres/flyingdb-v3-logical/data
   listen: 0.0.0.0:5432
   parameters:

Apply these changes? [y/N]: y
Configuration changed
```

**Patroni has an error**

```
Traceback (most recent call last):
  File "/home/postgres/patroni-1.4.3/patroni/config.py", line 139, in set_dynamic_configuration
    self._local_configuration)
  File "/home/postgres/patroni-1.4.3/patroni/config.py", line 280, in _build_effective_configuration
    config = self._safe_copy_dynamic_configuration(dynamic_configuration)
  File "/home/postgres/patroni-1.4.3/patroni/config.py", line 185, in _safe_copy_dynamic_configuration
    config[name] = int(value)
TypeError: int() argument must be a string or a number, not 'dict'
```

**This is in /service/batmant1/config**
```
[zk: localhost:2181(CONNECTED) 0] get /service/batmant1/config
{"bootstrap": {"pg_hba": ["host replication replicator 127.0.0.1/32 md5", "host all all 0.0.0.0/0 trust", "host replication ruser 192.168.1.142/32 trust", "host replication ruser 192.168.1.143/32 trust"], "users": {"admin": {"password": "admin", "options": ["createrole", "createdb"]}}, "initdb": [{"encoding": "UTF8"}, "data-checksums"], "dcs": {"ttl": 30, "maximum_lag_on_failover": 1048576, "retry_timeout": 10, "postgresql": {"use_pg_rewind": true, "parameters": {"wal_level": "logical"}}, "loop_wait": 10}}, "postgresql": {"create_replica_method": ["wal_e", "basebackup"], "data_dir": "/home/postgres/flyingdb-v3-logical/data", "parameters": {"unix_socket_directories": "/tmp"}, "pgpass": "/home/postgres/.pgpass", "callbacks": {"on_role_change": "/home/postgres/change_role.py"}, "authentication": {"replication": {"username": "ruser", "password": "123456"}, "superuser": {"username": "postgres", "password": "123456"}}, "connect_address": "192.168.1.143:5432", "listen": "0.0.0.0:5432"}, "name": "postgresql143", "tags": {"nofailover": false, "noloadbalance": false, "clonefrom": false, "nosync": false}, "restapi": {"connect_address": "192.168.1.143:8009", "listen": "192.168.1.143:8009"}, "zookeeper": {"hosts": "192.168.1.140:2181,192.168.1.141:2181,192.168.1.142:2181,192.168.1.143:2181,192.168.1.144:2181,192.168.1.145:2181,192.168.1.146:2181"}, "namespace": "/service/", "watchdog": {"device": "/dev/watchdog", "safety_margin": 5, "mode": false}, "scope": "batmant1"}
```

**Comment by CyberDem0n** [comment]
Hi,

First of all, `patronictl edit-config` should be used only to manage global cluster configuration.
It should not contain any node-specific settings like `connect_address`, `listen`, `data_dir` and so on.

Also it should not contain anything except sections `postgresql` and `watchdog` and bunch of cluster-wide parameters, like: `ttl`, `loop_wait`, `retry_timeout`, `maximum_lag_on_failover`, `master_start_timeout`, `synchronous_mode` and `synchronous_mode_strict`

There should be something like:
```yaml
loop_wait: 10
retry_timeout: 10
ttl: 30
maximum_lag_on_failover: 1048576
postgresql:
  use_pg_rewind: true
  create_replica_method:
  - wal_e
  wal_e:
    command: patroni_wale_restore
    # bunch of other options documented here: http://patroni.readthedocs.io/en/latest/replica_bootstrap.html#building-replicas
  parameters:
    max_connections: 300
    wal_level: logical
```

It looks like you just pushed patroni config from the node to DCS and Patroni doesn't like that there is a `bootstrap`, `restapi` and `tags` sections and some other parameters like `name` and `scope`.


We will definitely fix it, and ignore all parameters set in DCS which are not expected instead of just failing, but for you an easy fix would be running `patronictl edit-config` and removing everything what shouldn't be there

**Comment by yangshushu** [comment]
thank you,i'm changes create_replica_method in yml file and use patronictl edit-config.not effect .
i use like:
```
[postgres@test143 patroni-1.4.3]$ ./patronictl.py -c postgresmq.yml edit-config batmant1 --apply postgresmqup.yml 
--- 
+++ 
@@ -22,6 +22,7 @@
       - createrole
       - createdb
       password: admin
+maximum_lag_on_failover: 1048576
 name: postgresql143
 namespace: /service/
 postgresql:

Apply these changes? [y/N]: y
Configuration changed
```
postgresmqup.yml is:
```
[postgres@test142 patroni-1.4.3]$ cat postgresmqup.yml
postgresql:
  create_replica_method:
      - wal_e
      - basebackup
```
Patroni still reports this error and changes is not effect

```
Traceback (most recent call last):
  File "/home/postgres/patroni-1.4.3/patroni/config.py", line 139, in set_dynamic_configuration
    self._local_configuration)
  File "/home/postgres/patroni-1.4.3/patroni/config.py", line 279, in _build_effective_configuration
    config = self._safe_copy_dynamic_configuration(dynamic_configuration)
  File "/home/postgres/patroni-1.4.3/patroni/config.py", line 184, in _safe_copy_dynamic_configuration
    config[name] = int(value)
TypeError: int() argument must be a string or a number, not 'dict'
```

so,patronictl Does not support node-specific settings like 'create_replica_method'.
I still don't understand why this error is reported.

**Comment by CyberDem0n** [comment]
`patronictl edit-config --apply postgresmqup.yml` -- this command will apply changes to an existing config. It will change only parameters you have in the `postgresmqup.yml`

Bit it seems that you want to use `patronictl edit-config --replace` to replace the config stored in dcs with config from the file.

**Comment by yangshushu** [comment]
yes,'patronictl edit-config --replace' This error will not be reported again.
but,use --replace ,Is it not in the postgresmqup.yml parameters have all become default values?

**Comment by CyberDem0n** [comment]
You can also call `patronictl edit-config cluster-name` without specifying any additional parameters.
It will open an EDITOR for you where you can make changes, save and exit.

**Comment by yangshushu** [comment]
Thank you very much

**Comment by big-town** [comment]
If you see this message "FileNotFoundError: [Errno 2] No such file or directory: 'less': 'less'". You need install utils less.
