### ISSUE TITLE
Getting 'No such file or directory' error

### ISSUE THREAD

**Issue by imcitius** [zalando/patroni#714]
Hello

I'm trying to replace failed third replica in one of the clusters, and getting strange error.
After starting patroni, it gets DB files from master, and then, when try to start postgres, throw this error:

```
systemd[1]: Starting Runners to orchestrate a high-availability PostgreSQL...
patroni.py[69198]: 2018-06-18 20:42:19,557 INFO: Starting new HTTP connection (1): 127.0.0.1 
patroni.py[69198]: 2018-06-18 20:42:19,727 INFO: Lock owner: pgsql-03; I am pgsql-02
patroni.py[69198]: Traceback (most recent call last):
patroni.py[69198]: File "/opt/patroni/patroni.py", line 6, in <module>
patroni.py[69198]: main()
patroni.py[69198]: File "/opt/patroni/patroni/__init__.py", line 179, in main
patroni.py[69198]: return patroni_main()
patroni.py[69198]: File "/opt/patroni/patroni/__init__.py", line 148, in patroni_main
patroni.py[69198]: patroni.run()
patroni.py[69198]: File "/opt/patroni/patroni/__init__.py", line 114, in run
patroni.py[69198]: logger.info(self.ha.run_cycle())
patroni.py[69198]: File "/opt/patroni/patroni/ha.py", line 1154, in run_cycle
patroni.py[69198]: info = self._run_cycle()
patroni.py[69198]: File "/opt/patroni/patroni/ha.py", line 1100, in _run_cycle
patroni.py[69198]: data_sysid = self.state_handler.sysid
patroni.py[69198]: File "/opt/patroni/patroni/postgresql.py", line 412, in sysid
patroni.py[69198]: data = self.controldata()
patroni.py[69198]: File "/opt/patroni/patroni/postgresql.py", line 1204, in controldata
patroni.py[69198]: env={'LANG': 'C', 'LC_ALL': 'C', 'PATH': os.environ['PATH']})
patroni.py[69198]: File "/usr/lib64/python2.7/subprocess.py", line 568, in check_output
patroni.py[69198]: process = Popen(stdout=PIPE, *popenargs, **kwargs)
patroni.py[69198]: File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
patroni.py[69198]: errread, errwrite)
patroni.py[69198]: File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
patroni.py[69198]: raise child_exception
patroni.py[69198]: OSError: [Errno 2] No such file or directory
systemd[1]: patroni.service: main process exited, code=exited, status=1/FAILURE
systemd[1]: Unit patroni.service entered failed state.
systemd[1]: patroni.service failed.
```

Consul used as DCS, with agent on 127.0.0.1.

The system is Centos 7.4, with Postgres 9.6:
```
[root@pgsql-02 patroni]# rpm -qa postgresql*
postgresql96-server-9.6.9-1PGDG.rhel7.x86_64
postgresql96-libs-9.6.9-1PGDG.rhel7.x86_64
postgresql96-9.6.9-1PGDG.rhel7.x86_64
postgresql96-contrib-9.6.9-1PGDG.rhel7.x86_64
postgresql96-pgroonga-2.0.7-1.el7.centos.x86_64
```

**Comment by CyberDem0n** [comment]
Please make sure that Patroni can find all postgres binaries, either in the search PATH or by specifying postgresql.bin_dir

**Comment by CyberDem0n** [comment]
> "Environment=PATH=PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/var/lib/pgsql/bin:/usr/pgsql-9.6/bin"

It feels wrong to me. Why there is a double "PATH="?

**Comment by imcitius** [comment]
Shame on me.
Thanks, guys.
