### ISSUE TITLE
'ReadTimeoutError' getting consul leader with index property in secondary

### ISSUE THREAD

**Issue by carlosmkb** [zalando/patroni#734]
In secondary the following error occurs almost every second. If the secondary becomes new primary this erros stops and starts in the other secondary.
```
2018-07-13 09:34:04,711 ERROR: watch
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/patroni/dcs/consul.py", line 406, in watch
idx, _ = self._client.kv.get(self.leader_path, index=leader_index, wait=str(timeout) + 's')
File "/usr/lib/python2.7/site-packages/consul/base.py", line 554, in get
params=params)
File "/usr/lib/python2.7/site-packages/patroni/dcs/consul.py", line 102, in wrapper
return callback(self.response(self.http.request(method.upper(), self.uri(path, params), **kwargs)))
File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 68, in request
**urlopen_kw)
File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 89, in request_encode_url
return self.urlopen(method, url, **extra_kw)
File "/usr/lib/python2.7/site-packages/urllib3/poolmanager.py", line 322, in urlopen
response = conn.urlopen(method, u.request_uri, **kw)
File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
_stacktrace=sys.exc_info()[2])
File "/usr/lib/python2.7/site-packages/urllib3/util/retry.py", line 398, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
MaxRetryError: HTTPConnectionPool(host='server.raid.test', port=8500): Max retries exceeded with url: /v1/kv/service/postgres/leader?index=159&wait=3.26965403557s (Caused by ReadTimeoutError("HTTPConnectionPool(host='server.raid.test', port=8500): Read timed out. (read timeout=3.33333333333)",))
2018-07-13 09:34:04,716 INFO: Lock owner: postgres-2; I am postgres-1
2018-07-13 09:34:04,716 INFO: does not have lock
2018-07-13 09:34:04,718 INFO: no action.  i am a secondary and i am following a leader
```

**Comment by CyberDem0n** [comment]
Please try https://github.com/zalando/patroni/pull/744, I hope it should fix your problem
