### ISSUE TITLE
edit-config - [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by vitabaks** [zalando/patroni#740]
Please suggest the cause of the error:

export EDITOR=vim
patronictl -c /etc/patroni/patroni.yml edit-config mydb-cluster

Traceback (most recent call last):
  File "/usr/local/bin/patronictl", line 11, in <module>
    sys.exit(ctl())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/patroni/ctl.py", line 1091, in edit_config
    show_diff(before_editing, after_editing)
  File "/usr/local/lib/python2.7/dist-packages/patroni/ctl.py", line 951, in show_diff
    cdiff.markup_to_pager(cdiff.PatchStream(buf), opts)
  File "/usr/local/lib/python2.7/dist-packages/cdiff.py", line 640, in markup_to_pager
    pager_cmd, stdin=subprocess.PIPE, stdout=sys.stdout)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

--------------------
pip list

boto (2.49.0)
cdiff (1.0)
certifi (2018.4.16)
chardet (3.0.4)
click (6.7)
cryptography (1.7.1)
dnspython (1.15.0)
enum34 (1.1.6)
idna (2.7)
ipaddress (1.0.17)
kazoo (2.5.0)
keyring (10.1)
keyrings.alt (1.3)
patroni (1.4.4)
pip (9.0.1)
prettytable (0.7.2)
psutil (5.4.6)
psycopg2 (2.7.5)
psycopg2-binary (2.7.5)
pyasn1 (0.1.9)
pycrypto (2.6.1)
pygobject (3.22.0)
python-dateutil (2.7.3)
python-etcd (0.4.5)
pytz (2018.5)
pyxdg (0.25)
PyYAML (3.13)
requests (2.19.1)
SecretStorage (2.3.1)
setuptools (40.0.0)
six (1.10.0)
tzlocal (1.5.1)
urllib3 (1.22)
wheel (0.29.0)

**Comment by alexeyklyukin** [comment]
```
File "/usr/local/lib/python2.7/dist-packages/cdiff.py", line 640, in markup_to_pager
pager_cmd, stdin=subprocess.PIPE, stdout=sys.stdout)
File "/usr/lib/python2.7/subprocess.py", line 390, in init
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory
```

markup_to_pager tries to execute `less -FRSX --shift 1` unless you define the `LESS` environment variable, in which case less will take arguments from there. You sure you have `less` on your system?

**Comment by vitabaks** [comment]
A package of less was not installed...

Thank you!

**Comment by rexroof** [comment]
can this be revisited?   edit-config shouldn't require less.  if it needs a pager, it should honor the PAGER environment variable.
