### ISSUE TITLE
Patroni cannot start, consul answer timeout

### ISSUE THREAD

**Issue by imcitius** [zalando/patroni#742]
Hello

Just got strange situation with new replica installed in remote datacenter.
Patroni cannot start up with this error:

```
Jul 19 15:09:47 pgsql patroni.py[68505]: 2018-07-19 15:09:47,224 INFO: Lock owner: pgsql-04; I am pgsql-readonly-02
Jul 19 15:09:47 pgsql patroni.py[68505]: 2018-07-19 15:09:47,224 INFO: starting as a secondary
Jul 19 15:09:47 pgsql patroni.py[68505]: 2018-07-19 15:09:47,247 INFO: postmaster pid=68580
Jul 19 15:09:47 pgsql patroni.py[68505]: 2018-07-19 15:09:47,266 INFO: Lock owner: pgsql-04; I am pgsql-readonly-02
Jul 19 15:09:47 pgsql patroni.py[68505]: localhost:5432 - no response
Jul 19 15:09:47 pgsql patroni.py[68505]: 2018-07-19 15:09:47,307 INFO: restarting after failure in progress
Jul 19 15:09:47 pgsql patroni.py[68505]: 2018-07-19 15:09:47.370 UTC 68580 @ from  [vxid: txid:0] [] LOG:  redirecting log output to logging collector process
Jul 19 15:09:47 pgsql patroni.py[68505]: 2018-07-19 15:09:47.370 UTC 68580 @ from  [vxid: txid:0] [] HINT:  Future log output will appear in directory "/var/log/postgresql".
Jul 19 15:09:48 pgsql patroni.py[68505]: localhost:5432 - rejecting connections
Jul 19 15:09:48 pgsql patroni.py[68505]: localhost:5432 - rejecting connections
Jul 19 15:09:49 pgsql patroni.py[68505]: localhost:5432 - accepting connections
Jul 19 15:09:49 pgsql patroni.py[68505]: 2018-07-19 15:09:49,366 INFO: Lock owner: pgsql-04; I am pgsql-readonly-02
Jul 19 15:09:49 pgsql patroni.py[68505]: 2018-07-19 15:09:49,366 INFO: does not have lock
Jul 19 15:09:49 pgsql patroni.py[68505]: 2018-07-19 15:09:49,366 INFO: establishing a new patroni connection to the postgres cluster
Jul 19 15:09:49 pgsql patroni.py[68505]: 2018-07-19 15:09:49,413 INFO: no action.  i am a secondary and i am following a leader
Jul 19 15:09:52 pgsql patroni.py[68505]: 2018-07-19 15:09:52,750 ERROR: watch
Jul 19 15:09:52 pgsql patroni.py[68505]: Traceback (most recent call last):
Jul 19 15:09:52 pgsql patroni.py[68505]: File "/opt/patroni/patroni/dcs/consul.py", line 406, in watch
Jul 19 15:09:52 pgsql patroni.py[68505]: idx, _ = self._client.kv.get(self.leader_path, index=leader_index, wait=str(timeout) + 's')
Jul 19 15:09:52 pgsql patroni.py[68505]: File "/usr/lib/python2.7/site-packages/consul/base.py", line 554, in get
Jul 19 15:09:52 pgsql patroni.py[68505]: params=params)
Jul 19 15:09:52 pgsql patroni.py[68505]: File "/opt/patroni/patroni/dcs/consul.py", line 102, in wrapper
Jul 19 15:09:52 pgsql patroni.py[68505]: return callback(self.response(self.http.request(method.upper(), self.uri(path, params), **kwargs)))
Jul 19 15:09:52 pgsql patroni.py[68505]: File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 68, in request
Jul 19 15:09:52 pgsql patroni.py[68505]: **urlopen_kw)
Jul 19 15:09:52 pgsql patroni.py[68505]: File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 81, in request_encode_url
Jul 19 15:09:52 pgsql patroni.py[68505]: return self.urlopen(method, url, **urlopen_kw)
Jul 19 15:09:52 pgsql patroni.py[68505]: File "/usr/lib/python2.7/site-packages/urllib3/poolmanager.py", line 247, in urlopen
Jul 19 15:09:52 pgsql patroni.py[68505]: response = conn.urlopen(method, u.request_uri, **kw)
Jul 19 15:09:52 pgsql patroni.py[68505]: File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 597, in urlopen
Jul 19 15:09:52 pgsql patroni.py[68505]: _stacktrace=sys.exc_info()[2])
Jul 19 15:09:52 pgsql patroni.py[68505]: File "/usr/lib/python2.7/site-packages/urllib3/util/retry.py", line 271, in increment
Jul 19 15:09:52 pgsql patroni.py[68505]: raise MaxRetryError(_pool, url, error or ResponseError(cause))
Jul 19 15:09:52 pgsql patroni.py[68505]: MaxRetryError: HTTPConnectionPool(host='192.168.113.35', port=8500): Max retries exceeded with url: /v1/kv/service/prod-pgsql/leader?index=22407311&wait=9.91164708138s (Caused by ReadTimeoutError("HTTPConnectionPool(host='192.168.113.35', port=8500): Read timed out. (read timeout=3.33333333333)",))
```

At the same time Postgres process is working and serving. 
Patroni asks consul using `wait=xxx` parameters which seems to be longer (6-9 sec) than asnwer timeout it waits.

I tried to curl the same consul api, and consul answers in time:
```
[root@read-replica-02 ~]# curl "http://192.168.113.35:8500/v1/kv/service/prod-pgsql/leader?index=29397573&wait=6.49323987961s"
[{"LockIndex":1,"Key":"service/prod-pgsql/leader","Flags":0,"Value":"c2lhbW9wdGlvbi1wZ3NxbC0wNQ==","Session":"c019d8b8-dae4-e640-5cbe-f90682f7ce8f","CreateIndex":29397573,"ModifyIndex":29397573}]
real    0m6.681s
user    0m0.000s
sys     0m0.003s


[root@read-replica-02 ~]# time curl "http://192.168.113.35:8500/v1/kv/service/prod-pgsql/leader?index=29397573&wait=0.49323987961s"
[{"LockIndex":1,"Key":"service/prod-pgsql/leader","Flags":0,"Value":"c2lhbW9wdGlvbi1wZ3NxbC0wNQ==","Session":"c019d8b8-dae4-e640-5cbe-f90682f7ce8f","CreateIndex":29397573,"ModifyIndex":29397573}]
real    0m0.536s
user    0m0.002s
sys     0m0.001s

```

What should I do?
Thanks.

ps: please do not mention different host and cluster names, this is artifacts of testing and cleaning log on different servers.

**Comment by CyberDem0n** [comment]
Please try https://github.com/zalando/patroni/pull/744, I hope it should fix your problem

**Comment by imcitius** [comment]
Looking good, problem disappeared.
Thanks!
