### ISSUE TITLE
Error out in attempting to start first replica with current HEAD

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#76]
I'm trying to test the code which merges in the basebackup back to postgresql.py.  However, when I try to start the first replica, I get this error:

2015-10-22 18:49:34,852 INFO: Starting new HTTP connection (1): 172.17.0.5
pg_ctl: directory "data/postgresql2" is not a database cluster directory
Traceback (most recent call last):
  File "./patroni.py", line 6, in <module>
    main()
  File "/home/josh/patroni/patroni/__init__.py", line 69, in main
    patroni.run()
  File "/home/josh/patroni/patroni/__init__.py", line 50, in run
    logger.info(self.ha.run_cycle())
  File "/home/josh/patroni/patroni/ha.py", line 414, in run_cycle
    return self._run_cycle()
  File "/home/josh/patroni/patroni/ha.py", line 364, in _run_cycle
    self.touch_member()
  File "/home/josh/patroni/patroni/ha.py", line 53, in touch_member
    'state': self.state_handler.state,
AttributeError: Postgresql instance has no attribute 'state'

It seems that it's not correctly detecting that there's an empty data dir, and I can't quite figure out why.  This wasn't happening before I merged the most recent HEAD.

**Comment by CyberDem0n** [comment]
Are you sure that you are really pulled all latest changes from master HEAD?
Looking on trace I could tell that postgresql.py is not up to date...

Do you have your work saved somewhere before you pulled latest changes from HEAD?

**Comment by jberkus** [comment]
Hmmmm.   Well, the basebackup changes involved a lot of changes to postgresql.py; I had to do a hand-merge.  Lemme see what a diff has for me; are some of those variables new?

**Comment by jberkus** [comment]
Feh, I see.  Git merge fail. Not sure what happened there ....

**Comment by jberkus** [comment]
Closing
