### ISSUE TITLE
Getting the  error 403 while try do second switchover

### ISSUE THREAD

**Issue by tigranav** [zalando/patroni#775]
I have setup with PATRONI 1.4.5 with Kubernetes 3.9 as DCS.
When i try do **second** switchover with `patronyctl` i getting error :
```
Switchover failed, details: 503, failed to write switchover key into DCS
```
i can do second switchover only after delete configmap  `xxxxxx-failover`.

I guess couse of error is PATRONI trying create configmap always, instead of  update it.
may be error in https://github.com/zalando/patroni/blob/b282a0f254d69604f4e66218af10c1968eed9953/patroni/dcs/kubernetes.py#L325

**Comment by CyberDem0n** [comment]
In case if config map already exists Patroni does an update.
It seems something is wrong with your config or may be Patroni is not allowed to overwrite config maps.

Can you please share `kubernetes:` section of your patroni.yaml and output of `kubectl get cm xxxxxx-failover`?

**Comment by tigranav** [comment]
from patroni config:
```kubernetes:
  labels:
    pgcluster: common
  namespace: anne-test
  pod_ip: 10.130.0.191
  role_label: pgtype
  scope_label: pgcluster
```
from openshift:
```$ oc get cm common-failover
NAME              DATA      AGE
common-failover   0         3d
$ oc get cm common-failover -o json
{
    "apiVersion": "v1",
    "kind": "ConfigMap",
    "metadata": {
        "creationTimestamp": "2018-08-10T11:11:37Z",
        "labels": {
            "pgcluster": "common"
        },
        "name": "common-failover",
        "namespace": "anne-test",
        "resourceVersion": "52007420",
        "selfLink": "/api/v1/namespaces/anne-test/configmaps/common-failover",
        "uid": "25f9f70b-9c8e-11e8-b884-fa163e5f2c4f"
    }
}
$ oc describe cm/common-failover
Name:           common-failover
Namespace:      anne-test
Labels:         pgcluster=common
Annotations:    <none>

Data
====
```

**Comment by CyberDem0n** [comment]
Can it be that Patroni doesn't have permissions to update config maps?
In some cases (especially on open shift) you have to allow that explicitly: https://github.com/zalando/patroni/blob/master/kubernetes/patroni_k8s.yaml#L126-L186

**Comment by tigranav** [comment]
Patroni can update other configmaps.

**Comment by CyberDem0n** [comment]
`Switchover failed, details: 503, failed to write switchover key into DCS` - this log is from patronictl.
What is in Patroni logs?

**Comment by tigranav** [comment]
in pod logs:
```
2018-08-14 11:26:00,938 INFO: Got response from pg-common-node2-3-srfgk http://10.128.0.140:8008/patroni: {"database_system_identifier": "6588039132419055673", "postmaster_start_time": "2018-08-10 11:11:49.448 UTC", "timeline": 4, "xlog": {"received_location": 595893488, "replayed_timestamp": "2018-08-14 11:20:00.263 UTC", "paused": false, "replayed_location": 595893488}, "patroni": {"scope": "common", "version": "1.4.5"}, "state": "running", "role": "replica", "server_version": 90608}
  | 2018-08-14 11:26:01,039 ERROR: Unexpected error from Kubernetes API
  | Traceback (most recent call last):
  | File "/patroni/patroni/dcs/kubernetes.py", line 61, in wrapper
  | return func(*args, **kwargs)
  | File "/patroni/patroni/dcs/kubernetes.py", line 274, in patch_or_create
  | return self.retry(func, self._namespace, body) if retry else func(self._namespace, body)
  | File "/patroni/patroni/dcs/kubernetes.py", line 50, in wrapper
  | return getattr(self._api, func)(*args, **kwargs)
  | File "/usr/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 14673, in patch_namespaced_config_map
  | (data) = self.patch_namespaced_config_map_with_http_info(name, namespace, body, **kwargs)
  | File "/usr/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 14764, in patch_namespaced_config_map_with_http_info
  | collection_formats=collection_formats)
  | File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
  | _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  | File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
  | _request_timeout=_request_timeout)
  | File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 380, in request
  | body=body)
  | File "/usr/lib/python2.7/site-packages/kubernetes/client/rest.py", line 286, in PATCH
  | body=body)
  | File "/usr/lib/python2.7/site-packages/kubernetes/client/rest.py", line 222, in request
  | raise ApiException(http_resp=r)
  | ApiException: (500)
  | Reason: Internal Server Error
  | HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 14 Aug 2018 11:25:58 GMT', 'Content-Length': '143', 'Content-Type': 'application/json', 'Cache-Control': 'no-store'})
  | HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"[pos 110]: json: expect char '\"' but got char 'n'","code":500}
 ```

**Comment by CyberDem0n** [comment]
```python
  | File "/usr/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 14673, in patch_namespaced_config_map
  | File "/usr/lib/python2.7/site-packages/kubernetes/client/rest.py", line 286, in PATCH`

You see, Patroni knows that config map exists and calls "PATCH".

`"status":"Failure","message":"[pos 110]: json: expect char '\"' but got char 'n'"` -- this is the real problem.
What version of python kubernetes module do you use?

**Comment by tigranav** [comment]
kubernetes - 5.0.0

```
sh-4.2$ pip freeze |grep kubernetes
kubernetes==5.0.0
```

**Comment by CyberDem0n** [comment]
Please export `PATRONI_LOGLEVEL=DEBUG` before starting Patroni, it will help to figure out why PATCH request is broken (`"[pos 110]: json: expect char '\"' but got char 'n'"`)

**Comment by tigranav** [comment]
i added this variable, but i dont see requests, i see only responses

**Comment by anikin-aa** [comment]
facing the same problem, after changing 
```
annotations = {'leader': leader or None, 'member': candidate or None, 'scheduled_at': scheduled_at}
```
at
https://github.com/zalando/patroni/blob/master/patroni/dcs/kubernetes.py#L324

to 

```
annotations = {'leader': leader or '', 'member': candidate or '', 'scheduled_at': scheduled_at or ''}
```

problem disappeared, should I create PR for this changes ?

**Comment by anikin-aa** [comment]
this is a kubernetes issue. can't reproduce @ kubernetes 1.9. may be its better to raise the issue to kubernetes.
