### ISSUE TITLE
switchover show CERTIFICATE_VERIFY_FAILED stack trace

### ISSUE THREAD

**Issue by wilfriedroset** [zalando/patroni#785]
When performing a switchover patronictl fails due to self-sign SSL cert

```
# patronictl -c config.yml switchover
Master [patroni-99-node-1]:
Candidate ['patroni-99-backup-1', 'patroni-99-node-2'] []: patroni-99-node-2
When should the switchover take place (e.g. 2015-10-01T14:30)  [now]:
Current cluster topology
+-----------+---------------------+------------+--------+---------+-----------+
|  Cluster  |        Member       |    Host    |  Role  |  State  | Lag in MB |
+-----------+---------------------+------------+--------+---------+-----------+
| cluster99 | patroni-99-backup-1 | XXXX |        | running |           |
| cluster99 |  patroni-99-node-1  | XXXX | Leader | running |           |
| cluster99 |  patroni-99-node-2  | XXXX |        | running |           |
+-----------+---------------------+------------+--------+---------+-----------+
Are you sure you want to switchover cluster cluster99, demoting current master patroni-99-node-1? [y/N]: y
2018-08-20 15:59:57,292 - ERROR - None
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 837, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 323, in connect
    ssl_context=context)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 624, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/ctl.py", line 611, in _do_failover_or_switchover
    r = request_patroni(member, 'post', action, failover_value, auth_header(obj))
  File "/usr/lib/python3/dist-packages/patroni/ctl.py", line 141, in request_patroni
    data=json.dumps(content) if content else None, timeout=60)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)
2018-08-20 15:59:57,296 - WARNING - Failing over to DCS
2018-08-20 15:59:57.29682 Could not switchover using Patroni api, falling back to DCS
+-----------+---------------------+------------+--------+---------+-----------+
|  Cluster  |        Member       |    Host    |  Role  |  State  | Lag in MB |
+-----------+---------------------+------------+--------+---------+-----------+
| cluster99 | patroni-99-backup-1 | XXXX |        | running |           |
| cluster99 |  patroni-99-node-1  | XXXX | Leader | running |           |
| cluster99 |  patroni-99-node-2  | XXXX |        | running |           |
+-----------+---------------------+------------+--------+---------+-----------+
```

If we list our cluster's  nodes we can see that the switchover has been performed correctly.

```
# patronictl -c config.yml list
+-----------+---------------------+------------+--------+---------+-----------+
|  Cluster  |        Member       |    Host    |  Role  |  State  | Lag in MB |
+-----------+---------------------+------------+--------+---------+-----------+
| cluster99 | patroni-99-backup-1 | XXXX |        | running |           |
| cluster99 |  patroni-99-node-1  | XXXX |        | running |           |
| cluster99 |  patroni-99-node-2  | XXXX | Leader | running |           |
+-----------+---------------------+------------+--------+---------+-----------+
```

Seems like `request_patroni` in `ctl.py` should take some variable to the certificate of the rest API.
edit: patroni version 1.4.4 installed from pgdg  repository, debian strech

**Comment by CyberDem0n** [comment]
> Seems like request_patroni in ctl.py should take some variable to the certificate of the rest API.

Or use `verify=False` when doing REST API calls.

I think it should be configurable.

Pull requests are welcome.
