### ISSUE TITLE
edit config 

### ISSUE THREAD

**Issue by billikill** [zalando/patroni#816]
I'm using version 1.4.4
I configured DSC and restarted a service. But the service starts with default settings. In the file "postgresql.conf" the settings didn't change.
Could you explain me why the changes are not applied.Thanks in advance.

i am stupid, i am restart patroni "service patroni restart"

but restart from "patronictl -c /etc/patroni/patroni.yml restart jira", get error

`When should the restart take place (e.g. 2015-10-01T14:30)  [now]: now
Traceback (most recent call last):
  File "/usr/bin/patronictl", line 11, in <module>
    load_entry_point('patroni==1.4.4', 'console_scripts', 'patronictl')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/patroni/ctl.py", line 505, in restart
    r = request_patroni(member, 'post', 'restart', content, auth_header(obj))
  File "/usr/lib/python2.7/site-packages/patroni/ctl.py", line 141, in request_patroni
    data=json.dumps(content) if content else None, timeout=60)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))`

**Comment by CyberDem0n** [comment]
What parameters?
How did you changed them?
What is in the config?
Was the config changed for already existing cluster?

**Comment by billikill** [comment]
Hi, i am nor restart node in cluster. Get error 503
Are you sure you want to restart members node2.jira.dev? [y/N]: y
Restart if the PostgreSQL version is less than provided (e.g. 9.5.2)  []: 9.5.2
When should the restart take place (e.g. 2015-10-01T14:30)  [now]: now
Failed: restart for member node2.jira.dev, status code=503, (restart conditions are not satisfied)

**Comment by CyberDem0n** [comment]
Restart if the PostgreSQL version is less than provided (e.g. 9.5.2) []: **9.5.2** <= Why?????

**Comment by billikill** [comment]
PostgreSQL - version 9.6
When i am, write 9.6   get error
Are you sure you want to restart members node2.jira.dev? [y/N]: y
Restart if the PostgreSQL version is less than provided (e.g. 9.5.2)  []: 9.6
Error: Invalid PostgreSQL version format: X.Y or X.Y.Z is accepted: 9.6

**Comment by CyberDem0n** [comment]
Just leave it empty!

**Comment by billikill** [comment]
i am change config patroni "edit-config", reboot node in cluster, but patroni used default config. Why ?
example:
/usr/pgsql-9.6/bin/postgres -D /etc/patroni/data --config-file=/etc/patroni/data/postgresql.conf --listen_addresses=0.0.0.0 --max_worker_processes=8

but config patroni:
loop_wait: 10
maximum_lag_on_failover: 1024
postgresql:
  parametrs:
    autovacuum: true
    autovacuum_analyze_scale_factor: 0.05
    autovacuum_max_workers: 5
    autovacuum_naptime: 1s
    autovacuum_vacuum_scale_factor: 0.01
    checkpoint_completion_target: 0.9
    default_statistics_target: 100
    effective_cache_size: 5GB
    effective_io_concurrency: 2
    maintenance_work_mem: 1280MB
    max_connections: 200
    max_parallel_workers: 6
    max_parallel_workers_per_gather: 3
    max_wal_size: 1GB
    max_worker_processes: 6
    min_wal_size: 100MB
    random_page_cost: 4
    shared_buffers: 1280MB
    use_pg_rewind: true
    wal_buffers: 16MB
    work_mem: 1820kB
retry_timeout: 10
ttl: 30

why patroni used "max_worker_processes: 8" ??

**Comment by billikill** [comment]
> Just leave it empty!
 thanks, i am stupids )))

**Comment by CyberDem0n** [comment]
max_worker_processes is one of a few parameters which value on the replica must be not smaller than on the master, therefore Patroni is trying to make sure that its value is synchronized across all the nodes. Change of this value requires restart of postgres. In order to minimize damage from restarts and have something like anti-foot gun, we decided that the value of max_worker_processes can be set smaller then the default value 8.

Any attempt to make it smaller are just ignored. The same applies to max_wal_senders, max_replication_slots and so on. You can find more details here: https://github.com/zalando/patroni/blob/master/patroni/postgresql.py#L98-L106

**Comment by billikill** [comment]
hello.
I am create config and reboot member in cluster.
max_connections = 500
 patronictl -c /etc/patroni/patroni.yml show-config jira
loop_wait: 10
maximum_lag_on_failover: 1024
postgresql:
  max_connections: 500
  parametrs:
    checkpoint_completion_target: 0.7
    default_statistics_target: 100
    effective_cache_size: 6GB
    effective_io_concurrency: 2
    maintenance_work_mem: 512MB
    max_parallel_workers_per_gather: 2
    max_wal_size: 2GB
    max_worker_processes: 4
    min_wal_size: 1GB
    random_page_cost: 4
    shared_buffers: 2GB
    wal_buffers: 16MB
    work_mem: 5242kB
retry_timeout: 10
ttl: 30

but, app for start 
018-10-10 11:59:07 +0300 INFO: ------------------------------------------------------------
2018-10-10 11:59:07 +0300 INFO: eazyBI add-on version   : 4.5.4
2018-10-10 11:59:07 +0300 INFO: Jira version            : 7.12.1
2018-10-10 11:59:07 +0300 INFO: OS version              : Linux 3.10.0-862.11.6.el7.x86_64 amd64
2018-10-10 11:59:07 +0300 INFO: Database adapter        : postgresql
2018-10-10 11:59:07 +0300 INFO: Java VM name            : Java HotSpot(TM) 64-Bit Server VM
2018-10-10 11:59:07 +0300 INFO: Java version            : 1.8.0_181
2018-10-10 11:59:07 +0300 INFO: Java file.encoding      : UTF-8
2018-10-10 11:59:07 +0300 INFO: JVM max heap memory     : 4551 MB
2018-10-10 11:59:07 +0300 INFO: ------------------------------------------------------------
2018-10-10 11:59:08 +0300 INFO: Database version        : PostgreSQL 9.6.9
2018-10-10 11:59:08 +0300 INFO: shared_buffers          : 1GB
2018-10-10 11:59:08 +0300 INFO: wal_buffers             : 16MB
2018-10-10 11:59:08 +0300 INFO: max_connections         : 100

Why app max_connections: 100 ??

manual app
https://docs.eazybi.com/eazybijira/set-up-and-administer/set-up-and-administer-for-jira-server/installation-and-setup
If you have a large number of Jira issues then for faster eazyBI Jira data import it is recommended to tune PostgreSQL memory settings. The following postgresql.conf settings are recommended:

shared_buffers = 512MB
wal_buffers = 16MB
max_connections = 200

**Comment by CyberDem0n** [comment]
You have a typo: `parametrs:`, it should be `parameters:`
