### ISSUE TITLE
[Question] ERROR: Can not fetch local timeline and lsn from replication connectio

### ISSUE THREAD

**Issue by rutmir** [zalando/patroni#817]
Hello, i have issue in GKE kubernetes cluster (version of nodes 1.10.6-gke.1)
When i drop pod with master db, replica pod not become master, i see in log set of errors unlit kubernetes run new pod instead deleted. 
here list of errors from logs:

- 2018-10-01 14:11:25,780 ERROR: Can not fetch local timeline and lsn from replication connection

- Traceback (most recent call last): File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql.py", line 1256, in _get_local_timeline_lsn_from_replication_connection with self._get_replication_connection_cursor(**self._local_replication_address) as cur: File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__ return next(self.gen) File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql.py", line 1240, in _get_replication_connection_cursor connect_timeout=3, options='-c statement_timeout=2000') as cur: File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__ return next(self.gen) File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql.py", line 1231, in _get_connection_cursor with psycopg2.connect(**kwargs) as conn: File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 130, in connect conn = _connect(dsn, connection_factory=connection_factory, **kwasync) psycopg2.OperationalError: could not connect to server: Connection refused
Is the server running on host "localhost" (::1) and accepting TCP/IP connections on port 5432?

- FATAL:  password authentication failed for user "standby"

- FATAL:  no pg_hba.conf entry for replication connection from host "127.0.0.1", user "standby", SSL off

- 2018-10-01 14:11:25,780 INFO: no action.  i am a secondary and i am following a leader

on previous version for kubernetes 1.9 all works find.
should l use specific version of patroni image? or may be exists other way to fix this?

**Comment by CyberDem0n** [comment]
> FATAL: password authentication failed for user "standby"

Apparently replication password is wrong. Either somebody recreated `Secret` objects or may be changed the password in the cluster.
This error is actually a sign of a bigger problem, replica pods are not able to replicate from the master!

**Comment by rutmir** [comment]
@CyberDem0n thanks for the tip.
I updated the passwords for "standby" and "postgres" from k8s secret, original error went away, but others appeared. On replica pod data base not restored from backup.
here logs from k8s (this logs in loop each 10 seconds):
```
2018-10-07 18:14:35,310 INFO: Lock owner: db-0; I am db-1
2018-10-07 18:14:35,310 INFO: Still starting up as a standby.
2018-10-07 18:14:35,311 INFO: Lock owner: db-0; I am db-1
2018-10-07 18:14:35,311 INFO: does not have lock
2018-10-07 18:14:35,312 INFO: establishing a new patroni connection to the postgres cluster
2018-10-07 18:14:35,696 INFO: establishing a new patroni connection to the postgres cluster
2018-10-07 18:14:35,699 INFO: Error communicating with PostgreSQL. Will try again later
/var/run/postgresql:5432 - rejecting connections
```

here logs from pg-logs (.csv):
```
2018-10-07 18:11:46.373 UTC,,,1365,"[local]",5bba4c62.555,1,"",2018-10-07 18:11:46 UTC,,0,LOG,00000,"connection received: host=[local]",,,,,,,,,""
2018-10-07 18:11:46.374 UTC,"postgres","postgres",1365,"[local]",5bba4c62.555,2,"",2018-10-07 18:11:46 UTC,,0,FATAL,57P03,"the database system is starting up",,,,,,,,,""
2018-10-07 18:11:46.522 UTC,,,1371,"[local]",5bba4c62.55b,1,"",2018-10-07 18:11:46 UTC,,0,LOG,00000,"connection received: host=[local]",,,,,,,,,""
2018-10-07 18:11:46.522 UTC,"postgres","postgres",1371,"[local]",5bba4c62.55b,2,"",2018-10-07 18:11:46 UTC,,0,FATAL,57P03,"the database system is starting up",,,,,,,,,""
2018-10-07 18:11:46.531 UTC,,,1372,"[local]",5bba4c62.55c,1,"",2018-10-07 18:11:46 UTC,,0,LOG,00000,"connection received: host=[local]",,,,,,,,,""
2018-10-07 18:11:46.531 UTC,"postgres","postgres",1372,"[local]",5bba4c62.55c,2,"",2018-10-07 18:11:46 UTC,,0,FATAL,57P03,"the database system is starting up",,,,,,,,,""
2018-10-07 18:11:47.194 UTC,,,1373,"[local]",5bba4c63.55d,1,"",2018-10-07 18:11:47 UTC,,0,LOG,00000,"connection received: host=[local]",,,,,,,,,""
2018-10-07 18:11:47.194 UTC,"postgres","postgres",1373,"[local]",5bba4c63.55d,2,"",2018-10-07 18:11:47 UTC,,0,FATAL,57P03,"the database system is starting up",,,,,,,,,""
2018-10-07 18:11:48.724 UTC,,,1381,"[local]",5bba4c64.565,1,"",2018-10-07 18:11:48 UTC,,0,LOG,00000,"connection received: host=[local]",,,,,,,,,""
2018-10-07 18:11:48.724 UTC,"postgres","postgres",1381,"[local]",5bba4c64.565,2,"",2018-10-07 18:11:48 UTC,,0,FATAL,57P03,"the database system is starting up",,,,,,,,,""
2018-10-07 18:11:50.966 UTC,,,1383,,5bba4c66.567,1,,2018-10-07 18:11:50 UTC,,0,LOG,00000,"started streaming WAL from primary at 10/C000000 on timeline 10",,,,,,,,,""
2018-10-07 18:11:50.966 UTC,,,1383,,5bba4c66.567,2,,2018-10-07 18:11:50 UTC,,0,FATAL,XX000,"could not receive data from WAL stream: ERROR:  requested WAL segment 0000000A000000100000000C has already been removed

```

**Comment by mathisve** [comment]
I was playing around with patroni, installing and uninstalling it and had this issue all of a sudden.
Updating the secret and rebooting the pods didn't help.
Was able to resolve the issue by going into the master and doing `ALTER USER standby WITH PASSWORD 'password-here'`. Not sure if this is a good way to do it, but it fixed all issues for me.

**Comment by peedrr** [comment]
> Was able to resolve the issue by going into the master and doing ALTER USER standby WITH PASSWORD 'password-here';.

I just had this same issue on [a TimescaleDB installation](https://github.com/timescale/timescaledb-kubernetes) (also uses Patroni). Your solution is very odd, and very annoying, as it has no logic, but it definitely worked for me too! Thanks @mathisve !
