### ISSUE TITLE
ImportError: No module named 'requests.packages.urllib3'

### ISSUE THREAD

**Issue by Demuzx** [zalando/patroni#818]
I starting patroni, and get an issue:
Traceback (most recent call last):
  File "/usr/bin/patroni", line 11, in <module>
    load_entry_point('patroni==1.5.0', 'console_scripts', 'patroni')()
  File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 182, in main
    return patroni_main()
  File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 147, in patroni_main
    patroni = Patroni()
  File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 13, in __init__
    from patroni.api import RestApiServer
  File "/usr/lib/python2.7/site-packages/patroni/api.py", line 10, in <module>
    from patroni.postgresql import PostgresConnectionException, PostgresException, Postgresql
  File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 19, in <module>
    from requests.structures import CaseInsensitiveDict
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 32, in <module>
    from .exceptions import InvalidURL
  File "/usr/lib/python2.7/site-packages/requests/exceptions.py", line 10, in <module>
    from .packages.urllib3.exceptions import HTTPError as BaseHTTPError
  File "/usr/lib/python2.7/site-packages/requests/packages/__init__.py", line 95, in load_module
    raise ImportError("No module named '%s'" % (name,))
ImportError: No module named 'requests.packages.urllib3'

All dependencies was installed, but there is an error - ImportError: No module named 'requests.packages.urllib3'. Centos 7.

**Comment by CyberDem0n** [comment]
What versions of `requests` and `urllib3` are installed? And how they were installed?

**Comment by Demuzx** [comment]
> What versions of `requests` and `urllib3` are installed? And how they were installed?
requests (2.19.1)
urllib3 (1.23)

I've installed them by pip install -r requirements.txt, but full installation was interrupted and stopped with error: 
Installing collected packages: ipaddress, websocket-client, oauthlib, requests-oauthlib, enum34, pycparser, cffi, asn1crypto, cryptography, PyJWT, adal, pyasn1, pyasn1-modules, cachetools, rsa, google-auth, kubernetes
  Found existing installation: ipaddress 1.0.16
Cannot uninstall 'ipaddress'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by JanisSharma** [comment]
To install requests module on Debian/Ubuntu for Python2:

$ sudo apt-get install python-requests

And for Python3 the command is:

$ sudo apt-get install python3-requests

Full Source At [Here](https://icetutor.com/question/importerror-no-module-named-requests/)
