### ISSUE TITLE
supress error output on master check

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#84]
Doing a failover test, I got this output from the replica:

2015-10-28 11:49:41,781 ERROR: request failed: GET http://127.0.0.1:8008/patroni
Traceback (most recent call last):
  File "/home/josh/patroni/patroni/ha.py", line 147, in fetch_node_status
    response = requests.get(member.api_url, timeout=2, verify=False)
  File "/home/josh/patronienv/local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/home/josh/patronienv/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/josh/patronienv/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/josh/patronienv/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/josh/patronienv/local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8008): Max retries exceeded with url: /patroni (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7ff78ea0efd0>: Failed to establish a new connection: [Errno 111] Connection refused',))

What's happening there is that the replica is failing to connect to the master because it's down.  Which is as it should be; so why are we getting an error with a trace dump?

**Comment by jberkus** [comment]
Note that after that error, failover succeeds.  So it's just unneeded output.

**Comment by feikesteenbergen** [comment]
We should probably suppress this stacktrace and make an INFO line out of it.

**Comment by LappleApple** [comment]
@feikesteenbergen Did you implement the change referenced in your previous comment?

**Comment by CyberDem0n** [comment]
No, it still produces ERROR message with the stack trace.

**Comment by LappleApple** [comment]
@CyberDem0n Should I label as "bug" and/or "help wanted"?

**Comment by CyberDem0n** [comment]
This is not really a bug, just a small "feature" which is really easy to solve. So "help wanted" would be ok.

**Comment by CyberDem0n** [comment]
Solved by https://github.com/zalando/patroni/pull/256
