### ISSUE TITLE
 OSError: [Errno 2] No such file or directory  (data = subprocess.check_output([self._pgcommand('pg_controldata'), self._data_dir], env=env))

### ISSUE THREAD

**Issue by tomkcpr** [zalando/patroni#840]
Hey Guy's,

Would this qualify as an issue with Patroni 3.2 and PostgreSQL 10?  

```
   1220     def controldata(self):
   1221         """ return the contents of pg_controldata, or non-True value if pg_controldata call failed """
   1222         result = {}
   1223         # Don't try to call pg_controldata during backup restore
   1224         if self._version_file_exists() and self.state != 'creating replica':
   1225             try:
   1226                 env = {'LANG': 'C', 'LC_ALL': 'C', 'PATH': os.getenv('PATH')}
   1227                 if os.getenv('SYSTEMROOT') is not None:
   1228                     env['SYSTEMROOT'] = os.getenv('SYSTEMROOT')
   1229                 data = subprocess.check_output([self._pgcommand('pg_controldata'), self._data_dir], env=env)
   1230                 if data:
   1231                     data = data.decode('utf-8').splitlines()
   1232                     # pg_controldata output depends on major verion. Some of parameters are prefixed by 'Current '
   1233                     result = {l.split(':')[0].replace('Current ', '', 1): l.split(':', 1)[1].strip() for l in data
   1234                               if l and ':' in l}
   1235             except subprocess.CalledProcessError:
   1236                 logger.exception("Error when calling pg_controldata")
   1237         return result
   1238

```

```

[root@psql01 etcd]#
[root@psql01 etcd]# journalctl -xe
--
-- Unit patroni.service has begun starting up.
Oct 29 01:20:06 psql01.nix.mds.xyz polkitd[678]: Unregistered Authentication Agent for unix-process:31878:12146769 (system bus name :1.178, object path /org/freedesktop/PolicyKit1/Au
Oct 29 01:20:06 psql01.nix.mds.xyz Keepalived_vrrp[1248]: /usr/bin/killall -0 haproxy exited with status 1
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: 2018-10-29 01:20:07,138 INFO: Failed to import patroni.dcs.consul
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: 2018-10-29 01:20:07,167 INFO: Selected new etcd server http://192.168.0.108:2379
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: 2018-10-29 01:20:07,683 INFO: Lock owner: None; I am postgresql0
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: Traceback (most recent call last):
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: File "/bin/patroni", line 11, in <module>
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: load_entry_point('patroni==1.5.0', 'console_scripts', 'patroni')()
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 182, in main
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: return patroni_main()
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 149, in patroni_main
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: patroni.run()
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 114, in run
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: logger.info(self.ha.run_cycle())
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 1236, in run_cycle
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: info = self._run_cycle()
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 1177, in _run_cycle
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: data_sysid = self.state_handler.sysid
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 423, in sysid
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: data = self.controldata()
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 1229, in controldata
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: data = subprocess.check_output([self._pgcommand('pg_controldata'), self._data_dir], env=env)
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: File "/usr/lib64/python2.7/subprocess.py", line 568, in check_output
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: process = Popen(stdout=PIPE, *popenargs, **kwargs)
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: errread, errwrite)
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: raise child_exception
Oct 29 01:20:07 psql01.nix.mds.xyz patroni[31884]: OSError: [Errno 2] No such file or directory
Oct 29 01:20:07 psql01.nix.mds.xyz systemd[1]: patroni.service: main process exited, code=exited, status=1/FAILURE
Oct 29 01:20:07 psql01.nix.mds.xyz systemd[1]: Unit patroni.service entered failed state.
Oct 29 01:20:07 psql01.nix.mds.xyz systemd[1]: patroni.service failed.
Oct 29 01:20:08 psql01.nix.mds.xyz Keepalived_vrrp[1248]: /usr/bin/killall -0 haproxy exited with status 1
Oct 29 01:20:10 psql01.nix.mds.xyz Keepalived_vrrp[1248]: /usr/bin/killall -0 haproxy exited with status 1
Oct 29 01:20:12 psql01.nix.mds.xyz Keepalived_vrrp[1248]: /usr/bin/killall -0 haproxy exited with status 1
Oct 29 01:20:14 psql01.nix.mds.xyz Keepalived_vrrp[1248]: /usr/bin/killall -0 haproxy exited with status 1
Oct 29 01:20:16 psql01.nix.mds.xyz Keepalived_vrrp[1248]: /usr/bin/killall -0 haproxy exited with status 1
Oct 29 01:20:18 psql01.nix.mds.xyz Keepalived_vrrp[1248]: /usr/bin/killall -0 haproxy exited with status 1
Oct 29 01:20:20 psql01.nix.mds.xyz Keepalived_vrrp[1248]: /usr/bin/killall -0 haproxy exited with status 1
[root@psql01 etcd]#
```

```
[root@psql01 etcd]# cat /etc/systemd/system/patroni.service
[Unit]
Description=Runners to orchestrate a high-availability PostgreSQL
After=syslog.target network.target

[Service]
Type=simple

User=postgres
Group=postgres

ExecStart=/bin/patroni /etc/patroni.yml

KillMode=process

TimeoutSec=30

Restart=no

[Install]
WantedBy=multi-user.targ

[root@psql01 etcd]#
```

Despite that PGDATA is defined fine in .bash_profile:

```
-bash-4.2$ cat .bash_profile
[ -f /etc/profile ] && source /etc/profile
PGDATA=/data/patroni
export PGDATA
# If you want to customize your settings,
# Use the file below. This is not overridden
# by the RPMS.
[ -f /var/lib/pgsql/.pgsql_profile ] && source /var/lib/pgsql/.pgsql_profile
-bash-4.2$ logout
[root@psql01 etcd]#
```

Or is there a recommended approach that I might be missing?

Cheers,
TK

**Comment by tomkcpr** [comment]
pg_controldata works fine from within the postgres account once I su to it.

**Comment by CyberDem0n** [comment]
I am 100% sure Patroni can't find postgres binaries in the default PATH:
https://github.com/zalando/patroni/issues/569
https://github.com/zalando/patroni/issues/714
https://github.com/zalando/patroni/issues/497
and so on
