### ISSUE TITLE
ValueError on running patroni on CentOS

### ISSUE THREAD

**Issue by gauravojha** [zalando/patroni#847]
I am getting the following error on trying to run patroni on CentOS 7. Trying to run it as 'postgres' user

Using release 1.5.1

```
bash-4.2$ patroni /etc/patroni/postgres0.yml 
Traceback (most recent call last):
  File "/usr/bin/patroni", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 631, in resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2489, in requires
    dm = self._dep_map
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2483, in _dep_map
    dm.setdefault(extra,[]).extend(parse_requirements(reqs))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2839, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2817, in scan_list
    "Expected ',' or end-of-list in",line,"at",line[p:]
ValueError: ("Expected ',' or end-of-list in", 'kubernetes!=4.0.*,!=5.0.*,<=7.0.0,>=2.0.0', 'at', '*,!=5.0.*,<=7.0.0,>=2.0.0')
```

Other details:
```
Python 2.7.5 (default, Jul 13 2018, 13:06:57) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux2


pip --version
pip 18.1 from /usr/lib/python2.7/site-packages/pip (python 2.7)
```

**Comment by CyberDem0n** [comment]
Please upgrade `setuptools`

**Comment by gauravojha** [comment]
Found the problem. I had installed all of these as a different user, and had skipped installing them for the "postgres" user which I was using to run the cluster.
