### ISSUE TITLE
initialization fails if superuser.name=postgres

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#86]
With HEAD as of a couple days ago, if you set the following:

  superuser:
    username: postgres
    password: zalando

For a new database system, you will get this error on initialization:

```
2015-10-29 19:40:06,302 INFO: established a new patroni connection to the postgres cluster
ERROR:  role "postgres" already exists
STATEMENT:  CREATE ROLE "postgres" WITH LOGIN SUPERUSER PASSWORD 'super'
2015-10-29 19:40:06,316 INFO: removing initialize key after failed attempt to initialize the cluster
2015-10-29 19:40:06,317 INFO: closed patroni connection to the postgresql cluster
waiting for server to shut down...LOG:  received immediate shutdown request
.WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
 done
server stopped
2015-10-29 19:40:07,349 INFO: renaming data directory to /pgdata/data_2015-10-29-19-40-07
2015-10-29 19:40:07,350 ERROR: Error communicating with Postgresql. Will try again later
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/patroni/ha.py", line 380, in _run_cycle
    return self.bootstrap()  # new node
  File "build/bdist.linux-x86_64/egg/patroni/ha.py", line 79, in bootstrap
    self.state_handler.bootstrap()
  File "build/bdist.linux-x86_64/egg/patroni/postgresql.py", line 647, in bootstrap
    self.create_connection_users()
  File "build/bdist.linux-x86_64/egg/patroni/postgresql.py", line 588, in create_connection_users
    self.superuser['username']), self.superuser['password'])
  File "build/bdist.linux-x86_64/egg/patroni/postgresql.py", line 160, in query
    return self.retry(self._query, sql, *params)
  File "build/bdist.linux-x86_64/egg/patroni/utils.py", line 153, in __call__
    return func(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/patroni/postgresql.py", line 153, in _query
    raise e
ProgrammingError: role "postgres" already exists
```

Then initialization will fail ... and be reattempted, in a continuous loop.

For all of the roles, we should check if they already exist, and only create them if they don't (but set passwords if they do).

Will work on patch this week.

**Comment by feikesteenbergen** [comment]
Fixed by PR #94
