### ISSUE TITLE
Patroni throwing exception when attempting to connect to zookeeper.

### ISSUE THREAD

**Issue by NewOne121** [zalando/patroni#873]
I've installed and configured new patroni container, but patroni is failing to start.
It throwing this exception:
```
2018-11-19 16:25:15,826 INFO: Failed to import patroni.dcs.consul
2018-11-19 16:25:15,827 INFO: Failed to import patroni.dcs.etcd
2018-11-19 16:25:15,867 INFO: Failed to import patroni.dcs.kubernetes
2018-11-19 16:25:15,871 INFO: Connecting to 192.168.56.11:12181, use_ssl: False
2018-11-19 16:25:15,871 ERROR: Unhandled exception in connection loop
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/kazoo/protocol/connection.py", line 577, in _connect_attempt
    read_timeout, connect_timeout = self._connect(host, port)
  File "/usr/local/lib/python2.7/dist-packages/patroni/dcs/zookeeper.py", line 81, in _kazoo_connect
    ret = self._orig_kazoo_connect(host, port)
  File "/usr/local/lib/python2.7/dist-packages/kazoo/protocol/connection.py", line 653, in _connect
    verify_certs=self.client.verify_certs,
  File "/usr/local/lib/python2.7/dist-packages/patroni/dcs/zookeeper.py", line 43, in create_connection
    args[1] = max(self._connect_timeout, args[1]/10.0)
IndexError: list index out of range
2018-11-19 16:25:15,872 INFO: Zookeeper session lost, state: CLOSED
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kazoo/protocol/connection.py", line 510, in zk_loop
    if retry(self._connect_loop, retry) is STOP_CONNECTING:
  File "/usr/local/lib/python2.7/dist-packages/kazoo/retry.py", line 120, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kazoo/protocol/connection.py", line 549, in _connect_loop
    status = self._connect_attempt(host, port, retry)
  File "/usr/local/lib/python2.7/dist-packages/kazoo/protocol/connection.py", line 577, in _connect_attempt
    read_timeout, connect_timeout = self._connect(host, port)
  File "/usr/local/lib/python2.7/dist-packages/patroni/dcs/zookeeper.py", line 81, in _kazoo_connect
    ret = self._orig_kazoo_connect(host, port)
  File "/usr/local/lib/python2.7/dist-packages/kazoo/protocol/connection.py", line 653, in _connect
    verify_certs=self.client.verify_certs,
  File "/usr/local/lib/python2.7/dist-packages/patroni/dcs/zookeeper.py", line 43, in create_connection
    args[1] = max(self._connect_timeout, args[1]/10.0)
IndexError: list index out of range

^CTraceback (most recent call last):
  File "/usr/local/bin/patroni", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/patroni/__init__.py", line 182, in main
    return patroni_main()
  File "/usr/local/lib/python2.7/dist-packages/patroni/__init__.py", line 147, in patroni_main
    patroni = Patroni()
  File "/usr/local/lib/python2.7/dist-packages/patroni/__init__.py", line 25, in __init__
    self.dcs = get_dcs(self.config)
  File "/usr/local/lib/python2.7/dist-packages/patroni/dcs/__init__.py", line 89, in get_dcs
    return item(config[name])
  File "/usr/local/lib/python2.7/dist-packages/patroni/dcs/zookeeper.py", line 67, in __init__
    self._client.start()
  File "/usr/local/lib/python2.7/dist-packages/kazoo/client.py", line 578, in start
    event.wait(timeout=timeout)
  File "/usr/lib/python2.7/threading.py", line 614, in wait
    self.__cond.wait(timeout)
  File "/usr/lib/python2.7/threading.py", line 359, in wait
    _sleep(delay)
```

It seems like patroni can't connect to zookeeper server, but actually connection can be established, for examle via nc.
```
root@e598dcbbf530:/# echo "ruok" | nc 192.168.56.11 12181;echo
imok
```
Patroni was installed via pip in docker container.
```
root@e598dcbbf530:/# pip list --format=columns| grep patroni
patroni         1.5.1
```
Patroni configuration: (postgresql configuration skipped)
```
namespace: /patroni
scope: testing-zone
name: psql-node01

restapi:
  listen: 0.0.0.0:8008
  connect_address: 192.168.56.10:8008
  authentication:
    username: apiuser
    password: QzwMNiNVJT6goyS

zookeeper:
  hosts: ['192.168.56.11:12181']

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1073741824
    synchronous_mode: false

watchdog:
  mode: off

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

If i understand correct it fails because of this error:
```
IndexError: list index out of range
```

I have another cluster with similar configuration and it works just fine. Both have patroni version 1.5.1.
I've recognized difference between startup messages. On cluster where patroni works fine it seems like:
```
2018-11-19 08:11:47,009 INFO: Failed to import patroni.dcs.consul
2018-11-19 08:11:47,010 INFO: Failed to import patroni.dcs.etcd
2018-11-19 08:11:47,051 INFO: Failed to import patroni.dcs.kubernetes
2018-11-19 08:11:47,056 INFO: Connecting to 192.168.56.11:12181
2018-11-19 08:11:47,063 INFO: Zookeeper connection established, state: CONNECTED
2018-11-19 08:11:47,077 INFO: Lock owner: None; I am psql-node02
```
comparing to:
```
2018-11-19 16:39:02,432 INFO: Failed to import patroni.dcs.consul
2018-11-19 16:39:02,433 INFO: Failed to import patroni.dcs.etcd
2018-11-19 16:39:02,473 INFO: Failed to import patroni.dcs.kubernetes
2018-11-19 16:39:02,477 INFO: Connecting to 192.168.56.11:12181, use_ssl: False
2018-11-19 16:39:02,477 ERROR: Unhandled exception in connection loop
IndexError: list index out of range
2018-11-19 16:39:02,478 INFO: Zookeeper session lost, state: CLOSED
```
Any suggestions?

**Comment by CyberDem0n** [comment]
I pushed the fix today: https://github.com/zalando/patroni/pull/872
Unfortunately don't have time to prepare the new release.

**Comment by NewOne121** [comment]
Thanks a lot!
I've used kazoo==2.5.0 as a temporary solution.
