### ISSUE TITLE
Patroni fails if local consul agent restarted

### ISSUE THREAD

**Issue by shamil** [zalando/patroni#879]
I guess it's somehow related/similar to #853 
The problem I see is when I restart local consul agent on the patroni node, the Postgres cluster  becomes unavailable during that period, and sometimes even a failover occurs. 

Is it possible to have some grace before doing hard fail and let consul connection to recover?

Here are the relevant logs which printed during local consul agent restart

```log
2018-11-26 12:02:43,301 ERROR: touch_member
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/consul.py", line 356, in touch_member
    self._client.kv.put(self.member_path, json.dumps(data, separators=(',', ':')), **args)
  File "/usr/local/lib/python3.5/dist-packages/consul/base.py", line 621, in put
    CB.json(), '/v1/kv/%s' % key, params=params, data=value)
  File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/consul.py", line 105, in wrapper
    return callback(self.response(self.http.request(method.upper(), self.uri(path, params), **kwargs)))
  File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/consul.py", line 76, in response
    raise ConsulInternalError(msg)
patroni.dcs.consul.ConsulInternalError: 500 rpc error making call: rpc error making call: invalid session "8b081cb9-31c7-0748-f816-99c4bdcb1391"
2018-11-26 12:02:52,109 INFO: Could not take out TTL lock
2018-11-26 12:02:52,166 INFO: Deregister service postgres-main/postgres2
2018-11-26 12:02:52,180 INFO: demoted self after trying and failing to obtain lock
2018-11-26 12:02:52,181 INFO: closed patroni connection to the postgresql cluster
2018-11-26 12:02:52,230 INFO: postmaster pid=9496
localhost:5432 - rejecting connections
localhost:5432 - rejecting connections
2018-11-26 12:02:53,291 INFO: Lock owner: None; I am postgres2
2018-11-26 12:02:53,291 INFO: not healthy enough for leader race
2018-11-26 12:02:53,299 INFO: starting after demotion in progress
localhost:5432 - accepting connections
2018-11-26 12:02:53,338 INFO: establishing a new patroni connection to the postgres cluster
2018-11-26 12:02:53,360 INFO: Got response from postgres1 http://10.0.0.11:8008/patroni: b'{"state": "running", "pending_restart": true, "patroni": {"scope": "postgres-main", "version": "1.5.2"}, "cluster_unlocked": true, "xlog": {"replayed_location": 52429539088, "paused": false, "received_location": 52429539088, "replayed_timestamp": null}, "role": "replica", "database_system_identifier": "6596624351783773772", "timeline": 37, "tags": {"nosync": true}, "server_version": 100005, "postmaster_start_time": "2018-11-26 12:02:35.119 UTC"}'
2018-11-26 12:02:53,474 INFO: Register service postgres-main, params {'service_id': 'postgres-main/postgres2', 'check': {'http': 'http://10.0.0.12:8008/replica', 'DeregisterCriticalServiceAfter': 150.0, 'interval': '5s'}, 'tags': ['replica'], 'port': 5432, 'address': '10.0.0.12'}
2018-11-26 12:02:53,492 INFO: promoted self to leader by acquiring session lock
server promoting
2018-11-26 12:02:53,496 INFO: cleared rewind state after becoming the leader
2018-11-26 12:02:54,509 INFO: Lock owner: postgres2; I am postgres2
2018-11-26 12:02:54,539 INFO: Register service postgres-main, params {'service_id': 'postgres-main/postgres2', 'check': {'http': 'http://10.0.0.12:8008/master', 'DeregisterCriticalServiceAfter': 150.0, 'interval': '5s'}, 'tags': ['master'], 'port': 5432, 'address': '10.0.0.12'}
2018-11-26 12:02:54,555 INFO: no action.  i am the leader with the lock
```

**Comment by CyberDem0n** [comment]
Alright. Could you at least provide a little bit more logs before this line:
`2018-11-26 12:02:43,301 ERROR: touch_member`

**Comment by CyberDem0n** [comment]
And it would be better if you run it with `PATRONI_LOGLEVEL=DEBUG`

**Comment by shamil** [comment]
@CyberDem0n here are more logs with debug enabled:

```
2018-11-26 12:42:16,606 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:16,609 DEBUG: http://localhost:8500 "GET /v1/kv/patroni/postgres-main/?recurse=1 HTTP/1.1" 200 None
2018-11-26 12:42:16,610 INFO: Lock owner: postgres1; I am postgres1
2018-11-26 12:42:16,611 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:16,613 DEBUG: http://localhost:8500 "PUT /v1/session/renew/16492f43-c2d6-5307-432f-e32d6f7bcbd0 HTTP/1.1" 200 269
2018-11-26 12:42:16,613 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:16,621 DEBUG: http://localhost:8500 "PUT /v1/kv/patroni/postgres-main/optime/leader HTTP/1.1" 200 4
2018-11-26 12:42:16,621 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:16,629 DEBUG: http://localhost:8500 "PUT /v1/kv/patroni/postgres-main/members/postgres1?acquire=16492f43-c2d6-5307-432f-e32d6f7bcbd0 HTTP/1.1" 200 4
2018-11-26 12:42:16,630 INFO: no action.  i am the leader with the lock
2018-11-26 12:42:17,423 DEBUG: API thread: 10.0.0.11 - - [26/Nov/2018 12:42:17] "GET /master HTTP/1.1" 200 -
2018-11-26 12:42:18,330 DEBUG: API thread: 10.0.0.12 - - [26/Nov/2018 12:42:18] "GET /patroni HTTP/1.1" 200 -
2018-11-26 12:42:18,731 DEBUG: API thread: 10.0.0.12 - - [26/Nov/2018 12:42:18] "GET /patroni HTTP/1.1" 200 -
2018-11-26 12:42:26,505 DEBUG: API thread: 10.0.0.11 - - [26/Nov/2018 12:42:26] "GET /master HTTP/1.1" 200 -
2018-11-26 12:42:26,606 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:26,606 DEBUG: Resetting dropped connection: localhost
2018-11-26 12:42:26,609 DEBUG: http://localhost:8500 "GET /v1/kv/patroni/postgres-main/?recurse=1 HTTP/1.1" 200 None
2018-11-26 12:42:26,611 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:26,619 DEBUG: http://localhost:8500 "PUT /v1/kv/patroni/postgres-main/members/postgres1?acquire=16492f43-c2d6-5307-432f-e32d6f7bcbd0 HTTP/1.1" 500 100
2018-11-26 12:42:26,619 ERROR: touch_member
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/consul.py", line 356, in touch_member
    self._client.kv.put(self.member_path, json.dumps(data, separators=(',', ':')), **args)
  File "/usr/local/lib/python3.5/dist-packages/consul/base.py", line 621, in put
    CB.json(), '/v1/kv/%s' % key, params=params, data=value)
  File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/consul.py", line 105, in wrapper
    return callback(self.response(self.http.request(method.upper(), self.uri(path, params), **kwargs)))
  File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/consul.py", line 76, in response
    raise ConsulInternalError(msg)
patroni.dcs.consul.ConsulInternalError: 500 rpc error making call: rpc error making call: invalid session "16492f43-c2d6-5307-432f-e32d6f7bcbd0"
2018-11-26 12:42:26,621 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:26,630 DEBUG: http://localhost:8500 "PUT /v1/kv/patroni/postgres-main/leader?acquire=16492f43-c2d6-5307-432f-e32d6f7bcbd0 HTTP/1.1" 500 100
2018-11-26 12:42:27,342 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:27,350 DEBUG: http://localhost:8500 "PUT /v1/kv/patroni/postgres-main/leader?acquire=16492f43-c2d6-5307-432f-e32d6f7bcbd0 HTTP/1.1" 500 77
2018-11-26 12:42:28,151 DEBUG: API thread: 127.0.0.1 - - [26/Nov/2018 12:42:28] "GET / HTTP/1.1" 503 -
2018-11-26 12:42:28,172 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:28,182 DEBUG: http://localhost:8500 "PUT /v1/kv/patroni/postgres-main/leader?acquire=16492f43-c2d6-5307-432f-e32d6f7bcbd0 HTTP/1.1" 500 100
2018-11-26 12:42:28,719 DEBUG: API thread: 10.0.0.12 - - [26/Nov/2018 12:42:28] "GET /patroni HTTP/1.1" 200 -
2018-11-26 12:42:29,223 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:29,232 DEBUG: http://localhost:8500 "PUT /v1/kv/patroni/postgres-main/leader?acquire=16492f43-c2d6-5307-432f-e32d6f7bcbd0 HTTP/1.1" 500 100
2018-11-26 12:42:30,444 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:30,451 DEBUG: http://localhost:8500 "PUT /v1/kv/patroni/postgres-main/leader?acquire=16492f43-c2d6-5307-432f-e32d6f7bcbd0 HTTP/1.1" 500 77
2018-11-26 12:42:31,507 DEBUG: API thread: 10.0.0.11 - - [26/Nov/2018 12:42:31] "GET /master HTTP/1.1" 503 -
2018-11-26 12:42:31,773 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:31,781 DEBUG: http://localhost:8500 "PUT /v1/kv/patroni/postgres-main/leader?acquire=16492f43-c2d6-5307-432f-e32d6f7bcbd0 HTTP/1.1" 500 100
2018-11-26 12:42:33,254 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:33,262 DEBUG: http://localhost:8500 "PUT /v1/kv/patroni/postgres-main/leader?acquire=16492f43-c2d6-5307-432f-e32d6f7bcbd0 HTTP/1.1" 500 100
2018-11-26 12:42:34,815 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:34,822 DEBUG: http://localhost:8500 "PUT /v1/kv/patroni/postgres-main/leader?acquire=16492f43-c2d6-5307-432f-e32d6f7bcbd0 HTTP/1.1" 500 77
2018-11-26 12:42:36,384 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:36,395 DEBUG: http://localhost:8500 "PUT /v1/kv/patroni/postgres-main/leader?acquire=16492f43-c2d6-5307-432f-e32d6f7bcbd0 HTTP/1.1" 500 100
2018-11-26 12:42:36,396 INFO: Could not take out TTL lock
2018-11-26 12:42:36,396 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:36,398 DEBUG: http://localhost:8500 "GET /v1/kv/patroni/postgres-main/?recurse=1 HTTP/1.1" 200 None
2018-11-26 12:42:36,431 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:36,434 DEBUG: http://localhost:8500 "GET /v1/kv/patroni/postgres-main/?recurse=1 HTTP/1.1" 200 None
2018-11-26 12:42:36,435 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:36,437 DEBUG: http://localhost:8500 "PUT /v1/session/renew/16492f43-c2d6-5307-432f-e32d6f7bcbd0 HTTP/1.1" 404 59
2018-11-26 12:42:36,438 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:36,446 DEBUG: http://localhost:8500 "PUT /v1/session/create HTTP/1.1" 200 45
2018-11-26 12:42:36,446 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:36,454 DEBUG: http://localhost:8500 "PUT /v1/kv/patroni/postgres-main/members/postgres1?acquire=1d2ce8cc-f91e-f49e-a52d-847bcc999d83 HTTP/1.1" 200 4
2018-11-26 12:42:36,454 INFO: Deregister service postgres-main/postgres1
2018-11-26 12:42:36,454 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:36,470 DEBUG: http://localhost:8500 "PUT /v1/agent/service/deregister/postgres-main/postgres1 HTTP/1.1" 200 0
2018-11-26 12:42:36,471 INFO: demoted self after trying and failing to obtain lock
2018-11-26 12:42:36,471 INFO: closed patroni connection to the postgresql cluster
2018-11-26 12:42:36,476 DEBUG: Starting postgres: /usr/lib/postgresql/10/bin/postgres -D /data/postgresql --config-file=/data/postgresql/postgresql.conf --max_wal_senders=10 --listen_addresses=0.0.0.0 --max_prepared_transactions=0 --wal_level=replica --max_locks_per_transaction=64 --max_worker_processes=8 --port=5432 --max_connections=400 --track_commit_timestamp=off --cluster_name=postgres-main --hot_standby=on --wal_log_hints=on --max_replication_slots=10
2018-11-26 12:42:36,517 INFO: postmaster pid=32121
localhost:5432 - rejecting connections
localhost:5432 - rejecting connections
2018-11-26 12:42:36,608 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:36,613 DEBUG: http://localhost:8500 "GET /v1/kv/patroni/postgres-main/?recurse=1 HTTP/1.1" 200 None
2018-11-26 12:42:36,615 INFO: Lock owner: None; I am postgres1
2018-11-26 12:42:36,615 INFO: not healthy enough for leader race
2018-11-26 12:42:36,616 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:36,626 DEBUG: http://localhost:8500 "PUT /v1/kv/patroni/postgres-main/members/postgres1?acquire=1d2ce8cc-f91e-f49e-a52d-847bcc999d83 HTTP/1.1" 200 4
2018-11-26 12:42:36,626 INFO: starting after demotion in progress
localhost:5432 - accepting connections
2018-11-26 12:42:37,617 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:37,620 DEBUG: http://localhost:8500 "GET /v1/kv/patroni/postgres-main/?recurse=1 HTTP/1.1" 200 None
2018-11-26 12:42:37,621 INFO: establishing a new patroni connection to the postgres cluster
2018-11-26 12:42:37,642 INFO: Got response from postgres2 http://10.0.0.12:8008/patroni: b'{"postmaster_start_time": "2018-11-26 12:42:18.679 UTC", "server_version": 100005, "tags": {"nosync": true}, "patroni": {"version": "1.5.2", "scope": "postgres-main"}, "pending_restart": true, "database_system_identifier": "6596624351783773772", "state": "running", "timeline": 39, "role": "replica", "cluster_unlocked": true, "xlog": {"replayed_location": 52430424656, "received_location": 52430424656, "replayed_timestamp": "2018-11-26 12:41:29.643 UTC", "paused": false}}'
2018-11-26 12:42:37,731 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:37,740 DEBUG: http://localhost:8500 "PUT /v1/kv/patroni/postgres-main/leader?acquire=1d2ce8cc-f91e-f49e-a52d-847bcc999d83 HTTP/1.1" 200 4
2018-11-26 12:42:37,741 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:37,743 DEBUG: http://localhost:8500 "GET /v1/kv/patroni/postgres-main/?recurse=1 HTTP/1.1" 200 None
2018-11-26 12:42:37,750 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:37,758 DEBUG: http://localhost:8500 "PUT /v1/kv/patroni/postgres-main/members/postgres1?acquire=1d2ce8cc-f91e-f49e-a52d-847bcc999d83 HTTP/1.1" 200 4
2018-11-26 12:42:37,759 INFO: Register service postgres-main, params {'address': '10.0.0.11', 'tags': ['replica'], 'service_id': 'postgres-main/postgres1', 'port': 5432, 'check': {'interval': '5s', 'DeregisterCriticalServiceAfter': 150.0, 'http': 'http://10.0.0.11:8008/replica'}}
2018-11-26 12:42:37,759 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:37,775 DEBUG: http://localhost:8500 "PUT /v1/agent/service/register HTTP/1.1" 200 0
2018-11-26 12:42:37,775 INFO: promoted self to leader by acquiring session lock
server promoting
2018-11-26 12:42:37,778 INFO: cleared rewind state after becoming the leader
2018-11-26 12:42:37,858 DEBUG: API thread: 10.0.0.11 - - [26/Nov/2018 12:42:37] "GET /replica HTTP/1.1" 503 -
2018-11-26 12:42:38,785 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:38,789 DEBUG: http://localhost:8500 "GET /v1/kv/patroni/postgres-main/?recurse=1 HTTP/1.1" 200 None
2018-11-26 12:42:38,790 INFO: Lock owner: postgres1; I am postgres1
2018-11-26 12:42:38,791 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:38,793 DEBUG: http://localhost:8500 "PUT /v1/session/renew/1d2ce8cc-f91e-f49e-a52d-847bcc999d83 HTTP/1.1" 200 269
2018-11-26 12:42:38,794 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:38,802 DEBUG: http://localhost:8500 "PUT /v1/kv/patroni/postgres-main/optime/leader HTTP/1.1" 200 4
2018-11-26 12:42:38,803 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:38,811 DEBUG: http://localhost:8500 "PUT /v1/kv/patroni/postgres-main/history HTTP/1.1" 200 4
2018-11-26 12:42:38,812 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:38,820 DEBUG: http://localhost:8500 "PUT /v1/kv/patroni/postgres-main/members/postgres1?acquire=1d2ce8cc-f91e-f49e-a52d-847bcc999d83 HTTP/1.1" 200 4
2018-11-26 12:42:38,821 INFO: Register service postgres-main, params {'address': '10.0.0.11', 'tags': ['master'], 'service_id': 'postgres-main/postgres1', 'port': 5432, 'check': {'interval': '5s', 'DeregisterCriticalServiceAfter': 150.0, 'http': 'http://10.0.0.11:8008/master'}}
2018-11-26 12:42:38,821 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2018-11-26 12:42:38,835 DEBUG: http://localhost:8500 "PUT /v1/agent/service/register HTTP/1.1" 200 0
2018-11-26 12:42:38,836 INFO: no action.  i am the leader with the lock
```

**Comment by CyberDem0n** [comment]
Could you please apply https://github.com/zalando/patroni/pull/880 and try it one more time?

**Comment by shamil** [comment]
@CyberDem0n seems to be fixed, I just some warning logs, but everything works as supposed:

Thanks a lot, waiting for new release :pray: 

**On master**

```
2018-11-26 16:18:03,726 WARNING: Could not register service: unknown role type promoted
2018-11-26 16:18:03,745 INFO: Register service postgres-main, params {'port': 5432, 'address': '10.0.0.11, 'service_id': 'postgres-main/postgres0', 'tags': ['master'], 'check': {'http': 'http://10.0.0.11:8008/master', 'DeregisterCriticalServiceAfter': 150.0, 'interval': '5s'}}
```

**And on secondary**

```
2018-11-26 16:17:29,212 INFO: Lock owner: postgres0; I am postgres1
2018-11-26 16:17:29,212 INFO: does not have lock
2018-11-26 16:17:29,223 INFO: no action.  i am a secondary and i am following a leader
2018-11-26 16:17:39,105 INFO: Lock owner: postgres0; I am postgres1
2018-11-26 16:17:39,105 INFO: does not have lock
2018-11-26 16:17:39,106 INFO: no action.  i am a secondary and i am following a leader
2018-11-26 16:17:49,068 INFO: Lock owner: postgres0; I am postgres1
2018-11-26 16:17:49,068 INFO: does not have lock
2018-11-26 16:17:49,080 INFO: no action.  i am a secondary and i am following a leader
2018-11-26 16:17:56,988 INFO: Got response from postgres0 http://10.0.0.11:8008/patroni: b'{"replication": [{"sync_state": "async", "sync_priority": 0, "state": "streaming", "usename": "repl_user", "application_name": "postgres1", "client_addr": "10.101.32.205"}], "tags": {"nosync": true}, "postmaster_start_time": "2018-11-26 16:16:49.235 UTC", "timeline": 42, "database_system_identifier": "6596624351783773772", "role": "master", "server_version": 100005, "xlog": {"location": 52430770376}, "state": "running", "patroni": {"version": "1.5.2", "scope": "postgres-main"}, "cluster_unlocked": false, "pending_restart": true}'
2018-11-26 16:17:57,082 WARNING: Master (postgres0) is still alive
2018-11-26 16:17:57,094 INFO: following a different leader because i am not the healthiest node
2018-11-26 16:17:57,231 INFO: closed patroni connection to the postgresql cluster
2018-11-26 16:17:57,279 INFO: postmaster pid=22087
localhost:5432 - accepting connections
localhost:5432 - accepting connections
2018-11-26 16:17:57,356 INFO: establishing a new patroni connection to the postgres cluster
2018-11-26 16:17:57,371 INFO: Got response from postgres0 http://10.0.0.11:8008/patroni: b'{"patroni": {"version": "1.5.2", "scope": "postgres-main"}, "database_system_identifier": "6596624351783773772", "tags": {"nosync": true}, "role": "master", "postmaster_start_time": "2018-11-26 16:16:49.235 UTC", "state": "running", "pending_restart": true, "xlog": {"location": 52430770376}, "timeline": 42, "cluster_unlocked": false, "server_version": 100005}'
2018-11-26 16:17:57,467 WARNING: Master (postgres0) is still alive
2018-11-26 16:17:57,489 INFO: following a different leader because i am not the healthiest node
2018-11-26 16:18:07,355 INFO: Lock owner: postgres0; I am postgres1
2018-11-26 16:18:07,355 INFO: does not have lock
2018-11-26 16:18:07,366 INFO: no action.  i am a secondary and i am following a leader
2018-11-26 16:18:07,502 INFO: closed patroni connection to the postgresql cluster
2018-11-26 16:18:07,548 INFO: postmaster pid=22114
localhost:5432 - accepting connections
localhost:5432 - accepting connections
2018-11-26 16:18:07,627 INFO: Lock owner: postgres0; I am postgres1
2018-11-26 16:18:07,627 INFO: does not have lock
2018-11-26 16:18:07,628 INFO: establishing a new patroni connection to the postgres cluster
2018-11-26 16:18:07,649 INFO: no action.  i am a secondary and i am following a leader
2018-11-26 16:18:17,808 INFO: Lock owner: postgres0; I am postgres1
2018-11-26 16:18:17,808 INFO: does not have lock
```

**Comment by shamil** [comment]
@CyberDem0n do you need me to check anything else or #880 is the solution?
