### ISSUE TITLE
Please add to log info when define(used) twice pg_hba that first pg_hba overwrite second pg_hba.

### ISSUE THREAD

**Issue by patsevanton** [zalando/patroni#881]
Hello!
I try write patroni 

```yaml
scope: main
namespace: /service/
name: node1

restapi:
  listen: 0.0.0.0:8008
  connect_address: 192.168.88.235:8008

etcd:
  hosts: 127.0.0.1:2379
  protocol: http

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 100
        max_locks_per_transaction: 64
        max_worker_processes: 8
        max_prepared_transactions: 0
        wal_level: replica
        wal_log_hints: on
        track_commit_timestamp: off
        max_wal_senders: 10
        max_replication_slots: 10
        wal_keep_segments: 0
  initdb:
    - encoding: UTF8
    - data-checksums
  pg_hba:
    - host replication replicator 192.168.88.235/32 md5
    - host replication replicator 192.168.88.88/32 md5
    - host replication replicator 192.168.88.87/32 md5
  users:
    postgres:
      password: xxx
    replicator:
      password: xxx
      options:
        - replication

postgresql:
  use_unix_socket: true
  listen: 0.0.0.0:5432
  connect_address: 192.168.88.235:5432
  data_dir: /var/lib/postgresql/10/main
  bin_dir: /usr/lib/postgresql/10/bin
  config_dir: /var/lib/postgresql/10/main
  pgpass: /var/lib/postgresql/.pgpass
  authentication:
    superuser:
      username: postgres
      password: xxx
    replication:
      username: replicator
      password: xxx
  create_replica_method:
    - basebackup
  parameters:
    unix_socket_directories: /var/run/postgresql
  pg_hba:
    - host test1 test2 192.168.1.1/32 md5
  pg_ctl_timeout: 60
  use_pg_rewind: true
  pg_rewind:
    username: postgres
    password: xxx
  remove_data_directory_on_rewind_failure: false

watchdog:
  mode: automatic
  device: /dev/watchdog
  safety_margin: 5

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

After create cluster i get error

```
2018-11-27 11:32:34,456 INFO: establishing a new patroni connection to the postgres cluster
2018-11-27 11:32:34,799 INFO: establishing a new patroni connection to the postgres cluster
/var/run/postgresql:5432 - принимает подключения
2018-11-27 11:32:34,822 INFO: establishing a new patroni connection to the postgres cluster
2018-11-27 11:32:34,827 ERROR: Exception when changing replication slots
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/patroni/postgresql.py", line 1571, in sync_replication_slots
    self.load_replication_slots()
  File "/usr/local/lib/python2.7/dist-packages/patroni/postgresql.py", line 1540, in load_replication_slots
    cursor = self._query('SELECT slot_name, slot_type, plugin, database FROM pg_catalog.pg_replication_slots')
  File "/usr/local/lib/python2.7/dist-packages/patroni/postgresql.py", line 491, in _query
    raise PostgresConnectionException('connection problems')
PostgresConnectionException: 'connection problems'
2018-11-27 11:32:34,835 INFO: Error communicating with PostgreSQL. Will try again later
^C2018-11-27 11:32:40,804 INFO: Lock owner: None; I am node1
```

```
cat /var/lib/postgresql/10/main/pg_hba.conf
# Do not edit this file manually!
# It will be overwritten by Patroni!
host test1 test2 192.168.1.1/32 md5
```

Please add to log info when define(used) twice pg_hba that  first pg_hba overwrite  second pg_hba.

For, example:
```
Attention, Caution!
After restart patroni bootstrap.pg_hba dont used - used postrgesql.pg_hba.
```

**Comment by CyberDem0n** [comment]
This is an open-source project, feel free to open a PR.

**Comment by patsevanton** [comment]
Ok. I will try later.
