### ISSUE TITLE
Having some Python exceptions. But the cluster is functional.

### ISSUE THREAD

**Issue by srimaln91** [zalando/patroni#900]
I'm using Patroni version 1.5.3 and continously getting some Python exceptions. But the cluster works fine. I have added some logs below.

```text
Dec 20 13:01:13 node1 patroni: 2018-12-20 13:01:13,989 INFO: Lock owner: pg-node3; I am pg-node1
Dec 20 13:01:13 node1 patroni: 2018-12-20 13:01:13,989 INFO: does not have lock
Dec 20 13:01:14 node1 patroni: 2018-12-20 13:01:14,006 INFO: no action.  i am a secondary and i am following a leader
Dec 20 13:01:14 node1 patroni: Traceback (most recent call last):
Dec 20 13:01:14 node1 patroni: File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
Dec 20 13:01:14 node1 patroni: self.finish_request(request, client_address)
Dec 20 13:01:14 node1 patroni: File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
Dec 20 13:01:14 node1 patroni: self.RequestHandlerClass(request, client_address, self)
Dec 20 13:01:14 node1 patroni: File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
Dec 20 13:01:14 node1 patroni: self.finish()
Dec 20 13:01:14 node1 patroni: File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
Dec 20 13:01:14 node1 patroni: self.wfile.close()
Dec 20 13:01:14 node1 patroni: File "/usr/lib64/python2.7/socket.py", line 279, in close
Dec 20 13:01:14 node1 patroni: self.flush()
Dec 20 13:01:14 node1 patroni: File "/usr/lib64/python2.7/socket.py", line 303, in flush
Dec 20 13:01:14 node1 patroni: self._sock.sendall(view[write_offset:write_offset+buffer_size])
Dec 20 13:01:14 node1 patroni: error: [Errno 32] Broken pipe
Dec 20 13:01:17 node1 patroni: Traceback (most recent call last):
Dec 20 13:01:17 node1 patroni: File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
Dec 20 13:01:17 node1 patroni: self.finish_request(request, client_address)
Dec 20 13:01:17 node1 patroni: File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
Dec 20 13:01:17 node1 patroni: self.RequestHandlerClass(request, client_address, self)
Dec 20 13:01:17 node1 patroni: File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
Dec 20 13:01:17 node1 patroni: self.finish()
Dec 20 13:01:17 node1 patroni: File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
Dec 20 13:01:17 node1 patroni: self.wfile.close()
Dec 20 13:01:17 node1 patroni: File "/usr/lib64/python2.7/socket.py", line 279, in close
Dec 20 13:01:17 node1 patroni: self.flush()
Dec 20 13:01:17 node1 patroni: File "/usr/lib64/python2.7/socket.py", line 303, in flush
Dec 20 13:01:17 node1 patroni: self._sock.sendall(view[write_offset:write_offset+buffer_size])
Dec 20 13:01:17 node1 patroni: error: [Errno 32] Broken pipe
Dec 20 13:01:19 node1 patroni: -------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing of request from ('192.168.56.108', 35114)
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing of request from ('192.168.56.108', 35118)
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing of request from ('192.168.56.108', 35130)
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing of request from ('192.168.56.108', 35166)
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing of request from ('192.168.56.108', 35178)
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing of request from ('192.168.56.108', 35198)
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing of request from ('192.168.56.108', 35210)
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing of request from ('192.168.56.108', 35222)
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing of request from ('192.168.56.108', 35238)
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing of request from ('192.168.56.108', 35262)
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing of request from ('192.168.56.108', 35294)
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing of request from ('192.168.56.108', 35298)
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing of request from ('192.168.56.108', 35318)
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing of request from ('192.168.56.108', 35330)
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing of request from ('192.168.56.108', 35358)
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing of request from ('192.168.56.108', 35370)
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing of request from ('192.168.56.108', 35378)
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing of request from ('192.168.56.108', 35414)
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing of request from ('192.168.56.108', 35418)
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing of request from ('192.168.56.108', 35430)
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing of request from ('192.168.56.108', 35454)
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing of request from ('192.168.56.108', 35464)
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing of request from ('192.168.56.108', 35486)
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing of request from ('192.168.56.108', 35502)
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing of request from ('192.168.56.108', 35526)
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: ----------------------------------------
Dec 20 13:01:19 node1 patroni: Exception happened during processing ofTraceback (most recent call last):
Dec 20 13:01:19 node1 patroni: File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
Dec 20 13:01:19 node1 patroni: self.finish_request(request, client_address)
Dec 20 13:01:19 node1 patroni: File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
Dec 20 13:01:19 node1 patroni: self.RequestHandlerClass(request, client_address, self)
Dec 20 13:01:19 node1 patroni: File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
Dec 20 13:01:19 node1 patroni: self.finish()
Dec 20 13:01:19 node1 patroni: File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
Dec 20 13:01:19 node1 patroni: self.wfile.close()
Dec 20 13:01:19 node1 patroni: File "/usr/lib64/python2.7/socket.py", line 279, in close
Dec 20 13:01:19 node1 patroni: self.flush()
Dec 20 13:01:19 node1 patroni: File "/usr/lib64/python2.7/socket.py", line 303, in flush
Dec 20 13:01:19 node1 patroni: self._sock.sendall(view[write_offset:write_offset+buffer_size])
Dec 20 13:01:19 node1 patroni: error: [Errno 32] Broken pipe
Dec 20 13:01:23 node1 patroni: 2018-12-20 13:01:23,986 INFO: Lock owner: pg-node3; I am pg-node1
Dec 20 13:01:23 node1 patroni: 2018-12-20 13:01:23,986 INFO: does not have lock
Dec 20 13:01:24 node1 patroni: 2018-12-20 13:01:24,000 INFO: no action.  i am a secondary and i am following a leader
Dec 20 13:01:29 node1 patroni: Traceback (most recent call last):
Dec 20 13:01:29 node1 patroni: File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
Dec 20 13:01:29 node1 patroni: self.finish_request(request, client_address)
Dec 20 13:01:29 node1 patroni: File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
Dec 20 13:01:29 node1 patroni: self.RequestHandlerClass(request, client_address, self)
Dec 20 13:01:29 node1 patroni: File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
Dec 20 13:01:29 node1 patroni: self.finish()
Dec 20 13:01:29 node1 patroni: File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
Dec 20 13:01:29 node1 patroni: self.wfile.close()
Dec 20 13:01:29 node1 patroni: File "/usr/lib64/python2.7/socket.py", line 279, in close
Dec 20 13:01:29 node1 patroni: self.flush()
Dec 20 13:01:29 node1 patroni: File "/usr/lib64/python2.7/socket.py", line 303, in flush
Dec 20 13:01:29 node1 patroni: self._sock.sendall(view[write_offset:write_offset+buffer_size])
Dec 20 13:01:29 node1 patroni: error: [Errno 32] Broken pipe
Dec 20 13:01:34 node1 patroni: 2018-12-20 13:01:34,007 INFO: Lock owner: pg-node3; I am pg-node1
Dec 20 13:01:34 node1 patroni: 2018-12-20 13:01:34,007 INFO: does not have lock
Dec 20 13:01:34 node1 patroni: 2018-12-20 13:01:34,017 INFO: no action.  i am a secondary and i am following a leader


```

**Comment by CyberDem0n** [comment]
They come from rest api health-check.
Could you share haproxy configuration?
What version of haproxy do you use?

**Comment by srimaln91** [comment]
Yes. I have been using Haproxy in front of the server stack. Haproxy uses a GET request to get the status of nodes. I have replaced that GET request with OPTIONS request. Now the issue is fixed.

**Comment by CyberDem0n** [comment]
From one side you are kind of right, but from another side, the problem comes from the fact that HAProxy is closing a connection too early (when it just receive http response code).
Patroni uses python `HTTPServer` component to run rest api, and the exceptions are logged from there. We can make such error messages a less scary, but it will also make it harder to debug problems...

**Comment by srimaln91** [comment]
I suggest that we can have an option to turn on/off debug mode.
