### ISSUE TITLE
[GKE] wal-e enable => replicat nok

### ISSUE THREAD

**Issue by pmpetit** [zalando/patroni#965]
Hello,
by enabling wal-e backup with : 
image:
  repository: registry.opensource.zalan.do/acid/spilo-10
  tag: 1.4-p16

walE:
  enable: true
  scheduleCronJob: 0 * * * *
  retainBackups: 2
  s3Bucket:
  gcsBucket: test-patroni-backup
  kubernetesSecret: pgs-bucket_

here are the logs on the replicat : 
decompressing spilo image...
2019-02-06 14:27:44,382 - bootstrapping - INFO - Figuring out my environment (Google? AWS? Openstack? Local?)
2019-02-06 14:27:44,394 - bootstrapping - INFO - Looks like your running google
2019-02-06 14:27:44,413 - bootstrapping - INFO - Configuring patronictl
2019-02-06 14:27:44,415 - bootstrapping - INFO - Writing to file /home/postgres/.config/patroni/patronictl.yaml
2019-02-06 14:27:44,415 - bootstrapping - INFO - Configuring ldap
2019-02-06 14:27:44,415 - bootstrapping - INFO - No LDAP_URL was specified, skipping LDAP configuration
2019-02-06 14:27:44,415 - bootstrapping - INFO - Configuring certificate
2019-02-06 14:27:44,416 - bootstrapping - INFO - Generating ssl certificate
2019-02-06 14:27:44,526 - bootstrapping - INFO - Configuring pam-oauth2
2019-02-06 14:27:44,527 - bootstrapping - INFO - No PAM_OAUTH2 configuration was specified, skipping
2019-02-06 14:27:44,527 - bootstrapping - INFO - Configuring pgbouncer
2019-02-06 14:27:44,527 - bootstrapping - INFO - No PGBOUNCER_CONFIGURATION was specified, skipping
2019-02-06 14:27:44,527 - bootstrapping - INFO - Configuring bootstrap
2019-02-06 14:27:44,527 - bootstrapping - INFO - Configuring patroni
2019-02-06 14:27:44,537 - bootstrapping - INFO - Writing to file /home/postgres/postgres.yml
2019-02-06 14:27:44,537 - bootstrapping - INFO - Configuring wal-e
2019-02-06 14:27:44,537 - bootstrapping - INFO - Writing to file /home/postgres/etc/wal-e.d/env/WALE_GS_PREFIX
2019-02-06 14:27:44,537 - bootstrapping - INFO - Writing to file /home/postgres/etc/wal-e.d/env/GOOGLE_APPLICATION_CREDENTIALS
2019-02-06 14:27:44,538 - bootstrapping - INFO - Writing to file /home/postgres/etc/wal-e.d/env/TMPDIR
2019-02-06 14:27:44,538 - bootstrapping - INFO - Configuring crontab
2019-02-06 14:27:44,851 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2019-02-06 14:27:44,852 INFO Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
2019-02-06 14:27:44,852 INFO Included extra file "/etc/supervisor/conf.d/patroni.conf" during parsing
2019-02-06 14:27:44,852 INFO Included extra file "/etc/supervisor/conf.d/pgq.conf" during parsing
2019-02-06 14:27:44,860 INFO RPC interface 'supervisor' initialized
2019-02-06 14:27:44,860 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2019-02-06 14:27:44,860 INFO supervisord started with pid 1
2019-02-06 14:27:45,862 INFO spawned: 'cron' with pid 42
2019-02-06 14:27:45,865 INFO spawned: 'patroni' with pid 43
2019-02-06 14:27:45,868 INFO spawned: 'pgq' with pid 44
2019-02-06 14:27:46,693 INFO: Lock owner: None; I am patroni-1
2019-02-06 14:27:46,729 INFO: trying to bootstrap (without leader)
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-list".
        STRUCTURED: time=2019-02-06T14:27:47.378355-00 pid=57
2019-02-06 14:27:47,378 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-02-06 14:27:47,379 INFO success: patroni entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-02-06 14:27:47,379 INFO success: pgq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/usr/local/lib/python3.5/dist-packages/wal_e/cmd.py", line 627, in main
            backup_cxt.backup_list(query=args.QUERY, detail=args.detail)
          File "/usr/local/lib/python3.5/dist-packages/wal_e/operator/backup.py", line 53, in backup_list
            bl = self._backup_list(detail)
          File "/usr/local/lib/python3.5/dist-packages/wal_e/operator/backup.py", line 426, in _backup_list
            conn = self.new_connection()
          File "/usr/local/lib/python3.5/dist-packages/wal_e/operator/backup.py", line 44, in new_connection
            return self.cinfo.connect(self.creds)
          File "/usr/local/lib/python3.5/dist-packages/wal_e/blobstore/gs/calling_format.py", line 13, in connect
            credentials, project = google.auth.default()
          File "/usr/local/lib/python3.5/dist-packages/google/auth/_default.py", line 287, in default
            credentials, project_id = checker()
          File "/usr/local/lib/python3.5/dist-packages/google/auth/_default.py", line 148, in _get_explicit_environ_credentials
            os.environ[environment_vars.CREDENTIALS])
          File "/usr/local/lib/python3.5/dist-packages/google/auth/_default.py", line 67, in _load_credentials_from_file
            'File {} was not found.'.format(filename))
        google.auth.exceptions.DefaultCredentialsError: File /etc/credentials/pgs-bucket.json was not found.

        STRUCTURED: time=2019-02-06T14:27:47.624355-00 pid=57
2019-02-06 14:27:47,697 ERROR: could not query wal-e latest backup
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/patroni/scripts/wale_restore.py", line 170, in should_use_s3_to_create_replica
    wale_output = subprocess.check_output(cmd)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout_ 
(...)

for your inforamtion, in the the gcp bucket 'test-patroni-backup', the folder name is 
"acid-minimal-cluster", but my release name is "patroni" 
![image](https://user-images.githubusercontent.com/4059185/52348655-2ab25e80-2a25-11e9-92d1-b321e8d93c05.png)

**Comment by pmpetit** [comment]
the name of the secret created is pgs-bucket, but in the pod there is only the json file we used to create the secret : 
 kubectl create secret generic pgs-bucket --from-file ~/tmp/file-secret-74bbfei4288b7.json
in the pod :
"/etc/credentials/file-secret-74bbfe4288b7.json"

**Comment by pmpetit** [comment]
mess with secret creation, sorry
