### ISSUE TITLE
Confused by SETTINGS.rst 

### ISSUE THREAD

**Issue by IJOL** [zalando/patroni#975]
Hola a todos:

I'm a bit confused by SETTINGS.rst, i need to set remove_data_directory_on_diverged_timelines to true,  but i dont know where in the yml should i put it, under dcs/postgres  or where? given that i use docker i should modify entrypoint.sh to suit our needs?

Thnksd in advance for any insight..

Saludos,
Ignacio J.. Ortegs

**Comment by CyberDem0n** [comment]
It depends on what you want.
1. For an existing cluster one could use `patronictl edit-config` to change it globally.
2. Another option would be to modify patroni.yaml and put the option under `postgresql` section.
3. `bootstrap.dcs` works only when you create an absolutely new cluster. Patroni will put the content of `bootstrap.dcs` section into the `/config` key in DCS. Later you can work with it only with `patronictl edit-config` (see the first option).

**Comment by IJOL** [comment]
Thanks !!

I've tried first opetion, after some minor modifications to dockerfile, I can edit but after saving in nano y get :
postgres_patroni-162yl0jv8osxycpbzy2zmlvfq:/# patronictl edit-config 
Traceback (most recent call last):
  File "/usr/local/bin/patronictl", line 5, in <module>
    ctl(None)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/patroni/ctl.py", line 1013, in edit_config
    show_diff(before_editing, after_editing)
  File "/patroni/ctl.py", line 873, in show_diff
    cdiff.markup_to_pager(cdiff.PatchStream(buf), opts)
  File "/usr/local/lib/python2.7/dist-packages/cdiff.py", line 640, in markup_to_pager
    pager_cmd, stdin=subprocess.PIPE, stdout=sys.stdout)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by IJOL** [comment]
Solved myself, dockerfile need some tweaks, tyo get nano, EDITOR set and less, but after installing everything worked nicely. I will make a pull request with the needed changes to dockerfile..

Thanks,
